var EnMonth=["Jan","Feb","Mar","Apr","May","Jun","Jul","Aug","Spt","Oct","Nov","Dec"];
var EnDay=["Monday","Tuesday","Wednesday","Thursday","Friday","Saturday","Sunday"];
var CnDay=["星期一","星期二","星期三","星期四","星期五","星期六","星期日"];

var slidepics=[
{ "img":"images/20150512_xdsg.jpg","info":["01 I want to waste time with you","01 比如低头看鱼 比如把茶杯留在桌子上离开"]},
{ "img":"images/chundelinzhong.jpg","info":["02 Dying in Spring","02 可以睡觉了哟孩子们 我把悲伤喜欢过了"]},
{ "img":"images/yiqie.jpg","info":["03 All","03 一切都是命运 一切都是烟云"]},
];

var hometext=[
{"title":["Sui Sui Nian","碎碎念"],"page":["",""],"info":["A kitten is a juvenile cat. After being born, kittens are totally dependent on their mother for survival and they do not normally open their eyes until after seven to ten days. ","“你看到的我，是在走过很多风景后，发现最美的是平常。懂得人生终将告别后，用一期一会去遇见。所以你觉得明亮温暖，那是我的方式，来对待这个世界。”"]},
{"title":["Biography","简介"],"page":["",""],"info":["Born in China Shandong. Peking University master’s degree after graduation coming to Japan, up through the work at the Nippon Design Center, Inc. Hara Design Institute. She met with Shuntaro Tanikawa, Kensaku Tanikawa, Tien Yuen, Shine Yukawa to start working as a singer-songwriter based in Tokyo and Beijing.","程璧，旅日音乐人，词曲创作者。以一把古典吉他进行音乐创作，为诗歌谱曲。嗓音“又优美又沉静，又清亮又崭新”，被称为“离诗歌最近的声音”。发表独立音乐专辑《晴日共剪窗》《诗遇上歌》。曾工作于东京NDC原研哉设计研究所，独立从事艺术创作与写作。"]},
{"title":["THEN!","然后"],"page":["",""],"info":["A kitten is a juvenile cat. After being born, kittens are totally dependent on their mother for survival and they do not normally open their eyes until after seven to ten days. ","面璧大学好多小伙伴要看璧从前主页， 都到紫月这儿来问。然后..."]},
];
var home= { "slidepics":slidepics,"hometext":hometext,};

var waterpics=[
{ "img":"images/2015053001.jpg","date":"5/30/2015","info":["Miao miao miao miao miao miao","程璧x荔枝FM “我想和你虚度时光”全国剧场音乐会 成都站现场"]},
{ "img":"images/2014102601.jpg","date":"10/26/2014","info":["Miao miao miao miao miao miao","勇敢的告别，骄傲的生长。"]},
{ "img":"images/2015053001.jpg","date":"5/30/2015","info":["Miao miao miao miao miao miao","程璧x荔枝FM “我想和你虚度时光”全国剧场音乐会 成都站现场"]},
{ "img":"images/2014102601.jpg","date":"10/26/2014","info":["Miao miao miao miao miao miao","勇敢的告别，骄傲的生长。"]},
{ "img":"images/2015053001.jpg","date":"5/30/2015","info":["Miao miao miao miao miao miao","程璧x荔枝FM “我想和你虚度时光”全国剧场音乐会 成都站现场"]},
{ "img":"images/2014102601.jpg","date":"10/26/2014","info":["Miao miao miao miao miao miao","勇敢的告别，骄傲的生长。"]},
];	
var photos=waterpics;

var news=[
{ "d":"2012/09/16 19:30:00","page":"","title":["北京 69cafe","北京 69cafe"],"info":["A kitten is a juvenile cat. After being born, kittens are totally dependent on their mother for survival and they do not normally open their eyes until after seven to ten days. After about two weeks, kittens quickly develop and begin to explore the world outside the nest. After a further three to four weeks, they begin to eat solid food and grow adult teeth. Domestic kittens are highly social animals and usually enjoy human companionship.","这个设计是在这张原创音乐专辑录制完成后，由我自己来把握整体设计风格，素材与数据制版与清华美院高翔宇一起完成，印刷交付陆玖音乐咖啡馆的蘑菇老板兼资深设计师展旭。我一直很喜欢Vintage复古风，我的专辑唯一的伴奏乐器也是一把传统木构造兼尼龙弦的古典吉他，而且这张专辑的曲风，也都是有着淡淡怀旧的情怀。专辑名字直接以《晴日共剪窗》这首歌来命名，我很希望能够表达出窗花的意向，但又不是直接的把传统窗花贴上去，当我在寻找素材时候看到这组纹样的时候，我感觉味道很对。内页放了植物花纹，象征专辑是一所庭园，因为我常说，“你的心是一座庭园，请不要让它荒芜。” 我专辑里面的歌便是这座庭院里盛开的花草，生机勃勃，自然而然。封底我的头像剪影上的一只鸟，也暗指了歌唱。"]},
{ "d":"2019/11/02 19:30:00","page":"","title":["北京 糖果_TANGO","北京 糖果_TANGO"],"info":["A kitten is a juvenile cat. After being born, kittens are totally dependent on their mother for survival and they do not normally open their eyes until after seven to ten days. After about two weeks, kittens quickly develop and begin to explore the world outside the nest. After a further three to four weeks, they begin to eat solid food and grow adult teeth. Domestic kittens are highly social animals and usually enjoy human companionship.","每个人，都应像一株多年生木本植物，年年月月，经受着季节的变换，斑驳了枝干，褪去了曾经的稚嫩和青涩，然而每到春季，却愈加枝繁叶茂，花期到来时愈加烂漫。脱壳而出的金蝉，告别了幼时的模样，才拥有了轻盈的羽翼，从此获得飞翔的自由。"]},
{ "d":"2019/11/29 19:30:00","page":"","title":["广州 MAOLivehouse广州","广州 MAOLivehouse广州"],"info":["A kitten is a juvenile cat. After being born, kittens are totally dependent on their mother for survival and they do not normally open their eyes until after seven to ten days. After about two weeks, kittens quickly develop and begin to explore the world outside the nest. After a further three to four weeks, they begin to eat solid food and grow adult teeth. Domestic kittens are highly social animals and usually enjoy human companionship.","每个人，都应像一株多年生木本植物，年年月月，经受着季节的变换，斑驳了枝干，褪去了曾经的稚嫩和青涩，然而每到春季，却愈加枝繁叶茂，花期到来时愈加烂漫。脱壳而出的金蝉，告别了幼时的模样，才拥有了轻盈的羽翼，从此获得飞翔的自由。"]},
{ "d":"2019/11/02 19:30:00","page":"","title":["北京 糖果_TANGO","北京 糖果_TANGO"],"info":["A kitten is a juvenile cat. After being born, kittens are totally dependent on their mother for survival and they do not normally open their eyes until after seven to ten days. After about two weeks, kittens quickly develop and begin to explore the world outside the nest. After a further three to four weeks, they begin to eat solid food and grow adult teeth. Domestic kittens are highly social animals and usually enjoy human companionship.","每个人，都应像一株多年生木本植物，年年月月，经受着季节的变换，斑驳了枝干，褪去了曾经的稚嫩和青涩，然而每到春季，却愈加枝繁叶茂，花期到来时愈加烂漫。脱壳而出的金蝉，告别了幼时的模样，才拥有了轻盈的羽翼，从此获得飞翔的自由。"]},
{ "d":"2019/11/02 19:30:00","page":"","title":["北京 糖果_TANGO","北京 糖果_TANGO"],"info":["A kitten is a juvenile cat. After being born, kittens are totally dependent on their mother for survival and they do not normally open their eyes until after seven to ten days. After about two weeks, kittens quickly develop and begin to explore the world outside the nest. After a further three to four weeks, they begin to eat solid food and grow adult teeth. Domestic kittens are highly social animals and usually enjoy human companionship.","每个人，都应像一株多年生木本植物，年年月月，经受着季节的变换，斑驳了枝干，褪去了曾经的稚嫩和青涩，然而每到春季，却愈加枝繁叶茂，花期到来时愈加烂漫。脱壳而出的金蝉，告别了幼时的模样，才拥有了轻盈的羽翼，从此获得飞翔的自由。"]},
{ "d":"2019/11/02 19:30:00","page":"","title":["北京 糖果_TANGO","北京 糖果_TANGO"],"info":["A kitten is a juvenile cat. After being born, kittens are totally dependent on their mother for survival and they do not normally open their eyes until after seven to ten days. After about two weeks, kittens quickly develop and begin to explore the world outside the nest. After a further three to four weeks, they begin to eat solid food and grow adult teeth. Domestic kittens are highly social animals and usually enjoy human companionship.","每个人，都应像一株多年生木本植物，年年月月，经受着季节的变换，斑驳了枝干，褪去了曾经的稚嫩和青涩，然而每到春季，却愈加枝繁叶茂，花期到来时愈加烂漫。脱壳而出的金蝉，告别了幼时的模样，才拥有了轻盈的羽翼，从此获得飞翔的自由。"]},
{ "d":"2019/11/02 19:30:00","page":"","title":["北京 糖果_TANGO","北京 糖果_TANGO"],"info":["A kitten is a juvenile cat. After being born, kittens are totally dependent on their mother for survival and they do not normally open their eyes until after seven to ten days. After about two weeks, kittens quickly develop and begin to explore the world outside the nest. After a further three to four weeks, they begin to eat solid food and grow adult teeth. Domestic kittens are highly social animals and usually enjoy human companionship.","每个人，都应像一株多年生木本植物，年年月月，经受着季节的变换，斑驳了枝干，褪去了曾经的稚嫩和青涩，然而每到春季，却愈加枝繁叶茂，花期到来时愈加烂漫。脱壳而出的金蝉，告别了幼时的模样，才拥有了轻盈的羽翼，从此获得飞翔的自由。"]},
{ "d":"2019/11/02 19:30:00","page":"","title":["北京 糖果_TANGO","北京 糖果_TANGO"],"info":["A kitten is a juvenile cat. After being born, kittens are totally dependent on their mother for survival and they do not normally open their eyes until after seven to ten days. After about two weeks, kittens quickly develop and begin to explore the world outside the nest. After a further three to four weeks, they begin to eat solid food and grow adult teeth. Domestic kittens are highly social animals and usually enjoy human companionship.","每个人，都应像一株多年生木本植物，年年月月，经受着季节的变换，斑驳了枝干，褪去了曾经的稚嫩和青涩，然而每到春季，却愈加枝繁叶茂，花期到来时愈加烂漫。脱壳而出的金蝉，告别了幼时的模样，才拥有了轻盈的羽翼，从此获得飞翔的自由。"]},
{ "d":"2019/11/02 19:30:00","page":"","title":["北京 糖果_TANGO","北京 糖果_TANGO"],"info":["A kitten is a juvenile cat. After being born, kittens are totally dependent on their mother for survival and they do not normally open their eyes until after seven to ten days. After about two weeks, kittens quickly develop and begin to explore the world outside the nest. After a further three to four weeks, they begin to eat solid food and grow adult teeth. Domestic kittens are highly social animals and usually enjoy human companionship.","每个人，都应像一株多年生木本植物，年年月月，经受着季节的变换，斑驳了枝干，褪去了曾经的稚嫩和青涩，然而每到春季，却愈加枝繁叶茂，花期到来时愈加烂漫。脱壳而出的金蝉，告别了幼时的模样，才拥有了轻盈的羽翼，从此获得飞翔的自由。"]},
{ "d":"2019/12/27 19:30:00","page":"","title":["北京 糖果_TANGO","北京 糖果_TANGO"],"info":["A kitten is a juvenile cat. After being born, kittens are totally dependent on their mother for survival and they do not normally open their eyes until after seven to ten days. After about two weeks, kittens quickly develop and begin to explore the world outside the nest. After a further three to four weeks, they begin to eat solid food and grow adult teeth. Domestic kittens are highly social animals and usually enjoy human companionship.","每个人，都应像一株多年生木本植物，年年月月，经受着季节的变换，斑驳了枝干，褪去了曾经的稚嫩和青涩，然而每到春季，却愈加枝繁叶茂，花期到来时愈加烂漫。脱壳而出的金蝉，告别了幼时的模样，才拥有了轻盈的羽翼，从此获得飞翔的自由。"]},
{ "d":"2019/12/28 19:30:00","page":"","title":["北京 糖果_TANGO","北京 糖果_TANGO"],"info":["A kitten is a juvenile cat. After being born, kittens are totally dependent on their mother for survival and they do not normally open their eyes until after seven to ten days. After about two weeks, kittens quickly develop and begin to explore the world outside the nest. After a further three to four weeks, they begin to eat solid food and grow adult teeth. Domestic kittens are highly social animals and usually enjoy human companionship.","每个人，都应像一株多年生木本植物，年年月月，经受着季节的变换，斑驳了枝干，褪去了曾经的稚嫩和青涩，然而每到春季，却愈加枝繁叶茂，花期到来时愈加烂漫。脱壳而出的金蝉，告别了幼时的模样，才拥有了轻盈的羽翼，从此获得飞翔的自由。"]},
];
function add0(t){
	 if(t <=9) return '0'+t;
	 else return t;
}
for(let i in news) {
	var d = new Date(news[i].d);
	news[i].date=[EnDay[d.getDay()-1]+", "+d.getDate()+" "+EnMonth[d.getMonth()]+" "+d.getFullYear()+" "+add0(d.getHours())+":"+add0(d.getMinutes()),
	d.getFullYear()+"年"+(d.getMonth()+1)+"月"+d.getDate()+"日 "+add0(d.getHours())+":"+add0(d.getMinutes())+"，"+CnDay[d.getDay()-1]];
};

var lang= {
"lang":["EN","中"],
"back":["Back","返回"],
"menu":["Menu","菜单"],
};

var navinames= [
{ "Home":"HOME","About":"ALBUM","History":"HISTORY","Photos":"PHOTO","News":"LIVE","Contacts":"Contacts"},
{ "Home":"首页","About":"专辑","History":"历程","Photos":"相片","News":"演出","Contacts":"联系"},
];

var historylist= [
{"date":"9/16/2012","info":["Anna’s Patio","《晴日共剪窗》"],"page":"cb01.html"},
{"date":"8/15/2014","info":["Poetry Meets Song","《诗遇上歌》"],"page":"cb02.html"},
{"date":"3/13/2015","info":["I Want to Waste Time With You","《我想和你虚度时光》"],"page":"cb03.html"},
{"date":"8/9/2016","info":["Early Born Cricket","《早生的铃虫》"],"page":"cb04.html"},
{"date":"11/25/2017","info":["Ever Walking","《步履不停》"],"page":"cb05.html"},
{"date":"8/29/2019","info":["And When I Embraced You","《然后，我拥抱你》"],"page":"cb06.html"},
];
for(let i in historylist) {
	let d = new Date(historylist[i].date);
	historylist[i].year=d.getFullYear();
	historylist[i].month=d.getMonth()+1;
};
var about= { "historylist":historylist,"EnMonth":EnMonth,};

var historylist2= [
{"year":2012,"month":7,"date":7,"site":"北京 南锣鼓巷69cafe","n":"","class":"","info":"日式乡村民谣弹唱会","url":"http://weibo.com/2158787251/yrm7ffGg5"},
{"year":2012,"month":9,"date":16,"site":"北京 南锣鼓巷69cafe","n":"","class":"","info":"程璧首张原创音乐专辑Anna's Patio《晴日共剪窗》首发演出本周日16号晚九点69CAFE ","url":"http://weibo.com/2158787251/yBrEhdrKd"},
{"year":2013,"month":12,"date":17,"site":"北京 北大图书馆","n":"","class":"","info":"给阿兰，一位远行的音乐朋友，所做的纪念专辑发布会海报。我们在北大吉他协会结识，他那时一头长发，带古典吉他班，还弹尤可里里，后来为我那首《晴日共剪窗》做现场鼓手，上台前还给我拥抱加油鼓气。我们都爱他的自由不羁，爱他的童真浪漫。等着世界末日，他会实现承诺，带着一艘大方舟回来解救我们。","url":""},
{"year":2014,"month":10,"date":11,"site":"杭州","n":"","class":"","info":"这次杭州演出收到很贴心的礼物：一套好看的茶具，造型是一朵莲花一片荷叶。回家仔细一看里面还提了字，看到以后有些感动。拿来泡了一壶桂花龙井茶，真的是很爱，造型小巧加上外面这柔软的包裹，以后可以随时带着它出门了。谢谢美丽的@舒羽shuyu 和她的@舒羽咖啡","url":"http://weibo.com/1759006061/Br2k4zptr"},
{"year":2014,"month":11,"date":28,"site":"长沙","n":"","class":"","info":"全集视频在这。记得当时节目组微博私信我的时候，小伙伴提醒小心是骗子啊，笑。确实，因为我的路才刚刚开始。后来好奇问导演组，到底是怎样知道我的啊，导演说因为组里大家都很喜欢你的歌啊。世界上很多事真的就是这么简单。唯有继续努力。这次也认识了很棒的民谣人，不虚此行。谢谢电视机前的你！晚安","url":"http://weibo.com/1759006061/BypSir8Dd"},
{"year":2014,"month":11,"date":9,"site":"北京 西区剧场","n":"","class":"","info":"好多朋友问下一站演出来不来我们这。我当然会去，可又一点也不着急。我知道那些美丽的地方在，不想走马观花地看。我想每去一个地方就好好感受，一一看遍。所以远方的人啊，请你也不要急，等我慢慢地走过这大好河山，与你相见。 ​​​​","url":"http://weibo.com/1759006061/BAb97qGjw"},
{"year":2015,"month":2,"date":7,"site":"广州 289艺术空间","n":"","class":"","info":"今晚在广州289艺术空间，与诗歌岛、荔枝FM一起做一场诗歌与民谣的专场演出。因为活动在主办方一发出票马上就订光了，所以我这里没有在微博或者我的微信公号推送。原本只有可以容纳200人的场地因为大家的热情增加到350。下午南方报系等媒体群访也聊的很开心。谢谢广州小伙伴们，我们一会儿见。","url":"https://weibo.com/1759006061/C3dE4oQ88"},
{"year":2015,"month":2,"date":14,"site":"苏州 凯宾斯基大酒店","n":"","class":"","info":"你可知道我小时候因为这被老师叫出去训话，“程璧同学你上课可不可以不要老瞪着我”，然后以后上课都只能眯着眼睛了","url":"https://weibo.com/1759006061/C4oA9criI"},
{"year":2015,"month":5,"date":20,"site":"广州 中央车站","n":"1","class":"","info":"？？？","url":"http://weibo.com/1759006061/CixB16yWk"},
{"year":2015,"month":5,"date":23,"site":"济南 山东大学","n":"","class":"","info":"列车南下，到月末会一直在路上，济南，重庆，广州，成都，北京。今天下午2:00山东大学洪家楼校区108教室见","url":"http://weibo.com/1759006061/Cj85rarLK"},
{"year":2015,"month":5,"date":19,"site":"广州 中山大学","n":"","class":"","info":"明晚在广州中央车站音乐厅的演出，乐童上官方预售票包括所有现场票，都已全部卖光。提醒大家，不要来现场买票。如果买了套票同伴有事不能来，转发这条呼唤愿意一起来的伙伴分享。另外，本次演出乐视音乐会全程直播，在家里也可以看直播。听说有位小伙会在现场向心爱的姑娘求婚，先表达祝福呢！","url":""},
{"year":2015,"month":7,"date":11,"site":"北京 中山音乐堂","n":"5","class":"","info":"走了那么远的路，过了一整个春末夏初，终于是今晚最后一场音乐会了。回想起路上遇见的每一个可亲可爱的面孔，心里满是不舍和感激。今晚，还是我来唱歌，你来读诗，好吗？共赴一场春末夏初的最后约定。我把等待喜欢过了，我准备好了。","url":"https://weibo.com/1759006061/CqCu3oAJC"},
{"year":2015,"month":5,"date":2,"site":"镇江 世业洲长江国际音乐岛","n":"","class":"","info":"出发去镇江，参加长江国际音乐节。我会在5月2号的下午的长江舞台出现，也会在同一天的晚上参加星空露营舞台。白天的演出曲目选择的是轻快爽朗的，歌唱部分多一些，夜晚的选择的是舒服安静的，还可以看星星聊天，比较轻松随意。两场演出完还会有专辑签售。这是第一次的露天音乐节体验，请多关照！","url":"https://weibo.com/1759006061/CfOsf5W6D"},
{"year":2015,"month":5,"date":27,"site":"重庆 少数花园","n":"","class":"","info":"？？？","url":""},
{"year":2015,"month":5,"date":30,"site":"成都 MINI LIVE 音乐现场","n":"2","class":"","info":"？？？","url":""},
{"year":2015,"month":5,"date":29,"site":"成都 方所文化","n":"","class":"","info":"成都的庭院分享会，谢谢城市之音张舒来陪我一起和大家聊天。有一位朋友问，你的歌风格好像一成不变。我回答，为什么要急着变呢，能够保持着最初的模样，是一件多么不容易的事情。我的变，是诗歌的变，时间的变，情感的变。至于丰富的音乐元素，我才刚刚开始，不着急拿来堆砌。 ","url":"http://weibo.com/1759006061/CkIwD6uRO"},
{"year":2015,"month":6,"date":27,"site":"济南 山东剧院","n":"","class":"","info":"不知不觉，已离家千万里。","url":"http://weibo.com/1759006061/CoFOtiIji"},
{"year":2015,"month":6,"date":9,"site":"北京 北京大学","n":"","class":"","info":"在北大的分享会，我开场问大家一个问题：你觉得文艺是什么。一位男孩站起来说，文艺就是文化和艺术，是感性的抒发。一下就说中了关键的地方。文艺是非常宽泛的，是人类区别于动物的标志，是丰富多样的精神世界。我从不以文艺青年而自嘲，欣然接近各个艺术门类。再说，从小在班里就是文艺委员呢[害羞] ​​​​","url":"https://weibo.com/1759006061/Cm4spBJGr"},
{"year":2015,"month":6,"date":13,"site":"长沙 红色剧院","n":"3","class":"","info":"花菇凉扮起来[哈哈]我和小伙伴们都准备好了","url":"http://weibo.com/1759006061/Cmntb52cr"},
{"year":2015,"month":6,"date":17,"site":"上海 复旦大学","n":"","class":"","info":"转眼今晚将会是庭院分享会最后一站复旦大学","url":"http://weibo.com/1759006061/CmWYGrzN4"},
{"year":2015,"month":6,"date":21,"site":"上海 浅水湾艺术中心","n":"4","class":"","info":"？？？","url":""},
{"year":2015,"month":6,"date":12,"site":"长沙 湖南大学","n":"","class":"","info":"在湖大遇到一位女孩，让我想到了村上春树笔下的初美。","url":"http://weibo.com/1759006061/CmXAElOSM"},
{"year":2016,"month":4,"date":28,"site":"澳门 黑沙海滩","n":"","class":"","info":"HUSH MUSIC CONCERT","url":"http://weibo.com/1759006061/DsTfeBMpl"},
{"year":2016,"month":12,"date":21,"site":"宁波 宁波大剧院","n":"18","class":"","info":"十八城巡演最后的收官站宁波，因为北大师兄师妹...","url":"http://weibo.com/1759006061/Enj9pnG0N"},
{"year":2016,"month":9,"date":2,"site":"深圳 南山文体中心","n":"1","class":"","info":"我说再见某年某月，你说今夜不眠。","url":"http://weibo.com/1759006061/E6sUk8Gy9"},
{"year":2016,"month":9,"date":11,"site":"上海 上海交响音乐团","n":"2","class":"","info":"？？？","url":""},
{"year":2016,"month":9,"date":24,"site":"广州 中央车站","n":"3","class":"","info":"？？？","url":""},
{"year":2016,"month":10,"date":14,"site":"武汉 武汉剧院","n":"4","class":"","info":"昨晚忘了关窗，早晨被江边航船汽笛声叫醒了。","url":"http://weibo.com/1759006061/EcXgSccwI"},
{"year":2016,"month":12,"date":14,"site":"台北","n":"","class":"","info":"在台北风潮音乐旗舰店，做了非常用心的corner","url":"http://weibo.com/1759006061/Em7Tdke3y"},
{"year":2016,"month":10,"date":16,"site":"南京 文化馆大剧院","n":"5","class":"","info":"一城又一城 到达然后告别 南京站看到了那些默默举起的横幅","url":"http://weibo.com/1759006061/Edz44yNbg"},
{"year":2016,"month":10,"date":20,"site":"杭州 杭州大剧院","n":"6","class":"","info":"“我们不一样 我们都很棒”","url":"http://weibo.com/1759006061/Ee0jS849i"},
{"year":2016,"month":10,"date":22,"site":"重庆 人民大厦","n":"7","class":"","info":"？？？","url":""},
{"year":2016,"month":10,"date":23,"site":"成都 锦城艺术宫","n":"8","class":"","info":"在成都与橙色有关的日常","url":"http://weibo.com/1759006061/EewevqUa0"},
{"year":2016,"month":10,"date":28,"site":"厦门 钢琴音乐厅","n":"10","class":"","info":"聊聊古生物鲎、磕海瓜子、踏浪吹海风！","url":"http://weibo.com/1759006061/Ef385dl14"},
{"year":2016,"month":11,"date":5,"site":"长沙 湖南大剧院","n":"12","class":"","info":"花，旧友，笑顔，手写信。","url":"http://weibo.com/1759006061/Egf1W4EnA"},
{"year":2016,"month":11,"date":6,"site":"昆明 胜利堂剧院","n":"13","class":"","info":"收到一份特别礼物","url":"http://weibo.com/1759006061/Egrk763aN"},
{"year":2016,"month":11,"date":12,"site":"北京 世纪剧院","n":"14","class":"","info":"其实很多话在心里","url":"http://weibo.com/1759006061/EhyErqnV5"},
{"year":2016,"month":11,"date":18,"site":"西安 西安音乐厅","n":"15","class":"","info":"？？？？","url":""},
{"year":2016,"month":10,"date":26,"site":"无锡 演艺剧院","n":"9","class":"","info":"本月巡演倒数第二站！","url":"http://weibo.com/1759006061/EePgbkXGS"},
{"year":2016,"month":11,"date":20,"site":"苏州 独墅湖影剧院","n":"16","class":"","info":"有的人心里，藏着一片幽暗森林；有的人心里，留着一个光亮出口。","url":"http://weibo.com/1759006061/EizAa2VTz"},
{"year":2016,"month":9,"date":3,"site":"兰州 黄河剧院","n":"","class":"","info":"接着飞兰州，也是第一次去到西北演出，期待","url":"http://weibo.com/1759006061/E68l6uHxs"},
{"year":2016,"month":7,"date":30,"site":"张北","n":"","class":"","info":"去往张北草原音乐节的路上了！","url":"http://weibo.com/1759006061/E1g0Otvpf"},
{"year":2016,"month":12,"date":9,"site":"天津 津湾大剧院","n":"17","class":"","info":"趁夜色发个自拍大头照","url":"http://weibo.com/1759006061/Elmwp7x1P"},
{"year":2016,"month":1,"date":4,"site":"杭州","n":"","class":"","info":"请用一个词来形容这只正在尝试新发型的少女","url":"http://weibo.com/1759006061/DbzFsbdSy"},
{"year":2016,"month":6,"date":19,"site":"深圳","n":"","class":"","info":"晚上和风专场，发表一下「拙见」","url":"http://weibo.com/1759006061/DAX7vE767"},
{"year":2016,"month":6,"date":10,"site":"上海","n":"","class":"","info":"第一次看到新书《可以不可以》","url":"http://weibo.com/1759006061/DzC8xeBBe"},
{"year":2016,"month":8,"date":14,"site":"东京 月見ル君想ウ","n":"","class":"","info":"青山 月見ル君想ウ。","url":"http://weibo.com/1759006061/E3dAV86yf"},
{"year":2016,"month":10,"date":30,"site":"东莞 东莞市文化馆","n":"11","class":"","info":"今天是万圣节前夜","url":"http://weibo.com/1759006061/EffTiqNLb"},
{"year":2017,"month":4,"date":24,"site":"上海","n":"","class":"","info":"「从诗到歌的一些“温柔试探”」","url":"http://weibo.com/1759006061/F011e4aD3"},
{"year":2017,"month":6,"date":18,"site":"上海","n":"","class":"","info":"昨天。","url":"http://weibo.com/1759006061/F8xDnvMw0"},
{"year":2017,"month":4,"date":28,"site":"长沙","n":"","class":"","info":"唱了一首从未唱过的新歌。","url":"http://weibo.com/1759006061/F0O8wwTXR"},
{"year":2017,"month":6,"date":3,"site":"武藏野","n":"","class":"","info":"Nature Weekend. ","url":"http://weibo.com/1759006061/F67Evngu9"},
{"year":2017,"month":6,"date":20,"site":"克罗地亚","n":"","class":"","info":"Croatia | 克罗地亚。","url":"http://weibo.com/1759006061/F8FZTxSz6"},
{"year":2017,"month":7,"date":21,"site":"西安 西安音乐厅","n":"","class":"","info":"“长安县，阳光就很灿烂～！”","url":"http://weibo.com/1759006061/FdzFcbdrN"},
{"year":2017,"month":11,"date":25,"site":"","n":"","class":"","info":"新专辑《步履不停》于今日正式上架发售！","url":"http://weibo.com/1759006061/FwHhTdpWt"},
{"year":2018,"month":1,"date":12,"site":"北京 如论讲堂","n":"1","class":"","info":"深夜悄悄发图。<br>&#12288;&#12288;<br>&#12288;&#12288;从事音乐创作第四年，<br>&#12288;&#12288;很多东西变了，但又好像没变。<br>&#12288;&#12288;<br>&#12288;&#12288;感谢你一直在。<br>&#12288;&#12288;下一站，1.26，深圳保利剧院。","url":"http://weibo.com/1759006061/FEx0BvWuv"},
{"year":2018,"month":2,"date":3,"site":"上海 美琪大戏院","n":"3","class":"","info":"团队乐队大家，这一路辛苦了","url":"http://weibo.com/1759006061/G1AwSwYbI"},
{"year":2018,"month":1,"date":26,"site":"深圳 保利剧院","n":"2","class":"","info":"薄雾里的晨钟，是隐约的光亮。","url":"http://weibo.com/1759006061/G0WtbE6IO"},
{"year":2018,"month":3,"date":10,"site":"东京 月見ル君思ウ","n":"","class":"","info":"昨晚的纪念演出，尝试了这样的发型。","url":"http://weibo.com/1759006061/G6LOgbjl1"},
{"year":2018,"month":3,"date":24,"site":"苏州 文化艺术中心","n":"4","class":"","info":"唱完了！","url":"http://weibo.com/1759006061/G8UfzFN2c"},
{"year":2018,"month":12,"date":16,"site":"杭州 杭州大剧院","n":"11","class":"","info":"2018“薄雾里的晨钟”演唱会<br>&#12288;&#12288;从年初到年末，走过十一个城市，<br>&#12288;&#12288;最后杭州收官战顺利结束！！🎄🎄🎄<br>&#12288;&#12288;<br>&#12288;&#12288;感谢每一位来到现场的朋友，<br>&#12288;&#12288;感谢@FOTILE方太 一整年的支持陪伴。<br>&#12288;&#12288;<br>&#12288;&#12288;感谢团队每一位伙伴的专业和敬业，<br>&#12288;&#12288;有星宇阿伦带领的演奏乐队；<br>&#12288;&#12288;有冀翔老师带领的音响团队；<br>&#12288;&#12288;有早川绫子老师带领的灯光团队。<br>&#12288;&#12288;<br>&#12288;&#12288;就像昨晚在舞台上说过的，<br>&#12288;&#12288;这是一个“很快”的时代，<br>&#12288;&#12288;变化那么多，给人前所未有的重负感，<br>&#12288;&#12288;快到似乎让人无暇顾及，<br>&#12288;&#12288;那些有关“诗意”的东西。<br>&#12288;&#12288;<br>&#12288;&#12288;但我永远不会怀疑诗歌和音乐的力量。<br>&#12288;&#12288;<br>&#12288;&#12288;因为它会帮我们重新找回，<br>&#12288;&#12288;我们生活的最终目的。<br>&#12288;&#12288;新的一年，再见。","url":"http://weibo.com/1759006061/H7H2kpzHt"},
{"year":2018,"month":9,"date":1,"site":"西安 西安音乐厅","n":"9","class":"","info":"薄雾里的晨钟，在西安。","url":"http://weibo.com/1759006061/GxvvsEyWY"},
{"year":2018,"month":8,"date":12,"site":"沈阳 盛京大剧院","n":"8","class":"","info":"第一次到这里唱歌，感谢诸位来到现场听歌的人","url":"http://weibo.com/1759006061/GuqCbyxdJ"},
{"year":2018,"month":7,"date":21,"site":"武汉 武汉剧院","n":"7","class":"","info":"夏树苍翠，长夜如歌。","url":"http://weibo.com/1759006061/Gr71ArP1u"},
{"year":2018,"month":9,"date":22,"site":"石家庄 勒泰中心","n":"10","class":"","info":"谢谢石家庄的小伙伴，谢谢你们愿意来现场","url":"http://weibo.com/1759006061/GAEA3fyhd"},
{"year":2018,"month":4,"date":30,"site":"长沙 湖南大剧院","n":"5","class":"","info":"巡演第五场，长沙站，也唱好了！","url":"http://weibo.com/1759006061/Geximieho"},
{"year":2018,"month":6,"date":10,"site":"成都 锦城艺术宫","n":"6","class":"","info":"总在栀子花开的时候来成都。","url":"http://weibo.com/1759006061/GkJShE1Aq"},
{"year":2019,"month":5,"date":10,"site":"上海 1862艺术中心","n":"","class":"","info":"演出完最开心😃<br>&#12288;&#12288;这时候应该趁夜色溜达一下<br>&#12288;&#12288;还是应该赶紧休息？<br>&#12288;&#12288;你说呢～ ​​​​","url":"http://weibo.com/1759006061/HtAZtlMDC"},
{"year":2019,"month":12,"date":20,"site":"成都 NUSPACE_纽空间","n":"7","class":"","info":"已确认","url":""},
{"year":2019,"month":11,"date":29,"site":"广州 MAOLivehouse广州","n":"2","class":"","info":"已确认","url":""},
{"year":2019,"month":12,"date":1,"site":"深圳 B10现场","n":"3","class":"","info":"已确认","url":""},
{"year":2019,"month":12,"date":14,"site":"杭州 MAOLivehouse杭州","n":"5","class":"","info":"已确认","url":""},
{"year":2019,"month":12,"date":27,"site":"郑州 7LIVEHOUSE","n":"9","class":"","info":"已确认","url":""},
{"year":2019,"month":12,"date":13,"site":"南京 稻香音乐空间","n":"4","class":"","info":"已确认","url":""},
{"year":2019,"month":12,"date":21,"site":"西安 MAOLivehouse西安","n":"8","class":"","info":"已确认","url":""},
{"year":2019,"month":11,"date":2,"site":"北京 糖果_TANGO ","n":"1","class":"","info":"已确认","url":""},
{"year":2019,"month":12,"date":15,"site":"上海 MAOLivehouse上海","n":"6","class":"","info":"已确认","url":""},
{"year":2019,"month":12,"date":28,"site":"武汉 VOXLIVEHOUSE","n":"10","class":"","info":"已确认","url":""},
{"year":2019,"month":12,"date":99,"site":"东京 TSUTAYA","n":"","class":"","info":"待定","url":""},
];
historylist2.sort(function (a,b){return 10000*(a.year-b.year)+100*(a.month-b.month)+(a.date-b.date);});