var file=[

{"TITLE":"汉州站","F_GROUP":"draw","S_GROUP":"精绘","F_NAME":"hanzhou",},
{"TITLE":"外国车站","F_GROUP":"draw","S_GROUP":"精绘","F_NAME":"antwerpen",},
{"TITLE":"围楼","F_GROUP":"draw","S_GROUP":"精绘","F_NAME":"weilou1",},
{"TITLE":"石头城","F_GROUP":"draw","S_GROUP":"精绘","F_NAME":"shitoucheng",},
{"TITLE":"古堡","F_GROUP":"draw","S_GROUP":"精绘","F_NAME":"gubao",},
{"TITLE":"教堂","F_GROUP":"draw","S_GROUP":"精绘","F_NAME":"jiaotang",},
{"TITLE":"陰陽","F_GROUP":"draw","S_GROUP":"精绘","F_NAME":"qiyuan",},

{"TITLE":"塔布茏寺","F_GROUP":"draw","S_GROUP":"简绘","F_NAME":"taprohm",},
{"TITLE":"布达拉宫","F_GROUP":"draw","S_GROUP":"简绘","F_NAME":"budala",},
{"TITLE":"长城","F_GROUP":"draw","S_GROUP":"简绘","F_NAME":"changcheng",},
{"TITLE":"水乡","F_GROUP":"draw","S_GROUP":"简绘","F_NAME":"shuixiang",},
{"TITLE":"衙门","F_GROUP":"draw","S_GROUP":"简绘","F_NAME":"yamen",},
{"TITLE":"外国州府","F_GROUP":"draw","S_GROUP":"简绘","F_NAME":"cityhall",},

{"TITLE":"承星臺","F_GROUP":"draw","S_GROUP":"夜色","F_NAME":"chengxing",},
{"TITLE":"觀象臺","F_GROUP":"draw","S_GROUP":"夜色","F_NAME":"guanxiang",},
{"TITLE":"夜围楼","F_GROUP":"draw","S_GROUP":"夜色","F_NAME":"weilou2",},
{"TITLE":"太和殿","F_GROUP":"draw","S_GROUP":"夜色","F_NAME":"taihedian",},

{"TITLE":"铁索寒桥","F_GROUP":"photo","F_NAME":"1",},
{"TITLE":"残阳危坝","F_GROUP":"photo","F_NAME":"2",},
{"TITLE":"古樟千年","F_GROUP":"photo","F_NAME":"3",},
{"TITLE":"断崖飞树","F_GROUP":"photo","F_NAME":"4",},
{"TITLE":"西江入海","F_GROUP":"photo","F_NAME":"5",},
{"TITLE":"翰海无边","F_GROUP":"photo","F_NAME":"6",},
{"TITLE":"幽岭关隘","F_GROUP":"photo","F_NAME":"7",},
{"TITLE":"祠公文朱","F_GROUP":"photo","F_NAME":"8",},

{"TITLE":"北京01","F_GROUP":"map","F_NAME":"beijing01",},
{"TITLE":"北京02","F_GROUP":"map","F_NAME":"beijing02",},
{"TITLE":"上海","F_GROUP":"map","F_NAME":"shanghai",},
{"TITLE":"西安","F_GROUP":"map","F_NAME":"xian",},
{"TITLE":"厦门","F_GROUP":"map","F_NAME":"xiamen",},
{"TITLE":"漳州","F_GROUP":"map","F_NAME":"zhangzhou",},
{"TITLE":"神农架","F_GROUP":"map","F_NAME":"shennongjia",},
{"TITLE":"纳木错","F_GROUP":"map","F_NAME":"namucuo",},

{"TITLE":"👧和喵","F_GROUP":"piyipi","F_NAME":"cb01",},
{"TITLE":"👧骑车","F_GROUP":"piyipi","F_NAME":"cb02",},
{"TITLE":"👧的箱子","F_GROUP":"piyipi","F_NAME":"cb03",},
{"TITLE":"👧的舞台","F_GROUP":"piyipi","F_NAME":"juyuan",},
{"TITLE":"脑斧和大锅","F_GROUP":"piyipi","F_NAME":"naofudaguo",},
{"TITLE":"月球车","F_GROUP":"piyipi","F_NAME":"yueqiuche",},
{"TITLE":"石船","F_GROUP":"piyipi","F_NAME":"shichuan",},

{"TITLE":"财神庙","F_GROUP":"test","F_NAME":"csm",},
{"TITLE":"石头水库","F_GROUP":"test","F_NAME":"ssysk",},
{"TITLE":"天穹","F_GROUP":"test","F_NAME":"stars",},
{"TITLE":"火星","F_GROUP":"test","F_NAME":"mars",},
{"TITLE":"地","F_GROUP":"test","F_NAME":"earth",},
{"TITLE":"月","F_GROUP":"test","F_NAME":"moon",},
{"TITLE":"测试","F_GROUP":"test","F_NAME":"test",},

];