var file=[
{F_GROUP:"suse",S_GROUP:"小虫虫",TITLE:"蟋蟀",W_URL:["GoGZYsGUR"],},
{F_GROUP:"suse",S_GROUP:"小虫虫",TITLE:"大青虫",W_URL:["GjHzXbmg1"],},
{F_GROUP:"suse",S_GROUP:"小虫虫",TITLE:"豆娘",W_URL:["GjxxvkeK7"],F_NAME: ["dn1.jpg"],LINK: "photo_photo/透顶单脉色蟌",},
{F_GROUP:"suse",S_GROUP:"小虫虫",TITLE:"蠼螋",W_URL:["Ggv6dtl37"],},
{F_GROUP:"suse",S_GROUP:"小虫虫",TITLE:"叶上蝶",W_URL:["GiRQRlwzk"],},
{F_GROUP:"suse",S_GROUP:"小虫虫",TITLE:"叩头虫",W_URL:["GiJ47ujYA"],},
{F_GROUP:"suse",S_GROUP:"小虫虫",TITLE:"叶上绿螽斯",W_URL:["GhXPujZUA"],},
{F_GROUP:"suse",S_GROUP:"小虫虫",TITLE:"灰螳螂",W_URL:["Gh3dF9Ar5"],},
{F_GROUP:"suse",S_GROUP:"小虫虫",TITLE:"天牛",W_URL:["GgTAvaLpX"],F_NAME: ["tn1.jpg"],LINK: "photo_photo/天牛",},
{F_GROUP:"suse",S_GROUP:"小虫虫",TITLE:"地上绿螽斯",W_URL:["GgMCyaodh"],},
{F_GROUP:"suse",S_GROUP:"小虫虫",TITLE:"电蛱蝶",W_URL:["GgDL7xjQf"],},
{F_GROUP:"suse",S_GROUP:"小虫虫",TITLE:"知了",W_URL:["Ggh0c3aPB"],},
{F_GROUP:"suse",S_GROUP:"小虫虫",TITLE:"豆芫菁",W_URL:["GfIGHCOz3"],},
{F_GROUP:"suse",S_GROUP:"小虫虫",TITLE:"粉蜻蜓",W_URL:["GfGhw8Vkm"],},
{F_GROUP:"suse",S_GROUP:"小鸟",TITLE:"叶上小鸟",W_URL:["GizpFoxAJ"],},
{F_GROUP:"suse",S_GROUP:"小鸟",TITLE:"小PT",W_URL:["GhgPPhsT3"],},
{F_GROUP:"suse",S_GROUP:"小鸟",TITLE:"黑喉石鵖",W_URL:["GhlVrkBP0"],},
{F_GROUP:"suse",S_GROUP:"小鸟",TITLE:"小山雀",W_URL:["Gh5Dn9yb5"],},
{F_GROUP:"suse",S_GROUP:"小鸟",TITLE:"玛丽",W_URL:["GgMZKiycX"],},
{F_GROUP:"suse",S_GROUP:"小鸟",TITLE:"白胸翡翠",W_URL:["GgbbIuCem"],},
{F_GROUP:"suse",S_GROUP:"小鸟",TITLE:"伯劳",W_URL:["Gg1SW2RHb"],},
{F_GROUP:"suse",S_GROUP:"小鸟",TITLE:"老鹰",W_URL:["GfZ1kuqwW"],},
{F_GROUP:"suse",S_GROUP:"小鸟",TITLE:"褐翅鸦鹃",W_URL:["GfAoVzgHR"],},
{F_GROUP:"suse",S_GROUP:"小鸟",TITLE:"北红尾鸲",W_URL:["GfxApy9sa"],},
{F_GROUP:"suse",S_GROUP:"小鸟",TITLE:"鹪莺",W_URL:["GfwQApn9P"],},
{F_GROUP:"suse",S_GROUP:"小鸟",TITLE:"乌鸫",W_URL:["Gk5E7zRiw"],},
{F_GROUP:"suse",S_GROUP:"小鸟",TITLE:"领雀嘴鹎",W_URL:["GjMJDgCvp"],},
{F_GROUP:"suse",S_GROUP:"小鸟",TITLE:"夜鹭",W_URL:["H1rNBdcBC"],},
{F_GROUP:"suse",S_GROUP:"其它小动物",TITLE:"册册的喵",W_URL:["GpRHPv0kn"],},
{F_GROUP:"suse",S_GROUP:"其它小动物",TITLE:"小凶许",W_URL:["GiS8Pj2aj"],},
{F_GROUP:"suse",S_GROUP:"其它小动物",TITLE:"野生Totoro",W_URL:["HaPlg6p8v"],},
{F_GROUP:"suse",S_GROUP:"其它小动物",TITLE:"卡瓦老师捉的小胖",W_URL:["GiINHtr8C"],},
{F_GROUP:"suse",S_GROUP:"其它小动物",TITLE:"憨憨",W_URL:["GiUhIvpkq"],},
{F_GROUP:"suse",S_GROUP:"其它小动物",TITLE:"草鱼",W_URL:["Gg8vZjWVK"],},
{F_GROUP:"suse",S_GROUP:"其它",TITLE:"多肉",W_URL:["GiUT2uACF"],},
{F_GROUP:"suse",S_GROUP:"其它",TITLE:"风速风向仪",W_URL:["Ggl2c3XiX"],},
{F_GROUP:"suse",S_GROUP:"其它",TITLE:"莲花",W_URL:["GgaVtqLQc"],},
{F_GROUP:"suse",S_GROUP:"其它",TITLE:"越王之剑",W_URL:["GfPIGmncF"],},



{F_GROUP:"color",S_GROUP:"小虫虫",TITLE:"蛹",W_URL:["GtwpT0QqA"],},
{F_GROUP:"color",S_GROUP:"小虫虫",TITLE:"红螽斯",W_URL:["GsLd80yu4"],},
{F_GROUP:"color",S_GROUP:"小虫虫",TITLE:"萤火虫",W_URL:["GqWdhCSCD"],},
{F_GROUP:"color",S_GROUP:"小虫虫",TITLE:"黑尾叶蝉",W_URL:["GqGhW0tPn"],},
{F_GROUP:"color",S_GROUP:"小虫虫",TITLE:"大蚂蚁",W_URL:["GqtBWmARw"],},
{F_GROUP:"color",S_GROUP:"小虫虫",TITLE:"蟲脩",W_URL:["GqczxCSpl"],},
{F_GROUP:"color",S_GROUP:"小虫虫",TITLE:"手上蜻蜓",W_URL:["GpUHXEedd"],},
{F_GROUP:"color",S_GROUP:"小虫虫",TITLE:"莲蓬上蜻蜓",W_URL:["GlcNzzuCq"],},

{F_GROUP:"color",S_GROUP:"小鸟",TITLE:"画眉",W_URL:["GmgDRcADM"],},
{F_GROUP:"color",S_GROUP:"小鸟",TITLE:"红尾水鸲",W_URL:["Gp8W2qWoX"],},
{F_GROUP:"color",S_GROUP:"小鸟",TITLE:"红耳鹎",W_URL:["GlF25b3CT"],},
{F_GROUP:"color",S_GROUP:"小鸟",TITLE:"红嘴蓝鹊",W_URL:["Gl9Fy7FeL"],},
{F_GROUP:"color",S_GROUP:"小鸟",TITLE:"翠鸟",W_URL:["GkzC80gwy"],},
{F_GROUP:"color",S_GROUP:"小鸟",TITLE:"灰背燕尾",W_URL:["GjWwLrA9G"],},
{F_GROUP:"color",S_GROUP:"小鸟",TITLE:"白鹭灰鹭打架了",W_URL:["GjYpPiXHx"],},
{F_GROUP:"color",S_GROUP:"小鸟",TITLE:"栗喉蜂虎",W_URL:["GkgnHCSmI"],},
{F_GROUP:"color",S_GROUP:"小鸟",TITLE:"啄木鸟",W_URL:["He3kJidwX"],},

{F_GROUP:"color",S_GROUP:"其它",TITLE:"土丁桂",W_URL:["Gl2KsoIkq"],},



{F_GROUP:"jieqi",TITLE:"立春",W_URL:["Hf4G8z7n0"],F_NAME: ["00lichun.jpg"],F_DESC:"一候，東風解凍；<br>二候，蟄蟲始振；<br>三候，魚陟負冰。<br><br>立壁千仞，春冰虎尾。<br>是名立春。<br>",},
{F_GROUP:"jieqi",TITLE:"雨水",W_URL:["HhmoYgp6K"],F_NAME: ["01yushui.jpg"],F_DESC:"一候，獺祭魚；<br>二候，鴻雁來；<br>三候，草木萌動。<br><br>風雨晦明，水廣魚大。<br>是名雨水。<br>",},
{F_GROUP:"jieqi",TITLE:"惊蛰",W_URL:["HjDT9gY1g"],F_NAME: ["02jingzhe.jpg"],F_DESC:"一候，桃始華；<br>二候，倉庚鳴；<br>三候，鷹化為鳩。<br><br>雷驚電繞，久蟄思啟。<br>是名驚蟄。<br>",},
{F_GROUP:"jieqi",TITLE:"春分",W_URL:["HlQABrYeZ"],F_NAME: ["03chunfen.jpg"],F_DESC:"一候，玄鳥至；<br>二候，雷乃發聲；<br>三候，始電。<br><br>揚鑣分道，筆走春秋。<br>是名春分。<br>",},
{F_GROUP:"jieqi",TITLE:"清明",W_URL:["Hof0eCStg"],F_NAME: ["04qingming.jpg"],F_DESC:"一候，桐始華；<br>二候，田鼠化為鵪；<br>三候，虹始見。<br><br>晦明轉瞬，淵清玉潔。<br>是名清明。<br>",},
{F_GROUP:"jieqi",TITLE:"谷雨",W_URL:["Hqwrfo2mA"],F_NAME: ["05guyu.jpg"],F_DESC:"一候，萍始生；<br>二候，鳴鳩拂其羽；<br>三候，戴勝降於桑。<br><br>穀父蠶母，雨臥風餐。<br>是名穀雨。<br>",},
{F_GROUP:"jieqi",TITLE:"立夏",W_URL:["HsXatsJiE"],F_NAME: ["10lixia.jpg"],F_DESC:"一候，螻蟈鳴；<br>二候，蚯蚓出；<br>三候，王瓜生。<br><br>淵亭山立，夏山如碧。<br>是名立夏。<br>",},
{F_GROUP:"jieqi",TITLE:"小满",W_URL:["HveGeiXtB"],F_NAME: ["11xiaoman.jpg"],F_DESC:"一候，苦菜秀；<br>二候，靡草死；<br>三候，麥秋至。<br><br>積小成大，始得盈滿。<br>是名小滿。<br>",},
{F_GROUP:"jieqi",TITLE:"芒种",W_URL:["Gk8L7fhB7","HxFZHyRdO"],F_NAME: ["12mangzhong.jpg"],F_DESC:"一候 螳螂生；<br>二候 鵬始鳴；<br>三候 反舌無聲。<br><br>芒寒色正，種玉藍田。<br>是名芒種。<br>",},
{F_GROUP:"jieqi",TITLE:"夏至",W_URL:["Gmq3BqJzQ","HzWXIxMiH"],F_NAME: ["13xiazhi.jpg"],F_DESC:"一候，鹿角解；<br>二候，蟬始鳴；<br>三候，半夏生。<br><br>無冬無夏，物至則反。<br>是名夏至。<br>",},
{F_GROUP:"jieqi",TITLE:"小暑",W_URL:["GoOirzTzu","HCkRZ7kPZ"],F_NAME: ["14xiaoshu.jpg"],F_DESC:"一候，溫風至；<br>二候，蟋蟀居宇；<br>三候，鷹始鷙。<br><br>炎天暑月，不修小節。<br>是名小暑。<br>",},
{F_GROUP:"jieqi",TITLE:"大暑",W_URL:["Gra1kn7yq","HEMhIoWM6"],F_NAME: ["15dashu.jpg"],F_DESC:"一候，腐草為螢；<br>二候，土潤溽暑；<br>三候，大雨時行。<br><br>大處落墨，暑雨荷鳴。<br>是名大暑。<br>",},
{F_GROUP:"jieqi",TITLE:"立秋",W_URL:["GtrqO0XUX","I1fE0D1eZ"],F_NAME: ["20liqiu.jpg"],F_DESC:"一候，涼風至；<br>二候，白露生；<br>三候，寒蟬鳴。<br><br>一葉知秋，不立文字。<br>是名立秋。<br>",},
{F_GROUP:"jieqi",TITLE:"处暑",W_URL:["GvZwTmOMy","I3xj4wJ1p"],F_NAME: ["21chushu.jpg"],F_DESC:"一候，鷹乃祭鳥；<br>二候，天地始肅；<br>三候，禾乃登。<br><br>殘陽斷暑，處變不驚。<br>是名處暑。<br>",},
{F_GROUP:"jieqi",TITLE:"白露",W_URL:["GypM2z32s","I5XNyDm3O"],F_NAME: ["22bailu.jpg"],F_DESC:"一候，鴻雁來；<br>二候，玄鳥歸；<br>三候，群鳥養羞。<br><br>白雲蒼狗，朝露曇花。<br>是名白露。<br>",},
{F_GROUP:"jieqi",TITLE:"秋分",W_URL:["GAFjEskyT","I8fcRkqd9"],F_NAME: ["23qiufen.jpg"],F_DESC:"一候，雷始收聲；<br>二候，蟄蟲坯戶；<br>三候，水始涸。<br><br>華星秋月，裂土分茅。<br>是名秋分。​​​​<br>",},
{F_GROUP:"jieqi",TITLE:"寒露",W_URL:["GCZbfokzd","IawDA6bMB"],F_NAME: ["24hanlu.jpg"],F_DESC:"一候，鴻雁來賓；<br>二候，雀入大水為蛤；<br>三候，菊有黃華。<br><br>啼饑號寒，風燭草露 。<br>是名寒露。<br>",},
{F_GROUP:"jieqi",TITLE:"霜降",W_URL:["GFgp3zqSX","IcXtBfxaU"],F_NAME: ["25shuangjiang.jpg"],F_DESC:"一候，豺乃祭獸；<br>二候，草木黃落；<br>三候，蜇蟲咸俯。<br><br>降心下氣，戴霜履冰。<br>是名霜降。<br>",},
{F_GROUP:"jieqi",TITLE:"立冬",W_URL:["H1Akzz0Hn","IfeSsbjy7"],F_NAME: ["30lidong.jpg"],F_DESC:"一候，水始冰；<br>二候，地始凍；<br>三候，雉入大水為蜃。<br><br>煢煢孑立，冬山如睡。<br>是名立冬。<br>",},
{F_GROUP:"jieqi",TITLE:"小雪",W_URL:["H3S4Yr4Jx","IhmRZw788"],F_NAME: ["31xiaoxue.jpg"],F_DESC:"一候，虹藏不見；<br>二候，天氣上升、地氣下降；<br>三候，閉塞而成冬。<br><br>山高月小，雪魄冰魂 。<br>是名小雪。<br>",},
{F_GROUP:"jieqi",TITLE:"大雪",W_URL:["H69JVfhKB","IjElEzkqE"],F_NAME: ["32daxue.jpg"],F_DESC:"一候，鹖鴠不鳴；<br> 二候，虎始交；三候，荔挺出。<br><br>大賢虎變，雪爪鴻泥。<br>是名大雪。 <br>​​​​",},
{F_GROUP:"jieqi",TITLE:"冬至",W_URL:["H8qAXDYWa","IlVTCsTTy"],F_NAME: ["33dongzhi.jpg"],F_DESC:"一候，蚯蚓結；<br>二候，麋角解；<br>三候，水泉動。<br><br>數九寒冬，至於此極。<br><br>是名冬至。<br>",},
{F_GROUP:"jieqi",TITLE:"小寒",W_URL:["HazV8uLwd","Iod4XoZxD"],F_NAME: ["34xiaohan.jpg"],F_DESC:"一候，雁北鄉；<br>二候，鵲始巢；<br>三候，雉始鴝。<br><br>一尺寒光，造化小兒。<br>是名小寒。<br>",},
{F_GROUP:"jieqi",TITLE:"大寒",W_URL:["HcRHE2TqN","IqoPMeGaV"],F_NAME: ["35dahan.jpg"],F_DESC:"一候，雞乳；<br>二候，徵鳥厲疾；<br>三候，水澤腹堅。<br><br>啼饑號寒，居大不易。<br>是名大寒。<br>",},


{F_GROUP:"shufa",S_GROUP:"魏晋南北",TITLE:"三国 钟繇 淳化阁帖宣示表",W_URL:["Hguh6Axau"],F_NAME: ["Zchg.jpg"],F_DESC:"其文如下：<br><br>尚书宣示孙权所求，诏令所报，所以博示。逮于卿佐，必冀良方出于阿是。刍荛之言可择廊庙，况繇始以疏贱，得为前恩。横所盱睨，公私见异，爱同骨肉，殊遇厚宠，以至今日。再世荣名，同国休戚，敢不自量。窃致愚虑，仍日达晨，坐以待旦，退思鄙浅。圣意所弃，则又割意，不敢献闻。深念天下，今为已平，权之委质，外震神武。度其拳拳，无有二计。高尚自疏，况未见信。今推款诚，欲求见信，实怀不自信之心，亦宜待之以信，而当护其未自信也。其所求者，不可不许，许之而反，不必可与，求之而不许，势必自绝，许而不与，其曲在己。里语曰：何以罚？与之夺；何以怒？许不与。思省所示报权疏，曲折得宜，宜神圣之虑。非今臣下所能有增益，昔与文若奉事先帝，事有数者，有似于此。粗表二事，以为今者事势，尚当有所依违愿君思省。若以在所虑可，不须复貌。节度唯君，恐不可采，故不自拜表。<br>",},
{F_GROUP:"shufa",S_GROUP:"魏晋南北",TITLE:"东晋 王珣 伯远帖",W_URL:["GD94T9MRo"],},
{F_GROUP:"shufa",S_GROUP:"魏晋南北",TITLE:"东晋 王献之 中秋帖",W_URL:["GD65InEHL"],},
{F_GROUP:"shufa",S_GROUP:"魏晋南北",TITLE:"东晋 王羲之 兰亭集序",W_URL:["GCdyICmzK"],},
{F_GROUP:"shufa",S_GROUP:"魏晋南北",TITLE:"东晋 王羲之 游目帖",W_URL:["GBJp71ttc"],},
{F_GROUP:"shufa",S_GROUP:"魏晋南北",TITLE:"东晋 王羲之 快雪时晴帖",W_URL:["GBDFgo8Ds"],},
{F_GROUP:"shufa",S_GROUP:"魏晋南北",TITLE:"东晋 王羲之 远宦帖",W_URL:["GBzLHopQp"],},
{F_GROUP:"shufa",S_GROUP:"魏晋南北",TITLE:"东晋 王羲之 平安帖",W_URL:["GF95PuS3i"],},
{F_GROUP:"shufa",S_GROUP:"魏晋南北",TITLE:"东晋 王羲之 姨母帖",W_URL:["GDtatoF1z"],},
{F_GROUP:"shufa",S_GROUP:"隋唐五代",TITLE:"唐 欧阳询 梦奠帖",W_URL:["GD96xmvgp"],},
{F_GROUP:"shufa",S_GROUP:"隋唐五代",TITLE:"唐 欧阳询 张翰帖",W_URL:["GE53DoZeq"],},
{F_GROUP:"shufa",S_GROUP:"隋唐五代",TITLE:"唐 颜真卿 祭侄文稿",W_URL:["GCRQTv4rx"],},
{F_GROUP:"shufa",S_GROUP:"隋唐五代",TITLE:"唐 柳公权 蒙诏帖",W_URL:["H2PNb4HxV"],F_NAME: ["Lmzt.jpg"],F_DESC:"全文如下：<br><br>公权蒙诏，出守翰林，<br>职在闲冷，亲情嘱托，<br>谁肯响应，深察感幸。<br>公权呈。<br>",LINK: "paint/蒙诏帖",},
{F_GROUP:"shufa",S_GROUP:"隋唐五代",TITLE:"唐 钟绍京 灵飞经 之 正月二月",W_URL:["H1VELkelq"],},
{F_GROUP:"shufa",S_GROUP:"隋唐五代",TITLE:"唐 钟绍京 灵飞经 之 四月五月",W_URL:["H7Yuabs6P"],},
{F_GROUP:"shufa",S_GROUP:"隋唐五代",TITLE:"唐 李白 上阳台帖",W_URL:["GClbNr6Qa"],},
{F_GROUP:"shufa",S_GROUP:"隋唐五代",TITLE:"唐 陆柬之 文赋 首段",W_URL:["H6BxigXPL"],F_NAME: ["Lwf1.jpg"],F_DESC:"全文如下：<br><br>余每观才士之所作，窃有以得其用心。夫放言谴辞，良多变矣，妍蚩好恶，可得而言。每自属文，尤见其情。恒患意不称物，文不逮意。盖非知之难，能之难也。故作《文赋》，以述先士之盛藻，因论作文之利害所由，他日殆可谓曲尽其妙。至于操斧伐柯，虽取则不远，若夫随手之变，良难以辞逮。盖所能言者具于此云。<br>",LINK: "paint/文赋",},
{F_GROUP:"shufa",S_GROUP:"隋唐五代",TITLE:"唐末五代 杨凝式 韭花帖",W_URL:["GEGC9nWUa"],},
{F_GROUP:"shufa",S_GROUP:"宋",TITLE:"北宋 米芾 蜀素帖 拟古",W_URL:["GDih3qQe7"],},
{F_GROUP:"shufa",S_GROUP:"宋",TITLE:"北宋 米芾 蜀素帖 吴江垂虹亭作",W_URL:["GDVIlwckL"],},
{F_GROUP:"shufa",S_GROUP:"宋",TITLE:"北宋 米芾 元日帖",W_URL:["H9XupFBs6"],},
{F_GROUP:"shufa",S_GROUP:"宋",TITLE:"北宋 米芾 参政帖",W_URL:["Hqx58nZCa"],F_NAME: ["Mczt.jpg"],F_DESC:"全文如下：<br><br>苏太简参政家物，多著，<br>邳公之后四代相印，或用，<br>翰林学士院印。芾记。<br>",},
{F_GROUP:"shufa",S_GROUP:"宋",TITLE:"北宋 蔡襄 澄心堂帖",W_URL:["H5gpe48I9"],},
{F_GROUP:"shufa",S_GROUP:"宋",TITLE:"北宋 黄庭坚 松风阁",W_URL:["H2VbCzpgt"],},
{F_GROUP:"shufa",S_GROUP:"宋",TITLE:"北宋 范仲淹 二札帖",W_URL:["GDLZZda8E"],},
{F_GROUP:"shufa",S_GROUP:"宋",TITLE:"北宋 苏轼 黄州寒食帖",W_URL:["GCnBcgHkz"],},
{F_GROUP:"shufa",S_GROUP:"宋",TITLE:"北宋 欧阳修 灼艾帖",W_URL:["H3Pq0gkAh"],},
{F_GROUP:"shufa",S_GROUP:"宋",TITLE:"北宋 曾巩 局事帖",W_URL:["H4OP3wcbf"],},
{F_GROUP:"shufa",S_GROUP:"宋",TITLE:"北宋 司马光 神采帖",W_URL:["H8QqTgvu8"],},
{F_GROUP:"shufa",S_GROUP:"宋",TITLE:"北宋 李建中 土母帖",W_URL:["GEnFVuaWT"],},
{F_GROUP:"shufa",S_GROUP:"宋",TITLE:"南宋 陆游 尊眷帖",W_URL:["HamYV2WXF"],F_NAME: ["zjt1.jpg","zjt2.jpg"],F_DESC:"全文如下：<br><br>游惶恐拜问契家尊眷，共惟并拥寿祺。<br>镜中有委敢请，子聿六粗能勤苦，但恨不能卒业。<br>函丈若不弃遗，尚未晚也。<br>张七三哥□贫可念，官期尚远，奈何。<br>每为之心折，顾无所置力耳。<br>三丈亦念之否。游惶恐再拜。<br>",LINK: "paint/尊眷帖",},
{F_GROUP:"shufa",S_GROUP:"宋",TITLE:"南宋 辛弃疾 去国帖",W_URL:["ImJsNidVb"],F_NAME: ["qgt.jpg"],F_DESC:"全文如下：<br><br>弃疾自秋初去国，倏忽见冬，詹咏之诚，朝夕不替。第缘驱驰到官，即专意督捕，日从事於兵车羽檄间，坐是倥偬，略无少暇。起居之问，缺然不讲，非敢懈怠，当蒙情亮也。指吴会云间，未龟合并。心旌所向，坐以神驰。右谨具呈。宣教郎新除秘阁修撰，权江南西路提点刑狱公事，辛弃疾札子。<br>",LINK: "paint/去国帖",},
{F_GROUP:"shufa",S_GROUP:"宋",TITLE:"南宋 文天祥 陋室铭",W_URL:["HuLIx9dzP"],F_NAME: ["Wlsm.jpg"],F_DESC:"全文如下：<br><br>山不在高，有仙则名。<br>水不在深，有龙则灵。<br>斯是陋室，惟吾德馨。<br>苔痕上阶绿，草色入帘青。<br>谈笑有鸿儒，往来无白丁。<br>可以调素琴，阅金经。<br>无丝竹之乱耳，无案牍之劳形。<br>南阳诸葛庐，西蜀子云亭。<br>孔子云：何陋之有？<br>",LINK: "paint/陋室铭",},
{F_GROUP:"shufa",S_GROUP:"宋",TITLE:"南宋 文天祥 草书木鸡集序卷",W_URL:["Hi0G3acYU"],F_NAME: ["Wcsmjjxj.jpg"],F_DESC:"其文如下：<br><br>三百五篇，优柔而笃厚，选出焉，故极其平易，而极不易学。予嘗讀詩, 以選求之。如曰：駕言陟崔嵬。我馬何虺隤。我姑酌金罍。维以不永怀。如曰：自子之東方，我首如飞蓬。 豈無膏与沭。为誰作春容。詩非選也。而詩未嘗不選。以此見選实出於詩，特從魏而下，多作五言耳。故嘗谓学選而以選为法。則選为吾祖宗以詩求選，則吾視選为兄弟之国。予言之而莫予信也。一日，吉水张彊宗甫以木雞集示予，何其酷似選也。从宗甫道予素，宗甫欣然。便有平视曹劉沈謝意思。三百五篇，家有其书，子歸而求之，所謂吾道东矣。咸淳癸酉长至，里友人文天祥书于楚观。<br>",},
{F_GROUP:"shufa",S_GROUP:"元明",TITLE:"元 赵孟頫 秋声赋",W_URL:["GBVAkEbTJ"],},
{F_GROUP:"shufa",S_GROUP:"元明",TITLE:"元 赵孟頫 心经",W_URL:["H0yd0iAoJ"],},
{F_GROUP:"shufa",S_GROUP:"元明",TITLE:"元 赵孟頫 望江南净土词",W_URL:["HiUZWrxjk"],F_NAME: ["Zwjnjtc1.jpg"],F_DESC:"其文如下：<br><br>西方好，群鸟美音声。华下和鸣歌六度，光中哀雅攒三乘。闻者悟无生。<br>三恶道，犹自不知名。皆是佛慈亲变化，欲宣法语警迷情。心地顿圆明。<br>",},
{F_GROUP:"shufa",S_GROUP:"元明",TITLE:"元 赵孟頫 玄都坛歌",W_URL:["Hoq3qlHk5"],F_NAME: ["Zxdtg.jpg"],F_DESC:"其文如下：<br><br>玄都坛歌<br><br>故人昔隐东蒙峰，已佩含景苍精龙。<br>故人今居子午谷，独在阴崖结茅屋。<br>屋前太古玄都坛，青石漠漠常风寒。<br>子规夜啼山竹裂，王母昼下云旗翻。<br>知君此计成长往，芝草琅玕日应长。<br>铁锁高垂不可攀，致身福地何萧爽。<br><br>大德十年正月十八日，<br>南谷尊师过我车桥之馆。<br>要写古诗，乃书此篇。<br><br>",LINK: "paint/玄都坛歌",},
{F_GROUP:"shufa",S_GROUP:"元明",TITLE:"元 赵孟頫 真草千文 卷首",W_URL:["HdiLJwdDh"],},
{F_GROUP:"shufa",S_GROUP:"元明",TITLE:"元 赵孟頫 吴兴赋",W_URL:["HgvLLyF58"],F_NAME: ["Zwxf1.jpg"],},
{F_GROUP:"shufa",S_GROUP:"元明",TITLE:"元 王冕 梅花诗",W_URL:["HrTiyu6SV"],F_NAME: ["Wmhs.jpg"],F_DESC:"全文如下：<br><br>吾家洗砚池头树，<br>个个花开淡墨痕。<br>不要人夸好颜色，<br>只流清气满乾坤。<br>",LINK: "paint/墨梅·吾家洗研池头树",},
{F_GROUP:"shufa",S_GROUP:"元明",TITLE:"明 文徵明 陋室铭",W_URL:["GDCHO0kML"],},
{F_GROUP:"shufa",S_GROUP:"元明",TITLE:"明 文徵明 游石湖追和徐天全满庭芳",W_URL:["Hj24IDOnS"],F_NAME: ["Wmtf.jpg"],F_DESC:"岸柳霏烟 溪桃炫昼",},
{F_GROUP:"shufa",S_GROUP:"元明",TITLE:"明 徐渭 珮几不须长",W_URL:["Hmzj3CcbR"],F_NAME: ["Xpjbxc.jpg"],F_DESC:"其文如下：<br><br>珮几不须长，高唐侍楚王。红蘅椠边出，白雪口中翔。听青供不及，一夜白潇湘。天池。<br>",},
{F_GROUP:"shufa",S_GROUP:"元明",TITLE:"明 陈继儒 小窗幽记",W_URL:["HlvGluV22"],F_NAME: ["Cxcyj1.jpg"],F_DESC:"全文如下：<br><br>竹篱茅舍，石屋花轩，松柏群吟，藤萝翳景，流水绕户，飞泉挂簷，烟霞欲栖，林壑将瞑，中处野叟山翁四五，予以闲身，作此中主人。<br>",},
{F_GROUP:"shufa",S_GROUP:"清至近代",TITLE:"近代 黄帝纪元帖",W_URL:["GDjms0qnx"],},
{F_GROUP:"shufa",S_GROUP:"清至近代",TITLE:"近代 林徽因 李成江村秋晚",W_URL:["HEcVchgFs"],F_NAME: ["Llcjcsw.jpg"],F_DESC:"<br><br>元·吴镇 《李成江村秋晚》全文如下：<br><br>咸熙画图无与共，传世希微爱者众。<br>二李之后已寥寥，宣和当日尤珍重。<br>新图一旦落人间，神宫寂寞何时还。<br>经营意匠出尘表，上下五百谁能攀。<br>水回中有渔舟泊，山顶崇台招白鹤。<br>篱根浮出水潺潺，万竹琳琅奏天乐。<br>霜飞木落一天秋，栖禽向晚声啾啾。<br>柳溪错认渊明宅，过桥岂是王弘俦。<br>景色萧条如太古，路僻村深贮烟雾。<br>分明再见辋川人，芜词何敢轻为附。<br>清容自是鉴赏家，持将却向天之涯。<br>几回试展未能去，落尽庭前无数花。<br>",},
{F_GROUP:"shufa",S_GROUP:"清至近代",TITLE:"近代 佚名 道德经",W_URL:["Hhon24zhh"],F_NAME: ["Yddj1.jpg"],},
{F_GROUP:"shufa",S_GROUP:"海外",TITLE:"梵高 开花的梅树",W_URL:["HmGqldSKd"],F_NAME: ["Fkhdms.jpg"],F_DESC:"其文如下：<br><br>大黑屋锦木江户町一丁目<br>新吉原大丁耳屋木<br>",},



{F_GROUP:"guhua",S_GROUP:"先秦两汉",TITLE:"西汉 瓦当",W_URL:["GoOirzTzu"],},
{F_GROUP:"guhua",S_GROUP:"先秦两汉",TITLE:"东汉 护乌桓校尉 牧马图 局部",W_URL:["GzMZOkSaV"],},

{F_GROUP:"guhua",S_GROUP:"魏晋南北",TITLE:"东晋 佚名 竹林七贤与荣启期",W_URL:["H370Qz2Oh"],},
{F_GROUP:"guhua",S_GROUP:"魏晋南北",TITLE:"东晋 顾恺之 洛神赋图A 文鱼",W_URL:["Gw8OGk13u"],},
{F_GROUP:"guhua",S_GROUP:"魏晋南北",TITLE:"东晋 顾恺之 洛神赋图A 车殆马烦",W_URL:["GwgfkxSYq"],},
{F_GROUP:"guhua",S_GROUP:"魏晋南北",TITLE:"东晋 顾恺之 洛神赋图B 文鱼",W_URL:["H9c7s01gd"],},
{F_GROUP:"guhua",S_GROUP:"魏晋南北",TITLE:"东晋 顾恺之 洛神赋图B 洛神之一",W_URL:["H9kXndXAq"],},
{F_GROUP:"guhua",S_GROUP:"魏晋南北",TITLE:"东晋 顾恺之 洛神赋图B 车殆马烦",W_URL:["H9kSK12hc"],},
{F_GROUP:"guhua",S_GROUP:"魏晋南北",TITLE:"东晋 顾恺之 女史箴图 局部",W_URL:["GzXeP2Pto"],},

{F_GROUP:"guhua",S_GROUP:"隋唐五代",TITLE:"唐 阎立本 步辇图 之 通译者",W_URL:["GxkDRCS1C"],},
{F_GROUP:"guhua",S_GROUP:"隋唐五代",TITLE:"唐 王维 伏生授经图",W_URL:["Gwpei40LB"],},
{F_GROUP:"guhua",S_GROUP:"隋唐五代",TITLE:"唐 韩滉 五牛图 之三",W_URL:["Gw1FUfzUv"],},
{F_GROUP:"guhua",S_GROUP:"隋唐五代",TITLE:"唐 韩滉 五牛图 之四",W_URL:["GvIGp7aEj"],},
{F_GROUP:"guhua",S_GROUP:"隋唐五代",TITLE:"唐 吴道子 送子天王图 局部",W_URL:["GvoIDptV0"],},
{F_GROUP:"guhua",S_GROUP:"隋唐五代",TITLE:"唐 韓乾 照夜白",W_URL:["GvlACyZFy"],},
{F_GROUP:"guhua",S_GROUP:"隋唐五代",TITLE:"唐 章怀太子墓 观鸟捕蝉图",W_URL:["GAhCkD691"],},
{F_GROUP:"guhua",S_GROUP:"隋唐五代",TITLE:"五代 顾闳中 韩熙载夜宴图 局部",W_URL:["GvEoYxvJj"],},
{F_GROUP:"guhua",S_GROUP:"隋唐五代",TITLE:"五代 周文矩 苏李别意卷 局部",W_URL:["HbjT3zBxm"],},

{F_GROUP:"guhua",S_GROUP:"宋",TITLE:"北宋 王希孟 千里江山图 局部 桥",W_URL:["Gxdd4wF4F"],},
{F_GROUP:"guhua",S_GROUP:"宋",TITLE:"北宋 王希孟 千里江山图 局部 船",W_URL:["GzbNs4ZKA"],},
{F_GROUP:"guhua",S_GROUP:"宋",TITLE:"北宋 崔白 禽兔图 局部",W_URL:["GyJKhdXTs"],},
{F_GROUP:"guhua",S_GROUP:"宋",TITLE:"北宋 苏东坡 枯木怪石图",W_URL:["GC3uglTV5"],},
{F_GROUP:"guhua",S_GROUP:"宋",TITLE:"北宋 徐崇嗣 鼠戏图 局部",W_URL:["GBjstndQQ"],},
{F_GROUP:"guhua",S_GROUP:"宋",TITLE:"北宋 张择端 清明上河图 赶牛人",W_URL:["GA6mnkve1"],},
{F_GROUP:"guhua",S_GROUP:"宋",TITLE:"北宋 刘寀 群鱼戏瓣图卷 局部",W_URL:["GFJs8lk31"],},
{F_GROUP:"guhua",S_GROUP:"宋",TITLE:"南宋 李唐 万壑松风图 局部",W_URL:["GwIneiYEM"],},
{F_GROUP:"guhua",S_GROUP:"宋",TITLE:"南宋 林椿 果熟来禽图",W_URL:["H5xJr3GIp"],},
{F_GROUP:"guhua",S_GROUP:"宋",TITLE:"南宋 林椿 枇杷山鸟图",W_URL:["H92Z8q3oY"],},
{F_GROUP:"guhua",S_GROUP:"宋",TITLE:"南宋 马远 水图卷 之三",W_URL:["GvR4Lv0wQ"],},
{F_GROUP:"guhua",S_GROUP:"宋",TITLE:"南宋 马远 寒江独钓图",W_URL:["GzisFwPWR"],},
{F_GROUP:"guhua",S_GROUP:"宋",TITLE:"南宋 马远 踏歌图 局部",W_URL:["GyHa5Fl5Y"],},
{F_GROUP:"guhua",S_GROUP:"宋",TITLE:"南宋 钱选 桃枝松鼠图",W_URL:["GyZyyySU1"],},
{F_GROUP:"guhua",S_GROUP:"宋",TITLE:"宋元 龚开 中山出游图 局部",W_URL:["GAqKUsMt1"],},

{F_GROUP:"guhua",S_GROUP:"元",TITLE:"元 吴镇 墨竹谱 之 轻荫护绿苔",W_URL:["GxOHR6cFt"],},
{F_GROUP:"guhua",S_GROUP:"元",TITLE:"元 吴镇 渔夫图卷 局部",W_URL:["GzB7t7AEm"],},
{F_GROUP:"guhua",S_GROUP:"元",TITLE:"元 赵孟頫 幽篁戴胜图",W_URL:["GxZRE7Qxx"],},
{F_GROUP:"guhua",S_GROUP:"元",TITLE:"元 赵孟頫 鹊华秋色图",W_URL:["GAAqoFjyG"],},
{F_GROUP:"guhua",S_GROUP:"元",TITLE:"元 王冕 白雪梅花枝",W_URL:["GxmyviKRA"],},
{F_GROUP:"guhua",S_GROUP:"元",TITLE:"元 倪瓚 松林亭子图 局部",W_URL:["Gzum0cGHN"],},

{F_GROUP:"guhua",S_GROUP:"明",TITLE:"明 沈周 写生册 之 喵饼",W_URL:["GyrFpClEO"],},
{F_GROUP:"guhua",S_GROUP:"明",TITLE:"明 沈周 写生册 之 母鸡",W_URL:["GyxcUnSOw"],},
{F_GROUP:"guhua",S_GROUP:"明",TITLE:"明 徐渭 墨花九段图卷 之 水仙竹",W_URL:["GyeXp1kUz"],},
{F_GROUP:"guhua",S_GROUP:"明",TITLE:"明 徐渭 鱼蟹图 之 蟹",W_URL:["Gye79wHzY"],},
{F_GROUP:"guhua",S_GROUP:"明",TITLE:"明 徐渭 驴背吟诗图轴",W_URL:["HapG5ECto"],},
{F_GROUP:"guhua",S_GROUP:"明",TITLE:"明 文徵明 湘君湘夫人图",W_URL:["GxFymijyc"],},
{F_GROUP:"guhua",S_GROUP:"明",TITLE:"明 陈洪绶 画鸟草虫册 之 蜗牛",W_URL:["H1rkvxfVQ"],},
{F_GROUP:"guhua",S_GROUP:"明",TITLE:"明 仇英 汉宫春晓图 局部",W_URL:["GwVGzcWna"],},
{F_GROUP:"guhua",S_GROUP:"明",TITLE:"明 仇英 桃源仙境图 局部",W_URL:["GzKGjDsDT"],},
{F_GROUP:"guhua",S_GROUP:"明",TITLE:"明 唐寅 溪山渔隐图 局部",W_URL:["Gz8VQfhU7"],},
{F_GROUP:"guhua",S_GROUP:"明",TITLE:"明 唐寅 吹箫仕女图",W_URL:["GB7Av9jt5"],},

{F_GROUP:"guhua",S_GROUP:"清",TITLE:"清 朱耷 猫石图 局部",W_URL:["GCI83hvAh"],},
{F_GROUP:"guhua",S_GROUP:"清",TITLE:"清 沈铨 百鸟朝凤图 局部",W_URL:["GCFQ3qqFW"],},
{F_GROUP:"guhua",S_GROUP:"清",TITLE:"清 华喦 花鸟草虫册页 之 蜥蜴",W_URL:["GFGLVoelB"],},
{F_GROUP:"guhua",S_GROUP:"清",TITLE:"清 恽寿平 百花图卷 菊花",W_URL:["GCwrozI6p"],},
{F_GROUP:"guhua",S_GROUP:"清",TITLE:"清 恽寿平 百花图卷 牡丹",W_URL:["GBzPHyOO4"],},

{F_GROUP:"other",TITLE:"秋千璧.gif",W_URL:["GsXgSkS7z"],},
{F_GROUP:"other",TITLE:"主页二维码甲",W_URL:["Gsl4l7hwF"],F_NAME:["ewm1.jpg"],},
{F_GROUP:"other",TITLE:"主页二维码乙",W_URL:["GsdTGgD2R"],F_NAME:["ewm2.jpg"],},


];