var myjson={
"RECORDS":[
{
"BUGS_ID":71,
"BUGS_ORDER":"半翅目",
"BUGS_NAME":"知了中",
"BUGS_TYPE":"普通知了",
"BUGS_PICS":"zhiliao01.jpg",
"BUGS_DESC":null
},
{
"BUGS_ID":91,
"BUGS_ORDER":"半翅目",
"BUGS_NAME":"椿象橙绿",
"BUGS_TYPE":null,
"BUGS_PICS":"chunxiang01.jpg",
"BUGS_DESC":null
},
{
"BUGS_ID":92,
"BUGS_ORDER":"半翅目",
"BUGS_NAME":"椿象灰",
"BUGS_TYPE":null,
"BUGS_PICS":"chunxiang02.jpg",
"BUGS_DESC":null
},
{
"BUGS_ID":93,
"BUGS_ORDER":"半翅目",
"BUGS_NAME":"椿象长腿",
"BUGS_TYPE":null,
"BUGS_PICS":"chunxiang03.jpg",
"BUGS_DESC":null
},
{
"BUGS_ID":117,
"BUGS_ORDER":"半翅目",
"BUGS_NAME":"水虫",
"BUGS_TYPE":null,
"BUGS_PICS":"shuichong.jpg",
"BUGS_DESC":null
},
{
"BUGS_ID":123,
"BUGS_ORDER":"半翅目",
"BUGS_NAME":"知了壳",
"BUGS_TYPE":"普通知了",
"BUGS_PICS":"zhiliaoke01.jpg",
"BUGS_DESC":null
},
{
"BUGS_ID":133,
"BUGS_ORDER":"半翅目",
"BUGS_NAME":"知了小",
"BUGS_TYPE":"普通知了",
"BUGS_PICS":"zhiliao02.jpg",
"BUGS_DESC":null
},
{
"BUGS_ID":153,
"BUGS_ORDER":"半翅目",
"BUGS_NAME":"虫壳",
"BUGS_TYPE":null,
"BUGS_PICS":"chongke01.jpg",
"BUGS_DESC":null
},
{
"BUGS_ID":73,
"BUGS_ORDER":"双翅目",
"BUGS_NAME":"按蚊",
"BUGS_TYPE":"按蚊",
"BUGS_PICS":"wen01.jpg",
"BUGS_DESC":"按蚊（Anopheles） 无脊椎动物。 体多呈灰色，翅有黑白花斑，刺吸式口器。静止时腹部翘起，与停落面成一角度。雌虫吸取人、畜的血，传播疟疾和丝虫病等。又称疟蚊。"
},
{
"BUGS_ID":87,
"BUGS_ORDER":"双翅目",
"BUGS_NAME":"蓝苍蝇",
"BUGS_TYPE":null,
"BUGS_PICS":"cangying01.jpg",
"BUGS_DESC":null
},
{
"BUGS_ID":72,
"BUGS_ORDER":"直翅目",
"BUGS_NAME":"蚂蚱灰",
"BUGS_TYPE":"小蚂蚱",
"BUGS_PICS":"mazha01.jpg",
"BUGS_DESC":null
},
{
"BUGS_ID":84,
"BUGS_ORDER":"直翅目",
"BUGS_NAME":"蚂蚱黑绿",
"BUGS_TYPE":null,
"BUGS_PICS":"mazha02.jpg",
"BUGS_DESC":null
},
{
"BUGS_ID":94,
"BUGS_ORDER":"直翅目",
"BUGS_NAME":"蚂蚱绿",
"BUGS_TYPE":"绿蚂蚱",
"BUGS_PICS":"mazha03.jpg",
"BUGS_DESC":null
},
{
"BUGS_ID":103,
"BUGS_ORDER":"直翅目",
"BUGS_NAME":"黑",
"BUGS_TYPE":null,
"BUGS_PICS":"zhichi03.jpg",
"BUGS_DESC":null
},
{
"BUGS_ID":108,
"BUGS_ORDER":"直翅目",
"BUGS_NAME":"绿",
"BUGS_TYPE":null,
"BUGS_PICS":"zhichi01.jpg",
"BUGS_DESC":null
},
{
"BUGS_ID":109,
"BUGS_ORDER":"直翅目",
"BUGS_NAME":"棕",
"BUGS_TYPE":null,
"BUGS_PICS":"zhichi02.jpg",
"BUGS_DESC":null
},
{
"BUGS_ID":143,
"BUGS_ORDER":"直翅目",
"BUGS_NAME":"蚂蚱会叫",
"BUGS_TYPE":null,
"BUGS_PICS":"mazha04.jpg",
"BUGS_DESC":null
},
{
"BUGS_ID":144,
"BUGS_ORDER":"直翅目",
"BUGS_NAME":"蚂蚱叶上",
"BUGS_TYPE":null,
"BUGS_PICS":"mazha05.jpg",
"BUGS_DESC":null
},
{
"BUGS_ID":149,
"BUGS_ORDER":"直翅目",
"BUGS_NAME":"蝈蝈",
"BUGS_TYPE":null,
"BUGS_PICS":"guoguo01.jpg",
"BUGS_DESC":null
},
{
"BUGS_ID":62,
"BUGS_ORDER":"膜翅目",
"BUGS_NAME":"蜜蜂1",
"BUGS_TYPE":"普通的蜜蜂",
"BUGS_PICS":"feng03.jpg",
"BUGS_DESC":null
},
{
"BUGS_ID":77,
"BUGS_ORDER":"膜翅目",
"BUGS_NAME":"蜜蜂2",
"BUGS_TYPE":"普通的蜜蜂",
"BUGS_PICS":"feng02.jpg",
"BUGS_DESC":null
},
{
"BUGS_ID":80,
"BUGS_ORDER":"膜翅目",
"BUGS_NAME":"黑蜂1",
"BUGS_TYPE":null,
"BUGS_PICS":"feng04.jpg",
"BUGS_DESC":null
},
{
"BUGS_ID":83,
"BUGS_ORDER":"膜翅目",
"BUGS_NAME":"黄白相间蜂",
"BUGS_TYPE":null,
"BUGS_PICS":"feng05.jpg",
"BUGS_DESC":null
},
{
"BUGS_ID":86,
"BUGS_ORDER":"膜翅目",
"BUGS_NAME":"黑蜂2",
"BUGS_TYPE":null,
"BUGS_PICS":"feng06.jpg",
"BUGS_DESC":null
},
{
"BUGS_ID":90,
"BUGS_ORDER":"膜翅目",
"BUGS_NAME":"亮腹",
"BUGS_TYPE":null,
"BUGS_PICS":"mochi01.jpg",
"BUGS_DESC":null
},
{
"BUGS_ID":116,
"BUGS_ORDER":"膜翅目",
"BUGS_NAME":"蜂小头棕",
"BUGS_TYPE":null,
"BUGS_PICS":"feng07.jpg",
"BUGS_DESC":null
},
{
"BUGS_ID":119,
"BUGS_ORDER":"膜翅目",
"BUGS_NAME":"红毛尾蜂",
"BUGS_TYPE":null,
"BUGS_PICS":"feng08.jpg",
"BUGS_DESC":null
},
{
"BUGS_ID":122,
"BUGS_ORDER":"膜翅目",
"BUGS_NAME":"窗蜂",
"BUGS_TYPE":null,
"BUGS_PICS":"feng09.jpg",
"BUGS_DESC":null
},
{
"BUGS_ID":128,
"BUGS_ORDER":"膜翅目",
"BUGS_NAME":"大蜂蚁",
"BUGS_TYPE":null,
"BUGS_PICS":"feng10.jpg",
"BUGS_DESC":null
},
{
"BUGS_ID":129,
"BUGS_ORDER":"膜翅目",
"BUGS_NAME":"蚊帐蜂",
"BUGS_TYPE":null,
"BUGS_PICS":"feng12.jpg",
"BUGS_DESC":null
},
{
"BUGS_ID":130,
"BUGS_ORDER":"膜翅目",
"BUGS_NAME":"食腐蜂",
"BUGS_TYPE":null,
"BUGS_PICS":"feng11.jpg",
"BUGS_DESC":null
},
{
"BUGS_ID":135,
"BUGS_ORDER":"膜翅目",
"BUGS_NAME":"长绿眼蜂",
"BUGS_TYPE":null,
"BUGS_PICS":"feng01.jpg",
"BUGS_DESC":null
},
{
"BUGS_ID":136,
"BUGS_ORDER":"膜翅目",
"BUGS_NAME":"对蜂",
"BUGS_TYPE":null,
"BUGS_PICS":"feng13.jpg",
"BUGS_DESC":null
},
{
"BUGS_ID":137,
"BUGS_ORDER":"膜翅目",
"BUGS_NAME":"小蜂采蜜",
"BUGS_TYPE":null,
"BUGS_PICS":"feng14.jpg",
"BUGS_DESC":null
},
{
"BUGS_ID":138,
"BUGS_ORDER":"膜翅目",
"BUGS_NAME":"绿眼蜂",
"BUGS_TYPE":null,
"BUGS_PICS":"feng15.jpg",
"BUGS_DESC":null
},
{
"BUGS_ID":139,
"BUGS_ORDER":"膜翅目",
"BUGS_NAME":"蜂窝",
"BUGS_TYPE":"蜂窝",
"BUGS_PICS":"fengwo01.jpg",
"BUGS_DESC":null
},
{
"BUGS_ID":142,
"BUGS_ORDER":"膜翅目",
"BUGS_NAME":"茑萝蚁",
"BUGS_TYPE":"茑萝蚁",
"BUGS_PICS":"niaoluoyi.jpg",
"BUGS_DESC":null
},
{
"BUGS_ID":85,
"BUGS_ORDER":"蜈蚣目",
"BUGS_NAME":"蜈蚣",
"BUGS_TYPE":null,
"BUGS_PICS":"wugong01.jpg",
"BUGS_DESC":"《本草纲目》曰：“蜈蚣，西南处处有之，春出冬蛰，节节有足，双须岐尾。”"
},
{
"BUGS_ID":152,
"BUGS_ORDER":"蜈蚣目",
"BUGS_NAME":"小蜈蚣",
"BUGS_TYPE":null,
"BUGS_PICS":"wugong02.jpg",
"BUGS_DESC":null
},
{
"BUGS_ID":74,
"BUGS_ORDER":"蜘蛛目",
"BUGS_NAME":"脸蛛",
"BUGS_TYPE":"脸蛛",
"BUGS_PICS":"zhu01.jpg",
"BUGS_DESC":null
},
{
"BUGS_ID":105,
"BUGS_ORDER":"蜘蛛目",
"BUGS_NAME":"夜树",
"BUGS_TYPE":null,
"BUGS_PICS":"zhu02.jpg",
"BUGS_DESC":null
},
{
"BUGS_ID":106,
"BUGS_ORDER":"蜘蛛目",
"BUGS_NAME":"竹根下",
"BUGS_TYPE":null,
"BUGS_PICS":"zhu03.jpg",
"BUGS_DESC":null
},
{
"BUGS_ID":107,
"BUGS_ORDER":"蜘蛛目",
"BUGS_NAME":"绿",
"BUGS_TYPE":null,
"BUGS_PICS":"zhu04.jpg",
"BUGS_DESC":null
},
{
"BUGS_ID":126,
"BUGS_ORDER":"蜘蛛目",
"BUGS_NAME":"蛛丝雨",
"BUGS_TYPE":"蛛丝雨",
"BUGS_PICS":"zhu05.jpg",
"BUGS_DESC":null
},
{
"BUGS_ID":146,
"BUGS_ORDER":"蜘蛛目",
"BUGS_NAME":"大花",
"BUGS_TYPE":null,
"BUGS_PICS":"zhu07.jpg",
"BUGS_DESC":null
},
{
"BUGS_ID":147,
"BUGS_ORDER":"蜘蛛目",
"BUGS_NAME":"毛腿",
"BUGS_TYPE":null,
"BUGS_PICS":"zhu06.jpg",
"BUGS_DESC":null
},
{
"BUGS_ID":148,
"BUGS_ORDER":"蜘蛛目",
"BUGS_NAME":"窝",
"BUGS_TYPE":null,
"BUGS_PICS":"zhizhuwo01.jpg",
"BUGS_DESC":null
},
{
"BUGS_ID":63,
"BUGS_ORDER":"蜻蜓目",
"BUGS_NAME":"褐斑蜻蜓",
"BUGS_TYPE":"褐斑蜻蜓",
"BUGS_PICS":"qingting01.jpg",
"BUGS_DESC":"雄虫胸部褐色；腹部橙色；翅膀除末端外为橙色。雌虫和未熟雄虫外观相似，但体色偏黄褐色；翅膀也是淡褐色。"
},
{
"BUGS_ID":64,
"BUGS_ORDER":"蜻蜓目",
"BUGS_NAME":"蓝蜻蜓",
"BUGS_TYPE":"蓝蜻蜓",
"BUGS_PICS":"qingting02.jpg",
"BUGS_DESC":null
},
{
"BUGS_ID":65,
"BUGS_ORDER":"蜻蜓目",
"BUGS_NAME":"背黄腹黑",
"BUGS_TYPE":"黄黑蜻蜓",
"BUGS_PICS":"qingting03.jpg",
"BUGS_DESC":null
},
{
"BUGS_ID":66,
"BUGS_ORDER":"蜻蜓目",
"BUGS_NAME":"黑白蜻蜓",
"BUGS_TYPE":"黑白蜻蜓",
"BUGS_PICS":"qingting04.jpg",
"BUGS_DESC":null
},
{
"BUGS_ID":67,
"BUGS_ORDER":"蜻蜓目",
"BUGS_NAME":"粉蜻蜓平",
"BUGS_TYPE":"粉蜻蜓",
"BUGS_PICS":"qingting05.jpg",
"BUGS_DESC":null
},
{
"BUGS_ID":68,
"BUGS_ORDER":"蜻蜓目",
"BUGS_NAME":"蓝黄蜻蜓",
"BUGS_TYPE":"蓝黄蜻蜓",
"BUGS_PICS":"qingting06.jpg",
"BUGS_DESC":null
},
{
"BUGS_ID":69,
"BUGS_ORDER":"蜻蜓目",
"BUGS_NAME":"黄蜻蜓",
"BUGS_TYPE":"黄蜻蜓",
"BUGS_PICS":"qingting07.jpg",
"BUGS_DESC":null
},
{
"BUGS_ID":70,
"BUGS_ORDER":"蜻蜓目",
"BUGS_NAME":"褐蜻蜓",
"BUGS_TYPE":"褐蜻蜓",
"BUGS_PICS":"qingting08.jpg",
"BUGS_DESC":null
},
{
"BUGS_ID":76,
"BUGS_ORDER":"蜻蜓目",
"BUGS_NAME":"黑黄相间",
"BUGS_TYPE":"黑黄相间",
"BUGS_PICS":"qingting09.jpg",
"BUGS_DESC":null
},
{
"BUGS_ID":79,
"BUGS_ORDER":"蜻蜓目",
"BUGS_NAME":"黑黄蓝眼",
"BUGS_TYPE":null,
"BUGS_PICS":"qingting10.jpg",
"BUGS_DESC":null
},
{
"BUGS_ID":120,
"BUGS_ORDER":"蜻蜓目",
"BUGS_NAME":"豆娘双",
"BUGS_TYPE":null,
"BUGS_PICS":"douniang01.jpg",
"BUGS_DESC":null
},
{
"BUGS_ID":121,
"BUGS_ORDER":"蜻蜓目",
"BUGS_NAME":"粉蜻蜓展",
"BUGS_TYPE":null,
"BUGS_PICS":"qingting11.jpg",
"BUGS_DESC":null
},
{
"BUGS_ID":145,
"BUGS_ORDER":"蜻蜓目",
"BUGS_NAME":"豆娘蓝翅",
"BUGS_TYPE":null,
"BUGS_PICS":"douniang02.jpg",
"BUGS_DESC":null
},
{
"BUGS_ID":131,
"BUGS_ORDER":"螳螂目",
"BUGS_NAME":"灰螳螂",
"BUGS_TYPE":null,
"BUGS_PICS":"tanglang01.jpg",
"BUGS_DESC":null
},
{
"BUGS_ID":34,
"BUGS_ORDER":"鞘翅目",
"BUGS_NAME":"天牛",
"BUGS_TYPE":"最常见的那种",
"BUGS_PICS":"tianniu01.jpg",
"BUGS_DESC":"小丛丛间拍到嗒。"
},
{
"BUGS_ID":35,
"BUGS_ORDER":"鞘翅目",
"BUGS_NAME":"十二星瓢虫",
"BUGS_TYPE":"十多颗星",
"BUGS_PICS":"piaochong01.jpg",
"BUGS_DESC":"吃叶子的。"
},
{
"BUGS_ID":41,
"BUGS_ORDER":"鞘翅目",
"BUGS_NAME":"芫菁",
"BUGS_TYPE":null,
"BUGS_PICS":"yuanjing01.jpg",
"BUGS_DESC":"芫菁 blister beetle 鞘翅目(Coleoptera)芫菁科(Meloidae)甲虫，约2,500种，会分泌出一种刺激性物质，称「斑蝥素」(cantharidin)，主要是从斑蝥属(Mylabris)和欧洲的西班牙芫菁(Lytta vesicatoria, 俗称西班牙苍蝇)收集而来。斑蝥素可用作一种局部皮肤发炎药剂，以除去皮疣。在过去，引出芫菁来医治许多病痛是一种普遍作法，斑蝥素常用来治病。它还是所谓的「春药」的主要成分。芫菁对人类既有益又有害，幼虫食蝗卵，而如果数量很多，成虫就会危害作物。"
},
{
"BUGS_ID":88,
"BUGS_ORDER":"鞘翅目",
"BUGS_NAME":"亮壳六白点",
"BUGS_TYPE":null,
"BUGS_PICS":"qiaochi01.jpg",
"BUGS_DESC":null
},
{
"BUGS_ID":89,
"BUGS_ORDER":"鞘翅目",
"BUGS_NAME":"黑壳两白点",
"BUGS_TYPE":null,
"BUGS_PICS":"qiaochi02.jpg",
"BUGS_DESC":null
},
{
"BUGS_ID":102,
"BUGS_ORDER":"鞘翅目",
"BUGS_NAME":"黑",
"BUGS_TYPE":null,
"BUGS_PICS":"qiaochi03.jpg",
"BUGS_DESC":null
},
{
"BUGS_ID":111,
"BUGS_ORDER":"鞘翅目",
"BUGS_NAME":"萤火虫",
"BUGS_TYPE":null,
"BUGS_PICS":"yinghuo01.jpg",
"BUGS_DESC":null
},
{
"BUGS_ID":104,
"BUGS_ORDER":"鞘翅目",
"BUGS_NAME":"黑翘",
"BUGS_TYPE":null,
"BUGS_PICS":"qiaochi04.jpg",
"BUGS_DESC":null
},
{
"BUGS_ID":110,
"BUGS_ORDER":"鞘翅目",
"BUGS_NAME":"棕",
"BUGS_TYPE":null,
"BUGS_PICS":"qiaochi05.jpg",
"BUGS_DESC":null
},
{
"BUGS_ID":118,
"BUGS_ORDER":"鞘翅目",
"BUGS_NAME":"锚纹瓢虫",
"BUGS_TYPE":null,
"BUGS_PICS":"piaochong02.jpg",
"BUGS_DESC":null
},
{
"BUGS_ID":127,
"BUGS_ORDER":"鞘翅目",
"BUGS_NAME":"多星瓢虫",
"BUGS_TYPE":"多颗星",
"BUGS_PICS":"piaochong03.jpg",
"BUGS_DESC":"吃叶子的。"
},
{
"BUGS_ID":132,
"BUGS_ORDER":"鞘翅目",
"BUGS_NAME":"黄",
"BUGS_TYPE":null,
"BUGS_PICS":"qiaochi06.jpg",
"BUGS_DESC":null
},
{
"BUGS_ID":134,
"BUGS_ORDER":"鞘翅目",
"BUGS_NAME":"西光奥锹甲",
"BUGS_TYPE":"西光奥锹甲",
"BUGS_PICS":"qiaochi07.jpg",
"BUGS_DESC":null
},
{
"BUGS_ID":150,
"BUGS_ORDER":"鞘翅目",
"BUGS_NAME":"黑肚翘",
"BUGS_TYPE":null,
"BUGS_PICS":"qiaochi08.jpg",
"BUGS_DESC":null
},
{
"BUGS_ID":151,
"BUGS_ORDER":"鞘翅目",
"BUGS_NAME":"黑长须",
"BUGS_TYPE":null,
"BUGS_PICS":"qiaochi09.jpg",
"BUGS_DESC":null
},
{
"BUGS_ID":47,
"BUGS_ORDER":"鳞翅目",
"BUGS_NAME":"粉蝶",
"BUGS_TYPE":"最常见的白蝴蝶",
"BUGS_PICS":"die01.jpg",
"BUGS_DESC":"到处都能看见。"
},
{
"BUGS_ID":54,
"BUGS_ORDER":"鳞翅目",
"BUGS_NAME":"凤蝶黑",
"BUGS_TYPE":null,
"BUGS_PICS":"die06.jpg",
"BUGS_DESC":null
},
{
"BUGS_ID":61,
"BUGS_ORDER":"鳞翅目",
"BUGS_NAME":"枯叶蝶",
"BUGS_TYPE":"叶子枯了",
"BUGS_PICS":"die03.jpg",
"BUGS_DESC":null
},
{
"BUGS_ID":75,
"BUGS_ORDER":"鳞翅目",
"BUGS_NAME":"长喙天蛾",
"BUGS_TYPE":null,
"BUGS_PICS":"die20.jpg",
"BUGS_DESC":null
},
{
"BUGS_ID":78,
"BUGS_ORDER":"鳞翅目",
"BUGS_NAME":"蓝白蝶",
"BUGS_TYPE":null,
"BUGS_PICS":"die02.jpg",
"BUGS_DESC":null
},
{
"BUGS_ID":81,
"BUGS_ORDER":"鳞翅目",
"BUGS_NAME":"眼纹蝶",
"BUGS_TYPE":null,
"BUGS_PICS":"die04.jpg",
"BUGS_DESC":null
},
{
"BUGS_ID":82,
"BUGS_ORDER":"鳞翅目",
"BUGS_NAME":"叶蝶",
"BUGS_TYPE":null,
"BUGS_PICS":"die05.jpg",
"BUGS_DESC":null
},
{
"BUGS_ID":95,
"BUGS_ORDER":"鳞翅目",
"BUGS_NAME":"蓝点白",
"BUGS_TYPE":null,
"BUGS_PICS":"die07.jpg",
"BUGS_DESC":null
},
{
"BUGS_ID":96,
"BUGS_ORDER":"鳞翅目",
"BUGS_NAME":"红蝶",
"BUGS_TYPE":null,
"BUGS_PICS":"die08.jpg",
"BUGS_DESC":null
},
{
"BUGS_ID":97,
"BUGS_ORDER":"鳞翅目",
"BUGS_NAME":"蛾长白",
"BUGS_TYPE":null,
"BUGS_PICS":"die09.jpg",
"BUGS_DESC":null
},
{
"BUGS_ID":98,
"BUGS_ORDER":"鳞翅目",
"BUGS_NAME":"黄点黑",
"BUGS_TYPE":null,
"BUGS_PICS":"die10.jpg",
"BUGS_DESC":null
},
{
"BUGS_ID":99,
"BUGS_ORDER":"鳞翅目",
"BUGS_NAME":"蛾灰",
"BUGS_TYPE":null,
"BUGS_PICS":"die11.jpg",
"BUGS_DESC":null
},
{
"BUGS_ID":100,
"BUGS_ORDER":"鳞翅目",
"BUGS_NAME":"黄黑白蝶",
"BUGS_TYPE":null,
"BUGS_PICS":"die12.jpg",
"BUGS_DESC":null
},
{
"BUGS_ID":101,
"BUGS_ORDER":"鳞翅目",
"BUGS_NAME":"黑点白",
"BUGS_TYPE":null,
"BUGS_PICS":"die13.jpg",
"BUGS_DESC":null
},
{
"BUGS_ID":112,
"BUGS_ORDER":"鳞翅目",
"BUGS_NAME":"黄黑相间",
"BUGS_TYPE":null,
"BUGS_PICS":"die14.jpg",
"BUGS_DESC":null
},
{
"BUGS_ID":113,
"BUGS_ORDER":"鳞翅目",
"BUGS_NAME":"黑一白条",
"BUGS_TYPE":null,
"BUGS_PICS":"die15.jpg",
"BUGS_DESC":null
},
{
"BUGS_ID":114,
"BUGS_ORDER":"鳞翅目",
"BUGS_NAME":"黑三白条",
"BUGS_TYPE":null,
"BUGS_PICS":"die16.jpg",
"BUGS_DESC":null
},
{
"BUGS_ID":115,
"BUGS_ORDER":"鳞翅目",
"BUGS_NAME":"黑白头黄",
"BUGS_TYPE":null,
"BUGS_PICS":"die17.jpg",
"BUGS_DESC":null
},
{
"BUGS_ID":124,
"BUGS_ORDER":"鳞翅目",
"BUGS_NAME":"红黄黑",
"BUGS_TYPE":null,
"BUGS_PICS":"die18.jpg",
"BUGS_DESC":null
},
{
"BUGS_ID":125,
"BUGS_ORDER":"鳞翅目",
"BUGS_NAME":"破草蝶",
"BUGS_TYPE":null,
"BUGS_PICS":"die19.jpg",
"BUGS_DESC":null
},
{
"BUGS_ID":140,
"BUGS_ORDER":"鳞翅目",
"BUGS_NAME":"白点黑",
"BUGS_TYPE":null,
"BUGS_PICS":"die21.jpg",
"BUGS_DESC":null
},
{
"BUGS_ID":141,
"BUGS_ORDER":"鳞翅目",
"BUGS_NAME":"黑凤蝶飞",
"BUGS_TYPE":null,
"BUGS_PICS":"die22.jpg",
"BUGS_DESC":null
}
]
};