var file=[

{"TITLE":"果熟来禽图","F_GROUP":"paint","S_GROUP":"交互","F_NAME":"bird01",},
{"TITLE":"洛神赋图","F_GROUP":"paint","S_GROUP":"交互·长卷","F_NAME":"scroll01",},
{"TITLE":"女史箴图","F_GROUP":"paint","S_GROUP":"交互·长卷","F_NAME":"scroll02",},
{"TITLE":"千里江山图","F_GROUP":"paint","S_GROUP":"交互·无限远","F_NAME":"deep01",},
{"TITLE":"富春山居图","F_GROUP":"paint","S_GROUP":"交互·无限远","F_NAME":"deep02",},
{"TITLE":"松林亭子","F_GROUP":"paint","S_GROUP":"3D交互","F_NAME":"scene01",},
{"TITLE":"千里江山图·廊桥","F_GROUP":"paint","S_GROUP":"3D交互","F_NAME":"scene02",},
{"TITLE":"独钓寒江图","F_GROUP":"paint","S_GROUP":"动图","F_NAME":"boat01",},
{"TITLE":"竹林七贤","F_GROUP":"paint","S_GROUP":"播放","F_NAME":"player02",},

{"TITLE":"竹简","F_GROUP":"set","S_GROUP":"交互","F_NAME":"jian01",},
{"TITLE":"纸扇","F_GROUP":"set","S_GROUP":"交互","F_NAME":"fan03",},
{"TITLE":"卷轴01","F_GROUP":"set","S_GROUP":"交互","F_NAME":"reel01","SHOW":"no",},
{"TITLE":"兰亭序卷轴","F_GROUP":"set","S_GROUP":"交互","F_NAME":"reel02",},
{"TITLE":"地图","F_GROUP":"set","S_GROUP":"交互","F_NAME":"map01","SHOW":"no",},
{"TITLE":"小盒子","F_GROUP":"set","S_GROUP":"交互","F_NAME":"box01",},
{"TITLE":"答题","F_GROUP":"set","S_GROUP":"交互","F_NAME":"dati01/index.html"},
{"TITLE":"微博","F_GROUP":"set","S_GROUP":"交互","F_NAME":"weibo","SHOW":"no",},
{"TITLE":"影视集","F_GROUP":"set","S_GROUP":"交互","F_NAME":"movie","SHOW":"no",},
{"TITLE":"长江千里图","F_GROUP":"set","S_GROUP":"交互·长卷","F_NAME":"scroll03","SHOW":"no",},
{"TITLE":"古堡","F_GROUP":"set","S_GROUP":"全景动图","F_NAME":"pano01",},
{"TITLE":"古台","F_GROUP":"set","S_GROUP":"全景动图","F_NAME":"pano02",},
{"TITLE":"古寺","F_GROUP":"set","S_GROUP":"全景动图","F_NAME":"pano03",},
{"TITLE":"月球车","F_GROUP":"set","S_GROUP":"全景动图","F_NAME":"pano04",},


{"TITLE":"芭妖的夏天","F_GROUP":"svg","S_GROUP":"交互","F_NAME":"bayaoxia.html",},
{"TITLE":"芭妖的樱桃","F_GROUP":"svg","S_GROUP":"交互","F_NAME":"yingtao.html","SHOW":"no",},
{"TITLE":"寒江雪Scroll","F_GROUP":"svg","S_GROUP":"交互","F_NAME":"Scroll01.html","SHOW":"no",},
{"TITLE":"TIOBE变迁","F_GROUP":"svg","S_GROUP":"动图","F_NAME":"datatiobe.html",},
{"TITLE":"GDP变迁","F_GROUP":"svg","S_GROUP":"动图","F_NAME":"datagdp.html",},
{"TITLE":"军运会","F_GROUP":"svg","S_GROUP":"动图","F_NAME":"junyunhui.html",},
{"TITLE":"小鸟时钟","F_GROUP":"svg","S_GROUP":"动图","F_NAME":"birdclock.html",},
{"TITLE":"微博集卡抽奖","F_GROUP":"svg","S_GROUP":"动图","F_NAME":"weibojkcj.html","SHOW":"no",},
{"TITLE":"火箭起飞01","F_GROUP":"svg","S_GROUP":"动图","F_NAME":"rocket01.html",},
{"TITLE":"疫情地图","F_GROUP":"svg","S_GROUP":"动图","F_NAME":"map-2019-nCoV.html",},
{"TITLE":"疫情地图Demo","F_GROUP":"svg","S_GROUP":"动图","F_NAME":"map-2019-nCoV-Demo.html","SHOW":"no",},
{"TITLE":"疫情地图Fujian","F_GROUP":"svg","S_GROUP":"动图","F_NAME":"map-2019-nCoV-Fujian.html","SHOW":"no",},
{"TITLE":"SARS疫情地图","F_GROUP":"svg","S_GROUP":"动图","F_NAME":"map-2003-SARS.html","SHOW":"no",},
{"TITLE":"四季01","F_GROUP":"svg","S_GROUP":"动图","F_NAME":"season01.html","SHOW":"no",},
{"TITLE":"下雪01","F_GROUP":"svg","S_GROUP":"动图","F_NAME":"snow01.html","SHOW":"no",},
{"TITLE":"寒江雪1","F_GROUP":"svg","S_GROUP":"动图","F_NAME":"hjx01.html","SHOW":"no",},
{"TITLE":"寒江雪3","F_GROUP":"svg","S_GROUP":"动图","F_NAME":"hjx03.html","SHOW":"no",},


{"TITLE":"小盒子","F_GROUP":"cb","S_GROUP":"交互","F_NAME":"box03",},
{"TITLE":"画圈璧","F_GROUP":"cb","S_GROUP":"交互","F_NAME":"cbhqq",},
{"TITLE":"围住璧","F_GROUP":"cb","S_GROUP":"交互","F_NAME":"weizhu01",},
{"TITLE":"丁丁喵","F_GROUP":"cb","S_GROUP":"交互","F_NAME":"ddm",},
{"TITLE":"手表","F_GROUP":"cb","S_GROUP":"动图","F_NAME":"watch03",},
{"TITLE":"念经璧","F_GROUP":"cb","S_GROUP":"播放","F_NAME":"player03",},
{"TITLE":"晴日共剪窗","F_GROUP":"cb","S_GROUP":"播放","F_NAME":"player01",},
{"TITLE":"2016","F_GROUP":"cb","S_GROUP":"地图","F_NAME":"cb2016",},
{"TITLE":"2017","F_GROUP":"cb","S_GROUP":"地图","F_NAME":"cb2017",},
{"TITLE":"2018","F_GROUP":"cb","S_GROUP":"地图","F_NAME":"cb2018",},
{"TITLE":"年谱","F_GROUP":"cb","S_GROUP":"时间轴","F_NAME":"cbtimeline",},
{"TITLE":"主页","F_GROUP":"cb","S_GROUP":"DEMO","F_NAME":"cbw","SHOW":"no",},


{"TITLE":"主页DEMO","F_GROUP":"test","S_GROUP":"其它","F_NAME":"01/01vuec.html"},
{"TITLE":"CCTV","F_GROUP":"test","S_GROUP":"其它","F_NAME":"cctv"},
{"TITLE":"小圆点","F_GROUP":"test","S_GROUP":"其它","F_NAME":"points.html"},
{"TITLE":"屏幕有效尺寸测试","F_GROUP":"test","S_GROUP":"其它","F_NAME":"screentest.html"},
{"TITLE":"小飞机","F_GROUP":"test","S_GROUP":"其它","F_NAME":"gsap/plane.html"},
];