var book=[{F_GROUP: "古籍",S_GROUP: "经",TITLE: "诗经",COUNTRY: "中",DYNASTY: "先秦",AUTHOR: "佚名",FILE: "file/",F_EVAL: "line.length<20 && (line.indexOf('风')==1 || line.indexOf('雅')==1 || line.indexOf('颂')==1)",},
{F_GROUP: "古籍",S_GROUP: "经",TITLE: "尚书",COUNTRY: "中",DYNASTY: "先秦",AUTHOR: "佚名",FILE: "file/",F_EVAL: "line.indexOf('　　')==0 && line.length<18 && line.indexOf('书')==3",},
{F_GROUP: "古籍",S_GROUP: "经",TITLE: "周礼",COUNTRY: "中",DYNASTY: "先秦",AUTHOR: "周公旦",FILE: "file/",F_EVAL: "line.length<20 && line.indexOf('.')==1"},
{F_GROUP: "古籍",S_GROUP: "经",TITLE: "仪礼",COUNTRY: "中",DYNASTY: "先秦",AUTHOR: "佚名",FILE: "file/",F_EVAL: "line.length<20 && line.indexOf('	')!=0 && line.indexOf('第')>2 && line.indexOf('第')<8", },
{F_GROUP: "古籍",S_GROUP: "经",TITLE: "礼记",COUNTRY: "中",DYNASTY: "西汉",AUTHOR: "戴圣",FILE: "file/",F_EVAL: "line.length<20 && line.indexOf('　　《礼记')==0",},
{F_GROUP: "古籍",S_GROUP: "经",TITLE: "周易",COUNTRY: "中",DYNASTY: "先秦",AUTHOR: "周文王",FILE: "file/",F_EVAL: "line.length<20 && line.indexOf('　　')==0 && line[4]=='.'",},
{F_GROUP: "古籍",S_GROUP: "经",TITLE: "春秋左传",COUNTRY: "中",DYNASTY: "先秦",AUTHOR: "左丘明",FILE: "file/",F_EVAL: "line.length<20 && line.indexOf('　　◇')==0",},
{F_GROUP: "古籍",S_GROUP: "经",TITLE: "春秋公羊传",COUNTRY: "中",DYNASTY: "先秦",AUTHOR: "公羊高",FILE: "file/",F_EVAL: "line.length<20 && line.indexOf('公（经')==3",},
{F_GROUP: "古籍",S_GROUP: "经",TITLE: "春秋谷梁传",COUNTRY: "中",DYNASTY: "先秦",AUTHOR: "谷梁赤",FILE: "file/",F_EVAL: "line.length<20 && line.indexOf('公（经')==3",},
{F_GROUP: "古籍",S_GROUP: "经",TITLE: "论语",COUNTRY: "中",DYNASTY: "先秦",AUTHOR: "孔子",FILE: "file/",F_EVAL: "line.length<20 && line.indexOf('第')==4",},
{F_GROUP: "古籍",S_GROUP: "经",TITLE: "尔雅",COUNTRY: "中",DYNASTY: "先秦",AUTHOR: "佚名",FILE: "file/",F_EVAL: "line.length<20 && line.indexOf('释')==2 && line.indexOf('第')==4",},
{F_GROUP: "古籍",S_GROUP: "经",TITLE: "孝经",COUNTRY: "中",DYNASTY: "秦",AUTHOR: "佚名",FILE: "file/",F_EVAL: "line.length<20 && line.indexOf('○')==2",},
{F_GROUP: "古籍",S_GROUP: "经",TITLE: "孟子",COUNTRY: "中",DYNASTY: "先秦",AUTHOR: "孟子",FILE: "file/",F_EVAL: "line.length<20 && line.indexOf('卷')==2",},
{F_GROUP: "古籍",S_GROUP: "史",TITLE: "史记",COUNTRY: "中",DYNASTY: "西汉",AUTHOR: "司马迁",FILE: "file/",F_EVAL: "line.length<35 && line.indexOf('卷')==0",},
{F_GROUP: "古籍",S_GROUP: "史",TITLE: "汉书",COUNTRY: "中",DYNASTY: "东汉",AUTHOR: "班固 班超",FILE: "filel/",F_EVAL: "line.length<35 && line.indexOf('卷')==0",},
{F_GROUP: "古籍",S_GROUP: "史",TITLE: "后汉书",COUNTRY: "中",DYNASTY: "魏晋南北朝",AUTHOR: "范晔",FILE: "filel/",F_EVAL: "line.length<35 && (line.indexOf('后汉书卷')==0 || line.indexOf('后汉书志')==0)"},
{F_GROUP: "古籍",S_GROUP: "史",TITLE: "三国志",COUNTRY: "中",DYNASTY: "魏晋南北朝",AUTHOR: "陈寿",FILE: "filel/",F_EVAL: "line.indexOf('志卷')==3 && line.indexOf('证')==-1",},
{F_GROUP: "古籍",S_GROUP: "史",TITLE: "晋书",COUNTRY: "中",DYNASTY: "隋唐五代",AUTHOR: "房玄龄",FILE: "filel/",F_EVAL: "line[0]!='　' && (line[1]=='第' || line[2]=='第')",},
{F_GROUP: "古籍",S_GROUP: "史",TITLE: "宋书",COUNTRY: "中",DYNASTY: "魏晋南北朝",AUTHOR: "沈约",FILE: "filel/",F_EVAL: "(line[1]=='第' || line[2]=='第') && line.length<30 && line.length>6",},
{F_GROUP: "古籍",S_GROUP: "史",TITLE: "南齐书",COUNTRY: "中",DYNASTY: "魏晋南北朝",AUTHOR: "萧子显",FILE: "file/",F_EVAL: "(line[1]=='第' || line[2]=='第') && line.length<30",},
{F_GROUP: "古籍",S_GROUP: "史",TITLE: "梁书",COUNTRY: "中",DYNASTY: "隋唐五代",AUTHOR: "姚思廉",FILE: "file/",F_EVAL: "(line[1]=='第' || line[2]=='第') && line.length<50 && line[0]!='　'",},
{F_GROUP: "古籍",S_GROUP: "史",TITLE: "陈书",COUNTRY: "中",DYNASTY: "隋唐五代",AUTHOR: "姚思廉",FILE: "file/",F_EVAL: "line[2]=='第' && line.length<30",},
{F_GROUP: "古籍",S_GROUP: "史",TITLE: "魏书",COUNTRY: "中",DYNASTY: "魏晋南北朝",AUTHOR: "魏收",FILE: "filel/",F_EVAL: "line[0]!='　' && (line[1]=='第' || line[2]=='第')",},
{F_GROUP: "古籍",S_GROUP: "史",TITLE: "北齐书",COUNTRY: "中",DYNASTY: "隋唐五代",AUTHOR: "李百药",FILE: "file/",F_EVAL: "line[0]=='第' && line.length<80",},
{F_GROUP: "古籍",S_GROUP: "史",TITLE: "周书",COUNTRY: "中",DYNASTY: "隋唐五代",AUTHOR: "令狐德棻",FILE: "file/",F_EVAL: "line[2]=='卷'",},
{F_GROUP: "古籍",S_GROUP: "史",TITLE: "隋书",COUNTRY: "中",DYNASTY: "隋唐五代",AUTHOR: "魏徵",FILE: "filel/",F_EVAL: "line[0]!='　' && (line[1]=='第' || line[2]=='第')",},
{F_GROUP: "古籍",S_GROUP: "史",TITLE: "南史",COUNTRY: "中",DYNASTY: "隋唐五代",AUTHOR: "李延寿",FILE: "filel/",F_EVAL: "line.indexOf('南史卷')>=0 && line.length<30",},
{F_GROUP: "古籍",S_GROUP: "史",TITLE: "北史",COUNTRY: "中",DYNASTY: "隋唐五代",AUTHOR: "李延寿",FILE: "filel/",F_EVAL: "(line[2]=='第' || line[3]=='第') && line.length<30",},
{F_GROUP: "古籍",S_GROUP: "史",TITLE: "旧唐书",COUNTRY: "中",DYNASTY: "隋唐五代",AUTHOR: "刘昫",FILE: "filel/",F_EVAL: "(line[3]=='第' || line[4]=='第' || line[2]=='●') && line.indexOf('。')<0 && line.indexOf('：')<0",},
{F_GROUP: "古籍",S_GROUP: "史",TITLE: "新唐书",COUNTRY: "中",DYNASTY: "北宋",AUTHOR: "欧阳修 宋祁",FILE: "filel/",F_EVAL: "(line[2]=='第' || line[3]=='第') && line.length<30 && line.length>6"},
{F_GROUP: "古籍",S_GROUP: "史",TITLE: "新五代史",COUNTRY: "中",DYNASTY: "北宋",AUTHOR: "欧阳修",FILE: "file/",F_EVAL: "line.length<30 && line.indexOf('第')>1 && line[0]!='	'",},
{F_GROUP: "古籍",S_GROUP: "史",TITLE: "旧五代史",COUNTRY: "中",DYNASTY: "北宋",AUTHOR: "薛居正",FILE: "file/",F_EVAL: "line.length<30 && line[0]!='	' && line.indexOf('。')<0 && line.indexOf('：')<0 && line.indexOf('（')<0 && line.indexOf('-')<0",},
{F_GROUP: "古籍",S_GROUP: "史",TITLE: "宋史",COUNTRY: "中",DYNASTY: "元",AUTHOR: "脱脱",FILE: "filel/",F_EVAL: "(line[1]=='第' || line[2]=='第'|| line[3]=='第') && line.length<30 && line[0]!='　'",},
{F_GROUP: "古籍",S_GROUP: "史",TITLE: "辽史",COUNTRY: "中",DYNASTY: "元",AUTHOR: "脱脱",FILE: "file/",F_EVAL: "line[0]=='第'",},
{F_GROUP: "古籍",S_GROUP: "史",TITLE: "金史",COUNTRY: "中",DYNASTY: "元",AUTHOR: "脱脱",FILE: "filel/",F_EVAL: "(line[1]=='第' || line[2]=='第') && line.length<12",},
{F_GROUP: "古籍",S_GROUP: "史",TITLE: "元史",COUNTRY: "中",DYNASTY: "明",AUTHOR: "宋濂",FILE: "filel/",F_EVAL: "line[0]=='卷'",},
{F_GROUP: "古籍",S_GROUP: "史",TITLE: "明史",COUNTRY: "中",DYNASTY: "清",AUTHOR: "张廷玉",FILE: "filel/",F_EVAL: "(line[1]=='第' || line[2]=='第') && line.length<36 && line[0]!='　'",},
{F_GROUP: "古籍",S_GROUP: "史",TITLE: "清史稿",COUNTRY: "中",DYNASTY: "现代",AUTHOR: "赵尔巽",FILE: "filel/",F_EVAL: "(line.indexOf('本纪')==2 || line.indexOf('志')==2 || line.indexOf('表')==2 || line.indexOf('列传')==2) && line.length<20 && line.length>5 && line.indexOf('略')==-1",},
{F_GROUP: "古籍",S_GROUP: "史",TITLE: "战国策",COUNTRY: "中",DYNASTY: "先秦",AUTHOR: "佚名",FILE: "file/",F_EVAL: "line[0]=='卷'",},
{F_GROUP: "古籍",S_GROUP: "史",TITLE: "国语",COUNTRY: "中",DYNASTY: "先秦",AUTHOR: "左丘明",FILE: "file/",F_EVAL: "line[0]=='卷'",},
{F_GROUP: "古籍",S_GROUP: "史",TITLE: "竹书纪年",COUNTRY: "中",DYNASTY: "先秦",AUTHOR: "佚名",FILE: "file/",F_EVAL: "line[0]=='竹'",},
{F_GROUP: "古籍",S_GROUP: "史",TITLE: "资治通鉴",COUNTRY: "中",DYNASTY: "北宋",AUTHOR: "司马光",FILE: "filel/",F_EVAL: "line.length<12 && line.indexOf('●卷第')==0",},
{F_GROUP: "古籍",S_GROUP: "史",TITLE: "续资治通鉴",COUNTRY: "中",DYNASTY: "清",AUTHOR: "毕沅撰",FILE: "filel/",F_EVAL: "line[0]=='●'",},
{F_GROUP: "古籍",S_GROUP: "史",TITLE: "新元史",COUNTRY: "中",DYNASTY: "现代",AUTHOR: "柯劭忞",FILE: "filel/",F_EVAL: "line[0]=='卷'",},
{F_GROUP: "古籍",S_GROUP: "诗文",TITLE: "楚辞",COUNTRY: "中",DYNASTY: "西汉",AUTHOR: "刘向",FILE: "file/",F_EVAL: "line.indexOf('	')!=0 && line.length<12 && line.indexOf('作者')==-1 && line.indexOf('：')==-1 && line.indexOf('。')==-1 && line.indexOf('？')==-1 && line.indexOf('，')==-1",},
{F_GROUP: "古籍",S_GROUP: "诗文",TITLE: "乐府诗集",COUNTRY: "中",DYNASTY: "北宋",AUTHOR: "郭茂倩",FILE: "file/",F_EVAL: "line[0]=='卷' && line.length<16",},
{F_GROUP: "古籍",S_GROUP: "诗文",TITLE: "宋词三百首",COUNTRY: "中",DYNASTY: "现代",AUTHOR: "朱孝臧",FILE: "file/",F_EVAL: "(line.indexOf('、【')>0 && line.indexOf('、【')<5 )|| line.indexOf('首)')>0",},
{F_GROUP: "古籍",S_GROUP: "诗文",TITLE: "唐诗三百首",COUNTRY: "中",DYNASTY: "清",AUTHOR: "蘅塘退士",FILE: "file/",F_EVAL: "line.indexOf('：')>1 && line[0]<4",},
{F_GROUP: "古籍",S_GROUP: "诗文",TITLE: "全唐诗",COUNTRY: "中",DYNASTY: "清",AUTHOR: "曹寅 彭定求",FILE: "filel/",F_EVAL: "line[0]==' ' && line[3]=='卷'",},
{F_GROUP: "古籍",S_GROUP: "诗文",TITLE: "花间集",COUNTRY: "中",DYNASTY: "隋唐五代",AUTHOR: "赵崇祚",FILE: "file/",F_EVAL: "line[0]=='●'",},
{F_GROUP: "古籍",S_GROUP: "诗文",TITLE: "全唐词",COUNTRY: "中",DYNASTY: "现代",AUTHOR: "唐圭璋",FILE: "filel/",F_EVAL: "line[4]!='●' && line.length<10",},
{F_GROUP: "古籍",S_GROUP: "诗文",TITLE: "全唐五代词",COUNTRY: "中",DYNASTY: "现代",AUTHOR: "曾昭岷",FILE: "filel/",F_EVAL: "line[0]!=' ' && line.length>2 && line.length<5",},
{F_GROUP: "古籍",S_GROUP: "诗文",TITLE: "全金元词",COUNTRY: "中",DYNASTY: "现代",AUTHOR: "唐圭璋",FILE: "filel/",F_EVAL: "line[0]=='【'",},
{F_GROUP: "古籍",S_GROUP: "诗文",TITLE: "玉台新咏",COUNTRY: "中",DYNASTY: "魏晋南北朝",AUTHOR: "徐陵",FILE: "file/",F_EVAL: "line[0]=='●'",},
{F_GROUP: "古籍",S_GROUP: "诗文",TITLE: "古诗源",COUNTRY: "中",DYNASTY: "清",AUTHOR: "沈德潜",FILE: "file/",F_EVAL: "line[0]=='●'",},
{F_GROUP: "古籍",S_GROUP: "诗文",TITLE: "古谣谚",COUNTRY: "中",DYNASTY: "清",AUTHOR: "杜文澜",FILE: "file/",F_EVAL: "line[0]=='卷' && line[3]!='。'",},
{F_GROUP: "古籍",S_GROUP: "诗文",TITLE: "千家诗",COUNTRY: "中",DYNASTY: "清",AUTHOR: "曹寅",FILE: "file/",F_EVAL: "line[2]=='卷'",},
{F_GROUP: "古籍",S_GROUP: "诗文",TITLE: "千字文",COUNTRY: "中",DYNASTY: "魏晋南北朝",AUTHOR: "千字文",FILE: "file/",F_EVAL: "line[0]=='千'",},
{F_GROUP: "古籍",S_GROUP: "诗文",TITLE: "三字经",COUNTRY: "中",DYNASTY: "南宋",AUTHOR: "王应麟",FILE: "file/",F_EVAL: "line[1]=='.'",},
{F_GROUP: "古籍",S_GROUP: "诗文",TITLE: "笠翁对韵",COUNTRY: "中",DYNASTY: "明",AUTHOR: "李渔",FILE: "file/",F_EVAL: "line[2]==' ' || line[3]==' '",},
{F_GROUP: "古籍",S_GROUP: "诗文",TITLE: "声律启蒙",COUNTRY: "中",DYNASTY: "清",AUTHOR: "车万育",FILE: "file/",F_EVAL: "line[1]==' ' || line[2]==' '",},
{F_GROUP: "古籍",S_GROUP: "诗文",TITLE: "增广贤文",COUNTRY: "中",DYNASTY: "明",AUTHOR: "佚名",FILE: "file/",F_EVAL: "line[0]=='增'",},
{F_GROUP: "古籍",S_GROUP: "诗文",TITLE: "列朝诗集",COUNTRY: "中",DYNASTY: "明",AUTHOR: "钱谦益",FILE: "filel/",F_EVAL: "line[0]=='●'",},
{F_GROUP: "古籍",S_GROUP: "诗文",TITLE: "全宋词",COUNTRY: "中",DYNASTY: "现代",AUTHOR: "全宋词",FILE: "filel/",F_EVAL: "line[0]=='●'",},
{F_GROUP: "古籍",S_GROUP: "诗文",TITLE: "全宋诗",COUNTRY: "中",DYNASTY: "现代",AUTHOR: "北大",FILE: "filel/",F_EVAL: "line[0]!=' ' && line.length>2",},
{F_GROUP: "古籍",S_GROUP: "诗文",TITLE: "词综",COUNTRY: "中",DYNASTY: "清",AUTHOR: "朱彝尊",FILE: "filel/",F_EVAL: "line[0]=='《' && line[5]=='卷'",},
{F_GROUP: "古籍",S_GROUP: "诗文",TITLE: "元诗选",COUNTRY: "中",DYNASTY: "清",AUTHOR: "顾嗣立",FILE: "filel/",F_EVAL: "line[2]=='◆'",},
{F_GROUP: "古籍",S_GROUP: "诗文",TITLE: "明诗别裁集",COUNTRY: "中",DYNASTY: "清",AUTHOR: "沈德潜",FILE: "filel/",F_EVAL: "line[0]=='　' && line[1]=='卷'",},
{F_GROUP: "古籍",S_GROUP: "诗文",TITLE: "清诗别裁集",COUNTRY: "中",DYNASTY: "清",AUTHOR: "沈德潜",FILE: "filel/",F_EVAL: "line[0]=='●'",},
{F_GROUP: "古籍",S_GROUP: "诗文",TITLE: "先秦汉魏晋南北朝诗",COUNTRY: "中",DYNASTY: "现代",AUTHOR: "逯钦立",FILE: "filel/",F_EVAL: "line.length<15 && line.indexOf('诗卷')>0 && line[0]!='	'",},
{F_GROUP: "古籍",S_GROUP: "随笔",TITLE: "围炉夜话",COUNTRY: "中",DYNASTY: "清",AUTHOR: "王永彬",FILE: "file/",F_EVAL: "line[1]=='围'",},
{F_GROUP: "古籍",S_GROUP: "随笔",TITLE: "小窗幽记",COUNTRY: "中",DYNASTY: "清",AUTHOR: "陈继儒",FILE: "file/",F_EVAL: "line.indexOf('卷')==0",},
{F_GROUP: "古籍",S_GROUP: "随笔",TITLE: "小窗自记",COUNTRY: "中",DYNASTY: "清",AUTHOR: "吴从先",FILE: "file/",F_EVAL: "line.indexOf('小')==0",},
{F_GROUP: "古籍",S_GROUP: "随笔",TITLE: "幽梦影",COUNTRY: "中",DYNASTY: "清",AUTHOR: "张潮",FILE: "file/",F_EVAL: "line.indexOf('幽梦影')==2",},
{F_GROUP: "古籍",S_GROUP: "随笔",TITLE: "夜航船",COUNTRY: "中",DYNASTY: "明",AUTHOR: "张岱",FILE: "file/",F_EVAL: "line[0]=='卷'",},
{F_GROUP: "古籍",S_GROUP: "随笔",TITLE: "菜根谭",COUNTRY: "中",DYNASTY: "明",AUTHOR: "洪应明",FILE: "file/",F_EVAL: "line.length<12 && line.indexOf('●')==4",},
{F_GROUP: "古籍",S_GROUP: "小说戏剧",TITLE: "红楼梦",COUNTRY: "中",DYNASTY: "清",AUTHOR: "曹雪芹",FILE: "filel/",F_EVAL: "line.length>10 && line.length<40 && line.indexOf('第')==0 && line.indexOf('回')>1 && line.indexOf('回')<8",},
{F_GROUP: "古籍",S_GROUP: "小说戏剧",TITLE: "三国演义",COUNTRY: "中",DYNASTY: "明",AUTHOR: "罗贯中",FILE: "filel/",F_EVAL: "line.indexOf('第')>0 && line.indexOf('第')<3 && line.indexOf('回')>0 && line.indexOf('回')<8",},
{F_GROUP: "古籍",S_GROUP: "小说戏剧",TITLE: "水浒传",COUNTRY: "中",DYNASTY: "明",AUTHOR: "施耐庵",FILE: "filel/",F_EVAL: "line.length>10 && line.length<28 && line.indexOf('第')==0 && line.indexOf('回')>1 && line.indexOf('回')<6",},
{F_GROUP: "古籍",S_GROUP: "小说戏剧",TITLE: "西游记",COUNTRY: "中",DYNASTY: "明",AUTHOR: "吴承恩",FILE: "filel/",F_EVAL: "line.length>10 && line.length<28 && line.indexOf('第')==0 && line.indexOf('回')>1 && line.indexOf('回')<6",},
{F_GROUP: "古籍",S_GROUP: "小说戏剧",TITLE: "封神演义",COUNTRY: "中",DYNASTY: "明",AUTHOR: "许仲琳",FILE: "filel/",F_EVAL: "line.length>10 && line.length<18 && line.indexOf('第')==2 && line.indexOf('回')>3 && line.indexOf('回')<9",},
{F_GROUP: "古籍",S_GROUP: "小说戏剧",TITLE: "金瓶梅",COUNTRY: "中",DYNASTY: "明",AUTHOR: "兰陵笑笑生",FILE: "filel/",F_EVAL: "line.length>10 && line.length<28 && line.indexOf('第')==0 && line.indexOf('回')>1 && line.indexOf('回')<6",},
{F_GROUP: "古籍",S_GROUP: "小说戏剧",TITLE: "镜花缘",COUNTRY: "中",DYNASTY: "清",AUTHOR: "李汝珍",FILE: "file/",F_EVAL: "line[4]=='第' && line.indexOf('回')>5 && line.indexOf('回')<10 && line.indexOf('0')<0",},
{F_GROUP: "古籍",S_GROUP: "小说戏剧",TITLE: "聊斋志异",COUNTRY: "中",DYNASTY: "清",AUTHOR: "蒲松龄",FILE: "file/",F_EVAL: "line.length<8 && line.indexOf(' ')==-1",},
{F_GROUP: "古籍",S_GROUP: "小说戏剧",TITLE: "儒林外史",COUNTRY: "中",DYNASTY: "清",AUTHOR: "吴敬梓",FILE: "file/",F_EVAL: "line.indexOf('第')>0 && line.indexOf('第')<3 && line.indexOf('回')>0 && line.indexOf('回')<8",},
{F_GROUP: "古籍",S_GROUP: "小说戏剧",TITLE: "东周列国志",COUNTRY: "中",DYNASTY: "明",AUTHOR: "冯梦龙",FILE: "filel/",F_EVAL: "line[2]=='第' && line.length<40",},
{F_GROUP: "古籍",S_GROUP: "小说戏剧",TITLE: "搜神记",COUNTRY: "中",DYNASTY: "魏晋南北朝",AUTHOR: "干宝",FILE: "file/",F_EVAL: "line[0]=='搜'",},
{F_GROUP: "古籍",S_GROUP: "小说戏剧",TITLE: "喻世明言",COUNTRY: "中",DYNASTY: "明",AUTHOR: "冯梦龙",FILE: "filel/",F_EVAL: "line[4]=='第' && line.length<29",},
{F_GROUP: "古籍",S_GROUP: "小说戏剧",TITLE: "警世通言",COUNTRY: "中",DYNASTY: "明",AUTHOR: "冯梦龙",FILE: "filel/",F_EVAL: "line[4]=='警'",},
{F_GROUP: "古籍",S_GROUP: "小说戏剧",TITLE: "醒世恒言",COUNTRY: "中",DYNASTY: "明",AUTHOR: "冯梦龙",FILE: "filel/",F_EVAL: "line[0]=='第' || line[1]=='第'",},
{F_GROUP: "古籍",S_GROUP: "小说戏剧",TITLE: "型世言",COUNTRY: "中",DYNASTY: "明",AUTHOR: "陆人龙",FILE: "filel/",F_EVAL: "line[0]=='型'",},
{F_GROUP: "古籍",S_GROUP: "小说戏剧",TITLE: "初刻拍案惊奇",COUNTRY: "中",DYNASTY: "明",AUTHOR: "凌濛初",FILE: "filel/",F_EVAL: "line[0]=='卷'",},
{F_GROUP: "古籍",S_GROUP: "小说戏剧",TITLE: "二刻拍案惊奇",COUNTRY: "中",DYNASTY: "明",AUTHOR: "凌濛初",FILE: "filel/",F_EVAL: "line[0]=='卷'",},
{F_GROUP: "古籍",S_GROUP: "小说戏剧",TITLE: "官场现形记",COUNTRY: "中",DYNASTY: "清",AUTHOR: "李伯元",FILE: "filel/",F_EVAL: "line[0]=='第'",},
{F_GROUP: "古籍",S_GROUP: "小说戏剧",TITLE: "隋唐演义",COUNTRY: "中",DYNASTY: "清",AUTHOR: "褚人获",FILE: "filel/",F_EVAL: "line[2]=='第' && line.length<29 && line.length>16",},
{F_GROUP: "古籍",S_GROUP: "小说戏剧",TITLE: "三侠五义",COUNTRY: "中",DYNASTY: "清",AUTHOR: "石玉昆",FILE: "filel/",F_EVAL: "line[0]=='第'",},
{F_GROUP: "古籍",S_GROUP: "小说戏剧",TITLE: "七剑十三侠",COUNTRY: "中",DYNASTY: "清",AUTHOR: "唐芸洲",FILE: "filel/",F_EVAL: "line[0]=='第' && line.length>16",},
{F_GROUP: "古籍",S_GROUP: "小说戏剧",TITLE: "彭公案",COUNTRY: "中",DYNASTY: "清",AUTHOR: "贪梦道人",FILE: "filel/",F_EVAL: "line[2]=='第' && line.length<29",},
{F_GROUP: "古籍",S_GROUP: "小说戏剧",TITLE: "狄公案",COUNTRY: "中",DYNASTY: "清",AUTHOR: "佚名",FILE: "file/",F_EVAL: "line[0]=='第' && line.length<29",},
{F_GROUP: "古籍",S_GROUP: "小说戏剧",TITLE: "施公案",COUNTRY: "中",DYNASTY: "清",AUTHOR: "佚名",FILE: "filel/",F_EVAL: "line[0]=='第'",},
{F_GROUP: "古籍",S_GROUP: "小说戏剧",TITLE: "龙图公案",COUNTRY: "中",DYNASTY: "清",AUTHOR: "安遇时",FILE: "filel/",F_EVAL: "line[2]=='第'",},
{F_GROUP: "古籍",S_GROUP: "小说戏剧",TITLE: "虬髯客传",COUNTRY: "中",DYNASTY: "隋唐五代",AUTHOR: "杜光庭",FILE: "file/",F_EVAL: "line[0]=='虬'",},
{F_GROUP: "古籍",S_GROUP: "小说戏剧",TITLE: "儿女英雄传",COUNTRY: "中",DYNASTY: "清",AUTHOR: "文康",FILE: "filel/",F_EVAL: "line[0]=='第' || line[0]=='缘'",},
{F_GROUP: "古籍",S_GROUP: "小说戏剧",TITLE: "醒世姻缘传",COUNTRY: "中",DYNASTY: "明",AUTHOR: "西周生",FILE: "filel/",F_EVAL: "line[0]=='第'",},
{F_GROUP: "古籍",S_GROUP: "小说戏剧",TITLE: "说岳全传",COUNTRY: "中",DYNASTY: "清",AUTHOR: "钱彩 金丰",FILE: "filel/",F_EVAL: "line[2]=='第' && line.length<29",},
{F_GROUP: "古籍",S_GROUP: "小说戏剧",TITLE: "济公全传",COUNTRY: "中",DYNASTY: "清",AUTHOR: "郭小亭",FILE: "filel/",F_EVAL: "line[0]=='第'",},
{F_GROUP: "古籍",S_GROUP: "小说戏剧",TITLE: "飞龙全传",COUNTRY: "中",DYNASTY: "清",AUTHOR: "吴璿",FILE: "filel/",F_EVAL: "line[0]=='第' && line.length<29",},
{F_GROUP: "古籍",S_GROUP: "小说戏剧",TITLE: "梼杌闲评",COUNTRY: "中",DYNASTY: "清",AUTHOR: "不题撰人",FILE: "filel/",F_EVAL: "line[0]=='梼'",},
{F_GROUP: "古籍",S_GROUP: "小说戏剧",TITLE: "歧路灯",COUNTRY: "中",DYNASTY: "清",AUTHOR: "李绿园",},
{F_GROUP: "古籍",S_GROUP: "小说戏剧",TITLE: "花月痕",COUNTRY: "中",DYNASTY: "清",AUTHOR: "魏秀仁",FILE: "filel/",F_EVAL: "line[0]=='第'",},
{F_GROUP: "古籍",S_GROUP: "小说戏剧",TITLE: "二十年目睹之怪现状",COUNTRY: "中",DYNASTY: "清",AUTHOR: "吴趼人",FILE: "filel/",F_EVAL: "line[0]=='第' && line.length<29",},
{F_GROUP: "古籍",S_GROUP: "小说戏剧",TITLE: "绿野仙踪",COUNTRY: "中",DYNASTY: "清",AUTHOR: "李百川",FILE: "filel/",F_EVAL: "line[0]=='第'",},
{F_GROUP: "古籍",S_GROUP: "小说戏剧",TITLE: "孽海花",COUNTRY: "中",DYNASTY: "清",AUTHOR: "曾朴 金天翮",FILE: "filel/",F_EVAL: "line[0]=='第' || line[1]=='第'",},
{F_GROUP: "古籍",S_GROUP: "小说戏剧",TITLE: "九尾龟",COUNTRY: "中",DYNASTY: "清",AUTHOR: "张春帆",SHOW: "no",},
{F_GROUP: "古籍",S_GROUP: "小说戏剧",TITLE: "青楼梦",COUNTRY: "中",DYNASTY: "清",AUTHOR: "俞达",FILE: "filel/",F_EVAL: "line[1]=='第'",SHOW: "no",},
{F_GROUP: "古籍",S_GROUP: "小说戏剧",TITLE: "品花宝鉴",COUNTRY: "中",DYNASTY: "清",AUTHOR: "陈森",SHOW: "no",},
{F_GROUP: "古籍",S_GROUP: "小说戏剧",TITLE: "海上花列传",COUNTRY: "中",DYNASTY: "清",AUTHOR: "韩邦庆",},
{F_GROUP: "古籍",S_GROUP: "小说戏剧",TITLE: "禅真逸史",COUNTRY: "中",DYNASTY: "明",AUTHOR: "方汝浩",FILE: "file/",F_EVAL: "line[3]=='第' && line.length<29",},
{F_GROUP: "古籍",S_GROUP: "小说戏剧",TITLE: "女仙外史",COUNTRY: "中",DYNASTY: "清",AUTHOR: "吕熊",FILE: "filel/",F_EVAL: "line[0]=='第'",},
{F_GROUP: "古籍",S_GROUP: "小说戏剧",TITLE: "西厢记",COUNTRY: "中",DYNASTY: "元",AUTHOR: "王实甫",FILE: "file/",F_EVAL: "line[0]=='第'",},
{F_GROUP: "古籍",S_GROUP: "小说戏剧",TITLE: "墙头马上",COUNTRY: "中",DYNASTY: "元",AUTHOR: "白朴",},
{F_GROUP: "古籍",S_GROUP: "小说戏剧",TITLE: "汉宫秋",COUNTRY: "中",DYNASTY: "元",AUTHOR: "马致远",FILE: "file/",F_EVAL: "line[0]=='●'",},
{F_GROUP: "古籍",S_GROUP: "小说戏剧",TITLE: "牡丹亭",COUNTRY: "中",DYNASTY: "明",AUTHOR: "汤显祖",FILE: "file/",F_EVAL: "line[0]=='第'",},
{F_GROUP: "古籍",S_GROUP: "小说戏剧",TITLE: "桃花扇",COUNTRY: "中",DYNASTY: "清",AUTHOR: "孔尚任",FILE: "file/",F_EVAL: "line[0]=='第'",},
{F_GROUP: "古籍",S_GROUP: "小说戏剧",TITLE: "长生殿",COUNTRY: "中",DYNASTY: "清",AUTHOR: "洪升",FILE: "file/",F_EVAL: "line[0]=='第'",},
{F_GROUP: "古籍",S_GROUP: "小说戏剧",TITLE: "老残游记",COUNTRY: "中",DYNASTY: "清",AUTHOR: "刘鹗",FILE: "file/",F_EVAL: "line[0]=='第'",},
{F_GROUP: "古籍",S_GROUP: "小说戏剧",TITLE: "窦娥冤",COUNTRY: "中",DYNASTY: "元",AUTHOR: "关汉卿",FILE: "file/",F_EVAL: "line.indexOf('《')==0",},
{F_GROUP: "古籍",S_GROUP: "医",TITLE: "本草纲目",COUNTRY: "中",DYNASTY: "明",AUTHOR: "李时珍",},
{F_GROUP: "古籍",S_GROUP: "医",TITLE: "金匮要略",COUNTRY: "中",DYNASTY: "东汉",AUTHOR: "张仲景",},
{F_GROUP: "古籍",S_GROUP: "医",TITLE: "黄帝内经灵枢",COUNTRY: "中",DYNASTY: "先秦",AUTHOR: "佚名",FILE: "file/",F_EVAL: "line.indexOf('第')>0 && line.indexOf('第')<12",},
{F_GROUP: "古籍",S_GROUP: "医",TITLE: "黄帝内经素问",COUNTRY: "中",DYNASTY: "先秦",AUTHOR: "佚名",FILE: "file/",F_EVAL: "line.indexOf('第')>5 && line.indexOf('第')<16",},
{F_GROUP: "古籍",S_GROUP: "医",TITLE: "伤寒论",COUNTRY: "中",DYNASTY: "东汉",AUTHOR: "张仲景",FILE: "file/",F_EVAL: "line[2]=='辨'",},
{F_GROUP: "古籍",S_GROUP: "医",TITLE: "神农本草经",COUNTRY: "中",DYNASTY: "东汉",AUTHOR: "佚名",FILE: "file/",F_EVAL: "line[2]=='神' || line[3]=='部' || line[4]=='部'",},
{F_GROUP: "古籍",S_GROUP: "医",TITLE: "肘后备急方",COUNTRY: "中",DYNASTY: "魏晋南北朝",AUTHOR: "葛洪",FILE: "file/",F_EVAL: "line.indexOf('第')>5 && line.indexOf('第')<18 && line.length<20 && line.indexOf('。')==-1",},
{F_GROUP: "古籍",S_GROUP: "医",TITLE: "备急千金要方",COUNTRY: "中",DYNASTY: "隋唐五代",AUTHOR: "孙思邈",FILE: "file/",F_EVAL: "line[2]=='卷' || (line[2]=='《' && line[3]=='备')",},
{F_GROUP: "古籍",S_GROUP: "医",TITLE: "齐民要术",COUNTRY: "中",DYNASTY: "魏晋南北朝",AUTHOR: "贾思勰",FILE: "file/",F_EVAL: "line[4]=='●'",},
{F_GROUP: "古籍",S_GROUP: "释",TITLE: "四十二章经",COUNTRY: "中",DYNASTY: "东汉",AUTHOR: "摄摩腾 竺法兰",FILE: "file/",F_EVAL: "line[2]=='四'",},
{F_GROUP: "古籍",S_GROUP: "释",TITLE: "正法华经",COUNTRY: "中",DYNASTY: "东汉",AUTHOR: "竺法兰",FILE: "file/",F_EVAL: "line.indexOf('品第')>0",},
{F_GROUP: "古籍",S_GROUP: "释",TITLE: "金刚经",COUNTRY: "中",DYNASTY: "魏晋南北朝",AUTHOR: "鸠摩罗什",FILE: "file/",F_EVAL: "line.indexOf('第')==0",},
{F_GROUP: "古籍",S_GROUP: "释",TITLE: "法华经",COUNTRY: "中",DYNASTY: "魏晋南北朝",AUTHOR: "鸠摩罗什",},
{F_GROUP: "古籍",S_GROUP: "释",TITLE: "洛阳伽蓝记",COUNTRY: "中",DYNASTY: "魏晋南北朝",AUTHOR: "杨衒之",FILE: "file/",F_EVAL: "line[0]=='●'",},
{F_GROUP: "古籍",S_GROUP: "释",TITLE: "维摩诘经",COUNTRY: "中",DYNASTY: "魏晋南北朝",AUTHOR: "吴支谦",FILE: "file/",F_EVAL: "line.indexOf('品第')>0",},
{F_GROUP: "古籍",S_GROUP: "释",TITLE: "无量寿经",COUNTRY: "中",DYNASTY: "魏晋南北朝",AUTHOR: "康僧铠",},
{F_GROUP: "古籍",S_GROUP: "释",TITLE: "中阿含经",COUNTRY: "中",DYNASTY: "魏晋南北朝",AUTHOR: "僧伽提婆 僧伽罗叉",FILE: "filel/",F_EVAL: "line[2]=='（'",},
{F_GROUP: "古籍",S_GROUP: "释",TITLE: "杂阿含经",COUNTRY: "中",DYNASTY: "魏晋南北朝",AUTHOR: "求那跋陀罗",FILE: "file/",F_EVAL: "line[2]=='（'",},
{F_GROUP: "古籍",S_GROUP: "释",TITLE: "六祖坛经",COUNTRY: "中",DYNASTY: "隋唐五代",AUTHOR: "慧能",FILE: "file/",F_EVAL: "line[1]=='.'",},
{F_GROUP: "古籍",S_GROUP: "释",TITLE: "地藏菩萨本愿经",COUNTRY: "中",DYNASTY: "隋唐五代",AUTHOR: "实叉难陀",FILE: "file/",F_EVAL: "line.indexOf('品第')>0",},
{F_GROUP: "古籍",S_GROUP: "释",TITLE: "心经",COUNTRY: "中",DYNASTY: "隋唐五代",AUTHOR: "玄奘",FILE: "file/",F_EVAL: "line.indexOf('摩')>0",},
{F_GROUP: "古籍",S_GROUP: "释",TITLE: "药师经",COUNTRY: "中",DYNASTY: "隋唐五代",AUTHOR: "玄奘",},
{F_GROUP: "古籍",S_GROUP: "道",TITLE: "道德经",COUNTRY: "中",DYNASTY: "先秦",AUTHOR: "老子",FILE: "file/",F_EVAL: "line.length<12 && line.indexOf('章')>0 && line.indexOf('章')<6",},
{F_GROUP: "古籍",S_GROUP: "道",TITLE: "庄子",COUNTRY: "中",DYNASTY: "先秦",AUTHOR: "庄子",FILE: "file/",F_EVAL: "line.indexOf('卷')==2",},
{F_GROUP: "古籍",S_GROUP: "道",TITLE: "列子",COUNTRY: "中",DYNASTY: "先秦",AUTHOR: "列子",FILE: "file/",F_EVAL: "line[2]=='卷'",},
{F_GROUP: "古籍",S_GROUP: "道",TITLE: "关尹子",COUNTRY: "中",DYNASTY: "先秦",AUTHOR: "关尹子",FILE: "file/",F_EVAL: "line[3]==line[4]",},
{F_GROUP: "古籍",S_GROUP: "道",TITLE: "素书",COUNTRY: "中",DYNASTY: "秦",AUTHOR: "黄石公",FILE: "file/",F_EVAL: "line.indexOf('第')>0 && line.length<16",},
{F_GROUP: "古籍",S_GROUP: "道",TITLE: "列仙传",COUNTRY: "中",DYNASTY: "西汉",AUTHOR: "刘向",FILE: "file/",F_EVAL: "line.length<7",},
{F_GROUP: "古籍",S_GROUP: "道",TITLE: "周易参同契",COUNTRY: "中",DYNASTY: "东汉",AUTHOR: "魏伯阳",FILE: "file/",F_EVAL: "line[0]=='周'",},
{F_GROUP: "古籍",S_GROUP: "道",TITLE: "太平经",COUNTRY: "中",DYNASTY: "东汉",AUTHOR: "于吉",FILE: "filel/",F_EVAL: "line.indexOf('　　太平经卷之')==0 && line.indexOf('竟')<0",},
{F_GROUP: "古籍",S_GROUP: "道",TITLE: "清静经",COUNTRY: "中",DYNASTY: "魏晋南北朝",AUTHOR: "葛玄",},
{F_GROUP: "古籍",S_GROUP: "道",TITLE: "神仙传",COUNTRY: "中",DYNASTY: "魏晋南北朝",AUTHOR: "葛洪",FILE: "file/",F_EVAL: "line.length<10",},
{F_GROUP: "古籍",S_GROUP: "道",TITLE: "抱朴子",COUNTRY: "中",DYNASTY: "魏晋南北朝",AUTHOR: "葛洪",FILE: "file/",F_EVAL: "line.indexOf('卷')==0 || line.indexOf('附录')==0 || line.indexOf('抱朴子')==0 || line.indexOf('卷第')==4",},
{F_GROUP: "古籍",S_GROUP: "道",TITLE: "度人经",COUNTRY: "中",DYNASTY: "魏晋南北朝",AUTHOR: "佚名",},
{F_GROUP: "古籍",S_GROUP: "道",TITLE: "心印经",COUNTRY: "中",DYNASTY: "魏晋南北朝",AUTHOR: "佚名",},
{F_GROUP: "古籍",S_GROUP: "道",TITLE: "玉皇经",COUNTRY: "中",DYNASTY: "隋唐五代",AUTHOR: "佚名",},
{F_GROUP: "古籍",S_GROUP: "道",TITLE: "黄帝阴符经",COUNTRY: "中",DYNASTY: "隋唐五代",AUTHOR: "李荃",FILE: "file/",F_EVAL: "line[0]=='●'",},
{F_GROUP: "古籍",S_GROUP: "道",TITLE: "通玄真经",COUNTRY: "中",DYNASTY: "隋唐五代",AUTHOR: "通玄真人",FILE: "file/",F_EVAL: "line[0]=='卷'",},
{F_GROUP: "古籍",S_GROUP: "道",TITLE: "洞灵真经",COUNTRY: "中",DYNASTY: "隋唐五代",AUTHOR: "洞灵真人",FILE: "file/",F_EVAL: "line[3]=='道'",},
{F_GROUP: "古籍",S_GROUP: "道",TITLE: "历代崇道记",COUNTRY: "中",DYNASTY: "隋唐五代",AUTHOR: "杜光庭",FILE: "file/",F_EVAL: "line[0]=='历'",},
{F_GROUP: "古籍",S_GROUP: "道",TITLE: "灵飞经",COUNTRY: "中",DYNASTY: "隋唐五代",AUTHOR: "钟绍京",FILE: "file/",F_EVAL: "line[0]=='●'",},
{F_GROUP: "古籍",S_GROUP: "道",TITLE: "服气精义论",COUNTRY: "中",DYNASTY: "隋唐五代",AUTHOR: "司马承祯",FILE: "file/",F_EVAL: "line.indexOf('论第')>0",},
{F_GROUP: "古籍",S_GROUP: "道",TITLE: "无能子",COUNTRY: "中",DYNASTY: "隋唐五代",AUTHOR: "无能子",FILE: "file/",F_EVAL: "line.indexOf('第')>0 && line.length<12",},
{F_GROUP: "古籍",S_GROUP: "道",TITLE: "悟真篇",COUNTRY: "中",DYNASTY: "北宋",AUTHOR: "张伯瑞",FILE: "file/",F_EVAL: "line[0]=='●'",},
{F_GROUP: "古籍",S_GROUP: "道",TITLE: "僧宝传",COUNTRY: "中",DYNASTY: "北宋",AUTHOR: "释惠洪",},
{F_GROUP: "古籍",S_GROUP: "道",TITLE: "云笈七签",COUNTRY: "中",DYNASTY: "北宋",AUTHOR: "张君房",FILE: "filel/",F_EVAL: "line.indexOf('云笈七签')==2",},
{F_GROUP: "古籍",S_GROUP: "道",TITLE: "还丹复命篇",COUNTRY: "中",DYNASTY: "北宋",AUTHOR: "薛道光",FILE: "file/",F_EVAL: "line[0]=='●'",},
{F_GROUP: "古籍",S_GROUP: "道",TITLE: "五灯会元",COUNTRY: "中",DYNASTY: "南宋",AUTHOR: "普济",FILE: "filel/",F_EVAL: "line.indexOf('五灯会元')==2",},
{F_GROUP: "古籍",S_GROUP: "单集",TITLE: "陶渊明集",COUNTRY: "中",DYNASTY: "魏晋南北朝",AUTHOR: "陶渊明",FILE: "file/",F_EVAL: "line[0]=='○'",},
{F_GROUP: "古籍",S_GROUP: "单集",TITLE: "杜工部集",COUNTRY: "中",DYNASTY: "隋唐五代",AUTHOR: "杜甫",},
{F_GROUP: "古籍",S_GROUP: "单集",TITLE: "李太白集",COUNTRY: "中",DYNASTY: "隋唐五代",AUTHOR: "李白",FILE: "file/",F_EVAL: "line[0]=='李' && line[1]=='太'",},
{F_GROUP: "古籍",S_GROUP: "单集",TITLE: "昌黎先生集",COUNTRY: "中",DYNASTY: "隋唐五代",AUTHOR: "韩愈",},
{F_GROUP: "古籍",S_GROUP: "单集",TITLE: "河东先生集",COUNTRY: "中",DYNASTY: "隋唐五代",AUTHOR: "柳宗元",},
{F_GROUP: "古籍",S_GROUP: "单集",TITLE: "欧阳文忠公集",COUNTRY: "中",DYNASTY: "隋唐五代",AUTHOR: "欧阳修",},
{F_GROUP: "古籍",S_GROUP: "单集",TITLE: "乐章集",COUNTRY: "中",DYNASTY: "北宋",AUTHOR: "柳永",},
{F_GROUP: "古籍",S_GROUP: "单集",TITLE: "苏轼集",COUNTRY: "中",DYNASTY: "北宋",AUTHOR: "苏轼",FILE: "filel/",F_EVAL: "line[0]=='●'",},
{F_GROUP: "古籍",S_GROUP: "单集",TITLE: "漱玉词",COUNTRY: "中",DYNASTY: "南宋",AUTHOR: "李清照",FILE: "file/",F_EVAL: "line[0]=='○'",},
{F_GROUP: "古籍",S_GROUP: "单集",TITLE: "稼轩长短句",COUNTRY: "中",DYNASTY: "南宋",AUTHOR: "辛弃疾",},
{F_GROUP: "古籍",S_GROUP: "单集",TITLE: "纳兰词",COUNTRY: "中",DYNASTY: "清",AUTHOR: "纳兰性德",FILE: "file/",F_EVAL: "line[0]=='纳'",},
{F_GROUP: "古籍",S_GROUP: "合集",TITLE: "古文观止",COUNTRY: "中",DYNASTY: "清",AUTHOR: "吴楚才",FILE: "file/",F_EVAL: "line.indexOf('卷')==0 || line.indexOf('【')==0",},
{F_GROUP: "古籍",S_GROUP: "合集",TITLE: "吕氏春秋",COUNTRY: "中",DYNASTY: "秦",AUTHOR: "吕不韦",FILE: "file/",F_EVAL: "line[0]=='《'",},
{F_GROUP: "古籍",S_GROUP: "合集",TITLE: "春秋繁露",COUNTRY: "中",DYNASTY: "西汉",AUTHOR: "董仲舒",FILE: "file/",F_EVAL: "line[2]=='卷'",},
{F_GROUP: "古籍",S_GROUP: "合集",TITLE: "全上古三代秦汉三国六朝文",COUNTRY: "中",DYNASTY: "清",AUTHOR: "严可均",FILE: "filel/",F_EVAL: "line[0]=='【' || line[0]=='卷' || line[0]=='●'",},
{F_GROUP: "古籍",S_GROUP: "合集",TITLE: "全唐文",COUNTRY: "中",DYNASTY: "清",AUTHOR: "董诰 阮元 徐松",FILE: "filel/",F_EVAL: "line[4]=='●'",},
{F_GROUP: "古籍",S_GROUP: "合集",TITLE: "昭明文选",COUNTRY: "中",DYNASTY: "魏晋南北朝",AUTHOR: "萧统",FILE: "filel/",F_EVAL: "line[0]=='卷'",},
{F_GROUP: "古籍",S_GROUP: "合集",TITLE: "经史百家杂钞",COUNTRY: "中",DYNASTY: "清",AUTHOR: "曾国藩",FILE: "filel/",F_EVAL: "line[0]=='●' || line[0]=='○'",},
{F_GROUP: "古籍",S_GROUP: "合集",TITLE: "唐才子传",COUNTRY: "中",DYNASTY: "元",AUTHOR: "辛文房",FILE: "file/",F_EVAL: "line[4]=='●' || line[4]=='○'",},
{F_GROUP: "古籍",S_GROUP: "合集",TITLE: "太平广记",COUNTRY: "中",DYNASTY: "北宋",AUTHOR: "李昉 扈蒙 徐铉",FILE: "filel/",F_EVAL: "line[0]=='卷'",},
{F_GROUP: "古籍",S_GROUP: "合集",TITLE: "世说新语",COUNTRY: "中",DYNASTY: "魏晋南北朝",AUTHOR: "刘义庆",},
{F_GROUP: "古籍",S_GROUP: "合集",TITLE: "全元曲",COUNTRY: "中",DYNASTY: "现代",AUTHOR: "徐征",FILE: "filel/",F_EVAL: "line[0]=='●'",},
{F_GROUP: "古籍",S_GROUP: "合集",TITLE: "全元曲杂剧",COUNTRY: "中",DYNASTY: "现代",AUTHOR: "徐征",FILE: "filel/",F_EVAL: "line[0]=='☆' || line[0]=='★'",},
{F_GROUP: "古籍",S_GROUP: "诸子",TITLE: "墨子",COUNTRY: "中",DYNASTY: "先秦",AUTHOR: "墨子",FILE: "file/",F_EVAL: "line.length<18 && line.indexOf('第')>=3 && line.indexOf('第')<=8",},
{F_GROUP: "古籍",S_GROUP: "诸子",TITLE: "孙子兵法",COUNTRY: "中",DYNASTY: "先秦",AUTHOR: "孙武",FILE: "file/",F_EVAL: "line.indexOf('篇')==3 || line.indexOf('篇')==4",},
{F_GROUP: "古籍",S_GROUP: "诸子",TITLE: "三十六计",COUNTRY: "中",DYNASTY: "明",AUTHOR: "佚名",FILE: "file/",F_EVAL: "line.indexOf('○')>0",},
{F_GROUP: "古籍",S_GROUP: "诸子",TITLE: "孙膑兵法",COUNTRY: "中",DYNASTY: "先秦",AUTHOR: "孙膑",FILE: "file/",F_EVAL: "line[0]=='『'",},
{F_GROUP: "古籍",S_GROUP: "诸子",TITLE: "六韬",COUNTRY: "中",DYNASTY: "先秦",AUTHOR: "姜子牙",FILE: "file/",F_EVAL: "line[4]=='第'",},
{F_GROUP: "古籍",S_GROUP: "诸子",TITLE: "三略",COUNTRY: "中",DYNASTY: "西汉",AUTHOR: "佚名",},
{F_GROUP: "古籍",S_GROUP: "诸子",TITLE: "荀子",COUNTRY: "中",DYNASTY: "先秦",AUTHOR: "荀子",FILE: "file/",F_EVAL: "line.length<8",},
{F_GROUP: "古籍",S_GROUP: "诸子",TITLE: "鬼谷子",COUNTRY: "中",DYNASTY: "先秦",AUTHOR: "鬼谷子",FILE: "file/",F_EVAL: "line.indexOf('.')==1",},
{F_GROUP: "古籍",S_GROUP: "诸子",TITLE: "管子",COUNTRY: "中",DYNASTY: "先秦",AUTHOR: "管子",},
{F_GROUP: "古籍",S_GROUP: "诸子",TITLE: "商君书",COUNTRY: "中",DYNASTY: "先秦",AUTHOR: "商鞅",FILE: "file/",F_EVAL: "line[2]=='第'",},
{F_GROUP: "古籍",S_GROUP: "诸子",TITLE: "韩非子",COUNTRY: "中",DYNASTY: "先秦",AUTHOR: "韩非",FILE: "file/",F_EVAL: "(line.indexOf('韩非子卷')==2 && line.indexOf('竟')==-1) || (line[3]!='　' && line.indexOf('第')>=4 && line.indexOf('第')<=9)",},
{F_GROUP: "古籍",S_GROUP: "诸子",TITLE: "公孙龙子",COUNTRY: "中",DYNASTY: "先秦",AUTHOR: "公孙龙",FILE: "file/",F_EVAL: "(line[4]=='第' || line[5]=='第') && line.length<12",},
{F_GROUP: "古籍",S_GROUP: "其它",TITLE: "淮南子",COUNTRY: "中",DYNASTY: "西汉",AUTHOR: "刘安",FILE: "file/",F_EVAL: "line[2]=='卷'",},
{F_GROUP: "古籍",S_GROUP: "其它",TITLE: "论衡",COUNTRY: "中",DYNASTY: "东汉",AUTHOR: "王充",FILE: "file/",F_EVAL: "line.indexOf('论衡')==2",},
{F_GROUP: "古籍",S_GROUP: "其它",TITLE: "夏小正",COUNTRY: "中",DYNASTY: "先秦",AUTHOR: "佚名",FILE: "file/",F_EVAL: "line[3]=='夏'",},
{F_GROUP: "古籍",S_GROUP: "其它",TITLE: "曾国藩家书",COUNTRY: "中",DYNASTY: "清",AUTHOR: "曾国藩",FILE: "file/",F_EVAL: "line.length<20 && (line.indexOf('国藩')==3 || line.indexOf('国藩')==4 || line.indexOf('：')>5 )",},
{F_GROUP: "古籍",S_GROUP: "其它",TITLE: "孔子改制考",COUNTRY: "中",DYNASTY: "清",AUTHOR: "康有为",FILE: "filel/",F_EVAL: "line.indexOf('孔子改制考')==2",},
{F_GROUP: "古籍",S_GROUP: "其它",TITLE: "茶经",COUNTRY: "中",DYNASTY: "隋唐五代",AUTHOR: "陆羽",FILE: "file/",F_EVAL: "line[2]=='●'",},
{F_GROUP: "古籍",S_GROUP: "其它",TITLE: "传习录",COUNTRY: "中",DYNASTY: "明",AUTHOR: "王守仁",FILE: "file/",F_EVAL: "line[5]=='卷'",},
{F_GROUP: "古籍",S_GROUP: "其它",TITLE: "朱子语类",COUNTRY: "中",DYNASTY: "明",AUTHOR: "黎靖德",FILE: "filel/",F_EVAL: "line.indexOf('朱子语类')==2",},
{F_GROUP: "古籍",S_GROUP: "其它",TITLE: "九章算术",COUNTRY: "中",DYNASTY: "东汉",AUTHOR: "张苍 耿寿昌",FILE: "file/",F_EVAL: "line[2]=='卷'",},
{F_GROUP: "古籍",S_GROUP: "其它",TITLE: "周髀算经",COUNTRY: "中",DYNASTY: "西汉",AUTHOR: "周髀",},
{F_GROUP: "古籍",S_GROUP: "其它",TITLE: "华阳国志",COUNTRY: "中",DYNASTY: "魏晋南北朝",AUTHOR: "常璩",FILE: "filel/",F_EVAL: "line[2]=='●' && line[3]!='●'",},
{F_GROUP: "古籍",S_GROUP: "其它",TITLE: "开元占经",COUNTRY: "中",DYNASTY: "隋唐五代",AUTHOR: "瞿昙悉达",FILE: "filel/",F_EVAL: "line.indexOf('开元占经　卷')==2",},
{F_GROUP: "古籍",S_GROUP: "其它",TITLE: "山海经",COUNTRY: "中",DYNASTY: "先秦",AUTHOR: "佚名",FILE: "file/",F_EVAL: "line.indexOf('山海经卷之')==2 && line.indexOf('竟')==-1",},
{F_GROUP: "古籍",S_GROUP: "其它",TITLE: "水经注",COUNTRY: "中",DYNASTY: "魏晋南北朝",AUTHOR: "郦道元",FILE: "file/",F_EVAL: "line.indexOf('卷')==0",},
{F_GROUP: "古籍",S_GROUP: "其它",TITLE: "天工开物",COUNTRY: "中",DYNASTY: "明",AUTHOR: "宋应星",FILE: "file/",F_EVAL: "line[0]=='●'",},
{F_GROUP: "古籍",S_GROUP: "其它",TITLE: "农政全书",COUNTRY: "中",DYNASTY: "明",AUTHOR: "徐光启",},
{F_GROUP: "古籍",S_GROUP: "其它",TITLE: "梦溪笔谈",COUNTRY: "中",DYNASTY: "北宋",AUTHOR: "沈括",FILE: "file/",F_EVAL: "line.length<18 && (line.indexOf('卷')==2 || line.indexOf('序')==2|| line.indexOf('笔')==3)",},
{F_GROUP: "古籍",S_GROUP: "其它",TITLE: "徐霞客游记",COUNTRY: "中",DYNASTY: "明",AUTHOR: "徐霞客",FILE: "filel/",F_EVAL: "line.indexOf('.')==1",},
{F_GROUP: "古籍",S_GROUP: "其它",TITLE: "幼学琼林",COUNTRY: "中",DYNASTY: "明",AUTHOR: "程登吉 邱睿 邹圣脉",FILE: "file/",F_EVAL: "line[0]=='卷'",},
{F_GROUP: "古籍",S_GROUP: "其它",TITLE: "贞观政要",COUNTRY: "中",DYNASTY: "隋唐五代",AUTHOR: "吴兢",FILE: "file/",F_EVAL: "line.indexOf('第')>=2 && line.indexOf('第')<=10 && line[0]!=' '",},
{F_GROUP: "古籍",S_GROUP: "其它",TITLE: "唐律疏议",COUNTRY: "中",DYNASTY: "隋唐五代",AUTHOR: "长孙无忌",FILE: "filel/",F_EVAL: "line[4]=='●'",},
{F_GROUP: "古籍",S_GROUP: "其它",TITLE: "大唐西域记",COUNTRY: "中",DYNASTY: "隋唐五代",AUTHOR: "玄奘 辩机",FILE: "file/",F_EVAL: "line[0]=='卷'",},
{F_GROUP: "古籍",S_GROUP: "其它",TITLE: "说文解字",COUNTRY: "中",DYNASTY: "东汉",AUTHOR: "许慎",FILE: "file/",F_EVAL: "line[0]=='●'",},
{F_GROUP: "古籍",S_GROUP: "其它",TITLE: "洗冤集录",COUNTRY: "中",DYNASTY: "南宋",AUTHOR: "宋慈",FILE: "file/",F_EVAL: "line.indexOf('·')>=1 && line.length<30",},
{F_GROUP: "古籍",S_GROUP: "其它",TITLE: "说苑",COUNTRY: "中",DYNASTY: "西汉",AUTHOR: "刘向",FILE: "file/",F_EVAL: "line[0]=='卷'",},
{F_GROUP: "古籍",S_GROUP: "其它",TITLE: "林泉高致集",COUNTRY: "中",DYNASTY: "北宋",AUTHOR: "郭熙",FILE: "file/",F_EVAL: "line[0]=='●'",},
{F_GROUP: "古籍",S_GROUP: "其它",TITLE: "明夷待访录",COUNTRY: "中",DYNASTY: "明",AUTHOR: "黄宗羲",FILE: "file/",F_EVAL: "line.length<10",},
{F_GROUP: "古籍",S_GROUP: "其它",TITLE: "日知录",COUNTRY: "中",DYNASTY: "明",AUTHOR: "顾炎武",FILE: "filel/",F_EVAL: "line[2]=='●'",},
{F_GROUP: "古籍",S_GROUP: "其它",TITLE: "海国图志",COUNTRY: "中",DYNASTY: "清",AUTHOR: "魏源",},
{F_GROUP: "古籍",S_GROUP: "其它",TITLE: "文心雕龙",COUNTRY: "中",DYNASTY: "魏晋南北朝",AUTHOR: "刘勰",FILE: "file/",F_EVAL: "line[0]=='卷'",},
{F_GROUP: "古籍",S_GROUP: "其它",TITLE: "史通",COUNTRY: "中",DYNASTY: "隋唐五代",AUTHOR: "刘知几",FILE: "file/",F_EVAL: "line[1]=='篇'",},
{F_GROUP: "古籍",S_GROUP: "其它",TITLE: "颜氏家训",COUNTRY: "中",DYNASTY: "魏晋南北朝",AUTHOR: "颜之推",FILE: "file/",F_EVAL: "line.indexOf('《')==0",},
{F_GROUP: "古籍",S_GROUP: "其它",TITLE: "弟子规",COUNTRY: "中",DYNASTY: "清",AUTHOR: "李毓秀",FILE: "file/",F_EVAL: "line[0]=='●'",},
{F_GROUP: "今人",S_GROUP: "小说戏剧",TITLE: "阿Q正传",COUNTRY: "中",DYNASTY: "现代",AUTHOR: "鲁迅",},
{F_GROUP: "今人",S_GROUP: "小说戏剧",TITLE: "呐喊",COUNTRY: "中",DYNASTY: "现代",AUTHOR: "鲁迅",},
{F_GROUP: "今人",S_GROUP: "小说戏剧",TITLE: "白鹿原",COUNTRY: "中",DYNASTY: "当代",},
{F_GROUP: "今人",S_GROUP: "小说戏剧",TITLE: "边城",COUNTRY: "中",DYNASTY: "现代",},
{F_GROUP: "今人",S_GROUP: "小说戏剧",TITLE: "茶馆",COUNTRY: "中",DYNASTY: "现代",},
{F_GROUP: "今人",S_GROUP: "小说戏剧",TITLE: "芙蓉镇",COUNTRY: "中",DYNASTY: "当代",},
{F_GROUP: "今人",S_GROUP: "小说戏剧",TITLE: "红高粱",COUNTRY: "中",DYNASTY: "当代",AUTHOR: "莫言",},
{F_GROUP: "今人",S_GROUP: "小说戏剧",TITLE: "呼兰河传",COUNTRY: "中",DYNASTY: "现代",},
{F_GROUP: "今人",S_GROUP: "小说戏剧",TITLE: "黄金时代",COUNTRY: "中",DYNASTY: "当代",AUTHOR: "王小波",},
{F_GROUP: "今人",S_GROUP: "小说戏剧",TITLE: "活着",COUNTRY: "中",DYNASTY: "当代",},
{F_GROUP: "今人",S_GROUP: "小说戏剧",TITLE: "家",COUNTRY: "中",DYNASTY: "现代",AUTHOR: "巴金",},
{F_GROUP: "今人",S_GROUP: "小说戏剧",TITLE: "京华烟云",COUNTRY: "中",DYNASTY: "现代",AUTHOR: "林语堂",},
{F_GROUP: "今人",S_GROUP: "小说戏剧",TITLE: "孔乙己",COUNTRY: "中",DYNASTY: "现代",},
{F_GROUP: "今人",S_GROUP: "小说戏剧",TITLE: "狂人日记",COUNTRY: "中",DYNASTY: "现代",},
{F_GROUP: "今人",S_GROUP: "小说戏剧",TITLE: "老残游记",COUNTRY: "中",DYNASTY: "现代",AUTHOR: "刘鹗",},
{F_GROUP: "今人",S_GROUP: "小说戏剧",TITLE: "鹿鼎记",COUNTRY: "中",DYNASTY: "当代",},
{F_GROUP: "今人",S_GROUP: "小说戏剧",TITLE: "骆驼祥子",COUNTRY: "中",DYNASTY: "现代",},
{F_GROUP: "今人",S_GROUP: "小说戏剧",TITLE: "穆斯林的葬礼",COUNTRY: "中",DYNASTY: "当代",},
{F_GROUP: "今人",S_GROUP: "小说戏剧",TITLE: "呐喊",COUNTRY: "中",DYNASTY: "现代",},
{F_GROUP: "今人",S_GROUP: "小说戏剧",TITLE: "撒哈拉的故事",COUNTRY: "中",AUTHOR: "三毛",DYNASTY: "当代",},
{F_GROUP: "今人",S_GROUP: "小说戏剧",TITLE: "色戒",COUNTRY: "中",DYNASTY: "现代",AUTHOR: "张爱玲",},
{F_GROUP: "今人",S_GROUP: "小说戏剧",TITLE: "射雕英雄传",COUNTRY: "中",DYNASTY: "当代",},
{F_GROUP: "今人",S_GROUP: "小说戏剧",TITLE: "神雕侠侣",COUNTRY: "中",DYNASTY: "当代",},
{F_GROUP: "今人",S_GROUP: "小说戏剧",TITLE: "受戒",COUNTRY: "中",DYNASTY: "现代",AUTHOR: "汪曾祺",},
{F_GROUP: "今人",S_GROUP: "小说戏剧",TITLE: "四世同堂",COUNTRY: "中",DYNASTY: "现代",},
{F_GROUP: "今人",S_GROUP: "小说戏剧",TITLE: "围城",COUNTRY: "中",DYNASTY: "现代",},
{F_GROUP: "今人",S_GROUP: "小说戏剧",TITLE: "我与地坛",COUNTRY: "中",DYNASTY: "当代",AUTHOR: "史铁生",},
{F_GROUP: "今人",S_GROUP: "小说戏剧",TITLE: "笑傲江湖",COUNTRY: "中",DYNASTY: "当代",},
{F_GROUP: "今人",S_GROUP: "小说戏剧",TITLE: "子夜",COUNTRY: "中",DYNASTY: "现代",AUTHOR: "茅盾",},
{F_GROUP: "今人",S_GROUP: "小说戏剧",TITLE: "长恨歌",COUNTRY: "中",DYNASTY: "当代",AUTHOR: "王安忆",},
{F_GROUP: "今人",S_GROUP: "小说戏剧",TITLE: "流浪地球",COUNTRY: "中",DYNASTY: "当代",AUTHOR: "刘慈欣",FILE: "filel/",F_EVAL: "line[1]=='.'",},
{F_GROUP: "今人",S_GROUP: "小说戏剧",TITLE: "临高启明",COUNTRY: "中",DYNASTY: "当代",},
{F_GROUP: "今人",S_GROUP: "诗文",TITLE: "海子诗全编",COUNTRY: "中",DYNASTY: "当代",AUTHOR: "海子",},
{F_GROUP: "今人",S_GROUP: "诗文",TITLE: "云雀叫了一整天",COUNTRY: "中",DYNASTY: "现代",AUTHOR: "木心",},
{F_GROUP: "今人",S_GROUP: "诗文",TITLE: "北岛诗选",COUNTRY: "中",DYNASTY: "当代",AUTHOR: "北岛",},
{F_GROUP: "今人",S_GROUP: "诗文",TITLE: "双桅船",COUNTRY: "中",DYNASTY: "当代",AUTHOR: "苏婷",},
{F_GROUP: "今人",S_GROUP: "诗文",TITLE: "水问",COUNTRY: "中",DYNASTY: "当代",AUTHOR: "简媜",},
{F_GROUP: "今人",S_GROUP: "诗文",TITLE: "背影",COUNTRY: "中",DYNASTY: "现代",AUTHOR: "朱自清",},
{F_GROUP: "今人",S_GROUP: "单集",TITLE: "毛泽东选集",COUNTRY: "中",DYNASTY: "现代",AUTHOR: "毛泽东",FILE: "filel/",F_EVAL: "line[0]=='●'",},
{F_GROUP: "今人",S_GROUP: "单集",TITLE: "毛泽东文集",COUNTRY: "中",DYNASTY: "现代",AUTHOR: "毛泽东",},
{F_GROUP: "今人",S_GROUP: "单集",TITLE: "张爱玲文集",COUNTRY: "中",DYNASTY: "现代",AUTHOR: "张爱玲",},
{F_GROUP: "今人",S_GROUP: "单集",TITLE: "王朔文集",COUNTRY: "中",DYNASTY: "当代",AUTHOR: "王朔",},
{F_GROUP: "今人",S_GROUP: "单集",TITLE: "沈从文文集",COUNTRY: "中",DYNASTY: "现代",AUTHOR: "沈从文",},
{F_GROUP: "今人",S_GROUP: "单集",TITLE: "陈寅恪文集",COUNTRY: "中",DYNASTY: "现代",AUTHOR: "陈寅恪",},
{F_GROUP: "今人",S_GROUP: "单集",TITLE: "我的精神家园",COUNTRY: "中",DYNASTY: "当代",AUTHOR: "王小波",},
{F_GROUP: "今人",S_GROUP: "其它",TITLE: "荒芜英雄路",COUNTRY: "中",DYNASTY: "当代",},
{F_GROUP: "今人",S_GROUP: "其它",TITLE: "秦腔",COUNTRY: "中",DYNASTY: "当代",},
{F_GROUP: "今人",S_GROUP: "其它",TITLE: "管锥编",COUNTRY: "中",DYNASTY: "现代",AUTHOR: "钱钟书",},
{F_GROUP: "今人",S_GROUP: "其它",TITLE: "朝花夕拾",COUNTRY: "中",DYNASTY: "现代",AUTHOR: "鲁迅",},
{F_GROUP: "今人",S_GROUP: "其它",TITLE: "柳如是别传",COUNTRY: "中",DYNASTY: "现代",},
{F_GROUP: "今人",S_GROUP: "其它",TITLE: "人间词话",COUNTRY: "中",DYNASTY: "现代",},
{F_GROUP: "今人",S_GROUP: "其它",TITLE: "中国哲学简史",COUNTRY: "中",DYNASTY: "现代",},
{F_GROUP: "今人",S_GROUP: "其它",TITLE: "这个世界会好吗",COUNTRY: "中",DYNASTY: "现代",},
{F_GROUP: "今人",S_GROUP: "其它",TITLE: "人心与人生",COUNTRY: "中",DYNASTY: "现代",},
{F_GROUP: "今人",S_GROUP: "其它",TITLE: "傅雷家书",COUNTRY: "中",DYNASTY: "现代",AUTHOR: "傅雷",},
{F_GROUP: "外国",S_GROUP: "人文",TITLE: "国富论",COUNTRY: "法",AUTHOR: "亚当·斯密",},
{F_GROUP: "外国",S_GROUP: "人文",TITLE: "战争论",COUNTRY: "德",AUTHOR: "卡尔·冯·克劳塞维茨",},
{F_GROUP: "外国",S_GROUP: "人文",TITLE: "正义论",COUNTRY: "美",AUTHOR: "约翰·罗尔斯",},
{F_GROUP: "外国",S_GROUP: "人文",TITLE: "政府论",COUNTRY: "英",AUTHOR: "约翰·洛克",},
{F_GROUP: "外国",S_GROUP: "人文",TITLE: "资本论",COUNTRY: "德",AUTHOR: "马克思",},
{F_GROUP: "外国",S_GROUP: "人文",TITLE: "君主论",COUNTRY: "意",AUTHOR: "尼可罗·马基亚维利",},
{F_GROUP: "外国",S_GROUP: "人文",TITLE: "语言论",COUNTRY: "意",AUTHOR: "克罗齐",},
{F_GROUP: "外国",S_GROUP: "人文",TITLE: "社会契约论",COUNTRY: "法",AUTHOR: "卢梭",},
{F_GROUP: "外国",S_GROUP: "人文",TITLE: "权力意志论",AUTHOR: "尼采",},
{F_GROUP: "外国",S_GROUP: "人文",TITLE: "人类理解论",},
{F_GROUP: "外国",S_GROUP: "人文",TITLE: "人类理智新论",},
{F_GROUP: "外国",S_GROUP: "人文",TITLE: "伦理学",},
{F_GROUP: "外国",S_GROUP: "人文",TITLE: "政治学",AUTHOR: "亚里士多德",},
{F_GROUP: "外国",S_GROUP: "人文",TITLE: "形而上学",},
{F_GROUP: "外国",S_GROUP: "人文",TITLE: "尼各马可伦理学",},
{F_GROUP: "外国",S_GROUP: "人文",TITLE: "精神现象学",COUNTRY: "德",AUTHOR: "黑格尔",},
{F_GROUP: "外国",S_GROUP: "人文",TITLE: "人口原理",},
{F_GROUP: "外国",S_GROUP: "人文",TITLE: "经济学原理",},
{F_GROUP: "外国",S_GROUP: "人文",TITLE: "论自由",},
{F_GROUP: "外国",S_GROUP: "人文",TITLE: "论法的精神",},
{F_GROUP: "外国",S_GROUP: "人文",TITLE: "沉思录",},
{F_GROUP: "外国",S_GROUP: "人文",TITLE: "忏悔录",COUNTRY: "法",AUTHOR: "卢梭",},
{F_GROUP: "外国",S_GROUP: "人文",TITLE: "西方哲学史",COUNTRY: "英",AUTHOR: "罗素",},
{F_GROUP: "外国",S_GROUP: "人文",TITLE: "悲剧的诞生",COUNTRY: "德",AUTHOR: "尼采",},
{F_GROUP: "外国",S_GROUP: "人文",TITLE: "纯粹理性批判",COUNTRY: "德",AUTHOR: "康德",},
{F_GROUP: "外国",S_GROUP: "人文",TITLE: "存在与虚无",COUNTRY: "法",AUTHOR: "让·保罗·萨特",},
{F_GROUP: "外国",S_GROUP: "人文",TITLE: "梦的解析",COUNTRY: "其它",AUTHOR: "弗洛伊德",},
{F_GROUP: "外国",S_GROUP: "人文",TITLE: "精神分析引论",COUNTRY: "其它",AUTHOR: "弗洛伊德",},
{F_GROUP: "外国",S_GROUP: "人文",TITLE: "人性的弱点",COUNTRY: "美",AUTHOR: "卡耐基",},
{F_GROUP: "外国",S_GROUP: "人文",TITLE: "武士道",COUNTRY: "日",AUTHOR: "新渡户稻造",},
{F_GROUP: "外国",S_GROUP: "人文",TITLE: "菊与刀",COUNTRY: "日",},
{F_GROUP: "外国",S_GROUP: "人文",TITLE: "理想国",},
{F_GROUP: "外国",S_GROUP: "人文",TITLE: "汉谟拉比法典",},
{F_GROUP: "外国",S_GROUP: "人文",TITLE: "拿破仑法典",},
{F_GROUP: "外国",S_GROUP: "人文",TITLE: "奥本海国际法",},
{F_GROUP: "外国",S_GROUP: "人文",TITLE: "世界人权宣言",},
{F_GROUP: "外国",S_GROUP: "人文",TITLE: "第一哲学沉思集",},
{F_GROUP: "外国",S_GROUP: "人文",TITLE: "苏菲的世界",},
{F_GROUP: "外国",S_GROUP: "人文",TITLE: "存在与虚无",},
{F_GROUP: "外国",S_GROUP: "人文",TITLE: "新工具",},
{F_GROUP: "外国",S_GROUP: "人文",TITLE: "论神",COUNTRY: "荷",AUTHOR: "斯宾诺莎",},
{F_GROUP: "外国",S_GROUP: "人文",TITLE: "新教伦理与资本主义精神",AUTHOR: "马克斯·韦伯",},
{F_GROUP: "外国",S_GROUP: "诗文",TITLE: "荷马史诗",},
{F_GROUP: "外国",S_GROUP: "诗文",TITLE: "神曲",},
{F_GROUP: "外国",S_GROUP: "诗文",TITLE: "吉檀迦利",},
{F_GROUP: "外国",S_GROUP: "诗文",TITLE: "罗摩衍那",},
{F_GROUP: "外国",S_GROUP: "随笔",TITLE: "古今集",COUNTRY: "日",},
{F_GROUP: "外国",S_GROUP: "随笔",TITLE: "万叶集",COUNTRY: "日",AUTHOR: "大伴家持",},
{F_GROUP: "外国",S_GROUP: "随笔",TITLE: "枕草子",COUNTRY: "日",AUTHOR: "清少纳言",FILE: "file/",F_EVAL: "line[0]=='●' && line.length<18",},
{F_GROUP: "外国",S_GROUP: "随笔",TITLE: "徒然草",COUNTRY: "日",AUTHOR: "吉田兼好",},
{F_GROUP: "外国",S_GROUP: "小说戏剧",TITLE: "爱丽丝漫游仙境",},
{F_GROUP: "外国",S_GROUP: "小说戏剧",TITLE: "安娜·卡列尼娜",},
{F_GROUP: "外国",S_GROUP: "小说戏剧",TITLE: "安徒生童话",},
{F_GROUP: "外国",S_GROUP: "小说戏剧",TITLE: "傲慢与偏见",COUNTRY: "英",AUTHOR: "简·奥斯汀",},
{F_GROUP: "外国",S_GROUP: "小说戏剧",TITLE: "巴黎圣母院",},
{F_GROUP: "外国",S_GROUP: "小说戏剧",TITLE: "百年孤独",},
{F_GROUP: "外国",S_GROUP: "小说戏剧",TITLE: "包法利夫人",COUNTRY: "法",AUTHOR: "福楼拜",},
{F_GROUP: "外国",S_GROUP: "小说戏剧",TITLE: "悲惨世界",},
{F_GROUP: "外国",S_GROUP: "小说戏剧",TITLE: "变形记",},
{F_GROUP: "外国",S_GROUP: "小说戏剧",TITLE: "茶花女",},
{F_GROUP: "外国",S_GROUP: "小说戏剧",TITLE: "达·芬奇密码",},
{F_GROUP: "外国",S_GROUP: "小说戏剧",TITLE: "等待戈多",},
{F_GROUP: "外国",S_GROUP: "小说戏剧",TITLE: "福尔摩斯探案集",},
{F_GROUP: "外国",S_GROUP: "小说戏剧",TITLE: "父与子",},
{F_GROUP: "外国",S_GROUP: "小说戏剧",TITLE: "复活",},
{F_GROUP: "外国",S_GROUP: "小说戏剧",TITLE: "钢铁是怎样炼成的",},
{F_GROUP: "外国",S_GROUP: "小说戏剧",TITLE: "格林童话",},
{F_GROUP: "外国",S_GROUP: "小说戏剧",TITLE: "哈利波特",},
{F_GROUP: "外国",S_GROUP: "小说戏剧",TITLE: "哈姆雷特",},
{F_GROUP: "外国",S_GROUP: "小说戏剧",TITLE: "红与黑",},
{F_GROUP: "外国",S_GROUP: "小说戏剧",TITLE: "呼啸山庄",},
{F_GROUP: "外国",S_GROUP: "小说戏剧",TITLE: "基督山伯爵",},
{F_GROUP: "外国",S_GROUP: "小说戏剧",TITLE: "简爱",},
{F_GROUP: "外国",S_GROUP: "小说戏剧",TITLE: "Jane Eyre",FILE: "filel/",F_EVAL: "line.indexOf('Chapter')==0",},
{F_GROUP: "外国",S_GROUP: "小说戏剧",TITLE: "静静的顿河",},
{F_GROUP: "外国",S_GROUP: "小说戏剧",TITLE: "老人与海",},
{F_GROUP: "外国",S_GROUP: "小说戏剧",TITLE: "李尔王",},
{F_GROUP: "外国",S_GROUP: "小说戏剧",TITLE: "鲁滨逊漂流记",},
{F_GROUP: "外国",S_GROUP: "小说戏剧",TITLE: "漂亮朋友",COUNTRY: "法",AUTHOR: "莫泊桑",},
{F_GROUP: "外国",S_GROUP: "小说戏剧",TITLE: "罗密欧与朱丽叶",},
{F_GROUP: "外国",S_GROUP: "小说戏剧",TITLE: "洛丽塔",COUNTRY: "美",AUTHOR: "弗拉基米尔·纳博科夫",},
{F_GROUP: "外国",S_GROUP: "小说戏剧",TITLE: "绿野仙踪",},
{F_GROUP: "外国",S_GROUP: "小说戏剧",TITLE: "马可·波罗游记",},
{F_GROUP: "外国",S_GROUP: "小说戏剧",TITLE: "麦田里的守望者",},
{F_GROUP: "外国",S_GROUP: "小说戏剧",TITLE: "萌芽",},
{F_GROUP: "外国",S_GROUP: "小说戏剧",TITLE: "名利场",},
{F_GROUP: "外国",S_GROUP: "小说戏剧",TITLE: "牛虻",},
{F_GROUP: "外国",S_GROUP: "小说戏剧",TITLE: "挪威的森林",COUNTRY: "日",AUTHOR: "村上春树",},
{F_GROUP: "外国",S_GROUP: "小说戏剧",TITLE: "不能承受的生命之轻",COUNTRY: "其它",AUTHOR: "米兰·昆德拉",},
{F_GROUP: "外国",S_GROUP: "小说戏剧",TITLE: "飘",},
{F_GROUP: "外国",S_GROUP: "小说戏剧",TITLE: "唐璜",COUNTRY: "英",AUTHOR: "马克斯·韦伯",},
{F_GROUP: "外国",S_GROUP: "小说戏剧",TITLE: "杀死一只知更鸟",},
{F_GROUP: "外国",S_GROUP: "小说戏剧",TITLE: "上尉的女儿",COUNTRY: "俄",AUTHOR: "普希金",},
{F_GROUP: "外国",S_GROUP: "小说戏剧",TITLE: "少年Pi的奇幻漂流",},
{F_GROUP: "外国",S_GROUP: "小说戏剧",TITLE: "少年维特之烦恼",},
{F_GROUP: "外国",S_GROUP: "小说戏剧",TITLE: "十日谈",},
{F_GROUP: "外国",S_GROUP: "小说戏剧",TITLE: "双城记",},
{F_GROUP: "外国",S_GROUP: "小说戏剧",TITLE: "A Tale of Two Cities",FILE: "filel/",F_EVAL: "line.indexOf('Chapter')==0",},
{F_GROUP: "外国",S_GROUP: "小说戏剧",TITLE: "死魂灵",COUNTRY: "俄",AUTHOR: "果戈里",},
{F_GROUP: "外国",S_GROUP: "小说戏剧",TITLE: "嘉莉妹妹",COUNTRY: "美",AUTHOR: "西奥图·德莱塞",},
{F_GROUP: "外国",S_GROUP: "小说戏剧",TITLE: "哈克贝利·费恩历险记",COUNTRY: "美",AUTHOR: "马克·吐温",},
{F_GROUP: "外国",S_GROUP: "小说戏剧",TITLE: "汤姆·索亚历险记",},
{F_GROUP: "外国",S_GROUP: "小说戏剧",TITLE: "汤姆叔叔的小屋",},
{F_GROUP: "外国",S_GROUP: "小说戏剧",TITLE: "唐吉诃德",},
{F_GROUP: "外国",S_GROUP: "小说戏剧",TITLE: "玩偶之家",},
{F_GROUP: "外国",S_GROUP: "小说戏剧",TITLE: "娜娜",COUNTRY: "法",AUTHOR: "左拉",},
{F_GROUP: "外国",S_GROUP: "小说戏剧",TITLE: "欧也妮·葛朗台",COUNTRY: "法",AUTHOR: "巴尔扎克",},
{F_GROUP: "外国",S_GROUP: "小说戏剧",TITLE: "邦斯舅舅",COUNTRY: "法",AUTHOR: "巴尔扎克",},
{F_GROUP: "外国",S_GROUP: "小说戏剧",TITLE: "幻灭",COUNTRY: "法",AUTHOR: "巴尔扎克",},
{F_GROUP: "外国",S_GROUP: "小说戏剧",TITLE: "威尼斯商人",},
{F_GROUP: "外国",S_GROUP: "小说戏剧",TITLE: "雾都孤儿",},
{F_GROUP: "外国",S_GROUP: "小说戏剧",TITLE: "Oliver Twist",FILE: "filel/",F_EVAL: "line.indexOf('Chapter')==0",},
{F_GROUP: "外国",S_GROUP: "小说戏剧",TITLE: "小王子",},
{F_GROUP: "外国",S_GROUP: "小说戏剧",TITLE: "一九八四",},
{F_GROUP: "外国",S_GROUP: "小说戏剧",TITLE: "一千零一夜",},
{F_GROUP: "外国",S_GROUP: "小说戏剧",TITLE: "伊索寓言",},
{F_GROUP: "外国",S_GROUP: "小说戏剧",TITLE: "尤利西斯",COUNTRY: "其它",AUTHOR: "乔伊斯",},
{F_GROUP: "外国",S_GROUP: "小说戏剧",TITLE: "源氏物语",FILE: "filel/",F_EVAL: "line.indexOf('第')==1 && line.length<15",},
{F_GROUP: "外国",S_GROUP: "小说戏剧",TITLE: "约翰·克里斯朵夫",COUNTRY: "法",AUTHOR: "罗曼罗兰",},
{F_GROUP: "外国",S_GROUP: "小说戏剧",TITLE: "战争与和平",},
{F_GROUP: "外国",S_GROUP: "小说戏剧",TITLE: "指环王",},
{F_GROUP: "外国",S_GROUP: "小说戏剧",TITLE: "追忆似水年华",COUNTRY: "法",AUTHOR: "普鲁斯特",},
{F_GROUP: "外国",S_GROUP: "小说戏剧",TITLE: "罪与罚",},
{F_GROUP: "外国",S_GROUP: "小说戏剧",TITLE: "蝇王",},
{F_GROUP: "外国",S_GROUP: "其它",TITLE: "几何原本",},
{F_GROUP: "外国",S_GROUP: "其它",TITLE: "昆虫记",AUTHOR: "让-亨利·卡西米尔·法布尔",},
{F_GROUP: "外国",S_GROUP: "其它",TITLE: "寂静的春天",COUNTRY: "美",AUTHOR: "蕾切尔·卡逊",},
{F_GROUP: "外国",S_GROUP: "其它",TITLE: "圣经",},
{F_GROUP: "外国",S_GROUP: "其它",TITLE: "古兰经",},
{F_GROUP: "外国",S_GROUP: "其它",TITLE: "中国科学技术史",COUNTRY: "英",AUTHOR: "李约瑟",},
{F_GROUP: "外国",S_GROUP: "其它",TITLE: "天演论",COUNTRY: "英",AUTHOR: "赫胥黎",FILE: "file/",F_EVAL: "line.length>2 && line.length<10 && line.indexOf('：')<0 && line[0]!='回' && line[0]!='天'",},
{F_GROUP: "外国",S_GROUP: "其它",TITLE: "时间简史",COUNTRY: "英",AUTHOR: "霍金",},
{F_GROUP: "外国",S_GROUP: "其它",TITLE: "物种起源",},
];