var book=[
{
"BOOKS_ID": "1",
"B_NAME": "《红楼梦》",
"B_FILE": "古籍/叙事/红楼梦.txt",
"B_EVAL": "line.length>10 && line.length<40 && line.indexOf('第')==0 && line.indexOf('回')>1 && line.indexOf('回')<8",
},
{
"BOOKS_ID": "2",
"B_NAME": "《水浒传》",
"B_FILE": "古籍/叙事/水浒传.txt",
"B_EVAL": "line.length>10 && line.length<28 && line.indexOf('第')==0 && line.indexOf('回')>1 && line.indexOf('回')<6",
},
{
"BOOKS_ID": "3",
"B_NAME": "《三国演义》",
"B_FILE": "古籍/叙事/三国演义.txt",
"B_EVAL": "line.indexOf('第')>0 && line.indexOf('第')<3 && line.indexOf('回')>0 && line.indexOf('回')<8",
},
{
"BOOKS_ID": "4",
"B_NAME": "《西游记》",
"B_FILE": "古籍/叙事/西游记.txt",
"B_EVAL": "line.length>10 && line.length<28 && line.indexOf('第')==0 && line.indexOf('回')>1 && line.indexOf('回')<6",
},
{
"BOOKS_ID": "5",
"B_NAME": "《儒林外史》",
"B_FILE": "古籍/叙事/儒林外史.txt",
"B_EVAL": "line.indexOf('第')>0 && line.indexOf('第')<3 && line.indexOf('回')>0 && line.indexOf('回')<8",
},
{
"BOOKS_ID": "6",
"B_NAME": "《聊斋志异》",
"B_FILE": "古籍/叙事/聊斋志异.txt",
"B_EVAL": "line.length<8 && line.indexOf(' ')==-1",
},
{
"BOOKS_ID": "7",
"B_NAME": "《金瓶梅》",
"B_FILE": "古籍/叙事/金瓶梅.txt",
"B_EVAL": "line.length>10 && line.length<28 && line.indexOf('第')==0 && line.indexOf('回')>1 && line.indexOf('回')<6",
},
{
"BOOKS_ID": "8",
"B_NAME": "《封神演义》",
"B_FILE": "古籍/叙事/封神演义.txt",
"B_EVAL": "line.length>10 && line.length<18 && line.indexOf('第')==2 && line.indexOf('回')>3 && line.indexOf('回')<9",
},
{
"BOOKS_ID": "9",
"B_NAME": "01《史记》",
"B_FILE": "古籍/经史/正史/史记.txt",
"B_EVAL": "line.length<35 && line.indexOf('卷')==0",
},
{
"BOOKS_ID": "10",
"B_NAME": "02《汉书》",
"B_FILE": "古籍/经史/正史/汉书.txt",
"B_EVAL": "line.length<35 && line.indexOf('卷')==0",
},
{
"BOOKS_ID": "11",
"B_NAME": "03《后汉书》",
"B_FILE": "古籍/经史/正史/后汉书.txt",
"B_EVAL": "line.length<35 && (line.indexOf('后汉书卷')==0 || line.indexOf('后汉书志')==0)",
},
{
"BOOKS_ID": "12",
"B_NAME": "《楚辞》",
"B_FILE": "古籍/诗文/楚辞.txt",
"B_EVAL": "line.indexOf('	')!=0 && line.length<12 && line.indexOf('作者')==-1 && line.indexOf('：')==-1 && line.indexOf('。')==-1 && line.indexOf('？')==-1 && line.indexOf('，')==-1",
},
{
"BOOKS_ID": "13",
"B_NAME": "02《尚书》",
"B_FILE": "古籍/经史/儒家/尚书.txt",
"B_EVAL": "line.indexOf('　　')==0 && line.length<18 && line.indexOf('书')==3",
},
{
"BOOKS_ID": "14",
"B_NAME": "01《诗经》",
"B_FILE": "古籍/经史/儒家/诗经.txt",
"B_EVAL": "line.length<20 && (line.indexOf('风')==1 || line.indexOf('雅')==1 || line.indexOf('风')==1)",
},
{
"BOOKS_ID": "15",
"B_NAME": "06《周易》",
"B_FILE": "古籍/经史/儒家/周易.txt",
"B_EVAL": "line.length<20 && line.indexOf('　　')==0 && line[4]=='.'",
},
{
"BOOKS_ID": "16",
"B_NAME": "05《礼记》",
"B_FILE": "古籍/经史/儒家/礼记.txt",
"B_EVAL": "line.length<20 && line.indexOf('　　《礼记')==0",
},
{
"BOOKS_ID": "17",
"B_NAME": "07《春秋左传》",
"B_FILE": "古籍/经史/儒家/春秋左传.txt",
"B_EVAL": "line.length<20 && line.indexOf('　　◇')==0",
},
{
"BOOKS_ID": "18",
"B_NAME": "08《春秋公羊传》",
"B_FILE": "古籍/经史/儒家/春秋公羊传.txt",
"B_EVAL": "line.length<20 && line.indexOf('公（经')==3",
},
{
"BOOKS_ID": "19",
"B_NAME": "09《春秋谷梁传》",
"B_FILE": "古籍/经史/儒家/春秋谷梁传.txt",
"B_EVAL": "line.length<20 && line.indexOf('公（经')==3",
},
{
"BOOKS_ID": "20",
"B_NAME": "10《论语》",
"B_FILE": "古籍/经史/儒家/论语.txt",
"B_EVAL": "line.length<20 && line.indexOf('第')==4",
},
{
"BOOKS_ID": "21",
"B_NAME": "13《孟子》",
"B_FILE": "古籍/经史/儒家/孟子.txt",
"B_EVAL": "line.length<20 && line.indexOf('卷')==2",
},
{
"BOOKS_ID": "22",
"B_NAME": "11《尔雅》",
"B_FILE": "古籍/经史/儒家/尔雅.txt",
"B_EVAL": "line.length<20 && line.indexOf('释')==2 && line.indexOf('第')==4",
},
{
"BOOKS_ID": "23",
"B_NAME": "12《孝经》",
"B_FILE": "古籍/经史/儒家/孝经.txt",
"B_EVAL": "line.length<20 && line.indexOf('○')==2",
},
{
"BOOKS_ID": "24",
"B_NAME": "03《周礼》",
"B_FILE": "古籍/经史/儒家/周礼.txt",
"B_EVAL": "line.length<20 && line.indexOf('.')==1",
},
{
"BOOKS_ID": "25",
"B_NAME": "04《仪礼》",
"B_FILE": "古籍/经史/儒家/仪礼.txt",
"B_EVAL": "line.length<20 && line.indexOf('	')!=0 && line.indexOf('第')>2 && line.indexOf('第')<8",
},
{
"BOOKS_ID": "26",
"B_NAME": "《资治通鉴》",
"B_FILE": "古籍/经史/杂集/资治通鉴.txt",
"B_EVAL": "line.length<12 && line.indexOf('●卷第')==0",
},
{
"BOOKS_ID": "27",
"B_NAME": "《菜根谭》",
"B_FILE": "古籍/杂集/菜根谭.txt",
"B_EVAL": "line.length<12 && line.indexOf('●')==4",
},
{
"BOOKS_ID": "28",
"B_NAME": "《道德经》",
"B_FILE": "古籍/经史/杂集/道德经.txt",
"B_EVAL": "line.length<12 && line.indexOf('章')>0 && line.indexOf('章')<6",
},
{
"BOOKS_ID": "29",
"B_NAME": "《六祖坛经》",
"B_FILE": "古籍/经史/杂集/六祖坛经.txt",
"B_EVAL": "line[1]=='.'",
},
{
"BOOKS_ID": "30",
"B_NAME": "《庄子》",
"B_FILE": "古籍/经史/杂集/庄子.txt",
"B_EVAL": "line.indexOf('卷')==2",
},
{
"BOOKS_ID": "31",
"B_NAME": "《梦溪笔谈》",
"B_FILE": "古籍/叙事/梦溪笔谈.txt",
"B_EVAL": "line.length<18 && (line.indexOf('卷')==2 || line.indexOf('序')==2|| line.indexOf('笔')==3)",
},
{
"BOOKS_ID": "32",
"B_NAME": "《窦娥冤》",
"B_FILE": "古籍/叙事/窦娥冤.txt",
"B_EVAL": "line.indexOf('《')==0",
},
{
"BOOKS_ID": "33",
"B_NAME": "《水经注》",
"B_FILE": "古籍/杂集/水经注.txt",
"B_EVAL": "line.indexOf('卷')==0",
},
{
"BOOKS_ID": "34",
"B_NAME": "《韩非子》",
"B_FILE": "古籍/经史/杂集/韩非子.txt",
"B_EVAL": "(line.indexOf('韩非子卷')==2 && line.indexOf('竟')==-1) || (line[3]!='　' && line.indexOf('第')>=4 && line.indexOf('第')<=9)",
},
{
"BOOKS_ID": "35",
"B_NAME": "《孙子兵法》",
"B_FILE": "古籍/杂集/孙子兵法.txt",
"B_EVAL": "line.indexOf('篇')==3 || line.indexOf('篇')==4",
},
{
"BOOKS_ID": "36",
"B_NAME": "《颜氏家训》",
"B_FILE": "古籍/杂集/颜氏家训.txt",
"B_EVAL": "line.indexOf('《')==0",
},
{
"BOOKS_ID": "37",
"B_NAME": "《抱朴子》",
"B_FILE": "古籍/杂集/抱朴子.txt",
"B_EVAL": "line.indexOf('卷')==0 || line.indexOf('附录')==0 || line.indexOf('抱朴子')==0 || line.indexOf('卷第')==4",
},
{
"BOOKS_ID": "38",
"B_NAME": "《徐霞客游记》",
"B_FILE": "古籍/杂集/徐霞客游记.txt",
"B_EVAL": "line.indexOf('.')==1",
},
{
"BOOKS_ID": "39",
"B_NAME": "《曾国藩家书》",
"B_FILE": "古籍/杂集/曾国藩家书.txt",
"B_EVAL": "line.length<20 && (line.indexOf('国藩')==3 || line.indexOf('国藩')==4 || line.indexOf('：')>5 )",
},
{
"BOOKS_ID": "40",
"B_NAME": "《贞观政要》",
"B_FILE": "古籍/杂集/贞观政要.txt",
"B_EVAL": "line.indexOf('第')>=2 && line.indexOf('第')<=10 && line[0]!=' '",
},
{
"BOOKS_ID": "41",
"B_NAME": "《三十六计》",
"B_FILE": "古籍/杂集/三十六计.txt",
"B_EVAL": "line.indexOf('○')>0",
},
{
"BOOKS_ID": "42",
"B_NAME": "《金刚经》",
"B_FILE": "古籍/经史/杂集/金刚经.txt",
"B_EVAL": "line.indexOf('第')==0",
},
{
"BOOKS_ID": "43",
"B_NAME": "《墨子》",
"B_FILE": "古籍/杂集/墨子.txt",
"B_EVAL": "line.length<18 && line.indexOf('第')>=3 && line.indexOf('第')<=8",
},
{
"BOOKS_ID": "44",
"B_NAME": "《山海经》",
"B_FILE": "古籍/杂集/山海经.txt",
"B_EVAL": "line.indexOf('山海经卷之')==2 && line.indexOf('竟')==-1",
},
{
"BOOKS_ID": "45",
"B_NAME": "《古文观止》",
"B_FILE": "古籍/诗文/古文观止.txt",
"B_EVAL": "line.indexOf('卷')==0 || line.indexOf('【')==0",
},
{
"BOOKS_ID": "46",
"B_NAME": "《鬼谷子》",
"B_FILE": "古籍/杂集/鬼谷子.txt",
"B_EVAL": "line.indexOf('.')==1",
},
{
"BOOKS_ID": "47",
"B_NAME": "《笠翁对韵》",
"B_FILE": "古籍/诗文/笠翁对韵.txt",
"B_EVAL": "line[2]==' ' || line[3]==' '",
},
{
"BOOKS_ID": "48",
"B_NAME": "《声律启蒙》",
"B_FILE": "古籍/诗文/声律启蒙.txt",
"B_EVAL": "line[1]==' ' || line[2]==' '",
},
{
"BOOKS_ID": "49",
"B_NAME": "《三字经》",
"B_FILE": "古籍/诗文/三字经.txt",
"B_EVAL": "line[1]=='.'",
},
{
"BOOKS_ID": "50",
"B_NAME": "《千字文》",
"B_FILE": "古籍/诗文/千字文.txt",
"B_EVAL": "line[0]=='千'",
},
{
"BOOKS_ID": "51",
"B_NAME": "《宋词三百首》",
"B_FILE": "古籍/诗文/宋词三百首.txt",
"B_EVAL": "(line.indexOf('、【')>0 && line.indexOf('、【')<5 )|| line.indexOf('首)')>0",
},
{
"BOOKS_ID": "52",
"B_NAME": "《唐诗三百首》",
"B_FILE": "古籍/诗文/唐诗三百首.txt",
"B_EVAL": "line.indexOf('：')>1",
},
{
"BOOKS_ID": "53",
"B_NAME": "《天工开物》",
"B_FILE": "古籍/杂集/天工开物.txt",
"B_EVAL": "line[0]=='●'",
},
{
"BOOKS_ID": "54",
"B_NAME": "《本草纲目》",
"B_FILE": "古籍/杂集/本草纲目.txt",
"B_EVAL": "",
},
{
"BOOKS_ID": "55",
"B_NAME": "《黄帝内经》",
"B_FILE": "古籍/杂集/黄帝内经.txt",
"B_EVAL": "",
},
{
"BOOKS_ID": "56",
"B_NAME": "《九章算术》",
"B_FILE": "古籍/杂集/九章算术.txt",
"B_EVAL": "line[2]=='卷'",
},
{
"BOOKS_ID": "57",
"B_NAME": "《开元占经》",
"B_FILE": "古籍/杂集/开元占经.txt",
"B_EVAL": "line.indexOf('开元占经　卷')==2",
},
{
"BOOKS_ID": "58",
"B_NAME": "05《晋书》",
"B_FILE": "古籍/经史/正史/晋书.txt",
"B_EVAL": "line[0]!='　' && (line[1]=='第' || line[2]=='第')",
},
{
"BOOKS_ID": "59",
"B_NAME": "10《魏书》",
"B_FILE": "古籍/经史/正史/魏书.txt",
"B_EVAL": "line[0]!='　' && (line[1]=='第' || line[2]=='第')",
},
{
"BOOKS_ID": "60",
"B_NAME": "13《隋书》",
"B_FILE": "古籍/经史/正史/隋书.txt",
"B_EVAL": "line[0]!='　' && (line[1]=='第' || line[2]=='第')",
},
{
"BOOKS_ID": "61",
"B_NAME": "16《旧唐书》",
"B_FILE": "古籍/经史/正史/旧唐书aa.txt",
"B_EVAL": "(line[3]=='第' || line[4]=='第' || line[2]=='●') && line.indexOf('。')<0 && line.indexOf('：')<0",
},
{
"BOOKS_ID": "62",
"B_NAME": "《战国策》",
"B_FILE": "古籍/经史/杂集/战国策.txt",
"B_EVAL": "line[0]=='卷'",
},
{
"BOOKS_ID": "63",
"B_NAME": "04《三国志》",
"B_FILE": "古籍/经史/正史/三国志.txt",
"B_EVAL": "line.indexOf('志卷')==3 && line.indexOf('证')==-1",
},
{
"BOOKS_ID": "64",
"B_NAME": "06《宋书》",
"B_FILE": "古籍/经史/正史/宋书.txt",
"B_EVAL": "(line[1]=='第' || line[2]=='第') && line.length<30 && line.length>6",
},
{
"BOOKS_ID": "65",
"B_NAME": "07《南齐书》",
"B_FILE": "古籍/经史/正史/南齐书.txt",
"B_EVAL": "(line[1]=='第' || line[2]=='第') && line.length<30",
},
{
"BOOKS_ID": "66",
"B_NAME": "08《梁书》",
"B_FILE": "古籍/经史/正史/梁书.txt",
"B_EVAL": "(line[1]=='第' || line[2]=='第') && line.length<50 && line[0]!='　'",
},
{
"BOOKS_ID": "67",
"B_NAME": "09《陈书》",
"B_FILE": "古籍/经史/正史/陈书.txt",
"B_EVAL": "line[2]=='第' && line.length<30",
},
{
"BOOKS_ID": "68",
"B_NAME": "11《北齐书》",
"B_FILE": "古籍/经史/正史/北齐书.txt",
"B_EVAL": "line[0]=='第' && line.length<80",
},
{
"BOOKS_ID": "69",
"B_NAME": "12《周书》",
"B_FILE": "古籍/经史/正史/周书.txt",
"B_EVAL": "line[2]=='卷'",
},
{
"BOOKS_ID": "70",
"B_NAME": "14《南史》",
"B_FILE": "古籍/经史/正史/南史.txt",
"B_EVAL": "line.indexOf('南史卷')>=0 && line.length<30",
},
{
"BOOKS_ID": "71",
"B_NAME": "15《北史》",
"B_FILE": "古籍/经史/正史/北史.txt",
"B_EVAL": "(line[2]=='第' || line[3]=='第') && line.length<30",
},
{
"BOOKS_ID": "72",
"B_NAME": "17《新唐书》",
"B_FILE": "古籍/经史/正史/新唐书.txt",
"B_EVAL": "(line[2]=='第' || line[3]=='第') && line.length<30 && line.length>6",
},
{
"BOOKS_ID": "73",
"B_NAME": "18《旧五代史》",
"B_FILE": "古籍/经史/正史/旧五代史.txt",
"B_EVAL": "line.length<30 && line[0]!='	' && line.indexOf('。')<0 && line.indexOf('：')<0 && line.indexOf('（')<0 && line.indexOf('-')<0",
},
{
"BOOKS_ID": "74",
"B_NAME": "19《新五代史》",
"B_FILE": "古籍/经史/正史/新五代史.txt",
"B_EVAL": "line.length<30 && line.indexOf('第')>1 && line[0]!='	'",
},
{
"BOOKS_ID": "75",
"B_NAME": "20《宋史》",
"B_FILE": "古籍/经史/正史/宋史.txt",
"B_EVAL": "(line[1]=='第' || line[2]=='第'|| line[3]=='第') && line.length<30 && line[0]!='　'",
},
{
"BOOKS_ID": "76",
"B_NAME": "21《辽史》",
"B_FILE": "古籍/经史/正史/辽史.txt",
"B_EVAL": "line[0]=='第'",
},
{
"BOOKS_ID": "77",
"B_NAME": "22《金史》",
"B_FILE": "古籍/经史/正史/金史.txt",
"B_EVAL": "(line[1]=='第' || line[2]=='第') && line.length<12",
},
{
"BOOKS_ID": "78",
"B_NAME": "23《元史》",
"B_FILE": "古籍/经史/正史/元史.txt",
"B_EVAL": "line[0]=='卷'",
},
{
"BOOKS_ID": "79",
"B_NAME": "24《明史》",
"B_FILE": "古籍/经史/正史/明史.txt",
"B_EVAL": "(line[1]=='第' || line[2]=='第') && line.length<36 && line[0]!='　'",
},
{
"BOOKS_ID": "80",
"B_NAME": "25《清史稿》",
"B_FILE": "古籍/经史/正史/清史稿.txt",
"B_EVAL": "(line.indexOf('本纪')==2 || line.indexOf('志')==2 || line.indexOf('表')==2 || line.indexOf('列传')==2) && line.length<20 && line.length>5 && line.indexOf('略')==-1",
},
{
"BOOKS_ID": "81",
"B_NAME": "《国语》",
"B_FILE": "古籍/经史/杂集/国语.txt",
"B_EVAL": "line[0]=='卷'",
},
{
"BOOKS_ID": "82",
"B_NAME": "《竹书纪年》",
"B_FILE": "古籍/经史/杂集/竹书纪年.txt",
"B_EVAL": "line[0]=='竹'",
},
{
"BOOKS_ID": "83",
"B_NAME": "《肘后备急方》",
"B_FILE": "古籍/杂集/肘后备急方.txt",
"B_EVAL": "line.indexOf('第')>5 && line.indexOf('第')<18 && line.length<20 && line.indexOf('。')==-1",
},
{
"BOOKS_ID": "84",
"B_NAME": "《伤寒论》",
"B_FILE": "古籍/杂集/伤寒论.txt",
"B_EVAL": "line[2]=='辨'",
},
{
"BOOKS_ID": "85",
"B_NAME": "《神农本草经》",
"B_FILE": "古籍/杂集/神农本草经.txt",
"B_EVAL": "line[2]=='神' || line[3]=='部' || line[4]=='部'",
},
{
"BOOKS_ID": "86",
"B_NAME": "《镜花缘》",
"B_FILE": "古籍/叙事/镜花缘.txt",
"B_EVAL": "",
},


{
"BOOKS_ID": "301",
"B_NAME": "《一千零一夜》",
"B_FILE": "外国/叙事/一千零一夜.txt",
"B_EVAL": "",
},
{
"BOOKS_ID": "302",
"B_NAME": "《格林童话》",
"B_FILE": "外国/叙事/格林童话.txt",
"B_EVAL": "",
},
{
"BOOKS_ID": "303",
"B_NAME": "《安徒生童话》",
"B_FILE": "外国/叙事/安徒生童话.txt",
"B_EVAL": "",
},
{
"BOOKS_ID": "304",
"B_NAME": "《基督山伯爵》",
"B_FILE": "外国/叙事/基督山伯爵.txt",
"B_EVAL": "",
},
{
"BOOKS_ID": "305",
"B_NAME": "《巴黎圣母院》",
"B_FILE": "外国/叙事/巴黎圣母院.txt",
"B_EVAL": "",
},
{
"BOOKS_ID": "306",
"B_NAME": "《汤姆叔叔的小屋》",
"B_FILE": "外国/叙事/汤姆叔叔的小屋.txt",
"B_EVAL": "",
},
{
"BOOKS_ID": "307",
"B_NAME": "《苏菲的世界》",
"B_FILE": "外国/人文/苏菲的世界.txt",
"B_EVAL": "",
},
{
"BOOKS_ID": "308",
"B_NAME": "《静静的顿河》",
"B_FILE": "外国/叙事/静静的顿河.txt",
"B_EVAL": "",
},
{
"BOOKS_ID": "309",
"B_NAME": "《复活》",
"B_FILE": "外国/叙事/复活.txt",
"B_EVAL": "",
},
{
"BOOKS_ID": "310",
"B_NAME": "《小王子》",
"B_FILE": "外国/叙事/小王子.txt",
"B_EVAL": "",
},
{
"BOOKS_ID": "311",
"B_NAME": "《茶花女》",
"B_FILE": "外国/叙事/茶花女.txt",
"B_EVAL": "",
},
{
"BOOKS_ID": "312",
"B_NAME": "《少年维特之烦恼》",
"B_FILE": "外国/叙事/少年维特之烦恼.txt",
"B_EVAL": "",
},
{
"BOOKS_ID": "313",
"B_NAME": "《追忆似水年华》",
"B_FILE": "外国/叙事/追忆似水年华.txt",
"B_EVAL": "",
},
{
"BOOKS_ID": "314",
"B_NAME": "《钢铁是怎样炼成的》",
"B_FILE": "外国/叙事/钢铁是怎样炼成的.txt",
"B_EVAL": "",
},
{
"BOOKS_ID": "315",
"B_NAME": "《罗密欧与朱丽叶》",
"B_FILE": "外国/叙事/罗密欧与朱丽叶.txt",
"B_EVAL": "",
},
{
"BOOKS_ID": "316",
"B_NAME": "《百年孤独》",
"B_FILE": "外国/叙事/百年孤独.txt",
"B_EVAL": "",
},
{
"BOOKS_ID": "317",
"B_NAME": "《尤利西斯》",
"B_FILE": "外国/叙事/尤利西斯.txt",
"B_EVAL": "",
},
{
"BOOKS_ID": "318",
"B_NAME": "《理想国》",
"B_FILE": "外国/人文/理想国.txt",
"B_EVAL": "",
},
{
"BOOKS_ID": "319",
"B_NAME": "《社会契约论》",
"B_FILE": "外国/人文/社会契约论.txt",
"B_EVAL": "",
},
{
"BOOKS_ID": "320",
"B_NAME": "《安娜·卡列尼娜》",
"B_FILE": "外国/叙事/安娜·卡列尼娜.txt",
"B_EVAL": "",
},
{
"BOOKS_ID": "321",
"B_NAME": "《资本论》",
"B_FILE": "外国/人文/资本论.txt",
"B_EVAL": "",
},
{
"BOOKS_ID": "322",
"B_NAME": "《飘》",
"B_FILE": "外国/叙事/飘.txt",
"B_EVAL": "",
},
{
"BOOKS_ID": "323",
"B_NAME": "《荷马史诗》",
"B_FILE": "外国/叙事/荷马史诗.txt",
"B_EVAL": "",
},
{
"BOOKS_ID": "324",
"B_NAME": "《新教伦理与资本主义精神》",
"B_AUTHOR": "马克斯·韦伯",
"B_FILE": "外国/人文/新教伦理与资本主义精神.txt",
"B_EVAL": "",
},
{
"BOOKS_ID": "325",
"B_NAME": "《昆虫记》",
"B_AUTHOR": "让-亨利·卡西米尔·法布尔",
"B_FILE": "外国/杂项/昆虫记.txt",
"B_EVAL": "",
},
{
"BOOKS_ID": "326",
"B_NAME": "《红与黑》",
"B_FILE": "外国/叙事/红与黑.txt",
"B_EVAL": "",
},
{
"BOOKS_ID": "327",
"B_NAME": "《物种起源》",
"B_FILE": "外国/杂项/物种起源.txt",
"B_EVAL": "",
},
{
"BOOKS_ID": "328",
"B_NAME": "《君主论》",
"B_FILE": "外国/人文/君主论.txt",
"B_EVAL": "",
},
{
"BOOKS_ID": "329",
"B_NAME": "《人口原理》",
"B_FILE": "外国/人文/人口原理.txt",
"B_EVAL": "",
},
{
"BOOKS_ID": "330",
"B_NAME": "《源氏物语》",
"B_FILE": "外国/叙事/源氏物语.txt",
"B_EVAL": "line.indexOf('第')==1 && line.length<15",
},
{
"BOOKS_ID": "331",
"B_NAME": "《国富论》",
"B_FILE": "外国/人文/国富论.txt",
"B_EVAL": "",
},
{
"BOOKS_ID": "332",
"B_NAME": "《唐吉诃德》",
"B_FILE": "外国/叙事/唐吉诃德.txt",
"B_EVAL": "",
},
{
"BOOKS_ID": "333",
"B_NAME": "《战争论》",
"B_FILE": "外国/人文/君主论.txt",
"B_EVAL": "",
},
{
"BOOKS_ID": "334",
"B_NAME": "《几何原本》",
"B_FILE": "外国/杂项/几何原本.txt",
"B_EVAL": "",
},
{
"BOOKS_ID": "335",
"B_NAME": "《论法的精神》",
"B_FILE": "外国/人文/论法的精神.txt",
"B_EVAL": "",
},
{
"BOOKS_ID": "336",
"B_NAME": "《鲁滨逊漂流记》",
"B_FILE": "外国/叙事/鲁滨逊漂流记.txt",
"B_EVAL": "",
},
{
"BOOKS_ID": "337",
"B_NAME": "《老人与海》",
"B_FILE": "外国/叙事/老人与海.txt",
"B_EVAL": "",
},
{
"BOOKS_ID": "338",
"B_NAME": "《吉檀迦利》",
"B_FILE": "外国/叙事/吉檀迦利.txt",
"B_EVAL": "",
},
{
"BOOKS_ID": "339",
"B_NAME": "《简·爱》",
"B_FILE": "外国/叙事/简·爱.txt",
"B_EVAL": "",
},
{
"BOOKS_ID": "340",
"B_NAME": "《伦理学》",
"B_FILE": "外国/人文/伦理学.txt",
"B_EVAL": "",
},
{
"BOOKS_ID": "341",
"B_NAME": "《悲惨世界》",
"B_FILE": "外国/叙事/悲惨世界.txt",
"B_EVAL": "",
},
{
"BOOKS_ID": "342",
"B_NAME": "《悲剧的诞生》",
"B_FILE": "外国/人文/悲剧的诞生.txt",
"B_EVAL": "",
},
{
"BOOKS_ID": "343",
"B_NAME": "《梦的解析》",
"B_FILE": "外国/杂项/梦的解析.txt",
"B_EVAL": "",
},
{
"BOOKS_ID": "344",
"B_NAME": "《神曲》",
"B_FILE": "外国/叙事/神曲.txt",
"B_EVAL": "",
},
{
"BOOKS_ID": "345",
"B_NAME": "《马可·波罗游记》",
"B_FILE": "外国/叙事/马可·波罗游记.txt",
"B_EVAL": "",
},
{
"BOOKS_ID": "346",
"B_NAME": "《正义论》",
"B_FILE": "外国/人文/正义论.txt",
"B_EVAL": "",
},
{
"BOOKS_ID": "347",
"B_NAME": "《指环王》",
"B_FILE": "外国/叙事/指环王.txt",
"B_EVAL": "",
},
{
"BOOKS_ID": "348",
"B_NAME": "《哈利波特》",
"B_FILE": "外国/叙事/哈利波特.txt",
"B_EVAL": "",
},
{
"BOOKS_ID": "349",
"B_NAME": "《圣经》",
"B_FILE": "外国/杂项/圣经.txt",
"B_EVAL": "",
},
{
"BOOKS_ID": "350",
"B_NAME": "《呼啸山庄》",
"B_FILE": "外国/叙事/呼啸山庄.txt",
"B_EVAL": "",
},
{
"BOOKS_ID": "351",
"B_NAME": "《麦田里的守望者》",
"B_FILE": "外国/叙事/麦田里的守望者.txt",
"B_EVAL": "",
},
{
"BOOKS_ID": "351",
"B_NAME": "《傲慢与偏见》",
"B_FILE": "外国/叙事/傲慢与偏见.txt",
"B_EVAL": "",
},
{
"BOOKS_ID": "352",
"B_NAME": "《战争与和平》",
"B_FILE": "外国/叙事/战争与和平.txt",
"B_EVAL": "",
},
{
"BOOKS_ID": "353",
"B_NAME": "《爱丽丝漫游仙境》",
"B_FILE": "外国/叙事/爱丽丝漫游仙境.txt",
"B_EVAL": "",
},
{
"BOOKS_ID": "354",
"B_NAME": "《罪与罚》",
"B_FILE": "外国/叙事/罪与罚.txt",
"B_EVAL": "",
},
{
"BOOKS_ID": "355",
"B_NAME": "《双城记》",
"B_FILE": "外国/叙事/双城记.txt",
"B_EVAL": "",
},
{
"BOOKS_ID": "356",
"B_NAME": "《包法利夫人》",
"B_FILE": "外国/叙事/包法利夫人.txt",
"B_EVAL": "",
},
{
"BOOKS_ID": "357",
"B_NAME": "《福尔摩斯探案集》",
"B_FILE": "外国/叙事/福尔摩斯探案集.txt",
"B_EVAL": "",
},
{
"BOOKS_ID": "358",
"B_NAME": "《哈姆雷特》",
"B_FILE": "外国/叙事/哈姆雷特.txt",
"B_EVAL": "",
},
{
"BOOKS_ID": "359",
"B_NAME": "《萌芽》",
"B_FILE": "外国/叙事/萌芽.txt",
"B_EVAL": "",
},
{
"BOOKS_ID": "360",
"B_NAME": "《雾都孤儿》",
"B_FILE": "外国/叙事/雾都孤儿.txt",
"B_EVAL": "",
},
{
"BOOKS_ID": "361",
"B_NAME": "《洛丽塔》",
"B_FILE": "外国/叙事/洛丽塔.txt",
"B_EVAL": "",
},
{
"BOOKS_ID": "362",
"B_NAME": "《少年Pi的奇幻漂流》",
"B_FILE": "外国/叙事/少年Pi的奇幻漂流.txt",
"B_EVAL": "",
},
{
"BOOKS_ID": "363",
"B_NAME": "《达·芬奇密码》",
"B_FILE": "外国/叙事/达·芬奇密码.txt",
"B_EVAL": "",
},
{
"BOOKS_ID": "364",
"B_NAME": "《威尼斯商人》",
"B_FILE": "外国/叙事/威尼斯商人.txt",
"B_EVAL": "",
},
{
"BOOKS_ID": "365",
"B_NAME": "《名利场》",
"B_FILE": "外国/叙事/名利场.txt",
"B_EVAL": "",
},
{
"BOOKS_ID": "366",
"B_NAME": "《新工具》",
"B_FILE": "外国/人文/伦理学.txt",
"B_EVAL": "",
},
{
"BOOKS_ID": "367",
"B_NAME": "《约翰·克里斯朵夫》",
"B_FILE": "外国/叙事/约翰·克里斯朵夫.txt",
"B_EVAL": "",
},
{
"BOOKS_ID": "368",
"B_NAME": "《茶花女》",
"B_FILE": "外国/叙事/约翰·克里斯朵夫.txt",
"B_EVAL": "",
},
{
"BOOKS_ID": "369",
"B_NAME": "《拿破仑法典》",
"B_FILE": "外国/人文/拿破仑法典.txt",
"B_EVAL": "",
},
{
"BOOKS_ID": "370",
"B_NAME": "《忏悔录》",
"B_FILE": "外国/杂项/忏悔录.txt",
"B_EVAL": "",
},
{
"BOOKS_ID": "371",
"B_NAME": "《父与子》",
"B_FILE": "外国/叙事/父与子.txt",
"B_EVAL": "",
},
{
"BOOKS_ID": "372",
"B_NAME": "《上尉的女儿》",
"B_FILE": "外国/叙事/上尉的女儿.txt",
"B_EVAL": "",
},
{
"BOOKS_ID": "373",
"B_NAME": "《死魂灵》",
"B_FILE": "外国/叙事/死魂灵.txt",
"B_EVAL": "",
},
{
"BOOKS_ID": "374",
"B_NAME": "《伊索寓言》",
"B_FILE": "外国/叙事/伊索寓言.txt",
"B_EVAL": "",
},
{
"BOOKS_ID": "375",
"B_NAME": "《政治学》",
"B_AUTHOR": "亚里士多德",
"B_FILE": "外国/人文/政治学.txt",
"B_EVAL": "",
},
{
"BOOKS_ID": "376",
"B_NAME": "《牛虻》",
"B_FILE": "外国/叙事/牛虻.txt",
"B_EVAL": "",
},
{
"BOOKS_ID": "377",
"B_NAME": "《政府论》",
"B_FILE": "外国/人文/政府论.txt",
"B_EVAL": "",
},
{
"BOOKS_ID": "378",
"B_NAME": "《权力意志论》",
"B_AUTHOR": "尼采",
"B_FILE": "外国/人文/权力意志论.txt",
"B_EVAL": "",
},
{
"BOOKS_ID": "379",
"B_NAME": "《变形记》",
"B_FILE": "外国/叙事/变形记.txt",
"B_EVAL": "",
},
{
"BOOKS_ID": "380",
"B_NAME": "《十日谈》",
"B_FILE": "外国/叙事/十日谈.txt",
"B_EVAL": "",
},
{
"BOOKS_ID": "381",
"B_NAME": "《绿野仙踪》",
"B_FILE": "外国/叙事/绿野仙踪.txt",
"B_EVAL": "",
},
{
"BOOKS_ID": "382",
"B_NAME": "《一九八四》",
"B_FILE": "外国/叙事/一九八四.txt",
"B_EVAL": "",
},
{
"BOOKS_ID": "383",
"B_NAME": "《武士道》",
"B_FILE": "外国/人文/武士道.txt",
"B_EVAL": "",
},
{
"BOOKS_ID": "384",
"B_NAME": "《经济学原理》",
"B_FILE": "外国/人文/经济学原理.txt",
"B_EVAL": "",
},
{
"BOOKS_ID": "385",
"B_NAME": "《人性的弱点》",
"B_FILE": "外国/杂项/人性的弱点.txt",
"B_EVAL": "",
},
{
"BOOKS_ID": "386",
"B_NAME": "《玩偶之家》",
"B_FILE": "外国/叙事/玩偶之家.txt",
"B_EVAL": "",
},
{
"BOOKS_ID": "387",
"B_NAME": "《西方哲学史》",
"B_FILE": "外国/人文/西方哲学史.txt",
"B_EVAL": "",
},
{
"BOOKS_ID": "388",
"B_NAME": "《纯粹理性批判》",
"B_FILE": "外国/人文/纯粹理性批判.txt",
"B_EVAL": "",
},
{
"BOOKS_ID": "389",
"B_NAME": "《挪威的森林》",
"B_FILE": "外国/叙事/挪威的森林.txt",
"B_EVAL": "",
},
{
"BOOKS_ID": "390",
"B_NAME": "《杀死一只知更鸟》",
"B_FILE": "外国/叙事/杀死一只知更鸟.txt",
"B_EVAL": "",
},
{
"BOOKS_ID": "391",
"B_NAME": "《李尔王》",
"B_FILE": "外国/叙事/李尔王.txt",
"B_EVAL": "",
},
{
"BOOKS_ID": "392",
"B_NAME": "《罗摩衍那》",
"B_FILE": "外国/叙事/罗摩衍那.txt",
"B_EVAL": "",
},
{
"BOOKS_ID": "393",
"B_NAME": "《汤姆·索亚历险记》",
"B_FILE": "外国/叙事/汤姆·索亚历险记.txt",
"B_EVAL": "",
},
{
"BOOKS_ID": "394",
"B_NAME": "《时间简史》",
"B_FILE": "外国/杂项/时间简史.txt",
"B_EVAL": "",
},
{
"BOOKS_ID": "395",
"B_NAME": "《菊与刀》",
"B_FILE": "外国/人文/菊与刀.txt",
"B_EVAL": "",
},
{
"BOOKS_ID": "396",
"B_NAME": "《等待戈多》",
"B_FILE": "外国/叙事/等待戈多.txt",
"B_EVAL": "",
},


{
"BOOKS_ID": "501",
"B_NAME": "《围城》",
"B_FILE": "今人/叙事/围城.txt",
"B_EVAL": "",
},
{
"BOOKS_ID": "502",
"B_NAME": "《活着》",
"B_FILE": "今人/叙事/活着.txt",
"B_EVAL": "",
},
{
"BOOKS_ID": "503",
"B_NAME": "《骆驼祥子》",
"B_FILE": "今人/叙事/骆驼祥子.txt",
"B_EVAL": "",
},
{
"BOOKS_ID": "504",
"B_NAME": "《穆斯林的葬礼》",
"B_FILE": "今人/叙事/穆斯林的葬礼.txt",
"B_EVAL": "",
},
{
"BOOKS_ID": "505",
"B_NAME": "《柳如是别传》",
"B_FILE": "今人/叙事/柳如是别传.txt",
"B_EVAL": "",
},
{
"BOOKS_ID": "506",
"B_NAME": "《阿Q正传》",
"B_FILE": "今人/叙事/阿Q正传.txt",
"B_EVAL": "",
},
{
"BOOKS_ID": "507",
"B_NAME": "《人间词话》",
"B_FILE": "今人/叙事/人间词话.txt",
"B_EVAL": "",
},
{
"BOOKS_ID": "508",
"B_NAME": "《狂人日记》",
"B_FILE": "今人/叙事/狂人日记.txt",
"B_EVAL": "",
},
{
"BOOKS_ID": "509",
"B_NAME": "《边城》",
"B_FILE": "今人/叙事/边城.txt",
"B_EVAL": "",
},
{
"BOOKS_ID": "510",
"B_NAME": "《色戒》",
"B_FILE": "今人/叙事/色戒.txt",
"B_EVAL": "",
},
{
"BOOKS_ID": "511",
"B_NAME": "《茶馆》",
"B_FILE": "今人/叙事/茶馆.txt",
"B_EVAL": "",
},
{
"BOOKS_ID": "512",
"B_NAME": "《红高粱》",
"B_FILE": "今人/叙事/红高粱.txt",
"B_EVAL": "",
},
{
"BOOKS_ID": "513",
"B_NAME": "《神雕侠侣》",
"B_FILE": "今人/叙事/神雕侠侣.txt",
"B_EVAL": "",
},
{
"BOOKS_ID": "514",
"B_NAME": "《射雕英雄传》",
"B_FILE": "今人/叙事/射雕英雄传.txt",
"B_EVAL": "",
},
{
"BOOKS_ID": "515",
"B_NAME": "《笑傲江湖》",
"B_FILE": "今人/叙事/笑傲江湖.txt",
"B_EVAL": "",
},
{
"BOOKS_ID": "516",
"B_NAME": "《鹿鼎记》",
"B_FILE": "今人/叙事/鹿鼎记.txt",
"B_EVAL": "",
},
{
"BOOKS_ID": "517",
"B_NAME": "《我与地坛》",
"B_FILE": "今人/叙事/我与地坛.txt",
"B_EVAL": "",
},
{
"BOOKS_ID": "518",
"B_NAME": "《荒芜英雄路》",
"B_FILE": "今人/叙事/荒芜英雄路.txt",
"B_EVAL": "",
},
{
"BOOKS_ID": "519",
"B_NAME": "《撒哈拉的故事》",
"B_FILE": "今人/叙事/撒哈拉的故事.txt",
"B_EVAL": "",
},
{
"BOOKS_ID": "520",
"B_NAME": "《芙蓉镇》",
"B_FILE": "今人/叙事/芙蓉镇.txt",
"B_EVAL": "",
},
{
"BOOKS_ID": "521",
"B_NAME": "《孔乙己》",
"B_FILE": "今人/叙事/孔乙己.txt",
"B_EVAL": "",
},
{
"BOOKS_ID": "522",
"B_NAME": "《四世同堂》",
"B_FILE": "今人/叙事/四世同堂.txt",
"B_EVAL": "",
},
{
"BOOKS_ID": "523",
"B_NAME": "《呼兰河传》",
"B_FILE": "今人/叙事/呼兰河传.txt",
"B_EVAL": "",
},
{
"BOOKS_ID": "524",
"B_NAME": "《白鹿原》",
"B_FILE": "今人/叙事/白鹿原.txt",
"B_EVAL": "",
},
{
"BOOKS_ID": "525",
"B_NAME": "《秦腔》",
"B_FILE": "今人/叙事/秦腔.txt",
"B_EVAL": "",
},
{
"BOOKS_ID": "526",
"B_NAME": "《黄金时代》",
"B_FILE": "今人/叙事/黄金时代.txt",
"B_EVAL": "",
},
{
"BOOKS_ID": "527",
"B_NAME": "《呐喊》",
"B_FILE": "今人/叙事/呐喊.txt",
"B_EVAL": "",
},
{
"BOOKS_ID": "528",
"B_AUTHOR": "巴金",
"B_NAME": "《家》",
"B_FILE": "今人/叙事/家.txt",
"B_EVAL": "",
},
{
"BOOKS_ID": "529",
"B_AUTHOR": "茅盾",
"B_NAME": "《子夜》",
"B_FILE": "今人/叙事/子夜.txt",
"B_EVAL": "",
},
{
"BOOKS_ID": "530",
"B_AUTHOR": "刘鹗",
"B_NAME": "《老残游记》",
"B_FILE": "今人/叙事/老残游记.txt",
"B_EVAL": "",
},
{
"BOOKS_ID": "531",
"B_AUTHOR": "汪曾祺",
"B_NAME": "《受戒》",
"B_FILE": "今人/叙事/受戒.txt",
"B_EVAL": "",
},
{
"BOOKS_ID": "532",
"B_AUTHOR": "林语堂",
"B_NAME": "《京华烟云》",
"B_FILE": "今人/叙事/京华烟云.txt",
"B_EVAL": "",
},
{
"BOOKS_ID": "533",
"B_AUTHOR": "刘慈欣",
"B_NAME": "《流浪地球》",
"B_FILE": "今人/叙事/流浪地球.txt",
"B_EVAL": "line[1]=='.'",
},
];
