var file=[
{F_GROUP: "bug",S_GROUP: "半翅目",TITLE: "椿象橙绿",F_NAME: "chunxiang01.jpg",},
{F_GROUP: "bug",S_GROUP: "半翅目",TITLE: "椿象灰",F_NAME: "chunxiang02.jpg",},
{F_GROUP: "bug",S_GROUP: "半翅目",TITLE: "椿象长腿",F_NAME: "chunxiang03.jpg",},
{F_GROUP: "bug",S_GROUP: "半翅目",TITLE: "丽盾蝽",F_NAME: "chunxiang04.jpg",},
{F_GROUP: "bug",S_GROUP: "半翅目",TITLE: "椿象红",F_NAME: "chunxiang05.jpg",},
{F_GROUP: "bug",S_GROUP: "半翅目",TITLE: "椿的卵",F_NAME: "chundeluan01.jpg",},
{F_GROUP: "bug",S_GROUP: "半翅目",TITLE: "水虫",F_NAME: "shuichong.jpg",},
{F_GROUP: "bug",S_GROUP: "半翅目",TITLE: "知了中",F_NAME: "zhiliao01.jpg",},
{F_GROUP: "bug",S_GROUP: "半翅目",TITLE: "知了壳",F_NAME: "zhiliaoke01.jpg",LINK: "drug/蝉蜕",},
{F_GROUP: "bug",S_GROUP: "半翅目",TITLE: "知了小",F_NAME: "zhiliao02.jpg",},
{F_GROUP: "bug",S_GROUP: "半翅目",TITLE: "黑丽宝岛蝉",F_NAME: "zhiliao03.jpg",},
{F_GROUP: "bug",S_GROUP: "半翅目",TITLE: "眼纹广翅蜡蝉",F_NAME: "lachan01.jpg",},
{F_GROUP: "bug",S_GROUP: "半翅目",TITLE: "离脉叶蝉",F_NAME: "yechan01.jpg",},
{F_GROUP: "bug",S_GROUP: "半翅目",TITLE: "虫壳",F_NAME: "chongke01.jpg",},
{F_GROUP: "bug",S_GROUP: "双翅目",TITLE: "按蚊",F_NAME: "wen01.jpg",F_DESC: "按蚊（Anopheles） 无脊椎动物。 体多呈灰色，翅有黑白花斑，刺吸式口器。静止时腹部翘起，与停落面成一角度。雌虫吸取人、畜的血，传播疟疾和丝虫病等。又称疟蚊。",},
{F_GROUP: "bug",S_GROUP: "双翅目",TITLE: "蓝苍蝇",F_NAME: "cangying01.jpg",},
{F_GROUP: "bug",S_GROUP: "直翅目",TITLE: "棕",F_NAME: "zhichi02.jpg",},
{F_GROUP: "bug",S_GROUP: "直翅目",TITLE: "红螽斯",F_NAME: "zhongsi01.jpg",},
{F_GROUP: "bug",S_GROUP: "直翅目",TITLE: "绿",F_NAME: "zhichi01.jpg",},
{F_GROUP: "bug",S_GROUP: "直翅目",TITLE: "绿蟋蟀",F_NAME: "xishuai01.jpg",},
{F_GROUP: "bug",S_GROUP: "直翅目",TITLE: "蚂蚱会叫",F_NAME: "mazha04.jpg",},
{F_GROUP: "bug",S_GROUP: "直翅目",TITLE: "蚂蚱叶上",F_NAME: "mazha05.jpg",},
{F_GROUP: "bug",S_GROUP: "直翅目",TITLE: "蚂蚱灰",F_NAME: "mazha01.jpg",},
{F_GROUP: "bug",S_GROUP: "直翅目",TITLE: "蚂蚱绿",F_NAME: "mazha03.jpg",},
{F_GROUP: "bug",S_GROUP: "直翅目",TITLE: "蚂蚱黑绿",F_NAME: "mazha02.jpg",},
{F_GROUP: "bug",S_GROUP: "直翅目",TITLE: "蝈蝈",F_NAME: "guoguo01.jpg",},
{F_GROUP: "bug",S_GROUP: "直翅目",TITLE: "黑",F_NAME: "zhichi03.jpg",},
{F_GROUP: "bug",S_GROUP: "直翅目",TITLE: "黑长",F_NAME: "zhichi04.jpg",},
{F_GROUP: "bug",S_GROUP: "竹节虫目",TITLE: "灰竹节虫",F_NAME: "zhujie01.jpg",},
{F_GROUP: "bug",S_GROUP: "膜翅目",TITLE: "亮腹",F_NAME: "mochi01.jpg",},
{F_GROUP: "bug",S_GROUP: "膜翅目",TITLE: "大蜂蚁",F_NAME: "feng10.jpg",},
{F_GROUP: "bug",S_GROUP: "膜翅目",TITLE: "对蜂",F_NAME: "feng13.jpg",},
{F_GROUP: "bug",S_GROUP: "膜翅目",TITLE: "小蜂采蜜",F_NAME: "feng14.jpg",},
{F_GROUP: "bug",S_GROUP: "膜翅目",TITLE: "窗蜂",F_NAME: "feng09.jpg",},
{F_GROUP: "bug",S_GROUP: "膜翅目",TITLE: "红毛尾蜂",F_NAME: "feng08.jpg",},
{F_GROUP: "bug",S_GROUP: "膜翅目",TITLE: "绿眼蜂",F_NAME: "feng15.jpg",},
{F_GROUP: "bug",S_GROUP: "膜翅目",TITLE: "茑萝蚁",F_NAME: "niaoluoyi.jpg",},
{F_GROUP: "bug",S_GROUP: "膜翅目",TITLE: "蚊帐蜂",F_NAME: "feng12.jpg",},
{F_GROUP: "bug",S_GROUP: "膜翅目",TITLE: "蜂小头棕",F_NAME: "feng07.jpg",},
{F_GROUP: "bug",S_GROUP: "膜翅目",TITLE: "蜂窝",F_NAME: "fengwo01.jpg",},
{F_GROUP: "bug",S_GROUP: "膜翅目",TITLE: "蜜蜂1",F_NAME: "feng03.jpg",},
{F_GROUP: "bug",S_GROUP: "膜翅目",TITLE: "蜜蜂2",F_NAME: "feng02.jpg",},
{F_GROUP: "bug",S_GROUP: "膜翅目",TITLE: "长绿眼蜂",F_NAME: "feng01.jpg",},
{F_GROUP: "bug",S_GROUP: "膜翅目",TITLE: "食腐蜂",F_NAME: "feng11.jpg",},
{F_GROUP: "bug",S_GROUP: "膜翅目",TITLE: "黄白相间蜂",F_NAME: "feng05.jpg",},
{F_GROUP: "bug",S_GROUP: "膜翅目",TITLE: "黑蜂1",F_NAME: "feng04.jpg",},
{F_GROUP: "bug",S_GROUP: "膜翅目",TITLE: "黑蜂2",F_NAME: "feng06.jpg",},
{F_GROUP: "bug",S_GROUP: "膜翅目",TITLE: "蜾蠃1",F_NAME: "feng17.jpg",},
{F_GROUP: "bug",S_GROUP: "蜻蜓目",TITLE: "豆娘双",F_NAME: "douniang01.jpg",},
{F_GROUP: "bug",S_GROUP: "蜻蜓目",TITLE: "豆娘蓝翅",F_NAME: "douniang02.jpg",LINK: "mypaint/豆娘",},
{F_GROUP: "bug",S_GROUP: "蜻蜓目",TITLE: "竹枝豆影",F_NAME: "douniang03.jpg",},
{F_GROUP: "bug",S_GROUP: "蜻蜓目",TITLE: "豆娘立蕨",F_NAME: "douniang04.jpg",},
{F_GROUP: "bug",S_GROUP: "蜻蜓目",TITLE: "粉蜻蜓展",F_NAME: "qingting11.jpg",},
{F_GROUP: "bug",S_GROUP: "蜻蜓目",TITLE: "粉蜻蜓平",F_NAME: "qingting05.jpg",},
{F_GROUP: "bug",S_GROUP: "蜻蜓目",TITLE: "背黄腹黑",F_NAME: "qingting03.jpg",},
{F_GROUP: "bug",S_GROUP: "蜻蜓目",TITLE: "蓝蜻蜓",F_NAME: "qingting02.jpg",},
{F_GROUP: "bug",S_GROUP: "蜻蜓目",TITLE: "蓝黄蜻蜓",F_NAME: "qingting06.jpg",},
{F_GROUP: "bug",S_GROUP: "蜻蜓目",TITLE: "褐斑蜻蜓",F_NAME: "qingting01.jpg",F_DESC: "雄虫胸部褐色；腹部橙色；翅膀除末端外为橙色。雌虫和未熟雄虫外观相似，但体色偏黄褐色；翅膀也是淡褐色。",},
{F_GROUP: "bug",S_GROUP: "蜻蜓目",TITLE: "褐蜻蜓",F_NAME: "qingting08.jpg",},
{F_GROUP: "bug",S_GROUP: "蜻蜓目",TITLE: "黄蜻蜓",F_NAME: "qingting07.jpg",},
{F_GROUP: "bug",S_GROUP: "蜻蜓目",TITLE: "黑白蜻蜓",F_NAME: "qingting04.jpg",},
{F_GROUP: "bug",S_GROUP: "蜻蜓目",TITLE: "黑黄相间",F_NAME: "qingting09.jpg",},
{F_GROUP: "bug",S_GROUP: "蜻蜓目",TITLE: "黑黄蓝眼",F_NAME: "qingting10.jpg",},
{F_GROUP: "bug",S_GROUP: "螳螂目",TITLE: "橙螳螂",F_NAME: "tanglang02.jpg",},
{F_GROUP: "bug",S_GROUP: "螳螂目",TITLE: "灰螳螂",F_NAME: "tanglang01.jpg",},
{F_GROUP: "bug",S_GROUP: "螳螂目",TITLE: "绿螳螂",F_NAME: "tanglang03.jpg",LINK: "drug/桑螵蛸",},
{F_GROUP: "bug",S_GROUP: "螳螂目",TITLE: "螳螂青苔",F_NAME: "tanglang04.jpg",},
{F_GROUP: "bug",S_GROUP: "鞘翅目",TITLE: "亮壳六白点",F_NAME: "qiaochi01.jpg",},
{F_GROUP: "bug",S_GROUP: "鞘翅目",TITLE: "十二星瓢虫",F_NAME: "piaochong01.jpg",F_DESC: "十多颗星，吃叶子的。",},
{F_GROUP: "bug",S_GROUP: "鞘翅目",TITLE: "多星瓢虫",F_NAME: "piaochong03.jpg",F_DESC: "吃叶子的。",},
{F_GROUP: "bug",S_GROUP: "鞘翅目",TITLE: "天牛",F_NAME: "tianniu01.jpg",F_DESC: "最常见的那种，小丛丛间拍到嗒。",LINK: "mypaint/天牛",},
{F_GROUP: "bug",S_GROUP: "鞘翅目",TITLE: "棕",F_NAME: "qiaochi05.jpg",},
{F_GROUP: "bug",S_GROUP: "鞘翅目",TITLE: "芫菁",F_NAME: "yuanjing01.jpg",F_DESC: "芫菁 blister beetle 鞘翅目(Coleoptera)芫菁科(Meloidae)甲虫，约2,500种，会分泌出一种刺激性物质，称「斑蝥素」(cantharidin)，主要是从斑蝥属(Mylabris)和欧洲的西班牙芫菁(Lytta vesicatoria, 俗称西班牙苍蝇)收集而来。斑蝥素可用作一种局部皮肤发炎药剂，以除去皮疣。在过去，引出芫菁来医治许多病痛是一种普遍作法，斑蝥素常用来治病。它还是所谓的「春药」的主要成分。芫菁对人类既有益又有害，幼虫食蝗卵，而如果数量很多，成虫就会危害作物。",},
{F_GROUP: "bug",S_GROUP: "鞘翅目",TITLE: "萤火虫",F_NAME: "yinghuo01.jpg",},
{F_GROUP: "bug",S_GROUP: "鞘翅目",TITLE: "西光奥锹甲",F_NAME: "qiaochi07.jpg",},
{F_GROUP: "bug",S_GROUP: "鞘翅目",TITLE: "锚纹瓢虫",F_NAME: "piaochong02.jpg",},
{F_GROUP: "bug",S_GROUP: "鞘翅目",TITLE: "长绿甲",F_NAME: "lvjia01.jpg",},
{F_GROUP: "bug",S_GROUP: "鞘翅目",TITLE: "黄",F_NAME: "qiaochi06.jpg",},
{F_GROUP: "bug",S_GROUP: "鞘翅目",TITLE: "黑",F_NAME: "qiaochi03.jpg",},
{F_GROUP: "bug",S_GROUP: "鞘翅目",TITLE: "黑壳两白点",F_NAME: "qiaochi02.jpg",},
{F_GROUP: "bug",S_GROUP: "鞘翅目",TITLE: "黑翘",F_NAME: "qiaochi04.jpg",},
{F_GROUP: "bug",S_GROUP: "鞘翅目",TITLE: "黑肚翘",F_NAME: "qiaochi08.jpg",},
{F_GROUP: "bug",S_GROUP: "鞘翅目",TITLE: "黑长须",F_NAME: "qiaochi09.jpg",},
{F_GROUP: "bug",S_GROUP: "鞘翅目",TITLE: "黑长须2",F_NAME: "qiaochi12.jpg",},
{F_GROUP: "bug",S_GROUP: "鞘翅目",TITLE: "粪金龟",F_NAME: "qiaochi10.jpg",},
{F_GROUP: "bug",S_GROUP: "鞘翅目",TITLE: "小棕毛",F_NAME: "qiaochi11.jpg",},
{F_GROUP: "bug",S_GROUP: "鳞翅目",TITLE: "凤蝶黑",F_NAME: "die06.jpg",},
{F_GROUP: "bug",S_GROUP: "鳞翅目",TITLE: "叶蝶",F_NAME: "die05.jpg",},
{F_GROUP: "bug",S_GROUP: "鳞翅目",TITLE: "枯叶蝶",F_NAME: "die03.jpg",F_DESC: "叶子枯了。",},
{F_GROUP: "bug",S_GROUP: "鳞翅目",TITLE: "枯木绿蝶",F_NAME: "die23.jpg",},
{F_GROUP: "bug",S_GROUP: "鳞翅目",TITLE: "橘蝶蛹",F_NAME: "yong01.jpg",},
{F_GROUP: "bug",S_GROUP: "鳞翅目",TITLE: "橘蝶虫",F_NAME: "maochong01.jpg",},
{F_GROUP: "bug",S_GROUP: "鳞翅目",TITLE: "毛虫橙紫",F_NAME: "maochong02.jpg",},
{F_GROUP: "bug",S_GROUP: "鳞翅目",TITLE: "毛虫橙黑",F_NAME: "maochong03.jpg",},
{F_GROUP: "bug",S_GROUP: "鳞翅目",TITLE: "白点黑",F_NAME: "die21.jpg",},
{F_GROUP: "bug",S_GROUP: "鳞翅目",TITLE: "眼纹蝶",F_NAME: "die04.jpg",},
{F_GROUP: "bug",S_GROUP: "鳞翅目",TITLE: "破草蝶",F_NAME: "die19.jpg",},
{F_GROUP: "bug",S_GROUP: "鳞翅目",TITLE: "粉蝶",F_NAME: "die01.jpg",F_DESC: "最常见的白蝴蝶，到处都能看见。",},
{F_GROUP: "bug",S_GROUP: "鳞翅目",TITLE: "红蝶",F_NAME: "die08.jpg",},
{F_GROUP: "bug",S_GROUP: "鳞翅目",TITLE: "红黄黑",F_NAME: "die18.jpg",},
{F_GROUP: "bug",S_GROUP: "鳞翅目",TITLE: "蓝点白",F_NAME: "die07.jpg",},
{F_GROUP: "bug",S_GROUP: "鳞翅目",TITLE: "蓝白蝶",F_NAME: "die02.jpg",},
{F_GROUP: "bug",S_GROUP: "鳞翅目",TITLE: "蛾灰",F_NAME: "die11.jpg",},
{F_GROUP: "bug",S_GROUP: "鳞翅目",TITLE: "蛾长白",F_NAME: "die09.jpg",},
{F_GROUP: "bug",S_GROUP: "鳞翅目",TITLE: "长喙天蛾",F_NAME: "die20.jpg",},
{F_GROUP: "bug",S_GROUP: "鳞翅目",TITLE: "黄点黑",F_NAME: "die10.jpg",},
{F_GROUP: "bug",S_GROUP: "鳞翅目",TITLE: "黄黑白蝶",F_NAME: "die12.jpg",},
{F_GROUP: "bug",S_GROUP: "鳞翅目",TITLE: "黄黑相间",F_NAME: "die14.jpg",},
{F_GROUP: "bug",S_GROUP: "鳞翅目",TITLE: "黑一白条",F_NAME: "die15.jpg",},
{F_GROUP: "bug",S_GROUP: "鳞翅目",TITLE: "黑三白条",F_NAME: "die16.jpg",},
{F_GROUP: "bug",S_GROUP: "鳞翅目",TITLE: "黑凤蝶飞",F_NAME: "die22.jpg",},
{F_GROUP: "bug",S_GROUP: "鳞翅目",TITLE: "黑点白",F_NAME: "die13.jpg",},
{F_GROUP: "bug",S_GROUP: "鳞翅目",TITLE: "黑白头黄",F_NAME: "die17.jpg",},
{F_GROUP: "bug",S_GROUP: "鳞翅目",TITLE: "燄駝蛾",F_NAME: "die24.jpg",},
{F_GROUP: "bug",S_GROUP: "脉翅目",TITLE: "蚜狮",F_NAME: "yashi01.jpg",F_DESC: "蚜狮是草蛉的幼虫，纺锤状，喜在树叶间捕食蚜虫，故称蚜狮。",},
{F_GROUP: "bug",S_GROUP: "蜈蚣目",TITLE: "小蜈蚣",F_NAME: "wugong02.jpg",},
{F_GROUP: "bug",S_GROUP: "蜈蚣目",TITLE: "蜈蚣",F_NAME: "wugong01.jpg",F_DESC: "《本草纲目》曰：“蜈蚣，西南处处有之，春出冬蛰，节节有足，双须岐尾。”",LINK:"drug/蜈蚣",},
{F_GROUP: "bug",S_GROUP: "蜘蛛目",TITLE: "夜树",F_NAME: "zhu02.jpg",},
{F_GROUP: "bug",S_GROUP: "蜘蛛目",TITLE: "大圆",F_NAME: "zhu09.jpg",},
{F_GROUP: "bug",S_GROUP: "蜘蛛目",TITLE: "大花",F_NAME: "zhu07.jpg",},
{F_GROUP: "bug",S_GROUP: "蜘蛛目",TITLE: "毛腿",F_NAME: "zhu06.jpg",},
{F_GROUP: "bug",S_GROUP: "蜘蛛目",TITLE: "窝",F_NAME: "zhizhuwo01.jpg",},
{F_GROUP: "bug",S_GROUP: "蜘蛛目",TITLE: "竹根下",F_NAME: "zhu03.jpg",},
{F_GROUP: "bug",S_GROUP: "蜘蛛目",TITLE: "绿",F_NAME: "zhu04.jpg",},
{F_GROUP: "bug",S_GROUP: "蜘蛛目",TITLE: "脸蛛",F_NAME: "zhu01.jpg",},
{F_GROUP: "bug",S_GROUP: "蜘蛛目",TITLE: "腿橙黑白",F_NAME: "zhu08.jpg",},
{F_GROUP: "bug",S_GROUP: "蜘蛛目",TITLE: "蛛丝雨",F_NAME: "zhu05.jpg",},
{F_GROUP: "bug",S_GROUP: "蜘蛛目",TITLE: "蛛在看",F_NAME: "zhu10.jpg",},
{F_GROUP: "bug",S_GROUP: "蜘蛛目",TITLE: "蛛在台",F_NAME: "zhu11.jpg",},
{F_GROUP: "bug",S_GROUP: "等足目",TITLE: "球鼠妇",F_NAME: "qiushufu01.jpg",},
{F_GROUP: "bug",S_GROUP: "单向蚓目",TITLE: "蚯蚓",F_NAME: "qiuyin01.jpg",LINK: "drug/地龙",},
{F_GROUP: "bug",S_GROUP: "未知目",TITLE: "树上垂下",F_NAME: "weizhi01.jpg",},

{F_GROUP: "miao",S_GROUP: "两栖纲",S_ORDER: "无尾目",S_FAMILY: "蛙科",TITLE: "白蛙",F_NAME: "baiwa.jpg",},
{F_GROUP: "miao",S_GROUP: "两栖纲",S_ORDER: "无尾目",S_FAMILY: "蛙科",TITLE: "蝌蚪",F_NAME: "kedou01.jpg",},
{F_GROUP: "miao",S_GROUP: "两栖纲",S_ORDER: "无尾目",S_FAMILY: "蛙科",TITLE: "鸣蛙",F_NAME: "wa01.jpg",},
{F_GROUP: "miao",S_GROUP: "未知",TITLE: "触角怪",F_NAME: "weizhi01.jpg",},
{F_GROUP: "miao",S_GROUP: "未知",TITLE: "软软的",F_NAME: "weizhi02.jpg",},
{F_GROUP: "miao",S_GROUP: "爬行纲",S_ORDER: "龟鳖目",S_FAMILY: "龟科",TITLE: "乌龟",F_NAME: "gui.jpg",F_DESC: "看啥呢？",},
{F_GROUP: "miao",S_GROUP: "爬行纲",S_ORDER: "有鳞目",S_FAMILY: "蜥蜴科",TITLE: "四脚蛇",F_NAME: "sijiaoshe.jpg",F_DESC: "路边偶遇",},
{F_GROUP: "miao",S_GROUP: "爬行纲",S_ORDER: "有鳞目",S_FAMILY: "蜥蜴科",TITLE: "黑纹四脚蛇",F_NAME: "sijiaoshe02.jpg",F_DESC: "路边偶遇",},
{F_GROUP: "miao",S_GROUP: "爬行纲",S_ORDER: "有鳞目",S_FAMILY: "蜥蜴科",TITLE: "石龙子",F_NAME: "shilongzi01.jpg",F_DESC: "路边偶遇",},
{F_GROUP: "miao",S_GROUP: "爬行纲",S_ORDER: "有鳞目",S_FAMILY: "蜥蜴科",TITLE: "南草蜥",F_NAME: "xiyi01.jpg",F_DESC: "路边偶遇",},
{F_GROUP: "miao",S_GROUP: "爬行纲",S_ORDER: "有鳞目",S_FAMILY: "蝰科",TITLE: "竹叶青",F_NAME: "she01.jpg",F_DESC: "路边偶遇",},
{F_GROUP: "miao",S_GROUP: "爬行纲",S_ORDER: "有鳞目",S_FAMILY: "游蛇科",TITLE: "紫沙蛇",F_NAME: "zishashe01.jpg",F_DESC: "路边偶遇",},
{F_GROUP: "miao",S_GROUP: "爬行纲",S_ORDER: "有鳞目",S_FAMILY: "游蛇科",TITLE: "红脖颈槽蛇",F_NAME: "hbjcs01.jpg",F_DESC: "路边偶遇",},
{F_GROUP: "miao",S_GROUP: "爬行纲",S_ORDER: "有鳞目",S_FAMILY: "游蛇科",TITLE: "绿瘦蛇",F_NAME: "lvshoushe01.jpg",F_DESC: "路边偶遇",},
{F_GROUP: "miao",S_GROUP: "腹足纲",S_ORDER: "中腹足目",TITLE: "叶螺",F_NAME: "luo01.jpg",},
{F_GROUP: "miao",S_GROUP: "腹足纲",S_ORDER: "中腹足目",TITLE: "海螺",F_NAME: "luo02.jpg",},
{F_GROUP: "miao",S_GROUP: "腹足纲",S_ORDER: "柄眼目",S_FAMILY: "蜗牛科",TITLE: "蜗牛",F_NAME: "woniu01.jpg",},
{F_GROUP: "miao",S_GROUP: "软甲纲",S_ORDER: "十足目",S_FAMILY: "螃蟹",TITLE: "沙蟹",F_NAME: "xie03.jpg",F_DESC: "螃蟹",},
{F_GROUP: "miao",S_GROUP: "软甲纲",S_ORDER: "十足目",S_FAMILY: "螃蟹",TITLE: "滩蟹",F_NAME: "xie07.jpg",F_DESC: "螃蟹",},
{F_GROUP: "miao",S_GROUP: "软甲纲",S_ORDER: "十足目",S_FAMILY: "螃蟹",TITLE: "红树林蟹",F_NAME: "xie06.jpg",F_DESC: "螃蟹",},
{F_GROUP: "miao",S_GROUP: "软甲纲",S_ORDER: "十足目",S_FAMILY: "螃蟹",TITLE: "红蟹",F_NAME: "xie02.jpg",F_DESC: "螃蟹",},
{F_GROUP: "miao",S_GROUP: "软甲纲",S_ORDER: "十足目",S_FAMILY: "螃蟹",TITLE: "藏蟹",F_NAME: "xie05.jpg",F_DESC: "螃蟹",},
{F_GROUP: "miao",S_GROUP: "软甲纲",S_ORDER: "十足目",S_FAMILY: "螃蟹",TITLE: "蟹和螺",F_NAME: "xie04.jpg",F_DESC: "螃蟹",},
{F_GROUP: "miao",S_GROUP: "软甲纲",S_ORDER: "十足目",S_FAMILY: "螃蟹",TITLE: "黑黄蟹",F_NAME: "xie01.jpg",F_DESC: "螃蟹",},
{F_GROUP: "miao",S_GROUP: "软甲纲",S_ORDER: "等足目",S_FAMILY: "海蟑螂科",TITLE: "海蟑螂",F_NAME: "haizhanglang01.jpg",},
{F_GROUP: "miao",S_GROUP: "鱼纲",S_ORDER: "鲤形目",S_FAMILY: "鲤科",TITLE: "一群长鱼",F_NAME: "yu02.jpg",F_DESC: "鱼儿",},
{F_GROUP: "miao",S_GROUP: "鱼纲",S_ORDER: "鲤形目",S_FAMILY: "鲤科",TITLE: "一群鱼",F_NAME: "qunyu.jpg",F_DESC: "鱼儿",},
{F_GROUP: "miao",S_GROUP: "鱼纲",S_ORDER: "鲤形目",S_FAMILY: "鲤科",TITLE: "俩鱼",F_NAME: "liayu.jpg",F_DESC: "鱼儿",},
{F_GROUP: "miao",S_GROUP: "鱼纲",TITLE: "细长",F_NAME: "yu01.jpg",F_DESC: "鱼儿",},
{F_GROUP: "miao",S_GROUP: "鱼纲",S_ORDER: "鲤形目",S_FAMILY: "鲤科",TITLE: "草鱼",F_NAME: "caoyu.jpg",F_DESC: "鱼儿",},
{F_GROUP: "miao",S_GROUP: "鱼纲",S_ORDER: "鲤形目",S_FAMILY: "鲤科",TITLE: "金鱼",F_NAME: "jinyu.jpg",F_DESC: "鱼儿",},
{F_GROUP: "miao",S_GROUP: "鱼纲",S_ORDER: "鲤形目",S_FAMILY: "鲤科",TITLE: "鲤鱼",F_NAME: "liyu01.jpg",F_DESC: "鱼儿",},
{F_GROUP: "miao",S_GROUP: "鸟纲",S_ORDER: "鸡形目",S_FAMILY: "雉科",TITLE: "泥滑滑打架了",F_NAME: "nihuahua01.jpg",LINK: "bird/灰胸竹鸡",},
{F_GROUP: "miao",S_GROUP: "鸟纲",S_ORDER: "雀形目",S_FAMILY: "伯劳科",TITLE: "伯劳立枝",F_NAME: "bolao01.jpg",LINK: "bird/棕背伯劳",},
{F_GROUP: "miao",S_GROUP: "鸟纲",S_ORDER: "雀形目",S_FAMILY: "鹎科",TITLE: "红耳鹎电线上",F_NAME: "hongerbei01.jpg",LINK: "bird/红耳鹎",},
{F_GROUP: "miao",S_GROUP: "哺乳纲",S_ORDER: "长鼻目",S_FAMILY: "长鼻目",TITLE: "大象",F_NAME: "daxiang01.jpg",},
{F_GROUP: "miao",S_GROUP: "哺乳纲",S_ORDER: "啮齿目",S_FAMILY: "松鼠科",TITLE: "赤腹松鼠",F_NAME: "songshu.jpg",F_DESC: "赤腹松鼠（学名：Callosciurus erythraeus ）又称红腹松鼠，为啮齿类动物。栖息于热带和亚热带森林，亦见于次生林、砍伐迹地以及丘陵台地、椰林、灌木林、竹林、乔木和竹林混交林、马尾松林、枞林、灌木丛等植被环境，是树栖动物。",},
{F_GROUP: "miao",S_GROUP: "哺乳纲",S_ORDER: "啮齿目",S_FAMILY: "松鼠科",TITLE: "隐纹花鼠",F_NAME: "huashu.jpg",F_DESC: "筑巢于树叉间或利用树洞作窝。其主要食物为各种坚果、浆果以及昆虫等，常与红腹松鼠一起觅食。",},
{F_GROUP: "miao",S_GROUP: "哺乳纲",S_ORDER: "啮齿目",S_FAMILY: "松鼠科",TITLE: "松鼠在看1",F_NAME: "songshu01.jpg",F_DESC: "松鼠在看~~~",},
{F_GROUP: "miao",S_GROUP: "哺乳纲",S_ORDER: "啮齿目",S_FAMILY: "松鼠科",TITLE: "松鼠在看2",F_NAME: "songshu03.jpg",},
{F_GROUP: "miao",S_GROUP: "哺乳纲",S_ORDER: "啮齿目",S_FAMILY: "松鼠科",TITLE: "松鼠吃果",F_NAME: "songshu02.jpg",},
{F_GROUP: "miao",S_GROUP: "哺乳纲",S_ORDER: "啮齿目",S_FAMILY: "鼠科",TITLE: "鼠",F_NAME: "shu.jpg",F_DESC: "喵才不吃。。。",},
{F_GROUP: "miao",S_GROUP: "哺乳纲",S_ORDER: "兔形目",S_FAMILY: "兔科",TITLE: "可怜的兔兔",F_NAME: "tuzi01.jpg",},
{F_GROUP: "miao",S_GROUP: "哺乳纲",S_ORDER: "食肉目",S_FAMILY: "猫科",TITLE: "白喵",F_NAME: "miao01.jpg",F_DESC: "喵就是喵~ 喵呜~~~",},
{F_GROUP: "miao",S_GROUP: "哺乳纲",S_ORDER: "食肉目",S_FAMILY: "猫科",TITLE: "花喵",F_NAME: "miao.jpg",F_DESC: "喵就是喵~ 喵呜~~~",},
{F_GROUP: "miao",S_GROUP: "哺乳纲",S_ORDER: "食肉目",S_FAMILY: "猫科",TITLE: "草丛喵",F_NAME: "miao04.jpg",F_DESC: "喵就是喵~ 喵呜~~~",},
{F_GROUP: "miao",S_GROUP: "哺乳纲",S_ORDER: "食肉目",S_FAMILY: "猫科",TITLE: "黑喵",F_NAME: "miao03.jpg",F_DESC: "喵就是喵~ 喵呜~~~",},
{F_GROUP: "miao",S_GROUP: "哺乳纲",S_ORDER: "食肉目",S_FAMILY: "猫科",TITLE: "俩喵",F_NAME: "miao05.jpg",F_DESC: "喵就是喵~ 喵呜~~~",},
{F_GROUP: "miao",S_GROUP: "哺乳纲",S_ORDER: "食肉目",S_FAMILY: "熊科",TITLE: "大熊猫",F_NAME: "dxm01.jpg",},
{F_GROUP: "miao",S_GROUP: "哺乳纲",S_ORDER: "食肉目",S_FAMILY: "熊科",TITLE: "灰熊",F_NAME: "gouxiong01.jpg",},
{F_GROUP: "miao",S_GROUP: "哺乳纲",S_ORDER: "食肉目",S_FAMILY: "犬科",TITLE: "黄汪",F_NAME: "wang01.jpg",F_DESC: "汪就是汪！汪~~~",},
{F_GROUP: "miao",S_GROUP: "哺乳纲",S_ORDER: "食肉目",S_FAMILY: "犬科",TITLE: "汪在飞",F_NAME: "wang02.jpg",F_DESC: "会飞的汪！汪~~~",},
{F_GROUP: "miao",S_GROUP: "哺乳纲",S_ORDER: "食肉目",S_FAMILY: "犬科",TITLE: "黑汪",F_NAME: "wang.jpg",F_DESC: "汪就是汪！汪~~~",},
{F_GROUP: "miao",S_GROUP: "哺乳纲",S_ORDER: "翼手目",S_FAMILY: "蝙蝠科",TITLE: "蝙蝠",F_NAME: "bianfu01.jpg",},
{F_GROUP: "miao",S_GROUP: "哺乳纲",S_ORDER: "奇蹄目",S_FAMILY: "貘科",TITLE: "貘",F_NAME: "mo01.jpg",},
{F_GROUP: "miao",S_GROUP: "哺乳纲",S_ORDER: "奇蹄目",S_FAMILY: "马科",TITLE: "马",F_NAME: "ma.jpg",F_DESC: "照相的",},
{F_GROUP: "miao",S_GROUP: "哺乳纲",S_ORDER: "偶蹄目",S_FAMILY: "牛科",TITLE: "黄牛",F_NAME: "huangniu.jpg",},
{F_GROUP: "miao",S_GROUP: "哺乳纲",S_ORDER: "偶蹄目",S_FAMILY: "牛科",TITLE: "羊",F_NAME: "yang.jpg",F_DESC: "路边偶遇",},
{F_GROUP: "miao",S_GROUP: "哺乳纲",S_ORDER: "食虫目",S_FAMILY: "鼩鼱科",TITLE: "鼩鼱",F_NAME: "qujing01.jpg",F_DESC: "咦！",},

{F_GROUP: "scene",S_GROUP:"星辰日月",TITLE:"凉如水",F_NAME:"yklrs.jpg",F_DESC:"夜色凉如水",},
{F_GROUP: "scene",S_GROUP:"星辰日月",TITLE:"仙女星云",F_NAME:"xiannv.jpg",},
{F_GROUP: "scene",S_GROUP:"星辰日月",TITLE:"昴",F_NAME:"mao.jpg",},
{F_GROUP: "scene",S_GROUP:"星辰日月",TITLE:"云天",F_NAME:"yuntian.jpg",},
{F_GROUP: "scene",S_GROUP:"星辰日月",TITLE:"岁",F_NAME:"muxing.jpg",F_DESC:"《甘石星经》有云<br>\r\n“单阏之岁，摄提格在卯，岁星在子，与须女、虚、危晨出夕入，其状甚大有光，若有小赤星附于其侧，是谓同盟。”<br>\r\n小赤星，图一岁星右上最外一颗，即是。",},
{F_GROUP: "scene",S_GROUP:"星辰日月",TITLE:"海王星",F_NAME:"hwx01.jpg",F_DESC:"2019 09 12",},
{F_GROUP: "scene",S_GROUP:"星辰日月",TITLE:"火星",F_NAME:"mars01.jpg",F_DESC:"2018 07 28",},
{F_GROUP: "scene",S_GROUP:"星辰日月",TITLE:"彗星",F_NAME:"46P.jpg",F_DESC:"2018 12 18",},
{F_GROUP: "scene",S_GROUP:"星辰日月",TITLE:"青天白日",F_NAME:"qtbr.jpg",},
{F_GROUP: "scene",S_GROUP:"星辰日月",TITLE:"太阳黑子",F_NAME:"heizi01.jpg",F_DESC:"2019 05 12 18:23",},
{F_GROUP: "scene",S_GROUP:"星辰日月",TITLE:"日暮霞光",F_NAME:"xiaguang01.jpg",},
{F_GROUP: "scene",S_GROUP:"星辰日月",TITLE:"月全食",F_NAME:"yuequanshi01.jpg",F_DESC:"2018 07 28 0‏‎3:50:16",},
{F_GROUP: "scene",S_GROUP:"星辰日月",TITLE:"月下娘娘庙",F_NAME:"nnm.jpg",F_DESC:"月下娘娘庙，海月共潮升",},
{F_GROUP: "scene",S_GROUP:"星辰日月",TITLE:"月有食",F_NAME:"yueshi.jpg",F_DESC:"丁酉闰六月十七，月有食之，山河动，古树摇。",},
{F_GROUP: "scene",S_GROUP:"星辰日月",TITLE:"月云",F_NAME:"yueyun.jpg",},
{F_GROUP: "scene",S_GROUP:"星辰日月",TITLE:"星月合",F_NAME:"jxhy.jpg",F_DESC:"金星合月",},
{F_GROUP: "scene",S_GROUP:"星辰日月",TITLE:"蝠月",F_NAME:"fuyue.jpg",},
{F_GROUP: "scene",S_GROUP:"星辰日月",TITLE:"树月",F_NAME:"shuyue.jpg",},
{F_GROUP: "scene",S_GROUP:"星辰日月",TITLE:"冷月",F_NAME:"yue1.jpg",},
{F_GROUP: "scene",S_GROUP:"星辰日月",TITLE:"海月升",F_NAME:"haiyuesheng.jpg",},

{F_GROUP: "scene",S_GROUP:"林海花果",TITLE:"稻田",F_NAME:"daotian.jpg",},
{F_GROUP: "scene",S_GROUP:"林海花果",TITLE:"夜树",F_NAME:"yeshu.jpg",},
{F_GROUP: "scene",S_GROUP:"林海花果",TITLE:"树天",F_NAME:"shutian.jpg",},
{F_GROUP: "scene",S_GROUP:"林海花果",TITLE:"望天",F_NAME:"wangtian.jpg",},
{F_GROUP: "scene",S_GROUP:"林海花果",TITLE:"蓝红绿",F_NAME:"lanhonglv.jpg",},
{F_GROUP: "scene",S_GROUP:"林海花果",TITLE:"林间蛛网",F_NAME:"zhuwang01.jpg",},
{F_GROUP: "scene",S_GROUP:"河海湖山",TITLE:"河清",F_NAME:"river1.jpg",F_DESC:"河水",},
{F_GROUP: "scene",S_GROUP:"河海湖山",TITLE:"湖中游",F_NAME:"xihu01.jpg",},
{F_GROUP: "scene",S_GROUP:"河海湖山",TITLE:"玉带晴虹",F_NAME:"xihu02.jpg",},
{F_GROUP: "scene",S_GROUP:"河海湖山",TITLE:"荷塘·夏",F_NAME:"hetang01.jpg",LINK: "drug/荷叶",},
{F_GROUP: "scene",S_GROUP:"河海湖山",TITLE:"荷塘·秋",F_NAME:"hetang02.jpg",LINK: "drug/荷叶",},
{F_GROUP: "scene",S_GROUP:"河海湖山",TITLE:"西湖",F_NAME:"xihu03.jpg",},
{F_GROUP: "scene",S_GROUP:"河海湖山",TITLE:"湖中岛",F_NAME:"xihu04.jpg",},
{F_GROUP: "scene",S_GROUP:"河海湖山",TITLE:"江原",F_NAME:"jiangyuan.jpg",},
{F_GROUP: "scene",S_GROUP:"河海湖山",TITLE:"水岸",F_NAME:"shuian.jpg",},
{F_GROUP: "scene",S_GROUP:"河海湖山",TITLE:"水冷潭空",F_NAME:"shuiqing.jpg",},
{F_GROUP: "scene",S_GROUP:"河海湖山",TITLE:"落日",F_NAME:"hairi.jpg",},
{F_GROUP: "scene",S_GROUP:"河海湖山",TITLE:"孤树",F_NAME:"gushu.jpg",F_DESC:"孤单的大树。",},
{F_GROUP: "scene",S_GROUP:"河海湖山",TITLE:"雾山",F_NAME:"wushan.jpg",},
{F_GROUP: "scene",S_GROUP:"河海湖山",TITLE:"湖光",F_NAME:"huguang.jpg",},
{F_GROUP: "scene",S_GROUP:"河海湖山",TITLE:"海沙痕",F_NAME:"niaosha.jpg",},
{F_GROUP: "scene",S_GROUP:"河海湖山",TITLE:"海石",F_NAME:"haishi.jpg",},
{F_GROUP: "scene",S_GROUP:"雨雾霜露",TITLE:"雨落",F_NAME:"yuluo.jpg",},
{F_GROUP: "scene",S_GROUP:"雨雾霜露",TITLE:"空山一段云",F_NAME:"ksydy.jpg",},
{F_GROUP: "scene",S_GROUP:"雨雾霜露",TITLE:"雨草",F_NAME:"yucao.jpg",},
{F_GROUP: "scene",S_GROUP:"雨雾霜露",TITLE:"草露",F_NAME:"caolu.jpg",},
{F_GROUP: "scene",S_GROUP:"雨雾霜露",TITLE:"山雾",F_NAME:"shanwu.jpg",},
{F_GROUP: "scene",S_GROUP:"雨雾霜露",TITLE:"云过楼",F_NAME:"yunlou.jpg",F_DESC:"云过楼",},
{F_GROUP: "scene",S_GROUP:"雨雾霜露",TITLE: "雨荷",F_NAME: "hehuayu.jpg",},
{F_GROUP: "scene",S_GROUP:"鸟兽鱼虫",TITLE:"海沙狗",F_NAME:"shantangou.jpg",},
{F_GROUP: "scene",S_GROUP:"鸟兽鱼虫",TITLE:"大鸟在天",F_NAME:"daniao.jpg",},
{F_GROUP: "scene",S_GROUP:"鸟兽鱼虫",TITLE:"湖鸟",F_NAME:"huniao.jpg",},
{F_GROUP: "scene",S_GROUP:"鸟兽鱼虫",TITLE:"虫鸟树",F_NAME:"chongniao.jpg",},
{F_GROUP: "scene",S_GROUP:"鸟兽鱼虫",TITLE:"树影",F_NAME:"muniao.jpg",},
{F_GROUP: "scene",S_GROUP:"鸟兽鱼虫",TITLE:"飞鸟枯树",F_NAME:"feiniaokushu.jpg",},
{F_GROUP: "scene",S_GROUP:"鸟兽鱼虫",TITLE:"苇莺",F_NAME:"weiying.jpg",},
{F_GROUP: "scene",S_GROUP:"鸟兽鱼虫",TITLE:"飞鸟阵",F_NAME:"niaozhen.jpg",},
{F_GROUP: "scene",S_GROUP:"鸟兽鱼虫",TITLE:"芦苇黑伯劳",F_NAME:"luweibolao.jpg",},
{F_GROUP: "scene",S_GROUP:"鸟兽鱼虫",TITLE:"群鸟过树",F_NAME:"qunniao01.jpg",},

{F_GROUP: "utensil",S_GROUP:"器物",TITLE:"楚编钟",F_NAME:"chubiaozhong.jpg",F_DESC:"楚编钟",},
{F_GROUP: "utensil",S_GROUP:"器物",TITLE:"石头棋",F_NAME:"shitouqi.jpg",},
{F_GROUP: "utensil",S_GROUP:"器物",TITLE:"元青花四爱图梅瓶",F_NAME:"ciping01.jpg",},
{F_GROUP: "utensil",S_GROUP:"器物",TITLE:"越王勾践剑",F_NAME:"yuewangjian.jpg",F_DESC:"越王勾践剑",},
{F_GROUP: "utensil",S_GROUP:"器物",TITLE:"陶盆",F_NAME:"tao08.jpg",},
{F_GROUP: "utensil",S_GROUP:"器物",TITLE:"七里河",F_NAME:"qilihe01.jpg",},
{F_GROUP: "utensil",S_GROUP:"建筑",TITLE:"武大门（夜）",F_NAME:"whdx02.jpg",},
{F_GROUP: "utensil",S_GROUP:"建筑",TITLE:"苏小小墓",F_NAME:"suxiaoxiaomu.jpg",},
{F_GROUP: "utensil",S_GROUP:"建筑",TITLE:"浙大门",F_NAME:"zheda01.jpg",},
{F_GROUP: "utensil",S_GROUP:"建筑",TITLE:"庙葫芦",F_NAME:"hulu01.jpg",},
{F_GROUP: "utensil",S_GROUP:"建筑",TITLE:"滕阁秋风",F_NAME:"twg01.jpg",},
{F_GROUP: "utensil",S_GROUP:"建筑",TITLE:"雷峰塔",F_NAME:"lft09.jpg",},
{F_GROUP: "utensil",S_GROUP:"建筑",TITLE:"开元塔",F_NAME:"kys01.jpg",},
{F_GROUP: "utensil",S_GROUP:"建筑",TITLE:"北京站",F_NAME:"bjz.jpg",},
{F_GROUP: "utensil",S_GROUP:"建筑",TITLE:"雾里长城",F_NAME:"cc01.jpg",},
{F_GROUP: "utensil",S_GROUP:"建筑",TITLE:"楚天极目",F_NAME:"hhl08.jpg",},
{F_GROUP: "utensil",S_GROUP:"建筑",TITLE:"鄂军都督府内",F_NAME:"hbddf02.jpg",},
{F_GROUP: "utensil",S_GROUP:"建筑",TITLE:"保俶塔",F_NAME:"baochuta.jpg",},
{F_GROUP: "utensil",S_GROUP:"建筑",TITLE:"断桥",F_NAME:"duanqiao.jpg",},
{F_GROUP: "utensil",S_GROUP:"建筑",TITLE:"雷峰塔塔基",F_NAME:"lft07.jpg",},
{F_GROUP: "utensil",S_GROUP:"建筑",TITLE:"岳武穆遗像亭",F_NAME:"hhl04.jpg",},
{F_GROUP: "utensil",S_GROUP:"建筑",TITLE:"曲水流觞",F_NAME:"hhl06.jpg",},
{F_GROUP: "utensil",S_GROUP:"建筑",TITLE:"太和殿",F_NAME:"taihedian.jpg",},
{F_GROUP: "utensil",S_GROUP:"建筑",TITLE:"卢沟桥",F_NAME:"lgq.jpg",},
{F_GROUP: "utensil",S_GROUP:"建筑",TITLE:"十七孔桥",F_NAME:"yhy02.jpg",},
{F_GROUP: "utensil",S_GROUP:"建筑",TITLE:"颐和故楼",F_NAME:"yhy01.jpg",},
{F_GROUP: "utensil",S_GROUP:"建筑",TITLE:"鄂军都督府",F_NAME:"ejundudufu.jpg",F_DESC:"鄂军都督府",},
{F_GROUP: "utensil",S_GROUP:"建筑",TITLE:"雪屋顶",F_NAME:"tt03.jpg",},
{F_GROUP: "utensil",S_GROUP:"建筑",TITLE:"宛平城门",F_NAME:"wpc01.jpg",},
{F_GROUP: "utensil",S_GROUP:"建筑",TITLE:"天坛",F_NAME:"tt01.jpg",},
{F_GROUP: "utensil",S_GROUP:"建筑",TITLE:"玉带晴虹",F_NAME:"qyfh01.jpg",F_DESC:"玉带晴虹",},
{F_GROUP: "utensil",S_GROUP:"建筑",TITLE:"武大门（日）",F_NAME:"whdx01.jpg",},
{F_GROUP: "utensil",S_GROUP:"建筑",TITLE:"水桥",F_NAME:"shuiqiao.jpg",},
{F_GROUP: "utensil",S_GROUP:"建筑",TITLE:"雄州雾列",F_NAME:"twg02.jpg",},
{F_GROUP: "utensil",S_GROUP:"建筑",TITLE:"古屋尖顶",F_NAME:"jianding.jpg",},
{F_GROUP: "utensil",S_GROUP:"建筑",TITLE:"武汉长江大桥",F_NAME:"whcjdq.jpg",},
{F_GROUP: "utensil",S_GROUP:"建筑",TITLE:"林徽因墓",F_NAME:"huiyingmu.jpg",},
{F_GROUP: "utensil",S_GROUP:"建筑",TITLE:"武松墓",F_NAME:"wusongmu.jpg",},
{F_GROUP: "utensil",S_GROUP:"碑刻",TITLE:"盡忠報国",F_NAME:"ym04.jpg",},
{F_GROUP: "utensil",S_GROUP:"碑刻",TITLE:"越王台",F_NAME:"ywt01.jpg",},
{F_GROUP: "utensil",S_GROUP:"碑刻",TITLE:"盘龙雪水",F_NAME:"tt02.jpg",},
{F_GROUP: "utensil",S_GROUP:"碑刻",TITLE:"黄鹤楼公园",F_NAME:"hhl07.jpg",},
{F_GROUP: "utensil",S_GROUP:"碑刻",TITLE:"雷峰塔重建",F_NAME:"lft02.jpg",},
{F_GROUP: "utensil",S_GROUP:"碑刻",TITLE:"精忠报国",F_NAME:"hhl03.jpg",},
{F_GROUP: "utensil",S_GROUP:"碑刻",TITLE:"一统天下",F_NAME:"duian.jpg",},
{F_GROUP: "utensil",S_GROUP:"碑刻",TITLE:"黄鹤楼",F_NAME:"hhl01.jpg",},
{F_GROUP: "utensil",S_GROUP:"碑刻",TITLE:"碧血丹心",F_NAME:"yuemiao01.jpg",},
{F_GROUP: "utensil",S_GROUP:"碑刻",TITLE:"开元寺窗雕",F_NAME:"kys02.jpg",},
{F_GROUP: "utensil",S_GROUP:"碑刻",TITLE:"灵隐寺窗雕",F_NAME:"lys02.jpg",},
{F_GROUP: "utensil",S_GROUP:"碑刻",TITLE:"雷峰塔夕照毓秀",F_NAME:"lft03.jpg",},
{F_GROUP: "utensil",S_GROUP:"碑刻",TITLE:"雷峰塔南无",F_NAME:"lft04.jpg",},
{F_GROUP: "utensil",S_GROUP:"雕塑",TITLE:"岳飞坐像",F_NAME:"ym03.jpg",},
{F_GROUP: "utensil",S_GROUP:"雕塑",TITLE:"陶龙猫",F_NAME:"tao01.jpg",F_DESC:"陶龙猫",},
{F_GROUP: "utensil",S_GROUP:"雕塑",TITLE:"陶羊",F_NAME:"tao05.jpg",},
{F_GROUP: "utensil",S_GROUP:"雕塑",TITLE:"陶象",F_NAME:"tao06.jpg",},
{F_GROUP: "utensil",S_GROUP:"雕塑",TITLE:"陶龟猪",F_NAME:"tao07.jpg",},
{F_GROUP: "utensil",S_GROUP:"雕塑",TITLE:"岳飞（武）",F_NAME:"hhl05.jpg",},
{F_GROUP: "utensil",S_GROUP:"雕塑",TITLE:"盘蛇",F_NAME:"panshe.jpg",F_DESC:"盘蛇",},
{F_GROUP: "utensil",S_GROUP:"雕塑",TITLE:"飞来峰造像",F_NAME:"feilai01.jpg",F_DESC:"飞来峰造像",},
{F_GROUP: "utensil",S_GROUP:"雕塑",TITLE:"潭柘望天",F_NAME:"tzs01.jpg",},
{F_GROUP: "utensil",S_GROUP:"雕塑",TITLE:"岳飞（杭）",F_NAME:"yuefei01.jpg",F_DESC:"岳飞像",},
{F_GROUP: "utensil",S_GROUP:"雕塑",TITLE:"秋瑾",F_NAME:"qiujin.jpg",F_DESC:"秋瑾",},
{F_GROUP: "utensil",S_GROUP:"雕塑",TITLE:"陶人",F_NAME:"tao04.jpg",F_DESC:"陶柱",},
{F_GROUP: "utensil",S_GROUP:"雕塑",TITLE:"陶几",F_NAME:"tao03.jpg",F_DESC:"陶几",},
{F_GROUP: "utensil",S_GROUP:"雕塑",TITLE:"陶鸡犬",F_NAME:"tao02.jpg",F_DESC:"陶鸡犬",},
{F_GROUP: "utensil",S_GROUP:"工具",TITLE:"飞机",F_NAME:"feiji01.jpg",},
{F_GROUP: "utensil",S_GROUP:"工具",TITLE:"飞机残影",F_NAME:"feiji02.jpg",},
{F_GROUP: "utensil",S_GROUP:"工具",TITLE:"战斗机",F_NAME:"zhandouji01.jpg",SHOW:"no",},

{F_GROUP: "wood",S_GROUP:"木",S_CLASS: "松柏纲",S_ORDER: "松柏目",S_FAMILY: "松科",TITLE: "松",F_NAME: "song.jpg",},
{F_GROUP: "wood",S_GROUP:"木",TITLE: "枯木",F_NAME: "kumu.jpg",},
{F_GROUP: "wood",S_GROUP:"木",TITLE: "柏",F_NAME: "bai.jpg",},
{F_GROUP: "wood",S_GROUP:"木",TITLE: "榕",F_NAME: "rongshu.jpg",},
{F_GROUP: "wood",S_GROUP:"果",TITLE: "像石榴的果",F_NAME: "guo01.jpg",},
{F_GROUP: "wood",S_GROUP:"果",TITLE: "小绿团",F_NAME: "guo03.jpg",},
{F_GROUP: "wood",S_GROUP:"果",S_CLASS: "双子叶植物纲",TITLE: "怪果",F_NAME: "qgdc.jpg",F_DESC: "怪异的果",},
{F_GROUP: "wood",S_GROUP:"果",TITLE: "木棉麻雀",F_NAME: "mumianmaque.jpg",},
{F_GROUP: "wood",S_GROUP:"果",TITLE: "杉果",F_NAME: "shanguo01.jpg",},
{F_GROUP: "wood",S_GROUP:"果",TITLE: "松果",F_NAME: "songguo01.jpg",},
{F_GROUP: "wood",S_GROUP:"果",TITLE: "板栗",F_NAME: "banli01.jpg",},
{F_GROUP: "wood",S_GROUP:"果",TITLE: "柿子",F_NAME: "shizi01.jpg",LINK:"drug/柿蒂",},
{F_GROUP: "wood",S_GROUP:"果",TITLE: "树小果绿",F_NAME: "guo11.jpg",},
{F_GROUP: "wood",S_GROUP:"果",TITLE: "树果红紫绿圆小",F_NAME: "guo17.jpg",},
{F_GROUP: "wood",S_GROUP:"果",TITLE: "树果红绿圆小",F_NAME: "guo18.jpg",},
{F_GROUP: "wood",S_GROUP:"果",TITLE: "树果绿椭小",F_NAME: "guo15.jpg",},
{F_GROUP: "wood",S_GROUP:"果",TITLE: "树红果小",F_NAME: "guo12.jpg",},
{F_GROUP: "wood",S_GROUP:"果",TITLE: "桃子",F_NAME: "tao.jpg",},
{F_GROUP: "wood",S_GROUP:"果",TITLE: "桑椹",F_NAME: "guo06.jpg",LINK: "drug/桑椹",},
{F_GROUP: "wood",S_GROUP:"果",TITLE: "油桐",F_NAME: "youtong01.jpg",},
{F_GROUP: "wood",S_GROUP:"果",TITLE: "玉米",F_NAME: "yumi01.jpg",},
{F_GROUP: "wood",S_GROUP:"果",TITLE: "糖罐子",F_NAME: "tangguanzi.jpg",},
{F_GROUP: "wood",S_GROUP:"果",TITLE: "覆盆子",F_NAME: "guo14.jpg",LINK: "drug/覆盆子",},
{F_GROUP: "wood",S_GROUP:"果",TITLE: "红果刺",F_NAME: "guo04.jpg",},
{F_GROUP: "wood",S_GROUP:"果",TITLE: "红果小",F_NAME: "hongguo.jpg",},
{F_GROUP: "wood",S_GROUP:"果",TITLE: "红果怪",F_NAME: "hongguo01.jpg",},
{F_GROUP: "wood",S_GROUP:"果",TITLE: "红果小2",F_NAME: "hongguo02.jpg",},
{F_GROUP: "wood",S_GROUP:"果",TITLE: "红果枝",F_NAME: "guo07.jpg",},
{F_GROUP: "wood",S_GROUP:"果",TITLE: "红果椭",F_NAME: "guo05.jpg",},
{F_GROUP: "wood",S_GROUP:"果",TITLE: "红绿果小",F_NAME: "guo13.jpg",},
{F_GROUP: "wood",S_GROUP:"果",TITLE: "绿果刺",F_NAME: "guo08.jpg",},
{F_GROUP: "wood",S_GROUP:"果",TITLE: "绿果大圆",F_NAME: "lvguo.jpg",},
{F_GROUP: "wood",S_GROUP:"果",TITLE: "绿果椭串",F_NAME: "guo19.jpg",},
{F_GROUP: "wood",S_GROUP:"果",TITLE: "芒果",F_NAME: "guo10.jpg",},
{F_GROUP: "wood",S_GROUP:"果",TITLE: "草果绿圆小",F_NAME: "guo16.jpg",},
{F_GROUP: "wood",S_GROUP:"果",TITLE: "蓝果",F_NAME: "languo.jpg",},
{F_GROUP: "wood",S_GROUP:"果",TITLE: "青辣椒",F_NAME: "lajiao01.jpg",LINK:"drug/辣椒",},
{F_GROUP: "wood",S_GROUP:"果",TITLE: "黑的果",F_NAME: "guo02.jpg",},
{F_GROUP: "wood",S_GROUP:"果",TITLE: "黑绿小果",F_NAME: "guo09.jpg",},
{F_GROUP: "wood",S_GROUP:"果",TITLE: "青杨梅",F_NAME: "yangmei01.jpg",},
{F_GROUP: "wood",S_GROUP:"果",TITLE: "绿南瓜",F_NAME: "nangua01.jpg",},
{F_GROUP: "wood",S_GROUP:"果",TITLE: "白小珠",F_NAME: "baixiaozhu01.jpg",},
{F_GROUP: "wood",S_GROUP:"果",TITLE: "黑果小",F_NAME: "heixiaoguo01.jpg",},
{F_GROUP: "wood",S_GROUP:"花",TITLE: "桂花",F_NAME: "guihua.jpg",LINK:"drug/桂枝",},
{F_GROUP: "wood",S_GROUP:"花",TITLE: "桃花",F_NAME: "taohua.jpg",LINK:"drug/桃枝",},
{F_GROUP: "wood",S_GROUP:"花",TITLE: "彼岸花",F_NAME: "bianhua01.jpg",},
{F_GROUP: "wood",S_GROUP:"花",TITLE: "红三角梅",F_NAME: "hongsanjiao.jpg",},
{F_GROUP: "wood",S_GROUP:"花",S_CLASS: "被子植物门",S_ORDER: "双子叶植物纲",S_FAMILY: "茄科",TITLE: "曼陀罗",F_NAME: "mantuoluo.jpg",F_DESC: "曼陀罗花又叫洋金花、大喇叭花、山茄子，夕颜，果实名为：狗核桃、毛苹果原产印度，花期5－9月，果期6－10月，喜温暖、向阳及排水良好的砂质壤土。多野生在田间、沟旁、道边、河岸、山坡等地方，主要危害棉花、豆类、薯类、蔬菜等，有剧毒。",},
{F_GROUP: "wood",S_GROUP:"花",TITLE: "蒲公英",F_NAME: "pugongying2.jpg",LINK:"drug/蒲公英",},
{F_GROUP: "wood",S_GROUP:"花",TITLE: "鸡冠花",F_NAME: "jiguanhua01.jpg",LINK: "drug/覆盆子",},
{F_GROUP: "wood",S_GROUP:"花",S_CLASS: "双子叶植物纲",S_ORDER: "牻牛儿苗目",S_FAMILY: "凤仙花科",TITLE: "凤仙",F_NAME: "fengxianhua.jpg",F_DESC: "别名：指甲花，急性子，凤仙透骨草",LINK:"drug/急性子",},
{F_GROUP: "wood",S_GROUP:"花",TITLE: "凤凰花",F_NAME: "fenghuang.jpg",},
{F_GROUP: "wood",S_GROUP:"花",TITLE: "牵牛花",F_NAME: "qianniuhua02.jpg",LINK:"drug/牵牛子",},
{F_GROUP: "wood",S_GROUP:"花",TITLE: "牵牛花蓝",F_NAME: "qianniuhua01.jpg",},
{F_GROUP: "wood",S_GROUP:"花",TITLE: "牵牛花紫",F_NAME: "qianniuhua03.jpg",},
{F_GROUP: "wood",S_GROUP:"花",S_CLASS: "双子叶植物纲",S_ORDER: "毛茛目",TITLE: "灵隐寺莲",F_NAME: "lianhua02.jpg",},
{F_GROUP: "wood",S_GROUP:"花",S_CLASS: "双子叶植物纲",S_ORDER: "毛茛目",S_FAMILY: "睡莲科",TITLE: "睡莲",F_NAME: "112.jpg",},
{F_GROUP: "wood",S_GROUP:"花",S_CLASS: "双子叶植物纲",S_ORDER: "桃金娘目",S_FAMILY: "石榴科",TITLE: "石榴",F_NAME: "shiliuhua.jpg",F_DESC: "石榴花",LINK:"drug/石榴皮",},
{F_GROUP: "wood",S_GROUP:"花",S_CLASS: "双子叶植物纲",S_ORDER: "茄目",S_FAMILY: "旋花科",TITLE: "茑萝",F_NAME: "niaoluo.jpg",F_DESC: "茑与女萝，施于松柏",},
{F_GROUP: "wood",S_GROUP:"花",S_CLASS: "双子叶植物纲",S_ORDER: "茄目",S_FAMILY: "旋花科",TITLE: "茑萝雨",F_NAME: "niaoluo01.jpg",F_DESC: "茑与女萝，施于松柏",},
{F_GROUP: "wood",S_GROUP:"花",S_CLASS: "双子叶植物纲",S_ORDER: "毛茛目",S_FAMILY: "睡莲科",TITLE: "荷花",F_NAME: "hehua.jpg",},
{F_GROUP: "wood",S_GROUP:"花",S_CLASS: "双子叶植物纲",S_ORDER: "茄目",S_FAMILY: "旋花科",TITLE: "土丁桂",F_NAME: "tudinggui.jpg",F_DESC: "别名过饥草、小鹿衔。长于灌丛，起于路边",},
{F_GROUP: "wood",S_GROUP:"花",S_CLASS: "双子叶植物纲",S_ORDER: "蔷薇目",S_FAMILY: "蝶形花科",TITLE: "豌豆花",F_NAME: "wandou.jpg",F_DESC: "豌豆（学名：Pisum sativum Linn），一年生攀援草本，高0.5-2米。花期6-7月，果期7-9月。",},
{F_GROUP: "wood",S_GROUP:"花",TITLE: "喇叭花白",F_NAME: "labahua01.jpg",},
{F_GROUP: "wood",S_GROUP:"花",S_CLASS: "双子叶植物纲",S_ORDER: "菊目",S_FAMILY: "菊科",TITLE: "多瓣粉花",F_NAME: "fenhua.jpg",},
{F_GROUP: "wood",S_GROUP:"花",TITLE: "白小花",F_NAME: "baixiao.jpg",},
{F_GROUP: "wood",S_GROUP:"花",TITLE: "白花六",F_NAME: "bai602.jpg",},
{F_GROUP: "wood",S_GROUP:"花",TITLE: "三叶草花",F_NAME: "sanyecao01.jpg",},
{F_GROUP: "wood",S_GROUP:"花",TITLE: "五瓣白花1",F_NAME: "bai5.jpg",},
{F_GROUP: "wood",S_GROUP:"花",TITLE: "五瓣白花2",F_NAME: "bai52.jpg",},
{F_GROUP: "wood",S_GROUP:"花",TITLE: "六瓣白花",F_NAME: "bai6.jpg",},
{F_GROUP: "wood",S_GROUP:"花",TITLE: "六瓣粉花",F_NAME: "fen6.jpg",},
{F_GROUP: "wood",S_GROUP:"花",TITLE: "紫花",F_NAME: "zihua2.jpg",},
{F_GROUP: "wood",S_GROUP:"花",TITLE: "紫花多瓣",F_NAME: "huozi01.jpg",},
{F_GROUP: "wood",S_GROUP:"花",TITLE: "红花花蕊",F_NAME: "huarui01.jpg",},
{F_GROUP: "wood",S_GROUP:"花",TITLE: "红花雨",F_NAME: "hua01.jpg",},
{F_GROUP: "wood",S_GROUP:"花",TITLE: "小白花1",F_NAME: "baihuaxiao.jpg",},
{F_GROUP: "wood",S_GROUP:"花",TITLE: "小白花2",F_NAME: "xiaobaihua.jpg",},
{F_GROUP: "wood",S_GROUP:"花",TITLE: "黄白草花",F_NAME: "huangbaihua01.jpg",},
{F_GROUP: "wood",S_GROUP:"花",TITLE: "小紫花",F_NAME: "zihua.jpg",},
{F_GROUP: "wood",S_GROUP:"花",TITLE: "山花",F_NAME: "shanhua.jpg",},
{F_GROUP: "wood",S_GROUP:"花",TITLE: "橙花六瓣",F_NAME: "huacheng01.jpg",},
{F_GROUP: "wood",S_GROUP:"花",TITLE: "蓝紫花绿球果",F_NAME: "lanzi01.jpg",},
{F_GROUP: "wood",S_GROUP:"花",TITLE: "黄花",F_NAME: "huanghua.jpg",},
{F_GROUP: "wood",S_GROUP:"花",TITLE: "野菊花",F_NAME: "yejuhua01.jpg",LINK:"drug/野菊花",},
{F_GROUP: "wood",S_GROUP:"花",TITLE: "黄野菊花2",F_NAME: "yejuhua.jpg",},
{F_GROUP: "wood",S_GROUP:"花",TITLE: "野菊白",F_NAME: "yejubai.jpg",LINK:"drug/野菊花",},
{F_GROUP: "wood",S_GROUP:"花",TITLE: "落花",F_NAME: "luohua01.jpg",},
{F_GROUP: "wood",S_GROUP:"花",TITLE: "香蕉花（？）",F_NAME: "xiangjiao.jpg",},
{F_GROUP: "wood",S_GROUP:"花",TITLE: "黄花多瓣",F_NAME: "huanghuaduo.jpg",},
{F_GROUP: "wood",S_GROUP:"草",TITLE: "狗尾巴草",F_NAME: "gouyiba01.jpg",},
{F_GROUP: "wood",S_GROUP:"草",TITLE: "狗尾巴草雨",F_NAME: "gouyiba02.jpg",},
{F_GROUP: "wood",S_GROUP:"草",TITLE: "车前草",F_NAME: "cheqian01.jpg",LINK:"drug/车前草",},
{F_GROUP: "wood",S_GROUP:"草",TITLE: "薜荔",F_NAME: "bili01.jpg",},
{F_GROUP: "wood",S_GROUP:"草",TITLE: "灯笼草",F_NAME: "denglongcao01.jpg",},
{F_GROUP: "wood",S_GROUP:"草",TITLE: "铜钱草",F_NAME: "tongqiancao.jpg",},
{F_GROUP: "wood",S_GROUP:"草",S_CLASS: "双子叶植物纲",S_ORDER: "菊目",S_FAMILY: "菊科",TITLE: "鬼针草",F_NAME: "guizhencao.jpg",},
{F_GROUP: "wood",S_GROUP:"草",S_CLASS: "双子叶植物纲",S_ORDER: "菊目",S_FAMILY: "菊科",TITLE: "蒲公英细风",F_NAME: "pugongying.jpg",F_DESC: "蒲公英花花",},
{F_GROUP: "wood",S_GROUP:"草",S_CLASS: "双子叶植物纲",S_ORDER: "菊目",S_FAMILY: "菊科",TITLE: "蒲公英蝉蜕",F_NAME: "pugongying3.jpg",F_DESC: "蒲公英蝉蜕",},
{F_GROUP: "wood",S_GROUP:"草",S_CLASS: "单子叶植物纲",S_ORDER: "鸭跖草目",S_FAMILY: "鸭跖草科",TITLE: "紫鸭趾草",F_NAME: "zyzc.jpg",},
{F_GROUP: "wood",S_GROUP:"草",S_CLASS: "单子叶植物纲",S_ORDER: "禾本目",S_FAMILY: "禾本科",TITLE: "芒草",F_NAME: "mangcao.jpg",},
{F_GROUP: "wood",S_GROUP:"草",TITLE: "小草",F_NAME: "xiaocao.jpg",},
{F_GROUP: "wood",S_GROUP:"草",TITLE: "紫花草",F_NAME: "zihuacao.jpg",},
{F_GROUP: "wood",S_GROUP:"草",TITLE: "草雨",F_NAME: "caoyu01.jpg",},
{F_GROUP: "wood",S_GROUP:"草",TITLE: "蜂草",F_NAME: "cao1.jpg",},
{F_GROUP: "wood",S_GROUP:"草",TITLE: "小草",F_NAME: "xiaocao.jpg",},
{F_GROUP: "wood",S_GROUP:"菇",TITLE: "伞灰粗",F_NAME: "gu10.jpg",},
{F_GROUP: "wood",S_GROUP:"菇",TITLE: "小伞",F_NAME: "gu5.jpg",},
{F_GROUP: "wood",S_GROUP:"菇",TITLE: "年轮菇",F_NAME: "gu4.jpg",},
{F_GROUP: "wood",S_GROUP:"菇",TITLE: "彩菇",F_NAME: "gu9.jpg",},
{F_GROUP: "wood",S_GROUP:"菇",TITLE: "枯木白轮",F_NAME: "gu11.jpg",},
{F_GROUP: "wood",S_GROUP:"菇",TITLE: "树白菇",F_NAME: "gu6.jpg",},
{F_GROUP: "wood",S_GROUP:"菇",TITLE: "灰伞",F_NAME: "gu2.jpg",},
{F_GROUP: "wood",S_GROUP:"菇",TITLE: "白菇",F_NAME: "baigu.jpg",},
{F_GROUP: "wood",S_GROUP:"菇",TITLE: "红菇",F_NAME: "gu3.jpg",},
{F_GROUP: "wood",S_GROUP:"菇",TITLE: "竹叶菇",F_NAME: "gu7.jpg",},
{F_GROUP: "wood",S_GROUP:"菇",TITLE: "红菇",F_NAME: "gu8.jpg",},
{F_GROUP: "wood",S_GROUP:"菇",TITLE: "野生木耳",F_NAME: "muer01.jpg",},
{F_GROUP: "wood",S_GROUP:"菇",TITLE: "野生白木耳",F_NAME: "muer02.jpg",},
{F_GROUP: "wood",S_GROUP:"蕨",TITLE: "绿蕨",F_NAME: "jue2.jpg",},
{F_GROUP: "wood",S_GROUP:"蕨",TITLE: "阴阳蕨",F_NAME: "yinyangjue.jpg",},

]