var file=[
{F_GROUP: "bug",S_GROUP: "半翅目",TITLE: "椿象橙绿",F_NAME: "chunxiang01.jpg",},
{F_GROUP: "bug",S_GROUP: "半翅目",TITLE: "椿象灰",F_NAME: "chunxiang02.jpg",},
{F_GROUP: "bug",S_GROUP: "半翅目",TITLE: "椿象长腿",F_NAME: "chunxiang03.jpg",},
{F_GROUP: "bug",S_GROUP: "半翅目",TITLE: "丽盾蝽",F_NAME: "chunxiang04.jpg",},
{F_GROUP: "bug",S_GROUP: "半翅目",TITLE: "椿象红",F_NAME: "chunxiang05.jpg",},
{F_GROUP: "bug",S_GROUP: "半翅目",TITLE: "椿象橙",F_NAME: "chunxiang06.jpg",},
{F_GROUP: "bug",S_GROUP: "半翅目",TITLE: "椿象黑",F_NAME: "chunxiang07.jpg",},
{F_GROUP: "bug",S_GROUP: "半翅目",TITLE: "椿象灰",F_NAME: "chunxiang10.jpg",},
{F_GROUP: "bug",S_GROUP: "半翅目",TITLE: "麻皮蝽",F_NAME: "qiaochi13.jpg",},
{F_GROUP: "bug",S_GROUP: "半翅目",TITLE: "棉红蝽",F_NAME: "qiaochi30.jpg",},
{F_GROUP: "bug",S_GROUP: "半翅目",TITLE: "蝽在蕉叶",F_NAME: "chunxiang08.jpg",},
{F_GROUP: "bug",S_GROUP: "半翅目",TITLE: "蝽若虫",F_NAME: "qiaochi02.jpg",},
{F_GROUP: "bug",S_GROUP: "半翅目",TITLE: "缘蝽若虫",F_NAME: "qiaochi04.jpg",},
{F_GROUP: "bug",S_GROUP: "半翅目",TITLE: "腿有橙点",F_NAME: "qiaochi20.jpg",},
{F_GROUP: "bug",S_GROUP: "半翅目",TITLE: "蝽细长",F_NAME: "chunxiang09.jpg",},
{F_GROUP: "bug",S_GROUP: "半翅目",TITLE: "蝽有点",F_NAME: "chunxiang11.jpg",},
{F_GROUP: "bug",S_GROUP: "半翅目",TITLE: "椿的卵",F_NAME: "chundeluan01.jpg",},
{F_GROUP: "bug",S_GROUP: "半翅目",TITLE: "黑肚翘",F_NAME: "qiaochi08.jpg",},
{F_GROUP: "bug",S_GROUP: "半翅目",TITLE: "黑长须",F_NAME: "qiaochi09.jpg",},
{F_GROUP: "bug",S_GROUP: "半翅目",TITLE: "龟蝽",F_NAME: "qiaochi21.jpg",},
{F_GROUP: "bug",S_GROUP: "半翅目",TITLE: "水虫",F_NAME: "shuichong.jpg",},
{F_GROUP: "bug",S_GROUP: "半翅目",TITLE: "知了中",F_NAME: "zhiliao01.jpg",},
{F_GROUP: "bug",S_GROUP: "半翅目",TITLE: "知了壳",F_NAME: "zhiliaoke01.jpg",LINK: "drug/蝉蜕",},
{F_GROUP: "bug",S_GROUP: "半翅目",TITLE: "知了壳小",F_NAME: "zhiliaoke02.jpg",LINK: "drug/蝉蜕",},
{F_GROUP: "bug",S_GROUP: "半翅目",TITLE: "知了小侧",F_NAME: "zhiliao02.jpg",},
{F_GROUP: "bug",S_GROUP: "半翅目",TITLE: "知了小正",F_NAME: "zhiliao04.jpg",},
{F_GROUP: "bug",S_GROUP: "半翅目",TITLE: "黑丽宝岛蝉",F_NAME: "zhiliao03.jpg",},
{F_GROUP: "bug",S_GROUP: "半翅目",TITLE: "眼纹广翅蜡蝉",F_NAME: "lachan01.jpg",},
{F_GROUP: "bug",S_GROUP: "半翅目",TITLE: "离脉叶蝉",F_NAME: "yechan01.jpg",},
{F_GROUP: "bug",S_GROUP: "半翅目",TITLE: "碧蛾蜡蝉",F_NAME: "die23.jpg",},
{F_GROUP: "bug",S_GROUP: "半翅目",TITLE: "三角翅大眼",F_NAME: "banchi01.jpg",},
{F_GROUP: "bug",S_GROUP: "半翅目",TITLE: "虫壳",F_NAME: "chongke01.jpg",},
{F_GROUP: "bug",S_GROUP: "半翅目",S_FAMILY: "蚜科",TITLE: "蚜虫",F_NAME: "yachong01.jpg",},
{F_GROUP: "bug",S_GROUP: "双翅目",TITLE: "按蚊",F_NAME: "wen01.jpg",F_DESC: "按蚊（Anopheles） 无脊椎动物。 体多呈灰色，翅有黑白花斑，刺吸式口器。静止时腹部翘起，与停落面成一角度。雌虫吸取人、畜的血，传播疟疾和丝虫病等。又称疟蚊。",},
{F_GROUP: "bug",S_GROUP: "双翅目",TITLE: "山蚊子",F_NAME: "wen02.jpg",},
{F_GROUP: "bug",S_GROUP: "双翅目",TITLE: "普通蚊子3",F_NAME: "wen03.jpg",},
{F_GROUP: "bug",S_GROUP: "双翅目",TITLE: "普通蚊子4",F_NAME: "wen04.jpg",},
{F_GROUP: "bug",S_GROUP: "双翅目",TITLE: "普通蚊子5",F_NAME: "wen05.jpg",},
{F_GROUP: "bug",S_GROUP: "双翅目",TITLE: "长脚蚊",F_NAME: "wen06.jpg",},
{F_GROUP: "bug",S_GROUP: "双翅目",TITLE: "蓝苍蝇",F_NAME: "cangying01.jpg",},
{F_GROUP: "bug",S_GROUP: "双翅目",TITLE: "亮苍蝇",F_NAME: "cangying03.jpg",},
{F_GROUP: "bug",S_GROUP: "双翅目",TITLE: "红眼蓝苍蝇",F_NAME: "cangying02.jpg",},
{F_GROUP: "bug",S_GROUP: "双翅目",TITLE: "细腹条纹蝇",F_NAME: "ying01.jpg",},
{F_GROUP: "bug",S_GROUP: "双翅目",TITLE: "亮蓝蝇",F_NAME: "ying02.jpg",},
{F_GROUP: "bug",S_GROUP: "双翅目",TITLE: "亮腹蝇",F_NAME: "mochi01.jpg",},
{F_GROUP: "bug",S_GROUP: "双翅目",TITLE: "食蚜蝇",F_NAME: "ying03.jpg",},
{F_GROUP: "bug",S_GROUP: "双翅目",TITLE: "马蝇",F_NAME: "ying04.jpg",},
{F_GROUP: "bug",S_GROUP: "双翅目",TITLE: "虻",F_NAME: "feng12.jpg",},
{F_GROUP: "bug",S_GROUP: "双翅目",TITLE: "虻2",F_NAME: "feng18.jpg",},
{F_GROUP: "bug",S_GROUP: "双翅目",TITLE: "棕水虻",F_NAME: "zhichi02.jpg",},
{F_GROUP: "bug",S_GROUP: "双翅目",TITLE: "黑水虻",F_NAME: "shuim01.jpg",},
{F_GROUP: "bug",S_GROUP: "双翅目",TITLE: "虻1",F_NAME: "meng01.jpg",},
{F_GROUP: "bug",S_GROUP: "双翅目",TITLE: "黑长须2",F_NAME: "qiaochi12.jpg",},
{F_GROUP: "bug",S_GROUP: "双翅目",TITLE: "蛾蠓",F_NAME: "emeng01.jpg",},
{F_GROUP: "bug",S_GROUP: "直翅目",TITLE: "红螽斯",F_NAME: "zhongsi01.jpg",},
{F_GROUP: "bug",S_GROUP: "直翅目",TITLE: "绿",F_NAME: "zhichi01.jpg",},
{F_GROUP: "bug",S_GROUP: "直翅目",TITLE: "树蟋",F_NAME: "shuxi01.jpg",},
{F_GROUP: "bug",S_GROUP: "直翅目",TITLE: "灰蟋蟀",F_NAME: "xishuai02.jpg",},
{F_GROUP: "bug",S_GROUP: "直翅目",TITLE: "绿蟋蟀",F_NAME: "xishuai01.jpg",},
{F_GROUP: "bug",S_GROUP: "直翅目",TITLE: "黑蟋蟀",F_NAME: "xishuai03.jpg",},
{F_GROUP: "bug",S_GROUP: "直翅目",TITLE: "蚂蚱会叫",F_NAME: "mazha04.jpg",},
{F_GROUP: "bug",S_GROUP: "直翅目",TITLE: "蚂蚱叶上",F_NAME: "mazha05.jpg",},
{F_GROUP: "bug",S_GROUP: "直翅目",TITLE: "蚂蚱灰",F_NAME: "mazha01.jpg",},
{F_GROUP: "bug",S_GROUP: "直翅目",TITLE: "蚂蚱长须红",F_NAME: "mazha06.jpg",},
{F_GROUP: "bug",S_GROUP: "直翅目",TITLE: "负蝗",F_NAME: "mazha03.jpg",},
{F_GROUP: "bug",S_GROUP: "直翅目",TITLE: "蚂蚱棕黑绿",F_NAME: "mazha08.jpg",},
{F_GROUP: "bug",S_GROUP: "直翅目",TITLE: "蚂蚱黑绿",F_NAME: "mazha02.jpg",},
{F_GROUP: "bug",S_GROUP: "直翅目",TITLE: "蚂蚱在叶",F_NAME: "mazha07.jpg",},
{F_GROUP: "bug",S_GROUP: "直翅目",TITLE: "华绿螽",F_NAME: "caochong01.jpg",},
{F_GROUP: "bug",S_GROUP: "直翅目",TITLE: "蝈蝈",F_NAME: "guoguo01.jpg",},
{F_GROUP: "bug",S_GROUP: "直翅目",TITLE: "蝈蝈异色",F_NAME: "guoguo02.jpg",},
{F_GROUP: "bug",S_GROUP: "直翅目",TITLE: "蝼蛄",F_NAME: "lougu01.jpg",},
{F_GROUP: "bug",S_GROUP: "直翅目",TITLE: "蝼蛄2",F_NAME: "lougu02.jpg",},
{F_GROUP: "bug",S_GROUP: "直翅目",TITLE: "黑",F_NAME: "zhichi03.jpg",},
{F_GROUP: "bug",S_GROUP: "膜翅目",TITLE: "长须细腹",F_NAME: "mochi02.jpg",},
{F_GROUP: "bug",S_GROUP: "膜翅目",TITLE: "大蜂蚁",F_NAME: "feng10.jpg",},
{F_GROUP: "bug",S_GROUP: "膜翅目",TITLE: "对蜂",F_NAME: "feng13.jpg",},
{F_GROUP: "bug",S_GROUP: "膜翅目",TITLE: "小蜂采蜜",F_NAME: "feng14.jpg",},
{F_GROUP: "bug",S_GROUP: "膜翅目",TITLE: "窗蜂",F_NAME: "feng09.jpg",},
{F_GROUP: "bug",S_GROUP: "膜翅目",TITLE: "红毛尾蜂",F_NAME: "feng08.jpg",},
{F_GROUP: "bug",S_GROUP: "膜翅目",TITLE: "绿眼蜂",F_NAME: "feng15.jpg",},
{F_GROUP: "bug",S_GROUP: "膜翅目",TITLE: "茑萝蚁",F_NAME: "niaoluoyi.jpg",},
{F_GROUP: "bug",S_GROUP: "膜翅目",TITLE: "蜂小头棕",F_NAME: "feng07.jpg",},
{F_GROUP: "bug",S_GROUP: "膜翅目",TITLE: "蜂窝",F_NAME: "fengwo01.jpg",},
{F_GROUP: "bug",S_GROUP: "膜翅目",TITLE: "蜜蜂1",F_NAME: "feng03.jpg",},
{F_GROUP: "bug",S_GROUP: "膜翅目",TITLE: "蜜蜂2",F_NAME: "feng02.jpg",},
{F_GROUP: "bug",S_GROUP: "膜翅目",TITLE: "长绿眼蜂",F_NAME: "feng01.jpg",},
{F_GROUP: "bug",S_GROUP: "膜翅目",TITLE: "食腐蜂",F_NAME: "feng11.jpg",},
{F_GROUP: "bug",S_GROUP: "膜翅目",TITLE: "大蚂蚁",F_NAME: "mayi01.jpg",},
{F_GROUP: "bug",S_GROUP: "膜翅目",TITLE: "大蚂蚁2",F_NAME: "mayi02.jpg",},
{F_GROUP: "bug",S_GROUP: "膜翅目",TITLE: "小蚂蚁搬柚子",F_NAME: "mayi03.jpg",},
{F_GROUP: "bug",S_GROUP: "膜翅目",TITLE: "黄白相间蜂",F_NAME: "feng05.jpg",},
{F_GROUP: "bug",S_GROUP: "膜翅目",TITLE: "黑蜂1",F_NAME: "feng04.jpg",},
{F_GROUP: "bug",S_GROUP: "膜翅目",TITLE: "黑蜂2",F_NAME: "feng06.jpg",},
{F_GROUP: "bug",S_GROUP: "膜翅目",TITLE: "蜾蠃1",F_NAME: "feng17.jpg",},
{F_GROUP: "bug",S_GROUP: "膜翅目",TITLE: "叶上蜂",F_NAME: "feng19.jpg",},
{F_GROUP: "bug",S_GROUP: "膜翅目",TITLE: "木蜂",F_NAME: "feng20.jpg",},
{F_GROUP: "bug",S_GROUP: "鞘翅目",TITLE: "金斑虎甲",F_NAME: "qiaochi01.jpg",},
{F_GROUP: "bug",S_GROUP: "鞘翅目",TITLE: "十二星瓢虫",F_NAME: "piaochong01.jpg",F_DESC: "十多颗星，吃叶子的。",},
{F_GROUP: "bug",S_GROUP: "鞘翅目",TITLE: "锚纹瓢虫",F_NAME: "piaochong02.jpg",},
{F_GROUP: "bug",S_GROUP: "鞘翅目",TITLE: "多星瓢虫",F_NAME: "piaochong03.jpg",F_DESC: "吃叶子的。",},
{F_GROUP: "bug",S_GROUP: "鞘翅目",TITLE: "金梳龟甲",F_NAME: "piaochong04.jpg",},
{F_GROUP: "bug",S_GROUP: "鞘翅目",TITLE: "瓢虫幼虫",F_NAME: "piaochong05.jpg",},
{F_GROUP: "bug",S_GROUP: "鞘翅目",TITLE: "瓢虫橙黑",F_NAME: "piaochong06.jpg",},
{F_GROUP: "bug",S_GROUP: "鞘翅目",TITLE: "天牛",F_NAME: "tianniu01.jpg",F_DESC: "最常见的那种，小丛丛间拍到嗒。",LINK: "mypaint/天牛",},
{F_GROUP: "bug",S_GROUP: "鞘翅目",TITLE: "棕",F_NAME: "qiaochi05.jpg",},
{F_GROUP: "bug",S_GROUP: "鞘翅目",TITLE: "芫菁",F_NAME: "yuanjing01.jpg",F_DESC: "芫菁 blister beetle 鞘翅目(Coleoptera)芫菁科(Meloidae)甲虫，约2,500种，会分泌出一种刺激性物质，称「斑蝥素」(cantharidin)，主要是从斑蝥属(Mylabris)和欧洲的西班牙芫菁(Lytta vesicatoria, 俗称西班牙苍蝇)收集而来。斑蝥素可用作一种局部皮肤发炎药剂，以除去皮疣。在过去，引出芫菁来医治许多病痛是一种普遍作法，斑蝥素常用来治病。它还是所谓的「春药」的主要成分。芫菁对人类既有益又有害，幼虫食蝗卵，而如果数量很多，成虫就会危害作物。",},
{F_GROUP: "bug",S_GROUP: "鞘翅目",TITLE: "萤火虫",F_NAME: "yinghuo01.jpg",},
{F_GROUP: "bug",S_GROUP: "鞘翅目",TITLE: "长绿甲",F_NAME: "lvjia01.jpg",},
{F_GROUP: "bug",S_GROUP: "鞘翅目",TITLE: "黄",F_NAME: "qiaochi06.jpg",},
{F_GROUP: "bug",S_GROUP: "鞘翅目",TITLE: "黑",F_NAME: "qiaochi03.jpg",},
{F_GROUP: "bug",S_GROUP: "鞘翅目",TITLE: "小棕毛",F_NAME: "qiaochi11.jpg",},
{F_GROUP: "bug",S_GROUP: "鞘翅目",TITLE: "磕头虫灰",F_NAME: "qiaochi14.jpg",},
{F_GROUP: "bug",S_GROUP: "鞘翅目",TITLE: "绿金龟子",F_NAME: "qiaochi15.jpg",},
{F_GROUP: "bug",S_GROUP: "鞘翅目",TITLE: "绿长金龟子",F_NAME: "qiaochi16.jpg",},
{F_GROUP: "bug",S_GROUP: "鞘翅目",TITLE: "刷子须棕背",F_NAME: "qiaochi17.jpg",},
{F_GROUP: "bug",S_GROUP: "鞘翅目",TITLE: "多毛幼虫",F_NAME: "qiaochi18.jpg",},
{F_GROUP: "bug",S_GROUP: "鞘翅目",TITLE: "粪金龟",F_NAME: "qiaochi10.jpg",},
{F_GROUP: "bug",S_GROUP: "鞘翅目",TITLE: "西光奥锹甲",F_NAME: "qiaochi07.jpg",},
{F_GROUP: "bug",S_GROUP: "鞘翅目",TITLE: "奥锹甲雌虫",F_NAME: "qiaochi19.jpg",},
{F_GROUP: "bug",S_GROUP: "鞘翅目",TITLE: "荣瘤犀金龟母虫",F_NAME: "qiaochi22.jpg",},
{F_GROUP: "bug",S_GROUP: "鞘翅目",TITLE: "蜣螂",F_NAME: "qiaochi23.jpg",},
{F_GROUP: "bug",S_GROUP: "鞘翅目",TITLE: "甲虫1",F_NAME: "qiaochi28.jpg",},
{F_GROUP: "bug",S_GROUP: "鞘翅目",TITLE: "甲虫2",F_NAME: "qiaochi29.jpg",},
{F_GROUP: "bug",S_GROUP: "鞘翅目",TITLE: "蒙瘤犀金龟",F_NAME: "qiaochi24.jpg",},
{F_GROUP: "bug",S_GROUP: "鞘翅目",TITLE: "黑甲小",F_NAME: "qiaochi25.jpg",},
{F_GROUP: "bug",S_GROUP: "鞘翅目",TITLE: "黑白似天牛",F_NAME: "qiaochi26.jpg",},
{F_GROUP: "bug",S_GROUP: "鞘翅目",TITLE: "隐翅虫1",F_NAME: "qiaochi27.jpg",},
{F_GROUP: "bug",S_GROUP: "鞘翅目",TITLE: "隐翅虫2",F_NAME: "qiaochi32.jpg",},
{F_GROUP: "bug",S_GROUP: "鞘翅目",TITLE: "米象",F_NAME: "michong01.jpg",},
{F_GROUP: "bug",S_GROUP: "鞘翅目",TITLE: "黑白有翅",F_NAME: "qiaochi31.jpg",},
{F_GROUP: "bug",S_GROUP: "鳞翅目",TITLE: "橘蝶虫",F_NAME: "maochong01.jpg",},
{F_GROUP: "bug",S_GROUP: "鳞翅目",TITLE: "金毛虫",F_NAME: "maochong09.jpg",},
{F_GROUP: "bug",S_GROUP: "鳞翅目",TITLE: "竹叶大青虫",F_NAME: "qingchong01.jpg",},
{F_GROUP: "bug",S_GROUP: "鳞翅目",TITLE: "紫枝大青虫",F_NAME: "qingchong04.jpg",},
{F_GROUP: "bug",S_GROUP: "鳞翅目",TITLE: "半透青虫",F_NAME: "qingchong02.jpg",},
{F_GROUP: "bug",S_GROUP: "鳞翅目",TITLE: "青虫垂丝",F_NAME: "qingchong03.jpg",},
{F_GROUP: "bug",S_GROUP: "鳞翅目",TITLE: "毛虫橙紫",F_NAME: "maochong02.jpg",},
{F_GROUP: "bug",S_GROUP: "鳞翅目",TITLE: "毛虫橙黑",F_NAME: "maochong03.jpg",},
{F_GROUP: "bug",S_GROUP: "鳞翅目",TITLE: "毛虫垂丝",F_NAME: "maochong04.jpg",},
{F_GROUP: "bug",S_GROUP: "鳞翅目",TITLE: "毛虫在竹",F_NAME: "maochong11.jpg",},
{F_GROUP: "bug",S_GROUP: "鳞翅目",S_FAMILY: "毒蛾科",TITLE: "毒蛾幼虫",F_NAME: "maochong05.jpg",},
{F_GROUP: "bug",S_GROUP: "鳞翅目",S_FAMILY: "毒蛾科",TITLE: "毒蛾幼虫+",F_NAME: "maochong07.jpg",},
{F_GROUP: "bug",S_GROUP: "鳞翅目",S_FAMILY: "蛱蝶科",TITLE: "琉璃蛱蝶幼虫",F_NAME: "die38.jpg",},
{F_GROUP: "bug",S_GROUP: "鳞翅目",TITLE: "蛾幼虫",F_NAME: "maochong08.jpg",},
{F_GROUP: "bug",S_GROUP: "鳞翅目",TITLE: "白虫",F_NAME: "baichong01.jpg",},
{F_GROUP: "bug",S_GROUP: "鳞翅目",TITLE: "刺毛虫",F_NAME: "maochong06.jpg",},
{F_GROUP: "bug",S_GROUP: "鳞翅目",TITLE: "黄毛虫",F_NAME: "maochong10.jpg",},
{F_GROUP: "bug",S_GROUP: "鳞翅目",TITLE: "黑白蛹",F_NAME: "yong03.jpg",},
{F_GROUP: "bug",S_GROUP: "鳞翅目",TITLE: "小橘蝶蛹",F_NAME: "yong02.jpg",},
{F_GROUP: "bug",S_GROUP: "鳞翅目",TITLE: "橘蝶蛹",F_NAME: "yong01.jpg",},
{F_GROUP: "bug",S_GROUP: "鳞翅目",TITLE: "空蛹",F_NAME: "yong04.jpg",},
{F_GROUP: "bug",S_GROUP: "鳞翅目",S_FAMILY: "粉蝶科",TITLE: "尖角黄粉蝶",F_NAME: "die25.jpg",},
{F_GROUP: "bug",S_GROUP: "鳞翅目",S_FAMILY: "粉蝶科",TITLE: "黄粉蝶",F_NAME: "die66.jpg",},
{F_GROUP: "bug",S_GROUP: "鳞翅目",S_FAMILY: "粉蝶科",TITLE: "粉蝶",F_NAME: "die01.jpg",F_DESC: "最常见的白蝴蝶，到处都能看见。",},
{F_GROUP: "bug",S_GROUP: "鳞翅目",S_FAMILY: "粉蝶科",TITLE: "报喜斑粉蝶",F_NAME: "die18.jpg",},
{F_GROUP: "bug",S_GROUP: "鳞翅目",S_FAMILY: "环蝶科",TITLE: "箭环蝶",F_NAME: "die28.jpg",},
{F_GROUP: "bug",S_GROUP: "鳞翅目",S_FAMILY: "眼蝶科",TITLE: "蒙链荫眼蝶",F_NAME: "die04.jpg",},
{F_GROUP: "bug",S_GROUP: "鳞翅目",S_FAMILY: "眼蝶科",TITLE: "连纹黛眼蝶",F_NAME: "die30.jpg",},
{F_GROUP: "bug",S_GROUP: "鳞翅目",S_FAMILY: "眼蝶科",TITLE: "黄斑荫眼蝶",F_NAME: "die33.jpg",},
{F_GROUP: "bug",S_GROUP: "鳞翅目",S_FAMILY: "眼蝶科",TITLE: "玉带黛眼蝶",F_NAME: "die35.jpg",},
{F_GROUP: "bug",S_GROUP: "鳞翅目",S_FAMILY: "眼蝶科",TITLE: "拟稻眉眼蝶",F_NAME: "die70.jpg",},
{F_GROUP: "bug",S_GROUP: "鳞翅目",S_FAMILY: "眼蝶科",TITLE: "矍眼蝶",F_NAME: "die48.jpg",},
{F_GROUP: "bug",S_GROUP: "鳞翅目",S_FAMILY: "眼蝶科",TITLE: "白斑眼蝶1",F_NAME: "die37.jpg",},
{F_GROUP: "bug",S_GROUP: "鳞翅目",S_FAMILY: "眼蝶科",TITLE: "白斑眼蝶2",F_NAME: "die56.jpg",},
{F_GROUP: "bug",S_GROUP: "鳞翅目",S_FAMILY: "灰蝶科",TITLE: "蓝蝶",F_NAME: "die02.jpg",},
{F_GROUP: "bug",S_GROUP: "鳞翅目",S_FAMILY: "灰蝶科",TITLE: "雅灰蝶",F_NAME: "die52.jpg",},
{F_GROUP: "bug",S_GROUP: "鳞翅目",S_FAMILY: "灰蝶科",TITLE: "雅灰蝶鬼针草",F_NAME: "die68.jpg",},
{F_GROUP: "bug",S_GROUP: "鳞翅目",S_FAMILY: "灰蝶科",TITLE: "蚜灰蝶",F_NAME: "die21.jpg",},
{F_GROUP: "bug",S_GROUP: "鳞翅目",S_FAMILY: "灰蝶科",TITLE: "燕灰蝶",F_NAME: "die58.jpg",},
{F_GROUP: "bug",S_GROUP: "鳞翅目",S_FAMILY: "灰蝶科",TITLE: "酢浆灰蝶1",F_NAME: "die64.jpg",},
{F_GROUP: "bug",S_GROUP: "鳞翅目",S_FAMILY: "灰蝶科",TITLE: "酢浆灰蝶1",F_NAME: "die67.jpg",},
{F_GROUP: "bug",S_GROUP: "鳞翅目",S_FAMILY: "灰蝶科",TITLE: "斜斑彩灰蝶",F_NAME: "die42.jpg",},
{F_GROUP: "bug",S_GROUP: "鳞翅目",S_FAMILY: "灰蝶科",TITLE: "斜斑彩灰蝶展",F_NAME: "die53.jpg",},
{F_GROUP: "bug",S_GROUP: "鳞翅目",S_FAMILY: "灰蝶科",TITLE: "斜斑彩灰蝶外",F_NAME: "die43.jpg",},
{F_GROUP: "bug",S_GROUP: "鳞翅目",S_FAMILY: "灰蝶科",TITLE: "浓紫彩灰蝶",F_NAME: "die31.jpg",},
{F_GROUP: "bug",S_GROUP: "鳞翅目",S_FAMILY: "斑蝶科",TITLE: "虎斑蝶",F_NAME: "die12.jpg",},
{F_GROUP: "bug",S_GROUP: "鳞翅目",S_FAMILY: "斑蝶科",TITLE: "绢斑蝶",F_NAME: "die54.jpg",},
{F_GROUP: "bug",S_GROUP: "鳞翅目",S_FAMILY: "斑蝶科",TITLE: "青斑蝶",F_NAME: "die27.jpg",},
{F_GROUP: "bug",S_GROUP: "鳞翅目",S_FAMILY: "蛱蝶科",TITLE: "丝纹蛱蝶",F_NAME: "die03.jpg",F_DESC: "叶子枯了。",},
{F_GROUP: "bug",S_GROUP: "鳞翅目",S_FAMILY: "蛱蝶科",TITLE: "散纹盛蛱蝶",F_NAME: "die14.jpg",},
{F_GROUP: "bug",S_GROUP: "鳞翅目",S_FAMILY: "蛱蝶科",TITLE: "新月带蛱蝶",F_NAME: "die15.jpg",},
{F_GROUP: "bug",S_GROUP: "鳞翅目",S_FAMILY: "蛱蝶科",TITLE: "小环蛱蝶",F_NAME: "die16.jpg",},
{F_GROUP: "bug",S_GROUP: "鳞翅目",S_FAMILY: "蛱蝶科",TITLE: "猫蛱蝶",F_NAME: "die39.jpg",},
{F_GROUP: "bug",S_GROUP: "鳞翅目",S_FAMILY: "蛱蝶科",TITLE: "猫蛱蝶2",F_NAME: "die10.jpg",},
{F_GROUP: "bug",S_GROUP: "鳞翅目",S_FAMILY: "蛱蝶科",TITLE: "豹纹蛱蝶",F_NAME: "die47.jpg",},
{F_GROUP: "bug",S_GROUP: "鳞翅目",S_FAMILY: "蛱蝶科",TITLE: "电蛱蝶",F_NAME: "die07.jpg",},
{F_GROUP: "bug",S_GROUP: "鳞翅目",S_FAMILY: "蛱蝶科",TITLE: "琉璃蛱蝶",F_NAME: "die05.jpg",},
{F_GROUP: "bug",S_GROUP: "鳞翅目",S_FAMILY: "蛱蝶科",TITLE: "大红蛱蝶",F_NAME: "die34.jpg",},
{F_GROUP: "bug",S_GROUP: "鳞翅目",S_FAMILY: "蛱蝶科",TITLE: "黄钩蛱蝶",F_NAME: "die60.jpg",},
{F_GROUP: "bug",S_GROUP: "鳞翅目",S_FAMILY: "蛱蝶科",TITLE: "斐豹蛱蝶1",F_NAME: "die55.jpg",},
{F_GROUP: "bug",S_GROUP: "鳞翅目",S_FAMILY: "蛱蝶科",TITLE: "斐豹蛱蝶2",F_NAME: "die57.jpg",},
{F_GROUP: "bug",S_GROUP: "鳞翅目",S_FAMILY: "蛱蝶科",TITLE: "黑脉蛱蝶",F_NAME: "die61.jpg",},
{F_GROUP: "bug",S_GROUP: "鳞翅目",S_FAMILY: "弄蝶科",TITLE: "稻弄蝶",F_NAME: "die19.jpg",},
{F_GROUP: "bug",S_GROUP: "鳞翅目",S_FAMILY: "弄蝶科",TITLE: "稻弄蝶2",F_NAME: "die13.jpg",},
{F_GROUP: "bug",S_GROUP: "鳞翅目",S_FAMILY: "弄蝶科",TITLE: "黄斑弄蝶",F_NAME: "die69.jpg",},
{F_GROUP: "bug",S_GROUP: "鳞翅目",S_FAMILY: "弄蝶科",TITLE: "白弄蝶",F_NAME: "die17.jpg",},
{F_GROUP: "bug",S_GROUP: "鳞翅目",S_FAMILY: "凤蝶科",TITLE: "玉斑凤蝶1",F_NAME: "die06.jpg",},
{F_GROUP: "bug",S_GROUP: "鳞翅目",S_FAMILY: "凤蝶科",TITLE: "玉斑凤蝶2",F_NAME: "die32.jpg",},
{F_GROUP: "bug",S_GROUP: "鳞翅目",S_FAMILY: "凤蝶科",TITLE: "玉斑凤蝶飞",F_NAME: "die22.jpg",},
{F_GROUP: "bug",S_GROUP: "鳞翅目",S_FAMILY: "凤蝶科",TITLE: "巴黎翠凤蝶",F_NAME: "die26.jpg",},
{F_GROUP: "bug",S_GROUP: "鳞翅目",S_FAMILY: "凤蝶科",TITLE: "碧凤蝶",F_NAME: "die63.jpg",},
{F_GROUP: "bug",S_GROUP: "鳞翅目",S_FAMILY: "蚬蝶科",TITLE: "蛇目褐蚬蝶",F_NAME: "die44.jpg",},
{F_GROUP: "bug",S_GROUP: "鳞翅目",S_FAMILY: "蚬蝶科",TITLE: "蛇目褐蚬蝶展开",F_NAME: "die65.jpg",},
{F_GROUP: "bug",S_GROUP: "鳞翅目",S_FAMILY: "蚬蝶科",TITLE: "波蚬蝶",F_NAME: "die50.jpg",},
{F_GROUP: "bug",S_GROUP: "鳞翅目",S_FAMILY: "大蚕蛾科",TITLE: "樟蚕",F_NAME: "zhangcan01.jpg",},
{F_GROUP: "bug",S_GROUP: "鳞翅目",S_FAMILY: "大蚕蛾科",TITLE: "樟蚕蛹",F_NAME: "zhangcan02.jpg",},
{F_GROUP: "bug",S_GROUP: "鳞翅目",S_FAMILY: "灯蛾科",TITLE: "美苔蛾",F_NAME: "die08.jpg",},
{F_GROUP: "bug",S_GROUP: "鳞翅目",S_FAMILY: "灯蛾科",TITLE: "粉蝶灯蛾",F_NAME: "die51.jpg",},
{F_GROUP: "bug",S_GROUP: "鳞翅目",S_FAMILY: "灯蛾科",TITLE: "苔蛾",F_NAME: "die09.jpg",},
{F_GROUP: "bug",S_GROUP: "鳞翅目",S_FAMILY: "天蛾科",TITLE: "长喙天蛾",F_NAME: "die20.jpg",},
{F_GROUP: "bug",S_GROUP: "鳞翅目",S_FAMILY: "駝蛾科",TITLE: "燄駝蛾",F_NAME: "die24.jpg",},
{F_GROUP: "bug",S_GROUP: "鳞翅目",S_FAMILY: "鹿蛾科",TITLE: "鹿蛾",F_NAME: "die45.jpg",},
{F_GROUP: "bug",S_GROUP: "鳞翅目",S_FAMILY: "蕈蛾科",TITLE: "衣蛾幼虫",F_NAME: "bug01.jpg",},
{F_GROUP: "bug",S_GROUP: "鳞翅目",S_FAMILY: "蓑蛾科",TITLE: "袋蛾幼虫",F_NAME: "bug02.jpg",},
{F_GROUP: "bug",S_GROUP: "鳞翅目",S_FAMILY: "蓑蛾科",TITLE: "蓑蛾幼虫",F_NAME: "weizhi01.jpg",},
{F_GROUP: "bug",S_GROUP: "鳞翅目",S_FAMILY: "尺蛾科",TITLE: "尺蛾灰",F_NAME: "die11.jpg",},
{F_GROUP: "bug",S_GROUP: "鳞翅目",S_FAMILY: "尺蛾科",TITLE: "橙白黑点",F_NAME: "die40.jpg",},
{F_GROUP: "bug",S_GROUP: "鳞翅目",S_FAMILY: "尺蛾科",TITLE: "蕨点蛾白",F_NAME: "die29.jpg",},
{F_GROUP: "bug",S_GROUP: "鳞翅目",S_FAMILY: "尺蛾科",TITLE: "蛾白",F_NAME: "die59.jpg",},
{F_GROUP: "bug",S_GROUP: "鳞翅目",S_FAMILY: "螟蛾科",TITLE: "螟蛾",F_NAME: "die46.jpg",},
{F_GROUP: "bug",S_GROUP: "鳞翅目",S_FAMILY: "螟蛾科",TITLE: "野螟",F_NAME: "die41.jpg",},
{F_GROUP: "bug",S_GROUP: "鳞翅目",S_FAMILY: "斑蛾科",TITLE: "华庆锦斑蛾",F_NAME: "die49.jpg",},
{F_GROUP: "bug",S_GROUP: "鳞翅目",S_FAMILY: "斑蛾科",TITLE: "赤眉锦斑蛾",F_NAME: "die36.jpg",},
{F_GROUP: "bug",S_GROUP: "革翅目",TITLE: "蠼螋芭蕉叶",F_NAME: "qusou01.jpg",},
{F_GROUP: "bug",S_GROUP: "革翅目",TITLE: "蠼螋",F_NAME: "qusou02.jpg",},
{F_GROUP: "bug",S_GROUP: "襀翅目",TITLE: "石蝇",F_NAME: "zhichi04.jpg",},
{F_GROUP: "bug",S_GROUP: "襀翅目",TITLE: "石蝇2",F_NAME: "shiying01.jpg",},
{F_GROUP: "bug",S_GROUP: "襀翅目",TITLE: "石蝇3",F_NAME: "shiying03.jpg",},
{F_GROUP: "bug",S_GROUP: "广翅目",TITLE: "中华斑鱼蛉",F_NAME: "yuling01.jpg",},
{F_GROUP: "bug",S_GROUP: "脉翅目",TITLE: "蚜狮",F_NAME: "yashi01.jpg",F_DESC: "蚜狮是草蛉的幼虫，纺锤状，喜在树叶间捕食蚜虫，故称蚜狮。",},
{F_GROUP: "bug",S_GROUP: "脉翅目",TITLE: "蛉虫",F_NAME: "lingchong01.jpg",},
{F_GROUP: "bug",S_GROUP: "竹节虫目",TITLE: "灰竹节虫",F_NAME: "zhujie01.jpg",},
{F_GROUP: "bug",S_GROUP: "缨尾目",TITLE: "衣鱼",F_NAME: "yiyu01.jpg",},
{F_GROUP: "bug",S_GROUP: "蜚蠊目",TITLE: "白蚁",F_NAME: "baiyi01.jpg",},
{F_GROUP: "bug",S_GROUP: "蜚蠊目",TITLE: "白蟑螂",F_NAME: "zhanglang01.jpg",},
{F_GROUP: "bug",S_GROUP: "蜻蜓目",TITLE: "豆娘双",F_NAME: "douniang01.jpg",},
{F_GROUP: "bug",S_GROUP: "蜻蜓目",TITLE: "透顶单脉色蟌",F_NAME: "douniang02.jpg",LINK: "mypaint/豆娘",},
{F_GROUP: "bug",S_GROUP: "蜻蜓目",TITLE: "竹枝豆影",F_NAME: "douniang03.jpg",},
{F_GROUP: "bug",S_GROUP: "蜻蜓目",TITLE: "豆娘立蕨",F_NAME: "douniang04.jpg",},
{F_GROUP: "bug",S_GROUP: "蜻蜓目",TITLE: "豆娘黄",F_NAME: "douniang05.jpg",},
{F_GROUP: "bug",S_GROUP: "蜻蜓目",TITLE: "豆娘松针",F_NAME: "douniang06.jpg",},
{F_GROUP: "bug",S_GROUP: "蜻蜓目",TITLE: "豆娘双",F_NAME: "douniang07.jpg",},
{F_GROUP: "bug",S_GROUP: "蜻蜓目",TITLE: "豆娘双+",F_NAME: "douniang08.jpg",},
{F_GROUP: "bug",S_GROUP: "蜻蜓目",TITLE: "粉蜻蜓展",F_NAME: "qingting11.jpg",},
{F_GROUP: "bug",S_GROUP: "蜻蜓目",TITLE: "粉蜻蜓平",F_NAME: "qingting05.jpg",},
{F_GROUP: "bug",S_GROUP: "蜻蜓目",TITLE: "背黄腹黑",F_NAME: "qingting03.jpg",},
{F_GROUP: "bug",S_GROUP: "蜻蜓目",TITLE: "蓝蜻蜓",F_NAME: "qingting02.jpg",},
{F_GROUP: "bug",S_GROUP: "蜻蜓目",TITLE: "蓝黄蜻蜓",F_NAME: "qingting06.jpg",},
{F_GROUP: "bug",S_GROUP: "蜻蜓目",TITLE: "褐斑蜻蜓",F_NAME: "qingting01.jpg",F_DESC: "雄虫胸部褐色；腹部橙色；翅膀除末端外为橙色。雌虫和未熟雄虫外观相似，但体色偏黄褐色；翅膀也是淡褐色。",},
{F_GROUP: "bug",S_GROUP: "蜻蜓目",TITLE: "褐蜻蜓",F_NAME: "qingting08.jpg",},
{F_GROUP: "bug",S_GROUP: "蜻蜓目",TITLE: "黄蜻蜓",F_NAME: "qingting07.jpg",},
{F_GROUP: "bug",S_GROUP: "蜻蜓目",TITLE: "黑白蜻蜓",F_NAME: "qingting04.jpg",},
{F_GROUP: "bug",S_GROUP: "蜻蜓目",TITLE: "黑黄相间",F_NAME: "qingting09.jpg",},
{F_GROUP: "bug",S_GROUP: "蜻蜓目",TITLE: "黑黄蓝眼",F_NAME: "qingting10.jpg",},
{F_GROUP: "bug",S_GROUP: "蜻蜓目",TITLE: "棕",F_NAME: "qingting12.jpg",},
{F_GROUP: "bug",S_GROUP: "蜻蜓目",TITLE: "橙黑",F_NAME: "qingting14.jpg",},
{F_GROUP: "bug",S_GROUP: "蜻蜓目",TITLE: "红蜻蜓",F_NAME: "qingting13.jpg",},
{F_GROUP: "bug",S_GROUP: "螳螂目",TITLE: "橙螳螂",F_NAME: "tanglang02.jpg",},
{F_GROUP: "bug",S_GROUP: "螳螂目",TITLE: "灰螳螂",F_NAME: "tanglang01.jpg",},
{F_GROUP: "bug",S_GROUP: "螳螂目",TITLE: "绿螳螂",F_NAME: "tanglang03.jpg",LINK: "drug/桑螵蛸",},
{F_GROUP: "bug",S_GROUP: "螳螂目",TITLE: "螳螂青苔",F_NAME: "tanglang04.jpg",},
{F_GROUP: "bug",S_GROUP: "唇足纲",TITLE: "蜈蚣吃虫",F_NAME: "wugongcc01.jpg",},
{F_GROUP: "bug",S_GROUP: "唇足纲",TITLE: "蜈蚣",F_NAME: "wugong01.jpg",F_DESC: "《本草纲目》曰：“蜈蚣，西南处处有之，春出冬蛰，节节有足，双须岐尾。”",LINK:"drug/蜈蚣",},
{F_GROUP: "bug",S_GROUP: "唇足纲",TITLE: "小蜈蚣",F_NAME: "wugong03.jpg",},
{F_GROUP: "bug",S_GROUP: "倍足纲",TITLE: "条马陆",F_NAME: "wugong02.jpg",},
{F_GROUP: "bug",S_GROUP: "倍足纲",TITLE: "山蛩",F_NAME: "malu01.jpg",},
{F_GROUP: "bug",S_GROUP: "蛛形纲",TITLE: "夜树",F_NAME: "zhu02.jpg",},
{F_GROUP: "bug",S_GROUP: "蛛形纲",TITLE: "大圆",F_NAME: "zhu09.jpg",},
{F_GROUP: "bug",S_GROUP: "蛛形纲",TITLE: "大花",F_NAME: "zhu07.jpg",},
{F_GROUP: "bug",S_GROUP: "蛛形纲",TITLE: "毛腿",F_NAME: "zhu06.jpg",},
{F_GROUP: "bug",S_GROUP: "蛛形纲",TITLE: "窝",F_NAME: "zhizhuwo01.jpg",},
{F_GROUP: "bug",S_GROUP: "蛛形纲",TITLE: "竹根下",F_NAME: "zhu03.jpg",},
{F_GROUP: "bug",S_GROUP: "蛛形纲",TITLE: "绿",F_NAME: "zhu04.jpg",},
{F_GROUP: "bug",S_GROUP: "蛛形纲",TITLE: "脸蛛",F_NAME: "zhu01.jpg",},
{F_GROUP: "bug",S_GROUP: "蛛形纲",TITLE: "腿橙黑白",F_NAME: "zhu08.jpg",},
{F_GROUP: "bug",S_GROUP: "蛛形纲",TITLE: "蛛丝雨",F_NAME: "zhu05.jpg",},
{F_GROUP: "bug",S_GROUP: "蛛形纲",TITLE: "蛛在看",F_NAME: "zhu10.jpg",},
{F_GROUP: "bug",S_GROUP: "蛛形纲",TITLE: "蛛在台",F_NAME: "zhu11.jpg",},
{F_GROUP: "bug",S_GROUP: "蛛形纲",TITLE: "蛛在叶",F_NAME: "zhu15.jpg",},
{F_GROUP: "bug",S_GROUP: "蛛形纲",TITLE: "蛛在墙",F_NAME: "zhu16.jpg",},
{F_GROUP: "bug",S_GROUP: "蛛形纲",TITLE: "蛛在地",F_NAME: "zhu17.jpg",},
{F_GROUP: "bug",S_GROUP: "蛛形纲",S_ORDER: "蜘蛛目",S_FAMILY: "幽灵蛛科",TITLE: "蓝长细腿",F_NAME: "zhu14.jpg",},
{F_GROUP: "bug",S_GROUP: "蛛形纲",TITLE: "豹蛛与寄生螨",F_NAME: "zhu12.jpg",},
{F_GROUP: "bug",S_GROUP: "蛛形纲",TITLE: "屏东巨蟹蛛",F_NAME: "zhu13.jpg",},
{F_GROUP: "bug",S_GROUP: "蛛形纲",TITLE: "豹蛛的寄生螨",F_NAME: "manc01.jpg",},

{F_GROUP: "miao",S_GROUP: "两栖纲",S_ORDER: "无尾目",S_FAMILY: "蛙科",TITLE: "白蛙",F_NAME: "baiwa.jpg",},
{F_GROUP: "miao",S_GROUP: "两栖纲",S_ORDER: "无尾目",S_FAMILY: "蛙科",TITLE: "蝌蚪",F_NAME: "kedou01.jpg",},
{F_GROUP: "miao",S_GROUP: "两栖纲",S_ORDER: "无尾目",S_FAMILY: "蛙科",TITLE: "鸣蛙",F_NAME: "wa01.jpg",},
{F_GROUP: "miao",S_GROUP: "肢口纲",S_ORDER: "剑尾目",S_FAMILY: "鲎科",TITLE: "鲎",F_NAME: "hou02.jpg",},
{F_GROUP: "miao",S_GROUP: "未知",TITLE: "触角怪",F_NAME: "weizhi01.jpg",},
{F_GROUP: "miao",S_GROUP: "未知",TITLE: "软软的",F_NAME: "weizhi02.jpg",},
{F_GROUP: "miao",S_GROUP: "寡毛纲",TITLE: "蚯蚓",F_NAME: "qiuyin01.jpg",LINK: "drug/地龙",},
{F_GROUP: "miao",S_GROUP: "爬行纲",S_ORDER: "龟鳖目",S_FAMILY: "龟科",TITLE: "乌龟",F_NAME: "gui.jpg",F_DESC: "看啥呢？",LINK: "drug/龟甲",},
{F_GROUP: "miao",S_GROUP: "爬行纲",S_ORDER: "有鳞目",S_FAMILY: "蜥蜴科",TITLE: "四脚蛇",F_NAME: "sijiaoshe.jpg",F_DESC: "路边偶遇",},
{F_GROUP: "miao",S_GROUP: "爬行纲",S_ORDER: "有鳞目",S_FAMILY: "蜥蜴科",TITLE: "黑纹四脚蛇",F_NAME: "sijiaoshe02.jpg",F_DESC: "路边偶遇",},
{F_GROUP: "miao",S_GROUP: "爬行纲",S_ORDER: "有鳞目",S_FAMILY: "蜥蜴科",TITLE: "石龙子",F_NAME: "shilongzi01.jpg",F_DESC: "路边偶遇",},
{F_GROUP: "miao",S_GROUP: "爬行纲",S_ORDER: "有鳞目",S_FAMILY: "蜥蜴科",TITLE: "南草蜥",F_NAME: "xiyi01.jpg",F_DESC: "路边偶遇",},
{F_GROUP: "miao",S_GROUP: "爬行纲",S_ORDER: "有鳞目",S_FAMILY: "壁虎科",TITLE: "壁虎",F_NAME: "bihu01.jpg",},
{F_GROUP: "miao",S_GROUP: "爬行纲",S_ORDER: "有鳞目",S_FAMILY: "蝰科",TITLE: "竹叶青",F_NAME: "she01.jpg",F_DESC: "路边偶遇",},
{F_GROUP: "miao",S_GROUP: "爬行纲",S_ORDER: "有鳞目",S_FAMILY: "盲蛇科",TITLE: "钩盲蛇",F_NAME: "she02.jpg",F_DESC: "路边偶遇",},
{F_GROUP: "miao",S_GROUP: "爬行纲",S_ORDER: "有鳞目",S_FAMILY: "游蛇科",TITLE: "紫沙蛇",F_NAME: "zishashe01.jpg",F_DESC: "路边偶遇",},
{F_GROUP: "miao",S_GROUP: "爬行纲",S_ORDER: "有鳞目",S_FAMILY: "游蛇科",TITLE: "红脖颈槽蛇",F_NAME: "hbjcs01.jpg",F_DESC: "路边偶遇",},
{F_GROUP: "miao",S_GROUP: "爬行纲",S_ORDER: "有鳞目",S_FAMILY: "游蛇科",TITLE: "绿瘦蛇",F_NAME: "lvshoushe01.jpg",F_DESC: "路边偶遇",},
{F_GROUP: "miao",S_GROUP: "爬行纲",S_ORDER: "有鳞目",S_FAMILY: "游蛇科",TITLE: "绿瘦蛇2",F_NAME: "lvshoushe02.jpg",F_DESC: "路边偶遇",},
{F_GROUP: "miao",S_GROUP: "爬行纲",S_ORDER: "有鳞目",S_FAMILY: "未知",TITLE: "黄黑白卷",F_NAME: "she05.jpg",F_DESC: "路边偶遇",},
{F_GROUP: "miao",S_GROUP: "爬行纲",S_ORDER: "有鳞目",S_FAMILY: "眼镜蛇科",TITLE: "眼镜王蛇",F_NAME: "she06.jpg",F_DESC: "路边偶遇",},
{F_GROUP: "miao",S_GROUP: "爬行纲",S_ORDER: "有鳞目",S_FAMILY: "未知",TITLE: "灰卷",F_NAME: "she07.jpg",F_DESC: "路边偶遇",},
{F_GROUP: "miao",S_GROUP: "腹足纲",S_ORDER: "中腹足目",S_FAMILY: "玉黍螺科",TITLE: "玉黍螺",F_NAME: "luo02.jpg",},
{F_GROUP: "miao",S_GROUP: "腹足纲",S_ORDER: "中腹足目",S_FAMILY: "田螺科",TITLE: "田螺",F_NAME: "luo03.jpg",},
{F_GROUP: "miao",S_GROUP: "腹足纲",S_ORDER: "中腹足目",S_FAMILY: "瓶螺科",TITLE: "福寿螺卵",F_NAME: "luo04.jpg",},
{F_GROUP: "miao",S_GROUP: "腹足纲",S_ORDER: "柄眼目",S_FAMILY: "玛瑙螺科",TITLE: "非洲大蜗牛",F_NAME: "luo01.jpg",},
{F_GROUP: "miao",S_GROUP: "腹足纲",S_ORDER: "柄眼目",S_FAMILY: "蜗牛科",TITLE: "蜗牛",F_NAME: "woniu01.jpg",},
{F_GROUP: "miao",S_GROUP: "腹足纲",S_ORDER: "柄眼目",S_FAMILY: "蜗牛科",TITLE: "蜗牛2",F_NAME: "woniu02.jpg",},
{F_GROUP: "miao",S_GROUP: "腹足纲",S_ORDER: "柄眼目",S_FAMILY: "蛞蝓科",TITLE: "蛞蝓",F_NAME: "kuoyu01.jpg",},
{F_GROUP: "miao",S_GROUP: "腹足纲",S_ORDER: "柄眼目",S_FAMILY: "蛞蝓科",TITLE: "蛞蝓白",F_NAME: "kuoyu02.jpg",},
{F_GROUP: "miao",S_GROUP: "软甲纲",S_ORDER: "十足目",S_FAMILY: "沙蟹科",TITLE: "沙蟹0",F_NAME: "xie01.jpg",},
{F_GROUP: "miao",S_GROUP: "软甲纲",S_ORDER: "十足目",S_FAMILY: "沙蟹科",TITLE: "沙蟹1",F_NAME: "xie03.jpg",},
{F_GROUP: "miao",S_GROUP: "软甲纲",S_ORDER: "十足目",S_FAMILY: "沙蟹科",TITLE: "沙蟹2",F_NAME: "xie08.jpg",},
{F_GROUP: "miao",S_GROUP: "软甲纲",S_ORDER: "十足目",S_FAMILY: "沙蟹科",TITLE: "沙蟹3",F_NAME: "xie09.jpg",},
{F_GROUP: "miao",S_GROUP: "软甲纲",S_ORDER: "十足目",S_FAMILY: "沙蟹科",TITLE: "沙蟹4",F_NAME: "xie10.jpg",},
{F_GROUP: "miao",S_GROUP: "软甲纲",S_ORDER: "十足目",TITLE: "滩蟹",F_NAME: "xie07.jpg",},
{F_GROUP: "miao",S_GROUP: "软甲纲",S_ORDER: "十足目",TITLE: "红树林蟹",F_NAME: "xie06.jpg",},
{F_GROUP: "miao",S_GROUP: "软甲纲",S_ORDER: "十足目",TITLE: "红蟹",F_NAME: "xie02.jpg",},
{F_GROUP: "miao",S_GROUP: "软甲纲",S_ORDER: "十足目",TITLE: "藏蟹",F_NAME: "xie05.jpg",},
{F_GROUP: "miao",S_GROUP: "软甲纲",S_ORDER: "十足目",TITLE: "蟹和螺",F_NAME: "xie04.jpg",},
{F_GROUP: "miao",S_GROUP: "软甲纲",S_ORDER: "十足目",TITLE: "藤壶与海蟹",F_NAME: "thyhx.jpg",},
{F_GROUP: "miao",S_GROUP: "软甲纲",S_ORDER: "等足目",S_FAMILY: "海蟑螂科",TITLE: "海蟑螂",F_NAME: "haizhanglang01.jpg",},
{F_GROUP: "miao",S_GROUP: "软甲纲",S_ORDER: "等足目",TITLE: "球鼠妇",F_NAME: "qiushufu01.jpg",},
{F_GROUP: "miao",S_GROUP: "瓣鳃纲",S_ORDER: "异柱目",TITLE: "贻贝",F_NAME: "bei01.jpg",},
{F_GROUP: "miao",S_GROUP: "瓣鳃纲",S_ORDER: "异柱目",TITLE: "长牡蛎",F_NAME: "cml01.jpg",},
{F_GROUP: "miao",S_GROUP: "鱼纲",TITLE: "一群长鱼",F_NAME: "yu02.jpg",F_DESC: "鱼儿",},
{F_GROUP: "miao",S_GROUP: "鱼纲",TITLE: "一群长鱼2",F_NAME: "yu03.jpg",},
{F_GROUP: "miao",S_GROUP: "鱼纲",S_ORDER: "鲤形目",S_FAMILY: "鲤科",TITLE: "一群鱼1",F_NAME: "qunyu.jpg",F_DESC: "鱼儿",},
{F_GROUP: "miao",S_GROUP: "鱼纲",S_ORDER: "鲤形目",S_FAMILY: "鲤科",TITLE: "一群鱼2",F_NAME: "yuqun01.jpg",F_DESC: "鱼儿",},
{F_GROUP: "miao",S_GROUP: "鱼纲",S_ORDER: "鲤形目",S_FAMILY: "鲤科",TITLE: "俩鱼",F_NAME: "liayu.jpg",F_DESC: "鱼儿",},
{F_GROUP: "miao",S_GROUP: "鱼纲",TITLE: "细长",F_NAME: "yu01.jpg",F_DESC: "鱼儿",},
{F_GROUP: "miao",S_GROUP: "鱼纲",S_ORDER: "鲤形目",S_FAMILY: "鲤科",TITLE: "草鱼",F_NAME: "caoyu.jpg",F_DESC: "鱼儿",},
{F_GROUP: "miao",S_GROUP: "鱼纲",S_ORDER: "鲤形目",S_FAMILY: "鲤科",TITLE: "青鱼",F_NAME: "qingyu.jpg",F_DESC: "鱼儿",},
{F_GROUP: "miao",S_GROUP: "鱼纲",S_ORDER: "鲤形目",S_FAMILY: "鲤科",TITLE: "金鱼",F_NAME: "jinyu.jpg",F_DESC: "鱼儿",},
{F_GROUP: "miao",S_GROUP: "鱼纲",S_ORDER: "鲤形目",S_FAMILY: "鲤科",TITLE: "鲤鱼",F_NAME: "liyu01.jpg",F_DESC: "鱼儿",},
{F_GROUP: "miao",S_GROUP: "鱼纲",S_ORDER: "鲤形目",S_FAMILY: "鲤科",TITLE: "俩鱼",F_NAME: "yu04.jpg",},
{F_GROUP: "miao",S_GROUP: "鱼纲",S_ORDER: "鲱形目",S_FAMILY: "锯腹鳓科",TITLE: "鳓鱼",F_NAME: "leyu01.jpg",},
{F_GROUP: "miao",S_GROUP: "鸟纲",S_ORDER: "鸡形目",S_FAMILY: "雉科",TITLE: "泥滑滑打架了",F_NAME: "nihuahua01.jpg",LINK: "bird/灰胸竹鸡",},
{F_GROUP: "miao",S_GROUP: "鸟纲",S_ORDER: "鸡形目",S_FAMILY: "雉科",TITLE: "泥滑滑*2",F_NAME: "nihuahua03.jpg",LINK: "bird/灰胸竹鸡",},
{F_GROUP: "miao",S_GROUP: "鸟纲",S_ORDER: "鸡形目",S_FAMILY: "雉科",TITLE: "泥滑滑在看",F_NAME: "nihuahua02.jpg",LINK: "bird/灰胸竹鸡",},
{F_GROUP: "miao",S_GROUP: "鸟纲",S_ORDER: "鸡形目",S_FAMILY: "雉科",TITLE: "白的鸡",F_NAME: "baiji01.jpg",},
{F_GROUP: "miao",S_GROUP: "鸟纲",S_ORDER: "鸡形目",S_FAMILY: "雉科",TITLE: "黑的鸡",F_NAME: "ji01.jpg",},
{F_GROUP: "miao",S_GROUP: "鸟纲",S_ORDER: "鸡形目",S_FAMILY: "雉科",TITLE: "阉鸡",F_NAME: "ji02.jpg",},
{F_GROUP: "miao",S_GROUP: "鸟纲",S_ORDER: "鸡形目",S_FAMILY: "雉科",TITLE: "母鸡",F_NAME: "ji03.jpg",},
{F_GROUP: "miao",S_GROUP: "鸟纲",S_ORDER: "鸡形目",S_FAMILY: "雉科",TITLE: "竹篱母鸡",F_NAME: "ji04.jpg",},
{F_GROUP: "miao",S_GROUP: "鸟纲",S_ORDER: "鸡形目",S_FAMILY: "雉科",TITLE: "母鸡小鸡",F_NAME: "mujixiaoji01.jpg",},
{F_GROUP: "miao",S_GROUP: "鸟纲",S_ORDER: "雁形目",S_FAMILY: "鸭科",TITLE: "绿的鸭",F_NAME: "ya01.jpg",},
{F_GROUP: "miao",S_GROUP: "鸟纲",S_ORDER: "雁形目",S_FAMILY: "鸭科",TITLE: "麻鸭",F_NAME: "ya02.jpg",},
{F_GROUP: "miao",S_GROUP: "鸟纲",S_ORDER: "雁形目",S_FAMILY: "鸭科",TITLE: "麻鸭",F_NAME: "ya03.jpg",},
{F_GROUP: "miao",S_GROUP: "鸟纲",S_ORDER: "雁形目",S_FAMILY: "鸭科",TITLE: "麻鸭",F_NAME: "ya05.jpg",},
{F_GROUP: "miao",S_GROUP: "鸟纲",S_ORDER: "雁形目",S_FAMILY: "鸭科",TITLE: "白鸭",F_NAME: "ya04.jpg",},
{F_GROUP: "miao",S_GROUP: "鸟纲",S_ORDER: "雀形目",S_FAMILY: "伯劳科",TITLE: "伯劳立枝",F_NAME: "bolao01.jpg",LINK: "bird/棕背伯劳",},
{F_GROUP: "miao",S_GROUP: "鸟纲",S_ORDER: "雀形目",S_FAMILY: "伯劳科",TITLE: "伯劳立电杆",F_NAME: "bolao02.jpg",LINK: "bird/棕背伯劳",},
{F_GROUP: "miao",S_GROUP: "鸟纲",S_ORDER: "雀形目",S_FAMILY: "鹎科",TITLE: "白头鹎立枝",F_NAME: "baitoubei01.jpg",LINK: "bird/白头鹎",},
{F_GROUP: "miao",S_GROUP: "鸟纲",S_ORDER: "雀形目",S_FAMILY: "鹎科",TITLE: "红耳鹎电线上",F_NAME: "hongerbei01.jpg",LINK: "bird/红耳鹎",},
{F_GROUP: "miao",S_GROUP: "鸟纲",S_ORDER: "雀形目",S_FAMILY: "鹎科",TITLE: "红耳鹎竹竿蚂蚱",F_NAME: "hongerbei02.jpg",LINK: "bird/红耳鹎",},
{F_GROUP: "miao",S_GROUP: "鸟纲",S_ORDER: "鸽形目",S_FAMILY: "鸠鸽科",TITLE: "斑鸠飞",F_NAME: "banjiufei01.jpg",LINK: "bird/山斑鸠",},
{F_GROUP: "miao",S_GROUP: "鸟纲",S_ORDER: "雀形目",S_FAMILY: "鹟科",TITLE: "雌红尾水鸲捉虫",F_NAME: "zhuochong01.jpg",LINK: "bird/红尾水鸲",},
{F_GROUP: "miao",S_GROUP: "鸟纲",S_ORDER: "雀形目",S_FAMILY: "鹟科",TITLE: "雄红尾水鸲水上飞",F_NAME: "hongweishuiqu01.jpg",LINK: "bird/红尾水鸲",},
{F_GROUP: "miao",S_GROUP: "鸟纲",S_ORDER: "雀形目",S_FAMILY: "待定",TITLE: "躺电线",F_NAME: "tangdianxian.jpg",},
{F_GROUP: "miao",S_GROUP: "鸟纲",S_ORDER: "鹤形目",S_FAMILY: "秧鸡科",TITLE: "苦恶立水丛",F_NAME: "gue02.jpg",LINK: "bird/白胸苦恶鸟",},
{F_GROUP: "miao",S_GROUP: "鸟纲",S_ORDER: "雀形目",S_FAMILY: "椋鸟科",TITLE: "黑领椋鸟吃虫",F_NAME: "hllncc.jpg",},
{F_GROUP: "miao",S_GROUP: "鸟纲",S_ORDER: "雀形目",S_FAMILY: "燕科",TITLE: "燕子电线",F_NAME: "yanzidianxian01.jpg",},
{F_GROUP: "miao",S_GROUP: "鸟纲",S_ORDER: "雀形目",S_FAMILY: "鹟科",TITLE: "北红尾鸲夜吃虫",F_NAME: "bhwq01.jpg",},
{F_GROUP: "miao",S_GROUP: "鸟纲",S_ORDER: "雀形目",S_FAMILY: "鹟科",TITLE: "小画眉",F_NAME: "xiaohuamei01.jpg",LINK: "bird/黑领噪鹛",},
{F_GROUP: "miao",S_GROUP: "鸟纲",S_ORDER: "鹳形目",S_FAMILY: "鹭科",TITLE: "柳树鹭",F_NAME: "shulu.jpg",},
{F_GROUP: "miao",S_GROUP: "鸟纲",S_ORDER: "鹳形目",S_FAMILY: "鹭科",TITLE: "鹭寻食",F_NAME: "lu01.jpg",},
{F_GROUP: "miao",S_GROUP: "鸟纲",S_ORDER: "雀形目",S_FAMILY: "鸦科",TITLE: "雨红树灰喜鹊",F_NAME: "hxq01.jpg",},
{F_GROUP: "miao",S_GROUP: "哺乳纲",S_ORDER: "长鼻目",S_FAMILY: "长鼻目",TITLE: "大象",F_NAME: "daxiang01.jpg",},
{F_GROUP: "miao",S_GROUP: "哺乳纲",S_ORDER: "啮齿目",S_FAMILY: "松鼠科",TITLE: "赤腹松鼠",F_NAME: "songshu.jpg",F_DESC: "赤腹松鼠（学名：Callosciurus erythraeus ）又称红腹松鼠，为啮齿类动物。栖息于热带和亚热带森林，亦见于次生林、砍伐迹地以及丘陵台地、椰林、灌木林、竹林、乔木和竹林混交林、马尾松林、枞林、灌木丛等植被环境，是树栖动物。",},
{F_GROUP: "miao",S_GROUP: "哺乳纲",S_ORDER: "啮齿目",S_FAMILY: "松鼠科",TITLE: "隐纹花鼠",F_NAME: "huashu.jpg",F_DESC: "筑巢于树叉间或利用树洞作窝。其主要食物为各种坚果、浆果以及昆虫等，常与红腹松鼠一起觅食。",},
{F_GROUP: "miao",S_GROUP: "哺乳纲",S_ORDER: "啮齿目",S_FAMILY: "松鼠科",TITLE: "松鼠在看1",F_NAME: "songshu01.jpg",F_DESC: "松鼠在看~~~",},
{F_GROUP: "miao",S_GROUP: "哺乳纲",S_ORDER: "啮齿目",S_FAMILY: "松鼠科",TITLE: "松鼠在看2",F_NAME: "songshu03.jpg",},
{F_GROUP: "miao",S_GROUP: "哺乳纲",S_ORDER: "啮齿目",S_FAMILY: "松鼠科",TITLE: "松鼠吃果",F_NAME: "songshu02.jpg",},
{F_GROUP: "miao",S_GROUP: "哺乳纲",S_ORDER: "啮齿目",S_FAMILY: "鼠科",TITLE: "鼠",F_NAME: "shu.jpg",F_DESC: "喵才不吃。。。",},
{F_GROUP: "miao",S_GROUP: "哺乳纲",S_ORDER: "兔形目",S_FAMILY: "兔科",TITLE: "可怜的兔兔",F_NAME: "tuzi01.jpg",},
{F_GROUP: "miao",S_GROUP: "哺乳纲",S_ORDER: "食肉目",S_FAMILY: "猫科",TITLE: "白喵",F_NAME: "miao01.jpg",F_DESC: "喵就是喵~ 喵呜~~~",},
{F_GROUP: "miao",S_GROUP: "哺乳纲",S_ORDER: "食肉目",S_FAMILY: "猫科",TITLE: "花喵",F_NAME: "miao.jpg",F_DESC: "喵就是喵~ 喵呜~~~",},
{F_GROUP: "miao",S_GROUP: "哺乳纲",S_ORDER: "食肉目",S_FAMILY: "猫科",TITLE: "草丛喵",F_NAME: "miao04.jpg",F_DESC: "喵就是喵~ 喵呜~~~",},
{F_GROUP: "miao",S_GROUP: "哺乳纲",S_ORDER: "食肉目",S_FAMILY: "猫科",TITLE: "黑喵",F_NAME: "miao03.jpg",F_DESC: "喵就是喵~ 喵呜~~~",},
{F_GROUP: "miao",S_GROUP: "哺乳纲",S_ORDER: "食肉目",S_FAMILY: "猫科",TITLE: "俩喵",F_NAME: "miao05.jpg",F_DESC: "喵就是喵~ 喵呜~~~",},
{F_GROUP: "miao",S_GROUP: "哺乳纲",S_ORDER: "食肉目",S_FAMILY: "熊科",TITLE: "大熊猫",F_NAME: "dxm01.jpg",},
{F_GROUP: "miao",S_GROUP: "哺乳纲",S_ORDER: "食肉目",S_FAMILY: "熊科",TITLE: "灰熊",F_NAME: "gouxiong01.jpg",},
{F_GROUP: "miao",S_GROUP: "哺乳纲",S_ORDER: "食肉目",S_FAMILY: "獴科",TITLE: "非洲獴",F_NAME: "meng01.jpg",},
{F_GROUP: "miao",S_GROUP: "哺乳纲",S_ORDER: "食肉目",S_FAMILY: "犬科",TITLE: "黄汪",F_NAME: "wang01.jpg",F_DESC: "汪就是汪！汪~~~",},
{F_GROUP: "miao",S_GROUP: "哺乳纲",S_ORDER: "食肉目",S_FAMILY: "犬科",TITLE: "汪在飞",F_NAME: "wang02.jpg",F_DESC: "会飞的汪！汪~~~",},
{F_GROUP: "miao",S_GROUP: "哺乳纲",S_ORDER: "食肉目",S_FAMILY: "犬科",TITLE: "黑汪",F_NAME: "wang.jpg",F_DESC: "汪就是汪！汪~~~",},
{F_GROUP: "miao",S_GROUP: "哺乳纲",S_ORDER: "食肉目",S_FAMILY: "犬科",TITLE: "豺",F_NAME: "chai01.jpg",},
{F_GROUP: "miao",S_GROUP: "哺乳纲",S_ORDER: "食肉目",S_FAMILY: "犬科",TITLE: "狼",F_NAME: "lang01.jpg",},
{F_GROUP: "miao",S_GROUP: "哺乳纲",S_ORDER: "翼手目",S_FAMILY: "蝙蝠科",TITLE: "蝙蝠",F_NAME: "bianfu01.jpg",},
{F_GROUP: "miao",S_GROUP: "哺乳纲",S_ORDER: "奇蹄目",S_FAMILY: "貘科",TITLE: "中美貘",F_NAME: "mo01.jpg",},
{F_GROUP: "miao",S_GROUP: "哺乳纲",S_ORDER: "奇蹄目",S_FAMILY: "马科",TITLE: "马",F_NAME: "ma.jpg",F_DESC: "照相的",},
{F_GROUP: "miao",S_GROUP: "哺乳纲",S_ORDER: "偶蹄目",S_FAMILY: "牛科",TITLE: "黄牛",F_NAME: "huangniu.jpg",},
{F_GROUP: "miao",S_GROUP: "哺乳纲",S_ORDER: "偶蹄目",S_FAMILY: "牛科",TITLE: "羊",F_NAME: "yang.jpg",F_DESC: "路边偶遇",},
{F_GROUP: "miao",S_GROUP: "哺乳纲",S_ORDER: "灵长目",S_FAMILY: "猴科",TITLE: "川金丝猴",F_NAME: "hou01.jpg",},
{F_GROUP: "miao",S_GROUP: "哺乳纲",S_ORDER: "鼩形目",S_FAMILY: "鼩鼱科",TITLE: "鼩鼱",F_NAME: "qujing01.jpg",F_DESC: "咦！",},

{F_GROUP: "scene",S_GROUP:"星辰日月",TITLE:"凉如水",F_NAME:"yklrs.jpg",F_DESC:"夜色凉如水",},
{F_GROUP: "scene",S_GROUP:"星辰日月",TITLE:"仙女星云",F_NAME:"xiannv.jpg",},
{F_GROUP: "scene",S_GROUP:"星辰日月",TITLE:"昴",F_NAME:"mao.jpg",},
{F_GROUP: "scene",S_GROUP:"星辰日月",TITLE:"云天",F_NAME:"yuntian.jpg",},
{F_GROUP: "scene",S_GROUP:"星辰日月",TITLE:"岁",F_NAME:"muxing.jpg",F_DESC:"《甘石星经》有云<br>\r\n“单阏之岁，摄提格在卯，岁星在子，与须女、虚、危晨出夕入，其状甚大有光，若有小赤星附于其侧，是谓同盟。”<br>\r\n小赤星，图一岁星右上最外一颗，即是。",},
{F_GROUP: "scene",S_GROUP:"星辰日月",TITLE:"海王星",F_NAME:"hwx01.jpg",F_DESC:"2019 09 12",},
{F_GROUP: "scene",S_GROUP:"星辰日月",TITLE:"火星2018",F_NAME:"mars01.jpg",F_DESC:"2018 07 28",},
{F_GROUP: "scene",S_GROUP:"星辰日月",TITLE:"火星2020",F_NAME:"mars02.jpg",F_DESC:"2020 10 09",},
{F_GROUP: "scene",S_GROUP:"星辰日月",TITLE:"土星2017",F_NAME:"tuxing01.jpg",F_DESC:"2017 04 02",},
{F_GROUP: "scene",S_GROUP:"星辰日月",TITLE:"彗星46P",F_NAME:"46P.jpg",F_DESC:"2018 12 18",},
{F_GROUP: "scene",S_GROUP:"星辰日月",TITLE:"彗星2020F3_1",F_NAME:"2020F3.jpg",F_DESC:"2020 07 12",},
{F_GROUP: "scene",S_GROUP:"星辰日月",TITLE:"彗星2020F3_2",F_NAME:"2020F30722.jpg",F_DESC:"2020 07 22",},
{F_GROUP: "scene",S_GROUP:"星辰日月",TITLE:"金星月牙",F_NAME:"jinxing20200712.jpg",F_DESC:"2020 07 12",},
{F_GROUP: "scene",S_GROUP:"星辰日月",TITLE:"青天白日",F_NAME:"qtbr.jpg",},
{F_GROUP: "scene",S_GROUP:"星辰日月",TITLE:"太阳黑子",F_NAME:"heizi01.jpg",F_DESC:"2019 05 12 18:23",},
{F_GROUP: "scene",S_GROUP:"星辰日月",TITLE:"日偏食",F_NAME:"rishi2019.jpg",F_DESC:"2019 12 26 13:09",},
{F_GROUP: "scene",S_GROUP:"星辰日月",TITLE:"日环食",F_NAME:"rishi2020a.jpg",F_DESC:"2020 06 21 16:08",},
{F_GROUP: "scene",S_GROUP:"星辰日月",TITLE:"日暮霞光",F_NAME:"xiaguang01.jpg",},
{F_GROUP: "scene",S_GROUP:"星辰日月",TITLE:"日落",F_NAME:"riluo01.jpg",},
{F_GROUP: "scene",S_GROUP:"星辰日月",TITLE:"月全食",F_NAME:"yuequanshi01.jpg",F_DESC:"2018 07 28 0‏‎3:50:16",},
{F_GROUP: "scene",S_GROUP:"星辰日月",TITLE:"月下娘娘庙",F_NAME:"nnm.jpg",F_DESC:"月下娘娘庙，海月共潮升",},
{F_GROUP: "scene",S_GROUP:"星辰日月",TITLE:"月有食",F_NAME:"yueshi.jpg",F_DESC:"丁酉闰六月十七，月有食之，山河动，古树摇。",},
{F_GROUP: "scene",S_GROUP:"星辰日月",TITLE:"月云",F_NAME:"yueyun.jpg",},
{F_GROUP: "scene",S_GROUP:"星辰日月",TITLE:"暮云",F_NAME:"cloud01.jpg",},
{F_GROUP: "scene",S_GROUP:"星辰日月",TITLE:"星月合",F_NAME:"jxhy.jpg",F_DESC:"金星合月",},
{F_GROUP: "scene",S_GROUP:"星辰日月",TITLE:"蝠月",F_NAME:"fuyue.jpg",},
{F_GROUP: "scene",S_GROUP:"星辰日月",TITLE:"树月",F_NAME:"shuyue.jpg",},
{F_GROUP: "scene",S_GROUP:"星辰日月",TITLE:"冷月",F_NAME:"yue1.jpg",},
{F_GROUP: "scene",S_GROUP:"星辰日月",TITLE:"海月升",F_NAME:"haiyuesheng.jpg",},


{F_GROUP: "scene",S_GROUP:"林海花果",TITLE:"稻田",F_NAME:"daotian.jpg",},
{F_GROUP: "scene",S_GROUP:"林海花果",TITLE:"夜树",F_NAME:"yeshu.jpg",},
{F_GROUP: "scene",S_GROUP:"林海花果",TITLE:"树天",F_NAME:"shutian.jpg",},
{F_GROUP: "scene",S_GROUP:"林海花果",TITLE:"望天",F_NAME:"wangtian.jpg",},
{F_GROUP: "scene",S_GROUP:"林海花果",TITLE:"蓝红绿",F_NAME:"lanhonglv.jpg",},
{F_GROUP: "scene",S_GROUP:"林海花果",TITLE:"林间蛛网",F_NAME:"zhuwang01.jpg",},
{F_GROUP: "scene",S_GROUP:"林海花果",TITLE: "枯木",F_NAME: "kumu.jpg",},
{F_GROUP: "scene",S_GROUP:"林海花果",TITLE: "树上乌鸫",F_NAME: "wudong01.jpg",},
{F_GROUP: "scene",S_GROUP:"林海花果",TITLE: "空树一鸟",F_NAME: "ksyn01.jpg",},
{F_GROUP: "scene",S_GROUP:"河海湖山",TITLE:"河清",F_NAME:"river1.jpg",F_DESC:"河水",},
{F_GROUP: "scene",S_GROUP:"河海湖山",TITLE:"湖中游",F_NAME:"xihu01.jpg",},
{F_GROUP: "scene",S_GROUP:"河海湖山",TITLE:"玉带晴虹",F_NAME:"xihu02.jpg",},
{F_GROUP: "scene",S_GROUP:"河海湖山",TITLE:"荷塘·夏",F_NAME:"hetang01.jpg",LINK: "drug/荷叶",},
{F_GROUP: "scene",S_GROUP:"河海湖山",TITLE:"荷塘·秋",F_NAME:"hetang02.jpg",LINK: "drug/荷叶",},
{F_GROUP: "scene",S_GROUP:"河海湖山",TITLE:"西湖",F_NAME:"xihu03.jpg",},
{F_GROUP: "scene",S_GROUP:"河海湖山",TITLE:"湖中岛",F_NAME:"xihu04.jpg",},
{F_GROUP: "scene",S_GROUP:"河海湖山",TITLE:"江原",F_NAME:"jiangyuan.jpg",},
{F_GROUP: "scene",S_GROUP:"河海湖山",TITLE:"水岸",F_NAME:"shuian.jpg",},
{F_GROUP: "scene",S_GROUP:"河海湖山",TITLE:"水冷潭空",F_NAME:"shuiqing.jpg",},
{F_GROUP: "scene",S_GROUP:"河海湖山",TITLE:"落日",F_NAME:"hairi.jpg",},
{F_GROUP: "scene",S_GROUP:"河海湖山",TITLE:"孤树",F_NAME:"gushu.jpg",F_DESC:"孤单的大树。",},
{F_GROUP: "scene",S_GROUP:"河海湖山",TITLE:"雾山",F_NAME:"wushan.jpg",},
{F_GROUP: "scene",S_GROUP:"河海湖山",TITLE:"湖光",F_NAME:"huguang.jpg",},
{F_GROUP: "scene",S_GROUP:"河海湖山",TITLE:"海沙痕",F_NAME:"niaosha.jpg",},
{F_GROUP: "scene",S_GROUP:"河海湖山",TITLE:"海石",F_NAME:"haishi.jpg",},
{F_GROUP: "scene",S_GROUP:"河海湖山",TITLE:"湖光与小鸟",F_NAME:"hgyxn.jpg",},
{F_GROUP: "scene",S_GROUP:"雨雾霜露",TITLE:"雨落",F_NAME:"yuluo.jpg",},
{F_GROUP: "scene",S_GROUP:"雨雾霜露",TITLE:"空山一段云",F_NAME:"ksydy.jpg",},
{F_GROUP: "scene",S_GROUP:"雨雾霜露",TITLE:"云光",F_NAME:"yunguang01.jpg",},
{F_GROUP: "scene",S_GROUP:"雨雾霜露",TITLE:"雨草",F_NAME:"yucao.jpg",},
{F_GROUP: "scene",S_GROUP:"雨雾霜露",TITLE:"草露",F_NAME:"caolu.jpg",},
{F_GROUP: "scene",S_GROUP:"雨雾霜露",TITLE:"山雾",F_NAME:"shanwu.jpg",},
{F_GROUP: "scene",S_GROUP:"雨雾霜露",TITLE:"云过楼",F_NAME:"yunlou.jpg",F_DESC:"云过楼",},
{F_GROUP: "scene",S_GROUP:"雨雾霜露",TITLE: "雨荷",F_NAME: "hehuayu.jpg",},
{F_GROUP: "scene",S_GROUP:"雨雾霜露",TITLE:"日晕",F_NAME:"riyun01.jpg",},
{F_GROUP: "scene",S_GROUP:"雨雾霜露",TITLE:"虹与霓",F_NAME:"hong01.jpg",},
{F_GROUP: "scene",S_GROUP:"雨雾霜露",TITLE:"地平线虹",F_NAME:"hong02.jpg",},
{F_GROUP: "scene",S_GROUP:"雨雾霜露",TITLE:"半雨",F_NAME:"banyu.jpg",},
{F_GROUP: "scene",S_GROUP:"雨雾霜露",TITLE:"叶上霜",F_NAME:"shuang01.jpg",},
{F_GROUP: "scene",S_GROUP:"雨雾霜露",TITLE:"暮云",F_NAME:"muyun01.jpg",F_DESC:"2019 08 24",},
{F_GROUP: "scene",S_GROUP:"雨雾霜露",TITLE:"层积云",F_NAME:"cloudcjy01.jpg",F_DESC:"2019 06 16",},
{F_GROUP: "scene",S_GROUP:"雨雾霜露",TITLE:"浓积云",F_NAME:"cloudnjy01.jpg",F_DESC:"2019 08 04",},
{F_GROUP: "scene",S_GROUP:"雨雾霜露",TITLE:"卷层云",F_NAME:"cloudjcy01.jpg",F_DESC:"2019 08 04",},
{F_GROUP: "scene",S_GROUP:"雨雾霜露",TITLE:"云前云",F_NAME:"cloudyqy01.jpg",F_DESC:"2020 08 09",},
{F_GROUP: "scene",S_GROUP:"鸟兽鱼虫",TITLE:"海沙狗",F_NAME:"shantangou.jpg",},
{F_GROUP: "scene",S_GROUP:"鸟兽鱼虫",TITLE:"大鸟在天",F_NAME:"daniao.jpg",},
{F_GROUP: "scene",S_GROUP:"鸟兽鱼虫",TITLE:"蜘雨",F_NAME:"zhuyu01.jpg",},
{F_GROUP: "scene",S_GROUP:"鸟兽鱼虫",TITLE:"湖鸟",F_NAME:"huniao.jpg",},
{F_GROUP: "scene",S_GROUP:"鸟兽鱼虫",TITLE:"虫鸟树",F_NAME:"chongniao.jpg",},
{F_GROUP: "scene",S_GROUP:"鸟兽鱼虫",TITLE:"孤鸟立枝",F_NAME:"guniao01.jpg",},
{F_GROUP: "scene",S_GROUP:"鸟兽鱼虫",TITLE:"蝶立花",F_NAME:"dielihua01.jpg",},
{F_GROUP: "scene",S_GROUP:"鸟兽鱼虫",TITLE:"树影",F_NAME:"muniao.jpg",},
{F_GROUP: "scene",S_GROUP:"鸟兽鱼虫",TITLE:"飞鸟枯树",F_NAME:"feiniaokushu.jpg",},
{F_GROUP: "scene",S_GROUP:"鸟兽鱼虫",TITLE:"河边一群鸭",F_NAME:"yiqunya01.jpg",},
{F_GROUP: "scene",S_GROUP:"鸟兽鱼虫",TITLE:"苇莺",F_NAME:"weiying.jpg",},
{F_GROUP: "scene",S_GROUP:"鸟兽鱼虫",TITLE:"飞鸟阵",F_NAME:"niaozhen.jpg",},
{F_GROUP: "scene",S_GROUP:"鸟兽鱼虫",TITLE:"芦苇黑伯劳",F_NAME:"luweibolao.jpg",},
{F_GROUP: "scene",S_GROUP:"鸟兽鱼虫",TITLE:"群鸟过树",F_NAME:"qunniao01.jpg",},

{F_GROUP: "utensil",S_GROUP:"器物",TITLE:"楚编钟",F_NAME:"chubiaozhong.jpg",F_DESC:"楚编钟",},
{F_GROUP: "utensil",S_GROUP:"器物",TITLE:"石头棋",F_NAME:"shitouqi.jpg",},
{F_GROUP: "utensil",S_GROUP:"器物",TITLE:"元青花四爱图梅瓶",F_NAME:"ciping01.jpg",SHOW:"no",},
{F_GROUP: "utensil",S_GROUP:"器物",TITLE:"越王勾践剑",F_NAME:"yuewangjian.jpg",F_DESC:"越王勾践剑",},
{F_GROUP: "utensil",S_GROUP:"器物",TITLE:"陶盆",F_NAME:"tao08.jpg",},
{F_GROUP: "utensil",S_GROUP:"器物",TITLE:"七里河",F_NAME:"qilihe01.jpg",},
{F_GROUP: "utensil",S_GROUP:"器物",TITLE:"蜡烛",F_NAME:"lazhu01.jpg",},
{F_GROUP: "utensil",S_GROUP:"建筑",TITLE:"武大门（夜）",F_NAME:"whdx02.jpg",SHOW:"no",},
{F_GROUP: "utensil",S_GROUP:"建筑",TITLE:"苏小小墓",F_NAME:"suxiaoxiaomu.jpg",SHOW:"no",},
{F_GROUP: "utensil",S_GROUP:"建筑",TITLE:"浙大门",F_NAME:"zheda01.jpg",SHOW:"no",},
{F_GROUP: "utensil",S_GROUP:"建筑",TITLE:"庙葫芦",F_NAME:"hulu01.jpg",},
{F_GROUP: "utensil",S_GROUP:"建筑",TITLE:"滕阁秋风",F_NAME:"twg01.jpg",SHOW:"no",},
{F_GROUP: "utensil",S_GROUP:"建筑",TITLE:"雷峰塔",F_NAME:"lft09.jpg",SHOW:"no",},
{F_GROUP: "utensil",S_GROUP:"建筑",TITLE:"开元塔",F_NAME:"kys01.jpg",SHOW:"no",},
{F_GROUP: "utensil",S_GROUP:"建筑",TITLE:"北京站",F_NAME:"bjz.jpg",SHOW:"no",},
{F_GROUP: "utensil",S_GROUP:"建筑",TITLE:"雾里长城",F_NAME:"cc01.jpg",SHOW:"no",},
{F_GROUP: "utensil",S_GROUP:"建筑",TITLE:"楚天极目",F_NAME:"hhl08.jpg",SHOW:"no",},
{F_GROUP: "utensil",S_GROUP:"建筑",TITLE:"鄂军都督府内",F_NAME:"hbddf02.jpg",SHOW:"no",},
{F_GROUP: "utensil",S_GROUP:"建筑",TITLE:"保俶塔",F_NAME:"baochuta.jpg",SHOW:"no",},
{F_GROUP: "utensil",S_GROUP:"建筑",TITLE:"断桥",F_NAME:"duanqiao.jpg",SHOW:"no",},
{F_GROUP: "utensil",S_GROUP:"建筑",TITLE:"雷峰塔塔基",F_NAME:"lft07.jpg",SHOW:"no",},
{F_GROUP: "utensil",S_GROUP:"建筑",TITLE:"岳武穆遗像亭",F_NAME:"hhl04.jpg",SHOW:"no",},
{F_GROUP: "utensil",S_GROUP:"建筑",TITLE:"曲水流觞",F_NAME:"hhl06.jpg",SHOW:"no",},
{F_GROUP: "utensil",S_GROUP:"建筑",TITLE:"太和殿",F_NAME:"taihedian.jpg",SHOW:"no",},
{F_GROUP: "utensil",S_GROUP:"建筑",TITLE:"卢沟桥",F_NAME:"lgq.jpg",SHOW:"no",},
{F_GROUP: "utensil",S_GROUP:"建筑",TITLE:"十七孔桥",F_NAME:"yhy02.jpg",SHOW:"no",},
{F_GROUP: "utensil",S_GROUP:"建筑",TITLE:"颐和故楼",F_NAME:"yhy01.jpg",SHOW:"no",},
{F_GROUP: "utensil",S_GROUP:"建筑",TITLE:"鄂军都督府",F_NAME:"ejundudufu.jpg",F_DESC:"鄂军都督府",SHOW:"no",},
{F_GROUP: "utensil",S_GROUP:"建筑",TITLE:"雪屋顶",F_NAME:"tt03.jpg",SHOW:"no",},
{F_GROUP: "utensil",S_GROUP:"建筑",TITLE:"宛平城门",F_NAME:"wpc01.jpg",SHOW:"no",},
{F_GROUP: "utensil",S_GROUP:"建筑",TITLE:"天坛",F_NAME:"tt01.jpg",SHOW:"no",},
{F_GROUP: "utensil",S_GROUP:"建筑",TITLE:"玉带晴虹",F_NAME:"qyfh01.jpg",F_DESC:"玉带晴虹",SHOW:"no",},
{F_GROUP: "utensil",S_GROUP:"建筑",TITLE:"武大门（日）",F_NAME:"whdx01.jpg",SHOW:"no",},
{F_GROUP: "utensil",S_GROUP:"建筑",TITLE:"水桥",F_NAME:"shuiqiao.jpg",},
{F_GROUP: "utensil",S_GROUP:"建筑",TITLE:"雄州雾列",F_NAME:"twg02.jpg",SHOW:"no",},
{F_GROUP: "utensil",S_GROUP:"建筑",TITLE:"古屋尖顶",F_NAME:"jianding.jpg",},
{F_GROUP: "utensil",S_GROUP:"建筑",TITLE:"武汉长江大桥",F_NAME:"whcjdq.jpg",SHOW:"no",},
{F_GROUP: "utensil",S_GROUP:"建筑",TITLE:"林徽因墓",F_NAME:"huiyingmu.jpg",SHOW:"no",},
{F_GROUP: "utensil",S_GROUP:"建筑",TITLE:"武松墓",F_NAME:"wusongmu.jpg",SHOW:"no",},
{F_GROUP: "utensil",S_GROUP:"碑刻",TITLE:"盡忠報国",F_NAME:"ym04.jpg",SHOW:"no",},
{F_GROUP: "utensil",S_GROUP:"碑刻",TITLE:"越王台",F_NAME:"ywt01.jpg",SHOW:"no",},
{F_GROUP: "utensil",S_GROUP:"碑刻",TITLE:"盘龙雪水",F_NAME:"tt02.jpg",SHOW:"no",},
{F_GROUP: "utensil",S_GROUP:"碑刻",TITLE:"黄鹤楼公园",F_NAME:"hhl07.jpg",SHOW:"no",},
{F_GROUP: "utensil",S_GROUP:"碑刻",TITLE:"雷峰塔重建",F_NAME:"lft02.jpg",SHOW:"no",},
{F_GROUP: "utensil",S_GROUP:"碑刻",TITLE:"精忠报国",F_NAME:"hhl03.jpg",SHOW:"no",},
{F_GROUP: "utensil",S_GROUP:"碑刻",TITLE:"一统天下",F_NAME:"duian.jpg",SHOW:"no",},
{F_GROUP: "utensil",S_GROUP:"碑刻",TITLE:"黄鹤楼",F_NAME:"hhl01.jpg",SHOW:"no",},
{F_GROUP: "utensil",S_GROUP:"碑刻",TITLE:"碧血丹心",F_NAME:"yuemiao01.jpg",SHOW:"no",},
{F_GROUP: "utensil",S_GROUP:"碑刻",TITLE:"开元寺窗雕",F_NAME:"kys02.jpg",SHOW:"no",},
{F_GROUP: "utensil",S_GROUP:"碑刻",TITLE:"灵隐寺窗雕",F_NAME:"lys02.jpg",SHOW:"no",},
{F_GROUP: "utensil",S_GROUP:"碑刻",TITLE:"雷峰塔夕照毓秀",F_NAME:"lft03.jpg",SHOW:"no",},
{F_GROUP: "utensil",S_GROUP:"碑刻",TITLE:"雷峰塔南无",F_NAME:"lft04.jpg",SHOW:"no",},
{F_GROUP: "utensil",S_GROUP:"雕塑",TITLE:"岳飞坐像",F_NAME:"ym03.jpg",SHOW:"no",},
{F_GROUP: "utensil",S_GROUP:"雕塑",TITLE:"陶龙猫",F_NAME:"tao01.jpg",F_DESC:"陶龙猫",},
{F_GROUP: "utensil",S_GROUP:"雕塑",TITLE:"陶羊",F_NAME:"tao05.jpg",},
{F_GROUP: "utensil",S_GROUP:"雕塑",TITLE:"陶象",F_NAME:"tao06.jpg",},
{F_GROUP: "utensil",S_GROUP:"雕塑",TITLE:"陶龟猪",F_NAME:"tao07.jpg",},
{F_GROUP: "utensil",S_GROUP:"雕塑",TITLE:"岳飞（武）",F_NAME:"hhl05.jpg",SHOW:"no",},
{F_GROUP: "utensil",S_GROUP:"雕塑",TITLE:"盘蛇",F_NAME:"panshe.jpg",F_DESC:"盘蛇",SHOW:"no",},
{F_GROUP: "utensil",S_GROUP:"雕塑",TITLE:"飞来峰造像",F_NAME:"feilai01.jpg",F_DESC:"飞来峰造像",SHOW:"no",},
{F_GROUP: "utensil",S_GROUP:"雕塑",TITLE:"潭柘望天",F_NAME:"tzs01.jpg",},
{F_GROUP: "utensil",S_GROUP:"雕塑",TITLE:"岳飞（杭）",F_NAME:"yuefei01.jpg",F_DESC:"岳飞像",SHOW:"no",},
{F_GROUP: "utensil",S_GROUP:"雕塑",TITLE:"秋瑾",F_NAME:"qiujin.jpg",F_DESC:"秋瑾",SHOW:"no",},
{F_GROUP: "utensil",S_GROUP:"雕塑",TITLE:"陶人",F_NAME:"tao04.jpg",F_DESC:"陶柱",},
{F_GROUP: "utensil",S_GROUP:"雕塑",TITLE:"陶几",F_NAME:"tao03.jpg",F_DESC:"陶几",},
{F_GROUP: "utensil",S_GROUP:"雕塑",TITLE:"陶鸡犬",F_NAME:"tao02.jpg",F_DESC:"陶鸡犬",},
{F_GROUP: "utensil",S_GROUP:"古币",TITLE:"1766",F_NAME:"gubi01.jpg",},
{F_GROUP: "utensil",S_GROUP:"古币",TITLE:"1771",F_NAME:"gubi04.jpg",},
{F_GROUP: "utensil",S_GROUP:"古币",TITLE:"HISPAN ET IND",F_NAME:"gubi05.jpg",},
{F_GROUP: "utensil",S_GROUP:"古币",TITLE:"1842",F_NAME:"gubi02.jpg",},
{F_GROUP: "utensil",S_GROUP:"古币",TITLE:"1872",F_NAME:"gubi03.jpg",},
{F_GROUP: "utensil",S_GROUP:"车船行走",TITLE:"古沉船",F_NAME:"chenchuan01.jpg",},
{F_GROUP: "utensil",S_GROUP:"车船行走",TITLE:"飞机",F_NAME:"feiji01.jpg",},
{F_GROUP: "utensil",S_GROUP:"车船行走",TITLE:"飞机残影",F_NAME:"feiji02.jpg",},
{F_GROUP: "utensil",S_GROUP:"车船行走",TITLE:"战斗机",F_NAME:"zhandouji01.jpg",SHOW:"no",},

{F_GROUP: "wood",S_GROUP:"木",S_CLASS: "松柏纲",S_ORDER: "松柏目",S_FAMILY: "松科",TITLE: "松",F_NAME: "song.jpg",},
{F_GROUP: "wood",S_GROUP:"木",S_CLASS: "松柏纲",S_ORDER: "松柏目",S_FAMILY: "柏科",TITLE: "圆柏",F_NAME: "bai02.jpg",},
{F_GROUP: "wood",S_GROUP:"木",S_CLASS: "松柏纲",S_ORDER: "红豆杉目",S_FAMILY: "红豆杉科",TITLE: "红豆杉叶",F_NAME: "hds01.jpg",},
{F_GROUP: "wood",S_GROUP:"木",S_CLASS: "松柏纲",S_ORDER: "红豆杉目",S_FAMILY: "红豆杉科",TITLE: "红豆杉",F_NAME: "hds02.jpg",},
{F_GROUP: "wood",S_GROUP:"木",S_CLASS: "松柏纲",S_ORDER: "松柏目",F_NAME: "bai.jpg",},
{F_GROUP: "wood",S_GROUP:"木",S_CLASS: "银杏纲",S_ORDER: "银杏目",S_FAMILY: "银杏科",TITLE: "银杏1",F_NAME: "yinxing01.jpg",},
{F_GROUP: "wood",S_GROUP:"木",S_CLASS: "银杏纲",S_ORDER: "银杏目",S_FAMILY: "银杏科",TITLE: "银杏2",F_NAME: "yinxing02.jpg",},
{F_GROUP: "wood",S_GROUP:"木",S_CLASS: "苏铁纲",S_ORDER: "苏铁目",S_FAMILY: "苏铁科",TITLE: "苏铁",F_NAME: "sutie01.jpg",},
{F_GROUP: "wood",S_GROUP:"木",S_CLASS: "单子叶植物纲",S_ORDER: "初生目",S_FAMILY: "棕榈科",TITLE: "棕榈",F_NAME: "jbl01.jpg",},
{F_GROUP: "wood",S_GROUP:"木",S_CLASS: "单子叶植物纲",S_ORDER: "初生目",S_FAMILY: "棕榈科",TITLE: "棕榈2",F_NAME: "zlv02.jpg",},
{F_GROUP: "wood",S_GROUP:"木",S_CLASS: "单子叶植物纲",S_ORDER: "初生目",S_FAMILY: "棕榈科",TITLE: "蒲葵",F_NAME: "zlv03.jpg",},
{F_GROUP: "wood",S_GROUP:"木",S_CLASS: "单子叶植物纲",S_ORDER: "初生目",S_FAMILY: "棕榈科",TITLE: "金山葵",F_NAME: "zlv04.jpg",},
{F_GROUP: "wood",S_GROUP:"木",S_CLASS: "双子叶植物纲",S_ORDER: "荨麻目",S_FAMILY: "桑科",TITLE: "榕",F_NAME: "rongshu.jpg",},
{F_GROUP: "wood",S_GROUP:"木",S_CLASS: "双子叶植物纲",S_ORDER: "侧膜胎座目",S_FAMILY: "龙脑香科",TITLE: "娑罗树",F_NAME: "sls01.jpg",},
{F_GROUP: "wood",S_GROUP:"木",S_CLASS: "双子叶植物纲",S_ORDER: "山龙眼目",S_FAMILY: "山龙眼科",TITLE: "银桦",F_NAME: "yh01.jpg",},
{F_GROUP: "wood",S_GROUP:"木",S_CLASS: "双子叶植物纲",S_ORDER: "桃金娘目",S_FAMILY: "桃金娘科",TITLE: "桉树",F_NAME: "as01.jpg",},
{F_GROUP: "wood",S_GROUP:"木",S_CLASS: "双子叶植物纲",S_ORDER: "桃金娘目",S_FAMILY: "红树科",TITLE: "红树",F_NAME: "hongshu01.jpg",},
{F_GROUP: "wood",S_GROUP:"木",S_CLASS: "双子叶植物纲",S_ORDER: "桃金娘目",S_FAMILY: "红树科",TITLE: "红树",F_NAME: "hongshu02.jpg",},
{F_GROUP: "wood",S_GROUP:"木",S_CLASS: "双子叶植物纲",S_ORDER: "桃金娘目",S_FAMILY: "红树科",TITLE: "红树",F_NAME: "hongshu03.jpg",},
{F_GROUP: "wood",S_GROUP:"木",S_CLASS: "双子叶植物纲",S_ORDER: "桃金娘目",S_FAMILY: "红树科",TITLE: "红树",F_NAME: "hongshu04.jpg",},
{F_GROUP: "wood",S_GROUP:"木",S_CLASS: "双子叶植物纲",S_ORDER: "桃金娘目",S_FAMILY: "红树科",TITLE: "红树",F_NAME: "hongshu05.jpg",},
{F_GROUP: "wood",S_GROUP:"木",S_CLASS: "双子叶植物纲",S_ORDER: "桃金娘目",S_FAMILY: "红树科",TITLE: "红树",F_NAME: "hongshu06.jpg",},
{F_GROUP: "wood",S_GROUP:"木",S_CLASS: "双子叶植物纲",S_ORDER: "毛茛目",S_FAMILY: "樟科",TITLE: "天竺桂",F_NAME: "tzg01.jpg",},
{F_GROUP: "wood",S_GROUP:"木",S_CLASS: "双子叶植物纲",S_ORDER: "捩花目",S_FAMILY: "夹竹桃科",TITLE: "夹竹桃",F_NAME: "jzt01.jpg",},
{F_GROUP: "wood",S_GROUP:"木",S_CLASS: "双子叶植物纲",S_ORDER: "捩花目",S_FAMILY: "木犀科",TITLE: "紫丁香",F_NAME: "zdx01.jpg",},
{F_GROUP: "wood",S_GROUP:"木",S_CLASS: "双子叶植物纲",S_ORDER: "捩花目",S_FAMILY: "木犀科",TITLE: "连翘",F_NAME: "lq01.jpg",},
{F_GROUP: "wood",S_GROUP:"木",S_CLASS: "双子叶植物纲",S_ORDER: "仙人掌目",S_FAMILY: "仙人掌科",TITLE: "火龙果",F_NAME: "hlg01.jpg",},
{F_GROUP: "wood",S_GROUP:"木",S_CLASS: "双子叶植物纲",S_ORDER: "无患子目",S_FAMILY: "苦木科",TITLE: "臭椿",F_NAME: "chouc02.jpg",},
{F_GROUP: "wood",S_GROUP:"木",S_CLASS: "双子叶植物纲",S_ORDER: "管状花目",S_FAMILY: "紫葳科",TITLE: "火焰树",F_NAME: "hys01.jpg",},
{F_GROUP: "wood",S_GROUP:"木",S_CLASS: "双子叶植物纲",S_ORDER: "大戟目",S_FAMILY: "大戟科",TITLE: "蓖麻",F_NAME: "bima01.jpg",},
{F_GROUP: "wood",S_GROUP:"木",S_CLASS: "双子叶植物纲",S_ORDER: "鼠李目",S_FAMILY: "葡萄科",TITLE: "葡萄藤",F_NAME: "putao01.jpg",},
{F_GROUP: "wood",S_GROUP:"木",S_CLASS: "双子叶植物纲",S_ORDER: "无患子目",S_FAMILY: "槭树科",TITLE: "元宝枫",F_NAME: "ybf01.jpg",},
{F_GROUP: "wood",S_GROUP:"木",S_CLASS: "双子叶植物纲",S_ORDER: "杨柳目",S_FAMILY: "杨柳科",TITLE: "柳树",F_NAME: "liu01.jpg",},
{F_GROUP: "wood",S_GROUP:"木",TITLE: "绿叶长",F_NAME: "mu01.jpg",},
{F_GROUP: "wood",S_GROUP:"木",TITLE: "对叶长",F_NAME: "mu02.jpg",},
{F_GROUP: "wood",S_GROUP:"果",S_CLASS: "双子叶植物纲",S_ORDER: "无患子目",S_FAMILY: "槭树科",TITLE: "秀丽槭",F_NAME: "qishu01.jpg",},
{F_GROUP: "wood",S_GROUP:"果",S_CLASS: "双子叶植物纲",S_ORDER: "无患子目",S_FAMILY: "苦木科",TITLE: "臭椿",F_NAME: "chouc01.jpg",},
{F_GROUP: "wood",S_GROUP:"果",S_CLASS: "松柏纲",S_ORDER: "松柏目",S_FAMILY: "松科",TITLE: "杉果",F_NAME: "shanguo01.jpg",},
{F_GROUP: "wood",S_GROUP:"果",S_CLASS: "松柏纲",S_ORDER: "松柏目",S_FAMILY: "松科",TITLE: "松果",F_NAME: "songguo01.jpg",},
{F_GROUP: "wood",S_GROUP:"果",S_CLASS: "单子叶植物纲",S_ORDER: "芭蕉目",S_FAMILY: "芭蕉科",TITLE: "香蕉",F_NAME: "xiangjiao01.jpg",},
{F_GROUP: "wood",S_GROUP:"果",S_CLASS: "单子叶植物纲",S_ORDER: "禾本目",S_FAMILY: "禾本科",TITLE: "玉米",F_NAME: "yumi01.jpg",},
{F_GROUP: "wood",S_GROUP:"果",S_CLASS: "单子叶植物纲",S_ORDER: "禾本目",S_FAMILY: "禾本科",TITLE: "水稻1",F_NAME: "shuidao01.jpg",},
{F_GROUP: "wood",S_GROUP:"果",S_CLASS: "单子叶植物纲",S_ORDER: "禾本目",S_FAMILY: "禾本科",TITLE: "水稻2",F_NAME: "shuidao02.jpg",},
{F_GROUP: "wood",S_GROUP:"果",S_CLASS: "单子叶植物纲",S_ORDER: "莎草目",S_FAMILY: "莎草科",TITLE: "浆果薹草",F_NAME: "hongguo02.jpg",},
{F_GROUP: "wood",S_GROUP:"果",S_CLASS: "单子叶植物纲",S_ORDER: "初生目",S_FAMILY: "棕榈科",TITLE: "棕榈",F_NAME: "zlv01.jpg",},
{F_GROUP: "wood",S_GROUP:"果",S_CLASS: "单子叶植物纲",S_ORDER: "初生目",S_FAMILY: "棕榈科",TITLE: "砂糖椰子",F_NAME: "styz01.jpg",},
{F_GROUP: "wood",S_GROUP:"果",S_CLASS: "单子叶植物纲",S_ORDER: "百合目",S_FAMILY: "天门冬科",TITLE: "天门冬",F_NAME: "tmd01.jpg",},
{F_GROUP: "wood",S_GROUP:"果",S_CLASS: "单子叶植物纲",S_ORDER: "天南星目",S_FAMILY: "天南星科",TITLE: "海芋3",F_NAME: "haiyu03.jpg",},
{F_GROUP: "wood",S_GROUP:"果",S_CLASS: "双子叶植物纲",S_ORDER: "山毛榉目",S_FAMILY: "壳斗科",TITLE: "板栗",TITLE: "板栗",F_NAME: "banli01.jpg",},
{F_GROUP: "wood",S_GROUP:"果",S_CLASS: "双子叶植物纲",S_ORDER: "柿目",S_FAMILY: "柿科",TITLE: "柿子",F_NAME: "shizi01.jpg",LINK:"drug/柿蒂",},
{F_GROUP: "wood",S_GROUP:"果",S_CLASS: "双子叶植物纲",S_ORDER: "柿目",S_FAMILY: "山矾科",TITLE: "白檀",F_NAME: "baitan01.jpg",},
{F_GROUP: "wood",S_GROUP:"果",S_CLASS: "双子叶植物纲",S_ORDER: "桃金娘目",S_FAMILY: "野牡丹科",TITLE: "野牡丹子",F_NAME: "guo01.jpg",},
{F_GROUP: "wood",S_GROUP:"果",S_CLASS: "双子叶植物纲",S_ORDER: "桃金娘目",S_FAMILY: "野牡丹科",TITLE: "朝天罐",F_NAME: "ctg01.jpg",},
{F_GROUP: "wood",S_GROUP:"果",S_CLASS: "双子叶植物纲",S_ORDER: "桃金娘目",S_FAMILY: "野牡丹科",TITLE: "朝天罐",F_NAME: "ctg02.jpg",},
{F_GROUP: "wood",S_GROUP:"果",S_CLASS: "双子叶植物纲",S_ORDER: "锦葵目",S_FAMILY: "木棉科",TITLE: "木棉麻雀",F_NAME: "mumianmaque.jpg",},
{F_GROUP: "wood",S_GROUP:"果",S_CLASS: "双子叶植物纲",S_ORDER: "锦葵目",S_FAMILY: "木棉科",TITLE: "美丽异木棉",F_NAME: "guo22.jpg",},
{F_GROUP: "wood",S_GROUP:"果",S_CLASS: "双子叶植物纲",S_ORDER: "荨麻目",S_FAMILY: "桑科",TITLE: "桑椹",F_NAME: "guo06.jpg",LINK: "drug/桑椹",},
{F_GROUP: "wood",S_GROUP:"果",S_CLASS: "双子叶植物纲",S_ORDER: "荨麻目",S_FAMILY: "桑科",TITLE: "桑椹1",F_NAME: "sang01.jpg",},
{F_GROUP: "wood",S_GROUP:"果",S_CLASS: "双子叶植物纲",S_ORDER: "荨麻目",S_FAMILY: "桑科",TITLE: "变叶榕",F_NAME: "guo20.jpg",},
{F_GROUP: "wood",S_GROUP:"果",S_CLASS: "双子叶植物纲",S_ORDER: "荨麻目",S_FAMILY: "桑科",TITLE: "绿黄葛树",F_NAME: "guo07.jpg",},
{F_GROUP: "wood",S_GROUP:"果",S_CLASS: "双子叶植物纲",S_ORDER: "大戟目",S_FAMILY: "大戟科",TITLE: "油桐",F_NAME: "youtong01.jpg",},
{F_GROUP: "wood",S_GROUP:"果",S_CLASS: "双子叶植物纲",S_ORDER: "大戟目",S_FAMILY: "大戟科",TITLE: "蓖麻",F_NAME: "bima02.jpg",},
{F_GROUP: "wood",S_GROUP:"果",S_CLASS: "双子叶植物纲",S_ORDER: "大戟目",S_FAMILY: "大戟科",TITLE: "白背叶",F_NAME: "bby01.jpg",},
{F_GROUP: "wood",S_GROUP:"果",S_CLASS: "双子叶植物纲",S_ORDER: "大戟目",S_FAMILY: "大戟科",TITLE: "白背叶2",F_NAME: "bby02.jpg",},
{F_GROUP: "wood",S_GROUP:"果",S_CLASS: "双子叶植物纲",S_ORDER: "蔷薇目",S_FAMILY: "蔷薇科",TITLE: "桃子",F_NAME: "tao.jpg",},
{F_GROUP: "wood",S_GROUP:"果",S_CLASS: "双子叶植物纲",S_ORDER: "蔷薇目",S_FAMILY: "蔷薇科",TITLE: "糖罐子",F_NAME: "tangguanzi.jpg",},
{F_GROUP: "wood",S_GROUP:"果",S_CLASS: "双子叶植物纲",S_ORDER: "蔷薇目",S_FAMILY: "蔷薇科",TITLE: "覆盆子1",F_NAME: "guo14.jpg",LINK: "drug/覆盆子",},
{F_GROUP: "wood",S_GROUP:"果",S_CLASS: "双子叶植物纲",S_ORDER: "蔷薇目",S_FAMILY: "蔷薇科",TITLE: "覆盆子2",F_NAME: "guo21.jpg",LINK: "drug/覆盆子",},
{F_GROUP: "wood",S_GROUP:"果",S_CLASS: "双子叶植物纲",S_ORDER: "蔷薇目",S_FAMILY: "蔷薇科",TITLE: "枇杷树",F_NAME: "pipashu01.jpg",LINK:"drug/枇杷叶",},
{F_GROUP: "wood",S_GROUP:"果",S_CLASS: "双子叶植物纲",S_ORDER: "蔷薇目",S_FAMILY: "蔷薇科",TITLE: "枇杷",F_NAME: "pipa01.jpg",},
{F_GROUP: "wood",S_GROUP:"果",S_CLASS: "双子叶植物纲",S_ORDER: "蔷薇目",S_FAMILY: "蔷薇科",TITLE: "红腺悬钩子",F_NAME: "guo04.jpg",},
{F_GROUP: "wood",S_GROUP:"果",S_CLASS: "双子叶植物纲",S_ORDER: "蔷薇目",S_FAMILY: "蔷薇科",TITLE: "红腺悬钩子青",F_NAME: "guo08.jpg",},
{F_GROUP: "wood",S_GROUP:"果",S_CLASS: "双子叶植物纲",S_ORDER: "蔷薇目",S_FAMILY: "豆科",TITLE: "槐角",F_NAME: "guo19.jpg",},
{F_GROUP: "wood",S_GROUP:"果",S_CLASS: "双子叶植物纲",S_ORDER: "蔷薇目",S_FAMILY: "豆科",TITLE: "朱缨花",F_NAME: "zying01.jpg",},
{F_GROUP: "wood",S_GROUP:"果",S_CLASS: "双子叶植物纲",S_ORDER: "蔷薇目",S_FAMILY: "豆科",TITLE: "合欢",F_NAME: "hehuan01.jpg",},
{F_GROUP: "wood",S_GROUP:"果",S_CLASS: "双子叶植物纲",S_ORDER: "蔷薇目",S_FAMILY: "豆科",TITLE: "决明",F_NAME: "jueming01.jpg",},
{F_GROUP: "wood",S_GROUP:"果",S_CLASS: "双子叶植物纲",S_ORDER: "蔷薇目",S_FAMILY: "豆科",TITLE: "黧豆",F_NAME: "lidou01.jpg",},
{F_GROUP: "wood",S_GROUP:"果",S_CLASS: "双子叶植物纲",S_ORDER: "蔷薇目",S_FAMILY: "豆科",TITLE: "尼泊尔黄花木",F_NAME: "dou01.jpg",},
{F_GROUP: "wood",S_GROUP:"果",S_CLASS: "双子叶植物纲",S_ORDER: "蔷薇目",S_FAMILY: "豆科",TITLE: "木豆",F_NAME: "mudou02.jpg",},
{F_GROUP: "wood",S_GROUP:"果",S_CLASS: "双子叶植物纲",S_ORDER: "蔷薇目",S_FAMILY: "豆科",TITLE: "酸豆",F_NAME: "suandou01.jpg",},
{F_GROUP: "wood",S_GROUP:"果",S_CLASS: "双子叶植物纲",S_ORDER: "蔷薇目",S_FAMILY: "豆科",TITLE: "扁豆",F_NAME: "biandou01.jpg",},
{F_GROUP: "wood",S_GROUP:"果",S_CLASS: "双子叶植物纲",S_ORDER: "蔷薇目",S_FAMILY: "豆科",TITLE: "鸡冠刺桐",F_NAME: "jgct01.jpg",},
{F_GROUP: "wood",S_GROUP:"果",S_CLASS: "双子叶植物纲",S_ORDER: "报春花目",S_FAMILY: "紫金牛科",TITLE: "朱砂根",F_NAME: "hongguo.jpg",},
{F_GROUP: "wood",S_GROUP:"果",S_CLASS: "双子叶植物纲",S_ORDER: "报春花目",S_FAMILY: "紫金牛科",TITLE: "紫金牛",F_NAME: "zjn01.jpg",},
{F_GROUP: "wood",S_GROUP:"果",S_CLASS: "双子叶植物纲",S_ORDER: "侧膜胎座目",S_FAMILY: "西番莲科",TITLE: "百香果",F_NAME: "lvguo.jpg",},
{F_GROUP: "wood",S_GROUP:"果",S_CLASS: "双子叶植物纲",S_ORDER: "侧膜胎座目",S_FAMILY: "番木瓜科",TITLE: "番木瓜",F_NAME: "fmg01.jpg",},
{F_GROUP: "wood",S_GROUP:"果",S_CLASS: "双子叶植物纲",S_ORDER: "侧膜胎座目",S_FAMILY: "番木瓜科",TITLE: "番木瓜",F_NAME: "fmg02.jpg",},
{F_GROUP: "wood",S_GROUP:"果",S_CLASS: "双子叶植物纲",S_ORDER: "无患子目",S_FAMILY: "漆树科",TITLE: "芒果",F_NAME: "guo10.jpg",},
{F_GROUP: "wood",S_GROUP:"果",S_CLASS: "双子叶植物纲",S_ORDER: "蓼目",S_FAMILY: "蓼科",TITLE: "杠板归彩果",F_NAME: "languo.jpg",},
{F_GROUP: "wood",S_GROUP:"果",S_CLASS: "双子叶植物纲",S_ORDER: "蓼目",S_FAMILY: "蓼科",TITLE: "杠板归蓝果",F_NAME: "kbg02.jpg",},
{F_GROUP: "wood",S_GROUP:"果",S_CLASS: "双子叶植物纲",S_ORDER: "中央种子目",S_FAMILY: "商陆科",TITLE: "垂序商陆",F_NAME: "guo02.jpg",},
{F_GROUP: "wood",S_GROUP:"果",S_CLASS: "双子叶植物纲",S_ORDER: "管状花目",S_FAMILY: "茄科",TITLE: "青辣椒",F_NAME: "lajiao01.jpg",LINK:"drug/辣椒",},
{F_GROUP: "wood",S_GROUP:"果",S_CLASS: "双子叶植物纲",S_ORDER: "管状花目",S_FAMILY: "茄科",TITLE: "龙葵1",F_NAME: "guo09.jpg",},
{F_GROUP: "wood",S_GROUP:"果",S_CLASS: "双子叶植物纲",S_ORDER: "管状花目",S_FAMILY: "茄科",TITLE: "龙葵2",F_NAME: "guo24.jpg",},
{F_GROUP: "wood",S_GROUP:"果",S_CLASS: "双子叶植物纲",S_ORDER: "管状花目",S_FAMILY: "茄科",TITLE: "乳茄",F_NAME: "ruqie01.jpg",},
{F_GROUP: "wood",S_GROUP:"果",S_CLASS: "双子叶植物纲",S_ORDER: "管状花目",S_FAMILY: "马鞭草科",TITLE: "假连翘",F_NAME: "guo23.jpg",},
{F_GROUP: "wood",S_GROUP:"果",S_CLASS: "双子叶植物纲",S_ORDER: "杨梅目",S_FAMILY: "杨梅科",TITLE: "青杨梅",F_NAME: "yangmei01.jpg",},
{F_GROUP: "wood",S_GROUP:"果",S_CLASS: "双子叶植物纲",S_ORDER: "杨梅目",S_FAMILY: "杨梅科",TITLE: "杨梅快熟了",F_NAME: "yangmei02.jpg",},
{F_GROUP: "wood",S_GROUP:"果",S_CLASS: "双子叶植物纲",S_ORDER: "葫芦目",S_FAMILY: "葫芦科",TITLE: "绿南瓜",F_NAME: "nangua01.jpg",},
{F_GROUP: "wood",S_GROUP:"果",S_CLASS: "双子叶植物纲",S_ORDER: "葫芦目",S_FAMILY: "葫芦科",TITLE: "丝瓜",F_NAME: "sigua01.jpg",},
{F_GROUP: "wood",S_GROUP:"果",S_CLASS: "双子叶植物纲",S_ORDER: "葫芦目",S_FAMILY: "葫芦科",TITLE: "冬瓜",F_NAME: "donggua01.jpg",},
{F_GROUP: "wood",S_GROUP:"果",S_CLASS: "双子叶植物纲",S_ORDER: "葫芦目",S_FAMILY: "葫芦科",TITLE: "西瓜",F_NAME: "xigua01.jpg",},
{F_GROUP: "wood",S_GROUP:"果",S_CLASS: "双子叶植物纲",S_ORDER: "芸香目",S_FAMILY: "芸香科",TITLE: "臭檀吴萸",F_NAME: "heixiaoguo01.jpg",},
{F_GROUP: "wood",S_GROUP:"果",S_CLASS: "双子叶植物纲",S_ORDER: "芸香目",S_FAMILY: "芸香科",TITLE: "青橘子",F_NAME: "juzi01.jpg",},
{F_GROUP: "wood",S_GROUP:"果",S_CLASS: "双子叶植物纲",S_ORDER: "芸香目",S_FAMILY: "芸香科",TITLE: "青橘子",F_NAME: "juzi02.jpg",},
{F_GROUP: "wood",S_GROUP:"果",S_CLASS: "双子叶植物纲",S_ORDER: "茜草目",S_FAMILY: "茜草科",TITLE: "鸡眼藤",F_NAME: "hongguo01.jpg",},
{F_GROUP: "wood",S_GROUP:"果",S_CLASS: "双子叶植物纲",S_ORDER: "毛茛目",S_FAMILY: "小檗科",TITLE: "南天竹",F_NAME: "ntzguo01.jpg",},
{F_GROUP: "wood",S_GROUP:"果",S_CLASS: "双子叶植物纲",S_ORDER: "胡椒目",S_FAMILY: "金粟兰科",TITLE: "草珊瑚",F_NAME: "caosh01.jpg",},
{F_GROUP: "wood",S_GROUP:"果",S_CLASS: "双子叶植物纲",S_ORDER: "毛茛目",S_FAMILY: "木通科",TITLE: "木通",F_NAME: "mutong01.jpg",},
{F_GROUP: "wood",S_GROUP:"果",S_CLASS: "双子叶植物纲",S_ORDER: "毛茛目",S_FAMILY: "木通科",TITLE: "木通2",F_NAME: "mutong02.jpg",},
{F_GROUP: "wood",S_GROUP:"果",S_CLASS: "双子叶植物纲",S_ORDER: "鼠李目",S_FAMILY: "葡萄科",TITLE: "广东蛇葡萄",F_NAME: "gdspt01.jpg",},
{F_GROUP: "wood",S_GROUP:"果",S_CLASS: "双子叶植物纲",S_ORDER: "捩花目",S_FAMILY: "马钱科",TITLE: "钩吻",F_NAME: "gw02.jpg",},
{F_GROUP: "wood",S_GROUP:"果",TITLE: "小绿团",F_NAME: "guo03.jpg",},
{F_GROUP: "wood",S_GROUP:"果",TITLE: "树小果绿",F_NAME: "guo11.jpg",},
{F_GROUP: "wood",S_GROUP:"果",TITLE: "树果绿椭小",F_NAME: "guo15.jpg",},
{F_GROUP: "wood",S_GROUP:"果",TITLE: "绿果有刺",F_NAME: "lgc01.jpg",},
{F_GROUP: "wood",S_GROUP:"果",TITLE: "草果绿圆小",F_NAME: "guo16.jpg",},
{F_GROUP: "wood",S_GROUP:"果",TITLE: "黑绿果尖",F_NAME: "guo25.jpg",},
{F_GROUP: "wood",S_GROUP:"果",TITLE: "红绿果小",F_NAME: "guo13.jpg",},
{F_GROUP: "wood",S_GROUP:"果",TITLE: "树果红紫绿圆小",F_NAME: "guo17.jpg",},
{F_GROUP: "wood",S_GROUP:"果",TITLE: "树果红绿圆小",F_NAME: "guo18.jpg",},
{F_GROUP: "wood",S_GROUP:"果",TITLE: "树红果小",F_NAME: "guo12.jpg",},
{F_GROUP: "wood",S_GROUP:"果",TITLE: "椭果红小",F_NAME: "tghx01.jpg",},
{F_GROUP: "wood",S_GROUP:"果",TITLE: "红果椭",F_NAME: "guo05.jpg",},
{F_GROUP: "wood",S_GROUP:"果",TITLE: "橙果小",F_NAME: "cgx01.jpg",},
{F_GROUP: "wood",S_GROUP:"果",TITLE: "白小珠",F_NAME: "baixiaozhu01.jpg",},
{F_GROUP: "wood",S_GROUP:"果",S_CLASS: "双子叶植物纲",TITLE: "怪果",F_NAME: "qgdc.jpg",F_DESC: "怪异的果",},
{F_GROUP: "wood",S_GROUP:"花",S_CLASS: "单子叶植物纲",S_ORDER: "百合目",S_FAMILY: "石蒜科",TITLE: "葱莲",F_NAME: "bai602.jpg",},
{F_GROUP: "wood",S_GROUP:"花",S_CLASS: "单子叶植物纲",S_ORDER: "百合目",S_FAMILY: "石蒜科",TITLE: "葱莲2",F_NAME: "bai6.jpg",},
{F_GROUP: "wood",S_GROUP:"花",S_CLASS: "单子叶植物纲",S_ORDER: "百合目",S_FAMILY: "石蒜科",TITLE: "彼岸花",F_NAME: "bianhua01.jpg",},
{F_GROUP: "wood",S_GROUP:"花",S_CLASS: "单子叶植物纲",S_ORDER: "百合目",S_FAMILY: "石蒜科",TITLE: "紫娇花",F_NAME: "sanyecao01.jpg",},
{F_GROUP: "wood",S_GROUP:"花",S_CLASS: "单子叶植物纲",S_ORDER: "百合目",S_FAMILY: "石蒜科",TITLE: "网球花",F_NAME: "wqh01.jpg",},
{F_GROUP: "wood",S_GROUP:"花",S_CLASS: "单子叶植物纲",S_ORDER: "百合目",S_FAMILY: "石蒜科",TITLE: "水鬼蕉",F_NAME: "sgj03.jpg",},
{F_GROUP: "wood",S_GROUP:"花",S_CLASS: "单子叶植物纲",S_ORDER: "百合目",S_FAMILY: "石蒜科",TITLE: "水鬼蕉",F_NAME: "sgj04.jpg",},
{F_GROUP: "wood",S_GROUP:"花",S_CLASS: "单子叶植物纲",S_ORDER: "百合目",S_FAMILY: "石蒜科",TITLE: "朱顶红",F_NAME: "zhudh01.jpg",},
{F_GROUP: "wood",S_GROUP:"花",S_CLASS: "单子叶植物纲",S_ORDER: "百合目",S_FAMILY: "百合科",TITLE: "萱草",F_NAME: "huacheng01.jpg",},
{F_GROUP: "wood",S_GROUP:"花",S_CLASS: "单子叶植物纲",S_ORDER: "百合目",S_FAMILY: "百合科",TITLE: "白缘龙舌兰",F_NAME: "lsl01.jpg",},
{F_GROUP: "wood",S_GROUP:"花",S_CLASS: "单子叶植物纲",S_ORDER: "百合目",S_FAMILY: "百合科",TITLE: "蓝蝶在韭菜花",F_NAME: "jiucaihua01.jpg",},
{F_GROUP: "wood",S_GROUP:"花",S_CLASS: "单子叶植物纲",S_ORDER: "天南星目",S_FAMILY: "天南星科",TITLE: "一把伞南星",F_NAME: "xiangjiao.jpg",},
{F_GROUP: "wood",S_GROUP:"花",S_CLASS: "单子叶植物纲",S_ORDER: "天南星目",S_FAMILY: "天南星科",TITLE: "花魔芋",F_NAME: "hmy01.jpg",},
{F_GROUP: "wood",S_GROUP:"花",S_CLASS: "单子叶植物纲",S_ORDER: "天南星目",S_FAMILY: "天南星科",TITLE: "白鹤芋",F_NAME: "bhy01.jpg",},
{F_GROUP: "wood",S_GROUP:"花",S_CLASS: "单子叶植物纲",S_ORDER: "芭蕉目",S_FAMILY: "美人蕉科",TITLE: "兰花美人蕉",F_NAME: "huanghua.jpg",},
{F_GROUP: "wood",S_GROUP:"花",S_CLASS: "单子叶植物纲",S_ORDER: "芭蕉目",S_FAMILY: "姜科",TITLE: "花叶艳山姜",F_NAME: "hyysj02.jpg",},
{F_GROUP: "wood",S_GROUP:"花",S_CLASS: "单子叶植物纲",S_ORDER: "禾本目",S_FAMILY: "禾本科",TITLE: "芒草花",F_NAME: "mangcao01.jpg",},
{F_GROUP: "wood",S_GROUP:"花",S_CLASS: "单子叶植物纲",S_ORDER: "禾本目",S_FAMILY: "禾本科",TITLE: "竹开花",F_NAME: "zhuhua01.jpg",},
{F_GROUP: "wood",S_GROUP:"花",S_CLASS: "单子叶植物纲",S_ORDER: "粉状胚乳目",S_FAMILY: "雨久花科",TITLE: "梭鱼草",F_NAME: "syc01.jpg",},
{F_GROUP: "wood",S_GROUP:"花",S_CLASS: "单子叶植物纲",S_ORDER: "粉状胚乳目",S_FAMILY: "雨久花科",TITLE: "凤眼蓝",F_NAME: "fyl01.jpg",},
{F_GROUP: "wood",S_GROUP:"花",S_CLASS: "单子叶植物纲",S_ORDER: "粉状胚乳目",S_FAMILY: "鸭跖草科",TITLE: "杜若",F_NAME: "bai5.jpg",},
{F_GROUP: "wood",S_GROUP:"花",S_CLASS: "单子叶植物纲",S_ORDER: "粉状胚乳目",S_FAMILY: "鸭跖草科",TITLE: "紫鸭跖草",F_NAME: "zyzc.jpg",},
{F_GROUP: "wood",S_GROUP:"花",S_CLASS: "单子叶植物纲",S_ORDER: "粉状胚乳目",S_FAMILY: "鸭跖草科",TITLE: "深蓝鸭跖草",F_NAME: "lyzc01.jpg",},
{F_GROUP: "wood",S_GROUP:"花",S_CLASS: "单子叶植物纲",S_ORDER: "粉状胚乳目",S_FAMILY: "鸭跖草科",TITLE: "水竹叶",F_NAME: "szy01.jpg",F_DESC: "具有清热解毒，利尿之功效。用于发热，咽喉肿痛，肺热咳喘，咳血，热淋，热痢，痈疖疔肿，蛇虫咬伤。",},
{F_GROUP: "wood",S_GROUP:"花",S_CLASS: "双子叶植物纲",S_ORDER: "捩花目",S_FAMILY: "木犀科",TITLE: "桂花",F_NAME: "guihua.jpg",LINK:"drug/桂枝",},
{F_GROUP: "wood",S_GROUP:"花",S_CLASS: "双子叶植物纲",S_ORDER: "捩花目",S_FAMILY: "木犀科",TITLE: "桂花橙",F_NAME: "guihua02.jpg",},
{F_GROUP: "wood",S_GROUP:"花",S_CLASS: "双子叶植物纲",S_ORDER: "捩花目",S_FAMILY: "夹竹桃科",TITLE: "红鸡蛋花1",F_NAME: "hjdh01.jpg",},
{F_GROUP: "wood",S_GROUP:"花",S_CLASS: "双子叶植物纲",S_ORDER: "捩花目",S_FAMILY: "夹竹桃科",TITLE: "红鸡蛋花2",F_NAME: "hjdh02.jpg",},
{F_GROUP: "wood",S_GROUP:"花",S_CLASS: "双子叶植物纲",S_ORDER: "捩花目",S_FAMILY: "夹竹桃科",TITLE: "夹竹桃",F_NAME: "jzt02.jpg",},
{F_GROUP: "wood",S_GROUP:"花",S_CLASS: "双子叶植物纲",S_ORDER: "捩花目",S_FAMILY: "夹竹桃科",TITLE: "黄花夹竹桃",F_NAME: "hhjzt01.jpg",},
{F_GROUP: "wood",S_GROUP:"花",S_CLASS: "双子叶植物纲",S_ORDER: "捩花目",S_FAMILY: "夹竹桃科",TITLE: "长春花",F_NAME: "cch01.jpg",},
{F_GROUP: "wood",S_GROUP:"花",S_CLASS: "双子叶植物纲",S_ORDER: "捩花目",S_FAMILY: "马钱科",TITLE: "钩吻",F_NAME: "gw01.jpg",},
{F_GROUP: "wood",S_GROUP:"花",S_CLASS: "双子叶植物纲",S_ORDER: "捩花目",S_FAMILY: "马钱科",TITLE: "白背枫",F_NAME: "bbf01.jpg",},
{F_GROUP: "wood",S_GROUP:"花",S_CLASS: "双子叶植物纲",S_ORDER: "中央种子目",S_FAMILY: "紫茉莉科",TITLE: "红三角梅",F_NAME: "hongsanjiao.jpg",},
{F_GROUP: "wood",S_GROUP:"花",S_CLASS: "双子叶植物纲",S_ORDER: "中央种子目",S_FAMILY: "紫茉莉科",TITLE: "紫三角梅",F_NAME: "sanjiao01.jpg",},
{F_GROUP: "wood",S_GROUP:"花",S_CLASS: "双子叶植物纲",S_ORDER: "中央种子目",S_FAMILY: "紫茉莉科",TITLE: "紫茉莉",F_NAME: "labahongzi01.jpg",},
{F_GROUP: "wood",S_GROUP:"花",S_CLASS: "双子叶植物纲",S_ORDER: "中央种子目",S_FAMILY: "苋科",TITLE: "鸡冠花",F_NAME: "jiguanhua01.jpg",},
{F_GROUP: "wood",S_GROUP:"花",S_CLASS: "双子叶植物纲",S_ORDER: "中央种子目",S_FAMILY: "苋科",TITLE: "青葙",F_NAME: "qingxiang01.jpg",},
{F_GROUP: "wood",S_GROUP:"花",S_CLASS: "双子叶植物纲",S_ORDER: "中央种子目",S_FAMILY: "苋科",TITLE: "莲子草",F_NAME: "lzc01.jpg",},
{F_GROUP: "wood",S_GROUP:"花",S_CLASS: "双子叶植物纲",S_ORDER: "中央种子目",S_FAMILY: "商陆科",TITLE: "垂序商陆",F_NAME: "shanglu01.jpg",},
{F_GROUP: "wood",S_GROUP:"花",S_CLASS: "双子叶植物纲",S_ORDER: "中央种子目",S_FAMILY: "石竹科",TITLE: "繁星石竹",F_NAME: "fxsz01.jpg",},
{F_GROUP: "wood",S_GROUP:"花",S_CLASS: "双子叶植物纲",S_ORDER: "中央种子目",S_FAMILY: "藜科",TITLE: "地肤",F_NAME: "difu01.jpg",},
{F_GROUP: "wood",S_GROUP:"花",S_CLASS: "双子叶植物纲",S_ORDER: "牻牛儿苗目",S_FAMILY: "凤仙花科",TITLE: "红凤仙",F_NAME: "fengxianhua.jpg",F_DESC: "别名：指甲花，急性子，凤仙透骨草",LINK:"drug/急性子",},
{F_GROUP: "wood",S_GROUP:"花",S_CLASS: "双子叶植物纲",S_ORDER: "牻牛儿苗目",S_FAMILY: "凤仙花科",TITLE: "粉凤仙",F_NAME: "fengxian02.jpg",LINK:"drug/急性子",},
{F_GROUP: "wood",S_GROUP:"花",S_CLASS: "双子叶植物纲",S_ORDER: "牻牛儿苗目",S_FAMILY: "酢浆草科",TITLE: "红花酢浆草",F_NAME: "cjc02.jpg",},
{F_GROUP: "wood",S_GROUP:"花",S_CLASS: "双子叶植物纲",S_ORDER: "牻牛儿苗目",S_FAMILY: "牻牛儿苗科",TITLE: "野老鹳草",F_NAME: "ylhc01.jpg",},
{F_GROUP: "wood",S_GROUP:"花",S_CLASS: "双子叶植物纲",S_ORDER: "牻牛儿苗目",S_FAMILY: "牻牛儿苗科",TITLE: "野老鹳草",F_NAME: "ylhc02.jpg",},
{F_GROUP: "wood",S_GROUP:"花",S_CLASS: "双子叶植物纲",S_ORDER: "管状花目",S_FAMILY: "马鞭草科",TITLE: "臭牡丹",F_NAME: "choumudan01.jpg",},
{F_GROUP: "wood",S_GROUP:"花",S_CLASS: "双子叶植物纲",S_ORDER: "管状花目",S_FAMILY: "马鞭草科",TITLE: "臭牡丹粉",F_NAME: "choumudan02.jpg",},
{F_GROUP: "wood",S_GROUP:"花",S_CLASS: "双子叶植物纲",S_ORDER: "管状花目",S_FAMILY: "马鞭草科",TITLE: "臭牡丹3",F_NAME: "choumudan03.jpg",},
{F_GROUP: "wood",S_GROUP:"花",S_CLASS: "双子叶植物纲",S_ORDER: "管状花目",S_FAMILY: "马鞭草科",TITLE: "杜虹花",F_NAME: "duhonghua01.jpg",},
{F_GROUP: "wood",S_GROUP:"花",S_CLASS: "双子叶植物纲",S_ORDER: "管状花目",S_FAMILY: "马鞭草科",TITLE: "红黄马缨丹",F_NAME: "myd01.jpg",},
{F_GROUP: "wood",S_GROUP:"花",S_CLASS: "双子叶植物纲",S_ORDER: "管状花目",S_FAMILY: "马鞭草科",TITLE: "紫马缨丹",F_NAME: "zihua.jpg",},
{F_GROUP: "wood",S_GROUP:"花",S_CLASS: "双子叶植物纲",S_ORDER: "管状花目",S_FAMILY: "马鞭草科",TITLE: "柳叶马鞭草",F_NAME: "mbc01.jpg",},
{F_GROUP: "wood",S_GROUP:"花",S_CLASS: "双子叶植物纲",S_ORDER: "管状花目",S_FAMILY: "马鞭草科",TITLE: "赪桐",F_NAME: "honghua01.jpg",},
{F_GROUP: "wood",S_GROUP:"花",S_CLASS: "双子叶植物纲",S_ORDER: "管状花目",S_FAMILY: "马鞭草科",TITLE: "枇杷叶紫珠",F_NAME: "ppyzz02.jpg",},
{F_GROUP: "wood",S_GROUP:"花",S_CLASS: "双子叶植物纲",S_ORDER: "管状花目",S_FAMILY: "旋花科",TITLE: "牵牛花",F_NAME: "qianniuhua02.jpg",LINK:"drug/牵牛子",},
{F_GROUP: "wood",S_GROUP:"花",S_CLASS: "双子叶植物纲",S_ORDER: "管状花目",S_FAMILY: "旋花科",TITLE: "牵牛果",F_NAME: "qianniuguo01.jpg",LINK:"drug/牵牛子",},
{F_GROUP: "wood",S_GROUP:"花",S_CLASS: "双子叶植物纲",S_ORDER: "管状花目",S_FAMILY: "旋花科",TITLE: "牵牛花蓝",F_NAME: "qianniuhua01.jpg",},
{F_GROUP: "wood",S_GROUP:"花",S_CLASS: "双子叶植物纲",S_ORDER: "管状花目",S_FAMILY: "旋花科",TITLE: "牵牛花紫",F_NAME: "qianniuhua03.jpg",},
{F_GROUP: "wood",S_GROUP:"花",S_CLASS: "双子叶植物纲",S_ORDER: "管状花目",S_FAMILY: "旋花科",TITLE: "茑萝",F_NAME: "niaoluo.jpg",F_DESC: "茑与女萝，施于松柏",},
{F_GROUP: "wood",S_GROUP:"花",S_CLASS: "双子叶植物纲",S_ORDER: "管状花目",S_FAMILY: "旋花科",TITLE: "茑萝雨",F_NAME: "niaoluo01.jpg",F_DESC: "茑与女萝，施于松柏",},
{F_GROUP: "wood",S_GROUP:"花",S_CLASS: "双子叶植物纲",S_ORDER: "管状花目",S_FAMILY: "旋花科",TITLE: "土丁桂",F_NAME: "tudinggui.jpg",F_DESC: "别名过饥草、小鹿衔。长于灌丛，起于路边",},
{F_GROUP: "wood",S_GROUP:"花",S_CLASS: "双子叶植物纲",S_ORDER: "管状花目",S_FAMILY: "旋花科",TITLE: "打碗花",F_NAME: "labahua01.jpg",},
{F_GROUP: "wood",S_GROUP:"花",S_CLASS: "双子叶植物纲",S_ORDER: "管状花目",S_FAMILY: "旋花科",TITLE: "毛牵牛",F_NAME: "baihua01.jpg",},
{F_GROUP: "wood",S_GROUP:"花",S_CLASS: "双子叶植物纲",S_ORDER: "管状花目",S_FAMILY: "玄参科",TITLE: "毛叶蝴蝶草",F_NAME: "lanhua01.jpg",},
{F_GROUP: "wood",S_GROUP:"花",S_CLASS: "双子叶植物纲",S_ORDER: "管状花目",S_FAMILY: "玄参科",TITLE: "兰猪耳",F_NAME: "lze01.jpg",},
{F_GROUP: "wood",S_GROUP:"花",S_CLASS: "双子叶植物纲",S_ORDER: "管状花目",S_FAMILY: "爵床科",TITLE: "爵床花",F_NAME: "huozi02.jpg",},
{F_GROUP: "wood",S_GROUP:"花",S_CLASS: "双子叶植物纲",S_ORDER: "管状花目",S_FAMILY: "爵床科",TITLE: "蓝花草",F_NAME: "lhc01.jpg",},
{F_GROUP: "wood",S_GROUP:"花",S_CLASS: "双子叶植物纲",S_ORDER: "管状花目",S_FAMILY: "爵床科",TITLE: "蓝花草",F_NAME: "lhc02.jpg",},
{F_GROUP: "wood",S_GROUP:"花",S_CLASS: "双子叶植物纲",S_ORDER: "管状花目",S_FAMILY: "唇形科",TITLE: "蓝花鼠尾草",F_NAME: "lhswc01.jpg",},
{F_GROUP: "wood",S_GROUP:"花",S_CLASS: "双子叶植物纲",S_ORDER: "管状花目",S_FAMILY: "唇形科",TITLE: "蓝花鼠尾草",F_NAME: "lhswc02.jpg",},
{F_GROUP: "wood",S_GROUP:"花",S_CLASS: "双子叶植物纲",S_ORDER: "管状花目",S_FAMILY: "唇形科",TITLE: "益母草",F_NAME: "fenhua03.jpg",LINK:"drug/益母草",},
{F_GROUP: "wood",S_GROUP:"花",S_CLASS: "双子叶植物纲",S_ORDER: "管状花目",S_FAMILY: "唇形科",TITLE: "益母草全",F_NAME: "fenhua04.jpg",LINK:"drug/益母草",},
{F_GROUP: "wood",S_GROUP:"花",S_CLASS: "双子叶植物纲",S_ORDER: "管状花目",S_FAMILY: "茄科",TITLE: "假酸浆",F_NAME: "lanzi01.jpg",},
{F_GROUP: "wood",S_GROUP:"花",S_CLASS: "双子叶植物纲",S_ORDER: "管状花目",S_FAMILY: "茄科",TITLE: "喀西茄",F_NAME: "kxq01.jpg",},
{F_GROUP: "wood",S_GROUP:"花",S_CLASS: "双子叶植物纲",S_ORDER: "管状花目",S_FAMILY: "茄科",TITLE: "曼陀罗",F_NAME: "mantuoluo.jpg",F_DESC: "曼陀罗花又叫洋金花、大喇叭花、山茄子，夕颜，果实名为：狗核桃、毛苹果原产印度，花期5－9月，果期6－10月，喜温暖、向阳及排水良好的砂质壤土。多野生在田间、沟旁、道边、河岸、山坡等地方，主要危害棉花、豆类、薯类、蔬菜等，有剧毒。",},
{F_GROUP: "wood",S_GROUP:"花",S_CLASS: "双子叶植物纲",S_ORDER: "管状花目",S_FAMILY: "茄科",TITLE: "龙葵",F_NAME: "huangbaihua01.jpg",},
{F_GROUP: "wood",S_GROUP:"花",S_CLASS: "双子叶植物纲",S_ORDER: "管状花目",S_FAMILY: "列当科",TITLE: "野菰",F_NAME: "yegu01.jpg",F_DESC: "具有清热解毒之功效。用于咽喉肿痛，咳嗽，小儿高热，尿路感染，骨髓炎，毒蛇咬伤，疔疮。",},
{F_GROUP: "wood",S_GROUP:"花",S_CLASS: "双子叶植物纲",S_ORDER: "桔梗目",S_FAMILY: "菊科",TITLE: "黄秋英",F_NAME: "chenghua01.jpg",},
{F_GROUP: "wood",S_GROUP:"花",S_CLASS: "双子叶植物纲",S_ORDER: "桔梗目",S_FAMILY: "菊科",TITLE: "黄秋英2",F_NAME: "huanghuaduo.jpg",},
{F_GROUP: "wood",S_GROUP:"花",S_CLASS: "双子叶植物纲",S_ORDER: "桔梗目",S_FAMILY: "菊科",TITLE: "粉秋英",F_NAME: "fenhua02.jpg",},
{F_GROUP: "wood",S_GROUP:"花",S_CLASS: "双子叶植物纲",S_ORDER: "桔梗目",S_FAMILY: "菊科",TITLE: "黄鹌菜",F_NAME: "yejuhua01.jpg",},
{F_GROUP: "wood",S_GROUP:"花",S_CLASS: "双子叶植物纲",S_ORDER: "桔梗目",S_FAMILY: "菊科",TITLE: "黄鹌菜",F_NAME: "yejuhua02.jpg",},
{F_GROUP: "wood",S_GROUP:"花",S_CLASS: "双子叶植物纲",S_ORDER: "桔梗目",S_FAMILY: "菊科",TITLE: "粉色百日菊",F_NAME: "fenhua.jpg",},
{F_GROUP: "wood",S_GROUP:"花",S_CLASS: "双子叶植物纲",S_ORDER: "桔梗目",S_FAMILY: "菊科",TITLE: "重瓣粉色百日菊",F_NAME: "juhua03.jpg",},
{F_GROUP: "wood",S_GROUP:"花",S_CLASS: "双子叶植物纲",S_ORDER: "桔梗目",S_FAMILY: "菊科",TITLE: "重瓣紫色百日菊",F_NAME: "juhua01.jpg",},
{F_GROUP: "wood",S_GROUP:"花",S_CLASS: "双子叶植物纲",S_ORDER: "桔梗目",S_FAMILY: "菊科",TITLE: "万寿菊",F_NAME: "juhua02.jpg",},
{F_GROUP: "wood",S_GROUP:"花",S_CLASS: "双子叶植物纲",S_ORDER: "桔梗目",S_FAMILY: "菊科",TITLE: "马兰",F_NAME: "malan01.jpg",},
{F_GROUP: "wood",S_GROUP:"花",S_CLASS: "双子叶植物纲",S_ORDER: "桔梗目",S_FAMILY: "菊科",TITLE: "蒲公英",F_NAME: "pugongying2.jpg",LINK:"drug/蒲公英",},
{F_GROUP: "wood",S_GROUP:"花",S_CLASS: "双子叶植物纲",S_ORDER: "桔梗目",S_FAMILY: "菊科",TITLE: "一点红",F_NAME: "pugongying4.jpg",},
{F_GROUP: "wood",S_GROUP:"花",S_CLASS: "双子叶植物纲",S_ORDER: "桔梗目",S_FAMILY: "菊科",TITLE: "一点红小",F_NAME: "pugongying5.jpg",},
{F_GROUP: "wood",S_GROUP:"花",S_CLASS: "双子叶植物纲",S_ORDER: "桔梗目",S_FAMILY: "菊科",TITLE: "小蓬草",F_NAME: "xiaopeng01.jpg",},
{F_GROUP: "wood",S_GROUP:"花",S_CLASS: "双子叶植物纲",S_ORDER: "桔梗目",S_FAMILY: "菊科",TITLE: "南美蟛蜞菊",F_NAME: "yejuhua.jpg",},
{F_GROUP: "wood",S_GROUP:"花",S_CLASS: "双子叶植物纲",S_ORDER: "桔梗目",S_FAMILY: "菊科",TITLE: "鳢肠",F_NAME: "yejubai.jpg",LINK:"drug/野菊花",},
{F_GROUP: "wood",S_GROUP:"花",S_CLASS: "双子叶植物纲",S_ORDER: "桔梗目",S_FAMILY: "菊科",TITLE: "鳢肠",F_NAME: "lichang01.jpg",},
{F_GROUP: "wood",S_GROUP:"花",S_CLASS: "双子叶植物纲",S_ORDER: "桔梗目",S_FAMILY: "菊科",TITLE: "三脉紫菀",F_NAME: "yejubai2.jpg",},
{F_GROUP: "wood",S_GROUP:"花",S_CLASS: "双子叶植物纲",S_ORDER: "桔梗目",S_FAMILY: "菊科",TITLE: "一年蓬",F_NAME: "yinianpeng01.jpg",},
{F_GROUP: "wood",S_GROUP:"花",S_CLASS: "双子叶植物纲",S_ORDER: "桔梗目",S_FAMILY: "菊科",TITLE: "金钮扣",F_NAME: "jinniukou01.jpg",},
{F_GROUP: "wood",S_GROUP:"花",S_CLASS: "双子叶植物纲",S_ORDER: "桔梗目",S_FAMILY: "菊科",TITLE: "钻叶紫菀",F_NAME: "zyzw01.jpg",},
{F_GROUP: "wood",S_GROUP:"花",S_CLASS: "双子叶植物纲",S_ORDER: "桔梗目",S_FAMILY: "菊科",TITLE: "假臭草花",F_NAME: "jccao02.jpg",},
{F_GROUP: "wood",S_GROUP:"花",S_CLASS: "双子叶植物纲",S_ORDER: "桔梗目",S_FAMILY: "菊科",TITLE: "雪叶菊",F_NAME: "xyj01.jpg",},
{F_GROUP: "wood",S_GROUP:"花",S_CLASS: "双子叶植物纲",S_ORDER: "毛茛目",TITLE: "灵隐寺莲",F_NAME: "lianhua02.jpg",},
{F_GROUP: "wood",S_GROUP:"花",S_CLASS: "双子叶植物纲",S_ORDER: "毛茛目",S_FAMILY: "睡莲科",TITLE: "睡莲",F_NAME: "112.jpg",},
{F_GROUP: "wood",S_GROUP:"花",S_CLASS: "双子叶植物纲",S_ORDER: "毛茛目",TITLE: "莲蓬",F_NAME: "lianpeng01.jpg",LINK:"drug/莲子",},
{F_GROUP: "wood",S_GROUP:"花",S_CLASS: "双子叶植物纲",S_ORDER: "毛茛目",S_FAMILY: "睡莲科",TITLE: "荷花",F_NAME: "hehua.jpg",},
{F_GROUP: "wood",S_GROUP:"花",S_CLASS: "双子叶植物纲",S_ORDER: "毛茛目",S_FAMILY: "小檗科",TITLE: "南天竹",F_NAME: "baihuaxiao.jpg",},
{F_GROUP: "wood",S_GROUP:"花",S_CLASS: "双子叶植物纲",S_ORDER: "毛茛目",S_FAMILY: "毛茛科",TITLE: "茴茴蒜1",F_NAME: "hhs01.jpg",},
{F_GROUP: "wood",S_GROUP:"花",S_CLASS: "双子叶植物纲",S_ORDER: "毛茛目",S_FAMILY: "毛茛科",TITLE: "茴茴蒜2",F_NAME: "hhs02.jpg",},
{F_GROUP: "wood",S_GROUP:"花",S_CLASS: "双子叶植物纲",S_ORDER: "桃金娘目",S_FAMILY: "石榴科",TITLE: "石榴2",F_NAME: "shiliuhua.jpg",F_DESC: "石榴花",LINK:"drug/石榴皮",},
{F_GROUP: "wood",S_GROUP:"花",S_CLASS: "双子叶植物纲",S_ORDER: "桃金娘目",S_FAMILY: "石榴科",TITLE: "石榴1",F_NAME: "shiliuhua01.jpg",},
{F_GROUP: "wood",S_GROUP:"花",S_CLASS: "双子叶植物纲",S_ORDER: "桃金娘目",S_FAMILY: "野牡丹科",TITLE: "地菍",F_NAME: "fen6.jpg",},
{F_GROUP: "wood",S_GROUP:"花",S_CLASS: "双子叶植物纲",S_ORDER: "桃金娘目",S_FAMILY: "野牡丹科",TITLE: "巴西野牡丹",F_NAME: "bxymd01.jpg",},
{F_GROUP: "wood",S_GROUP:"花",S_CLASS: "双子叶植物纲",S_ORDER: "桃金娘目",S_FAMILY: "野牡丹科",TITLE: "巴西野牡丹",F_NAME: "bxymd02.jpg",},
{F_GROUP: "wood",S_GROUP:"花",S_CLASS: "双子叶植物纲",S_ORDER: "桃金娘目",S_FAMILY: "柳叶菜科",TITLE: "月见草",F_NAME: "yjc01.jpg",},
{F_GROUP: "wood",S_GROUP:"花",S_CLASS: "双子叶植物纲",S_ORDER: "桃金娘目",S_FAMILY: "柳叶菜科",TITLE: "月见草2",F_NAME: "yjc02.jpg",},
{F_GROUP: "wood",S_GROUP:"花",S_CLASS: "双子叶植物纲",S_ORDER: "桃金娘目",S_FAMILY: "柳叶菜科",TITLE: "毛草龙",F_NAME: "mcl01.jpg",},
{F_GROUP: "wood",S_GROUP:"花",S_CLASS: "双子叶植物纲",S_ORDER: "桃金娘目",S_FAMILY: "千屈菜科",TITLE: "千屈菜",F_NAME: "qqc01.jpg",},
{F_GROUP: "wood",S_GROUP:"花",S_CLASS: "双子叶植物纲",S_ORDER: "桃金娘目",S_FAMILY: "千屈菜科",TITLE: "银薇",F_NAME: "yw01.jpg",},
{F_GROUP: "wood",S_GROUP:"花",S_CLASS: "双子叶植物纲",S_ORDER: "桃金娘目",S_FAMILY: "千屈菜科",TITLE: "紫薇1",F_NAME: "zw01.jpg",},
{F_GROUP: "wood",S_GROUP:"花",S_CLASS: "双子叶植物纲",S_ORDER: "桃金娘目",S_FAMILY: "千屈菜科",TITLE: "紫薇2",F_NAME: "zw02.jpg",},
{F_GROUP: "wood",S_GROUP:"花",S_CLASS: "双子叶植物纲",S_ORDER: "桃金娘目",S_FAMILY: "桃金娘科",TITLE: "桃金娘",F_NAME: "tjn01.jpg",},
{F_GROUP: "wood",S_GROUP:"花",S_CLASS: "双子叶植物纲",S_ORDER: "蔷薇目",S_FAMILY: "豆科",TITLE: "豌豆花",F_NAME: "wandou.jpg",F_DESC: "豌豆（学名：Pisum sativum Linn），一年生攀援草本，高0.5-2米。花期6-7月，果期7-9月。",},
{F_GROUP: "wood",S_GROUP:"花",S_CLASS: "双子叶植物纲",S_ORDER: "蔷薇目",S_FAMILY: "豆科",TITLE: "鸡冠刺桐",F_NAME: "hua01.jpg",},
{F_GROUP: "wood",S_GROUP:"花",S_CLASS: "双子叶植物纲",S_ORDER: "蔷薇目",S_FAMILY: "豆科",TITLE: "木蓝1",F_NAME: "mulan01.jpg",},
{F_GROUP: "wood",S_GROUP:"花",S_CLASS: "双子叶植物纲",S_ORDER: "蔷薇目",S_FAMILY: "豆科",TITLE: "木蓝2",F_NAME: "mulan02.jpg",},
{F_GROUP: "wood",S_GROUP:"花",S_CLASS: "双子叶植物纲",S_ORDER: "蔷薇目",S_FAMILY: "豆科",TITLE: "木蓝2",F_NAME: "mulan03.jpg",},
{F_GROUP: "wood",S_GROUP:"花",S_CLASS: "双子叶植物纲",S_ORDER: "蔷薇目",S_FAMILY: "豆科",TITLE: "银合欢",F_NAME: "yhh01.jpg",},
{F_GROUP: "wood",S_GROUP:"花",S_CLASS: "双子叶植物纲",S_ORDER: "蔷薇目",S_FAMILY: "豆科",TITLE: "银合欢2",F_NAME: "yhh02.jpg",},
{F_GROUP: "wood",S_GROUP:"花",S_CLASS: "双子叶植物纲",S_ORDER: "蔷薇目",S_FAMILY: "豆科",TITLE: "凤凰花",F_NAME: "fenghuang.jpg",},
{F_GROUP: "wood",S_GROUP:"花",S_CLASS: "双子叶植物纲",S_ORDER: "蔷薇目",S_FAMILY: "豆科",TITLE: "红花羊蹄甲",F_NAME: "hhytj01.jpg",},
{F_GROUP: "wood",S_GROUP:"花",S_CLASS: "双子叶植物纲",S_ORDER: "蔷薇目",S_FAMILY: "豆科",TITLE: "白灰毛豆",F_NAME: "bhmd01.jpg",},
{F_GROUP: "wood",S_GROUP:"花",S_CLASS: "双子叶植物纲",S_ORDER: "蔷薇目",S_FAMILY: "豆科",TITLE: "木豆1",F_NAME: "mudou01.jpg",},
{F_GROUP: "wood",S_GROUP:"花",S_CLASS: "双子叶植物纲",S_ORDER: "蔷薇目",S_FAMILY: "豆科",TITLE: "木豆3",F_NAME: "mudou03.jpg",},
{F_GROUP: "wood",S_GROUP:"花",S_CLASS: "双子叶植物纲",S_ORDER: "蔷薇目",S_FAMILY: "豆科",TITLE: "葛",F_NAME: "ge01.jpg",},
{F_GROUP: "wood",S_GROUP:"花",S_CLASS: "双子叶植物纲",S_ORDER: "蔷薇目",S_FAMILY: "豆科",TITLE: "白车轴草",F_NAME: "bczc01.jpg",},
{F_GROUP: "wood",S_GROUP:"花",S_CLASS: "双子叶植物纲",S_ORDER: "蔷薇目",S_FAMILY: "豆科",TITLE: "首冠藤1",F_NAME: "sgt01.jpg",},
{F_GROUP: "wood",S_GROUP:"花",S_CLASS: "双子叶植物纲",S_ORDER: "蔷薇目",S_FAMILY: "豆科",TITLE: "首冠藤2",F_NAME: "sgt02.jpg",},
{F_GROUP: "wood",S_GROUP:"花",S_CLASS: "双子叶植物纲",S_ORDER: "蔷薇目",S_FAMILY: "蔷薇科",TITLE: "石斑木",F_NAME: "shanhua.jpg",},
{F_GROUP: "wood",S_GROUP:"花",S_CLASS: "双子叶植物纲",S_ORDER: "蔷薇目",S_FAMILY: "蔷薇科",TITLE: "石斑木1",F_NAME: "sbm01.jpg",},
{F_GROUP: "wood",S_GROUP:"花",S_CLASS: "双子叶植物纲",S_ORDER: "蔷薇目",S_FAMILY: "蔷薇科",TITLE: "桃花",F_NAME: "taohua.jpg",LINK:"drug/桃枝",},
{F_GROUP: "wood",S_GROUP:"花",S_CLASS: "双子叶植物纲",S_ORDER: "蔷薇目",S_FAMILY: "蔷薇科",TITLE: "黄月季",F_NAME: "hyj01.jpg",},
{F_GROUP: "wood",S_GROUP:"花",S_CLASS: "双子叶植物纲",S_ORDER: "蔷薇目",S_FAMILY: "蔷薇科",TITLE: "月季",F_NAME: "yueji01.jpg",},
{F_GROUP: "wood",S_GROUP:"花",S_CLASS: "双子叶植物纲",S_ORDER: "蔷薇目",S_FAMILY: "蔷薇科",TITLE: "梅花",F_NAME: "meihua02.jpg",},
{F_GROUP: "wood",S_GROUP:"花",S_CLASS: "双子叶植物纲",S_ORDER: "蔷薇目",S_FAMILY: "蔷薇科",TITLE: "梅",F_NAME: "zhibai01.jpg",},
{F_GROUP: "wood",S_GROUP:"花",S_CLASS: "双子叶植物纲",S_ORDER: "蔷薇目",S_FAMILY: "蔷薇科",TITLE: "梅或杏或李",F_NAME: "meihua01.jpg",},
{F_GROUP: "wood",S_GROUP:"花",S_CLASS: "双子叶植物纲",S_ORDER: "蔷薇目",S_FAMILY: "蔷薇科",TITLE: "石楠",F_NAME: "sn01.jpg",},
{F_GROUP: "wood",S_GROUP:"花",S_CLASS: "双子叶植物纲",S_ORDER: "蔷薇目",S_FAMILY: "蔷薇科",TITLE: "椤木石楠",F_NAME: "lmsn01.jpg",},
{F_GROUP: "wood",S_GROUP:"花",S_CLASS: "双子叶植物纲",S_ORDER: "蔷薇目",S_FAMILY: "蔷薇科",TITLE: "关山樱",F_NAME: "gsy01.jpg",},
{F_GROUP: "wood",S_GROUP:"花",S_CLASS: "双子叶植物纲",S_ORDER: "蔷薇目",S_FAMILY: "蔷薇科",TITLE: "日本晚樱",F_NAME: "rbwy01.jpg",},
{F_GROUP: "wood",S_GROUP:"花",S_CLASS: "双子叶植物纲",S_ORDER: "蔷薇目",S_FAMILY: "蔷薇科",TITLE: "白樱花",F_NAME: "ying01.jpg",},
{F_GROUP: "wood",S_GROUP:"花",S_CLASS: "双子叶植物纲",S_ORDER: "蔷薇目",S_FAMILY: "蔷薇科",TITLE: "樱桃",F_NAME: "yingtao01.jpg",},
{F_GROUP: "wood",S_GROUP:"花",S_CLASS: "双子叶植物纲",S_ORDER: "罂粟目",S_FAMILY: "罂粟科",TITLE: "野罂粟",F_NAME: "yingsu01.jpg",},
{F_GROUP: "wood",S_GROUP:"花",S_CLASS: "双子叶植物纲",S_ORDER: "罂粟目",S_FAMILY: "罂粟科",TITLE: "北越紫堇",F_NAME: "byzj01.jpg",},
{F_GROUP: "wood",S_GROUP:"花",S_CLASS: "双子叶植物纲",S_ORDER: "罂粟目",S_FAMILY: "山柑科",TITLE: "醉蝶花",F_NAME: "zdh01.jpg",},
{F_GROUP: "wood",S_GROUP:"花",S_CLASS: "双子叶植物纲",S_ORDER: "罂粟目",S_FAMILY: "十字花科",TITLE: "油菜花1",F_NAME: "youcaihua01.jpg",},
{F_GROUP: "wood",S_GROUP:"花",S_CLASS: "双子叶植物纲",S_ORDER: "罂粟目",S_FAMILY: "十字花科",TITLE: "油菜花2",F_NAME: "youcaihua02.jpg",},
{F_GROUP: "wood",S_GROUP:"花",S_CLASS: "双子叶植物纲",S_ORDER: "罂粟目",S_FAMILY: "十字花科",TITLE: "花旗杆",F_NAME: "hqg01.jpg",},
{F_GROUP: "wood",S_GROUP:"花",S_CLASS: "双子叶植物纲",S_ORDER: "伞形目",S_FAMILY: "伞形科",TITLE: "蛇床",F_NAME: "bai52.jpg",},
{F_GROUP: "wood",S_GROUP:"花",S_CLASS: "双子叶植物纲",S_ORDER: "杜鹃花目",S_FAMILY: "杜鹃花科",TITLE: "杜鹃花3",F_NAME: "zihua2.jpg",},
{F_GROUP: "wood",S_GROUP:"花",S_CLASS: "双子叶植物纲",S_ORDER: "杜鹃花目",S_FAMILY: "杜鹃花科",TITLE: "杜鹃花2",F_NAME: "fenhua01.jpg",},
{F_GROUP: "wood",S_GROUP:"花",S_CLASS: "双子叶植物纲",S_ORDER: "杜鹃花目",S_FAMILY: "杜鹃花科",TITLE: "杜鹃花4",F_NAME: "dujuan04.jpg",},
{F_GROUP: "wood",S_GROUP:"花",S_CLASS: "双子叶植物纲",S_ORDER: "杜鹃花目",S_FAMILY: "杜鹃花科",TITLE: "粉杜鹃",F_NAME: "dujuan01.jpg",},
{F_GROUP: "wood",S_GROUP:"花",S_CLASS: "双子叶植物纲",S_ORDER: "杜鹃花目",S_FAMILY: "杜鹃花科",TITLE: "映山红",F_NAME: "dujuan02.jpg",},
{F_GROUP: "wood",S_GROUP:"花",S_CLASS: "双子叶植物纲",S_ORDER: "杜鹃花目",S_FAMILY: "山茶科",TITLE: "白山茶花",F_NAME: "shancha01.jpg",},
{F_GROUP: "wood",S_GROUP:"花",S_CLASS: "双子叶植物纲",S_ORDER: "杜鹃花目",S_FAMILY: "山茶科",TITLE: "油茶",F_NAME: "youcha01.jpg",},
{F_GROUP: "wood",S_GROUP:"花",S_CLASS: "双子叶植物纲",S_ORDER: "杜鹃花目",S_FAMILY: "山茶科",TITLE: "山茶",F_NAME: "shancha02.jpg",},
{F_GROUP: "wood",S_GROUP:"花",S_CLASS: "双子叶植物纲",S_ORDER: "蓼目",S_FAMILY: "蓼科",TITLE: "长鬃蓼",F_NAME: "huozi03.jpg",},
{F_GROUP: "wood",S_GROUP:"花",S_CLASS: "双子叶植物纲",S_ORDER: "蓼目",S_FAMILY: "蓼科",TITLE: "火炭母",F_NAME: "htm01.jpg",},
{F_GROUP: "wood",S_GROUP:"花",S_CLASS: "双子叶植物纲",S_ORDER: "锦葵目",S_FAMILY: "锦葵科",TITLE: "朱槿",F_NAME: "huarui01.jpg",},
{F_GROUP: "wood",S_GROUP:"花",S_CLASS: "双子叶植物纲",S_ORDER: "锦葵目",S_FAMILY: "锦葵科",TITLE: "朱槿2",F_NAME: "zhujin01.jpg",},
{F_GROUP: "wood",S_GROUP:"花",S_CLASS: "双子叶植物纲",S_ORDER: "锦葵目",S_FAMILY: "锦葵科",TITLE: "木槿",F_NAME: "mujin01.jpg",},
{F_GROUP: "wood",S_GROUP:"花",S_CLASS: "双子叶植物纲",S_ORDER: "锦葵目",S_FAMILY: "锦葵科",TITLE: "木芙蓉",F_NAME: "mufurong01.jpg",},
{F_GROUP: "wood",S_GROUP:"花",S_CLASS: "双子叶植物纲",S_ORDER: "锦葵目",S_FAMILY: "锦葵科",TITLE: "木芙蓉",F_NAME: "mufurong02.jpg",},
{F_GROUP: "wood",S_GROUP:"花",S_CLASS: "双子叶植物纲",S_ORDER: "锦葵目",S_FAMILY: "锦葵科",TITLE: "蜀葵",F_NAME: "shukui01.jpg",},
{F_GROUP: "wood",S_GROUP:"花",S_CLASS: "双子叶植物纲",S_ORDER: "锦葵目",S_FAMILY: "锦葵科",TITLE: "赛葵1",F_NAME: "saikui01.jpg",},
{F_GROUP: "wood",S_GROUP:"花",S_CLASS: "双子叶植物纲",S_ORDER: "锦葵目",S_FAMILY: "锦葵科",TITLE: "赛葵2",F_NAME: "saikui02.jpg",},
{F_GROUP: "wood",S_GROUP:"花",S_CLASS: "双子叶植物纲",S_ORDER: "锦葵目",S_FAMILY: "锦葵科",TITLE: "梵天花",F_NAME: "fth01.jpg",},
{F_GROUP: "wood",S_GROUP:"花",S_CLASS: "双子叶植物纲",S_ORDER: "大戟目",S_FAMILY: "大戟科",TITLE: "木油桐",F_NAME: "luohua01.jpg",},
{F_GROUP: "wood",S_GROUP:"花",S_CLASS: "双子叶植物纲",S_ORDER: "大戟目",S_FAMILY: "大戟科",TITLE: "猩猩草",F_NAME: "xxc01.jpg",},
{F_GROUP: "wood",S_GROUP:"花",S_CLASS: "双子叶植物纲",S_ORDER: "侧膜胎座目",S_FAMILY: "秋海棠科",TITLE: "四季秋海棠",F_NAME: "haitang01.jpg",},
{F_GROUP: "wood",S_GROUP:"花",S_CLASS: "双子叶植物纲",S_ORDER: "侧膜胎座目",S_FAMILY: "藤黄科",TITLE: "地耳草",F_NAME: "dec01.jpg",},
{F_GROUP: "wood",S_GROUP:"花",S_CLASS: "双子叶植物纲",S_ORDER: "侧膜胎座目",S_FAMILY: "西番莲科",TITLE: "百香果",F_NAME: "bxg01.jpg",},
{F_GROUP: "wood",S_GROUP:"花",S_CLASS: "双子叶植物纲",S_ORDER: "仙人掌目",S_FAMILY: "仙人掌科",TITLE: "仙人掌黄花",F_NAME: "xianrenz01.jpg",},
{F_GROUP: "wood",S_GROUP:"花",S_CLASS: "双子叶植物纲",S_ORDER: "仙人掌目",S_FAMILY: "仙人掌科",TITLE: "仙人掌单独",F_NAME: "xianrenz02.jpg",},
{F_GROUP: "wood",S_GROUP:"花",S_CLASS: "双子叶植物纲",S_ORDER: "报春花目",S_FAMILY: "报春花科",TITLE: "星宿菜",F_NAME: "bai7.jpg",},
{F_GROUP: "wood",S_GROUP:"花",S_CLASS: "双子叶植物纲",S_ORDER: "报春花目",S_FAMILY: "报春花科",TITLE: "广西过路黄",F_NAME: "gxglh01.jpg",F_DESC: "具有清热利湿，排石通淋之功效。用于黄疸型肝炎，痢疾，热淋，石淋，白带。味苦、辛，性凉。",},
{F_GROUP: "wood",S_GROUP:"花",S_CLASS: "双子叶植物纲",S_ORDER: "茜草目",S_FAMILY: "茜草科",TITLE: "鸡矢藤",F_NAME: "jst01.jpg",},
{F_GROUP: "wood",S_GROUP:"花",S_CLASS: "双子叶植物纲",S_ORDER: "茜草目",S_FAMILY: "茜草科",TITLE: "长节耳草",F_NAME: "cjec01.jpg",},
{F_GROUP: "wood",S_GROUP:"花",S_CLASS: "双子叶植物纲",S_ORDER: "茜草目",S_FAMILY: "茜草科",TITLE: "五星花",F_NAME: "wxh01.jpg",},
{F_GROUP: "wood",S_GROUP:"花",S_CLASS: "双子叶植物纲",S_ORDER: "荨麻目",S_FAMILY: "桑科",TITLE: "楮树",F_NAME: "chu01.jpg",},
{F_GROUP: "wood",S_GROUP:"花",TITLE: "白小花",F_NAME: "baixiao.jpg",},
{F_GROUP: "wood",S_GROUP:"花",TITLE: "小白花2",F_NAME: "xiaobaihua.jpg",},
{F_GROUP: "wood",S_GROUP:"花",TITLE: "紫花小",F_NAME: "zhx01.jpg",},
{F_GROUP: "wood",S_GROUP:"花",TITLE: "紫花散",F_NAME: "zhs01.jpg",},
{F_GROUP: "wood",S_GROUP:"草",S_CLASS: "单子叶植物纲",S_ORDER: "禾本目",S_FAMILY: "禾本科",TITLE: "狗尾巴草",F_NAME: "gouyiba01.jpg",},
{F_GROUP: "wood",S_GROUP:"草",S_CLASS: "单子叶植物纲",S_ORDER: "禾本目",S_FAMILY: "禾本科",TITLE: "狗尾巴草雨",F_NAME: "gouyiba02.jpg",},
{F_GROUP: "wood",S_GROUP:"草",S_CLASS: "单子叶植物纲",S_ORDER: "禾本目",S_FAMILY: "禾本科",TITLE: "芒草",F_NAME: "mangcao.jpg",},
{F_GROUP: "wood",S_GROUP:"草",S_CLASS: "单子叶植物纲",S_ORDER: "禾本目",S_FAMILY: "禾本科",TITLE: "糠稷",F_NAME: "cao02.jpg",},
{F_GROUP: "wood",S_GROUP:"草",S_CLASS: "单子叶植物纲",S_ORDER: "禾本目",S_FAMILY: "禾本科",TITLE: "苦竹",F_NAME: "zu01.jpg",},
{F_GROUP: "wood",S_GROUP:"草",S_CLASS: "单子叶植物纲",S_ORDER: "禾本目",S_FAMILY: "禾本科",TITLE: "竹笋",F_NAME: "zu02.jpg",},
{F_GROUP: "wood",S_GROUP:"草",S_CLASS: "单子叶植物纲",S_ORDER: "莎草目",S_FAMILY: "莎草科",TITLE: "香附子",F_NAME: "caoyu01.jpg",},
{F_GROUP: "wood",S_GROUP:"草",S_CLASS: "单子叶植物纲",S_ORDER: "莎草目",S_FAMILY: "莎草科",TITLE: "水蜈蚣",F_NAME: "swg01.jpg",},
{F_GROUP: "wood",S_GROUP:"草",S_CLASS: "单子叶植物纲",S_ORDER: "天南星目",S_FAMILY: "天南星科",TITLE: "大薸",F_NAME: "dapiao01.jpg",},
{F_GROUP: "wood",S_GROUP:"草",S_CLASS: "单子叶植物纲",S_ORDER: "天南星目",S_FAMILY: "天南星科",TITLE: "海芋",F_NAME: "haiyu01.jpg",},
{F_GROUP: "wood",S_GROUP:"草",S_CLASS: "单子叶植物纲",S_ORDER: "天南星目",S_FAMILY: "天南星科",TITLE: "海芋2",F_NAME: "haiyu02.jpg",},
{F_GROUP: "wood",S_GROUP:"草",S_CLASS: "单子叶植物纲",S_ORDER: "百合目",S_FAMILY: "百合科",TITLE: "麦冬",F_NAME: "maid01.jpg",},
{F_GROUP: "wood",S_GROUP:"草",S_CLASS: "单子叶植物纲",S_ORDER: "百合目",S_FAMILY: "百合科",TITLE: "麦冬",F_NAME: "maid02.jpg",},
{F_GROUP: "wood",S_GROUP:"草",S_CLASS: "单子叶植物纲",S_ORDER: "百合目",S_FAMILY: "石蒜科",TITLE: "水鬼蕉",F_NAME: "sgj01.jpg",},
{F_GROUP: "wood",S_GROUP:"草",S_CLASS: "单子叶植物纲",S_ORDER: "百合目",S_FAMILY: "石蒜科",TITLE: "水鬼蕉",F_NAME: "sgj02.jpg",},
{F_GROUP: "wood",S_GROUP:"草",S_CLASS: "单子叶植物纲",S_ORDER: "百合目",S_FAMILY: "薯蓣科",TITLE: "薯蓣",F_NAME: "shuyu01.jpg",},
{F_GROUP: "wood",S_GROUP:"草",S_CLASS: "单子叶植物纲",S_ORDER: "芭蕉目",S_FAMILY: "姜科",TITLE: "花叶艳山姜",F_NAME: "hyysj01.jpg",},
{F_GROUP: "wood",S_GROUP:"草",S_CLASS: "单子叶植物纲",S_ORDER: "芭蕉目",S_FAMILY: "姜科",TITLE: "姜",F_NAME: "jiang01.jpg",},
{F_GROUP: "wood",S_GROUP:"草",S_CLASS: "单子叶植物纲",S_ORDER: "粉状胚乳目",S_FAMILY: "鸭跖草科",TITLE: "白花紫露草",F_NAME: "bhzlc01.jpg",},
{F_GROUP: "wood",S_GROUP:"草",S_CLASS: "双子叶植物纲",S_ORDER: "车前目",S_FAMILY: "车前科",TITLE: "车前草",F_NAME: "cheqian01.jpg",LINK:"drug/车前草",},
{F_GROUP: "wood",S_GROUP:"草",S_CLASS: "双子叶植物纲",S_ORDER: "胡椒目",S_FAMILY: "三白草科",TITLE: "鱼腥草",F_NAME: "yuxingcao01.jpg",LINK:"drug/鱼腥草",},
{F_GROUP: "wood",S_GROUP:"草",S_CLASS: "双子叶植物纲",S_ORDER: "荨麻目",S_FAMILY: "桑科",TITLE: "薜荔",F_NAME: "bili01.jpg",F_DESC: "又名凉粉子，木莲等。攀援或匍匐灌木，叶两型，不结果枝节上生不定根，叶卵状心形。瘦果水洗可作凉粉，藤叶药用。",},
{F_GROUP: "wood",S_GROUP:"草",S_CLASS: "双子叶植物纲",S_ORDER: "荨麻目",S_FAMILY: "桑科",TITLE: "薜荔缠树2",F_NAME: "bili02.jpg",},
{F_GROUP: "wood",S_GROUP:"草",S_CLASS: "双子叶植物纲",S_ORDER: "荨麻目",S_FAMILY: "桑科",TITLE: "薜荔缠树3",F_NAME: "bili03.jpg",},
{F_GROUP: "wood",S_GROUP:"草",S_CLASS: "双子叶植物纲",S_ORDER: "伞形目",S_FAMILY: "伞形科",TITLE: "铜钱草",F_NAME: "tongqiancao.jpg",},
{F_GROUP: "wood",S_GROUP:"草",S_CLASS: "双子叶植物纲",S_ORDER: "伞形目",S_FAMILY: "伞形科",TITLE: "积雪草",F_NAME: "jxc01.jpg",},
{F_GROUP: "wood",S_GROUP:"草",S_CLASS: "双子叶植物纲",S_ORDER: "伞形目",S_FAMILY: "伞形科",TITLE: "蜂与蛇床草",F_NAME: "cao1.jpg",},
{F_GROUP: "wood",S_GROUP:"草",S_CLASS: "双子叶植物纲",S_ORDER: "伞形目",S_FAMILY: "伞形科",TITLE: "茴香",F_NAME: "huix01.jpg",},
{F_GROUP: "wood",S_GROUP:"草",S_CLASS: "双子叶植物纲",S_ORDER: "伞形目",S_FAMILY: "五加科",TITLE: "鹅掌藤",F_NAME: "ezt01.jpg",},
{F_GROUP: "wood",S_GROUP:"草",S_CLASS: "双子叶植物纲",S_ORDER: "伞形目",S_FAMILY: "五加科",TITLE: "鹅掌藤2",F_NAME: "ezt02.jpg",},
{F_GROUP: "wood",S_GROUP:"草",S_CLASS: "双子叶植物纲",S_ORDER: "管状花目",S_FAMILY: "马鞭草科",TITLE: "花叶假连翘",F_NAME: "jlq01.jpg",},
{F_GROUP: "wood",S_GROUP:"草",S_CLASS: "双子叶植物纲",S_ORDER: "管状花目",S_FAMILY: "马鞭草科",TITLE: "花叶假连翘",F_NAME: "jlq02.jpg",},
{F_GROUP: "wood",S_GROUP:"草",S_CLASS: "双子叶植物纲",S_ORDER: "管状花目",S_FAMILY: "马鞭草科",TITLE: "枇杷叶紫珠",F_NAME: "ppyzz01.jpg",},
{F_GROUP: "wood",S_GROUP:"草",S_CLASS: "双子叶植物纲",S_ORDER: "管状花目",S_FAMILY: "玄参科",TITLE: "通泉草",F_NAME: "tongquancao1.jpg",},
{F_GROUP: "wood",S_GROUP:"草",S_CLASS: "双子叶植物纲",S_ORDER: "管状花目",S_FAMILY: "爵床科",TITLE: "爵床",F_NAME: "jc01.jpg",},
{F_GROUP: "wood",S_GROUP:"草",S_CLASS: "双子叶植物纲",S_ORDER: "蓼目",S_FAMILY: "蓼科",TITLE: "杠板归",F_NAME: "kbg01.jpg",},
{F_GROUP: "wood",S_GROUP:"草",S_CLASS: "双子叶植物纲",S_ORDER: "茜草目",S_FAMILY: "茜草科",TITLE: "火龙水杨梅",F_NAME: "hlsym01.jpg",},
{F_GROUP: "wood",S_GROUP:"草",S_CLASS: "双子叶植物纲",S_ORDER: "桔梗目",S_FAMILY: "菊科",TITLE: "鬼针草",F_NAME: "guizhencao.jpg",},
{F_GROUP: "wood",S_GROUP:"草",S_CLASS: "双子叶植物纲",S_ORDER: "桔梗目",S_FAMILY: "菊科",TITLE: "鬼针草",F_NAME: "guizhencao01.jpg",},
{F_GROUP: "wood",S_GROUP:"草",S_CLASS: "双子叶植物纲",S_ORDER: "桔梗目",S_FAMILY: "菊科",TITLE: "鬼针草3",F_NAME: "guizhencao03.jpg",},
{F_GROUP: "wood",S_GROUP:"草",S_CLASS: "双子叶植物纲",S_ORDER: "桔梗目",S_FAMILY: "菊科",TITLE: "蒲公英细风",F_NAME: "pugongying.jpg",F_DESC: "蒲公英花花",},
{F_GROUP: "wood",S_GROUP:"草",S_CLASS: "双子叶植物纲",S_ORDER: "桔梗目",S_FAMILY: "菊科",TITLE: "蒲公英蝉蜕",F_NAME: "pugongying3.jpg",F_DESC: "蒲公英蝉蜕",},
{F_GROUP: "wood",S_GROUP:"草",S_CLASS: "双子叶植物纲",S_ORDER: "桔梗目",S_FAMILY: "菊科",TITLE: "刺儿菜",F_NAME: "huozi01.jpg",},
{F_GROUP: "wood",S_GROUP:"草",S_CLASS: "双子叶植物纲",S_ORDER: "桔梗目",S_FAMILY: "菊科",TITLE: "苣荬菜",F_NAME: "qumai01.jpg",},
{F_GROUP: "wood",S_GROUP:"草",S_CLASS: "双子叶植物纲",S_ORDER: "桔梗目",S_FAMILY: "菊科",TITLE: "艾草",F_NAME: "aicao01.jpg",},
{F_GROUP: "wood",S_GROUP:"草",S_CLASS: "双子叶植物纲",S_ORDER: "桔梗目",S_FAMILY: "菊科",TITLE: "假臭草小",F_NAME: "jccao01.jpg",},
{F_GROUP: "wood",S_GROUP:"草",S_CLASS: "双子叶植物纲",S_ORDER: "桔梗目",S_FAMILY: "菊科",TITLE: "假臭草整",F_NAME: "jccao03.jpg",},
{F_GROUP: "wood",S_GROUP:"草",S_CLASS: "双子叶植物纲",S_ORDER: "侧膜胎座目",S_FAMILY: "堇菜科",TITLE: "长萼堇菜",F_NAME: "zihuacao.jpg",},
{F_GROUP: "wood",S_GROUP:"草",S_CLASS: "双子叶植物纲",S_ORDER: "中央种子目",S_FAMILY: "石竹科",TITLE: "繁缕",F_NAME: "xiaocao.jpg",},
{F_GROUP: "wood",S_GROUP:"草",S_CLASS: "双子叶植物纲",S_ORDER: "中央种子目",S_FAMILY: "石竹科",TITLE: "繁缕2",F_NAME: "fanlv02.jpg",},
{F_GROUP: "wood",S_GROUP:"草",S_CLASS: "双子叶植物纲",S_ORDER: "中央种子目",S_FAMILY: "石竹科",TITLE: "荷莲豆草",F_NAME: "hldc01.jpg",},
{F_GROUP: "wood",S_GROUP:"草",S_CLASS: "双子叶植物纲",S_ORDER: "蔷薇目",S_FAMILY: "景天科",TITLE: "棒叶落地生根",F_NAME: "byldsg01.jpg",},
{F_GROUP: "wood",S_GROUP:"草",S_CLASS: "双子叶植物纲",S_ORDER: "桃金娘目",S_FAMILY: "小二仙草科",TITLE: "粉绿狐尾藻",F_NAME: "hwz01.jpg",},
{F_GROUP: "wood",S_GROUP:"草",S_CLASS: "双子叶植物纲",S_ORDER: "桃金娘目",S_FAMILY: "小二仙草科",TITLE: "粉绿狐尾藻2",F_NAME: "hwz02.jpg",},
{F_GROUP: "wood",S_GROUP:"草",S_CLASS: "双子叶植物纲",S_ORDER: "牻牛儿苗目",S_FAMILY: "酢浆草科",TITLE: "红花酢浆草",F_NAME: "cjc01.jpg",},
{F_GROUP: "wood",S_GROUP:"草",S_CLASS: "双子叶植物纲",S_ORDER: "牻牛儿苗目",S_FAMILY: "酢浆草科",TITLE: "黄花酢浆草3",F_NAME: "cjc03.jpg",},
{F_GROUP: "wood",S_GROUP:"草",S_CLASS: "双子叶植物纲",S_ORDER: "牻牛儿苗目",S_FAMILY: "酢浆草科",TITLE: "黄花酢浆草4",F_NAME: "cjc04.jpg",},
{F_GROUP: "wood",S_GROUP:"草",S_CLASS: "双子叶植物纲",S_ORDER: "大戟目",S_FAMILY: "大戟科",TITLE: "叶下珠",F_NAME: "yxz01.jpg",},
{F_GROUP: "wood",S_GROUP:"草",S_CLASS: "双子叶植物纲",S_ORDER: "大戟目",S_FAMILY: "大戟科",TITLE: "红背桂花",F_NAME: "hbgh01.jpg",},
{F_GROUP: "wood",S_GROUP:"草",S_CLASS: "双子叶植物纲",S_ORDER: "大戟目",S_FAMILY: "大戟科",TITLE: "地锦草1",F_NAME: "djc01.jpg",},
{F_GROUP: "wood",S_GROUP:"草",S_CLASS: "双子叶植物纲",S_ORDER: "捩花目",S_FAMILY: "夹竹桃科",TITLE: "络石",F_NAME: "ls01.jpg",},
{F_GROUP: "wood",S_GROUP:"木",S_CLASS: "双子叶植物纲",S_ORDER: "鼠李目",S_FAMILY: "葡萄科",TITLE: "五叶地锦",F_NAME: "wydj01.jpg",},
{F_GROUP: "wood",S_GROUP:"草",TITLE: "草蜿蜒",F_NAME: "caowanyan.jpg",},
{F_GROUP: "wood",S_GROUP:"草",TITLE: "草五分",F_NAME: "caowufen.jpg",},
{F_GROUP: "wood",S_GROUP:"草",TITLE: "草绿小",F_NAME: "caolvxiao.jpg",},
{F_GROUP: "wood",S_GROUP:"草",TITLE: "墙上草1",F_NAME: "qsc01.jpg",},
{F_GROUP: "wood",S_GROUP:"草",TITLE: "细草",F_NAME: "caoxi01.jpg",},
{F_GROUP: "wood",S_GROUP:"草",TITLE: "草三",F_NAME: "cao01.jpg",},
{F_GROUP: "wood",S_GROUP:"草",TITLE: "草长叶",F_NAME: "cao03.jpg",},
{F_GROUP: "wood",S_GROUP:"草",TITLE: "草长茎",F_NAME: "cao04.jpg",},
{F_GROUP: "wood",S_GROUP:"草",TITLE: "草木梢",F_NAME: "cao05.jpg",},
{F_GROUP: "wood",S_GROUP:"草",TITLE: "草似花",F_NAME: "cao06.jpg",},
{F_GROUP: "wood",S_GROUP:"草",TITLE: "水上草",F_NAME: "cao07.jpg",},
{F_GROUP: "wood",S_GROUP:"草",TITLE: "草大叶",F_NAME: "cao08.jpg",},
{F_GROUP: "wood",S_GROUP:"草",TITLE: "草梨叶",F_NAME: "cao09.jpg",},
{F_GROUP: "wood",S_GROUP:"草",TITLE: "草红茎",F_NAME: "cao10.jpg",},
{F_GROUP: "wood",S_GROUP:"草",TITLE: "水草蜿蜒",F_NAME: "cao11.jpg",},
{F_GROUP: "wood",S_GROUP:"草",TITLE: "椭叶红茎",F_NAME: "cao12.jpg",},
{F_GROUP: "wood",S_GROUP:"草",TITLE: "小椭叶红茎",F_NAME: "cao13.jpg",},
{F_GROUP: "wood",S_GROUP:"菇",S_CLASS: "伞菌纲",S_ORDER: "无蕈褶目",S_FAMILY: "多孔菌科",TITLE: "树舌",F_NAME: "gu4.jpg",},
{F_GROUP: "wood",S_GROUP:"菇",S_CLASS: "层菌纲",S_ORDER: "红菇目",S_FAMILY: "红菇科",TITLE: "红菇",F_NAME: "gu8.jpg",},
{F_GROUP: "wood",S_GROUP:"菇",S_CLASS: "银耳纲",S_ORDER: "木耳目",S_FAMILY: "木耳科",TITLE: "野生黑木耳",F_NAME: "muer01.jpg",},
{F_GROUP: "wood",S_GROUP:"菇",S_CLASS: "银耳纲",S_ORDER: "木耳目",S_FAMILY: "木耳科",TITLE: "野生黑木耳",F_NAME: "muer03.jpg",},
{F_GROUP: "wood",S_GROUP:"菇",S_CLASS: "银耳纲",S_ORDER: "银耳目",S_FAMILY: "银耳科",TITLE: "野生白木耳",F_NAME: "muer02.jpg",},
{F_GROUP: "wood",S_GROUP:"菇",S_CLASS: "层菌纲",S_ORDER: "伞菌目",S_FAMILY: "鹅膏菌科",TITLE: "角鳞白鹅膏菌",F_NAME: "gu16.jpg",},
{F_GROUP: "wood",S_GROUP:"菇",S_CLASS: "层菌纲",S_ORDER: "伞菌目",S_FAMILY: "鬼伞科",TITLE: "花褶伞",F_NAME: "gu17.jpg",F_DESC: "春至秋季在牛、马粪或肥沃的地上成群生长",},
{F_GROUP: "wood",S_GROUP:"菇",TITLE: "伞灰粗",F_NAME: "gu10.jpg",},
{F_GROUP: "wood",S_GROUP:"菇",TITLE: "小伞",F_NAME: "gu5.jpg",},
{F_GROUP: "wood",S_GROUP:"菇",TITLE: "彩菇",F_NAME: "gu9.jpg",},
{F_GROUP: "wood",S_GROUP:"菇",TITLE: "枯木白轮",F_NAME: "gu11.jpg",},
{F_GROUP: "wood",S_GROUP:"菇",TITLE: "树白菇",F_NAME: "gu6.jpg",},
{F_GROUP: "wood",S_GROUP:"菇",TITLE: "灰伞",F_NAME: "gu2.jpg",},
{F_GROUP: "wood",S_GROUP:"菇",TITLE: "白菇",F_NAME: "baigu.jpg",},
{F_GROUP: "wood",S_GROUP:"菇",TITLE: "红菇",F_NAME: "gu3.jpg",},
{F_GROUP: "wood",S_GROUP:"菇",TITLE: "竹叶菇",F_NAME: "gu7.jpg",},
{F_GROUP: "wood",S_GROUP:"菇",TITLE: "网黄菇",F_NAME: "gu1.jpg",},
{F_GROUP: "wood",S_GROUP:"菇",TITLE: "棕木串",F_NAME: "gu12.jpg",},
{F_GROUP: "wood",S_GROUP:"菇",TITLE: "群紫菇",F_NAME: "gu13.jpg",},
{F_GROUP: "wood",S_GROUP:"菇",TITLE: "乱角菇",F_NAME: "gu14.jpg",},
{F_GROUP: "wood",S_GROUP:"菇",TITLE: "黑菇",F_NAME: "gu18.jpg",},
{F_GROUP: "wood",S_GROUP:"菇",TITLE: "苔藓菇",F_NAME: "gu19.jpg",},
{F_GROUP: "wood",S_GROUP:"菇",TITLE: "黄点白蘑菇",F_NAME: "gu15.jpg",},
{F_GROUP: "wood",S_GROUP:"菇",TITLE: "一簇菇",F_NAME: "gu20.jpg",},
{F_GROUP: "wood",S_GROUP:"菇",TITLE: "伞菇小",F_NAME: "gu21.jpg",},
{F_GROUP: "wood",S_GROUP:"藓",S_CLASS: "藓纲",S_ORDER: "真藓目",S_FAMILY: "葫芦藓科",TITLE: "葫芦藓",F_NAME: "hlx01.jpg",},
{F_GROUP: "wood",S_GROUP:"藓",S_CLASS: "藓纲",S_ORDER: "金发藓目",S_FAMILY: "金发藓科",TITLE: "金发藓",F_NAME: "jfx01.jpg",},
{F_GROUP: "wood",S_GROUP:"藓",S_CLASS: "藓纲",S_ORDER: "丛藓目",S_FAMILY: "丛藓科",TITLE: "墙藓",F_NAME: "qx01.jpg",},
{F_GROUP: "wood",S_GROUP:"蕨",S_CLASS: "薄囊蕨纲",S_ORDER: "水龙骨目",S_FAMILY: "肾蕨科",TITLE: "肾蕨",F_NAME: "juelei02.jpg",},
{F_GROUP: "wood",S_GROUP:"蕨",S_CLASS: "薄囊蕨纲",S_ORDER: "水龙骨目",S_FAMILY: "里白科",TITLE: "里白",F_NAME: "juelei03.jpg",},
{F_GROUP: "wood",S_GROUP:"蕨",S_CLASS: "薄囊蕨纲",S_ORDER: "水龙骨目",S_FAMILY: "里白科",TITLE: "里白2",F_NAME: "juelei08.jpg",},
{F_GROUP: "wood",S_GROUP:"蕨",S_CLASS: "薄囊蕨纲",S_ORDER: "水龙骨目",S_FAMILY: "里白科",TITLE: "芒萁",F_NAME: "juelei07.jpg",},
{F_GROUP: "wood",S_GROUP:"蕨",S_CLASS: "薄囊蕨纲",S_ORDER: "水龙骨目",TITLE: "一大片蕨",F_NAME: "juelei01.jpg",},
{F_GROUP: "wood",S_GROUP:"蕨",S_CLASS: "薄囊蕨纲",S_ORDER: "水龙骨目",S_FAMILY: "桫椤科",TITLE: "桫椤",F_NAME: "suoluo01.jpg",},
{F_GROUP: "wood",S_GROUP:"蕨",S_CLASS: "薄囊蕨纲",S_ORDER: "水龙骨目",S_FAMILY: "海金沙科",TITLE: "海金沙草",F_NAME: "hjsc01.jpg",},
{F_GROUP: "wood",S_GROUP:"蕨",S_CLASS: "薄囊蕨纲",S_ORDER: "水龙骨目",S_FAMILY: "水龙骨科",TITLE: "江南星蕨",F_NAME: "juelei05.jpg",},
{F_GROUP: "wood",S_GROUP:"蕨",S_CLASS: "薄囊蕨纲",S_ORDER: "水龙骨目",S_FAMILY: "陵齿蕨科",TITLE: "乌蕨1",F_NAME: "juelei06.jpg",},
{F_GROUP: "wood",S_GROUP:"蕨",S_CLASS: "薄囊蕨纲",S_ORDER: "水龙骨目",S_FAMILY: "陵齿蕨科",TITLE: "乌蕨2",F_NAME: "juelei11.jpg",},
{F_GROUP: "wood",S_GROUP:"蕨",S_CLASS: "薄囊蕨纲",S_ORDER: "水龙骨目",S_FAMILY: "乌毛蕨科",TITLE: "乌毛蕨",F_NAME: "juelei09.jpg",},
{F_GROUP: "wood",S_GROUP:"蕨",S_CLASS: "薄囊蕨纲",S_ORDER: "水龙骨目",S_FAMILY: "铁线蕨科",TITLE: "扇叶铁线蕨",F_NAME: "juelei12.jpg",},
{F_GROUP: "wood",S_GROUP:"蕨",S_CLASS: "厚囊蕨纲",S_ORDER: "观音座莲目",_FAMILY: "观音座莲科",TITLE: "福建观音座莲",F_NAME: "gyzl01.jpg",},
{F_GROUP: "wood",S_GROUP:"蕨",S_CLASS: "石松纲",S_ORDER: "石松目",S_FAMILY: "石松科",TITLE: "垂穗石松",F_NAME: "juanjuan01.jpg",},
{F_GROUP: "wood",S_GROUP:"蕨",S_CLASS: "石松纲",S_ORDER: "卷柏目",S_FAMILY: "卷柏科",TITLE: "江南卷柏",F_NAME: "juanjuan02.jpg",},
{F_GROUP: "wood",S_GROUP:"蕨",S_CLASS: "石松纲",S_ORDER: "卷柏目",S_FAMILY: "卷柏科",TITLE: "深绿卷柏",F_NAME: "jue2.jpg",},
{F_GROUP: "wood",S_GROUP:"蕨",S_CLASS: "石松纲",S_ORDER: "卷柏目",S_FAMILY: "卷柏科",TITLE: "未知卷柏",F_NAME: "juanjuan03.jpg",},
{F_GROUP: "wood",S_GROUP:"蕨",TITLE: "蕨红细",F_NAME: "juelei04.jpg",},
{F_GROUP: "wood",S_GROUP:"蕨",TITLE: "蕨多级",F_NAME: "juelei10.jpg",},
{F_GROUP: "wood",S_GROUP:"蕨",TITLE: "阴阳蕨",F_NAME: "yinyangjue.jpg",},
{F_GROUP: "wood",S_GROUP:"藻",S_CLASS: "红藻纲",S_ORDER: "珊瑚藻目",S_FAMILY: "珊瑚藻科",TITLE: "珊瑚藻",F_NAME: "zao01.jpg",},
{F_GROUP: "wood",S_GROUP:"地衣",S_CLASS: "子囊衣纲",S_ORDER: "茶渍目",S_FAMILY: "梅衣科",TITLE: "梅衣属",F_NAME: "kzdy01.jpg",},
]