var ifile=[
{S_DOMAIN: "空之域",S_KINGDOM: "星河界",S_PHYLUM: "太阳系",S_CLASS: "日月",S_ORDER: "太阳",},
{S_DOMAIN: "空之域",S_KINGDOM: "星河界",S_PHYLUM: "太阳系",S_CLASS: "日月",S_ORDER: "月亮",},
{S_DOMAIN: "空之域",S_KINGDOM: "星河界",S_PHYLUM: "太阳系",S_CLASS: "行星",S_ORDER: "水星",},
{S_DOMAIN: "空之域",S_KINGDOM: "星河界",S_PHYLUM: "太阳系",S_CLASS: "行星",S_ORDER: "金星",},
{S_DOMAIN: "空之域",S_KINGDOM: "星河界",S_PHYLUM: "太阳系",S_CLASS: "行星",S_ORDER: "地球",},
{S_DOMAIN: "空之域",S_KINGDOM: "星河界",S_PHYLUM: "太阳系",S_CLASS: "行星",S_ORDER: "火星",},
{S_DOMAIN: "空之域",S_KINGDOM: "星河界",S_PHYLUM: "太阳系",S_CLASS: "行星",S_ORDER: "木星",},
{S_DOMAIN: "空之域",S_KINGDOM: "星河界",S_PHYLUM: "太阳系",S_CLASS: "行星",S_ORDER: "土星",},
{S_DOMAIN: "空之域",S_KINGDOM: "星河界",S_PHYLUM: "太阳系",S_CLASS: "行星",S_ORDER: "海王星",},
{S_DOMAIN: "空之域",S_KINGDOM: "星河界",S_PHYLUM: "太阳系",S_CLASS: "行星",S_ORDER: "天王星",},
{S_DOMAIN: "空之域",S_KINGDOM: "星河界",S_PHYLUM: "太阳系",S_CLASS: "彗星",S_ORDER: "46P",},
{S_DOMAIN: "空之域",S_KINGDOM: "星河界",S_PHYLUM: "太阳系",S_CLASS: "彗星",S_ORDER: "2020F3",},
{S_DOMAIN: "空之域",S_KINGDOM: "星河界",S_PHYLUM: "系外",S_CLASS: "星团星系",S_ORDER: "昴星团",},
{S_DOMAIN: "空之域",S_KINGDOM: "星河界",S_PHYLUM: "系外",S_CLASS: "星团星系",S_ORDER: "猎户座大星云",},
{S_DOMAIN: "空之域",S_KINGDOM: "星河界",S_PHYLUM: "系外",S_CLASS: "星团星系",S_ORDER: "仙女星云",},
{S_DOMAIN: "地之域",S_KINGDOM: "地界",S_PHYLUM: "气象",S_CLASS: "云",S_ORDER: "积云",},
{S_DOMAIN: "地之域",S_KINGDOM: "地界",S_PHYLUM: "气象",S_CLASS: "云",S_ORDER: "积雨云",},
{S_DOMAIN: "地之域",S_KINGDOM: "地界",S_PHYLUM: "气象",S_CLASS: "云",S_ORDER: "层云",},
{S_DOMAIN: "地之域",S_KINGDOM: "地界",S_PHYLUM: "气象",S_CLASS: "云",S_ORDER: "层积云",},
{S_DOMAIN: "地之域",S_KINGDOM: "地界",S_PHYLUM: "气象",S_CLASS: "云",S_ORDER: "高积云",},
{S_DOMAIN: "地之域",S_KINGDOM: "地界",S_PHYLUM: "气象",S_CLASS: "云",S_ORDER: "浓积云",},
{S_DOMAIN: "地之域",S_KINGDOM: "地界",S_PHYLUM: "气象",S_CLASS: "云",S_ORDER: "高层云",},
{S_DOMAIN: "地之域",S_KINGDOM: "地界",S_PHYLUM: "气象",S_CLASS: "云",S_ORDER: "雨层云",},
{S_DOMAIN: "地之域",S_KINGDOM: "地界",S_PHYLUM: "气象",S_CLASS: "云",S_ORDER: "卷云",},
{S_DOMAIN: "地之域",S_KINGDOM: "地界",S_PHYLUM: "气象",S_CLASS: "云",S_ORDER: "卷积云",},
{S_DOMAIN: "地之域",S_KINGDOM: "地界",S_PHYLUM: "气象",S_CLASS: "云",S_ORDER: "卷层云",},
{S_DOMAIN: "地之域",S_KINGDOM: "地界",S_PHYLUM: "气象",S_CLASS: "其它",S_ORDER: "闪电",},
{S_DOMAIN: "地之域",S_KINGDOM: "地界",S_PHYLUM: "气象",S_CLASS: "其它",S_ORDER: "红色精灵",},
{S_DOMAIN: "地之域",S_KINGDOM: "地界",S_PHYLUM: "气象",S_CLASS: "其它",S_ORDER: "暖夜灯柱",},
{S_DOMAIN: "地之域",S_KINGDOM: "地界",S_PHYLUM: "气象",S_CLASS: "其它",S_ORDER: "日晕",},
{S_DOMAIN: "地之域",S_KINGDOM: "地界",S_PHYLUM: "气象",S_CLASS: "其它",S_ORDER: "彩虹",},
{S_DOMAIN: "古菌域",S_KINGDOM: "嗜泉古菌界",S_PHYLUM: "未知门",S_CLASS: "未知纲",S_ORDER: "未知目",},
{S_DOMAIN: "古菌域",S_KINGDOM: "广域古菌界",S_PHYLUM: "未知门",S_CLASS: "未知纲",S_ORDER: "未知目",},
{S_DOMAIN: "古菌域",S_KINGDOM: "始生古菌界",S_PHYLUM: "未知门",S_CLASS: "未知纲",S_ORDER: "未知目",},
{S_DOMAIN: "细菌域",S_KINGDOM: "细菌界",S_PHYLUM: "未知门",S_CLASS: "未知纲",S_ORDER: "未知目",},
{S_DOMAIN: "真核域",S_KINGDOM: "原生生物界",S_PHYLUM: "未知门",S_CLASS: "未知纲",S_ORDER: "未知目",},
{S_DOMAIN: "真核域",S_KINGDOM: "真菌界",S_PHYLUM: "真菌门",S_CLASS: "未知纲",S_ORDER: "未知目",},
{S_DOMAIN: "真核域",S_KINGDOM: "真菌界",S_PHYLUM: "粘菌门",S_CLASS: "未知纲",S_ORDER: "未知目",},
{S_DOMAIN: "真核域",S_KINGDOM: "真菌界",S_PHYLUM: "担子菌门",S_CLASS: "黑粉菌纲",S_ORDER: "未知目",},
{S_DOMAIN: "真核域",S_KINGDOM: "真菌界",S_PHYLUM: "担子菌门",S_CLASS: "锈菌纲",S_ORDER: "未知目",},
{S_DOMAIN: "真核域",S_KINGDOM: "真菌界",S_PHYLUM: "担子菌门",S_CLASS: "伞菌纲",S_ORDER: "木耳目",},
{S_DOMAIN: "真核域",S_KINGDOM: "真菌界",S_PHYLUM: "担子菌门",S_CLASS: "伞菌纲",S_ORDER: "无蕈褶目",},
{S_DOMAIN: "真核域",S_KINGDOM: "真菌界",S_PHYLUM: "担子菌门",S_CLASS: "银耳纲",S_ORDER: "银耳目",},
{S_DOMAIN: "真核域",S_KINGDOM: "真菌界",S_PHYLUM: "担子菌门",S_CLASS: "层菌纲",S_ORDER: "伞菌目",},
{S_DOMAIN: "真核域",S_KINGDOM: "真菌界",S_PHYLUM: "担子菌门",S_CLASS: "层菌纲",S_ORDER: "红菇目",},
/*{S_DOMAIN: "真核域",S_KINGDOM: "植物界",S_PHYLUM: "绿藻门",S_CLASS: "未知纲",S_ORDER: "未知目",},
{S_DOMAIN: "真核域",S_KINGDOM: "植物界",S_PHYLUM: "裸藻门",S_CLASS: "未知纲",S_ORDER: "未知目",},
{S_DOMAIN: "真核域",S_KINGDOM: "植物界",S_PHYLUM: "金藻门",S_CLASS: "未知纲",S_ORDER: "未知目",},
{S_DOMAIN: "真核域",S_KINGDOM: "植物界",S_PHYLUM: "黄藻门",S_CLASS: "未知纲",S_ORDER: "未知目",},
{S_DOMAIN: "真核域",S_KINGDOM: "植物界",S_PHYLUM: "甲藻门",S_CLASS: "未知纲",S_ORDER: "未知目",},
{S_DOMAIN: "真核域",S_KINGDOM: "植物界",S_PHYLUM: "硅藻门",S_CLASS: "未知纲",S_ORDER: "未知目",},
{S_DOMAIN: "真核域",S_KINGDOM: "植物界",S_PHYLUM: "蓝藻门",S_CLASS: "未知纲",S_ORDER: "未知目",},
{S_DOMAIN: "真核域",S_KINGDOM: "植物界",S_PHYLUM: "褐藻门",S_CLASS: "未知纲",S_ORDER: "未知目",},
{S_DOMAIN: "真核域",S_KINGDOM: "植物界",S_PHYLUM: "红藻门",S_CLASS: "未知纲",S_ORDER: "未知目",},
{S_DOMAIN: "真核域",S_KINGDOM: "植物界",S_PHYLUM: "地衣门",S_CLASS: "未知纲",S_ORDER: "未知目",},*/
{S_DOMAIN: "真核域",S_KINGDOM: "植物界",S_PHYLUM: "苔藓植物门",S_CLASS: "未知纲",S_ORDER: "未知目",},
{S_DOMAIN: "真核域",S_KINGDOM: "植物界",S_PHYLUM: "蕨类植物门",S_CLASS: "松叶蕨纲",S_ORDER: "松叶蕨目",},
{S_DOMAIN: "真核域",S_KINGDOM: "植物界",S_PHYLUM: "蕨类植物门",S_CLASS: "石松纲",S_ORDER: "石松目",},
{S_DOMAIN: "真核域",S_KINGDOM: "植物界",S_PHYLUM: "蕨类植物门",S_CLASS: "石松纲",S_ORDER: "卷柏目",},
{S_DOMAIN: "真核域",S_KINGDOM: "植物界",S_PHYLUM: "蕨类植物门",S_CLASS: "水韭纲",S_ORDER: "水韭目",},
{S_DOMAIN: "真核域",S_KINGDOM: "植物界",S_PHYLUM: "蕨类植物门",S_CLASS: "木贼纲",S_ORDER: "木贼目",},
{S_DOMAIN: "真核域",S_KINGDOM: "植物界",S_PHYLUM: "蕨类植物门",S_CLASS: "厚囊蕨纲",S_ORDER: "瓶尔小草目",},
{S_DOMAIN: "真核域",S_KINGDOM: "植物界",S_PHYLUM: "蕨类植物门",S_CLASS: "厚囊蕨纲",S_ORDER: "莲座蕨目",},
{S_DOMAIN: "真核域",S_KINGDOM: "植物界",S_PHYLUM: "蕨类植物门",S_CLASS: "原始薄囊蕨纲",S_ORDER: "紫萁目",},
{S_DOMAIN: "真核域",S_KINGDOM: "植物界",S_PHYLUM: "蕨类植物门",S_CLASS: "薄囊蕨纲",S_ORDER: "水龙骨目",},
{S_DOMAIN: "真核域",S_KINGDOM: "植物界",S_PHYLUM: "蕨类植物门",S_CLASS: "薄囊蕨纲",S_ORDER: "苹目",},
{S_DOMAIN: "真核域",S_KINGDOM: "植物界",S_PHYLUM: "蕨类植物门",S_CLASS: "薄囊蕨纲",S_ORDER: "槐叶苹目",},
{S_DOMAIN: "真核域",S_KINGDOM: "植物界",S_PHYLUM: "裸子植物门",S_CLASS: "苏铁纲",S_ORDER: "苏铁目",},
{S_DOMAIN: "真核域",S_KINGDOM: "植物界",S_PHYLUM: "裸子植物门",S_CLASS: "银杏纲",S_ORDER: "银杏目",},
{S_DOMAIN: "真核域",S_KINGDOM: "植物界",S_PHYLUM: "裸子植物门",S_CLASS: "松柏纲",S_ORDER: "松柏目",},
{S_DOMAIN: "真核域",S_KINGDOM: "植物界",S_PHYLUM: "裸子植物门",S_CLASS: "松柏纲",S_ORDER: "红豆杉目",},
{S_DOMAIN: "真核域",S_KINGDOM: "植物界",S_PHYLUM: "裸子植物门",S_CLASS: "买麻藤纲",S_ORDER: "买麻藤目",},
{S_DOMAIN: "真核域",S_KINGDOM: "植物界",S_PHYLUM: "被子植物门",S_CLASS: "单子叶植物纲",INFO: "单子叶植物种子的胚具1片子叶，植物多为草本，稀为木本（龙血树）；茎中维管束星散排列，无形成层，不能次生加粗；叶具平行脉或弧形脉；花部通常为3的基数；多成须根系。"},
{S_DOMAIN: "真核域",S_KINGDOM: "植物界",S_PHYLUM: "被子植物门",S_CLASS: "单子叶植物纲",S_ORDER: "天南星目",INFO: "为草本，稀为攀援木本，极少数为水生植物。叶宽，具叶柄。花小，高度退化，密生成肉穗花序，通常为1大形佛焰苞片所包。佛焰苞片常具彩色；花被缺或退化为鳞片状；子房上位。浆果或胞果，种子有丰富胚乳或有时缺如。"},
{S_DOMAIN: "真核域",S_KINGDOM: "植物界",S_PHYLUM: "被子植物门",S_CLASS: "单子叶植物纲",S_ORDER: "莎草目",INFO: "多为草本。叶互生，狭长，叶具叶鞘。花小，生于颖状苞片内，由1至多数小花组成小穗；花被退化为鳞片状、刚毛状、鳞被状或无花被；雄蕊3~6，子房上位，由2~3心皮构成，合生，1室1胚珠。叶片通常狭窄而细长，具闭合的叶鞘，平行脉；叶片与叶鞘连接处常有一个小型的近轴附属物——叶舌。",},
{S_DOMAIN: "真核域",S_KINGDOM: "植物界",S_PHYLUM: "被子植物门",S_CLASS: "单子叶植物纲",S_ORDER: "莎草目",S_FAMILY: "莎草科",TITLE: "水蜈蚣",F_GROUP: "wood",F_NAME: "swg01.jpg",},
{S_DOMAIN: "真核域",S_KINGDOM: "植物界",S_PHYLUM: "被子植物门",S_CLASS: "单子叶植物纲",S_ORDER: "莎草目",S_FAMILY: "莎草科",TITLE: "浆果薹草",F_GROUP: "wood",F_NAME: "hongguo02.jpg",},
{S_DOMAIN: "真核域",S_KINGDOM: "植物界",S_PHYLUM: "被子植物门",S_CLASS: "单子叶植物纲",S_ORDER: "粉状胚乳目",INFO: "多年生稀为一年生草本。叶互生或基生，单叶，具开放或闭合的叶鞘。花序各式各样；花两性或单性，辐射对称或两侧对称，同被花或区分花萼与花冠，通常3基数；花被片3-6枚，排成1-2轮，稀缺花被片；雄蕊6枚，2轮或3（4）枚，有时仅1或2枚；花药1-2室，常纵裂；雌蕊通常由3个心皮所构成；子房上位或下位，1-3室，胚珠通常直生。果实多数为蒴果，稀为核果、坚果或蓇葖果。种子有粉状胚乳。",},
{S_DOMAIN: "真核域",S_KINGDOM: "植物界",S_PHYLUM: "被子植物门",S_CLASS: "单子叶植物纲",S_ORDER: "粉状胚乳目",S_FAMILY: "鸭跖草科",INFO: "多年生常绿草本，单叶互生，叶全缘，叶脉平行，茎枝多汁粗厚，植株形态有蔓性、匍匐性或簇生之短茎直立型。花多整齐的两性花，常着生于叶腋，或茎顶簇生成聚伞或圆锥花序，花色白、蓝或粉色，多只绽放一日，花数多为3或3的倍数，蒴果。",},
{S_DOMAIN: "真核域",S_KINGDOM: "植物界",S_PHYLUM: "被子植物门",S_CLASS: "单子叶植物纲",S_ORDER: "禾本目",INFO: "一年生、二年生或多年生草本，稀为木本，常具根状茎或匍匐茎。秆通常圆柱形，中空，稀实心，节实心。叶互生，呈二行排列，叶由叶鞘、叶舌及叶片组成，叶舌生于叶鞘与叶片连接处的内侧，通常膜质，有时为一圈毛所代替，稀无叶舌，有时在叶鞘顶端叶片基部尚有耳状附属物称为叶耳；叶片线形或丝状，稀披针形或至卵形。",},
{S_DOMAIN: "真核域",S_KINGDOM: "植物界",S_PHYLUM: "被子植物门",S_CLASS: "单子叶植物纲",S_ORDER: "沼生目",},
{S_DOMAIN: "真核域",S_KINGDOM: "植物界",S_PHYLUM: "被子植物门",S_CLASS: "单子叶植物纲",S_ORDER: "百合目",},
{S_DOMAIN: "真核域",S_KINGDOM: "植物界",S_PHYLUM: "被子植物门",S_CLASS: "单子叶植物纲",S_ORDER: "微子目",},
{S_DOMAIN: "真核域",S_KINGDOM: "植物界",S_PHYLUM: "被子植物门",S_CLASS: "单子叶植物纲",S_ORDER: "露兜树目",},
{S_DOMAIN: "真核域",S_KINGDOM: "植物界",S_PHYLUM: "被子植物门",S_CLASS: "单子叶植物纲",S_ORDER: "初生目",S_FAMILY: "棕榈科",TITLE: "棕榈",F_GROUP: "wood",F_NAME: "zlv02.jpg,jbl01.jpg,zlv01.jpg",},
{S_DOMAIN: "真核域",S_KINGDOM: "植物界",S_PHYLUM: "被子植物门",S_CLASS: "单子叶植物纲",S_ORDER: "芭蕉目",S_FAMILY: "美人蕉科",TITLE: "美人蕉",F_GROUP: "wood",F_NAME: "huanghua.jpg",},
{S_DOMAIN: "真核域",S_KINGDOM: "植物界",S_PHYLUM: "被子植物门",S_CLASS: "单子叶植物纲",S_ORDER: "芭蕉目",S_FAMILY: "姜科",TITLE: "香蕉",F_GROUP: "wood",F_NAME: "xiangjiao01.jpg",},
{S_DOMAIN: "真核域",S_KINGDOM: "植物界",S_PHYLUM: "被子植物门",S_CLASS: "单子叶植物纲",S_ORDER: "霉草目",},
{S_DOMAIN: "真核域",S_KINGDOM: "植物界",S_PHYLUM: "被子植物门",S_CLASS: "双子叶植物纲",INFO: "双子叶植物纲植物胚具子叶2片，主根发达，多为直根系，茎内为开放型维管束，环状，有形成层和次生组织，叶除少数外，均为网状脉，花部通常5~4基数，花粉多具3个萌发孔。",},
{S_DOMAIN: "真核域",S_KINGDOM: "植物界",S_PHYLUM: "被子植物门",S_CLASS: "双子叶植物纲",S_ORDER: "蔷薇目",INFO:"含24科，约320属，有6,700种。包括一些温带地区著名的观赏植物及果树，如蔷薇、山楂、苹果、桃、樱桃、梨、李、草莓及醋栗等。花各部轮状排列，少有螺旋状排列，花被2轮，有时缺花瓣，少有花被全缺，花下位、周位或上位，常为辐射对称及两性花，心皮常分离，或合生，有时有厚的、多数胚珠的胎座。",},
{S_DOMAIN: "真核域",S_KINGDOM: "植物界",S_PHYLUM: "被子植物门",S_CLASS: "双子叶植物纲",S_ORDER: "蔷薇目",S_FAMILY: "蔷薇科",INFO:"草本、灌木或小乔木，有刺或无刺，有时攀援状；叶互生，常有托叶；花两性，辐射对称，颜色各种；花托多少中空，花被即着生于其周缘；萼片4－5，有时具副萼；花瓣4－5或有时缺；雄蕊多数，周位，稀5或10；子房由1至多个、分离或合生的心皮所成，上位或下位；花柱分离或合生，顶生、侧生或基生；胚珠每室1至多颗；果为核果或聚合果，或为多数的瘦果藏于肉质或干燥的花托内，稀蒴果。",},
{S_DOMAIN: "真核域",S_KINGDOM: "植物界",S_PHYLUM: "被子植物门",S_CLASS: "双子叶植物纲",S_ORDER: "马兜铃目",},
{S_DOMAIN: "真核域",S_KINGDOM: "植物界",S_PHYLUM: "被子植物门",S_CLASS: "双子叶植物纲",S_ORDER: "蛇菰目",},
{S_DOMAIN: "真核域",S_KINGDOM: "植物界",S_PHYLUM: "被子植物门",S_CLASS: "双子叶植物纲",S_ORDER: "中央种子目",},
{S_DOMAIN: "真核域",S_KINGDOM: "植物界",S_PHYLUM: "被子植物门",S_CLASS: "双子叶植物纲",S_ORDER: "大戟目",INFO: "木本，少数为草本。单叶，有时为复叶。花单性，通常较小，常无花瓣;雄蕊多数至1个；花盘存在或缺如；雌蕊由2-5(稀多数)心皮合成；子房上位，多室，常3室，胚珠每室1-2。种子有丰富的胚乳。",},
{S_DOMAIN: "真核域",S_KINGDOM: "植物界",S_PHYLUM: "被子植物门",S_CLASS: "双子叶植物纲",S_ORDER: "大戟目",S_FAMILY: "大戟科",INFO: "草本或木本，体内常具乳汁；花单性，多为雌雄同株，雄蕊1至多数，雌蕊3，心皮合生、子房3室；多为蒴果。",},
{S_DOMAIN: "真核域",S_KINGDOM: "植物界",S_PHYLUM: "被子植物门",S_CLASS: "双子叶植物纲",S_ORDER: "山毛榉目",S_FAMILY: "壳斗科",TITLE: "板栗",F_GROUP: "wood",F_NAME: "banli01.jpg",},
{S_DOMAIN: "真核域",S_KINGDOM: "植物界",S_PHYLUM: "被子植物门",S_CLASS: "双子叶植物纲",S_ORDER: "牻牛儿苗目",INFO:"草本，少数为木本。花两性:稀单性，辐射对称或两侧对称。萼片5--3；常有1萼片向后延伸成距；花瓣5--3；雄蕊5--4或10--8；通常有花盘；子房合生或离生，中轴胎座，胚珠多数至1个。种子常无胚乳。",},
{S_DOMAIN: "真核域",S_KINGDOM: "植物界",S_PHYLUM: "被子植物门",S_CLASS: "双子叶植物纲",S_ORDER: "藤黄目",},
{S_DOMAIN: "真核域",S_KINGDOM: "植物界",S_PHYLUM: "被子植物门",S_CLASS: "双子叶植物纲",S_ORDER: "胡桃目",},
{S_DOMAIN: "真核域",S_KINGDOM: "植物界",S_PHYLUM: "被子植物门",S_CLASS: "双子叶植物纲",S_ORDER: "木兰目",},
{S_DOMAIN: "真核域",S_KINGDOM: "植物界",S_PHYLUM: "被子植物门",S_CLASS: "双子叶植物纲",S_ORDER: "锦葵目",S_FAMILY: "木棉科",TITLE: "木棉",F_GROUP: "wood",F_NAME: "mumianmaque.jpg,guo22.jpg",},
{S_DOMAIN: "真核域",S_KINGDOM: "植物界",S_PHYLUM: "被子植物门",S_CLASS: "双子叶植物纲",S_ORDER: "锦葵目",S_FAMILY: "锦葵科",TITLE: "朱槿",F_GROUP: "wood",F_NAME: "huarui01.jpg",},
{S_DOMAIN: "真核域",S_KINGDOM: "植物界",S_PHYLUM: "被子植物门",S_CLASS: "双子叶植物纲",S_ORDER: "杨梅目",S_FAMILY: "杨梅科",TITLE: "杨梅子",F_GROUP: "wood",F_NAME: "yangmei01.jpg,yangmei02.jpg",},
{S_DOMAIN: "真核域",S_KINGDOM: "植物界",S_PHYLUM: "被子植物门",S_CLASS: "双子叶植物纲",S_ORDER: "桃金娘目",INFO: "周位花，心皮合生，花柱1个。多数为木本，很少是草本，叶通常对生，单叶全缘，常无托叶。花整齐，两性，花被2层，通常4片(或5、6片)，雄蕊数目和花瓣数目相等，或为其2倍，或为多数，有群生成束的倾向。花柱1个，柱头头状，中轴胎座。花托常成管状萼筒，形成周位花；萼筒与子房分离，或互相结合而成子房下位。",},
{S_DOMAIN: "真核域",S_KINGDOM: "植物界",S_PHYLUM: "被子植物门",S_CLASS: "双子叶植物纲",S_ORDER: "仙人掌目",S_FAMILY: "仙人掌科",TITLE: "仙人掌",F_GROUP: "wood",F_NAME: "xianrenz01.jpg",},
{S_DOMAIN: "真核域",S_KINGDOM: "植物界",S_PHYLUM: "被子植物门",S_CLASS: "双子叶植物纲",S_ORDER: "攀打目",},
{S_DOMAIN: "真核域",S_KINGDOM: "植物界",S_PHYLUM: "被子植物门",S_CLASS: "双子叶植物纲",S_ORDER: "侧膜胎座目",S_FAMILY: "堇菜科",TITLE: "长萼堇菜",F_GROUP: "wood",F_NAME: "zihuacao.jpg",},
{S_DOMAIN: "真核域",S_KINGDOM: "植物界",S_PHYLUM: "被子植物门",S_CLASS: "双子叶植物纲",S_ORDER: "侧膜胎座目",S_FAMILY: "秋海棠科",TITLE: "四季秋海棠",F_GROUP: "wood",F_NAME: "haitang01.jpg",},
{S_DOMAIN: "真核域",S_KINGDOM: "植物界",S_PHYLUM: "被子植物门",S_CLASS: "双子叶植物纲",S_ORDER: "侧膜胎座目",S_FAMILY: "西番莲科",TITLE: "百香果",F_GROUP: "wood",F_NAME: "lvguo.jpg",},
{S_DOMAIN: "真核域",S_KINGDOM: "植物界",S_PHYLUM: "被子植物门",S_CLASS: "双子叶植物纲",S_ORDER: "侧膜胎座目",S_FAMILY: "番木瓜科",TITLE: "番木瓜",F_GROUP: "wood",F_NAME: "fmg01.jpg",},
{S_DOMAIN: "真核域",S_KINGDOM: "植物界",S_PHYLUM: "被子植物门",S_CLASS: "双子叶植物纲",S_ORDER: "胡椒目",S_FAMILY: "三白草科",TITLE: "鱼腥草",F_GROUP: "wood",F_NAME: "yuxingcao01.jpg",},
{S_DOMAIN: "真核域",S_KINGDOM: "植物界",S_PHYLUM: "被子植物门",S_CLASS: "双子叶植物纲",S_ORDER: "川苔草目",},
{S_DOMAIN: "真核域",S_KINGDOM: "植物界",S_PHYLUM: "被子植物门",S_CLASS: "双子叶植物纲",S_ORDER: "蓼目",S_FAMILY: "蓼科",TITLE: "杠板归",F_GROUP: "wood",F_NAME: "kbg01.jpg,kbg02.jpg,languo.jpg",},
{S_DOMAIN: "真核域",S_KINGDOM: "植物界",S_PHYLUM: "被子植物门",S_CLASS: "双子叶植物纲",S_ORDER: "蓼目",S_FAMILY: "蓼科",TITLE: "长鬃蓼",F_GROUP: "wood",F_NAME: "huozi03.jpg",},
{S_DOMAIN: "真核域",S_KINGDOM: "植物界",S_PHYLUM: "被子植物门",S_CLASS: "双子叶植物纲",S_ORDER: "山龙眼目",S_FAMILY: "山龙眼科",TITLE: "银桦",F_GROUP: "wood",F_NAME: "yh01.jpg",},
{S_DOMAIN: "真核域",S_KINGDOM: "植物界",S_PHYLUM: "被子植物门",S_CLASS: "双子叶植物纲",S_ORDER: "毛茛目",S_FAMILY: "睡莲科",TITLE: "荷",F_GROUP: "wood",F_NAME: "hehua.jpg,lianhua02.jpg,112.jpg,lianpeng01.jpg,",},
{S_DOMAIN: "真核域",S_KINGDOM: "植物界",S_PHYLUM: "被子植物门",S_CLASS: "双子叶植物纲",S_ORDER: "毛茛目",S_FAMILY: "樟科",TITLE: "樟树",F_GROUP: "scene",F_NAME: "wangtian.jpg",},
{S_DOMAIN: "真核域",S_KINGDOM: "植物界",S_PHYLUM: "被子植物门",S_CLASS: "双子叶植物纲",S_ORDER: "毛茛目",S_FAMILY: "小檗科",TITLE: "南天竹",F_GROUP: "scene",F_NAME: "baihuaxiao.jpg,ntzguo01.jpg",},
{S_DOMAIN: "真核域",S_KINGDOM: "植物界",S_PHYLUM: "被子植物门",S_CLASS: "双子叶植物纲",S_ORDER: "鼠李目",},
{S_DOMAIN: "真核域",S_KINGDOM: "植物界",S_PHYLUM: "被子植物门",S_CLASS: "双子叶植物纲",S_ORDER: "罂粟目",S_FAMILY: "山柑科",TITLE: "醉蝶花",F_GROUP: "wood",F_NAME: "zdh01.jpg",},
{S_DOMAIN: "真核域",S_KINGDOM: "植物界",S_PHYLUM: "被子植物门",S_CLASS: "双子叶植物纲",S_ORDER: "芸香目",S_FAMILY: "芸香科",TITLE: "橘子",F_GROUP: "wood",F_NAME: "juzi01.jpg",},
{S_DOMAIN: "真核域",S_KINGDOM: "植物界",S_PHYLUM: "被子植物门",S_CLASS: "双子叶植物纲",S_ORDER: "芸香目",S_FAMILY: "芸香科",TITLE: "臭檀吴萸",F_GROUP: "wood",F_NAME: "heixiaoguo01.jpg",},
{S_DOMAIN: "真核域",S_KINGDOM: "植物界",S_PHYLUM: "被子植物门",S_CLASS: "双子叶植物纲",S_ORDER: "杨柳目",S_FAMILY: "杨柳科",TITLE: "柳树",F_GROUP: "miao",F_NAME: "shulu.jpg",},
{S_DOMAIN: "真核域",S_KINGDOM: "植物界",S_PHYLUM: "被子植物门",S_CLASS: "双子叶植物纲",S_ORDER: "檀香目",},
{S_DOMAIN: "真核域",S_KINGDOM: "植物界",S_PHYLUM: "被子植物门",S_CLASS: "双子叶植物纲",S_ORDER: "无患子目",S_FAMILY: "漆树科",TITLE: "芒果",F_GROUP: "wood",F_NAME: "guo10.jpg",},
{S_DOMAIN: "真核域",S_KINGDOM: "植物界",S_PHYLUM: "被子植物门",S_CLASS: "双子叶植物纲",S_ORDER: "瓶子草目",},
{S_DOMAIN: "真核域",S_KINGDOM: "植物界",S_PHYLUM: "被子植物门",S_CLASS: "双子叶植物纲",S_ORDER: "伞形目",S_FAMILY: "伞形科",TITLE: "蛇床",F_GROUP: "wood",F_NAME: "bai52.jpg,cao1.jpg",},
{S_DOMAIN: "真核域",S_KINGDOM: "植物界",S_PHYLUM: "被子植物门",S_CLASS: "双子叶植物纲",S_ORDER: "伞形目",S_FAMILY: "伞形科",TITLE: "铜钱草",F_GROUP: "wood",F_NAME: "tongqiancao.jpg",},
{S_DOMAIN: "真核域",S_KINGDOM: "植物界",S_PHYLUM: "被子植物门",S_CLASS: "双子叶植物纲",S_ORDER: "伞形目",S_FAMILY: "伞形科",TITLE: "积雪草",F_GROUP: "wood",F_NAME: "jxc01.jpg",},
{S_DOMAIN: "真核域",S_KINGDOM: "植物界",S_PHYLUM: "被子植物门",S_CLASS: "双子叶植物纲",S_ORDER: "荨麻目",},
{S_DOMAIN: "真核域",S_KINGDOM: "植物界",S_PHYLUM: "被子植物门",S_CLASS: "双子叶植物纲",S_ORDER: "轮生目",},
{S_DOMAIN: "真核域",S_KINGDOM: "植物界",S_PHYLUM: "被子植物门",S_CLASS: "双子叶植物纲",S_ORDER: "桔梗目",},
{S_DOMAIN: "真核域",S_KINGDOM: "植物界",S_PHYLUM: "被子植物门",S_CLASS: "双子叶植物纲",S_ORDER: "捩花目",},
{S_DOMAIN: "真核域",S_KINGDOM: "植物界",S_PHYLUM: "被子植物门",S_CLASS: "双子叶植物纲",S_ORDER: "葫芦目",},
{S_DOMAIN: "真核域",S_KINGDOM: "植物界",S_PHYLUM: "被子植物门",S_CLASS: "双子叶植物纲",S_ORDER: "岩梅目",},
{S_DOMAIN: "真核域",S_KINGDOM: "植物界",S_PHYLUM: "被子植物门",S_CLASS: "双子叶植物纲",S_ORDER: "柿目",S_FAMILY: "柿科",TITLE: "柿子",F_GROUP: "wood",F_NAME: "shizi01.jpg",},
{S_DOMAIN: "真核域",S_KINGDOM: "植物界",S_PHYLUM: "被子植物门",S_CLASS: "双子叶植物纲",S_ORDER: "杜鹃花目",S_FAMILY: "杜鹃花科",TITLE: "杜鹃花",F_GROUP: "wood",F_NAME: "zihua2.jpg,fenhua01.jpg",},
{S_DOMAIN: "真核域",S_KINGDOM: "植物界",S_PHYLUM: "被子植物门",S_CLASS: "双子叶植物纲",S_ORDER: "车前目",S_FAMILY: "车前科",TITLE: "车前草",F_GROUP: "wood",F_NAME: "cheqian01.jpg",},
{S_DOMAIN: "真核域",S_KINGDOM: "植物界",S_PHYLUM: "被子植物门",S_CLASS: "双子叶植物纲",S_ORDER: "白花丹目",},
{S_DOMAIN: "真核域",S_KINGDOM: "植物界",S_PHYLUM: "被子植物门",S_CLASS: "双子叶植物纲",S_ORDER: "报春花目",},
{S_DOMAIN: "真核域",S_KINGDOM: "植物界",S_PHYLUM: "被子植物门",S_CLASS: "双子叶植物纲",S_ORDER: "唇形目",INFO: "唇形目（学名：Lamiales）也被称为玄参目（Scrophulariales），是一类双子叶植物，木本或草本，其中玄参科常含有生物碱和甙类，所以很多种都可以作为药用，也有一些观赏植物花卉。本目包括木犀科、玄参科、唇形科、车前科、列当科、紫葳科、爵床科、苦苣苔科、狸藻科、马鞭草科、醉鱼草科、透骨草科等25科。",},
{S_DOMAIN: "真核域",S_KINGDOM: "植物界",S_PHYLUM: "被子植物门",S_CLASS: "双子叶植物纲",S_ORDER: "金虎尾目",INFO: "APG 分类法设立了这个目，在I类真蔷薇分支下面，其中许多科原来是被分在许多其他不同的目中的，像大戟目、杨柳目、堇菜目、山茶目等。《APG 分类法》设立了32个科，2003年修订的《APG II 分类法》剔除了几个科，又合并了几个科，已知共有36个科。",},
{S_DOMAIN: "真核域",S_KINGDOM: "植物界",S_PHYLUM: "被子植物门",S_CLASS: "双子叶植物纲",S_ORDER: "茜草目",S_FAMILY: "茜草科",TITLE: "鸡眼藤",F_GROUP: "wood",F_NAME: "hongguo01.jpg",},
{S_DOMAIN: "真核域",S_KINGDOM: "植物界",S_PHYLUM: "被子植物门",S_CLASS: "双子叶植物纲",S_ORDER: "管状花目",INFO: "大多为草本，也有灌木、乔木或木质藤本；不具托叶。花两性，很少单性，下位花，典型地为5基数的四轮，或通常心皮数减少，如为左右对称花时雄蕊数也减少；花冠合瓣，整齐或左右对称；虫媒花；雄蕊着生于花冠上；心皮通常2个，合生，纵向的，子房通常有假隔膜；胚珠少数至多数，倒生，稀横生或直生，珠孔向上或向下，稀侧向，1层珠被。",},
/*{S_DOMAIN: "真核域",S_KINGDOM: "动物界",S_PHYLUM: "原生动物门",S_CLASS: "未知纲",S_ORDER: "未知目",},
{S_DOMAIN: "真核域",S_KINGDOM: "动物界",S_PHYLUM: "菱形虫门",S_CLASS: "未知纲",S_ORDER: "未知目",},
{S_DOMAIN: "真核域",S_KINGDOM: "动物界",S_PHYLUM: "直泳虫门",S_CLASS: "未知纲",S_ORDER: "未知目",},
{S_DOMAIN: "真核域",S_KINGDOM: "动物界",S_PHYLUM: "多孔动物门",S_CLASS: "未知纲",S_ORDER: "未知目",},
{S_DOMAIN: "真核域",S_KINGDOM: "动物界",S_PHYLUM: "扁盘动物门",S_CLASS: "未知纲",S_ORDER: "未知目",},
{S_DOMAIN: "真核域",S_KINGDOM: "动物界",S_PHYLUM: "古杯动物门",S_CLASS: "未知纲",S_ORDER: "未知目",},
{S_DOMAIN: "真核域",S_KINGDOM: "动物界",S_PHYLUM: "腔肠动物门",S_CLASS: "未知纲",S_ORDER: "未知目",},
{S_DOMAIN: "真核域",S_KINGDOM: "动物界",S_PHYLUM: "栉水母动物门",S_CLASS: "未知纲",S_ORDER: "未知目",},
{S_DOMAIN: "真核域",S_KINGDOM: "动物界",S_PHYLUM: "扁形动物门",S_CLASS: "未知纲",S_ORDER: "未知目",},
{S_DOMAIN: "真核域",S_KINGDOM: "动物界",S_PHYLUM: "环节动物门",S_CLASS: "多毛纲",S_ORDER: "未知目",},
{S_DOMAIN: "真核域",S_KINGDOM: "动物界",S_PHYLUM: "环节动物门",S_CLASS: "蛭纲",S_ORDER: "未知目",},*/
{S_DOMAIN: "真核域",S_KINGDOM: "动物界",S_PHYLUM: "环节动物门",S_CLASS: "寡毛纲",S_ORDER: "带丝蚓目",},
{S_DOMAIN: "真核域",S_KINGDOM: "动物界",S_PHYLUM: "环节动物门",S_CLASS: "寡毛纲",S_ORDER: "颤蚓目",},
{S_DOMAIN: "真核域",S_KINGDOM: "动物界",S_PHYLUM: "环节动物门",S_CLASS: "寡毛纲",S_ORDER: "单向蚓目",TITLE: "蚯蚓",F_GROUP: "miao",F_NAME: "qiuyin01.jpg",},
/*{S_DOMAIN: "真核域",S_KINGDOM: "动物界",S_PHYLUM: "螠虫动物门",S_CLASS: "未知纲",S_ORDER: "未知目",},
{S_DOMAIN: "真核域",S_KINGDOM: "动物界",S_PHYLUM: "纽形动物门",S_CLASS: "未知纲",S_ORDER: "未知目",},
{S_DOMAIN: "真核域",S_KINGDOM: "动物界",S_PHYLUM: "线虫动物门",S_CLASS: "未知纲",S_ORDER: "未知目",},
{S_DOMAIN: "真核域",S_KINGDOM: "动物界",S_PHYLUM: "线形动物门",S_CLASS: "未知纲",S_ORDER: "未知目",},
{S_DOMAIN: "真核域",S_KINGDOM: "动物界",S_PHYLUM: "星虫动物门",S_CLASS: "未知纲",S_ORDER: "未知目",},
{S_DOMAIN: "真核域",S_KINGDOM: "动物界",S_PHYLUM: "棘头动物门",S_CLASS: "未知纲",S_ORDER: "未知目",},
{S_DOMAIN: "真核域",S_KINGDOM: "动物界",S_PHYLUM: "须腕动物门",S_CLASS: "未知纲",S_ORDER: "未知目",},
{S_DOMAIN: "真核域",S_KINGDOM: "动物界",S_PHYLUM: "毛颚动物门",S_CLASS: "未知纲",S_ORDER: "未知目",},
{S_DOMAIN: "真核域",S_KINGDOM: "动物界",S_PHYLUM: "软体动物门",S_CLASS: "无板纲",S_ORDER: "未知目",},
{S_DOMAIN: "真核域",S_KINGDOM: "动物界",S_PHYLUM: "软体动物门",S_CLASS: "多板纲",S_ORDER: "未知目",},
{S_DOMAIN: "真核域",S_KINGDOM: "动物界",S_PHYLUM: "软体动物门",S_CLASS: "掘足纲",S_ORDER: "未知目",},
{S_DOMAIN: "真核域",S_KINGDOM: "动物界",S_PHYLUM: "软体动物门",S_CLASS: "双壳纲",S_ORDER: "未知目",},
{S_DOMAIN: "真核域",S_KINGDOM: "动物界",S_PHYLUM: "软体动物门",S_CLASS: "头足纲",S_ORDER: "未知目",},*/
{S_DOMAIN: "真核域",S_KINGDOM: "动物界",S_PHYLUM: "软体动物门",S_CLASS: "腹足纲",S_ORDER: "古腹足目",},
{S_DOMAIN: "真核域",S_KINGDOM: "动物界",S_PHYLUM: "软体动物门",S_CLASS: "腹足纲",S_ORDER: "中腹足目",S_FAMILY: "玉黍螺科",TITLE: "玉黍螺",F_GROUP: "miao",F_NAME: "luo02.jpg",},
{S_DOMAIN: "真核域",S_KINGDOM: "动物界",S_PHYLUM: "软体动物门",S_CLASS: "腹足纲",S_ORDER: "中腹足目",S_FAMILY: "田螺科",TITLE: "田螺",F_GROUP: "miao",F_NAME: "luo03.jpg",},
{S_DOMAIN: "真核域",S_KINGDOM: "动物界",S_PHYLUM: "软体动物门",S_CLASS: "腹足纲",S_ORDER: "新腹足目",},
{S_DOMAIN: "真核域",S_KINGDOM: "动物界",S_PHYLUM: "软体动物门",S_CLASS: "腹足纲",S_ORDER: "无楯目",},
{S_DOMAIN: "真核域",S_KINGDOM: "动物界",S_PHYLUM: "软体动物门",S_CLASS: "腹足纲",S_ORDER: "被壳翼足目",},
{S_DOMAIN: "真核域",S_KINGDOM: "动物界",S_PHYLUM: "软体动物门",S_CLASS: "腹足纲",S_ORDER: "裸体翼足目",},
{S_DOMAIN: "真核域",S_KINGDOM: "动物界",S_PHYLUM: "软体动物门",S_CLASS: "腹足纲",S_ORDER: "囊舌目",},
{S_DOMAIN: "真核域",S_KINGDOM: "动物界",S_PHYLUM: "软体动物门",S_CLASS: "腹足纲",S_ORDER: "背楯目",},
{S_DOMAIN: "真核域",S_KINGDOM: "动物界",S_PHYLUM: "软体动物门",S_CLASS: "腹足纲",S_ORDER: "裸鳃目",},
{S_DOMAIN: "真核域",S_KINGDOM: "动物界",S_PHYLUM: "软体动物门",S_CLASS: "腹足纲",S_ORDER: "基眼目",},
{S_DOMAIN: "真核域",S_KINGDOM: "动物界",S_PHYLUM: "软体动物门",S_CLASS: "腹足纲",S_ORDER: "柄眼目",S_FAMILY: "蜗牛科",TITLE: "蜗牛",F_GROUP: "miao",F_NAME: "woniu01.jpg",},
{S_DOMAIN: "真核域",S_KINGDOM: "动物界",S_PHYLUM: "软体动物门",S_CLASS: "腹足纲",S_ORDER: "柄眼目",S_FAMILY: "玛瑙螺科",TITLE: "非洲大蜗牛",F_GROUP: "miao",F_NAME: "luo01.jpg",},
{S_DOMAIN: "真核域",S_KINGDOM: "动物界",S_PHYLUM: "软体动物门",S_CLASS: "腹足纲",S_ORDER: "柄眼目",S_FAMILY: "蛞蝓科",TITLE: "蛞蝓",F_GROUP: "miao",F_NAME: "kuoyu01.jpg",},
{S_DOMAIN: "真核域",S_KINGDOM: "动物界",S_PHYLUM: "软体动物门",S_CLASS: "瓣鳃纲",S_ORDER: "异柱目",TITLE: "贻贝",F_GROUP: "miao",F_NAME: "bei01.jpg",},
/*{S_DOMAIN: "真核域",S_KINGDOM: "动物界",S_PHYLUM: "节肢动物门",S_CLASS: "三叶虫纲",S_ORDER: "未知目",},
{S_DOMAIN: "真核域",S_KINGDOM: "动物界",S_PHYLUM: "节肢动物门",S_CLASS: "颚足纲",S_ORDER: "未知目",},
{S_DOMAIN: "真核域",S_KINGDOM: "动物界",S_PHYLUM: "节肢动物门",S_CLASS: "内口纲",S_ORDER: "未知目",},
{S_DOMAIN: "真核域",S_KINGDOM: "动物界",S_PHYLUM: "节肢动物门",S_CLASS: "海蜘蛛纲",S_ORDER: "未知目",},
{S_DOMAIN: "真核域",S_KINGDOM: "动物界",S_PHYLUM: "节肢动物门",S_CLASS: "头虾纲",S_ORDER: "未知目",},
{S_DOMAIN: "真核域",S_KINGDOM: "动物界",S_PHYLUM: "节肢动物门",S_CLASS: "桨足纲",S_ORDER: "未知目",},
{S_DOMAIN: "真核域",S_KINGDOM: "动物界",S_PHYLUM: "节肢动物门",S_CLASS: "鳃足纲",S_ORDER: "未知目",},
{S_DOMAIN: "真核域",S_KINGDOM: "动物界",S_PHYLUM: "节肢动物门",S_CLASS: "少足纲",S_ORDER: "未知目",},
{S_DOMAIN: "真核域",S_KINGDOM: "动物界",S_PHYLUM: "节肢动物门",S_CLASS: "综合纲",S_ORDER: "未知目",},*/
{S_DOMAIN: "真核域",S_KINGDOM: "动物界",S_PHYLUM: "节肢动物门",S_CLASS: "肢口纲",S_ORDER: "剑尾目",TITLE: "鲎",F_GROUP: "miao",F_NAME: "hou02.jpg",},
{S_DOMAIN: "真核域",S_KINGDOM: "动物界",S_PHYLUM: "节肢动物门",S_CLASS: "蛛形纲",S_ORDER: "蝎目",TITLE: "蝎",F_GROUP: "wai",F_NAME: "xm01.jpg",},
{S_DOMAIN: "真核域",S_KINGDOM: "动物界",S_PHYLUM: "节肢动物门",S_CLASS: "蛛形纲",S_ORDER: "伪蝎目",},
{S_DOMAIN: "真核域",S_KINGDOM: "动物界",S_PHYLUM: "节肢动物门",S_CLASS: "蛛形纲",S_ORDER: "盲蛛目",TITLE: "盲蛛",F_GROUP: "wai",F_NAME: "mzm01.jpg",},
{S_DOMAIN: "真核域",S_KINGDOM: "动物界",S_PHYLUM: "节肢动物门",S_CLASS: "蛛形纲",S_ORDER: "蜱螨目",TITLE: "螨虫",F_GROUP: "bug",F_NAME: "manc01.jpg",},
{S_DOMAIN: "真核域",S_KINGDOM: "动物界",S_PHYLUM: "节肢动物门",S_CLASS: "蛛形纲",S_ORDER: "须脚目",},
{S_DOMAIN: "真核域",S_KINGDOM: "动物界",S_PHYLUM: "节肢动物门",S_CLASS: "蛛形纲",S_ORDER: "有鞭目",},
{S_DOMAIN: "真核域",S_KINGDOM: "动物界",S_PHYLUM: "节肢动物门",S_CLASS: "蛛形纲",S_ORDER: "裂盾目",},
{S_DOMAIN: "真核域",S_KINGDOM: "动物界",S_PHYLUM: "节肢动物门",S_CLASS: "蛛形纲",S_ORDER: "无鞭目",},
{S_DOMAIN: "真核域",S_KINGDOM: "动物界",S_PHYLUM: "节肢动物门",S_CLASS: "蛛形纲",S_ORDER: "蜘蛛目",TITLE: "蜘蛛",F_GROUP: "bug",F_NAME: "zhu09.jpg",},
{S_DOMAIN: "真核域",S_KINGDOM: "动物界",S_PHYLUM: "节肢动物门",S_CLASS: "蛛形纲",S_ORDER: "节腹目",},
{S_DOMAIN: "真核域",S_KINGDOM: "动物界",S_PHYLUM: "节肢动物门",S_CLASS: "蛛形纲",S_ORDER: "避日目",TITLE: "避日蛛",F_GROUP: "wai",F_NAME: "brm01.jpg",},
{S_DOMAIN: "真核域",S_KINGDOM: "动物界",S_PHYLUM: "节肢动物门",S_CLASS: "软甲纲",S_ORDER: "涟虫目",},
{S_DOMAIN: "真核域",S_KINGDOM: "动物界",S_PHYLUM: "节肢动物门",S_CLASS: "软甲纲",S_ORDER: "十足目",TITLE: "螃蟹",F_GROUP: "miao",F_NAME: "xie07.jpg",},
{S_DOMAIN: "真核域",S_KINGDOM: "动物界",S_PHYLUM: "节肢动物门",S_CLASS: "软甲纲",S_ORDER: "口足目",},
{S_DOMAIN: "真核域",S_KINGDOM: "动物界",S_PHYLUM: "节肢动物门",S_CLASS: "软甲纲",S_ORDER: "原足目",},
{S_DOMAIN: "真核域",S_KINGDOM: "动物界",S_PHYLUM: "节肢动物门",S_CLASS: "软甲纲",S_ORDER: "等足目",TITLE: "海蟑螂",F_GROUP: "miao",F_NAME: "haizhanglang01.jpg",},
{S_DOMAIN: "真核域",S_KINGDOM: "动物界",S_PHYLUM: "节肢动物门",S_CLASS: "软甲纲",S_ORDER: "端足目",},
{S_DOMAIN: "真核域",S_KINGDOM: "动物界",S_PHYLUM: "节肢动物门",S_CLASS: "软甲纲",S_ORDER: "混足目",},
{S_DOMAIN: "真核域",S_KINGDOM: "动物界",S_PHYLUM: "节肢动物门",S_CLASS: "软甲纲",S_ORDER: "异虾目",},
{S_DOMAIN: "真核域",S_KINGDOM: "动物界",S_PHYLUM: "节肢动物门",S_CLASS: "软甲纲",S_ORDER: "叶虾目",},
{S_DOMAIN: "真核域",S_KINGDOM: "动物界",S_PHYLUM: "节肢动物门",S_CLASS: "软甲纲",S_ORDER: "磷虾目",},
{S_DOMAIN: "真核域",S_KINGDOM: "动物界",S_PHYLUM: "节肢动物门",S_CLASS: "软甲纲",S_ORDER: "糠虾目",},
{S_DOMAIN: "真核域",S_KINGDOM: "动物界",S_PHYLUM: "节肢动物门",S_CLASS: "软甲纲",S_ORDER: "山虾目",},
{S_DOMAIN: "真核域",S_KINGDOM: "动物界",S_PHYLUM: "节肢动物门",S_CLASS: "软甲纲",S_ORDER: "地虾目",},
{S_DOMAIN: "真核域",S_KINGDOM: "动物界",S_PHYLUM: "节肢动物门",S_CLASS: "软甲纲",S_ORDER: "洞虾目",},
{S_DOMAIN: "真核域",S_KINGDOM: "动物界",S_PHYLUM: "节肢动物门",S_CLASS: "软甲纲",S_ORDER: "温泉虾目",},
{S_DOMAIN: "真核域",S_KINGDOM: "动物界",S_PHYLUM: "节肢动物门",S_CLASS: "软甲纲",S_ORDER: "疣背糠虾目",},
{S_DOMAIN: "真核域",S_KINGDOM: "动物界",S_PHYLUM: "节肢动物门",S_CLASS: "蔓足纲",S_ORDER: "无柄目",TITLE: "藤壶",F_GROUP: "scene",F_NAME: "haishi.jpg",},
{S_DOMAIN: "真核域",S_KINGDOM: "动物界",S_PHYLUM: "节肢动物门",S_CLASS: "昆虫纲",S_ORDER: "石蛃目",TITLE: "石蛃",F_GROUP: "wai",F_NAME: "sbm01.jpg",},
{S_DOMAIN: "真核域",S_KINGDOM: "动物界",S_PHYLUM: "节肢动物门",S_CLASS: "昆虫纲",S_ORDER: "衣鱼目",TITLE: "衣鱼",F_GROUP: "bug",F_NAME: "yiyu01.jpg",},
{S_DOMAIN: "真核域",S_KINGDOM: "动物界",S_PHYLUM: "节肢动物门",S_CLASS: "昆虫纲",S_ORDER: "蜉蝣目",TITLE: "蜉蝣",F_GROUP: "wai",F_NAME: "fym01.jpg",},
{S_DOMAIN: "真核域",S_KINGDOM: "动物界",S_PHYLUM: "节肢动物门",S_CLASS: "昆虫纲",S_ORDER: "蜻蜓目",S_FAMILY: "蜓科",TITLE: "蜻蜓",F_GROUP: "bug",F_NAME: "qingting11.jpg",},
{S_DOMAIN: "真核域",S_KINGDOM: "动物界",S_PHYLUM: "节肢动物门",S_CLASS: "昆虫纲",S_ORDER: "蜻蜓目",S_FAMILY: "色蟌科",TITLE: "色蟌",F_GROUP: "bug",F_NAME: "douniang02.jpg",},
{S_DOMAIN: "真核域",S_KINGDOM: "动物界",S_PHYLUM: "节肢动物门",S_CLASS: "昆虫纲",S_ORDER: "襀翅目",TITLE: "石蝇",F_GROUP: "bug",F_NAME: "shiying03.jpg",},
{S_DOMAIN: "真核域",S_KINGDOM: "动物界",S_PHYLUM: "节肢动物门",S_CLASS: "昆虫纲",S_ORDER: "蜚蠊目",S_FAMILY: "蜚蠊科",TITLE: "蟑螂",F_GROUP: "bug",F_NAME: "zhanglang01.jpg",},
{S_DOMAIN: "真核域",S_KINGDOM: "动物界",S_PHYLUM: "节肢动物门",S_CLASS: "昆虫纲",S_ORDER: "蜚蠊目",S_FAMILY: "白蚁科",TITLE: "白蚁",F_GROUP: "bug",F_NAME: "baiyi01.jpg",},
{S_DOMAIN: "真核域",S_KINGDOM: "动物界",S_PHYLUM: "节肢动物门",S_CLASS: "昆虫纲",S_ORDER: "螳螂目",TITLE: "螳螂",F_GROUP: "bug",F_NAME: "tanglang01.jpg",},
{S_DOMAIN: "真核域",S_KINGDOM: "动物界",S_PHYLUM: "节肢动物门",S_CLASS: "昆虫纲",S_ORDER: "蛩蠊目",TITLE: "蛩蠊",F_GROUP: "wai",F_NAME: "qlm01.jpg",},
{S_DOMAIN: "真核域",S_KINGDOM: "动物界",S_PHYLUM: "节肢动物门",S_CLASS: "昆虫纲",S_ORDER: "螳䗛目",TITLE: "螳䗛",F_GROUP: "wai",F_NAME: "txm01.jpg",},
{S_DOMAIN: "真核域",S_KINGDOM: "动物界",S_PHYLUM: "节肢动物门",S_CLASS: "昆虫纲",S_ORDER: "竹节虫目",TITLE: "竹节虫",F_GROUP: "bug",F_NAME: "zhujie01.jpg",},
{S_DOMAIN: "真核域",S_KINGDOM: "动物界",S_PHYLUM: "节肢动物门",S_CLASS: "昆虫纲",S_ORDER: "纺足目",},
{S_DOMAIN: "真核域",S_KINGDOM: "动物界",S_PHYLUM: "节肢动物门",S_CLASS: "昆虫纲",S_ORDER: "直翅目",},
{S_DOMAIN: "真核域",S_KINGDOM: "动物界",S_PHYLUM: "节肢动物门",S_CLASS: "昆虫纲",S_ORDER: "革翅目",TITLE: "蠼螋",F_GROUP: "bug",F_NAME: "qusou02.jpg",},
{S_DOMAIN: "真核域",S_KINGDOM: "动物界",S_PHYLUM: "节肢动物门",S_CLASS: "昆虫纲",S_ORDER: "缺翅目",},
{S_DOMAIN: "真核域",S_KINGDOM: "动物界",S_PHYLUM: "节肢动物门",S_CLASS: "昆虫纲",S_ORDER: "虱目",},
{S_DOMAIN: "真核域",S_KINGDOM: "动物界",S_PHYLUM: "节肢动物门",S_CLASS: "昆虫纲",S_ORDER: "啮虫目",},
{S_DOMAIN: "真核域",S_KINGDOM: "动物界",S_PHYLUM: "节肢动物门",S_CLASS: "昆虫纲",S_ORDER: "缨翅目",},
{S_DOMAIN: "真核域",S_KINGDOM: "动物界",S_PHYLUM: "节肢动物门",S_CLASS: "昆虫纲",S_ORDER: "半翅目",S_FAMILY: "蝽科",TITLE: "椿象",F_GROUP: "bug",F_NAME: "chunxiang01.jpg",},
{S_DOMAIN: "真核域",S_KINGDOM: "动物界",S_PHYLUM: "节肢动物门",S_CLASS: "昆虫纲",S_ORDER: "半翅目",S_FAMILY: "蝉科",TITLE: "蝉",F_GROUP: "bug",F_NAME: "zhiliao02.jpg",},
{S_DOMAIN: "真核域",S_KINGDOM: "动物界",S_PHYLUM: "节肢动物门",S_CLASS: "昆虫纲",S_ORDER: "半翅目",S_FAMILY: "蜡蝉科",TITLE: "碧蛾蜡蝉",F_GROUP: "bug",F_NAME: "die23.jpg",},
{S_DOMAIN: "真核域",S_KINGDOM: "动物界",S_PHYLUM: "节肢动物门",S_CLASS: "昆虫纲",S_ORDER: "脉翅目",TITLE: "蚜狮",F_GROUP: "bug",F_NAME: "yashi01.jpg",},
{S_DOMAIN: "真核域",S_KINGDOM: "动物界",S_PHYLUM: "节肢动物门",S_CLASS: "昆虫纲",S_ORDER: "广翅目",TITLE: "中华斑鱼蛉",F_GROUP: "bug",F_NAME: "yuling01.jpg",},
{S_DOMAIN: "真核域",S_KINGDOM: "动物界",S_PHYLUM: "节肢动物门",S_CLASS: "昆虫纲",S_ORDER: "蛇蛉目",},
{S_DOMAIN: "真核域",S_KINGDOM: "动物界",S_PHYLUM: "节肢动物门",S_CLASS: "昆虫纲",S_ORDER: "鞘翅目",S_FAMILY: "天牛科",TITLE: "天牛",F_GROUP: "bug",F_NAME: "tianniu01.jpg",},
{S_DOMAIN: "真核域",S_KINGDOM: "动物界",S_PHYLUM: "节肢动物门",S_CLASS: "昆虫纲",S_ORDER: "鞘翅目",S_FAMILY: "金龟甲科",TITLE: "蜣螂",F_GROUP: "bug",F_NAME: "qiaochi23.jpg",},
{S_DOMAIN: "真核域",S_KINGDOM: "动物界",S_PHYLUM: "节肢动物门",S_CLASS: "昆虫纲",S_ORDER: "鞘翅目",S_FAMILY: "犀金龟科",TITLE: "荣瘤犀金龟",F_GROUP: "bug",F_NAME: "qiaochi22.jpg",},
{S_DOMAIN: "真核域",S_KINGDOM: "动物界",S_PHYLUM: "节肢动物门",S_CLASS: "昆虫纲",S_ORDER: "双翅目",TITLE: "苍蝇",F_GROUP: "bug",F_NAME: "cangying02.jpg",},
{S_DOMAIN: "真核域",S_KINGDOM: "动物界",S_PHYLUM: "节肢动物门",S_CLASS: "昆虫纲",S_ORDER: "蚤目",},
{S_DOMAIN: "真核域",S_KINGDOM: "动物界",S_PHYLUM: "节肢动物门",S_CLASS: "昆虫纲",S_ORDER: "捻翅目",},
{S_DOMAIN: "真核域",S_KINGDOM: "动物界",S_PHYLUM: "节肢动物门",S_CLASS: "昆虫纲",S_ORDER: "长翅目",},
{S_DOMAIN: "真核域",S_KINGDOM: "动物界",S_PHYLUM: "节肢动物门",S_CLASS: "昆虫纲",S_ORDER: "毛翅目",},
{S_DOMAIN: "真核域",S_KINGDOM: "动物界",S_PHYLUM: "节肢动物门",S_CLASS: "昆虫纲",S_ORDER: "鳞翅目",},
{S_DOMAIN: "真核域",S_KINGDOM: "动物界",S_PHYLUM: "节肢动物门",S_CLASS: "昆虫纲",S_ORDER: "膜翅目",TITLE: "蜜蜂",F_GROUP: "bug",F_NAME: "feng02.jpg",},
{S_DOMAIN: "真核域",S_KINGDOM: "动物界",S_PHYLUM: "节肢动物门",S_CLASS: "倍足纲",S_ORDER: "毛马陆目",},
{S_DOMAIN: "真核域",S_KINGDOM: "动物界",S_PHYLUM: "节肢动物门",S_CLASS: "倍足纲",S_ORDER: "蟠马陆目",},
{S_DOMAIN: "真核域",S_KINGDOM: "动物界",S_PHYLUM: "节肢动物门",S_CLASS: "倍足纲",S_ORDER: "蛞形目",},
{S_DOMAIN: "真核域",S_KINGDOM: "动物界",S_PHYLUM: "节肢动物门",S_CLASS: "倍足纲",S_ORDER: "山蛩目",TITLE: "山蛩",F_GROUP: "bug",F_NAME: "malu01.jpg",},
{S_DOMAIN: "真核域",S_KINGDOM: "动物界",S_PHYLUM: "节肢动物门",S_CLASS: "倍足纲",S_ORDER: "条马陆目",TITLE: "条马陆",F_GROUP: "bug",F_NAME: "wugong02.jpg",},
{S_DOMAIN: "真核域",S_KINGDOM: "动物界",S_PHYLUM: "节肢动物门",S_CLASS: "倍足纲",S_ORDER: "球马陆目",},
{S_DOMAIN: "真核域",S_KINGDOM: "动物界",S_PHYLUM: "节肢动物门",S_CLASS: "倍足纲",S_ORDER: "绩马陆目",},
{S_DOMAIN: "真核域",S_KINGDOM: "动物界",S_PHYLUM: "节肢动物门",S_CLASS: "倍足纲",S_ORDER: "带马陆目",},
{S_DOMAIN: "真核域",S_KINGDOM: "动物界",S_PHYLUM: "节肢动物门",S_CLASS: "倍足纲",S_ORDER: "姬马陆目",},
{S_DOMAIN: "真核域",S_KINGDOM: "动物界",S_PHYLUM: "节肢动物门",S_CLASS: "倍足纲",S_ORDER: "畸颚目",},
{S_DOMAIN: "真核域",S_KINGDOM: "动物界",S_PHYLUM: "节肢动物门",S_CLASS: "唇足纲",S_ORDER: "地蜈蚣目",},
{S_DOMAIN: "真核域",S_KINGDOM: "动物界",S_PHYLUM: "节肢动物门",S_CLASS: "唇足纲",S_ORDER: "蜈蚣目",TITLE: "蜈蚣",F_GROUP: "bug",F_NAME: "wugong01.jpg",},
{S_DOMAIN: "真核域",S_KINGDOM: "动物界",S_PHYLUM: "节肢动物门",S_CLASS: "唇足纲",S_ORDER: "石蜈蚣目",},
{S_DOMAIN: "真核域",S_KINGDOM: "动物界",S_PHYLUM: "节肢动物门",S_CLASS: "唇足纲",S_ORDER: "蚰蜒目",},
/*{S_DOMAIN: "真核域",S_KINGDOM: "动物界",S_PHYLUM: "叶足动物门",S_CLASS: "未知纲",S_ORDER: "未知目",},
{S_DOMAIN: "真核域",S_KINGDOM: "动物界",S_PHYLUM: "缓步动物门",S_CLASS: "未知纲",S_ORDER: "未知目",},
{S_DOMAIN: "真核域",S_KINGDOM: "动物界",S_PHYLUM: "有爪动物门",S_CLASS: "未知纲",S_ORDER: "未知目",},
{S_DOMAIN: "真核域",S_KINGDOM: "动物界",S_PHYLUM: "腹毛动物门",S_CLASS: "未知纲",S_ORDER: "未知目",},
{S_DOMAIN: "真核域",S_KINGDOM: "动物界",S_PHYLUM: "轮虫动物门",S_CLASS: "未知纲",S_ORDER: "未知目",},
{S_DOMAIN: "真核域",S_KINGDOM: "动物界",S_PHYLUM: "鳃曳动物门",S_CLASS: "未知纲",S_ORDER: "未知目",},
{S_DOMAIN: "真核域",S_KINGDOM: "动物界",S_PHYLUM: "动吻动物门",S_CLASS: "未知纲",S_ORDER: "未知目",},
{S_DOMAIN: "真核域",S_KINGDOM: "动物界",S_PHYLUM: "铠甲动物门",S_CLASS: "未知纲",S_ORDER: "未知目",},
{S_DOMAIN: "真核域",S_KINGDOM: "动物界",S_PHYLUM: "内肛动物门",S_CLASS: "未知纲",S_ORDER: "未知目",},
{S_DOMAIN: "真核域",S_KINGDOM: "动物界",S_PHYLUM: "环口动物门",S_CLASS: "未知纲",S_ORDER: "未知目",},
{S_DOMAIN: "真核域",S_KINGDOM: "动物界",S_PHYLUM: "舌形动物门",S_CLASS: "未知纲",S_ORDER: "未知目",},
{S_DOMAIN: "真核域",S_KINGDOM: "动物界",S_PHYLUM: "微颚动物门",S_CLASS: "未知纲",S_ORDER: "未知目",},
{S_DOMAIN: "真核域",S_KINGDOM: "动物界",S_PHYLUM: "颚胃动物门",S_CLASS: "未知纲",S_ORDER: "未知目",},
{S_DOMAIN: "真核域",S_KINGDOM: "动物界",S_PHYLUM: "腕足动物门",S_CLASS: "未知纲",S_ORDER: "未知目",},
{S_DOMAIN: "真核域",S_KINGDOM: "动物界",S_PHYLUM: "外肛动物门",S_CLASS: "未知纲",S_ORDER: "未知目",},
{S_DOMAIN: "真核域",S_KINGDOM: "动物界",S_PHYLUM: "帚虫动物门",S_CLASS: "未知纲",S_ORDER: "未知目",},
{S_DOMAIN: "真核域",S_KINGDOM: "动物界",S_PHYLUM: "棘皮动物门",S_CLASS: "未知纲",S_ORDER: "未知目",},
{S_DOMAIN: "真核域",S_KINGDOM: "动物界",S_PHYLUM: "须腕动物门",S_CLASS: "未知纲",S_ORDER: "未知目",},
{S_DOMAIN: "真核域",S_KINGDOM: "动物界",S_PHYLUM: "异涡动物门",S_CLASS: "未知纲",S_ORDER: "未知目",},
{S_DOMAIN: "真核域",S_KINGDOM: "动物界",S_PHYLUM: "半索动物门",S_CLASS: "未知纲",S_ORDER: "未知目",},
{S_DOMAIN: "真核域",S_KINGDOM: "动物界",S_PHYLUM: "脊索动物门",S_CLASS: "尾海鞘纲",S_ORDER: "未知目",},
{S_DOMAIN: "真核域",S_KINGDOM: "动物界",S_PHYLUM: "脊索动物门",S_CLASS: "海鞘纲",S_ORDER: "未知目",},
{S_DOMAIN: "真核域",S_KINGDOM: "动物界",S_PHYLUM: "脊索动物门",S_CLASS: "海樽纲",S_ORDER: "未知目",},*/
{S_DOMAIN: "真核域",S_KINGDOM: "动物界",S_PHYLUM: "脊索动物门",S_CLASS: "圆口纲",S_ORDER: "七鳃鳗目",},
{S_DOMAIN: "真核域",S_KINGDOM: "动物界",S_PHYLUM: "脊索动物门",S_CLASS: "圆口纲",S_ORDER: "盲鳗目",},
{S_DOMAIN: "真核域",S_KINGDOM: "动物界",S_PHYLUM: "脊索动物门",S_CLASS: "软骨鱼纲",S_ORDER: "六鳃鲨目",},
{S_DOMAIN: "真核域",S_KINGDOM: "动物界",S_PHYLUM: "脊索动物门",S_CLASS: "软骨鱼纲",S_ORDER: "虎鲨目",},
{S_DOMAIN: "真核域",S_KINGDOM: "动物界",S_PHYLUM: "脊索动物门",S_CLASS: "软骨鱼纲",S_ORDER: "鼠鲨目",},
{S_DOMAIN: "真核域",S_KINGDOM: "动物界",S_PHYLUM: "脊索动物门",S_CLASS: "软骨鱼纲",S_ORDER: "须鲨目",},
{S_DOMAIN: "真核域",S_KINGDOM: "动物界",S_PHYLUM: "脊索动物门",S_CLASS: "软骨鱼纲",S_ORDER: "真鲨目",},
{S_DOMAIN: "真核域",S_KINGDOM: "动物界",S_PHYLUM: "脊索动物门",S_CLASS: "软骨鱼纲",S_ORDER: "角鲨目",},
{S_DOMAIN: "真核域",S_KINGDOM: "动物界",S_PHYLUM: "脊索动物门",S_CLASS: "软骨鱼纲",S_ORDER: "扁鲨目",},
{S_DOMAIN: "真核域",S_KINGDOM: "动物界",S_PHYLUM: "脊索动物门",S_CLASS: "软骨鱼纲",S_ORDER: "锯鲨目",},
{S_DOMAIN: "真核域",S_KINGDOM: "动物界",S_PHYLUM: "脊索动物门",S_CLASS: "软骨鱼纲",S_ORDER: "胸脊鲨目",},
{S_DOMAIN: "真核域",S_KINGDOM: "动物界",S_PHYLUM: "脊索动物门",S_CLASS: "软骨鱼纲",S_ORDER: "筋异刺鲨目",},
{S_DOMAIN: "真核域",S_KINGDOM: "动物界",S_PHYLUM: "脊索动物门",S_CLASS: "软骨鱼纲",S_ORDER: "旋齿鲨目",},
{S_DOMAIN: "真核域",S_KINGDOM: "动物界",S_PHYLUM: "脊索动物门",S_CLASS: "软骨鱼纲",S_ORDER: "锯鳐目",},
{S_DOMAIN: "真核域",S_KINGDOM: "动物界",S_PHYLUM: "脊索动物门",S_CLASS: "软骨鱼纲",S_ORDER: "鳐形目",},
{S_DOMAIN: "真核域",S_KINGDOM: "动物界",S_PHYLUM: "脊索动物门",S_CLASS: "软骨鱼纲",S_ORDER: "鲼形目",},
{S_DOMAIN: "真核域",S_KINGDOM: "动物界",S_PHYLUM: "脊索动物门",S_CLASS: "软骨鱼纲",S_ORDER: "电鳐目",},
{S_DOMAIN: "真核域",S_KINGDOM: "动物界",S_PHYLUM: "脊索动物门",S_CLASS: "软骨鱼纲",S_ORDER: "犁头鳐目",},
{S_DOMAIN: "真核域",S_KINGDOM: "动物界",S_PHYLUM: "脊索动物门",S_CLASS: "软骨鱼纲",S_ORDER: "银鲛目",},
{S_DOMAIN: "真核域",S_KINGDOM: "动物界",S_PHYLUM: "脊索动物门",S_CLASS: "硬骨鱼纲",S_ORDER: "单鳔肺鱼目",},
{S_DOMAIN: "真核域",S_KINGDOM: "动物界",S_PHYLUM: "脊索动物门",S_CLASS: "硬骨鱼纲",S_ORDER: "双鳔肺鱼目",},
{S_DOMAIN: "真核域",S_KINGDOM: "动物界",S_PHYLUM: "脊索动物门",S_CLASS: "硬骨鱼纲",S_ORDER: "腔棘目",},
{S_DOMAIN: "真核域",S_KINGDOM: "动物界",S_PHYLUM: "脊索动物门",S_CLASS: "硬骨鱼纲",S_ORDER: "多鳍鱼目",},
{S_DOMAIN: "真核域",S_KINGDOM: "动物界",S_PHYLUM: "脊索动物门",S_CLASS: "硬骨鱼纲",S_ORDER: "鲟形目",},
{S_DOMAIN: "真核域",S_KINGDOM: "动物界",S_PHYLUM: "脊索动物门",S_CLASS: "硬骨鱼纲",S_ORDER: "弓鳍鱼目",},
{S_DOMAIN: "真核域",S_KINGDOM: "动物界",S_PHYLUM: "脊索动物门",S_CLASS: "硬骨鱼纲",S_ORDER: "雀鳝目",},
{S_DOMAIN: "真核域",S_KINGDOM: "动物界",S_PHYLUM: "脊索动物门",S_CLASS: "硬骨鱼纲",S_ORDER: "海鲢目",},
{S_DOMAIN: "真核域",S_KINGDOM: "动物界",S_PHYLUM: "脊索动物门",S_CLASS: "硬骨鱼纲",S_ORDER: "鼠鱚目",},
{S_DOMAIN: "真核域",S_KINGDOM: "动物界",S_PHYLUM: "脊索动物门",S_CLASS: "硬骨鱼纲",S_ORDER: "鲱形目",},
{S_DOMAIN: "真核域",S_KINGDOM: "动物界",S_PHYLUM: "脊索动物门",S_CLASS: "硬骨鱼纲",S_ORDER: "鲑形目",},
{S_DOMAIN: "真核域",S_KINGDOM: "动物界",S_PHYLUM: "脊索动物门",S_CLASS: "硬骨鱼纲",S_ORDER: "灯笼鱼目",},
{S_DOMAIN: "真核域",S_KINGDOM: "动物界",S_PHYLUM: "脊索动物门",S_CLASS: "硬骨鱼纲",S_ORDER: "鲸口鱼目",},
{S_DOMAIN: "真核域",S_KINGDOM: "动物界",S_PHYLUM: "脊索动物门",S_CLASS: "硬骨鱼纲",S_ORDER: "鳗鲡目",},
{S_DOMAIN: "真核域",S_KINGDOM: "动物界",S_PHYLUM: "脊索动物门",S_CLASS: "硬骨鱼纲",S_ORDER: "背棘鱼目",},
{S_DOMAIN: "真核域",S_KINGDOM: "动物界",S_PHYLUM: "脊索动物门",S_CLASS: "硬骨鱼纲",S_ORDER: "骨舌鱼目",},
{S_DOMAIN: "真核域",S_KINGDOM: "动物界",S_PHYLUM: "脊索动物门",S_CLASS: "硬骨鱼纲",S_ORDER: "鲤形目",TITLE: "草鱼",F_GROUP: "miao",F_NAME: "caoyu.jpg",},
{S_DOMAIN: "真核域",S_KINGDOM: "动物界",S_PHYLUM: "脊索动物门",S_CLASS: "硬骨鱼纲",S_ORDER: "鲇形目",},
{S_DOMAIN: "真核域",S_KINGDOM: "动物界",S_PHYLUM: "脊索动物门",S_CLASS: "硬骨鱼纲",S_ORDER: "鳉形目",},
{S_DOMAIN: "真核域",S_KINGDOM: "动物界",S_PHYLUM: "脊索动物门",S_CLASS: "硬骨鱼纲",S_ORDER: "银汉鱼目",},
{S_DOMAIN: "真核域",S_KINGDOM: "动物界",S_PHYLUM: "脊索动物门",S_CLASS: "硬骨鱼纲",S_ORDER: "颌针鱼目",},
{S_DOMAIN: "真核域",S_KINGDOM: "动物界",S_PHYLUM: "脊索动物门",S_CLASS: "硬骨鱼纲",S_ORDER: "鲑鲈目",},
{S_DOMAIN: "真核域",S_KINGDOM: "动物界",S_PHYLUM: "脊索动物门",S_CLASS: "硬骨鱼纲",S_ORDER: "鳕形目",},
{S_DOMAIN: "真核域",S_KINGDOM: "动物界",S_PHYLUM: "脊索动物门",S_CLASS: "硬骨鱼纲",S_ORDER: "金眼鲷目",},
{S_DOMAIN: "真核域",S_KINGDOM: "动物界",S_PHYLUM: "脊索动物门",S_CLASS: "硬骨鱼纲",S_ORDER: "海鲂目",},
{S_DOMAIN: "真核域",S_KINGDOM: "动物界",S_PHYLUM: "脊索动物门",S_CLASS: "硬骨鱼纲",S_ORDER: "月鱼目",},
{S_DOMAIN: "真核域",S_KINGDOM: "动物界",S_PHYLUM: "脊索动物门",S_CLASS: "硬骨鱼纲",S_ORDER: "刺鱼目",},
{S_DOMAIN: "真核域",S_KINGDOM: "动物界",S_PHYLUM: "脊索动物门",S_CLASS: "硬骨鱼纲",S_ORDER: "鲻形目",},
{S_DOMAIN: "真核域",S_KINGDOM: "动物界",S_PHYLUM: "脊索动物门",S_CLASS: "硬骨鱼纲",S_ORDER: "合鳃鱼目",},
{S_DOMAIN: "真核域",S_KINGDOM: "动物界",S_PHYLUM: "脊索动物门",S_CLASS: "硬骨鱼纲",S_ORDER: "鲈形目",},
{S_DOMAIN: "真核域",S_KINGDOM: "动物界",S_PHYLUM: "脊索动物门",S_CLASS: "硬骨鱼纲",S_ORDER: "鲉形目",},
{S_DOMAIN: "真核域",S_KINGDOM: "动物界",S_PHYLUM: "脊索动物门",S_CLASS: "硬骨鱼纲",S_ORDER: "鲽形目",},
{S_DOMAIN: "真核域",S_KINGDOM: "动物界",S_PHYLUM: "脊索动物门",S_CLASS: "硬骨鱼纲",S_ORDER: "鲀形目",},
{S_DOMAIN: "真核域",S_KINGDOM: "动物界",S_PHYLUM: "脊索动物门",S_CLASS: "硬骨鱼纲",S_ORDER: "蟾鱼目",},
{S_DOMAIN: "真核域",S_KINGDOM: "动物界",S_PHYLUM: "脊索动物门",S_CLASS: "硬骨鱼纲",S_ORDER: "海蛾鱼目",},
{S_DOMAIN: "真核域",S_KINGDOM: "动物界",S_PHYLUM: "脊索动物门",S_CLASS: "硬骨鱼纲",S_ORDER: "喉盘鱼目",},
{S_DOMAIN: "真核域",S_KINGDOM: "动物界",S_PHYLUM: "脊索动物门",S_CLASS: "硬骨鱼纲",S_ORDER: "鮟鱇目",},
{S_DOMAIN: "真核域",S_KINGDOM: "动物界",S_PHYLUM: "脊索动物门",S_CLASS: "头索纲",S_ORDER: "文昌鱼目",},
{S_DOMAIN: "真核域",S_KINGDOM: "动物界",S_PHYLUM: "脊索动物门",S_CLASS: "两栖纲",S_ORDER: "蚓螈目",},
{S_DOMAIN: "真核域",S_KINGDOM: "动物界",S_PHYLUM: "脊索动物门",S_CLASS: "两栖纲",S_ORDER: "有尾目",},
{S_DOMAIN: "真核域",S_KINGDOM: "动物界",S_PHYLUM: "脊索动物门",S_CLASS: "两栖纲",S_ORDER: "无尾目",TITLE: "蛙",F_GROUP: "miao",F_NAME: "wa01.jpg",},
{S_DOMAIN: "真核域",S_KINGDOM: "动物界",S_PHYLUM: "脊索动物门",S_CLASS: "爬行纲",S_ORDER: "龟鳖目",TITLE: "乌龟",F_GROUP: "miao",F_NAME: "gui.jpg",},
{S_DOMAIN: "真核域",S_KINGDOM: "动物界",S_PHYLUM: "脊索动物门",S_CLASS: "爬行纲",S_ORDER: "",},
{S_DOMAIN: "真核域",S_KINGDOM: "动物界",S_PHYLUM: "脊索动物门",S_CLASS: "爬行纲",S_ORDER: "喙头目",},
{S_DOMAIN: "真核域",S_KINGDOM: "动物界",S_PHYLUM: "脊索动物门",S_CLASS: "爬行纲",S_ORDER: "鳄目",},
{S_DOMAIN: "真核域",S_KINGDOM: "动物界",S_PHYLUM: "脊索动物门",S_CLASS: "鸟纲",INFO: "体均被羽，恒温，卵生，胚胎外有羊膜。前肢成翼，有时退化。多营飞翔生活。",},
{S_DOMAIN: "真核域",S_KINGDOM: "动物界",S_PHYLUM: "脊索动物门",S_CLASS: "鸟纲",S_ORDER: "鸵鸟目",},
{S_DOMAIN: "真核域",S_KINGDOM: "动物界",S_PHYLUM: "脊索动物门",S_CLASS: "鸟纲",S_ORDER: "美洲鸵鸟目",},
{S_DOMAIN: "真核域",S_KINGDOM: "动物界",S_PHYLUM: "脊索动物门",S_CLASS: "鸟纲",S_ORDER: "无冀目",},
{S_DOMAIN: "真核域",S_KINGDOM: "动物界",S_PHYLUM: "脊索动物门",S_CLASS: "鸟纲",S_ORDER: "鹤鸵目",},
{S_DOMAIN: "真核域",S_KINGDOM: "动物界",S_PHYLUM: "脊索动物门",S_CLASS: "鸟纲",S_ORDER: "䳍形目",},
{S_DOMAIN: "真核域",S_KINGDOM: "动物界",S_PHYLUM: "脊索动物门",S_CLASS: "鸟纲",S_ORDER: "企鹅目",},
{S_DOMAIN: "真核域",S_KINGDOM: "动物界",S_PHYLUM: "脊索动物门",S_CLASS: "鸟纲",S_ORDER: "鸡形目",INFO: "6科83属302种。全世界分布。走禽。体结实，喙短，呈圆锥形，适于啄食植物种子；翼短圆，不善飞；脚强健，具锐爪，善于行走和掘地寻食；雄鸟具大的肉冠和美丽的羽毛；有的跗蹠后缘具距。",},
{S_DOMAIN: "真核域",S_KINGDOM: "动物界",S_PHYLUM: "脊索动物门",S_CLASS: "鸟纲",S_ORDER: "雁形目",},
{S_DOMAIN: "真核域",S_KINGDOM: "动物界",S_PHYLUM: "脊索动物门",S_CLASS: "鸟纲",S_ORDER: "夜鹰目",},
{S_DOMAIN: "真核域",S_KINGDOM: "动物界",S_PHYLUM: "脊索动物门",S_CLASS: "鸟纲",S_ORDER: "雨燕目",},
{S_DOMAIN: "真核域",S_KINGDOM: "动物界",S_PHYLUM: "脊索动物门",S_CLASS: "鸟纲",S_ORDER: "蕉鹃目",},
{S_DOMAIN: "真核域",S_KINGDOM: "动物界",S_PHYLUM: "脊索动物门",S_CLASS: "鸟纲",S_ORDER: "鸨形目",},
{S_DOMAIN: "真核域",S_KINGDOM: "动物界",S_PHYLUM: "脊索动物门",S_CLASS: "鸟纲",S_ORDER: "鹃形目",},
{S_DOMAIN: "真核域",S_KINGDOM: "动物界",S_PHYLUM: "脊索动物门",S_CLASS: "鸟纲",S_ORDER: "鹳形目",},
{S_DOMAIN: "真核域",S_KINGDOM: "动物界",S_PHYLUM: "脊索动物门",S_CLASS: "鸟纲",S_ORDER: "鸻形目",S_FAMILY: "鸻科",TITLE: "剑鸻",F_GROUP: "../bird/birds",F_NAME: "鸻.剑鸻.jpg",},
{S_DOMAIN: "真核域",S_KINGDOM: "动物界",S_PHYLUM: "脊索动物门",S_CLASS: "鸟纲",S_ORDER: "鸻形目",S_FAMILY: "鸻科",TITLE: "环颈鸻",F_GROUP: "../bird/birds",F_NAME: "鸻.环颈鸻.jpg",},
{S_DOMAIN: "真核域",S_KINGDOM: "动物界",S_PHYLUM: "脊索动物门",S_CLASS: "鸟纲",S_ORDER: "鸽形目",S_FAMILY: "鸠鸽科",TITLE: "珠颈斑鸠",F_GROUP: "../bird/birds",F_NAME: "鸠鸽.珠颈斑鸠.jpg",},
{S_DOMAIN: "真核域",S_KINGDOM: "动物界",S_PHYLUM: "脊索动物门",S_CLASS: "鸟纲",S_ORDER: "鸽形目",S_FAMILY: "鸠鸽科",TITLE: "原鸽",F_GROUP: "../bird/birds",F_NAME: "鸠鸽.原鸽.jpg",},
{S_DOMAIN: "真核域",S_KINGDOM: "动物界",S_PHYLUM: "脊索动物门",S_CLASS: "鸟纲",S_ORDER: "鸽形目",S_FAMILY: "鸠鸽科",TITLE: "山斑鸠",F_GROUP: "../bird/birds",F_NAME: "鸠鸽.山斑鸠.jpg",},
{S_DOMAIN: "真核域",S_KINGDOM: "动物界",S_PHYLUM: "脊索动物门",S_CLASS: "鸟纲",S_ORDER: "鸽形目",S_FAMILY: "鸠鸽科",TITLE: "灰斑鸠",F_GROUP: "../bird/birds",F_NAME: "鸠鸽.灰斑鸠.jpg",},
{S_DOMAIN: "真核域",S_KINGDOM: "动物界",S_PHYLUM: "脊索动物门",S_CLASS: "鸟纲",S_ORDER: "佛法僧目",S_FAMILY: "蜂虎科",TITLE: "栗喉蜂虎",F_GROUP: "../bird/birds",F_NAME: "蜂虎.栗喉蜂虎.jpg",},
{S_DOMAIN: "真核域",S_KINGDOM: "动物界",S_PHYLUM: "脊索动物门",S_CLASS: "鸟纲",S_ORDER: "佛法僧目",S_FAMILY: "蜂虎科",TITLE: "蓝喉蜂虎",F_GROUP: "../bird/birds",F_NAME: "蜂虎.蓝喉蜂虎.jpg",},
{S_DOMAIN: "真核域",S_KINGDOM: "动物界",S_PHYLUM: "脊索动物门",S_CLASS: "鸟纲",S_ORDER: "佛法僧目",S_FAMILY: "翠鸟科",TITLE: "白胸翡翠",F_GROUP: "../bird/birds",F_NAME: "翠鸟.白胸翡翠.jpg",},
{S_DOMAIN: "真核域",S_KINGDOM: "动物界",S_PHYLUM: "脊索动物门",S_CLASS: "鸟纲",S_ORDER: "佛法僧目",S_FAMILY: "翠鸟科",TITLE: "普通翠鸟",F_GROUP: "../bird/birds",F_NAME: "翠鸟.普通翠鸟.jpg",},
{S_DOMAIN: "真核域",S_KINGDOM: "动物界",S_PHYLUM: "脊索动物门",S_CLASS: "鸟纲",S_ORDER: "潜鸟目",},
{S_DOMAIN: "真核域",S_KINGDOM: "动物界",S_PHYLUM: "脊索动物门",S_CLASS: "鸟纲",S_ORDER: "鹰形目",S_FAMILY: "鹰科",TITLE: "林雕",F_GROUP: "../bird/birds",F_NAME: "鹰.林雕.jpg",},
{S_DOMAIN: "真核域",S_KINGDOM: "动物界",S_PHYLUM: "脊索动物门",S_CLASS: "鸟纲",S_ORDER: "鹰形目",S_FAMILY: "鹰科",TITLE: "黑耳鸢",F_GROUP: "../bird/birds",F_NAME: "鹰.黑耳鸢.jpg",},
{S_DOMAIN: "真核域",S_KINGDOM: "动物界",S_PHYLUM: "脊索动物门",S_CLASS: "鸟纲",S_ORDER: "鹰形目",S_FAMILY: "鹰科",TITLE: "蛇雕",F_GROUP: "../bird/birds",F_NAME: "鹰.蛇雕.jpg",},
{S_DOMAIN: "真核域",S_KINGDOM: "动物界",S_PHYLUM: "脊索动物门",S_CLASS: "鸟纲",S_ORDER: "鹰形目",S_FAMILY: "鹰科",TITLE: "赤腹鹰",F_GROUP: "../bird/birds",F_NAME: "鹰.赤腹鹰.jpg",},
{S_DOMAIN: "真核域",S_KINGDOM: "动物界",S_PHYLUM: "脊索动物门",S_CLASS: "鸟纲",S_ORDER: "鸥形目",S_FAMILY: "鸥科",TITLE: "红嘴鸥",F_GROUP: "../bird/birds",F_NAME: "鸥.红嘴鸥.jpg",},
{S_DOMAIN: "真核域",S_KINGDOM: "动物界",S_PHYLUM: "脊索动物门",S_CLASS: "鸟纲",S_ORDER: "雀形目",},
{S_DOMAIN: "真核域",S_KINGDOM: "动物界",S_PHYLUM: "脊索动物门",S_CLASS: "鸟纲",S_ORDER: "鹈形目",S_FAMILY: "鸬鹚",TITLE: "鸬鹚",F_GROUP: "../bird/birds",F_NAME: "鸬鹚.普通鸬鹚.jpg",},
{S_DOMAIN: "真核域",S_KINGDOM: "动物界",S_PHYLUM: "脊索动物门",S_CLASS: "鸟纲",S_ORDER: "鴷形目",S_FAMILY: "啄木鸟科",TITLE: "斑姬啄木鸟",F_GROUP: "../bird/birds",F_NAME: "啄木鸟.斑姬啄木鸟.jpg",},
{S_DOMAIN: "真核域",S_KINGDOM: "动物界",S_PHYLUM: "脊索动物门",S_CLASS: "鸟纲",S_ORDER: "鸊鷉目",S_FAMILY: "科",TITLE: "小鸊鷉",F_GROUP: "../bird/birds",F_NAME: ".小.jpg",},
{S_DOMAIN: "真核域",S_KINGDOM: "动物界",S_PHYLUM: "脊索动物门",S_CLASS: "鸟纲",S_ORDER: "鹱形目",},
{S_DOMAIN: "真核域",S_KINGDOM: "动物界",S_PHYLUM: "脊索动物门",S_CLASS: "鸟纲",S_ORDER: "鹦形目",S_FAMILY: "鹦鹉科",TITLE: "非洲灰鹦鹉",F_GROUP: "../bird/others",F_NAME: "鹦鹉.非洲灰鹦鹉.jpg",},
{S_DOMAIN: "真核域",S_KINGDOM: "动物界",S_PHYLUM: "脊索动物门",S_CLASS: "鸟纲",S_ORDER: "鸮形目",},
{S_DOMAIN: "真核域",S_KINGDOM: "动物界",S_PHYLUM: "脊索动物门",S_CLASS: "鸟纲",S_ORDER: "咬鹃目",},
{S_DOMAIN: "真核域",S_KINGDOM: "动物界",S_PHYLUM: "脊索动物门",S_CLASS: "鸟纲",S_ORDER: "隼形目",},
{S_DOMAIN: "真核域",S_KINGDOM: "动物界",S_PHYLUM: "脊索动物门",S_CLASS: "鸟纲",S_ORDER: "几维目",},
{S_DOMAIN: "真核域",S_KINGDOM: "动物界",S_PHYLUM: "脊索动物门",S_CLASS: "鸟纲",S_ORDER: "叫鹤目",},
{S_DOMAIN: "真核域",S_KINGDOM: "动物界",S_PHYLUM: "脊索动物门",S_CLASS: "鸟纲",S_ORDER: "犀鸟目",},
{S_DOMAIN: "真核域",S_KINGDOM: "动物界",S_PHYLUM: "脊索动物门",S_CLASS: "鸟纲",S_ORDER: "鼠鸟目",},
{S_DOMAIN: "真核域",S_KINGDOM: "动物界",S_PHYLUM: "脊索动物门",S_CLASS: "鸟纲",S_ORDER: "鹃鴗目",},
{S_DOMAIN: "真核域",S_KINGDOM: "动物界",S_PHYLUM: "脊索动物门",S_CLASS: "鸟纲",S_ORDER: "麝雉目",},
{S_DOMAIN: "真核域",S_KINGDOM: "动物界",S_PHYLUM: "脊索动物门",S_CLASS: "鸟纲",S_ORDER: "鲣鸟目",},
{S_DOMAIN: "真核域",S_KINGDOM: "动物界",S_PHYLUM: "脊索动物门",S_CLASS: "鸟纲",S_ORDER: "鹲形目",},
{S_DOMAIN: "真核域",S_KINGDOM: "动物界",S_PHYLUM: "脊索动物门",S_CLASS: "鸟纲",S_ORDER: "日鳽目",},
{S_DOMAIN: "真核域",S_KINGDOM: "动物界",S_PHYLUM: "脊索动物门",S_CLASS: "鸟纲",S_ORDER: "红鹳目",},
{S_DOMAIN: "真核域",S_KINGDOM: "动物界",S_PHYLUM: "脊索动物门",S_CLASS: "鸟纲",S_ORDER: "拟鹑目",},
{S_DOMAIN: "真核域",S_KINGDOM: "动物界",S_PHYLUM: "脊索动物门",S_CLASS: "鸟纲",S_ORDER: "沙鸡目",},
{S_DOMAIN: "真核域",S_KINGDOM: "动物界",S_PHYLUM: "脊索动物门",S_CLASS: "哺乳纲",S_ORDER: "单孔目",},
{S_DOMAIN: "真核域",S_KINGDOM: "动物界",S_PHYLUM: "脊索动物门",S_CLASS: "哺乳纲",S_ORDER: "有袋目",},
{S_DOMAIN: "真核域",S_KINGDOM: "动物界",S_PHYLUM: "脊索动物门",S_CLASS: "哺乳纲",S_ORDER: "鼩形目",TITLE: "鼩鼱",F_GROUP: "miao",F_NAME: "qujing01.jpg",},
{S_DOMAIN: "真核域",S_KINGDOM: "动物界",S_PHYLUM: "脊索动物门",S_CLASS: "哺乳纲",S_ORDER: "猬形目",},
{S_DOMAIN: "真核域",S_KINGDOM: "动物界",S_PHYLUM: "脊索动物门",S_CLASS: "哺乳纲",S_ORDER: "非洲猬目",},
{S_DOMAIN: "真核域",S_KINGDOM: "动物界",S_PHYLUM: "脊索动物门",S_CLASS: "哺乳纲",S_ORDER: "跳鼩目",},
{S_DOMAIN: "真核域",S_KINGDOM: "动物界",S_PHYLUM: "脊索动物门",S_CLASS: "哺乳纲",S_ORDER: "攀兽目",},
{S_DOMAIN: "真核域",S_KINGDOM: "动物界",S_PHYLUM: "脊索动物门",S_CLASS: "哺乳纲",S_ORDER: "皮翼目",},
{S_DOMAIN: "真核域",S_KINGDOM: "动物界",S_PHYLUM: "脊索动物门",S_CLASS: "哺乳纲",S_ORDER: "翼手目",TITLE: "蝙蝠",F_GROUP: "miao",F_NAME: "bianfu01.jpg",},
{S_DOMAIN: "真核域",S_KINGDOM: "动物界",S_PHYLUM: "脊索动物门",S_CLASS: "哺乳纲",S_ORDER: "灵长目",TITLE: "川金丝猴",F_GROUP: "miao",F_NAME: "hou01.jpg",},
{S_DOMAIN: "真核域",S_KINGDOM: "动物界",S_PHYLUM: "脊索动物门",S_CLASS: "哺乳纲",S_ORDER: "贫齿目",},
{S_DOMAIN: "真核域",S_KINGDOM: "动物界",S_PHYLUM: "脊索动物门",S_CLASS: "哺乳纲",S_ORDER: "鳞甲目",},
{S_DOMAIN: "真核域",S_KINGDOM: "动物界",S_PHYLUM: "脊索动物门",S_CLASS: "哺乳纲",S_ORDER: "兔型目",TITLE: "兔",F_GROUP: "miao",F_NAME: "tuzi01.jpg",},
{S_DOMAIN: "真核域",S_KINGDOM: "动物界",S_PHYLUM: "脊索动物门",S_CLASS: "哺乳纲",S_ORDER: "啮齿目",S_FAMILY: "松鼠科",TITLE: "赤腹松鼠",F_GROUP: "miao",F_NAME: "songshu.jpg",},
{S_DOMAIN: "真核域",S_KINGDOM: "动物界",S_PHYLUM: "脊索动物门",S_CLASS: "哺乳纲",S_ORDER: "啮齿目",S_FAMILY: "鼠科",TITLE: "老鼠",F_GROUP: "miao",F_NAME: "shu.jpg",},
{S_DOMAIN: "真核域",S_KINGDOM: "动物界",S_PHYLUM: "脊索动物门",S_CLASS: "哺乳纲",S_ORDER: "食肉目",},
{S_DOMAIN: "真核域",S_KINGDOM: "动物界",S_PHYLUM: "脊索动物门",S_CLASS: "哺乳纲",S_ORDER: "鲸目",},
{S_DOMAIN: "真核域",S_KINGDOM: "动物界",S_PHYLUM: "脊索动物门",S_CLASS: "哺乳纲",S_ORDER: "海牛目",},
{S_DOMAIN: "真核域",S_KINGDOM: "动物界",S_PHYLUM: "脊索动物门",S_CLASS: "哺乳纲",S_ORDER: "蹄兔目",},
{S_DOMAIN: "真核域",S_KINGDOM: "动物界",S_PHYLUM: "脊索动物门",S_CLASS: "哺乳纲",S_ORDER: "长鼻目",TITLE: "象",F_GROUP: "miao",F_NAME: "daxiang01.jpg",},
{S_DOMAIN: "真核域",S_KINGDOM: "动物界",S_PHYLUM: "脊索动物门",S_CLASS: "哺乳纲",S_ORDER: "管齿目",},
{S_DOMAIN: "真核域",S_KINGDOM: "动物界",S_PHYLUM: "脊索动物门",S_CLASS: "哺乳纲",S_ORDER: "奇蹄目",S_FAMILY: "貘科",TITLE: "貘",F_GROUP: "miao",F_NAME: "mo01.jpg",},
{S_DOMAIN: "真核域",S_KINGDOM: "动物界",S_PHYLUM: "脊索动物门",S_CLASS: "哺乳纲",S_ORDER: "奇蹄目",S_FAMILY: "马科",TITLE: "马",F_GROUP: "miao",F_NAME: "ma.jpg",},
{S_DOMAIN: "真核域",S_KINGDOM: "动物界",S_PHYLUM: "脊索动物门",S_CLASS: "哺乳纲",S_ORDER: "偶蹄目",S_FAMILY: "牛科",TITLE: "黄牛",F_GROUP: "miao",F_NAME: "huangniu.jpg",},
{S_DOMAIN: "真核域",S_KINGDOM: "动物界",S_PHYLUM: "脊索动物门",S_CLASS: "哺乳纲",S_ORDER: "偶蹄目",S_FAMILY: "牛科",TITLE: "羊",F_GROUP: "miao",F_NAME: "yang.jpg",},
]
