var file=[
{S_DOMAIN: "空之域",S_KINGDOM: "星河界",S_PHYLUM: "太阳系",S_CLASS: "日月",S_ORDER: "太阳",TITLE: "太阳",F_GROUP: "scene",F_NAME: "heizi01.jpg",},
{S_DOMAIN: "空之域",S_KINGDOM: "星河界",S_PHYLUM: "太阳系",S_CLASS: "日月",S_ORDER: "月亮",TITLE: "月球",F_GROUP: "scene",F_NAME: "yue1.jpg",},
{S_DOMAIN: "空之域",S_KINGDOM: "星河界",S_PHYLUM: "太阳系",S_CLASS: "行星",S_ORDER: "水星",},
{S_DOMAIN: "空之域",S_KINGDOM: "星河界",S_PHYLUM: "太阳系",S_CLASS: "行星",S_ORDER: "金星",TITLE: "金星",F_GROUP: "scene",F_NAME: "jinxing20200712.jpg",},
{S_DOMAIN: "空之域",S_KINGDOM: "星河界",S_PHYLUM: "太阳系",S_CLASS: "行星",S_ORDER: "地球",},
{S_DOMAIN: "空之域",S_KINGDOM: "星河界",S_PHYLUM: "太阳系",S_CLASS: "行星",S_ORDER: "火星",TITLE: "火星",F_GROUP: "scene",F_NAME: "mars02.jpg",},
{S_DOMAIN: "空之域",S_KINGDOM: "星河界",S_PHYLUM: "太阳系",S_CLASS: "行星",S_ORDER: "木星",TITLE: "木星",F_GROUP: "scene",F_NAME: "muxing.jpg",},
{S_DOMAIN: "空之域",S_KINGDOM: "星河界",S_PHYLUM: "太阳系",S_CLASS: "行星",S_ORDER: "土星",TITLE: "土星",F_GROUP: "scene",F_NAME: "tuxing01.jpg",},
{S_DOMAIN: "空之域",S_KINGDOM: "星河界",S_PHYLUM: "太阳系",S_CLASS: "行星",S_ORDER: "海王星",TITLE: "海王星",F_GROUP: "scene",F_NAME: "hwx01.jpg",},
{S_DOMAIN: "空之域",S_KINGDOM: "星河界",S_PHYLUM: "太阳系",S_CLASS: "行星",S_ORDER: "天王星",},
{S_DOMAIN: "空之域",S_KINGDOM: "星河界",S_PHYLUM: "太阳系",S_CLASS: "彗星",S_ORDER: "46P",TITLE: "彗星46P",F_GROUP: "scene",F_NAME: "46P.jpg",},
{S_DOMAIN: "空之域",S_KINGDOM: "星河界",S_PHYLUM: "太阳系",S_CLASS: "彗星",S_ORDER: "2020F3",TITLE: "彗星2020F3",F_GROUP: "scene",F_NAME: "2020F30722.jpg",},
{S_DOMAIN: "空之域",S_KINGDOM: "星河界",S_PHYLUM: "银河系天体",S_CLASS: "星团",S_ORDER: "昴星团",TITLE: "昴星团",F_GROUP: "scene",F_NAME: "mao.jpg",},
{S_DOMAIN: "空之域",S_KINGDOM: "星河界",S_PHYLUM: "银河系天体",S_CLASS: "星云",S_ORDER: "猎户座大星云",TITLE: "猎户座大星云",F_GROUP: "scene",F_NAME: "yklrs.jpg",},
{S_DOMAIN: "空之域",S_KINGDOM: "星河界",S_PHYLUM: "银河系外天体",S_CLASS: "星系",S_ORDER: "仙女星云",TITLE: "仙女星云",F_GROUP: "scene",F_NAME: "xiannv.jpg",},
{S_DOMAIN: "地之域",S_KINGDOM: "地界",S_PHYLUM: "气象",S_CLASS: "云",S_ORDER: "积云",},
{S_DOMAIN: "地之域",S_KINGDOM: "地界",S_PHYLUM: "气象",S_CLASS: "云",S_ORDER: "积雨云",},
{S_DOMAIN: "地之域",S_KINGDOM: "地界",S_PHYLUM: "气象",S_CLASS: "云",S_ORDER: "层云",},
{S_DOMAIN: "地之域",S_KINGDOM: "地界",S_PHYLUM: "气象",S_CLASS: "云",S_ORDER: "层积云",TITLE: "日晕",F_GROUP: "scene",F_NAME: "cloudcjy01.jpg",},
{S_DOMAIN: "地之域",S_KINGDOM: "地界",S_PHYLUM: "气象",S_CLASS: "云",S_ORDER: "高积云",},
{S_DOMAIN: "地之域",S_KINGDOM: "地界",S_PHYLUM: "气象",S_CLASS: "云",S_ORDER: "高层云",},
{S_DOMAIN: "地之域",S_KINGDOM: "地界",S_PHYLUM: "气象",S_CLASS: "云",S_ORDER: "雨层云",},
{S_DOMAIN: "地之域",S_KINGDOM: "地界",S_PHYLUM: "气象",S_CLASS: "云",S_ORDER: "卷云",},
{S_DOMAIN: "地之域",S_KINGDOM: "地界",S_PHYLUM: "气象",S_CLASS: "云",S_ORDER: "卷积云",},
{S_DOMAIN: "地之域",S_KINGDOM: "地界",S_PHYLUM: "气象",S_CLASS: "云",S_ORDER: "卷层云",},
{S_DOMAIN: "地之域",S_KINGDOM: "地界",S_PHYLUM: "气象",S_CLASS: "雷雨",S_ORDER: "大雨",TITLE: "日晕",F_GROUP: "scene",F_NAME: "banyu.jpg",},
{S_DOMAIN: "地之域",S_KINGDOM: "地界",S_PHYLUM: "气象",S_CLASS: "雷雨",S_ORDER: "闪电",},
{S_DOMAIN: "地之域",S_KINGDOM: "地界",S_PHYLUM: "气象",S_CLASS: "雷雨",S_ORDER: "红色精灵",},
{S_DOMAIN: "地之域",S_KINGDOM: "地界",S_PHYLUM: "气象",S_CLASS: "其它",S_ORDER: "暖夜灯柱",},
{S_DOMAIN: "地之域",S_KINGDOM: "地界",S_PHYLUM: "气象",S_CLASS: "其它",S_ORDER: "日晕",TITLE: "日晕",F_GROUP: "scene",F_NAME: "riyun01.jpg",},
{S_DOMAIN: "地之域",S_KINGDOM: "地界",S_PHYLUM: "气象",S_CLASS: "其它",S_ORDER: "彩虹",TITLE: "彩虹",F_GROUP: "scene",F_NAME: "hong01.jpg",},
/*{S_DOMAIN: "古菌域",S_KINGDOM: "嗜泉古菌界",S_PHYLUM: "未知门",S_CLASS: "未知纲",S_ORDER: "未知目",},
{S_DOMAIN: "古菌域",S_KINGDOM: "广域古菌界",S_PHYLUM: "未知门",S_CLASS: "未知纲",S_ORDER: "未知目",},
{S_DOMAIN: "古菌域",S_KINGDOM: "始生古菌界",S_PHYLUM: "未知门",S_CLASS: "未知纲",S_ORDER: "未知目",},
{S_DOMAIN: "细菌域",S_KINGDOM: "细菌界",S_PHYLUM: "未知门",S_CLASS: "未知纲",S_ORDER: "未知目",},
{S_DOMAIN: "真核域",S_KINGDOM: "原生生物界",S_PHYLUM: "未知门",S_CLASS: "未知纲",S_ORDER: "未知目",},
{S_DOMAIN: "真核域",S_KINGDOM: "真菌界",S_PHYLUM: "真菌门",S_CLASS: "未知纲",S_ORDER: "未知目",},
{S_DOMAIN: "真核域",S_KINGDOM: "真菌界",S_PHYLUM: "粘菌门",S_CLASS: "未知纲",S_ORDER: "未知目",},
{S_DOMAIN: "真核域",S_KINGDOM: "真菌界",S_PHYLUM: "担子菌门",S_CLASS: "黑粉菌纲",S_ORDER: "未知目",},
{S_DOMAIN: "真核域",S_KINGDOM: "真菌界",S_PHYLUM: "担子菌门",S_CLASS: "锈菌纲",S_ORDER: "未知目",},*/
{S_DOMAIN: "真核域",S_KINGDOM: "真菌界",S_PHYLUM: "担子菌门",S_CLASS: "伞菌纲",S_ORDER: "木耳目",TITLE: "黑木耳",F_GROUP: "wood",F_NAME: "muer01.jpg",},
{S_DOMAIN: "真核域",S_KINGDOM: "真菌界",S_PHYLUM: "担子菌门",S_CLASS: "伞菌纲",S_ORDER: "无蕈褶目",TITLE: "树舌",F_GROUP: "wood",F_NAME: "gu4.jpg",},
{S_DOMAIN: "真核域",S_KINGDOM: "真菌界",S_PHYLUM: "担子菌门",S_CLASS: "银耳纲",S_ORDER: "银耳目",TITLE: "银耳",F_GROUP: "wood",F_NAME: "muer02.jpg",},
{S_DOMAIN: "真核域",S_KINGDOM: "真菌界",S_PHYLUM: "担子菌门",S_CLASS: "层菌纲",S_ORDER: "伞菌目",TITLE: "角鳞白鹅膏菌",F_GROUP: "wood",F_NAME: "gu16.jpg",},
{S_DOMAIN: "真核域",S_KINGDOM: "真菌界",S_PHYLUM: "担子菌门",S_CLASS: "层菌纲",S_ORDER: "红菇目",TITLE: "红菇",F_GROUP: "wood",F_NAME: "gu8.jpg",},
/*{S_DOMAIN: "真核域",S_KINGDOM: "植物界",S_PHYLUM: "绿藻门",S_CLASS: "未知纲",S_ORDER: "未知目",},
{S_DOMAIN: "真核域",S_KINGDOM: "植物界",S_PHYLUM: "裸藻门",S_CLASS: "未知纲",S_ORDER: "未知目",},
{S_DOMAIN: "真核域",S_KINGDOM: "植物界",S_PHYLUM: "金藻门",S_CLASS: "未知纲",S_ORDER: "未知目",},
{S_DOMAIN: "真核域",S_KINGDOM: "植物界",S_PHYLUM: "黄藻门",S_CLASS: "未知纲",S_ORDER: "未知目",},
{S_DOMAIN: "真核域",S_KINGDOM: "植物界",S_PHYLUM: "甲藻门",S_CLASS: "未知纲",S_ORDER: "未知目",},
{S_DOMAIN: "真核域",S_KINGDOM: "植物界",S_PHYLUM: "硅藻门",S_CLASS: "未知纲",S_ORDER: "未知目",},
{S_DOMAIN: "真核域",S_KINGDOM: "植物界",S_PHYLUM: "蓝藻门",S_CLASS: "未知纲",S_ORDER: "未知目",},
{S_DOMAIN: "真核域",S_KINGDOM: "植物界",S_PHYLUM: "褐藻门",S_CLASS: "未知纲",S_ORDER: "未知目",},
{S_DOMAIN: "真核域",S_KINGDOM: "植物界",S_PHYLUM: "红藻门",S_CLASS: "未知纲",S_ORDER: "未知目",},
{S_DOMAIN: "真核域",S_KINGDOM: "植物界",S_PHYLUM: "地衣门",S_CLASS: "未知纲",S_ORDER: "未知目",},
{S_DOMAIN: "真核域",S_KINGDOM: "植物界",S_PHYLUM: "苔藓植物门",S_CLASS: "未知纲",S_ORDER: "未知目",},*/
{S_DOMAIN: "真核域",S_KINGDOM: "植物界",S_PHYLUM: "蕨类植物门",S_CLASS: "松叶蕨纲",S_ORDER: "松叶蕨目",},
{S_DOMAIN: "真核域",S_KINGDOM: "植物界",S_PHYLUM: "蕨类植物门",S_CLASS: "石松纲",S_ORDER: "石松目",TITLE: "垂穗石松",F_GROUP: "wood",F_NAME: "juanjuan01.jpg",},
{S_DOMAIN: "真核域",S_KINGDOM: "植物界",S_PHYLUM: "蕨类植物门",S_CLASS: "石松纲",S_ORDER: "卷柏目",TITLE: "深绿卷柏",F_GROUP: "wood",F_NAME: "jue2.jpg",},
{S_DOMAIN: "真核域",S_KINGDOM: "植物界",S_PHYLUM: "蕨类植物门",S_CLASS: "水韭纲",S_ORDER: "水韭目",},
{S_DOMAIN: "真核域",S_KINGDOM: "植物界",S_PHYLUM: "蕨类植物门",S_CLASS: "木贼纲",S_ORDER: "木贼目",},
{S_DOMAIN: "真核域",S_KINGDOM: "植物界",S_PHYLUM: "蕨类植物门",S_CLASS: "厚囊蕨纲",S_ORDER: "瓶尔小草目",},
{S_DOMAIN: "真核域",S_KINGDOM: "植物界",S_PHYLUM: "蕨类植物门",S_CLASS: "厚囊蕨纲",S_ORDER: "莲座蕨目",},
{S_DOMAIN: "真核域",S_KINGDOM: "植物界",S_PHYLUM: "蕨类植物门",S_CLASS: "原始薄囊蕨纲",S_ORDER: "紫萁目",},
{S_DOMAIN: "真核域",S_KINGDOM: "植物界",S_PHYLUM: "蕨类植物门",S_CLASS: "薄囊蕨纲",S_ORDER: "真蕨目",TITLE: "桫椤",F_GROUP: "wood",F_NAME: "suoluo01.jpg",},
{S_DOMAIN: "真核域",S_KINGDOM: "植物界",S_PHYLUM: "蕨类植物门",S_CLASS: "薄囊蕨纲",S_ORDER: "苹目",},
{S_DOMAIN: "真核域",S_KINGDOM: "植物界",S_PHYLUM: "蕨类植物门",S_CLASS: "薄囊蕨纲",S_ORDER: "槐叶苹目",},
{S_DOMAIN: "真核域",S_KINGDOM: "植物界",S_PHYLUM: "裸子植物门",S_CLASS: "苏铁纲",S_ORDER: "苏铁目",},
{S_DOMAIN: "真核域",S_KINGDOM: "植物界",S_PHYLUM: "裸子植物门",S_CLASS: "银杏纲",S_ORDER: "银杏目",},
{S_DOMAIN: "真核域",S_KINGDOM: "植物界",S_PHYLUM: "裸子植物门",S_CLASS: "松柏纲",S_ORDER: "松柏目",TITLE: "松树",F_GROUP: "wood",F_NAME: "song.jpg",},
{S_DOMAIN: "真核域",S_KINGDOM: "植物界",S_PHYLUM: "裸子植物门",S_CLASS: "松柏纲",S_ORDER: "红豆杉目",},
{S_DOMAIN: "真核域",S_KINGDOM: "植物界",S_PHYLUM: "裸子植物门",S_CLASS: "买麻藤纲",S_ORDER: "买麻藤目",},
{S_DOMAIN: "真核域",S_KINGDOM: "植物界",S_PHYLUM: "被子植物门",S_CLASS: "单子叶植物纲",S_ORDER: "泽泻目",},
{S_DOMAIN: "真核域",S_KINGDOM: "植物界",S_PHYLUM: "被子植物门",S_CLASS: "单子叶植物纲",S_ORDER: "水鳖目",},
{S_DOMAIN: "真核域",S_KINGDOM: "植物界",S_PHYLUM: "被子植物门",S_CLASS: "单子叶植物纲",S_ORDER: "槟榔目",},
{S_DOMAIN: "真核域",S_KINGDOM: "植物界",S_PHYLUM: "被子植物门",S_CLASS: "单子叶植物纲",S_ORDER: "天南星目",TITLE: "一把伞南星",F_GROUP: "wood",F_NAME: "xiangjiao.jpg",},
{S_DOMAIN: "真核域",S_KINGDOM: "植物界",S_PHYLUM: "被子植物门",S_CLASS: "单子叶植物纲",S_ORDER: "鸭跖草目",TITLE: "紫鸭趾草",F_GROUP: "wood",F_NAME: "zyzc.jpg",},
{S_DOMAIN: "真核域",S_KINGDOM: "植物界",S_PHYLUM: "被子植物门",S_CLASS: "单子叶植物纲",S_ORDER: "姜目",TITLE: "香蕉",F_GROUP: "wood",F_NAME: "xiangjiao01.jpg",},
{S_DOMAIN: "真核域",S_KINGDOM: "植物界",S_PHYLUM: "被子植物门",S_CLASS: "单子叶植物纲",S_ORDER: "百合目",TITLE: "石蒜",F_GROUP: "wood",F_NAME: "bianhua01.jpg",},
{S_DOMAIN: "真核域",S_KINGDOM: "植物界",S_PHYLUM: "被子植物门",S_CLASS: "单子叶植物纲",S_ORDER: "天门冬目",},
{S_DOMAIN: "真核域",S_KINGDOM: "植物界",S_PHYLUM: "被子植物门",S_CLASS: "单子叶植物纲",S_ORDER: "薯蓣目",},
{S_DOMAIN: "真核域",S_KINGDOM: "植物界",S_PHYLUM: "被子植物门",S_CLASS: "单子叶植物纲",S_ORDER: "无叶莲目",},
{S_DOMAIN: "真核域",S_KINGDOM: "植物界",S_PHYLUM: "被子植物门",S_CLASS: "单子叶植物纲",S_ORDER: "禾本目",TITLE: "玉米",F_GROUP: "wood",F_NAME: "yumi01.jpg",},
{S_DOMAIN: "真核域",S_KINGDOM: "植物界",S_PHYLUM: "被子植物门",S_CLASS: "双子叶植物纲",S_ORDER: "木兰目",},
{S_DOMAIN: "真核域",S_KINGDOM: "植物界",S_PHYLUM: "被子植物门",S_CLASS: "双子叶植物纲",S_ORDER: "樟目",TITLE: "樟树",F_GROUP: "scene",F_NAME: "wangtian.jpg",},
{S_DOMAIN: "真核域",S_KINGDOM: "植物界",S_PHYLUM: "被子植物门",S_CLASS: "双子叶植物纲",S_ORDER: "胡椒目",TITLE: "鱼腥草",F_GROUP: "wood",F_NAME: "yuxingcao01.jpg",},
{S_DOMAIN: "真核域",S_KINGDOM: "植物界",S_PHYLUM: "被子植物门",S_CLASS: "双子叶植物纲",S_ORDER: "毛茛目",TITLE: "荷",F_GROUP: "wood",F_NAME: "hehua.jpg",},
{S_DOMAIN: "真核域",S_KINGDOM: "植物界",S_PHYLUM: "被子植物门",S_CLASS: "双子叶植物纲",S_ORDER: "罂粟目",},
{S_DOMAIN: "真核域",S_KINGDOM: "植物界",S_PHYLUM: "被子植物门",S_CLASS: "双子叶植物纲",S_ORDER: "昆栏树目",},
{S_DOMAIN: "真核域",S_KINGDOM: "植物界",S_PHYLUM: "被子植物门",S_CLASS: "双子叶植物纲",S_ORDER: "金缕梅目",},
{S_DOMAIN: "真核域",S_KINGDOM: "植物界",S_PHYLUM: "被子植物门",S_CLASS: "双子叶植物纲",S_ORDER: "杜仲目",},
{S_DOMAIN: "真核域",S_KINGDOM: "植物界",S_PHYLUM: "被子植物门",S_CLASS: "双子叶植物纲",S_ORDER: "荨麻目",TITLE: "薜荔",F_GROUP: "wood",F_NAME: "bili01.jpg",},
{S_DOMAIN: "真核域",S_KINGDOM: "植物界",S_PHYLUM: "被子植物门",S_CLASS: "双子叶植物纲",S_ORDER: "胡桃目",},
{S_DOMAIN: "真核域",S_KINGDOM: "植物界",S_PHYLUM: "被子植物门",S_CLASS: "双子叶植物纲",S_ORDER: "壳斗目",},
{S_DOMAIN: "真核域",S_KINGDOM: "植物界",S_PHYLUM: "被子植物门",S_CLASS: "双子叶植物纲",S_ORDER: "石竹目",TITLE: "鸡冠花",F_GROUP: "wood",F_NAME: "jiguanhua01.jpg",},
{S_DOMAIN: "真核域",S_KINGDOM: "植物界",S_PHYLUM: "被子植物门",S_CLASS: "双子叶植物纲",S_ORDER: "蓼目",},
{S_DOMAIN: "真核域",S_KINGDOM: "植物界",S_PHYLUM: "被子植物门",S_CLASS: "双子叶植物纲",S_ORDER: "五桠果目",},
{S_DOMAIN: "真核域",S_KINGDOM: "植物界",S_PHYLUM: "被子植物门",S_CLASS: "双子叶植物纲",S_ORDER: "山茶目",TITLE: "四季秋海棠",F_GROUP: "wood",F_NAME: "haitang01.jpg",},
{S_DOMAIN: "真核域",S_KINGDOM: "植物界",S_PHYLUM: "被子植物门",S_CLASS: "双子叶植物纲",S_ORDER: "锦葵目",TITLE: "木棉",F_GROUP: "wood",F_NAME: "mumianmaque.jpg",},
{S_DOMAIN: "真核域",S_KINGDOM: "植物界",S_PHYLUM: "被子植物门",S_CLASS: "双子叶植物纲",S_ORDER: "堇菜目",TITLE: "南瓜",F_GROUP: "wood",F_NAME: "nangua01.jpg",},
{S_DOMAIN: "真核域",S_KINGDOM: "植物界",S_PHYLUM: "被子植物门",S_CLASS: "双子叶植物纲",S_ORDER: "杨柳目",TITLE: "柳树",F_GROUP: "miao",F_NAME: "shulu.jpg",},
{S_DOMAIN: "真核域",S_KINGDOM: "植物界",S_PHYLUM: "被子植物门",S_CLASS: "双子叶植物纲",S_ORDER: "白花菜目",},
{S_DOMAIN: "真核域",S_KINGDOM: "植物界",S_PHYLUM: "被子植物门",S_CLASS: "双子叶植物纲",S_ORDER: "蔷薇目",TITLE: "豌豆",F_GROUP: "wood",F_NAME: "wandou.jpg",},
{S_DOMAIN: "真核域",S_KINGDOM: "植物界",S_PHYLUM: "被子植物门",S_CLASS: "双子叶植物纲",S_ORDER: "豆目",TITLE: "凤凰木",F_GROUP: "wood",F_NAME: "fenghuang.jpg",},
{S_DOMAIN: "真核域",S_KINGDOM: "植物界",S_PHYLUM: "被子植物门",S_CLASS: "双子叶植物纲",S_ORDER: "桃金娘目",TITLE: "石榴",F_GROUP: "wood",F_NAME: "shiliuhua.jpg",},
{S_DOMAIN: "真核域",S_KINGDOM: "植物界",S_PHYLUM: "被子植物门",S_CLASS: "双子叶植物纲",S_ORDER: "红树目",},
{S_DOMAIN: "真核域",S_KINGDOM: "植物界",S_PHYLUM: "被子植物门",S_CLASS: "双子叶植物纲",S_ORDER: "檀香目",},
{S_DOMAIN: "真核域",S_KINGDOM: "植物界",S_PHYLUM: "被子植物门",S_CLASS: "双子叶植物纲",S_ORDER: "卫矛目",},
{S_DOMAIN: "真核域",S_KINGDOM: "植物界",S_PHYLUM: "被子植物门",S_CLASS: "双子叶植物纲",S_ORDER: "大戟目",},
{S_DOMAIN: "真核域",S_KINGDOM: "植物界",S_PHYLUM: "被子植物门",S_CLASS: "双子叶植物纲",S_ORDER: "鼠李目",},
{S_DOMAIN: "真核域",S_KINGDOM: "植物界",S_PHYLUM: "被子植物门",S_CLASS: "双子叶植物纲",S_ORDER: "无患子目",TITLE: "芒果",F_GROUP: "wood",F_NAME: "guo10.jpg",},
{S_DOMAIN: "真核域",S_KINGDOM: "植物界",S_PHYLUM: "被子植物门",S_CLASS: "双子叶植物纲",S_ORDER: "牻牛儿苗目",TITLE: "凤仙花",F_GROUP: "wood",F_NAME: "fengxianhua.jpg",},
{S_DOMAIN: "真核域",S_KINGDOM: "植物界",S_PHYLUM: "被子植物门",S_CLASS: "双子叶植物纲",S_ORDER: "伞形目",TITLE: "铜钱草",F_GROUP: "wood",F_NAME: "tongqiancao.jpg",},
{S_DOMAIN: "真核域",S_KINGDOM: "植物界",S_PHYLUM: "被子植物门",S_CLASS: "双子叶植物纲",S_ORDER: "杜鹃花目",TITLE: "杜鹃花",F_GROUP: "wood",F_NAME: "zihua2.jpg",},
{S_DOMAIN: "真核域",S_KINGDOM: "植物界",S_PHYLUM: "被子植物门",S_CLASS: "双子叶植物纲",S_ORDER: "柿树目",TITLE: "柿子",F_GROUP: "wood",F_NAME: "shizi01.jpg",},
{S_DOMAIN: "真核域",S_KINGDOM: "植物界",S_PHYLUM: "被子植物门",S_CLASS: "双子叶植物纲",S_ORDER: "报春花目",TITLE: "广西过路黄",F_GROUP: "wood",F_NAME: "gxglh01.jpg",},
{S_DOMAIN: "真核域",S_KINGDOM: "植物界",S_PHYLUM: "被子植物门",S_CLASS: "双子叶植物纲",S_ORDER: "龙胆目",},
{S_DOMAIN: "真核域",S_KINGDOM: "植物界",S_PHYLUM: "被子植物门",S_CLASS: "双子叶植物纲",S_ORDER: "茄目",TITLE: "茑萝",F_GROUP: "wood",F_NAME: "niaoluo.jpg",},
{S_DOMAIN: "真核域",S_KINGDOM: "植物界",S_PHYLUM: "被子植物门",S_CLASS: "双子叶植物纲",S_ORDER: "唇形目",},
{S_DOMAIN: "真核域",S_KINGDOM: "植物界",S_PHYLUM: "被子植物门",S_CLASS: "双子叶植物纲",S_ORDER: "玄参目",},
{S_DOMAIN: "真核域",S_KINGDOM: "植物界",S_PHYLUM: "被子植物门",S_CLASS: "双子叶植物纲",S_ORDER: "桔梗目",TITLE: "黄秋英",F_GROUP: "wood",F_NAME: "chenghua01.jpg",},
{S_DOMAIN: "真核域",S_KINGDOM: "植物界",S_PHYLUM: "被子植物门",S_CLASS: "双子叶植物纲",S_ORDER: "茜草目",},
{S_DOMAIN: "真核域",S_KINGDOM: "植物界",S_PHYLUM: "被子植物门",S_CLASS: "双子叶植物纲",S_ORDER: "川续断目",},
{S_DOMAIN: "真核域",S_KINGDOM: "植物界",S_PHYLUM: "被子植物门",S_CLASS: "双子叶植物纲",S_ORDER: "菊目",TITLE: "鬼针草",F_GROUP: "wood",F_NAME: "guizhencao.jpg",},
{S_DOMAIN: "真核域",S_KINGDOM: "植物界",S_PHYLUM: "被子植物门",S_CLASS: "双子叶植物纲",S_ORDER: "管状花目",TITLE: "益母草",F_GROUP: "wood",F_NAME: "fenhua04.jpg",},
{S_DOMAIN: "真核域",S_KINGDOM: "植物界",S_PHYLUM: "被子植物门",S_CLASS: "双子叶植物纲",S_ORDER: "仙人掌目",TITLE: "仙人掌",F_GROUP: "wood",F_NAME: "xianrenz01.jpg",},
{S_DOMAIN: "真核域",S_KINGDOM: "植物界",S_PHYLUM: "被子植物门",S_CLASS: "双子叶植物纲",S_ORDER: "山毛榉目",TITLE: "板栗",F_GROUP: "wood",F_NAME: "banli01.jpg",},
{S_DOMAIN: "真核域",S_KINGDOM: "植物界",S_PHYLUM: "被子植物门",S_CLASS: "双子叶植物纲",S_ORDER: "杨梅目",TITLE: "杨梅子",F_GROUP: "wood",F_NAME: "yangmei01.jpg",},
{S_DOMAIN: "真核域",S_KINGDOM: "植物界",S_PHYLUM: "被子植物门",S_CLASS: "双子叶植物纲",S_ORDER: "捩花目",TITLE: "桂",F_GROUP: "wood",F_NAME: "guihua.jpg",},
{S_DOMAIN: "真核域",S_KINGDOM: "植物界",S_PHYLUM: "被子植物门",S_CLASS: "双子叶植物纲",S_ORDER: "中央种子目",TITLE: "三角梅",F_GROUP: "wood",F_NAME: "hongsanjiao.jpg",},
{S_DOMAIN: "真核域",S_KINGDOM: "植物界",S_PHYLUM: "被子植物门",S_CLASS: "双子叶植物纲",S_ORDER: "车前目",TITLE: "车前草",F_GROUP: "wood",F_NAME: "cheqian01.jpg",},
{S_DOMAIN: "真核域",S_KINGDOM: "植物界",S_PHYLUM: "被子植物门",S_CLASS: "双子叶植物纲",S_ORDER: "侧膜胎座目",TITLE: "长萼堇菜",F_GROUP: "wood",F_NAME: "zihuacao.jpg",},
/*{S_DOMAIN: "真核域",S_KINGDOM: "动物界",S_PHYLUM: "原生动物门",S_CLASS: "未知纲",S_ORDER: "未知目",},
{S_DOMAIN: "真核域",S_KINGDOM: "动物界",S_PHYLUM: "菱形虫门",S_CLASS: "未知纲",S_ORDER: "未知目",},
{S_DOMAIN: "真核域",S_KINGDOM: "动物界",S_PHYLUM: "直泳虫门",S_CLASS: "未知纲",S_ORDER: "未知目",},
{S_DOMAIN: "真核域",S_KINGDOM: "动物界",S_PHYLUM: "多孔动物门",S_CLASS: "未知纲",S_ORDER: "未知目",},
{S_DOMAIN: "真核域",S_KINGDOM: "动物界",S_PHYLUM: "扁盘动物门",S_CLASS: "未知纲",S_ORDER: "未知目",},
{S_DOMAIN: "真核域",S_KINGDOM: "动物界",S_PHYLUM: "古杯动物门",S_CLASS: "未知纲",S_ORDER: "未知目",},
{S_DOMAIN: "真核域",S_KINGDOM: "动物界",S_PHYLUM: "腔肠动物门",S_CLASS: "未知纲",S_ORDER: "未知目",},
{S_DOMAIN: "真核域",S_KINGDOM: "动物界",S_PHYLUM: "栉水母动物门",S_CLASS: "未知纲",S_ORDER: "未知目",},
{S_DOMAIN: "真核域",S_KINGDOM: "动物界",S_PHYLUM: "扁形动物门",S_CLASS: "未知纲",S_ORDER: "未知目",},
{S_DOMAIN: "真核域",S_KINGDOM: "动物界",S_PHYLUM: "环节动物门",S_CLASS: "多毛纲",S_ORDER: "未知目",},
{S_DOMAIN: "真核域",S_KINGDOM: "动物界",S_PHYLUM: "环节动物门",S_CLASS: "蛭纲",S_ORDER: "未知目",},*/
{S_DOMAIN: "真核域",S_KINGDOM: "动物界",S_PHYLUM: "环节动物门",S_CLASS: "寡毛纲",S_ORDER: "带丝蚓目",},
{S_DOMAIN: "真核域",S_KINGDOM: "动物界",S_PHYLUM: "环节动物门",S_CLASS: "寡毛纲",S_ORDER: "颤蚓目",},
{S_DOMAIN: "真核域",S_KINGDOM: "动物界",S_PHYLUM: "环节动物门",S_CLASS: "寡毛纲",S_ORDER: "单向蚓目",TITLE: "蚯蚓",F_GROUP: "miao",F_NAME: "qiuyin01.jpg",},
/*{S_DOMAIN: "真核域",S_KINGDOM: "动物界",S_PHYLUM: "螠虫动物门",S_CLASS: "未知纲",S_ORDER: "未知目",},
{S_DOMAIN: "真核域",S_KINGDOM: "动物界",S_PHYLUM: "纽形动物门",S_CLASS: "未知纲",S_ORDER: "未知目",},
{S_DOMAIN: "真核域",S_KINGDOM: "动物界",S_PHYLUM: "线虫动物门",S_CLASS: "未知纲",S_ORDER: "未知目",},
{S_DOMAIN: "真核域",S_KINGDOM: "动物界",S_PHYLUM: "线形动物门",S_CLASS: "未知纲",S_ORDER: "未知目",},
{S_DOMAIN: "真核域",S_KINGDOM: "动物界",S_PHYLUM: "星虫动物门",S_CLASS: "未知纲",S_ORDER: "未知目",},
{S_DOMAIN: "真核域",S_KINGDOM: "动物界",S_PHYLUM: "棘头动物门",S_CLASS: "未知纲",S_ORDER: "未知目",},
{S_DOMAIN: "真核域",S_KINGDOM: "动物界",S_PHYLUM: "须腕动物门",S_CLASS: "未知纲",S_ORDER: "未知目",},
{S_DOMAIN: "真核域",S_KINGDOM: "动物界",S_PHYLUM: "毛颚动物门",S_CLASS: "未知纲",S_ORDER: "未知目",},
{S_DOMAIN: "真核域",S_KINGDOM: "动物界",S_PHYLUM: "软体动物门",S_CLASS: "无板纲",S_ORDER: "未知目",},
{S_DOMAIN: "真核域",S_KINGDOM: "动物界",S_PHYLUM: "软体动物门",S_CLASS: "多板纲",S_ORDER: "未知目",},
{S_DOMAIN: "真核域",S_KINGDOM: "动物界",S_PHYLUM: "软体动物门",S_CLASS: "掘足纲",S_ORDER: "未知目",},
{S_DOMAIN: "真核域",S_KINGDOM: "动物界",S_PHYLUM: "软体动物门",S_CLASS: "双壳纲",S_ORDER: "未知目",},
{S_DOMAIN: "真核域",S_KINGDOM: "动物界",S_PHYLUM: "软体动物门",S_CLASS: "头足纲",S_ORDER: "未知目",},*/
{S_DOMAIN: "真核域",S_KINGDOM: "动物界",S_PHYLUM: "软体动物门",S_CLASS: "腹足纲",S_ORDER: "古腹足目",},
{S_DOMAIN: "真核域",S_KINGDOM: "动物界",S_PHYLUM: "软体动物门",S_CLASS: "腹足纲",S_ORDER: "中腹足目",TITLE: "海螺",F_GROUP: "miao",F_NAME: "luo02.jpg",},
{S_DOMAIN: "真核域",S_KINGDOM: "动物界",S_PHYLUM: "软体动物门",S_CLASS: "腹足纲",S_ORDER: "新腹足目",},
{S_DOMAIN: "真核域",S_KINGDOM: "动物界",S_PHYLUM: "软体动物门",S_CLASS: "腹足纲",S_ORDER: "无楯目",},
{S_DOMAIN: "真核域",S_KINGDOM: "动物界",S_PHYLUM: "软体动物门",S_CLASS: "腹足纲",S_ORDER: "被壳翼足目",},
{S_DOMAIN: "真核域",S_KINGDOM: "动物界",S_PHYLUM: "软体动物门",S_CLASS: "腹足纲",S_ORDER: "裸体翼足目",},
{S_DOMAIN: "真核域",S_KINGDOM: "动物界",S_PHYLUM: "软体动物门",S_CLASS: "腹足纲",S_ORDER: "囊舌目",},
{S_DOMAIN: "真核域",S_KINGDOM: "动物界",S_PHYLUM: "软体动物门",S_CLASS: "腹足纲",S_ORDER: "背楯目",},
{S_DOMAIN: "真核域",S_KINGDOM: "动物界",S_PHYLUM: "软体动物门",S_CLASS: "腹足纲",S_ORDER: "裸鳃目",},
{S_DOMAIN: "真核域",S_KINGDOM: "动物界",S_PHYLUM: "软体动物门",S_CLASS: "腹足纲",S_ORDER: "基眼目",},
{S_DOMAIN: "真核域",S_KINGDOM: "动物界",S_PHYLUM: "软体动物门",S_CLASS: "腹足纲",S_ORDER: "柄眼目",TITLE: "蜗牛",F_GROUP: "miao",F_NAME: "woniu01.jpg",},
/*{S_DOMAIN: "真核域",S_KINGDOM: "动物界",S_PHYLUM: "节肢动物门",S_CLASS: "三叶虫纲",S_ORDER: "未知目",},
{S_DOMAIN: "真核域",S_KINGDOM: "动物界",S_PHYLUM: "节肢动物门",S_CLASS: "颚足纲",S_ORDER: "未知目",},
{S_DOMAIN: "真核域",S_KINGDOM: "动物界",S_PHYLUM: "节肢动物门",S_CLASS: "内口纲",S_ORDER: "未知目",},
{S_DOMAIN: "真核域",S_KINGDOM: "动物界",S_PHYLUM: "节肢动物门",S_CLASS: "海蜘蛛纲",S_ORDER: "未知目",},
{S_DOMAIN: "真核域",S_KINGDOM: "动物界",S_PHYLUM: "节肢动物门",S_CLASS: "头虾纲",S_ORDER: "未知目",},
{S_DOMAIN: "真核域",S_KINGDOM: "动物界",S_PHYLUM: "节肢动物门",S_CLASS: "桨足纲",S_ORDER: "未知目",},
{S_DOMAIN: "真核域",S_KINGDOM: "动物界",S_PHYLUM: "节肢动物门",S_CLASS: "鳃足纲",S_ORDER: "未知目",},
{S_DOMAIN: "真核域",S_KINGDOM: "动物界",S_PHYLUM: "节肢动物门",S_CLASS: "少足纲",S_ORDER: "未知目",},
{S_DOMAIN: "真核域",S_KINGDOM: "动物界",S_PHYLUM: "节肢动物门",S_CLASS: "综合纲",S_ORDER: "未知目",},*/
{S_DOMAIN: "真核域",S_KINGDOM: "动物界",S_PHYLUM: "节肢动物门",S_CLASS: "肢口纲",S_ORDER: "剑尾目",TITLE: "鲎",F_GROUP: "miao",F_NAME: "hou02.jpg",},
{S_DOMAIN: "真核域",S_KINGDOM: "动物界",S_PHYLUM: "节肢动物门",S_CLASS: "蛛形纲",S_ORDER: "蝎目",},
{S_DOMAIN: "真核域",S_KINGDOM: "动物界",S_PHYLUM: "节肢动物门",S_CLASS: "蛛形纲",S_ORDER: "伪蝎目",},
{S_DOMAIN: "真核域",S_KINGDOM: "动物界",S_PHYLUM: "节肢动物门",S_CLASS: "蛛形纲",S_ORDER: "盲蛛目",},
{S_DOMAIN: "真核域",S_KINGDOM: "动物界",S_PHYLUM: "节肢动物门",S_CLASS: "蛛形纲",S_ORDER: "蜱螨目",TITLE: "螨虫",F_GROUP: "bug",F_NAME: "manc01.jpg",},
{S_DOMAIN: "真核域",S_KINGDOM: "动物界",S_PHYLUM: "节肢动物门",S_CLASS: "蛛形纲",S_ORDER: "须脚目",},
{S_DOMAIN: "真核域",S_KINGDOM: "动物界",S_PHYLUM: "节肢动物门",S_CLASS: "蛛形纲",S_ORDER: "有鞭目",},
{S_DOMAIN: "真核域",S_KINGDOM: "动物界",S_PHYLUM: "节肢动物门",S_CLASS: "蛛形纲",S_ORDER: "裂盾目",},
{S_DOMAIN: "真核域",S_KINGDOM: "动物界",S_PHYLUM: "节肢动物门",S_CLASS: "蛛形纲",S_ORDER: "无鞭目",},
{S_DOMAIN: "真核域",S_KINGDOM: "动物界",S_PHYLUM: "节肢动物门",S_CLASS: "蛛形纲",S_ORDER: "蜘蛛目",TITLE: "蜘蛛",F_GROUP: "bug",F_NAME: "zhu09.jpg",},
{S_DOMAIN: "真核域",S_KINGDOM: "动物界",S_PHYLUM: "节肢动物门",S_CLASS: "蛛形纲",S_ORDER: "节腹目",},
{S_DOMAIN: "真核域",S_KINGDOM: "动物界",S_PHYLUM: "节肢动物门",S_CLASS: "蛛形纲",S_ORDER: "避日目",},
{S_DOMAIN: "真核域",S_KINGDOM: "动物界",S_PHYLUM: "节肢动物门",S_CLASS: "软甲纲",S_ORDER: "涟虫目",},
{S_DOMAIN: "真核域",S_KINGDOM: "动物界",S_PHYLUM: "节肢动物门",S_CLASS: "软甲纲",S_ORDER: "十足目",TITLE: "螃蟹",F_GROUP: "miao",F_NAME: "xie07.jpg",},
{S_DOMAIN: "真核域",S_KINGDOM: "动物界",S_PHYLUM: "节肢动物门",S_CLASS: "软甲纲",S_ORDER: "口足目",},
{S_DOMAIN: "真核域",S_KINGDOM: "动物界",S_PHYLUM: "节肢动物门",S_CLASS: "软甲纲",S_ORDER: "原足目",},
{S_DOMAIN: "真核域",S_KINGDOM: "动物界",S_PHYLUM: "节肢动物门",S_CLASS: "软甲纲",S_ORDER: "等足目",TITLE: "海蟑螂",F_GROUP: "miao",F_NAME: "haizhanglang01.jpg",},
{S_DOMAIN: "真核域",S_KINGDOM: "动物界",S_PHYLUM: "节肢动物门",S_CLASS: "软甲纲",S_ORDER: "端足目",},
{S_DOMAIN: "真核域",S_KINGDOM: "动物界",S_PHYLUM: "节肢动物门",S_CLASS: "软甲纲",S_ORDER: "混足目",},
{S_DOMAIN: "真核域",S_KINGDOM: "动物界",S_PHYLUM: "节肢动物门",S_CLASS: "软甲纲",S_ORDER: "异虾目",},
{S_DOMAIN: "真核域",S_KINGDOM: "动物界",S_PHYLUM: "节肢动物门",S_CLASS: "软甲纲",S_ORDER: "叶虾目",},
{S_DOMAIN: "真核域",S_KINGDOM: "动物界",S_PHYLUM: "节肢动物门",S_CLASS: "软甲纲",S_ORDER: "磷虾目",},
{S_DOMAIN: "真核域",S_KINGDOM: "动物界",S_PHYLUM: "节肢动物门",S_CLASS: "软甲纲",S_ORDER: "糠虾目",},
{S_DOMAIN: "真核域",S_KINGDOM: "动物界",S_PHYLUM: "节肢动物门",S_CLASS: "软甲纲",S_ORDER: "山虾目",},
{S_DOMAIN: "真核域",S_KINGDOM: "动物界",S_PHYLUM: "节肢动物门",S_CLASS: "软甲纲",S_ORDER: "地虾目",},
{S_DOMAIN: "真核域",S_KINGDOM: "动物界",S_PHYLUM: "节肢动物门",S_CLASS: "软甲纲",S_ORDER: "洞虾目",},
{S_DOMAIN: "真核域",S_KINGDOM: "动物界",S_PHYLUM: "节肢动物门",S_CLASS: "软甲纲",S_ORDER: "温泉虾目",},
{S_DOMAIN: "真核域",S_KINGDOM: "动物界",S_PHYLUM: "节肢动物门",S_CLASS: "软甲纲",S_ORDER: "疣背糠虾目",},
{S_DOMAIN: "真核域",S_KINGDOM: "动物界",S_PHYLUM: "节肢动物门",S_CLASS: "蔓足纲",S_ORDER: "无柄目",TITLE: "藤壶",F_GROUP: "scene",F_NAME: "haishi.jpg",},
{S_DOMAIN: "真核域",S_KINGDOM: "动物界",S_PHYLUM: "节肢动物门",S_CLASS: "昆虫纲",S_ORDER: "石蛃目",},
{S_DOMAIN: "真核域",S_KINGDOM: "动物界",S_PHYLUM: "节肢动物门",S_CLASS: "昆虫纲",S_ORDER: "缨尾目",TITLE: "衣鱼",F_GROUP: "bug",F_NAME: "yiyu01.jpg",},
{S_DOMAIN: "真核域",S_KINGDOM: "动物界",S_PHYLUM: "节肢动物门",S_CLASS: "昆虫纲",S_ORDER: "蜉蝣目",},
{S_DOMAIN: "真核域",S_KINGDOM: "动物界",S_PHYLUM: "节肢动物门",S_CLASS: "昆虫纲",S_ORDER: "蜻蜓目",TITLE: "蜻蜓",F_GROUP: "bug",F_NAME: "qingting11.jpg",},
{S_DOMAIN: "真核域",S_KINGDOM: "动物界",S_PHYLUM: "节肢动物门",S_CLASS: "昆虫纲",S_ORDER: "襀翅目",TITLE: "石蝇",F_GROUP: "bug",F_NAME: "zhichi04.jpg",},
{S_DOMAIN: "真核域",S_KINGDOM: "动物界",S_PHYLUM: "节肢动物门",S_CLASS: "昆虫纲",S_ORDER: "蜚蠊目",TITLE: "蟑螂",F_GROUP: "bug",F_NAME: "zhanglang01.jpg",},
{S_DOMAIN: "真核域",S_KINGDOM: "动物界",S_PHYLUM: "节肢动物门",S_CLASS: "昆虫纲",S_ORDER: "螳螂目",TITLE: "螳螂",F_GROUP: "bug",F_NAME: "tanglang01.jpg",},
{S_DOMAIN: "真核域",S_KINGDOM: "动物界",S_PHYLUM: "节肢动物门",S_CLASS: "昆虫纲",S_ORDER: "蛩蠊目",},
{S_DOMAIN: "真核域",S_KINGDOM: "动物界",S_PHYLUM: "节肢动物门",S_CLASS: "昆虫纲",S_ORDER: "螳䗛目",},
{S_DOMAIN: "真核域",S_KINGDOM: "动物界",S_PHYLUM: "节肢动物门",S_CLASS: "昆虫纲",S_ORDER: "竹节虫目",TITLE: "竹节虫",F_GROUP: "bug",F_NAME: "zhujie01.jpg",},
{S_DOMAIN: "真核域",S_KINGDOM: "动物界",S_PHYLUM: "节肢动物门",S_CLASS: "昆虫纲",S_ORDER: "纺足目",},
{S_DOMAIN: "真核域",S_KINGDOM: "动物界",S_PHYLUM: "节肢动物门",S_CLASS: "昆虫纲",S_ORDER: "直翅目",TITLE: "蝈蝈",F_GROUP: "bug",F_NAME: "guoguo01.jpg",},
{S_DOMAIN: "真核域",S_KINGDOM: "动物界",S_PHYLUM: "节肢动物门",S_CLASS: "昆虫纲",S_ORDER: "革翅目",TITLE: "蠼螋",F_GROUP: "bug",F_NAME: "qusou01.jpg",},
{S_DOMAIN: "真核域",S_KINGDOM: "动物界",S_PHYLUM: "节肢动物门",S_CLASS: "昆虫纲",S_ORDER: "缺翅目",},
{S_DOMAIN: "真核域",S_KINGDOM: "动物界",S_PHYLUM: "节肢动物门",S_CLASS: "昆虫纲",S_ORDER: "虱目",},
{S_DOMAIN: "真核域",S_KINGDOM: "动物界",S_PHYLUM: "节肢动物门",S_CLASS: "昆虫纲",S_ORDER: "啮虫目",},
{S_DOMAIN: "真核域",S_KINGDOM: "动物界",S_PHYLUM: "节肢动物门",S_CLASS: "昆虫纲",S_ORDER: "缨翅目",},
{S_DOMAIN: "真核域",S_KINGDOM: "动物界",S_PHYLUM: "节肢动物门",S_CLASS: "昆虫纲",S_ORDER: "半翅目",TITLE: "椿象",F_GROUP: "bug",F_NAME: "chunxiang01.jpg",},
{S_DOMAIN: "真核域",S_KINGDOM: "动物界",S_PHYLUM: "节肢动物门",S_CLASS: "昆虫纲",S_ORDER: "脉翅目",TITLE: "蚜狮",F_GROUP: "bug",F_NAME: "yashi01.jpg",},
{S_DOMAIN: "真核域",S_KINGDOM: "动物界",S_PHYLUM: "节肢动物门",S_CLASS: "昆虫纲",S_ORDER: "广翅目",TITLE: "中华斑鱼蛉",F_GROUP: "bug",F_NAME: "yuling01.jpg",},
{S_DOMAIN: "真核域",S_KINGDOM: "动物界",S_PHYLUM: "节肢动物门",S_CLASS: "昆虫纲",S_ORDER: "蛇蛉目",},
{S_DOMAIN: "真核域",S_KINGDOM: "动物界",S_PHYLUM: "节肢动物门",S_CLASS: "昆虫纲",S_ORDER: "鞘翅目",TITLE: "天牛",F_GROUP: "bug",F_NAME: "tianniu01.jpg",},
{S_DOMAIN: "真核域",S_KINGDOM: "动物界",S_PHYLUM: "节肢动物门",S_CLASS: "昆虫纲",S_ORDER: "双翅目",TITLE: "苍蝇",F_GROUP: "bug",F_NAME: "cangying02.jpg",},
{S_DOMAIN: "真核域",S_KINGDOM: "动物界",S_PHYLUM: "节肢动物门",S_CLASS: "昆虫纲",S_ORDER: "蚤目",},
{S_DOMAIN: "真核域",S_KINGDOM: "动物界",S_PHYLUM: "节肢动物门",S_CLASS: "昆虫纲",S_ORDER: "捻翅目",},
{S_DOMAIN: "真核域",S_KINGDOM: "动物界",S_PHYLUM: "节肢动物门",S_CLASS: "昆虫纲",S_ORDER: "长翅目",},
{S_DOMAIN: "真核域",S_KINGDOM: "动物界",S_PHYLUM: "节肢动物门",S_CLASS: "昆虫纲",S_ORDER: "毛翅目",},
{S_DOMAIN: "真核域",S_KINGDOM: "动物界",S_PHYLUM: "节肢动物门",S_CLASS: "昆虫纲",S_ORDER: "鳞翅目",TITLE: "蛇目褐蚬蝶",F_GROUP: "bug",F_NAME: "die44.jpg",},
{S_DOMAIN: "真核域",S_KINGDOM: "动物界",S_PHYLUM: "节肢动物门",S_CLASS: "昆虫纲",S_ORDER: "膜翅目",TITLE: "蜜蜂",F_GROUP: "bug",F_NAME: "feng02.jpg",},
{S_DOMAIN: "真核域",S_KINGDOM: "动物界",S_PHYLUM: "节肢动物门",S_CLASS: "倍足纲",S_ORDER: "毛马陆目",},
{S_DOMAIN: "真核域",S_KINGDOM: "动物界",S_PHYLUM: "节肢动物门",S_CLASS: "倍足纲",S_ORDER: "蟠马陆目",},
{S_DOMAIN: "真核域",S_KINGDOM: "动物界",S_PHYLUM: "节肢动物门",S_CLASS: "倍足纲",S_ORDER: "蛞形目",},
{S_DOMAIN: "真核域",S_KINGDOM: "动物界",S_PHYLUM: "节肢动物门",S_CLASS: "倍足纲",S_ORDER: "山蛩目",TITLE: "山蛩",F_GROUP: "bug",F_NAME: "malu01.jpg",},
{S_DOMAIN: "真核域",S_KINGDOM: "动物界",S_PHYLUM: "节肢动物门",S_CLASS: "倍足纲",S_ORDER: "条马陆目",TITLE: "条马陆",F_GROUP: "bug",F_NAME: "wugong02.jpg",},
{S_DOMAIN: "真核域",S_KINGDOM: "动物界",S_PHYLUM: "节肢动物门",S_CLASS: "倍足纲",S_ORDER: "球马陆目",},
{S_DOMAIN: "真核域",S_KINGDOM: "动物界",S_PHYLUM: "节肢动物门",S_CLASS: "倍足纲",S_ORDER: "绩马陆目",},
{S_DOMAIN: "真核域",S_KINGDOM: "动物界",S_PHYLUM: "节肢动物门",S_CLASS: "倍足纲",S_ORDER: "带马陆目",},
{S_DOMAIN: "真核域",S_KINGDOM: "动物界",S_PHYLUM: "节肢动物门",S_CLASS: "倍足纲",S_ORDER: "姬马陆目",},
{S_DOMAIN: "真核域",S_KINGDOM: "动物界",S_PHYLUM: "节肢动物门",S_CLASS: "倍足纲",S_ORDER: "畸颚目",},
{S_DOMAIN: "真核域",S_KINGDOM: "动物界",S_PHYLUM: "节肢动物门",S_CLASS: "唇足纲",S_ORDER: "地蜈蚣目",},
{S_DOMAIN: "真核域",S_KINGDOM: "动物界",S_PHYLUM: "节肢动物门",S_CLASS: "唇足纲",S_ORDER: "蜈蚣目",TITLE: "蜈蚣",F_GROUP: "bug",F_NAME: "wugong01.jpg",},
{S_DOMAIN: "真核域",S_KINGDOM: "动物界",S_PHYLUM: "节肢动物门",S_CLASS: "唇足纲",S_ORDER: "石蜈蚣目",},
{S_DOMAIN: "真核域",S_KINGDOM: "动物界",S_PHYLUM: "节肢动物门",S_CLASS: "唇足纲",S_ORDER: "蚰蜒目",},
/*{S_DOMAIN: "真核域",S_KINGDOM: "动物界",S_PHYLUM: "叶足动物门",S_CLASS: "未知纲",S_ORDER: "未知目",},
{S_DOMAIN: "真核域",S_KINGDOM: "动物界",S_PHYLUM: "缓步动物门",S_CLASS: "未知纲",S_ORDER: "未知目",},
{S_DOMAIN: "真核域",S_KINGDOM: "动物界",S_PHYLUM: "有爪动物门",S_CLASS: "未知纲",S_ORDER: "未知目",},
{S_DOMAIN: "真核域",S_KINGDOM: "动物界",S_PHYLUM: "腹毛动物门",S_CLASS: "未知纲",S_ORDER: "未知目",},
{S_DOMAIN: "真核域",S_KINGDOM: "动物界",S_PHYLUM: "轮虫动物门",S_CLASS: "未知纲",S_ORDER: "未知目",},
{S_DOMAIN: "真核域",S_KINGDOM: "动物界",S_PHYLUM: "鳃曳动物门",S_CLASS: "未知纲",S_ORDER: "未知目",},
{S_DOMAIN: "真核域",S_KINGDOM: "动物界",S_PHYLUM: "动吻动物门",S_CLASS: "未知纲",S_ORDER: "未知目",},
{S_DOMAIN: "真核域",S_KINGDOM: "动物界",S_PHYLUM: "铠甲动物门",S_CLASS: "未知纲",S_ORDER: "未知目",},
{S_DOMAIN: "真核域",S_KINGDOM: "动物界",S_PHYLUM: "内肛动物门",S_CLASS: "未知纲",S_ORDER: "未知目",},
{S_DOMAIN: "真核域",S_KINGDOM: "动物界",S_PHYLUM: "环口动物门",S_CLASS: "未知纲",S_ORDER: "未知目",},
{S_DOMAIN: "真核域",S_KINGDOM: "动物界",S_PHYLUM: "舌形动物门",S_CLASS: "未知纲",S_ORDER: "未知目",},
{S_DOMAIN: "真核域",S_KINGDOM: "动物界",S_PHYLUM: "微颚动物门",S_CLASS: "未知纲",S_ORDER: "未知目",},
{S_DOMAIN: "真核域",S_KINGDOM: "动物界",S_PHYLUM: "颚胃动物门",S_CLASS: "未知纲",S_ORDER: "未知目",},
{S_DOMAIN: "真核域",S_KINGDOM: "动物界",S_PHYLUM: "腕足动物门",S_CLASS: "未知纲",S_ORDER: "未知目",},
{S_DOMAIN: "真核域",S_KINGDOM: "动物界",S_PHYLUM: "外肛动物门",S_CLASS: "未知纲",S_ORDER: "未知目",},
{S_DOMAIN: "真核域",S_KINGDOM: "动物界",S_PHYLUM: "帚虫动物门",S_CLASS: "未知纲",S_ORDER: "未知目",},
{S_DOMAIN: "真核域",S_KINGDOM: "动物界",S_PHYLUM: "棘皮动物门",S_CLASS: "未知纲",S_ORDER: "未知目",},
{S_DOMAIN: "真核域",S_KINGDOM: "动物界",S_PHYLUM: "须腕动物门",S_CLASS: "未知纲",S_ORDER: "未知目",},
{S_DOMAIN: "真核域",S_KINGDOM: "动物界",S_PHYLUM: "异涡动物门",S_CLASS: "未知纲",S_ORDER: "未知目",},
{S_DOMAIN: "真核域",S_KINGDOM: "动物界",S_PHYLUM: "半索动物门",S_CLASS: "未知纲",S_ORDER: "未知目",},
{S_DOMAIN: "真核域",S_KINGDOM: "动物界",S_PHYLUM: "脊索动物门",S_CLASS: "尾海鞘纲",S_ORDER: "未知目",},
{S_DOMAIN: "真核域",S_KINGDOM: "动物界",S_PHYLUM: "脊索动物门",S_CLASS: "海鞘纲",S_ORDER: "未知目",},
{S_DOMAIN: "真核域",S_KINGDOM: "动物界",S_PHYLUM: "脊索动物门",S_CLASS: "海樽纲",S_ORDER: "未知目",},*/
{S_DOMAIN: "真核域",S_KINGDOM: "动物界",S_PHYLUM: "脊索动物门",S_CLASS: "圆口纲",S_ORDER: "七鳃鳗目",},
{S_DOMAIN: "真核域",S_KINGDOM: "动物界",S_PHYLUM: "脊索动物门",S_CLASS: "圆口纲",S_ORDER: "盲鳗目",},
{S_DOMAIN: "真核域",S_KINGDOM: "动物界",S_PHYLUM: "脊索动物门",S_CLASS: "软骨鱼纲",S_ORDER: "六鳃鲨目",},
{S_DOMAIN: "真核域",S_KINGDOM: "动物界",S_PHYLUM: "脊索动物门",S_CLASS: "软骨鱼纲",S_ORDER: "虎鲨目",},
{S_DOMAIN: "真核域",S_KINGDOM: "动物界",S_PHYLUM: "脊索动物门",S_CLASS: "软骨鱼纲",S_ORDER: "鼠鲨目",},
{S_DOMAIN: "真核域",S_KINGDOM: "动物界",S_PHYLUM: "脊索动物门",S_CLASS: "软骨鱼纲",S_ORDER: "须鲨目",},
{S_DOMAIN: "真核域",S_KINGDOM: "动物界",S_PHYLUM: "脊索动物门",S_CLASS: "软骨鱼纲",S_ORDER: "真鲨目",},
{S_DOMAIN: "真核域",S_KINGDOM: "动物界",S_PHYLUM: "脊索动物门",S_CLASS: "软骨鱼纲",S_ORDER: "角鲨目",},
{S_DOMAIN: "真核域",S_KINGDOM: "动物界",S_PHYLUM: "脊索动物门",S_CLASS: "软骨鱼纲",S_ORDER: "扁鲨目",},
{S_DOMAIN: "真核域",S_KINGDOM: "动物界",S_PHYLUM: "脊索动物门",S_CLASS: "软骨鱼纲",S_ORDER: "锯鲨目",},
{S_DOMAIN: "真核域",S_KINGDOM: "动物界",S_PHYLUM: "脊索动物门",S_CLASS: "软骨鱼纲",S_ORDER: "胸脊鲨目",},
{S_DOMAIN: "真核域",S_KINGDOM: "动物界",S_PHYLUM: "脊索动物门",S_CLASS: "软骨鱼纲",S_ORDER: "筋异刺鲨目",},
{S_DOMAIN: "真核域",S_KINGDOM: "动物界",S_PHYLUM: "脊索动物门",S_CLASS: "软骨鱼纲",S_ORDER: "旋齿鲨目",},
{S_DOMAIN: "真核域",S_KINGDOM: "动物界",S_PHYLUM: "脊索动物门",S_CLASS: "软骨鱼纲",S_ORDER: "锯鳐目",},
{S_DOMAIN: "真核域",S_KINGDOM: "动物界",S_PHYLUM: "脊索动物门",S_CLASS: "软骨鱼纲",S_ORDER: "鳐形目",},
{S_DOMAIN: "真核域",S_KINGDOM: "动物界",S_PHYLUM: "脊索动物门",S_CLASS: "软骨鱼纲",S_ORDER: "鲼形目",},
{S_DOMAIN: "真核域",S_KINGDOM: "动物界",S_PHYLUM: "脊索动物门",S_CLASS: "软骨鱼纲",S_ORDER: "电鳐目",},
{S_DOMAIN: "真核域",S_KINGDOM: "动物界",S_PHYLUM: "脊索动物门",S_CLASS: "软骨鱼纲",S_ORDER: "犁头鳐目",},
{S_DOMAIN: "真核域",S_KINGDOM: "动物界",S_PHYLUM: "脊索动物门",S_CLASS: "软骨鱼纲",S_ORDER: "银鲛目",},
{S_DOMAIN: "真核域",S_KINGDOM: "动物界",S_PHYLUM: "脊索动物门",S_CLASS: "硬骨鱼纲",S_ORDER: "单鳔肺鱼目",},
{S_DOMAIN: "真核域",S_KINGDOM: "动物界",S_PHYLUM: "脊索动物门",S_CLASS: "硬骨鱼纲",S_ORDER: "双鳔肺鱼目",},
{S_DOMAIN: "真核域",S_KINGDOM: "动物界",S_PHYLUM: "脊索动物门",S_CLASS: "硬骨鱼纲",S_ORDER: "腔棘目",},
{S_DOMAIN: "真核域",S_KINGDOM: "动物界",S_PHYLUM: "脊索动物门",S_CLASS: "硬骨鱼纲",S_ORDER: "多鳍鱼目",},
{S_DOMAIN: "真核域",S_KINGDOM: "动物界",S_PHYLUM: "脊索动物门",S_CLASS: "硬骨鱼纲",S_ORDER: "鲟形目",},
{S_DOMAIN: "真核域",S_KINGDOM: "动物界",S_PHYLUM: "脊索动物门",S_CLASS: "硬骨鱼纲",S_ORDER: "弓鳍鱼目",},
{S_DOMAIN: "真核域",S_KINGDOM: "动物界",S_PHYLUM: "脊索动物门",S_CLASS: "硬骨鱼纲",S_ORDER: "雀鳝目",},
{S_DOMAIN: "真核域",S_KINGDOM: "动物界",S_PHYLUM: "脊索动物门",S_CLASS: "硬骨鱼纲",S_ORDER: "海鲢目",},
{S_DOMAIN: "真核域",S_KINGDOM: "动物界",S_PHYLUM: "脊索动物门",S_CLASS: "硬骨鱼纲",S_ORDER: "鼠鱚目",},
{S_DOMAIN: "真核域",S_KINGDOM: "动物界",S_PHYLUM: "脊索动物门",S_CLASS: "硬骨鱼纲",S_ORDER: "鲱形目",},
{S_DOMAIN: "真核域",S_KINGDOM: "动物界",S_PHYLUM: "脊索动物门",S_CLASS: "硬骨鱼纲",S_ORDER: "鲑形目",},
{S_DOMAIN: "真核域",S_KINGDOM: "动物界",S_PHYLUM: "脊索动物门",S_CLASS: "硬骨鱼纲",S_ORDER: "灯笼鱼目",},
{S_DOMAIN: "真核域",S_KINGDOM: "动物界",S_PHYLUM: "脊索动物门",S_CLASS: "硬骨鱼纲",S_ORDER: "鲸口鱼目",},
{S_DOMAIN: "真核域",S_KINGDOM: "动物界",S_PHYLUM: "脊索动物门",S_CLASS: "硬骨鱼纲",S_ORDER: "鳗鲡目",},
{S_DOMAIN: "真核域",S_KINGDOM: "动物界",S_PHYLUM: "脊索动物门",S_CLASS: "硬骨鱼纲",S_ORDER: "背棘鱼目",},
{S_DOMAIN: "真核域",S_KINGDOM: "动物界",S_PHYLUM: "脊索动物门",S_CLASS: "硬骨鱼纲",S_ORDER: "骨舌鱼目",},
{S_DOMAIN: "真核域",S_KINGDOM: "动物界",S_PHYLUM: "脊索动物门",S_CLASS: "硬骨鱼纲",S_ORDER: "鲤形目",TITLE: "草鱼",F_GROUP: "miao",F_NAME: "caoyu.jpg",},
{S_DOMAIN: "真核域",S_KINGDOM: "动物界",S_PHYLUM: "脊索动物门",S_CLASS: "硬骨鱼纲",S_ORDER: "鲇形目",},
{S_DOMAIN: "真核域",S_KINGDOM: "动物界",S_PHYLUM: "脊索动物门",S_CLASS: "硬骨鱼纲",S_ORDER: "鳉形目",},
{S_DOMAIN: "真核域",S_KINGDOM: "动物界",S_PHYLUM: "脊索动物门",S_CLASS: "硬骨鱼纲",S_ORDER: "银汉鱼目",},
{S_DOMAIN: "真核域",S_KINGDOM: "动物界",S_PHYLUM: "脊索动物门",S_CLASS: "硬骨鱼纲",S_ORDER: "颌针鱼目",},
{S_DOMAIN: "真核域",S_KINGDOM: "动物界",S_PHYLUM: "脊索动物门",S_CLASS: "硬骨鱼纲",S_ORDER: "鲑鲈目",},
{S_DOMAIN: "真核域",S_KINGDOM: "动物界",S_PHYLUM: "脊索动物门",S_CLASS: "硬骨鱼纲",S_ORDER: "鳕形目",},
{S_DOMAIN: "真核域",S_KINGDOM: "动物界",S_PHYLUM: "脊索动物门",S_CLASS: "硬骨鱼纲",S_ORDER: "金眼鲷目",},
{S_DOMAIN: "真核域",S_KINGDOM: "动物界",S_PHYLUM: "脊索动物门",S_CLASS: "硬骨鱼纲",S_ORDER: "海鲂目",},
{S_DOMAIN: "真核域",S_KINGDOM: "动物界",S_PHYLUM: "脊索动物门",S_CLASS: "硬骨鱼纲",S_ORDER: "月鱼目",},
{S_DOMAIN: "真核域",S_KINGDOM: "动物界",S_PHYLUM: "脊索动物门",S_CLASS: "硬骨鱼纲",S_ORDER: "刺鱼目",},
{S_DOMAIN: "真核域",S_KINGDOM: "动物界",S_PHYLUM: "脊索动物门",S_CLASS: "硬骨鱼纲",S_ORDER: "鲻形目",},
{S_DOMAIN: "真核域",S_KINGDOM: "动物界",S_PHYLUM: "脊索动物门",S_CLASS: "硬骨鱼纲",S_ORDER: "合鳃鱼目",},
{S_DOMAIN: "真核域",S_KINGDOM: "动物界",S_PHYLUM: "脊索动物门",S_CLASS: "硬骨鱼纲",S_ORDER: "鲈形目",},
{S_DOMAIN: "真核域",S_KINGDOM: "动物界",S_PHYLUM: "脊索动物门",S_CLASS: "硬骨鱼纲",S_ORDER: "鲉形目",},
{S_DOMAIN: "真核域",S_KINGDOM: "动物界",S_PHYLUM: "脊索动物门",S_CLASS: "硬骨鱼纲",S_ORDER: "鲽形目",},
{S_DOMAIN: "真核域",S_KINGDOM: "动物界",S_PHYLUM: "脊索动物门",S_CLASS: "硬骨鱼纲",S_ORDER: "鲀形目",},
{S_DOMAIN: "真核域",S_KINGDOM: "动物界",S_PHYLUM: "脊索动物门",S_CLASS: "硬骨鱼纲",S_ORDER: "蟾鱼目",},
{S_DOMAIN: "真核域",S_KINGDOM: "动物界",S_PHYLUM: "脊索动物门",S_CLASS: "硬骨鱼纲",S_ORDER: "海蛾鱼目",},
{S_DOMAIN: "真核域",S_KINGDOM: "动物界",S_PHYLUM: "脊索动物门",S_CLASS: "硬骨鱼纲",S_ORDER: "喉盘鱼目",},
{S_DOMAIN: "真核域",S_KINGDOM: "动物界",S_PHYLUM: "脊索动物门",S_CLASS: "硬骨鱼纲",S_ORDER: "鮟鱇目",},
{S_DOMAIN: "真核域",S_KINGDOM: "动物界",S_PHYLUM: "脊索动物门",S_CLASS: "头索纲",S_ORDER: "文昌鱼目",},
{S_DOMAIN: "真核域",S_KINGDOM: "动物界",S_PHYLUM: "脊索动物门",S_CLASS: "两栖纲",S_ORDER: "蚓螈目",},
{S_DOMAIN: "真核域",S_KINGDOM: "动物界",S_PHYLUM: "脊索动物门",S_CLASS: "两栖纲",S_ORDER: "有尾目",},
{S_DOMAIN: "真核域",S_KINGDOM: "动物界",S_PHYLUM: "脊索动物门",S_CLASS: "两栖纲",S_ORDER: "无尾目",TITLE: "蛙",F_GROUP: "miao",F_NAME: "wa01.jpg",},
{S_DOMAIN: "真核域",S_KINGDOM: "动物界",S_PHYLUM: "脊索动物门",S_CLASS: "爬行纲",S_ORDER: "龟鳖目",TITLE: "乌龟",F_GROUP: "miao",F_NAME: "gui.jpg",},
{S_DOMAIN: "真核域",S_KINGDOM: "动物界",S_PHYLUM: "脊索动物门",S_CLASS: "爬行纲",S_ORDER: "有鳞目",TITLE: "南草蜥",F_GROUP: "miao",F_NAME: "xiyi01.jpg",F_DESC: "路边偶遇",},
{S_DOMAIN: "真核域",S_KINGDOM: "动物界",S_PHYLUM: "脊索动物门",S_CLASS: "爬行纲",S_ORDER: "喙头目",},
{S_DOMAIN: "真核域",S_KINGDOM: "动物界",S_PHYLUM: "脊索动物门",S_CLASS: "爬行纲",S_ORDER: "鳄目",},
{S_DOMAIN: "真核域",S_KINGDOM: "动物界",S_PHYLUM: "脊索动物门",S_CLASS: "鸟纲",S_ORDER: "鸵鸟目",},
{S_DOMAIN: "真核域",S_KINGDOM: "动物界",S_PHYLUM: "脊索动物门",S_CLASS: "鸟纲",S_ORDER: "美洲鸵鸟目",},
{S_DOMAIN: "真核域",S_KINGDOM: "动物界",S_PHYLUM: "脊索动物门",S_CLASS: "鸟纲",S_ORDER: "无冀目",},
{S_DOMAIN: "真核域",S_KINGDOM: "动物界",S_PHYLUM: "脊索动物门",S_CLASS: "鸟纲",S_ORDER: "鹤鸵目",},
{S_DOMAIN: "真核域",S_KINGDOM: "动物界",S_PHYLUM: "脊索动物门",S_CLASS: "鸟纲",S_ORDER: "䳍形目",},
{S_DOMAIN: "真核域",S_KINGDOM: "动物界",S_PHYLUM: "脊索动物门",S_CLASS: "鸟纲",S_ORDER: "企鹅目",},
{S_DOMAIN: "真核域",S_KINGDOM: "动物界",S_PHYLUM: "脊索动物门",S_CLASS: "鸟纲",S_ORDER: "鸡形目",TITLE: "灰胸竹鸡",F_GROUP: "miao",F_NAME: "nihuahua01.jpg",},
{S_DOMAIN: "真核域",S_KINGDOM: "动物界",S_PHYLUM: "脊索动物门",S_CLASS: "鸟纲",S_ORDER: "雁形目",TITLE: "大天鹅",F_GROUP: "miao",F_NAME: "datiane01.jpg",},
{S_DOMAIN: "真核域",S_KINGDOM: "动物界",S_PHYLUM: "脊索动物门",S_CLASS: "鸟纲",S_ORDER: "夜鹰目",},
{S_DOMAIN: "真核域",S_KINGDOM: "动物界",S_PHYLUM: "脊索动物门",S_CLASS: "鸟纲",S_ORDER: "雨燕目",},
{S_DOMAIN: "真核域",S_KINGDOM: "动物界",S_PHYLUM: "脊索动物门",S_CLASS: "鸟纲",S_ORDER: "蕉鹃目",},
{S_DOMAIN: "真核域",S_KINGDOM: "动物界",S_PHYLUM: "脊索动物门",S_CLASS: "鸟纲",S_ORDER: "鸨形目",},
{S_DOMAIN: "真核域",S_KINGDOM: "动物界",S_PHYLUM: "脊索动物门",S_CLASS: "鸟纲",S_ORDER: "鹃形目",TITLE: "褐翅鸦鹃",F_GROUP: "miao",F_NAME: "hcyj01.jpg",},
{S_DOMAIN: "真核域",S_KINGDOM: "动物界",S_PHYLUM: "脊索动物门",S_CLASS: "鸟纲",S_ORDER: "鹳形目",TITLE: "白鹭",F_GROUP: "miao",F_NAME: "bailu01.jpg",},
{S_DOMAIN: "真核域",S_KINGDOM: "动物界",S_PHYLUM: "脊索动物门",S_CLASS: "鸟纲",S_ORDER: "鹤形目",TITLE: "白胸苦恶鸟",F_GROUP: "miao",F_NAME: "bxken01.jpg",},
{S_DOMAIN: "真核域",S_KINGDOM: "动物界",S_PHYLUM: "脊索动物门",S_CLASS: "鸟纲",S_ORDER: "鸻形目",TITLE: "剑鸻",F_GROUP: "miao",F_NAME: "jianx01.jpg",},
{S_DOMAIN: "真核域",S_KINGDOM: "动物界",S_PHYLUM: "脊索动物门",S_CLASS: "鸟纲",S_ORDER: "鸽形目",TITLE: "珠颈斑鸠",F_GROUP: "miao",F_NAME: "zjbj01.jpg",},
{S_DOMAIN: "真核域",S_KINGDOM: "动物界",S_PHYLUM: "脊索动物门",S_CLASS: "鸟纲",S_ORDER: "佛法僧目",TITLE: "蓝喉蜂虎",F_GROUP: "miao",F_NAME: "lhfh01.jpg",},
{S_DOMAIN: "真核域",S_KINGDOM: "动物界",S_PHYLUM: "脊索动物门",S_CLASS: "鸟纲",S_ORDER: "潜鸟目",},
{S_DOMAIN: "真核域",S_KINGDOM: "动物界",S_PHYLUM: "脊索动物门",S_CLASS: "鸟纲",S_ORDER: "鹰形目",TITLE: "林雕",F_GROUP: "miao",F_NAME: "lindiao01.jpg",},
{S_DOMAIN: "真核域",S_KINGDOM: "动物界",S_PHYLUM: "脊索动物门",S_CLASS: "鸟纲",S_ORDER: "鸥形目",TITLE: "红嘴鸥",F_GROUP: "miao",F_NAME: "hzou01.jpg",},
{S_DOMAIN: "真核域",S_KINGDOM: "动物界",S_PHYLUM: "脊索动物门",S_CLASS: "鸟纲",S_ORDER: "雀形目",TITLE: "红耳鹎",F_GROUP: "miao",F_NAME: "hongerbei01.jpg",},
{S_DOMAIN: "真核域",S_KINGDOM: "动物界",S_PHYLUM: "脊索动物门",S_CLASS: "鸟纲",S_ORDER: "鹈形目",TITLE: "鸬鹚",F_GROUP: "miao",F_NAME: "luci01.jpg",},
{S_DOMAIN: "真核域",S_KINGDOM: "动物界",S_PHYLUM: "脊索动物门",S_CLASS: "鸟纲",S_ORDER: "鴷形目",TITLE: "斑姬啄木鸟",F_GROUP: "miao",F_NAME: "bjzmn01.jpg",},
{S_DOMAIN: "真核域",S_KINGDOM: "动物界",S_PHYLUM: "脊索动物门",S_CLASS: "鸟纲",S_ORDER: "鸊鷉目",TITLE: "小鸊鷉",F_GROUP: "miao",F_NAME: "xpiti01.jpg",},
{S_DOMAIN: "真核域",S_KINGDOM: "动物界",S_PHYLUM: "脊索动物门",S_CLASS: "鸟纲",S_ORDER: "鹱形目",},
{S_DOMAIN: "真核域",S_KINGDOM: "动物界",S_PHYLUM: "脊索动物门",S_CLASS: "鸟纲",S_ORDER: "鹦形目",TITLE: "非洲灰鹦鹉",F_GROUP: "miao",F_NAME: "fzhyw01.jpg",},
{S_DOMAIN: "真核域",S_KINGDOM: "动物界",S_PHYLUM: "脊索动物门",S_CLASS: "鸟纲",S_ORDER: "鸮形目",},
{S_DOMAIN: "真核域",S_KINGDOM: "动物界",S_PHYLUM: "脊索动物门",S_CLASS: "鸟纲",S_ORDER: "咬鹃目",},
{S_DOMAIN: "真核域",S_KINGDOM: "动物界",S_PHYLUM: "脊索动物门",S_CLASS: "鸟纲",S_ORDER: "隼形目",},
{S_DOMAIN: "真核域",S_KINGDOM: "动物界",S_PHYLUM: "脊索动物门",S_CLASS: "鸟纲",S_ORDER: "几维目",},
{S_DOMAIN: "真核域",S_KINGDOM: "动物界",S_PHYLUM: "脊索动物门",S_CLASS: "鸟纲",S_ORDER: "叫鹤目",},
{S_DOMAIN: "真核域",S_KINGDOM: "动物界",S_PHYLUM: "脊索动物门",S_CLASS: "鸟纲",S_ORDER: "犀鸟目",},
{S_DOMAIN: "真核域",S_KINGDOM: "动物界",S_PHYLUM: "脊索动物门",S_CLASS: "鸟纲",S_ORDER: "鼠鸟目",},
{S_DOMAIN: "真核域",S_KINGDOM: "动物界",S_PHYLUM: "脊索动物门",S_CLASS: "鸟纲",S_ORDER: "鹃鴗目",},
{S_DOMAIN: "真核域",S_KINGDOM: "动物界",S_PHYLUM: "脊索动物门",S_CLASS: "鸟纲",S_ORDER: "麝雉目",},
{S_DOMAIN: "真核域",S_KINGDOM: "动物界",S_PHYLUM: "脊索动物门",S_CLASS: "鸟纲",S_ORDER: "鲣鸟目",},
{S_DOMAIN: "真核域",S_KINGDOM: "动物界",S_PHYLUM: "脊索动物门",S_CLASS: "鸟纲",S_ORDER: "鹲形目",},
{S_DOMAIN: "真核域",S_KINGDOM: "动物界",S_PHYLUM: "脊索动物门",S_CLASS: "鸟纲",S_ORDER: "日鳽目",},
{S_DOMAIN: "真核域",S_KINGDOM: "动物界",S_PHYLUM: "脊索动物门",S_CLASS: "鸟纲",S_ORDER: "红鹳目",},
{S_DOMAIN: "真核域",S_KINGDOM: "动物界",S_PHYLUM: "脊索动物门",S_CLASS: "鸟纲",S_ORDER: "拟鹑目",},
{S_DOMAIN: "真核域",S_KINGDOM: "动物界",S_PHYLUM: "脊索动物门",S_CLASS: "鸟纲",S_ORDER: "沙鸡目",},
{S_DOMAIN: "真核域",S_KINGDOM: "动物界",S_PHYLUM: "脊索动物门",S_CLASS: "哺乳纲",S_ORDER: "单孔目",},
{S_DOMAIN: "真核域",S_KINGDOM: "动物界",S_PHYLUM: "脊索动物门",S_CLASS: "哺乳纲",S_ORDER: "有袋目",},
{S_DOMAIN: "真核域",S_KINGDOM: "动物界",S_PHYLUM: "脊索动物门",S_CLASS: "哺乳纲",S_ORDER: "鼩形目",TITLE: "鼩鼱",F_GROUP: "miao",F_NAME: "qujing01.jpg",},
{S_DOMAIN: "真核域",S_KINGDOM: "动物界",S_PHYLUM: "脊索动物门",S_CLASS: "哺乳纲",S_ORDER: "猬形目",},
{S_DOMAIN: "真核域",S_KINGDOM: "动物界",S_PHYLUM: "脊索动物门",S_CLASS: "哺乳纲",S_ORDER: "非洲猬目",},
{S_DOMAIN: "真核域",S_KINGDOM: "动物界",S_PHYLUM: "脊索动物门",S_CLASS: "哺乳纲",S_ORDER: "跳鼩目",},
{S_DOMAIN: "真核域",S_KINGDOM: "动物界",S_PHYLUM: "脊索动物门",S_CLASS: "哺乳纲",S_ORDER: "攀兽目",},
{S_DOMAIN: "真核域",S_KINGDOM: "动物界",S_PHYLUM: "脊索动物门",S_CLASS: "哺乳纲",S_ORDER: "皮翼目",},
{S_DOMAIN: "真核域",S_KINGDOM: "动物界",S_PHYLUM: "脊索动物门",S_CLASS: "哺乳纲",S_ORDER: "翼手目",TITLE: "蝙蝠",F_GROUP: "miao",F_NAME: "bianfu01.jpg",},
{S_DOMAIN: "真核域",S_KINGDOM: "动物界",S_PHYLUM: "脊索动物门",S_CLASS: "哺乳纲",S_ORDER: "灵长目",TITLE: "川金丝猴",F_GROUP: "miao",F_NAME: "hou01.jpg",},
{S_DOMAIN: "真核域",S_KINGDOM: "动物界",S_PHYLUM: "脊索动物门",S_CLASS: "哺乳纲",S_ORDER: "贫齿目",},
{S_DOMAIN: "真核域",S_KINGDOM: "动物界",S_PHYLUM: "脊索动物门",S_CLASS: "哺乳纲",S_ORDER: "鳞甲目",},
{S_DOMAIN: "真核域",S_KINGDOM: "动物界",S_PHYLUM: "脊索动物门",S_CLASS: "哺乳纲",S_ORDER: "兔型目",TITLE: "兔",F_GROUP: "miao",F_NAME: "tuzi01.jpg",},
{S_DOMAIN: "真核域",S_KINGDOM: "动物界",S_PHYLUM: "脊索动物门",S_CLASS: "哺乳纲",S_ORDER: "啮齿目",TITLE: "赤腹松鼠",F_GROUP: "miao",F_NAME: "songshu.jpg",},
{S_DOMAIN: "真核域",S_KINGDOM: "动物界",S_PHYLUM: "脊索动物门",S_CLASS: "哺乳纲",S_ORDER: "食肉目",TITLE: "猫",F_GROUP: "miao",F_NAME: "miao05.jpg",},
{S_DOMAIN: "真核域",S_KINGDOM: "动物界",S_PHYLUM: "脊索动物门",S_CLASS: "哺乳纲",S_ORDER: "鲸目",},
{S_DOMAIN: "真核域",S_KINGDOM: "动物界",S_PHYLUM: "脊索动物门",S_CLASS: "哺乳纲",S_ORDER: "海牛目",},
{S_DOMAIN: "真核域",S_KINGDOM: "动物界",S_PHYLUM: "脊索动物门",S_CLASS: "哺乳纲",S_ORDER: "蹄兔目",},
{S_DOMAIN: "真核域",S_KINGDOM: "动物界",S_PHYLUM: "脊索动物门",S_CLASS: "哺乳纲",S_ORDER: "长鼻目",TITLE: "象",F_GROUP: "miao",F_NAME: "daxiang01.jpg",},
{S_DOMAIN: "真核域",S_KINGDOM: "动物界",S_PHYLUM: "脊索动物门",S_CLASS: "哺乳纲",S_ORDER: "管齿目",},
{S_DOMAIN: "真核域",S_KINGDOM: "动物界",S_PHYLUM: "脊索动物门",S_CLASS: "哺乳纲",S_ORDER: "奇蹄目",TITLE: "貘",F_GROUP: "miao",F_NAME: "mo01.jpg",},
{S_DOMAIN: "真核域",S_KINGDOM: "动物界",S_PHYLUM: "脊索动物门",S_CLASS: "哺乳纲",S_ORDER: "偶蹄目",TITLE: "牛",F_GROUP: "miao",F_NAME: "huangniu.jpg",},
]
