var myjson={
"RECORDS": [
{
"P_ID": "301",
"P_NAME": "人物龙凤图",
"P_AUTHOR": "佚名",
"P_DYNASTY": "战国",
"P_TYPE": "绢本 设色 人物",
"P_INFO": "http",
"P_PICS": "rwlft.jpg",
"P_POSTIL": "",
"P_WIDTH": "23.2",
"P_HEIGHT": "31.2",
"P_STAR": "5"
},
{
"P_ID": "332",
"P_NAME": "地主庄园图",
"P_AUTHOR": "佚名",
"P_DYNASTY": "东晋",
"P_TYPE": "纸本 人物",
"P_INFO": "http",
"P_PICS": "dzzyt.jpg",
"P_POSTIL": "最早的纸画",
"P_WIDTH": "105",
"P_HEIGHT": "46.2",
"P_STAR": "4"
},
{
"P_ID": "154",
"P_NAME": "中秋帖",
"P_AUTHOR": "王献之",
"P_DYNASTY": "东晋",
"P_TYPE": "书法 水墨 纸本",
"P_INFO": "http",
"P_PICS": "zqt.jpg",
"P_POSTIL": "",
"P_WIDTH": "0",
"P_HEIGHT": "0",
"P_STAR": "5"
},
{
"P_ID": "155",
"P_NAME": "伯远帖",
"P_AUTHOR": "王珣",
"P_DYNASTY": "东晋",
"P_TYPE": "书法 水墨 纸本",
"P_INFO": "http",
"P_PICS": "byt.jpg",
"P_POSTIL": "",
"P_WIDTH": "0",
"P_HEIGHT": "0",
"P_STAR": "5"
},
{
"P_ID": "152",
"P_NAME": "快雪时晴帖",
"P_AUTHOR": "王羲之",
"P_DYNASTY": "东晋",
"P_TYPE": "书法 水墨 纸本",
"P_INFO": "http",
"P_PICS": "kxsqt.jpg",
"P_POSTIL": "",
"P_WIDTH": "0",
"P_HEIGHT": "0",
"P_STAR": "5"
},
{
"P_ID": "158",
"P_NAME": "平安帖",
"P_AUTHOR": "王羲之",
"P_DYNASTY": "东晋",
"P_TYPE": "书法 水墨 纸本",
"P_INFO": "http",
"P_PICS": "pat.jpg",
"P_POSTIL": "",
"P_WIDTH": "0",
"P_HEIGHT": "0",
"P_STAR": "4"
},
{
"P_ID": "153",
"P_NAME": "游目帖",
"P_AUTHOR": "王羲之",
"P_DYNASTY": "东晋",
"P_TYPE": "书法 水墨 纸本",
"P_INFO": "http",
"P_PICS": "ymt.jpg",
"P_POSTIL": "",
"P_WIDTH": "0",
"P_HEIGHT": "0",
"P_STAR": "4"
},
{
"P_ID": "156",
"P_NAME": "远宦帖",
"P_AUTHOR": "王羲之",
"P_DYNASTY": "东晋",
"P_TYPE": "书法 水墨 纸本",
"P_INFO": "http",
"P_PICS": "yht.jpg",
"P_POSTIL": "",
"P_WIDTH": "0",
"P_HEIGHT": "0",
"P_STAR": "4"
},
{
"P_ID": "151",
"P_NAME": "兰亭集序",
"P_AUTHOR": "王羲之",
"P_DYNASTY": "东晋",
"P_TYPE": "书法 水墨 纸本",
"P_INFO": "http",
"P_PICS": "ltjx.jpg",
"P_POSTIL": "",
"P_WIDTH": "0",
"P_HEIGHT": "0",
"P_STAR": "5"
},
{
"P_ID": "157",
"P_NAME": "姨母帖",
"P_AUTHOR": "王羲之",
"P_DYNASTY": "东晋",
"P_TYPE": "书法 水墨 纸本",
"P_INFO": "http",
"P_PICS": "ymt.jpg",
"P_POSTIL": "",
"P_WIDTH": "0",
"P_HEIGHT": "0",
"P_STAR": "4"
},
{
"P_ID": "1",
"P_NAME": "洛神赋图",
"P_AUTHOR": "顾恺之",
"P_DYNASTY": "东晋",
"P_TYPE": "卷轴 设色 人物 山水",
"P_INFO": "http",
"P_PICS": "lsft.jpg",
"P_POSTIL": "冯夷鸣鼓，女娲清歌。",
"P_WIDTH": "572.8",
"P_HEIGHT": "27.1",
"P_STAR": "5"
},
{
"P_ID": "2",
"P_NAME": "女史箴图",
"P_AUTHOR": "顾恺之",
"P_DYNASTY": "东晋",
"P_TYPE": "卷轴 设色 人物",
"P_INFO": "http",
"P_PICS": "nszt.jpg",
"P_POSTIL": "茫茫造化，两仪既分； 散气流形，既陶既甄。",
"P_WIDTH": "348.2",
"P_HEIGHT": "24.8",
"P_STAR": "5"
},
{
"P_ID": "3",
"P_NAME": "列女图",
"P_AUTHOR": "顾恺之",
"P_DYNASTY": "东晋",
"P_TYPE": "卷轴 设色 人物",
"P_INFO": "http",
"P_PICS": "lnt.jpg",
"P_POSTIL": "楚武邓曼”、 “许穆夫人”、“曹僖氏妻”、“孙叔敖母”、“晋伯宗妻”、“灵公夫人”、“晋羊叔姬”",
"P_WIDTH": "417.8",
"P_HEIGHT": "25.8",
"P_STAR": "5"
},
{
"P_ID": "4",
"P_NAME": "竹林七贤与荣启期",
"P_AUTHOR": "佚名",
"P_DYNASTY": "南北朝",
"P_TYPE": "砖画 人物",
"P_INFO": "http",
"P_PICS": "zlqx.jpg",
"P_POSTIL": "",
"P_WIDTH": "0",
"P_HEIGHT": "0",
"P_STAR": "5"
},
{
"P_ID": "279",
"P_NAME": "九色鹿经图",
"P_AUTHOR": "佚名",
"P_DYNASTY": "南北朝",
"P_TYPE": "壁画 宗教 动物",
"P_INFO": "http",
"P_PICS": "jsljt.jpg",
"P_POSTIL": "",
"P_WIDTH": "0",
"P_HEIGHT": "0",
"P_STAR": "5"
},
{
"P_ID": "5",
"P_NAME": "五星二十八宿真形图",
"P_AUTHOR": "张僧繇",
"P_DYNASTY": "南北朝",
"P_TYPE": "卷轴 设色 人物",
"P_INFO": "http",
"P_PICS": "wxesb.jpg",
"P_POSTIL": "",
"P_WIDTH": "489.7",
"P_HEIGHT": "27.5",
"P_STAR": "5"
},
{
"P_ID": "284",
"P_NAME": "校书图卷",
"P_AUTHOR": "杨子华",
"P_DYNASTY": "南北朝",
"P_TYPE": "卷轴 绢本 设色 人物",
"P_INFO": "http",
"P_PICS": "jstj.jpg",
"P_POSTIL": "",
"P_WIDTH": "240",
"P_HEIGHT": "80",
"P_STAR": "4"
},
{
"P_ID": "312",
"P_NAME": "职贡图",
"P_AUTHOR": "萧绎",
"P_DYNASTY": "南北朝",
"P_TYPE": "卷轴 绢本 设色 人物",
"P_INFO": "http",
"P_PICS": "zgt.jpg",
"P_POSTIL": "",
"P_WIDTH": "200.7",
"P_HEIGHT": "26.7",
"P_STAR": "4"
},
{
"P_ID": "6",
"P_NAME": "游春图",
"P_AUTHOR": "展子虔",
"P_DYNASTY": "隋",
"P_TYPE": "立轴 绢本 青绿 山水",
"P_INFO": "http",
"P_PICS": "yct.jpg",
"P_POSTIL": "",
"P_WIDTH": "80.5",
"P_HEIGHT": "43",
"P_STAR": "5"
},
{
"P_ID": "314",
"P_NAME": "张议潮统军出行图",
"P_AUTHOR": "佚名",
"P_DYNASTY": "唐",
"P_TYPE": "壁画 人物",
"P_INFO": "http",
"P_PICS": "zyctjcxt.jpg",
"P_POSTIL": "",
"P_WIDTH": "830",
"P_HEIGHT": "130",
"P_STAR": "4"
},
{
"P_ID": "17",
"P_NAME": "观鸟捕蝉图",
"P_AUTHOR": "佚名",
"P_DYNASTY": "唐",
"P_TYPE": "壁画 人物",
"P_INFO": "http",
"P_PICS": "gnbct.jpg",
"P_POSTIL": "",
"P_WIDTH": "175",
"P_HEIGHT": "168",
"P_STAR": "5"
},
{
"P_ID": "313",
"P_NAME": "西方净土变",
"P_AUTHOR": "佚名",
"P_DYNASTY": "唐",
"P_TYPE": "壁画 人物 宗教",
"P_INFO": "http",
"P_PICS": "xfjtb.jpg",
"P_POSTIL": "",
"P_WIDTH": "0",
"P_HEIGHT": "0",
"P_STAR": "4"
},
{
"P_ID": "302",
"P_NAME": "维摩诘经变",
"P_AUTHOR": "佚名",
"P_DYNASTY": "唐",
"P_TYPE": "壁画 人物 宗教",
"P_INFO": "http",
"P_PICS": "wmjjb.jpg",
"P_POSTIL": "",
"P_WIDTH": "0",
"P_HEIGHT": "0",
"P_STAR": "4"
},
{
"P_ID": "21",
"P_NAME": "送子天王图",
"P_AUTHOR": "吴道子",
"P_DYNASTY": "唐",
"P_TYPE": "卷轴 纸本 水墨 人物",
"P_INFO": "http",
"P_PICS": "sztwt.jpg",
"P_POSTIL": "",
"P_WIDTH": "338.1",
"P_HEIGHT": "35.5",
"P_STAR": "5"
},
{
"P_ID": "13",
"P_NAME": "挥扇仕女图",
"P_AUTHOR": "周昉",
"P_DYNASTY": "唐",
"P_TYPE": "卷轴 绢本 设色 人物",
"P_INFO": "http",
"P_PICS": "hssnt.jpg",
"P_POSTIL": "",
"P_WIDTH": "204.8",
"P_HEIGHT": "33.7",
"P_STAR": "4"
},
{
"P_ID": "22",
"P_NAME": "内人双陆图",
"P_AUTHOR": "周昉",
"P_DYNASTY": "唐",
"P_TYPE": "绢本 设色 人物",
"P_INFO": "http",
"P_PICS": "nrslt.jpg",
"P_POSTIL": "",
"P_WIDTH": "64.4",
"P_HEIGHT": "30.7",
"P_STAR": "4"
},
{
"P_ID": "12",
"P_NAME": "簪花仕女图",
"P_AUTHOR": "周昉",
"P_DYNASTY": "唐",
"P_TYPE": "卷轴 绢本 设色 人物",
"P_INFO": "http",
"P_PICS": "zhsnt.jpg",
"P_POSTIL": "",
"P_WIDTH": "180",
"P_HEIGHT": "46",
"P_STAR": "5"
},
{
"P_ID": "355",
"P_NAME": "高逸图",
"P_AUTHOR": "孙位",
"P_DYNASTY": "唐",
"P_TYPE": "卷轴 绢本 设色 人物",
"P_INFO": "http",
"P_PICS": "gyt.jpg",
"P_POSTIL": "",
"P_WIDTH": "168.7",
"P_HEIGHT": "45.2",
"P_STAR": "4"
},
{
"P_ID": "10",
"P_NAME": "捣练图",
"P_AUTHOR": "张萱",
"P_DYNASTY": "唐",
"P_TYPE": "卷轴 绢本 设色 人物",
"P_INFO": "http",
"P_PICS": "dlt.jpg",
"P_POSTIL": "",
"P_WIDTH": "145.3",
"P_HEIGHT": "37",
"P_STAR": "5"
},
{
"P_ID": "11",
"P_NAME": "虢国夫人游春图",
"P_AUTHOR": "张萱",
"P_DYNASTY": "唐",
"P_TYPE": "卷轴 绢本 设色 人物",
"P_INFO": "http",
"P_PICS": "ggfr.jpg",
"P_POSTIL": "",
"P_WIDTH": "148",
"P_HEIGHT": "51.8",
"P_STAR": "5"
},
{
"P_ID": "182",
"P_NAME": "自叙帖",
"P_AUTHOR": "怀素",
"P_DYNASTY": "唐",
"P_TYPE": "书法 水墨 纸本",
"P_INFO": "http",
"P_PICS": "zxt.jpg",
"P_POSTIL": "",
"P_WIDTH": "0",
"P_HEIGHT": "0",
"P_STAR": "5"
},
{
"P_ID": "18",
"P_NAME": "明皇幸蜀图",
"P_AUTHOR": "李思训",
"P_DYNASTY": "唐",
"P_TYPE": "绢本 青绿 山水",
"P_INFO": "http",
"P_PICS": "mhxst.jpg",
"P_POSTIL": "",
"P_WIDTH": "81",
"P_HEIGHT": "55.9",
"P_STAR": "5"
},
{
"P_ID": "303",
"P_NAME": "江帆楼阁图",
"P_AUTHOR": "李思训",
"P_DYNASTY": "唐",
"P_TYPE": "立轴 绢本 青绿 山水",
"P_INFO": "http",
"P_PICS": "jflgt.jpg",
"P_POSTIL": "",
"P_WIDTH": "54.7",
"P_HEIGHT": "101.9",
"P_STAR": "4"
},
{
"P_ID": "19",
"P_NAME": "春山行旅图",
"P_AUTHOR": "李昭道",
"P_DYNASTY": "唐",
"P_TYPE": "绢本 设色 山水",
"P_INFO": "http",
"P_PICS": "csxlt.jpg",
"P_POSTIL": "",
"P_WIDTH": "55.3",
"P_HEIGHT": "95.5",
"P_STAR": "4"
},
{
"P_ID": "164",
"P_NAME": "上阳台帖",
"P_AUTHOR": "李白",
"P_DYNASTY": "唐",
"P_TYPE": "书法 水墨 纸本",
"P_INFO": "http",
"P_PICS": "sytt.jpg",
"P_POSTIL": "",
"P_WIDTH": "0",
"P_HEIGHT": "0",
"P_STAR": "5"
},
{
"P_ID": "166",
"P_NAME": "韭花帖",
"P_AUTHOR": "杨凝式",
"P_DYNASTY": "唐",
"P_TYPE": "书法 水墨 纸本",
"P_INFO": "http",
"P_PICS": "jht.jpg",
"P_POSTIL": "",
"P_WIDTH": "0",
"P_HEIGHT": "0",
"P_STAR": "5"
},
{
"P_ID": "162",
"P_NAME": "蒙诏帖",
"P_AUTHOR": "柳公权",
"P_DYNASTY": "唐",
"P_TYPE": "书法 水墨 纸本",
"P_INFO": "http",
"P_PICS": "mzt.jpg",
"P_POSTIL": "",
"P_WIDTH": "0",
"P_HEIGHT": "0",
"P_STAR": "5"
},
{
"P_ID": "160",
"P_NAME": "张翰帖",
"P_AUTHOR": "欧阳询",
"P_DYNASTY": "唐",
"P_TYPE": "书法 水墨 纸本",
"P_INFO": "http",
"P_PICS": "zht.jpg",
"P_POSTIL": "",
"P_WIDTH": "0",
"P_HEIGHT": "0",
"P_STAR": "5"
},
{
"P_ID": "159",
"P_NAME": "梦奠帖",
"P_AUTHOR": "欧阳询",
"P_DYNASTY": "唐",
"P_TYPE": "书法 水墨 纸本",
"P_INFO": "http",
"P_PICS": "mdt.jpg",
"P_POSTIL": "",
"P_WIDTH": "0",
"P_HEIGHT": "0",
"P_STAR": "5"
},
{
"P_ID": "367",
"P_NAME": "江皋会遇图",
"P_AUTHOR": "王维",
"P_DYNASTY": "唐",
"P_TYPE": "卷轴 绢本 设色 山水",
"P_INFO": "http",
"P_PICS": "jghyt.jpg",
"P_POSTIL": "",
"P_WIDTH": "0",
"P_HEIGHT": "0",
"P_STAR": "4"
},
{
"P_ID": "304",
"P_NAME": "辋川图",
"P_AUTHOR": "王维",
"P_DYNASTY": "唐",
"P_TYPE": "壁画 山水",
"P_INFO": "img",
"P_PICS": "wct.jpg",
"P_POSTIL": "",
"P_WIDTH": "0",
"P_HEIGHT": "0",
"P_STAR": "4"
},
{
"P_ID": "20",
"P_NAME": "伏生授经图",
"P_AUTHOR": "王维",
"P_DYNASTY": "唐",
"P_TYPE": "绢本 设色 人物",
"P_INFO": "http",
"P_PICS": "fssjt.jpg",
"P_POSTIL": "",
"P_WIDTH": "44.7",
"P_HEIGHT": "34",
"P_STAR": "5"
},
{
"P_ID": "163",
"P_NAME": "灵飞经",
"P_AUTHOR": "钟绍京",
"P_DYNASTY": "唐",
"P_TYPE": "书法 水墨 纸本",
"P_INFO": "http",
"P_PICS": "lfj.jpg",
"P_POSTIL": "",
"P_WIDTH": "0",
"P_HEIGHT": "0",
"P_STAR": "5"
},
{
"P_ID": "7",
"P_NAME": "历代帝王图",
"P_AUTHOR": "阎立本",
"P_DYNASTY": "唐",
"P_TYPE": "卷轴 绢本 设色 人物",
"P_INFO": "http",
"P_PICS": "lddwt.jpg",
"P_POSTIL": "",
"P_WIDTH": "531",
"P_HEIGHT": "51",
"P_STAR": "5"
},
{
"P_ID": "8",
"P_NAME": "步辇图",
"P_AUTHOR": "阎立本",
"P_DYNASTY": "唐",
"P_TYPE": "卷轴 绢本 设色 人物",
"P_INFO": "http",
"P_PICS": "bnt.jpg",
"P_POSTIL": "",
"P_WIDTH": "129.6",
"P_HEIGHT": "38.5",
"P_STAR": "5"
},
{
"P_ID": "9",
"P_NAME": "职贡图",
"P_AUTHOR": "阎立本",
"P_DYNASTY": "唐",
"P_TYPE": "卷轴 绢本 设色 人物",
"P_INFO": "http",
"P_PICS": "zgt.jpg",
"P_POSTIL": "",
"P_WIDTH": "121.5",
"P_HEIGHT": "61.5",
"P_STAR": "5"
},
{
"P_ID": "165",
"P_NAME": "文赋",
"P_AUTHOR": "陆柬之",
"P_DYNASTY": "唐",
"P_TYPE": "书法 水墨 纸本",
"P_INFO": "http",
"P_PICS": "ljz.jpg",
"P_POSTIL": "",
"P_WIDTH": "0",
"P_HEIGHT": "0",
"P_STAR": "4"
},
{
"P_ID": "15",
"P_NAME": "牧马图",
"P_AUTHOR": "韩幹",
"P_DYNASTY": "唐",
"P_TYPE": "绢本 设色 动物",
"P_INFO": "http",
"P_PICS": "mmt.jpg",
"P_POSTIL": "",
"P_WIDTH": "27.5",
"P_HEIGHT": "34.1",
"P_STAR": "4"
},
{
"P_ID": "14",
"P_NAME": "照夜白图",
"P_AUTHOR": "韩幹",
"P_DYNASTY": "唐",
"P_TYPE": "纸本 水墨 动物",
"P_INFO": "http",
"P_PICS": "zyb.jpg",
"P_POSTIL": "",
"P_WIDTH": "30.8",
"P_HEIGHT": "33.5",
"P_STAR": "5"
},
{
"P_ID": "38",
"P_NAME": "猿马图",
"P_AUTHOR": "韩幹",
"P_DYNASTY": "唐",
"P_TYPE": "立轴 纸本 设色 动物",
"P_INFO": "img",
"P_PICS": "ymt.jpg",
"P_POSTIL": "",
"P_WIDTH": "48.5",
"P_HEIGHT": "136.8",
"P_STAR": "4"
},
{
"P_ID": "16",
"P_NAME": "五牛图",
"P_AUTHOR": "韩滉",
"P_DYNASTY": "唐",
"P_TYPE": "卷轴 纸本 设色 动物",
"P_INFO": "http",
"P_PICS": "wnt.jpg",
"P_POSTIL": "",
"P_WIDTH": "139.8",
"P_HEIGHT": "20.8",
"P_STAR": "5"
},
{
"P_ID": "161",
"P_NAME": "祭侄文稿",
"P_AUTHOR": "颜真卿",
"P_DYNASTY": "唐",
"P_TYPE": "书法 水墨 纸本",
"P_INFO": "http",
"P_PICS": "jzwg.jpg",
"P_POSTIL": "",
"P_WIDTH": "0",
"P_HEIGHT": "0",
"P_STAR": "5"
},
{
"P_ID": "24",
"P_NAME": "关山行旅图",
"P_AUTHOR": "关仝",
"P_DYNASTY": "五代",
"P_TYPE": "立轴 绢本 水墨 山水",
"P_INFO": "http",
"P_PICS": "gsxlt.jpg",
"P_POSTIL": "",
"P_WIDTH": "56.8",
"P_HEIGHT": "144.4",
"P_STAR": "5"
},
{
"P_ID": "33",
"P_NAME": "闸口盘车图",
"P_AUTHOR": "卫贤",
"P_DYNASTY": "五代",
"P_TYPE": "绢本 设色 市井",
"P_INFO": "http",
"P_PICS": "zkpct.jpg",
"P_POSTIL": "",
"P_WIDTH": "119.2",
"P_HEIGHT": "53.3",
"P_STAR": "4"
},
{
"P_ID": "305",
"P_NAME": "重屏会棋图",
"P_AUTHOR": "周文矩",
"P_DYNASTY": "五代",
"P_TYPE": "绢本 设色 人物",
"P_INFO": "http",
"P_PICS": "cphqt.jpg",
"P_POSTIL": "",
"P_WIDTH": "70.5",
"P_HEIGHT": "40.2",
"P_STAR": "4"
},
{
"P_ID": "36",
"P_NAME": "文苑图",
"P_AUTHOR": "周文矩",
"P_DYNASTY": "五代",
"P_TYPE": "绢本 设色 人物",
"P_INFO": "http",
"P_PICS": "wyt.jpg",
"P_POSTIL": "",
"P_WIDTH": "58.5",
"P_HEIGHT": "37.4",
"P_STAR": "4"
},
{
"P_ID": "37",
"P_NAME": "宫中图",
"P_AUTHOR": "周文矩",
"P_DYNASTY": "五代",
"P_TYPE": "卷轴 绢本 设色 人物",
"P_INFO": "http",
"P_PICS": "gzt.jpg",
"P_POSTIL": "",
"P_WIDTH": "145.5",
"P_HEIGHT": "26",
"P_STAR": "4"
},
{
"P_ID": "35",
"P_NAME": "李苏别意图",
"P_AUTHOR": "周文矩",
"P_DYNASTY": "五代",
"P_TYPE": "绢本 设色 人物",
"P_INFO": "img",
"P_PICS": "lsbyt.jpg",
"P_POSTIL": "",
"P_WIDTH": "0",
"P_HEIGHT": "0",
"P_STAR": "4"
},
{
"P_ID": "278",
"P_NAME": "溪山兰若图",
"P_AUTHOR": "巨然",
"P_DYNASTY": "五代",
"P_TYPE": "立轴 绢本 水墨 山水",
"P_INFO": "http",
"P_PICS": "xslrt.jpg",
"P_POSTIL": "",
"P_WIDTH": "57.6",
"P_HEIGHT": "185.4",
"P_STAR": "4"
},
{
"P_ID": "26",
"P_NAME": "秋山问道图",
"P_AUTHOR": "巨然",
"P_DYNASTY": "五代",
"P_TYPE": "立轴 绢本 水墨 山水",
"P_INFO": "http",
"P_PICS": "qswdt.jpg",
"P_POSTIL": "",
"P_WIDTH": "77.2",
"P_HEIGHT": "165.2",
"P_STAR": "5"
},
{
"P_ID": "283",
"P_NAME": "东丹王出行图",
"P_AUTHOR": "李赞华",
"P_DYNASTY": "五代",
"P_TYPE": "卷轴 绢本 设色 人物",
"P_INFO": "http",
"P_PICS": "ddwcxt.jpg",
"P_POSTIL": "",
"P_WIDTH": "125.1",
"P_HEIGHT": "27.8",
"P_STAR": "4"
},
{
"P_ID": "292",
"P_NAME": "渔乐图",
"P_AUTHOR": "荆浩",
"P_DYNASTY": "五代",
"P_TYPE": "卷轴 绢本 水墨 山水 人物",
"P_INFO": "http",
"P_PICS": "ylt.jpg",
"P_POSTIL": "",
"P_WIDTH": "200",
"P_HEIGHT": "30",
"P_STAR": "4"
},
{
"P_ID": "23",
"P_NAME": "匡庐图",
"P_AUTHOR": "荆浩",
"P_DYNASTY": "五代",
"P_TYPE": "立轴 绢本 水墨 山水",
"P_INFO": "http",
"P_PICS": "klt.jpg",
"P_POSTIL": "",
"P_WIDTH": "106.8",
"P_HEIGHT": "185.8",
"P_STAR": "5"
},
{
"P_ID": "306",
"P_NAME": "夏山图",
"P_AUTHOR": "董源",
"P_DYNASTY": "五代",
"P_TYPE": "卷轴 绢本 水墨 设色 山水",
"P_INFO": "http",
"P_PICS": "xst.jpg",
"P_POSTIL": "",
"P_WIDTH": "313.2",
"P_HEIGHT": "49.4",
"P_STAR": "4"
},
{
"P_ID": "25",
"P_NAME": "潇湘图",
"P_AUTHOR": "董源",
"P_DYNASTY": "五代",
"P_TYPE": "卷轴 绢本 水墨 山水",
"P_INFO": "http",
"P_PICS": "xxt.jpg",
"P_POSTIL": "",
"P_WIDTH": "141.4",
"P_HEIGHT": "50",
"P_STAR": "5"
},
{
"P_ID": "362",
"P_NAME": "溪岸图",
"P_AUTHOR": "董源",
"P_DYNASTY": "五代",
"P_TYPE": "立轴 绢本 设色 山水",
"P_INFO": "http",
"P_PICS": "xat.jpg",
"P_POSTIL": "",
"P_WIDTH": "110",
"P_HEIGHT": "221.5",
"P_STAR": "4"
},
{
"P_ID": "282",
"P_NAME": "夏景山口待渡图",
"P_AUTHOR": "董源",
"P_DYNASTY": "五代",
"P_TYPE": "卷轴 绢本 设色 山水",
"P_INFO": "http",
"P_PICS": "xjskddt.jpg",
"P_POSTIL": "",
"P_WIDTH": "320",
"P_HEIGHT": "50",
"P_STAR": "5"
},
{
"P_ID": "363",
"P_NAME": "龙宿郊民图",
"P_AUTHOR": "董源",
"P_DYNASTY": "五代",
"P_TYPE": "立轴 绢本 设色 山水",
"P_INFO": "http",
"P_PICS": "lsjmt.jpg",
"P_POSTIL": "",
"P_WIDTH": "160",
"P_HEIGHT": "156",
"P_STAR": "4"
},
{
"P_ID": "29",
"P_NAME": "十六罗汉图",
"P_AUTHOR": "贯休",
"P_DYNASTY": "五代",
"P_TYPE": "人物",
"P_INFO": "http",
"P_PICS": "sllht.jpg",
"P_POSTIL": "",
"P_WIDTH": "45.2",
"P_HEIGHT": "92.2",
"P_STAR": "4"
},
{
"P_ID": "34",
"P_NAME": "八达春游图",
"P_AUTHOR": "赵嵒",
"P_DYNASTY": "五代",
"P_TYPE": "绢本 设色 人物",
"P_INFO": "http",
"P_PICS": "bdyct.jpg",
"P_POSTIL": "",
"P_WIDTH": "102",
"P_HEIGHT": "161.9",
"P_STAR": "4"
},
{
"P_ID": "28",
"P_NAME": "江行初雪图",
"P_AUTHOR": "赵幹",
"P_DYNASTY": "五代",
"P_TYPE": "卷轴 绢本 水墨 设色 人物",
"P_INFO": "http",
"P_PICS": "jxcxt.jpg",
"P_POSTIL": "",
"P_WIDTH": "376.5",
"P_HEIGHT": "25.9",
"P_STAR": "5"
},
{
"P_ID": "27",
"P_NAME": "韩熙载夜宴图",
"P_AUTHOR": "顾闳中",
"P_DYNASTY": "五代",
"P_TYPE": "卷轴 绢本 设色 人物",
"P_INFO": "http",
"P_PICS": "hzxyyt.jpg",
"P_POSTIL": "",
"P_WIDTH": "335.5",
"P_HEIGHT": "28.7",
"P_STAR": "5"
},
{
"P_ID": "31",
"P_NAME": "山鹧棘雀图",
"P_AUTHOR": "黄居寀",
"P_DYNASTY": "五代",
"P_TYPE": "立轴 绢本 设色 动物",
"P_INFO": "http",
"P_PICS": "szjqt.jpg",
"P_POSTIL": "",
"P_WIDTH": "53.6",
"P_HEIGHT": "97",
"P_STAR": "4"
},
{
"P_ID": "30",
"P_NAME": "写生珍禽图",
"P_AUTHOR": "黄筌",
"P_DYNASTY": "五代",
"P_TYPE": "绢本 设色 动物",
"P_INFO": "http",
"P_PICS": "xszqt.jpg",
"P_POSTIL": "",
"P_WIDTH": "70",
"P_HEIGHT": "41.5",
"P_STAR": "5"
},
{
"P_ID": "32",
"P_NAME": "丹枫呦鹿图",
"P_AUTHOR": "佚名",
"P_DYNASTY": "辽",
"P_TYPE": "立轴 绢本 重彩 动物",
"P_INFO": "http",
"P_PICS": "dfylt.jpg",
"P_POSTIL": "",
"P_WIDTH": "64.6",
"P_HEIGHT": "118.5",
"P_STAR": "5"
},
{
"P_ID": "356",
"P_NAME": "游骑图",
"P_AUTHOR": "佚名",
"P_DYNASTY": "北宋",
"P_TYPE": "卷轴 绢本 设色 人物 动物",
"P_INFO": "http",
"P_PICS": "yjt.jpg",
"P_POSTIL": "",
"P_WIDTH": "94.8",
"P_HEIGHT": "22.7",
"P_STAR": "4"
},
{
"P_ID": "175",
"P_NAME": "神采帖",
"P_AUTHOR": "司马光",
"P_DYNASTY": "北宋",
"P_TYPE": "书法 水墨 纸本",
"P_INFO": "http",
"P_PICS": "sct.jpg",
"P_POSTIL": "",
"P_WIDTH": "0",
"P_HEIGHT": "0",
"P_STAR": "4"
},
{
"P_ID": "39",
"P_NAME": "双喜图",
"P_AUTHOR": "崔白",
"P_DYNASTY": "北宋",
"P_TYPE": "立轴 绢本 设色 动物",
"P_INFO": "http",
"P_PICS": "sxt.jpg",
"P_POSTIL": "",
"P_WIDTH": "103.4",
"P_HEIGHT": "193.7",
"P_STAR": "5"
},
{
"P_ID": "290",
"P_NAME": "寒雀图",
"P_AUTHOR": "崔白",
"P_DYNASTY": "北宋",
"P_TYPE": "卷轴 绢本 设色 动物",
"P_INFO": "http",
"P_PICS": "hqt.jpg",
"P_POSTIL": "",
"P_WIDTH": "101",
"P_HEIGHT": "25.5",
"P_STAR": "4"
},
{
"P_ID": "65",
"P_NAME": "清明上河图",
"P_AUTHOR": "张择端",
"P_DYNASTY": "北宋",
"P_TYPE": "卷轴 绢本 设色 市井",
"P_INFO": "http",
"P_PICS": "qmsht.jpg",
"P_POSTIL": "",
"P_WIDTH": "528.7",
"P_HEIGHT": "24.8",
"P_STAR": "5"
},
{
"P_ID": "360",
"P_NAME": "溪山春晓图",
"P_AUTHOR": "惠崇",
"P_DYNASTY": "北宋",
"P_TYPE": "卷轴 绢本 设色 山水",
"P_INFO": "http",
"P_PICS": "xscxt.jpg",
"P_POSTIL": "",
"P_WIDTH": "185",
"P_HEIGHT": "24.5",
"P_STAR": "4"
},
{
"P_ID": "71",
"P_NAME": "墨竹图",
"P_AUTHOR": "文同",
"P_DYNASTY": "北宋",
"P_TYPE": "立轴 绢本 水墨",
"P_INFO": "http",
"P_PICS": "mzt.jpg",
"P_POSTIL": "",
"P_WIDTH": "105.4",
"P_HEIGHT": "131.6",
"P_STAR": "4"
},
{
"P_ID": "174",
"P_NAME": "局事帖",
"P_AUTHOR": "曾巩",
"P_DYNASTY": "北宋",
"P_TYPE": "书法 水墨 纸本",
"P_INFO": "http",
"P_PICS": "jst.jpg",
"P_POSTIL": "",
"P_WIDTH": "0",
"P_HEIGHT": "0",
"P_STAR": "4"
},
{
"P_ID": "308",
"P_NAME": "五马图",
"P_AUTHOR": "李公麟",
"P_DYNASTY": "北宋",
"P_TYPE": "卷轴 纸本 水墨 动物",
"P_INFO": "http",
"P_PICS": "wmt.jpg",
"P_POSTIL": "",
"P_WIDTH": "225",
"P_HEIGHT": "29.3",
"P_STAR": "4"
},
{
"P_ID": "294",
"P_NAME": "晋文公复国图",
"P_AUTHOR": "李唐",
"P_DYNASTY": "北宋",
"P_TYPE": "卷轴 绢本 水墨 人物",
"P_INFO": "http",
"P_PICS": "jggfgt.jpg",
"P_POSTIL": "",
"P_WIDTH": "713",
"P_HEIGHT": "24.5",
"P_STAR": "5"
},
{
"P_ID": "297",
"P_NAME": "濠梁秋水图",
"P_AUTHOR": "李唐",
"P_DYNASTY": "北宋",
"P_TYPE": "卷轴 绢本 设色 山水",
"P_INFO": "http",
"P_PICS": "hlqst.jpg",
"P_POSTIL": "",
"P_WIDTH": "104.7",
"P_HEIGHT": "22.7",
"P_STAR": "4"
},
{
"P_ID": "57",
"P_NAME": "万壑松风图",
"P_AUTHOR": "李唐",
"P_DYNASTY": "北宋",
"P_TYPE": "立轴 绢本 设色 山水",
"P_INFO": "http",
"P_PICS": "whsft.jpg",
"P_POSTIL": "",
"P_WIDTH": "139.8",
"P_HEIGHT": "188.7",
"P_STAR": "5"
},
{
"P_ID": "60",
"P_NAME": "灸艾图",
"P_AUTHOR": "李唐",
"P_DYNASTY": "北宋",
"P_TYPE": "立轴 绢本 设色 人物",
"P_INFO": "http",
"P_PICS": "jat.jpg",
"P_POSTIL": "",
"P_WIDTH": "58.7",
"P_HEIGHT": "68.8",
"P_STAR": "4"
},
{
"P_ID": "339",
"P_NAME": "松湖钓隐图",
"P_AUTHOR": "李唐",
"P_DYNASTY": "北宋",
"P_TYPE": "团扇 绢本 设色 山水",
"P_INFO": "http",
"P_PICS": "shydt.jpg",
"P_POSTIL": "",
"P_WIDTH": "67.8",
"P_HEIGHT": "46",
"P_STAR": "4"
},
{
"P_ID": "345",
"P_NAME": "牧牛图",
"P_AUTHOR": "李唐",
"P_DYNASTY": "北宋",
"P_TYPE": "团扇 绢本 设色",
"P_INFO": "img",
"P_PICS": "mnt.jpg",
"P_POSTIL": "",
"P_WIDTH": "61",
"P_HEIGHT": "63",
"P_STAR": "4"
},
{
"P_ID": "58",
"P_NAME": "采薇图",
"P_AUTHOR": "李唐",
"P_DYNASTY": "北宋",
"P_TYPE": "卷轴 绢本 水墨 人物",
"P_INFO": "http",
"P_PICS": "cwt.jpg",
"P_POSTIL": "",
"P_WIDTH": "90.5",
"P_HEIGHT": "27.2",
"P_STAR": "5"
},
{
"P_ID": "176",
"P_NAME": "土母帖",
"P_AUTHOR": "李建中",
"P_DYNASTY": "北宋",
"P_TYPE": "书法 水墨 纸本",
"P_INFO": "http",
"P_PICS": "tmt.jpg",
"P_POSTIL": "",
"P_WIDTH": "0",
"P_HEIGHT": "0",
"P_STAR": "5"
},
{
"P_ID": "47",
"P_NAME": "寒林平野图",
"P_AUTHOR": "李成",
"P_DYNASTY": "北宋",
"P_TYPE": "立轴 绢本 水墨 山水",
"P_INFO": "http",
"P_PICS": "hlpyt.jpg",
"P_POSTIL": "",
"P_WIDTH": "70.2",
"P_HEIGHT": "120",
"P_STAR": "5"
},
{
"P_ID": "307",
"P_NAME": "读碑窠石图",
"P_AUTHOR": "李成",
"P_DYNASTY": "北宋",
"P_TYPE": "立轴 绢本 水墨 山水",
"P_INFO": "http",
"P_PICS": "dbkst.jpg",
"P_POSTIL": "",
"P_WIDTH": "104.9",
"P_HEIGHT": "126.3",
"P_STAR": "4"
},
{
"P_ID": "293",
"P_NAME": "芦汀密雪图",
"P_AUTHOR": "梁师闵",
"P_DYNASTY": "北宋",
"P_TYPE": "卷轴 绢本 设色 山水",
"P_INFO": "http",
"P_PICS": "ltmxt.jpg",
"P_POSTIL": "",
"P_WIDTH": "145.6",
"P_HEIGHT": "26.5",
"P_STAR": "4"
},
{
"P_ID": "173",
"P_NAME": "灼艾帖",
"P_AUTHOR": "欧阳修",
"P_DYNASTY": "北宋",
"P_TYPE": "书法 水墨 纸本",
"P_INFO": "http",
"P_PICS": "zat.jpg",
"P_POSTIL": "",
"P_WIDTH": "0",
"P_HEIGHT": "0",
"P_STAR": "4"
},
{
"P_ID": "53",
"P_NAME": "溪山楼观图",
"P_AUTHOR": "燕文贵",
"P_DYNASTY": "北宋",
"P_TYPE": "立轴 绢本 水墨 山水",
"P_INFO": "http",
"P_PICS": "xslgt.jpg",
"P_POSTIL": "",
"P_WIDTH": "47.4",
"P_HEIGHT": "103.9",
"P_STAR": "4"
},
{
"P_ID": "83",
"P_NAME": "子母鸡图",
"P_AUTHOR": "王凝",
"P_DYNASTY": "北宋",
"P_TYPE": "册页 纸本 设色 花鸟",
"P_INFO": "http",
"P_PICS": "zmjt.jpg",
"P_POSTIL": "",
"P_WIDTH": "24.6",
"P_HEIGHT": "23.7",
"P_STAR": "4"
},
{
"P_ID": "299",
"P_NAME": "纺车图卷",
"P_AUTHOR": "王居正",
"P_DYNASTY": "北宋",
"P_TYPE": "卷轴 绢本 设色 人物",
"P_INFO": "http",
"P_PICS": "fctj.jpg",
"P_POSTIL": "",
"P_WIDTH": "69.2",
"P_HEIGHT": "26.2",
"P_STAR": "4"
},
{
"P_ID": "68",
"P_NAME": "千里江山图",
"P_AUTHOR": "王希孟",
"P_DYNASTY": "北宋",
"P_TYPE": "卷轴 绢本 青绿 山水",
"P_INFO": "http",
"P_PICS": "qljst.jpg",
"P_POSTIL": "",
"P_WIDTH": "1191.5",
"P_HEIGHT": "51.5",
"P_STAR": "5"
},
{
"P_ID": "341",
"P_NAME": "玉楼春思图",
"P_AUTHOR": "王诜",
"P_DYNASTY": "北宋",
"P_TYPE": "团扇 绢本 设色 山水",
"P_INFO": "img",
"P_PICS": "ylsct.jpg",
"P_POSTIL": "",
"P_WIDTH": "25",
"P_HEIGHT": "24",
"P_STAR": "4"
},
{
"P_ID": "55",
"P_NAME": "渔村小雪图",
"P_AUTHOR": "王诜",
"P_DYNASTY": "北宋",
"P_TYPE": "立轴 绢本 设色 山水",
"P_INFO": "http",
"P_PICS": "ycxxt.jpg",
"P_POSTIL": "",
"P_WIDTH": "219.7",
"P_HEIGHT": "44.4",
"P_STAR": "4"
},
{
"P_ID": "309",
"P_NAME": "潇湘奇观图",
"P_AUTHOR": "米友仁",
"P_DYNASTY": "北宋",
"P_TYPE": "卷轴 茧纸本 水墨 山水",
"P_INFO": "http",
"P_PICS": "xxqgt.jpg",
"P_POSTIL": "",
"P_WIDTH": "289.5",
"P_HEIGHT": "19.8",
"P_STAR": "4"
},
{
"P_ID": "72",
"P_NAME": "云山图",
"P_AUTHOR": "米友仁",
"P_DYNASTY": "北宋",
"P_TYPE": "卷轴 绢本 设色 山水",
"P_INFO": "http",
"P_PICS": "yst.jpg",
"P_POSTIL": "",
"P_WIDTH": "194.3",
"P_HEIGHT": "43.4",
"P_STAR": "4"
},
{
"P_ID": "167",
"P_NAME": "蜀素帖",
"P_AUTHOR": "米芾",
"P_DYNASTY": "北宋",
"P_TYPE": "书法 水墨 绢本",
"P_INFO": "http",
"P_PICS": "sst.jpg",
"P_POSTIL": "",
"P_WIDTH": "0",
"P_HEIGHT": "0",
"P_STAR": "5"
},
{
"P_ID": "168",
"P_NAME": "元日帖",
"P_AUTHOR": "米芾",
"P_DYNASTY": "北宋",
"P_TYPE": "书法 水墨 纸本",
"P_INFO": "http",
"P_PICS": "yrt.jpg",
"P_POSTIL": "",
"P_WIDTH": "0",
"P_HEIGHT": "0",
"P_STAR": "4"
},
{
"P_ID": "45",
"P_NAME": "货郎图",
"P_AUTHOR": "苏汉臣",
"P_DYNASTY": "北宋",
"P_TYPE": "绢本 设色 人物",
"P_INFO": "http",
"P_PICS": "shchlt.jpg",
"P_POSTIL": "",
"P_WIDTH": "97",
"P_HEIGHT": "159.2",
"P_STAR": "4"
},
{
"P_ID": "66",
"P_NAME": "秋庭戏婴图",
"P_AUTHOR": "苏汉臣",
"P_DYNASTY": "北宋",
"P_TYPE": "立轴 绢本 设色 人物",
"P_INFO": "http",
"P_PICS": "qtxyt.jpg",
"P_POSTIL": "",
"P_WIDTH": "108.7",
"P_HEIGHT": "197.5",
"P_STAR": "4"
},
{
"P_ID": "172",
"P_NAME": "黄州寒食帖",
"P_AUTHOR": "苏轼",
"P_DYNASTY": "北宋",
"P_TYPE": "书法 水墨 纸本",
"P_INFO": "http",
"P_PICS": "hzhst.jpg",
"P_POSTIL": "",
"P_WIDTH": "119.5",
"P_HEIGHT": "34",
"P_STAR": "5"
},
{
"P_ID": "74",
"P_NAME": "竹石图",
"P_AUTHOR": "苏轼",
"P_DYNASTY": "北宋",
"P_TYPE": "卷轴 绢本 水墨",
"P_INFO": "http",
"P_PICS": "sszst.jpg",
"P_POSTIL": "",
"P_WIDTH": "105.6",
"P_HEIGHT": "28",
"P_STAR": "4"
},
{
"P_ID": "75",
"P_NAME": "枯木怪石图",
"P_AUTHOR": "苏轼",
"P_DYNASTY": "北宋",
"P_TYPE": "卷轴 纸本 水墨",
"P_INFO": "http",
"P_PICS": "gmgst.jpg",
"P_POSTIL": "",
"P_WIDTH": "50.5",
"P_HEIGHT": "26.3",
"P_STAR": "4"
},
{
"P_ID": "171",
"P_NAME": "二札帖",
"P_AUTHOR": "范仲淹",
"P_DYNASTY": "北宋",
"P_TYPE": "书法 水墨 纸本",
"P_INFO": "http",
"P_PICS": "ezt.jpg",
"P_POSTIL": "",
"P_WIDTH": "0",
"P_HEIGHT": "0",
"P_STAR": "4"
},
{
"P_ID": "300",
"P_NAME": "烟岚秋晓图",
"P_AUTHOR": "范宽",
"P_DYNASTY": "北宋",
"P_TYPE": "卷轴 绢本 设色 山水",
"P_INFO": "http",
"P_PICS": "ylqxt.jpg",
"P_POSTIL": "",
"P_WIDTH": "603.3",
"P_HEIGHT": "40",
"P_STAR": "4"
},
{
"P_ID": "48",
"P_NAME": "溪山行旅图",
"P_AUTHOR": "范宽",
"P_DYNASTY": "北宋",
"P_TYPE": "立轴 绢本 水墨 山水",
"P_INFO": "http",
"P_PICS": "xsxlt.jpg",
"P_POSTIL": "",
"P_WIDTH": "103.3",
"P_HEIGHT": "206.3",
"P_STAR": "5"
},
{
"P_ID": "49",
"P_NAME": "雪景寒林图",
"P_AUTHOR": "范宽",
"P_DYNASTY": "北宋",
"P_TYPE": "立轴 绢本 水墨 山水",
"P_INFO": "http",
"P_PICS": "xjhlt.jpg",
"P_POSTIL": "",
"P_WIDTH": "160.3",
"P_HEIGHT": "193.5",
"P_STAR": "4"
},
{
"P_ID": "169",
"P_NAME": "澄心堂帖",
"P_AUTHOR": "蔡襄",
"P_DYNASTY": "北宋",
"P_TYPE": "书法 水墨 纸本",
"P_INFO": "http",
"P_PICS": "cxtt.jpg",
"P_POSTIL": "",
"P_WIDTH": "0",
"P_HEIGHT": "0",
"P_STAR": "4"
},
{
"P_ID": "56",
"P_NAME": "渔父图",
"P_AUTHOR": "许道宁",
"P_DYNASTY": "北宋",
"P_TYPE": "卷轴 绢本 水墨 山水",
"P_INFO": "http",
"P_PICS": "xdnyft.jpg",
"P_POSTIL": "",
"P_WIDTH": "209.6",
"P_HEIGHT": "48.9",
"P_STAR": "4"
},
{
"P_ID": "88",
"P_NAME": "湖庄清夏图",
"P_AUTHOR": "赵令穰",
"P_DYNASTY": "北宋",
"P_TYPE": "卷轴 绢本 设色 山水",
"P_INFO": "http",
"P_PICS": "hzqxt.jpg",
"P_POSTIL": "",
"P_WIDTH": "161.3",
"P_HEIGHT": "19.1",
"P_STAR": "4"
},
{
"P_ID": "50",
"P_NAME": "腊梅山禽图",
"P_AUTHOR": "赵佶",
"P_DYNASTY": "北宋",
"P_TYPE": "绢本 设色 花鸟",
"P_INFO": "http",
"P_PICS": "lmsqt.jpg",
"P_POSTIL": "",
"P_WIDTH": "52.8",
"P_HEIGHT": "82.8",
"P_STAR": "4"
},
{
"P_ID": "51",
"P_NAME": "芙蓉锦鸡图",
"P_AUTHOR": "赵佶",
"P_DYNASTY": "北宋",
"P_TYPE": "绢本 设色 花鸟",
"P_INFO": "http",
"P_PICS": "frjjt.jpg",
"P_POSTIL": "",
"P_WIDTH": "53.6",
"P_HEIGHT": "81.5",
"P_STAR": "4"
},
{
"P_ID": "52",
"P_NAME": "瑞鹤图",
"P_AUTHOR": "赵佶",
"P_DYNASTY": "北宋",
"P_TYPE": "绢本 设色 花鸟",
"P_INFO": "http",
"P_PICS": "rht.jpg",
"P_POSTIL": "",
"P_WIDTH": "138.2",
"P_HEIGHT": "51",
"P_STAR": "5"
},
{
"P_ID": "183",
"P_NAME": "草书千字文",
"P_AUTHOR": "赵佶",
"P_DYNASTY": "北宋",
"P_TYPE": "书法 水墨 纸本",
"P_INFO": "http",
"P_PICS": "zcqzw.jpg",
"P_POSTIL": "",
"P_WIDTH": "0",
"P_HEIGHT": "0",
"P_STAR": "5"
},
{
"P_ID": "82",
"P_NAME": "写生蛱蝶图",
"P_AUTHOR": "赵昌",
"P_DYNASTY": "北宋",
"P_TYPE": "立轴 绢本 设色 花鸟",
"P_INFO": "http",
"P_PICS": "xsjdt.jpg",
"P_POSTIL": "",
"P_WIDTH": "91",
"P_HEIGHT": "27.7",
"P_STAR": "4"
},
{
"P_ID": "81",
"P_NAME": "岁朝图",
"P_AUTHOR": "赵昌",
"P_DYNASTY": "北宋",
"P_TYPE": "立轴 绢本 设色 花鸟",
"P_INFO": "http",
"P_PICS": "sct.jpg",
"P_POSTIL": "",
"P_WIDTH": "51.2",
"P_HEIGHT": "103.8",
"P_STAR": "4"
},
{
"P_ID": "54",
"P_NAME": "早春图",
"P_AUTHOR": "郭熙",
"P_DYNASTY": "北宋",
"P_TYPE": "立轴 绢本 设色 山水",
"P_INFO": "http",
"P_PICS": "zct.jpg",
"P_POSTIL": "",
"P_WIDTH": "108.1",
"P_HEIGHT": "158.3",
"P_STAR": "5"
},
{
"P_ID": "357",
"P_NAME": "树色平远图",
"P_AUTHOR": "郭熙",
"P_DYNASTY": "北宋",
"P_TYPE": "卷轴 绢本 水墨 山水",
"P_INFO": "http",
"P_PICS": "sspyt.jpg",
"P_POSTIL": "",
"P_WIDTH": "104.8",
"P_HEIGHT": "32.4",
"P_STAR": "4"
},
{
"P_ID": "358",
"P_NAME": "梨花诗",
"P_AUTHOR": "黄庭坚",
"P_DYNASTY": "北宋",
"P_TYPE": "卷轴 书法 水墨 纸本",
"P_INFO": "http",
"P_PICS": "lhs.jpg",
"P_POSTIL": "",
"P_WIDTH": "272",
"P_HEIGHT": "29",
"P_STAR": "4"
},
{
"P_ID": "170",
"P_NAME": "松风阁",
"P_AUTHOR": "黄庭坚",
"P_DYNASTY": "北宋",
"P_TYPE": "卷轴 书法 水墨 纸本",
"P_INFO": "http",
"P_PICS": "sfg.jpg",
"P_POSTIL": "",
"P_WIDTH": "219.2",
"P_HEIGHT": "32.8",
"P_STAR": "5"
},
{
"P_ID": "359",
"P_NAME": "刘明仲墨竹赋",
"P_AUTHOR": "黄庭坚",
"P_DYNASTY": "北宋",
"P_TYPE": "卷轴 书法 水墨 纸本",
"P_INFO": "http",
"P_PICS": "lmzmzf.jpg",
"P_POSTIL": "",
"P_WIDTH": "773",
"P_HEIGHT": "26",
"P_STAR": "4"
},
{
"P_ID": "343",
"P_NAME": "青枫巨蝶图",
"P_AUTHOR": "佚名",
"P_DYNASTY": "南宋",
"P_TYPE": "团扇 绢本 设色 花鸟",
"P_INFO": "img",
"P_PICS": "qfjdt.jpg",
"P_POSTIL": "",
"P_WIDTH": "24.2",
"P_HEIGHT": "23",
"P_STAR": "4"
},
{
"P_ID": "346",
"P_NAME": "秋树鸜鹆图",
"P_AUTHOR": "佚名",
"P_DYNASTY": "南宋",
"P_TYPE": "团扇 绢本 设色 花鸟",
"P_INFO": "img",
"P_PICS": "qsqyt.jpg",
"P_POSTIL": "",
"P_WIDTH": "26.5",
"P_HEIGHT": "25",
"P_STAR": "4"
},
{
"P_ID": "280",
"P_NAME": "胡笳十八拍图卷",
"P_AUTHOR": "佚名",
"P_DYNASTY": "南宋",
"P_TYPE": "卷轴 绢本 设色 人物",
"P_INFO": "http",
"P_PICS": "hjsbptj.jpg",
"P_POSTIL": "",
"P_WIDTH": "1232",
"P_HEIGHT": "31.3",
"P_STAR": "4"
},
{
"P_ID": "347",
"P_NAME": "猿猴摘果图",
"P_AUTHOR": "佚名",
"P_DYNASTY": "南宋",
"P_TYPE": "团扇 绢本 设色",
"P_INFO": "img",
"P_PICS": "yhzgt.jpg",
"P_POSTIL": "",
"P_WIDTH": "25.6",
"P_HEIGHT": "25",
"P_STAR": "4"
},
{
"P_ID": "353",
"P_NAME": "猿猴献果图",
"P_AUTHOR": "刘松年",
"P_DYNASTY": "南宋",
"P_TYPE": "立轴 纸本 设色 人物 动物",
"P_INFO": "http",
"P_PICS": "yhxgt.jpg",
"P_POSTIL": "",
"P_WIDTH": "55.8",
"P_HEIGHT": "117",
"P_STAR": "4"
},
{
"P_ID": "348",
"P_NAME": "松溪濯足图",
"P_AUTHOR": "刘松年",
"P_DYNASTY": "南宋",
"P_TYPE": "团扇 绢本 设色 山水",
"P_INFO": "img",
"P_PICS": "sxdzt.jpg",
"P_POSTIL": "",
"P_WIDTH": "0",
"P_HEIGHT": "0",
"P_STAR": "4"
},
{
"P_ID": "285",
"P_NAME": "四景山水图",
"P_AUTHOR": "刘松年",
"P_DYNASTY": "南宋",
"P_TYPE": "册页 绢本 水墨 山水",
"P_INFO": "http",
"P_PICS": "sjsst.jpg",
"P_POSTIL": "",
"P_WIDTH": "69",
"P_HEIGHT": "41.3",
"P_STAR": "4"
},
{
"P_ID": "344",
"P_NAME": "出水芙蓉图",
"P_AUTHOR": "吴炳",
"P_DYNASTY": "南宋",
"P_TYPE": "团扇 绢本 设色 花鸟",
"P_INFO": "img",
"P_PICS": "csfrt.jpg",
"P_POSTIL": "",
"P_WIDTH": "25.1",
"P_HEIGHT": "23.8",
"P_STAR": "4"
},
{
"P_ID": "59",
"P_NAME": "溪山清远图",
"P_AUTHOR": "夏圭",
"P_DYNASTY": "南宋",
"P_TYPE": "卷轴 纸本 水墨 山水",
"P_INFO": "http",
"P_PICS": "xsqyt.jpg",
"P_POSTIL": "",
"P_WIDTH": "889.1",
"P_HEIGHT": "46.5",
"P_STAR": "4"
},
{
"P_ID": "350",
"P_NAME": "春山渔艇图",
"P_AUTHOR": "张训礼",
"P_DYNASTY": "南宋",
"P_TYPE": "团扇 绢本 设色 山水",
"P_INFO": "img",
"P_PICS": "csytt.jpg",
"P_POSTIL": "",
"P_WIDTH": "29",
"P_HEIGHT": "29.8",
"P_STAR": "4"
},
{
"P_ID": "43",
"P_NAME": "花篮图",
"P_AUTHOR": "李嵩",
"P_DYNASTY": "南宋",
"P_TYPE": "册页 绢本 设色 花鸟",
"P_INFO": "http",
"P_PICS": "hlt.jpg",
"P_POSTIL": "",
"P_WIDTH": "26.1",
"P_HEIGHT": "19.2",
"P_STAR": "4"
},
{
"P_ID": "46",
"P_NAME": "骷髅幻戏图",
"P_AUTHOR": "李嵩",
"P_DYNASTY": "南宋",
"P_TYPE": "团扇 绢本 设色 人物",
"P_INFO": "http",
"P_PICS": "klhxt.jpg",
"P_POSTIL": "",
"P_WIDTH": "26.3",
"P_HEIGHT": "27",
"P_STAR": "4"
},
{
"P_ID": "342",
"P_NAME": "水末孤亭图",
"P_AUTHOR": "李嵩",
"P_DYNASTY": "南宋",
"P_TYPE": "团扇 绢本 设色 山水",
"P_INFO": "img",
"P_PICS": "smgtt.jpg",
"P_POSTIL": "",
"P_WIDTH": "50",
"P_HEIGHT": "46",
"P_STAR": "4"
},
{
"P_ID": "67",
"P_NAME": "市担婴戏图",
"P_AUTHOR": "李嵩",
"P_DYNASTY": "南宋",
"P_TYPE": "绢本 设色 人物",
"P_INFO": "http",
"P_PICS": "sdyxt.jpg",
"P_POSTIL": "",
"P_WIDTH": "27.6",
"P_HEIGHT": "25.8",
"P_STAR": "4"
},
{
"P_ID": "44",
"P_NAME": "货郎图",
"P_AUTHOR": "李嵩",
"P_DYNASTY": "南宋",
"P_TYPE": "绢本 水墨 人物",
"P_INFO": "http",
"P_PICS": "lshlt.jpg",
"P_POSTIL": "",
"P_WIDTH": "70.4",
"P_HEIGHT": "25.5",
"P_STAR": "4"
},
{
"P_ID": "85",
"P_NAME": "雪树寒禽图",
"P_AUTHOR": "李迪",
"P_DYNASTY": "南宋",
"P_TYPE": "立轴 绢本 设色 花鸟",
"P_INFO": "http",
"P_PICS": "xshqt.jpg",
"P_POSTIL": "",
"P_WIDTH": "52.8",
"P_HEIGHT": "115.2",
"P_STAR": "4"
},
{
"P_ID": "86",
"P_NAME": "风雨归牧图",
"P_AUTHOR": "李迪",
"P_DYNASTY": "南宋",
"P_TYPE": "立轴 绢本 设色 花鸟",
"P_INFO": "http",
"P_PICS": "fxmgt.jpg",
"P_POSTIL": "",
"P_WIDTH": "102.5",
"P_HEIGHT": "120.4",
"P_STAR": "4"
},
{
"P_ID": "84",
"P_NAME": "枫鹰雉鸡图",
"P_AUTHOR": "李迪",
"P_DYNASTY": "南宋",
"P_TYPE": "绢本 设色 花鸟",
"P_INFO": "http",
"P_PICS": "fyzjt.jpg",
"P_POSTIL": "",
"P_WIDTH": "209.5",
"P_HEIGHT": "189",
"P_STAR": "4"
},
{
"P_ID": "80",
"P_NAME": "四梅图",
"P_AUTHOR": "杨无咎",
"P_DYNASTY": "南宋",
"P_TYPE": "卷轴 纸本 水墨",
"P_INFO": "http",
"P_PICS": "smt.jpg",
"P_POSTIL": "",
"P_WIDTH": "358.8",
"P_HEIGHT": "37",
"P_STAR": "4"
},
{
"P_ID": "42",
"P_NAME": "葡萄草虫图",
"P_AUTHOR": "林椿",
"P_DYNASTY": "南宋",
"P_TYPE": "团扇 绢本 设色 花鸟",
"P_INFO": "http",
"P_PICS": "ptcct.jpg",
"P_POSTIL": "",
"P_WIDTH": "27",
"P_HEIGHT": "26.2",
"P_STAR": "4"
},
{
"P_ID": "40",
"P_NAME": "果熟来禽图",
"P_AUTHOR": "林椿",
"P_DYNASTY": "南宋",
"P_TYPE": "绢本 设色 花鸟",
"P_INFO": "http",
"P_PICS": "gslqt.jpg",
"P_POSTIL": "",
"P_WIDTH": "27",
"P_HEIGHT": "26.5",
"P_STAR": "5"
},
{
"P_ID": "41",
"P_NAME": "枇杷山鸟图",
"P_AUTHOR": "林椿",
"P_DYNASTY": "南宋",
"P_TYPE": "绢本 设色 花鸟",
"P_INFO": "http",
"P_PICS": "ppsnt.jpg",
"P_POSTIL": "",
"P_WIDTH": "27.2",
"P_HEIGHT": "26.9",
"P_STAR": "4"
},
{
"P_ID": "69",
"P_NAME": "李白行吟图",
"P_AUTHOR": "梁楷",
"P_DYNASTY": "南宋",
"P_TYPE": "纸本 水墨 人物",
"P_INFO": "http",
"P_PICS": "lbxyt.jpg",
"P_POSTIL": "",
"P_WIDTH": "30.4",
"P_HEIGHT": "81.2",
"P_STAR": "4"
},
{
"P_ID": "70",
"P_NAME": "泼墨仙人图",
"P_AUTHOR": "梁楷",
"P_DYNASTY": "南宋",
"P_TYPE": "册页 纸本 水墨 人物",
"P_INFO": "http",
"P_PICS": "pmxrt.jpg",
"P_POSTIL": "",
"P_WIDTH": "27.7",
"P_HEIGHT": "48.7",
"P_STAR": "5"
},
{
"P_ID": "340",
"P_NAME": "麝香图",
"P_AUTHOR": "毛松",
"P_DYNASTY": "南宋",
"P_TYPE": "团扇 绢本 设色 花鸟",
"P_INFO": "img",
"P_PICS": "sxt.jpg",
"P_POSTIL": "",
"P_WIDTH": "21.3",
"P_HEIGHT": "22.2",
"P_STAR": "4"
},
{
"P_ID": "73",
"P_NAME": "渔村夕照图",
"P_AUTHOR": "牧溪",
"P_DYNASTY": "南宋",
"P_TYPE": "卷轴 纸本 水墨 山水",
"P_INFO": "http",
"P_PICS": "ycxzt.jpg",
"P_POSTIL": "",
"P_WIDTH": "112.4",
"P_HEIGHT": "33",
"P_STAR": "4"
},
{
"P_ID": "296",
"P_NAME": "野蔬草虫图",
"P_AUTHOR": "许迪",
"P_DYNASTY": "南宋",
"P_TYPE": "团扇 绢本 设色",
"P_INFO": "http",
"P_PICS": "yscct.jpg",
"P_POSTIL": "",
"P_WIDTH": "26.9",
"P_HEIGHT": "25.8",
"P_STAR": "4"
},
{
"P_ID": "310",
"P_NAME": "江山秋色图",
"P_AUTHOR": "赵伯驹",
"P_DYNASTY": "南宋",
"P_TYPE": "卷轴 绢本 设色 青绿 山水",
"P_INFO": "http",
"P_PICS": "jsqst.jpg",
"P_POSTIL": "",
"P_WIDTH": "323.2",
"P_HEIGHT": "56.6",
"P_STAR": "4"
},
{
"P_ID": "79",
"P_NAME": "墨兰图",
"P_AUTHOR": "赵孟坚",
"P_DYNASTY": "南宋",
"P_TYPE": "卷轴 纸本 水墨",
"P_INFO": "http",
"P_PICS": "mlt.jpg",
"P_POSTIL": "",
"P_WIDTH": "90.2",
"P_HEIGHT": "34.5",
"P_STAR": "4"
},
{
"P_ID": "311",
"P_NAME": "岁寒三友图",
"P_AUTHOR": "赵孟坚",
"P_DYNASTY": "南宋",
"P_TYPE": "纸本 水墨 花鸟",
"P_INFO": "http",
"P_PICS": "shsyt.jpg",
"P_POSTIL": "",
"P_WIDTH": "53.4",
"P_HEIGHT": "32.2",
"P_STAR": "4"
},
{
"P_ID": "76",
"P_NAME": "墨兰图",
"P_AUTHOR": "郑思肖",
"P_DYNASTY": "南宋",
"P_TYPE": "卷轴 纸本 水墨",
"P_INFO": "http",
"P_PICS": "mlt.jpg",
"P_POSTIL": "",
"P_WIDTH": "55.3",
"P_HEIGHT": "23.2",
"P_STAR": "4"
},
{
"P_ID": "349",
"P_NAME": "松磴精庐图",
"P_AUTHOR": "阎次平",
"P_DYNASTY": "南宋",
"P_TYPE": "团扇 绢本 设色 山水",
"P_INFO": "img",
"P_PICS": "sdjlt.jpg",
"P_POSTIL": "",
"P_WIDTH": "22.6",
"P_HEIGHT": "22.6",
"P_STAR": "4"
},
{
"P_ID": "177",
"P_NAME": "尊眷帖",
"P_AUTHOR": "陆游",
"P_DYNASTY": "南宋",
"P_TYPE": "书法 水墨 纸本",
"P_INFO": "http",
"P_PICS": "zjt.jpg",
"P_POSTIL": "",
"P_WIDTH": "0",
"P_HEIGHT": "0",
"P_STAR": "4"
},
{
"P_ID": "361",
"P_NAME": "九龙图",
"P_AUTHOR": "陈容",
"P_DYNASTY": "南宋",
"P_TYPE": "卷轴 纸本 水墨",
"P_INFO": "http",
"P_PICS": "jlt.jpg",
"P_POSTIL": "",
"P_WIDTH": "1092.4",
"P_HEIGHT": "46.3",
"P_STAR": "4"
},
{
"P_ID": "298",
"P_NAME": "周颂·闵予小子之什图卷",
"P_AUTHOR": "马和之",
"P_DYNASTY": "南宋",
"P_TYPE": "卷轴 绢本 设色",
"P_INFO": "http",
"P_PICS": "mhzzs.jpg",
"P_POSTIL": "",
"P_WIDTH": "713",
"P_HEIGHT": "27.7",
"P_STAR": "4"
},
{
"P_ID": "62",
"P_NAME": "水图",
"P_AUTHOR": "马远",
"P_DYNASTY": "南宋",
"P_TYPE": "册页 绢本 水墨 山水",
"P_INFO": "http",
"P_PICS": "st.jpg",
"P_POSTIL": "",
"P_WIDTH": "20.7",
"P_HEIGHT": "26.8",
"P_STAR": "4"
},
{
"P_ID": "63",
"P_NAME": "山径春行图",
"P_AUTHOR": "马远",
"P_DYNASTY": "南宋",
"P_TYPE": "卷轴 绢本 设色 人物",
"P_INFO": "http",
"P_PICS": "sjcxt.jpg",
"P_POSTIL": "",
"P_WIDTH": "43.1",
"P_HEIGHT": "27.4",
"P_STAR": "4"
},
{
"P_ID": "61",
"P_NAME": "踏歌图",
"P_AUTHOR": "马远",
"P_DYNASTY": "南宋",
"P_TYPE": "立轴 绢本 水墨 山水 人物",
"P_INFO": "http",
"P_PICS": "tgt.jpg",
"P_POSTIL": "",
"P_WIDTH": "111",
"P_HEIGHT": "192.5",
"P_STAR": "5"
},
{
"P_ID": "338",
"P_NAME": "秉烛夜游图",
"P_AUTHOR": "马麟",
"P_DYNASTY": "南宋",
"P_TYPE": "团扇 绢本 设色",
"P_INFO": "img",
"P_PICS": "bzyyt.jpg",
"P_POSTIL": "",
"P_WIDTH": "24.8",
"P_HEIGHT": "25.2",
"P_STAR": "4"
},
{
"P_ID": "351",
"P_NAME": "郊原曳杖图",
"P_AUTHOR": "马麟",
"P_DYNASTY": "南宋",
"P_TYPE": "团扇 绢本 设色 山水",
"P_INFO": "img",
"P_PICS": "jyczt.jpg",
"P_POSTIL": "",
"P_WIDTH": "23.6",
"P_HEIGHT": "23.3",
"P_STAR": "4"
},
{
"P_ID": "64",
"P_NAME": "静听松风图",
"P_AUTHOR": "马麟",
"P_DYNASTY": "南宋",
"P_TYPE": "立轴 绢本 设色 人物",
"P_INFO": "http",
"P_PICS": "jtsft.jpg",
"P_POSTIL": "",
"P_WIDTH": "110.3",
"P_HEIGHT": "226.6",
"P_STAR": "4"
},
{
"P_ID": "288",
"P_NAME": "江山行旅图",
"P_AUTHOR": "太古遗民",
"P_DYNASTY": "金",
"P_TYPE": "卷轴 纸本 水墨 山水",
"P_INFO": "http",
"P_PICS": "jsxlt.jpg",
"P_POSTIL": "",
"P_WIDTH": "40",
"P_HEIGHT": "449",
"P_STAR": "4"
},
{
"P_ID": "281",
"P_NAME": "文姬归汉图",
"P_AUTHOR": "张瑀",
"P_DYNASTY": "金",
"P_TYPE": "卷轴 绢本 设色 人物",
"P_INFO": "http",
"P_PICS": "wjght.jpg",
"P_POSTIL": "",
"P_WIDTH": "129",
"P_HEIGHT": "29",
"P_STAR": "4"
},
{
"P_ID": "289",
"P_NAME": "二骏图",
"P_AUTHOR": "杨微",
"P_DYNASTY": "金",
"P_TYPE": "卷轴 绢本 设色 动物",
"P_INFO": "http",
"P_PICS": "ejt.jpg",
"P_POSTIL": "",
"P_WIDTH": "81",
"P_HEIGHT": "25.2",
"P_STAR": "4"
},
{
"P_ID": "286",
"P_NAME": "赤壁图",
"P_AUTHOR": "武元直",
"P_DYNASTY": "金",
"P_TYPE": "卷轴 纸本 水墨 山水",
"P_INFO": "http",
"P_PICS": "cbt.jpg",
"P_POSTIL": "",
"P_WIDTH": "136",
"P_HEIGHT": "51",
"P_STAR": "4"
},
{
"P_ID": "87",
"P_NAME": "幽竹枯槎图",
"P_AUTHOR": "王庭筠",
"P_DYNASTY": "金",
"P_TYPE": "纸本 水墨",
"P_INFO": "http",
"P_PICS": "yzkct.jpg",
"P_POSTIL": "",
"P_WIDTH": "69.7",
"P_HEIGHT": "38",
"P_STAR": "4"
},
{
"P_ID": "366",
"P_NAME": "商山四皓图",
"P_AUTHOR": "佚名",
"P_DYNASTY": "元",
"P_TYPE": "立轴 绢本 设色 山水 人物",
"P_INFO": "http",
"P_PICS": "sssht.jpg",
"P_POSTIL": "",
"P_WIDTH": "77.2",
"P_HEIGHT": "155.3",
"P_STAR": "4"
},
{
"P_ID": "106",
"P_NAME": "容膝斋图",
"P_AUTHOR": "倪瓒",
"P_DYNASTY": "元",
"P_TYPE": "立轴 纸本 水墨 山水",
"P_INFO": "http",
"P_PICS": "rxzt.jpg",
"P_POSTIL": "",
"P_WIDTH": "35.5",
"P_HEIGHT": "74.7",
"P_STAR": "5"
},
{
"P_ID": "327",
"P_NAME": "幽涧寒松图",
"P_AUTHOR": "倪瓒",
"P_DYNASTY": "元",
"P_TYPE": "立轴 纸本 水墨 山水",
"P_INFO": "http",
"P_PICS": "yjhst.jpg",
"P_POSTIL": "",
"P_WIDTH": "50.4",
"P_HEIGHT": "59.7",
"P_STAR": "4"
},
{
"P_ID": "103",
"P_NAME": "墨竹谱",
"P_AUTHOR": "吴镇",
"P_DYNASTY": "元",
"P_TYPE": "册页 纸本 水墨",
"P_INFO": "http",
"P_PICS": "mzp.jpg",
"P_POSTIL": "",
"P_WIDTH": "52",
"P_HEIGHT": "40.3",
"P_STAR": "4"
},
{
"P_ID": "104",
"P_NAME": "渔父图",
"P_AUTHOR": "吴镇",
"P_DYNASTY": "元",
"P_TYPE": "立轴 绢本 水墨 山水",
"P_INFO": "http",
"P_PICS": "yft.jpg",
"P_POSTIL": "",
"P_WIDTH": "95.6",
"P_HEIGHT": "176.1",
"P_STAR": "4"
},
{
"P_ID": "181",
"P_NAME": "陋室铭",
"P_AUTHOR": "文徵明",
"P_DYNASTY": "元",
"P_TYPE": "书法 水墨 纸本",
"P_INFO": "http",
"P_PICS": "lsm.jpg",
"P_POSTIL": "",
"P_WIDTH": "0",
"P_HEIGHT": "0",
"P_STAR": "4"
},
{
"P_ID": "330",
"P_NAME": "四清图",
"P_AUTHOR": "李衎",
"P_DYNASTY": "元",
"P_TYPE": "卷轴 纸本 水墨",
"P_INFO": "http",
"P_PICS": "xqt.jpg",
"P_POSTIL": "",
"P_WIDTH": "359.8",
"P_HEIGHT": "36.5",
"P_STAR": "4"
},
{
"P_ID": "331",
"P_NAME": "清閟阁墨竹图",
"P_AUTHOR": "柯九思",
"P_DYNASTY": "元",
"P_TYPE": "立轴 纸本 水墨",
"P_INFO": "http",
"P_PICS": "qbgmzt.jpg",
"P_POSTIL": "",
"P_WIDTH": "58.5",
"P_HEIGHT": "132.8",
"P_STAR": "4"
},
{
"P_ID": "102",
"P_NAME": "墨梅图",
"P_AUTHOR": "王冕",
"P_DYNASTY": "元",
"P_TYPE": "纸本 水墨 花鸟",
"P_INFO": "http",
"P_PICS": "mmt.jpg",
"P_POSTIL": "",
"P_WIDTH": "26",
"P_HEIGHT": "68",
"P_STAR": "4"
},
{
"P_ID": "329",
"P_NAME": "杨竹西小像",
"P_AUTHOR": "王绎",
"P_DYNASTY": "元",
"P_TYPE": "卷轴 纸本 水墨 人物",
"P_INFO": "http",
"P_PICS": "yzxxx.jpg",
"P_POSTIL": "作者王绎、倪瓒。王绎执笔画人物，倪瓒补景。",
"P_WIDTH": "86.8",
"P_HEIGHT": "27.7",
"P_STAR": "4"
},
{
"P_ID": "295",
"P_NAME": "瑶岑玉树图",
"P_AUTHOR": "王蒙",
"P_DYNASTY": "元",
"P_TYPE": "立轴 纸本 设色 山水",
"P_INFO": "http",
"P_PICS": "ycyst.jpg",
"P_POSTIL": "",
"P_WIDTH": "40",
"P_HEIGHT": "96.4",
"P_STAR": "4"
},
{
"P_ID": "107",
"P_NAME": "青卞隐居图",
"P_AUTHOR": "王蒙",
"P_DYNASTY": "元",
"P_TYPE": "立轴 纸本 水墨 山水",
"P_INFO": "http",
"P_PICS": "qbyjt.jpg",
"P_POSTIL": "",
"P_WIDTH": "42.2",
"P_HEIGHT": "141",
"P_STAR": "4"
},
{
"P_ID": "108",
"P_NAME": "具区林屋图",
"P_AUTHOR": "王蒙",
"P_DYNASTY": "元",
"P_TYPE": "立轴 纸本 设色 山水",
"P_INFO": "http",
"P_PICS": "jqlwt.jpg",
"P_POSTIL": "",
"P_WIDTH": "42.5",
"P_HEIGHT": "68.7",
"P_STAR": "4"
},
{
"P_ID": "186",
"P_NAME": "江枫秋艇图",
"P_AUTHOR": "盛懋",
"P_DYNASTY": "元",
"P_TYPE": "卷轴 青绿 水墨 山水",
"P_INFO": "http",
"P_PICS": "jfqtt.jpg",
"P_POSTIL": "",
"P_WIDTH": "111",
"P_HEIGHT": "24.7",
"P_STAR": "4"
},
{
"P_ID": "99",
"P_NAME": "竹石图",
"P_AUTHOR": "管道昇",
"P_DYNASTY": "元",
"P_TYPE": "立轴 纸本 水墨",
"P_INFO": "http",
"P_PICS": "gdszst.jpg",
"P_POSTIL": "",
"P_WIDTH": "28.7",
"P_HEIGHT": "87.1",
"P_STAR": "4"
},
{
"P_ID": "291",
"P_NAME": "二羊图",
"P_AUTHOR": "赵孟頫",
"P_DYNASTY": "元",
"P_TYPE": "卷轴 纸本 水墨 动物",
"P_INFO": "http",
"P_PICS": "eyt.jpg",
"P_POSTIL": "",
"P_WIDTH": "48.2",
"P_HEIGHT": "25.2",
"P_STAR": "4"
},
{
"P_ID": "94",
"P_NAME": "调良图",
"P_AUTHOR": "赵孟頫",
"P_DYNASTY": "元",
"P_TYPE": "册页 纸本 水墨 动物",
"P_INFO": "http",
"P_PICS": "tlt.jpg",
"P_POSTIL": "",
"P_WIDTH": "49",
"P_HEIGHT": "22.7",
"P_STAR": "4"
},
{
"P_ID": "97",
"P_NAME": "水村图",
"P_AUTHOR": "赵孟頫",
"P_DYNASTY": "元",
"P_TYPE": "卷轴 纸本 水墨 山水",
"P_INFO": "http",
"P_PICS": "sct.jpg",
"P_POSTIL": "",
"P_WIDTH": "120.5",
"P_HEIGHT": "24.9",
"P_STAR": "4"
},
{
"P_ID": "178",
"P_NAME": "秋声赋",
"P_AUTHOR": "赵孟頫",
"P_DYNASTY": "元",
"P_TYPE": "书法 水墨 纸本",
"P_INFO": "http",
"P_PICS": "qsf.jpg",
"P_POSTIL": "",
"P_WIDTH": "0",
"P_HEIGHT": "0",
"P_STAR": "4"
},
{
"P_ID": "184",
"P_NAME": "前后赤壁赋",
"P_AUTHOR": "赵孟頫",
"P_DYNASTY": "元",
"P_TYPE": "书法 水墨 册页 纸本",
"P_INFO": "http",
"P_PICS": "qhcbf.jpg",
"P_POSTIL": "",
"P_WIDTH": "0",
"P_HEIGHT": "0",
"P_STAR": "5"
},
{
"P_ID": "95",
"P_NAME": "古木散马图",
"P_AUTHOR": "赵孟頫",
"P_DYNASTY": "元",
"P_TYPE": "纸本 水墨 动物",
"P_INFO": "http",
"P_PICS": "gmsmt.jpg",
"P_POSTIL": "",
"P_WIDTH": "71",
"P_HEIGHT": "29.6",
"P_STAR": "4"
},
{
"P_ID": "98",
"P_NAME": "窠木竹石图",
"P_AUTHOR": "赵孟頫",
"P_DYNASTY": "元",
"P_TYPE": "立轴 绢本 水墨",
"P_INFO": "http",
"P_PICS": "kmzst.jpg",
"P_POSTIL": "",
"P_WIDTH": "48.2",
"P_HEIGHT": "99.4",
"P_STAR": "4"
},
{
"P_ID": "179",
"P_NAME": "心经",
"P_AUTHOR": "赵孟頫",
"P_DYNASTY": "元",
"P_TYPE": "书法 水墨 纸本",
"P_INFO": "http",
"P_PICS": "xj.jpg",
"P_POSTIL": "",
"P_WIDTH": "0",
"P_HEIGHT": "0",
"P_STAR": "4"
},
{
"P_ID": "96",
"P_NAME": "鹊华秋色图",
"P_AUTHOR": "赵孟頫",
"P_DYNASTY": "元",
"P_TYPE": "卷轴 纸本 设色 山水",
"P_INFO": "http",
"P_PICS": "qhqst.jpg",
"P_POSTIL": "",
"P_WIDTH": "90.2",
"P_HEIGHT": "28.4",
"P_STAR": "5"
},
{
"P_ID": "325",
"P_NAME": "秋郊饮马图",
"P_AUTHOR": "赵孟頫",
"P_DYNASTY": "元",
"P_TYPE": "卷轴 绢本 设色",
"P_INFO": "http",
"P_PICS": "qjymt.jpg",
"P_POSTIL": "",
"P_WIDTH": "59",
"P_HEIGHT": "23.6",
"P_STAR": "4"
},
{
"P_ID": "180",
"P_NAME": "真草千文",
"P_AUTHOR": "赵孟頫",
"P_DYNASTY": "元",
"P_TYPE": "书法 水墨 纸本",
"P_INFO": "http",
"P_PICS": "zcqw.jpg",
"P_POSTIL": "",
"P_WIDTH": "0",
"P_HEIGHT": "0",
"P_STAR": "4"
},
{
"P_ID": "100",
"P_NAME": "挟弹游骑图",
"P_AUTHOR": "赵雍",
"P_DYNASTY": "元",
"P_TYPE": "纸本 设色 人物",
"P_INFO": "http",
"P_PICS": "jdyjt.jpg",
"P_POSTIL": "",
"P_WIDTH": "46",
"P_HEIGHT": "108.5",
"P_STAR": "4"
},
{
"P_ID": "91",
"P_NAME": "贵妃上马图",
"P_AUTHOR": "钱选",
"P_DYNASTY": "元",
"P_TYPE": "卷轴 纸本 设色 人物",
"P_INFO": "http",
"P_PICS": "gfsmt.jpg",
"P_POSTIL": "",
"P_WIDTH": "117",
"P_HEIGHT": "29.5",
"P_STAR": "4"
},
{
"P_ID": "90",
"P_NAME": "八花图",
"P_AUTHOR": "钱选",
"P_DYNASTY": "元",
"P_TYPE": "卷轴 纸本 设色 花鸟",
"P_INFO": "http",
"P_PICS": "bht.jpg",
"P_POSTIL": "",
"P_WIDTH": "333.9",
"P_HEIGHT": "29.4",
"P_STAR": "4"
},
{
"P_ID": "92",
"P_NAME": "浮玉山居图",
"P_AUTHOR": "钱选",
"P_DYNASTY": "元",
"P_TYPE": "卷轴 纸本 设色 山水",
"P_INFO": "http",
"P_PICS": "fysjt.jpg",
"P_POSTIL": "",
"P_WIDTH": "98.7",
"P_HEIGHT": "29.6",
"P_STAR": "4"
},
{
"P_ID": "89",
"P_NAME": "羲之观鹅图",
"P_AUTHOR": "钱选",
"P_DYNASTY": "元",
"P_TYPE": "卷轴 纸本 设色 人物 山水",
"P_INFO": "http",
"P_PICS": "xzget.jpg",
"P_POSTIL": "",
"P_WIDTH": "92.7",
"P_HEIGHT": "23.2",
"P_STAR": "4"
},
{
"P_ID": "93",
"P_NAME": "桃枝松鼠图",
"P_AUTHOR": "钱选",
"P_DYNASTY": "元",
"P_TYPE": "卷轴 纸本 设色 动物",
"P_INFO": "http",
"P_PICS": "tzsst.jpg",
"P_POSTIL": "",
"P_WIDTH": "44.3",
"P_HEIGHT": "26.3",
"P_STAR": "4"
},
{
"P_ID": "101",
"P_NAME": "溪凫图",
"P_AUTHOR": "陈琳",
"P_DYNASTY": "元",
"P_TYPE": "纸本 设色 花鸟",
"P_INFO": "http",
"P_PICS": "xft.jpg",
"P_POSTIL": "",
"P_WIDTH": "47.5",
"P_HEIGHT": "35.7",
"P_STAR": "4"
},
{
"P_ID": "328",
"P_NAME": "朝元图",
"P_AUTHOR": "马君祥",
"P_DYNASTY": "元",
"P_TYPE": "壁画 人物",
"P_INFO": "http",
"P_PICS": "cyt.jpg",
"P_POSTIL": "作者马君祥 马七等。",
"P_WIDTH": "0",
"P_HEIGHT": "0",
"P_STAR": "4"
},
{
"P_ID": "326",
"P_NAME": "云横秀岭图",
"P_AUTHOR": "高克恭",
"P_DYNASTY": "元",
"P_TYPE": "立轴 绢本 设色 山水",
"P_INFO": "http",
"P_PICS": "yhxlt.jpg",
"P_POSTIL": "",
"P_WIDTH": "106.7",
"P_HEIGHT": "182.3",
"P_STAR": "4"
},
{
"P_ID": "105",
"P_NAME": "富春山居图",
"P_AUTHOR": "黄公望",
"P_DYNASTY": "元",
"P_TYPE": "卷轴 纸本 水墨 山水",
"P_INFO": "http",
"P_PICS": "fcsjt.jpg",
"P_POSTIL": "",
"P_WIDTH": "636.9",
"P_HEIGHT": "33",
"P_STAR": "5"
},
{
"P_ID": "77",
"P_NAME": "中山出游图",
"P_AUTHOR": "龚开",
"P_DYNASTY": "元",
"P_TYPE": "卷轴 纸本 水墨 人物",
"P_INFO": "http",
"P_PICS": "zzcyt.jpg",
"P_POSTIL": "",
"P_WIDTH": "169.5",
"P_HEIGHT": "32.8",
"P_STAR": "5"
},
{
"P_ID": "78",
"P_NAME": "骏骨图",
"P_AUTHOR": "龚开",
"P_DYNASTY": "元",
"P_TYPE": "卷轴 纸本 水墨 动物",
"P_INFO": "http",
"P_PICS": "jgt.jpg",
"P_POSTIL": "",
"P_WIDTH": "56.9",
"P_HEIGHT": "29.9",
"P_STAR": "4"
},
{
"P_ID": "364",
"P_NAME": "渔乐图",
"P_AUTHOR": "丁玉川",
"P_DYNASTY": "明",
"P_TYPE": "立轴 纸本 水墨 山水 人物",
"P_INFO": "http",
"P_PICS": "ylt.jpg",
"P_POSTIL": "",
"P_WIDTH": "38",
"P_HEIGHT": "77",
"P_STAR": "4"
},
{
"P_ID": "321",
"P_NAME": "桃源仙境图",
"P_AUTHOR": "仇英",
"P_DYNASTY": "明",
"P_TYPE": "立轴 绢本 设色 山水 人物",
"P_INFO": "http",
"P_PICS": "tyxjt.jpg",
"P_POSTIL": "",
"P_WIDTH": "66.7",
"P_HEIGHT": "175",
"P_STAR": "4"
},
{
"P_ID": "122",
"P_NAME": "汉宫春晓图",
"P_AUTHOR": "仇英",
"P_DYNASTY": "明",
"P_TYPE": "卷轴 绢本 设色 人物",
"P_INFO": "http",
"P_PICS": "hgcxt.jpg",
"P_POSTIL": "",
"P_WIDTH": "574.1",
"P_HEIGHT": "30.6",
"P_STAR": "5"
},
{
"P_ID": "354",
"P_NAME": "帝释梵天西",
"P_AUTHOR": "佚名",
"P_DYNASTY": "明",
"P_TYPE": "壁画",
"P_INFO": "http",
"P_PICS": "dsftx.jpg",
"P_POSTIL": "",
"P_WIDTH": "0",
"P_HEIGHT": "0",
"P_STAR": "4"
},
{
"P_ID": "110",
"P_NAME": "渔乐图",
"P_AUTHOR": "吴伟",
"P_DYNASTY": "明",
"P_TYPE": "卷轴 纸本 设色",
"P_INFO": "http",
"P_PICS": "ylt.jpg",
"P_POSTIL": "",
"P_WIDTH": "0",
"P_HEIGHT": "27.3",
"P_STAR": "4"
},
{
"P_ID": "127",
"P_NAME": "仙山高士图",
"P_AUTHOR": "吴彬",
"P_DYNASTY": "明",
"P_TYPE": "立轴 纸本 设色 山水",
"P_INFO": "http",
"P_PICS": "xsgst.jpg",
"P_POSTIL": "",
"P_WIDTH": "59.1",
"P_HEIGHT": "162",
"P_STAR": "4"
},
{
"P_ID": "111",
"P_NAME": "流民图",
"P_AUTHOR": "周臣",
"P_DYNASTY": "明",
"P_TYPE": "卷轴 纸本 设色",
"P_INFO": "http",
"P_PICS": "lmt.jpg",
"P_POSTIL": "",
"P_WIDTH": "244.5",
"P_HEIGHT": "31.9",
"P_STAR": "4"
},
{
"P_ID": "117",
"P_NAME": "溪山渔隐图",
"P_AUTHOR": "唐寅",
"P_DYNASTY": "明",
"P_TYPE": "卷轴 绢本 设色 山水",
"P_INFO": "http",
"P_PICS": "xsyyt.jpg",
"P_POSTIL": "",
"P_WIDTH": "351",
"P_HEIGHT": "29.2",
"P_STAR": "4"
},
{
"P_ID": "118",
"P_NAME": "吹萧仕女图",
"P_AUTHOR": "唐寅",
"P_DYNASTY": "明",
"P_TYPE": "立轴 设色 人物",
"P_INFO": "http",
"P_PICS": "cxsnt.jpg",
"P_POSTIL": "",
"P_WIDTH": "89.5",
"P_HEIGHT": "184.8",
"P_STAR": "5"
},
{
"P_ID": "191",
"P_NAME": "函关雪霁图",
"P_AUTHOR": "唐寅",
"P_DYNASTY": "明",
"P_TYPE": "立轴 绢本 设色 山水",
"P_INFO": "img",
"P_PICS": "hgxjt.jpg",
"P_POSTIL": "",
"P_WIDTH": "37.3",
"P_HEIGHT": "69.3",
"P_STAR": "4"
},
{
"P_ID": "116",
"P_NAME": "西洲话旧图",
"P_AUTHOR": "唐寅",
"P_DYNASTY": "明",
"P_TYPE": "立轴 纸本 水墨",
"P_INFO": "http",
"P_PICS": "xzhjt.jpg",
"P_POSTIL": "",
"P_WIDTH": "52.3",
"P_HEIGHT": "110.7",
"P_STAR": "4"
},
{
"P_ID": "322",
"P_NAME": "秋风纨扇图",
"P_AUTHOR": "唐寅",
"P_DYNASTY": "明",
"P_TYPE": "立轴 纸本 水墨 人物",
"P_INFO": "http",
"P_PICS": "qfwst.jpg",
"P_POSTIL": "",
"P_WIDTH": "39.3",
"P_HEIGHT": "77.1",
"P_STAR": "5"
},
{
"P_ID": "126",
"P_NAME": "扫象图",
"P_AUTHOR": "崔子忠",
"P_DYNASTY": "明",
"P_TYPE": "立轴 绢本 设色",
"P_INFO": "http",
"P_PICS": "sxt.jpg",
"P_POSTIL": "",
"P_WIDTH": "49.4",
"P_HEIGHT": "152.5",
"P_STAR": "4"
},
{
"P_ID": "120",
"P_NAME": "墨花九段图卷",
"P_AUTHOR": "徐渭",
"P_DYNASTY": "明",
"P_TYPE": "卷轴 纸本 水墨 花鸟",
"P_INFO": "http",
"P_PICS": "mhjdtj.jpg",
"P_POSTIL": "",
"P_WIDTH": "625",
"P_HEIGHT": "46.6",
"P_STAR": "5"
},
{
"P_ID": "352",
"P_NAME": "黄甲图",
"P_AUTHOR": "徐渭",
"P_DYNASTY": "明",
"P_TYPE": "立轴 纸本 水墨",
"P_INFO": "http",
"P_PICS": "hjt.jpg",
"P_POSTIL": "",
"P_WIDTH": "29.7",
"P_HEIGHT": "114.6",
"P_STAR": "4"
},
{
"P_ID": "121",
"P_NAME": "蟹鱼图",
"P_AUTHOR": "徐渭",
"P_DYNASTY": "明",
"P_TYPE": "卷轴 纸本 水墨",
"P_INFO": "http",
"P_PICS": "xyt.jpg",
"P_POSTIL": "",
"P_WIDTH": "98",
"P_HEIGHT": "28.7",
"P_STAR": "4"
},
{
"P_ID": "119",
"P_NAME": "墨葡萄图",
"P_AUTHOR": "徐渭",
"P_DYNASTY": "明",
"P_TYPE": "立轴 纸本 水墨 花鸟",
"P_INFO": "http",
"P_PICS": "mptt.jpg",
"P_POSTIL": "",
"P_WIDTH": "64.5",
"P_HEIGHT": "165.4",
"P_STAR": "4"
},
{
"P_ID": "109",
"P_NAME": "渔人图",
"P_AUTHOR": "戴进",
"P_DYNASTY": "明",
"P_TYPE": "卷轴 纸本 设色",
"P_INFO": "http",
"P_PICS": "yrt.jpg",
"P_POSTIL": "",
"P_WIDTH": "0",
"P_HEIGHT": "46",
"P_STAR": "4"
},
{
"P_ID": "324",
"P_NAME": "风雨归舟图",
"P_AUTHOR": "戴进",
"P_DYNASTY": "明",
"P_TYPE": "立轴 绢本 设色 山水",
"P_INFO": "http",
"P_PICS": "fygzt.jpg",
"P_POSTIL": "",
"P_WIDTH": "81.8",
"P_HEIGHT": "143",
"P_STAR": "4"
},
{
"P_ID": "320",
"P_NAME": "湘君湘夫人图",
"P_AUTHOR": "文徵明",
"P_DYNASTY": "明",
"P_TYPE": "立轴 纸本 设色 人物",
"P_INFO": "http",
"P_PICS": "xjxfrt.jpg",
"P_POSTIL": "",
"P_WIDTH": "35.6",
"P_HEIGHT": "100.8",
"P_STAR": "4"
},
{
"P_ID": "115",
"P_NAME": "古木寒泉图",
"P_AUTHOR": "文徵明",
"P_DYNASTY": "明",
"P_TYPE": "立轴 绢本 设色 山水",
"P_INFO": "http",
"P_PICS": "gmhqt.jpg",
"P_POSTIL": "",
"P_WIDTH": "59",
"P_HEIGHT": "139.6",
"P_STAR": "4"
},
{
"P_ID": "114",
"P_NAME": "写生册页·驴",
"P_AUTHOR": "沈周",
"P_DYNASTY": "明",
"P_TYPE": "册页 纸本 水墨",
"P_INFO": "img",
"P_PICS": "xscl.jpg",
"P_POSTIL": "",
"P_WIDTH": "55.4",
"P_HEIGHT": "34.7",
"P_STAR": "4"
},
{
"P_ID": "323",
"P_NAME": "庐山高图",
"P_AUTHOR": "沈周",
"P_DYNASTY": "明",
"P_TYPE": "立轴 纸本 设色 山水",
"P_INFO": "http",
"P_PICS": "lsgt.jpg",
"P_POSTIL": "",
"P_WIDTH": "98.1",
"P_HEIGHT": "193.8",
"P_STAR": "4"
},
{
"P_ID": "112",
"P_NAME": "策杖图",
"P_AUTHOR": "沈周",
"P_DYNASTY": "明",
"P_TYPE": "立轴 纸本 水墨 山水",
"P_INFO": "http",
"P_PICS": "czt.jpg",
"P_POSTIL": "",
"P_WIDTH": "72",
"P_HEIGHT": "158",
"P_STAR": "5"
},
{
"P_ID": "365",
"P_NAME": "瓶荷图",
"P_AUTHOR": "沈周",
"P_DYNASTY": "明",
"P_TYPE": "立轴 纸本 设色 静物",
"P_INFO": "http",
"P_PICS": "pht.jpg",
"P_POSTIL": "",
"P_WIDTH": "60",
"P_HEIGHT": "144.5",
"P_STAR": "4"
},
{
"P_ID": "113",
"P_NAME": "写生册页·猫",
"P_AUTHOR": "沈周",
"P_DYNASTY": "明",
"P_TYPE": "册页 纸本 水墨",
"P_INFO": "img",
"P_PICS": "xscm.jpg",
"P_POSTIL": "",
"P_WIDTH": "54.9",
"P_HEIGHT": "34.8",
"P_STAR": "5"
},
{
"P_ID": "185",
"P_NAME": "草书诗帖",
"P_AUTHOR": "祝允明",
"P_DYNASTY": "明",
"P_TYPE": "书法 水墨 纸本",
"P_INFO": "http",
"P_PICS": "csst.jpg",
"P_POSTIL": "",
"P_WIDTH": "0",
"P_HEIGHT": "0",
"P_STAR": "5"
},
{
"P_ID": "124",
"P_NAME": "秋兴八景图",
"P_AUTHOR": "董其昌",
"P_DYNASTY": "明",
"P_TYPE": "纸本 设色 山水",
"P_INFO": "http",
"P_PICS": "qxbjt.jpg",
"P_POSTIL": "",
"P_WIDTH": "31.7",
"P_HEIGHT": "53.8",
"P_STAR": "4"
},
{
"P_ID": "188",
"P_NAME": "秋山图",
"P_AUTHOR": "董其昌",
"P_DYNASTY": "明",
"P_TYPE": "立轴 绢本 设色 山水",
"P_INFO": "img",
"P_PICS": "qst.jpg",
"P_POSTIL": "",
"P_WIDTH": "37.5",
"P_HEIGHT": "107.5",
"P_STAR": "5"
},
{
"P_ID": "125",
"P_NAME": "燕吴八景图",
"P_AUTHOR": "董其昌",
"P_DYNASTY": "明",
"P_TYPE": "团扇 设色 山水",
"P_INFO": "http",
"P_PICS": "ywbjt.jpg",
"P_POSTIL": "",
"P_WIDTH": "0",
"P_HEIGHT": "0",
"P_STAR": "4"
},
{
"P_ID": "187",
"P_NAME": "三友百禽图",
"P_AUTHOR": "边景昭",
"P_DYNASTY": "明",
"P_TYPE": "立轴 绢本 设色 花鸟",
"P_INFO": "http",
"P_PICS": "sybqt.jpg",
"P_POSTIL": "",
"P_WIDTH": "78.1",
"P_HEIGHT": "152.2",
"P_STAR": "5"
},
{
"P_ID": "123",
"P_NAME": "水浒叶子",
"P_AUTHOR": "陈洪绶",
"P_DYNASTY": "明",
"P_TYPE": "版画 人物",
"P_INFO": "http",
"P_PICS": "shyz.jpg",
"P_POSTIL": "",
"P_WIDTH": "0",
"P_HEIGHT": "0",
"P_STAR": "4"
},
{
"P_ID": "319",
"P_NAME": "荷花鸳鸯图",
"P_AUTHOR": "陈洪绶",
"P_DYNASTY": "明",
"P_TYPE": "立轴 绢本 设色 花鸟",
"P_INFO": "http",
"P_PICS": "hhyyt.jpg",
"P_POSTIL": "",
"P_WIDTH": "98.3",
"P_HEIGHT": "183",
"P_STAR": "4"
},
{
"P_ID": "150",
"P_NAME": "中秋赏月图",
"P_AUTHOR": "任伯年",
"P_DYNASTY": "清",
"P_TYPE": "立轴 纸本 设色",
"P_INFO": "http",
"P_PICS": "zqsyt.jpg",
"P_POSTIL": "",
"P_WIDTH": "60",
"P_HEIGHT": "122",
"P_STAR": "4"
},
{
"P_ID": "148",
"P_NAME": "女娲补天图",
"P_AUTHOR": "任伯年",
"P_DYNASTY": "清",
"P_TYPE": "立轴 纸本 设色 人物",
"P_INFO": "http",
"P_PICS": "nwbtt.jpg",
"P_POSTIL": "",
"P_WIDTH": "66",
"P_HEIGHT": "119.6",
"P_STAR": "4"
},
{
"P_ID": "142",
"P_NAME": "桃潭浴鸭图",
"P_AUTHOR": "华嵒",
"P_DYNASTY": "清",
"P_TYPE": "立轴 纸本 设色 花鸟",
"P_INFO": "http",
"P_PICS": "ttyyt.jpg",
"P_POSTIL": "",
"P_WIDTH": "137",
"P_HEIGHT": "271.5",
"P_STAR": "4"
},
{
"P_ID": "190",
"P_NAME": "湖天春色图",
"P_AUTHOR": "吴历",
"P_DYNASTY": "清",
"P_TYPE": "立轴 纸本 设色 山水",
"P_INFO": "http",
"P_PICS": "htcst.jpg",
"P_POSTIL": "",
"P_WIDTH": "62.5",
"P_HEIGHT": "123.5",
"P_STAR": "4"
},
{
"P_ID": "317",
"P_NAME": "锦石秋花图",
"P_AUTHOR": "恽寿平",
"P_DYNASTY": "清",
"P_TYPE": "立轴 绢本 设色 花鸟",
"P_INFO": "http",
"P_PICS": "jsqht.jpg",
"P_POSTIL": "",
"P_WIDTH": "58.6",
"P_HEIGHT": "140.5",
"P_STAR": "4"
},
{
"P_ID": "189",
"P_NAME": "百花图",
"P_AUTHOR": "恽寿平",
"P_DYNASTY": "清",
"P_TYPE": "卷轴 绢本 设色 花鸟",
"P_INFO": "http",
"P_PICS": "bht.jpg",
"P_POSTIL": "",
"P_WIDTH": "32",
"P_HEIGHT": "530",
"P_STAR": "4"
},
{
"P_ID": "129",
"P_NAME": "鱼石图",
"P_AUTHOR": "朱耷",
"P_DYNASTY": "清",
"P_TYPE": "立轴 纸本 水墨 动物",
"P_INFO": "http",
"P_PICS": "yst.jpg",
"P_POSTIL": "",
"P_WIDTH": "60.5",
"P_HEIGHT": "134.8",
"P_STAR": "4"
},
{
"P_ID": "130",
"P_NAME": "猫石图",
"P_AUTHOR": "朱耷",
"P_DYNASTY": "清",
"P_TYPE": "卷轴 纸本 水墨 动物",
"P_INFO": "http",
"P_PICS": "mst.jpg",
"P_POSTIL": "",
"P_WIDTH": "218",
"P_HEIGHT": "34",
"P_STAR": "5"
},
{
"P_ID": "128",
"P_NAME": "松树双鹿图",
"P_AUTHOR": "朱耷",
"P_DYNASTY": "清",
"P_TYPE": "立轴 纸本 水墨 动物",
"P_INFO": "http",
"P_PICS": "ssslt.jpg",
"P_POSTIL": "",
"P_WIDTH": "91.4",
"P_HEIGHT": "182",
"P_STAR": "4"
},
{
"P_ID": "131",
"P_NAME": "孤禽图",
"P_AUTHOR": "朱耷",
"P_DYNASTY": "清",
"P_TYPE": "立轴 纸本 水墨 动物",
"P_INFO": "http",
"P_PICS": "gqt.jpg",
"P_POSTIL": "",
"P_WIDTH": "44",
"P_HEIGHT": "103.5",
"P_STAR": "5"
},
{
"P_ID": "143",
"P_NAME": "玫瑰图",
"P_AUTHOR": "李鱓",
"P_DYNASTY": "清",
"P_TYPE": "纸本 设色 花鸟",
"P_INFO": "http",
"P_PICS": "mgt.jpg",
"P_POSTIL": "",
"P_WIDTH": "39.7",
"P_HEIGHT": "26.7",
"P_STAR": "4"
},
{
"P_ID": "144",
"P_NAME": "萱草花",
"P_AUTHOR": "李鱓",
"P_DYNASTY": "清",
"P_TYPE": "纸本 设色 花鸟",
"P_INFO": "http",
"P_PICS": "xch.jpg",
"P_POSTIL": "",
"P_WIDTH": "38.8",
"P_HEIGHT": "28.9",
"P_STAR": "4"
},
{
"P_ID": "135",
"P_NAME": "黄山图",
"P_AUTHOR": "梅清",
"P_DYNASTY": "清",
"P_TYPE": "册页 纸本 水墨 山水",
"P_INFO": "http",
"P_PICS": "hst.jpg",
"P_POSTIL": "",
"P_WIDTH": "44.8",
"P_HEIGHT": "32.6",
"P_STAR": "4"
},
{
"P_ID": "315",
"P_NAME": "天都峰图轴",
"P_AUTHOR": "渐江",
"P_DYNASTY": "清",
"P_TYPE": "立轴 纸本 水墨 山水",
"P_INFO": "http",
"P_PICS": "tdftz.jpg",
"P_POSTIL": "",
"P_WIDTH": "99.6",
"P_HEIGHT": "307.5",
"P_STAR": "4"
},
{
"P_ID": "134",
"P_NAME": "黄海松石图",
"P_AUTHOR": "渐江",
"P_DYNASTY": "清",
"P_TYPE": "立轴 纸本 水墨 山水",
"P_INFO": "http",
"P_PICS": "hhsst.jpg",
"P_POSTIL": "",
"P_WIDTH": "81",
"P_HEIGHT": "198.7",
"P_STAR": "4"
},
{
"P_ID": "318",
"P_NAME": "南山积翠图",
"P_AUTHOR": "王时敏",
"P_DYNASTY": "清",
"P_TYPE": "立轴 绢本 设色 山水",
"P_INFO": "http",
"P_PICS": "nsjct.jpg",
"P_POSTIL": "",
"P_WIDTH": "66.4",
"P_HEIGHT": "147.1",
"P_STAR": "4"
},
{
"P_ID": "137",
"P_NAME": "山水图",
"P_AUTHOR": "王时敏",
"P_DYNASTY": "清",
"P_TYPE": "册页 纸本 水墨 山水",
"P_INFO": "http",
"P_PICS": "sst.jpg",
"P_POSTIL": "",
"P_WIDTH": "31",
"P_HEIGHT": "23",
"P_STAR": "4"
},
{
"P_ID": "138",
"P_NAME": "山水扇面",
"P_AUTHOR": "王翚",
"P_DYNASTY": "清",
"P_TYPE": "纸扇 纸本 设色 山水",
"P_INFO": "http",
"P_PICS": "sssm.jpg",
"P_POSTIL": "",
"P_WIDTH": "55.7",
"P_HEIGHT": "17.7",
"P_STAR": "4"
},
{
"P_ID": "132",
"P_NAME": "江山胜揽图",
"P_AUTHOR": "石涛",
"P_DYNASTY": "清",
"P_TYPE": "卷轴 纸本 水墨 山水",
"P_INFO": "http",
"P_PICS": "jslst.jpg",
"P_POSTIL": "",
"P_WIDTH": "762",
"P_HEIGHT": "20",
"P_STAR": "4"
},
{
"P_ID": "133",
"P_NAME": "游华阳山图",
"P_AUTHOR": "石涛",
"P_DYNASTY": "清",
"P_TYPE": "立轴 纸本 设色 山水",
"P_INFO": "http",
"P_PICS": "yhyst.jpg",
"P_POSTIL": "",
"P_WIDTH": "103.3",
"P_HEIGHT": "239.6",
"P_STAR": "4"
},
{
"P_ID": "136",
"P_NAME": "山高水长图",
"P_AUTHOR": "石谿",
"P_DYNASTY": "清",
"P_TYPE": "立轴 纸本 设色 山水",
"P_INFO": "http",
"P_PICS": "sgsct.jpg",
"P_POSTIL": "",
"P_WIDTH": "127.8",
"P_HEIGHT": "322.1",
"P_STAR": "4"
},
{
"P_ID": "140",
"P_NAME": "醉钟馗图",
"P_AUTHOR": "罗聘",
"P_DYNASTY": "清",
"P_TYPE": "立轴 纸本 设色 人物",
"P_INFO": "http",
"P_PICS": "zzkt.jpg",
"P_POSTIL": "",
"P_WIDTH": "39",
"P_HEIGHT": "57",
"P_STAR": "4"
},
{
"P_ID": "149",
"P_NAME": "蔬鱼图",
"P_AUTHOR": "虚谷",
"P_DYNASTY": "清",
"P_TYPE": "册页 纸本 设色",
"P_INFO": "http",
"P_PICS": "syt.jpg",
"P_POSTIL": "",
"P_WIDTH": "42.1",
"P_HEIGHT": "34",
"P_STAR": "4"
},
{
"P_ID": "146",
"P_NAME": "八骏图",
"P_AUTHOR": "郎世宁",
"P_DYNASTY": "清",
"P_TYPE": "立轴 绢本 设色",
"P_INFO": "http",
"P_PICS": "bajt.jpg",
"P_POSTIL": "",
"P_WIDTH": "139.3",
"P_HEIGHT": "80.2",
"P_STAR": "4"
},
{
"P_ID": "147",
"P_NAME": "百骏图",
"P_AUTHOR": "郎世宁",
"P_DYNASTY": "清",
"P_TYPE": "卷轴 设色",
"P_INFO": "http",
"P_PICS": "baijt.jpg",
"P_POSTIL": "",
"P_WIDTH": "813",
"P_HEIGHT": "102",
"P_STAR": "5"
},
{
"P_ID": "145",
"P_NAME": "仙萼长春图",
"P_AUTHOR": "郎世宁",
"P_DYNASTY": "清",
"P_TYPE": "绢本 设色 花鸟",
"P_INFO": "http",
"P_PICS": "xecct.jpg",
"P_POSTIL": "",
"P_WIDTH": "27.8",
"P_HEIGHT": "33.3",
"P_STAR": "4"
},
{
"P_ID": "139",
"P_NAME": "竹石图",
"P_AUTHOR": "郑燮",
"P_DYNASTY": "清",
"P_TYPE": "立轴 纸本 水墨",
"P_INFO": "http",
"P_PICS": "zst.jpg",
"P_POSTIL": "",
"P_WIDTH": "90",
"P_HEIGHT": "170",
"P_STAR": "4"
},
{
"P_ID": "141",
"P_NAME": "观荷图",
"P_AUTHOR": "金农",
"P_DYNASTY": "清",
"P_TYPE": "册页 纸本 设色",
"P_INFO": "http",
"P_PICS": "ght.jpg",
"P_POSTIL": "",
"P_WIDTH": "24",
"P_HEIGHT": "28",
"P_STAR": "4"
},
{
"P_ID": "316",
"P_NAME": "苍翠凌天图",
"P_AUTHOR": "髡残",
"P_DYNASTY": "清",
"P_TYPE": "立轴 纸本 设色 山水",
"P_INFO": "http",
"P_PICS": "cclty.jpg",
"P_POSTIL": "",
"P_WIDTH": "40.5",
"P_HEIGHT": "85",
"P_STAR": "4"
},
{
"P_ID": "274",
"P_NAME": "圣方济各向鸟雀布道",
"P_AUTHOR": "乔托",
"P_DYNASTY": "文艺复兴",
"P_TYPE": "壁画 人物 宗教 花鸟",
"P_INFO": "http",
"P_PICS": "sfjgxnqbd.jpg",
"P_POSTIL": "",
"P_WIDTH": "200",
"P_HEIGHT": "270",
"P_STAR": "4"
},
{
"P_ID": "273",
"P_NAME": "挪亚之梦",
"P_AUTHOR": "乔托",
"P_DYNASTY": "文艺复兴",
"P_TYPE": "壁画 人物 宗教",
"P_INFO": "http",
"P_PICS": "nyzm.jpg",
"P_POSTIL": "",
"P_WIDTH": "200",
"P_HEIGHT": "185",
"P_STAR": "4"
},
{
"P_ID": "261",
"P_NAME": "逐出乐园",
"P_AUTHOR": "马萨乔",
"P_DYNASTY": "文艺复兴",
"P_TYPE": "壁画 人物 宗教",
"P_INFO": "http",
"P_PICS": "zcly.jpg",
"P_POSTIL": "",
"P_WIDTH": "208",
"P_HEIGHT": "88",
"P_STAR": "4"
},
{
"P_ID": "221",
"P_NAME": "包着红头巾的男子",
"P_AUTHOR": "凡·艾克",
"P_DYNASTY": "文艺复兴",
"P_TYPE": "布面 油彩 人物",
"P_INFO": "http",
"P_PICS": "bzhtjdnz.jpg",
"P_POSTIL": "",
"P_WIDTH": "19",
"P_HEIGHT": "26",
"P_STAR": "4"
},
{
"P_ID": "198",
"P_NAME": "阿尔诺芬尼夫妇像",
"P_AUTHOR": "凡·艾克",
"P_DYNASTY": "文艺复兴",
"P_TYPE": "木板 油彩 人物",
"P_INFO": "http",
"P_PICS": "aenfnffx.jpg",
"P_POSTIL": "",
"P_WIDTH": "57",
"P_HEIGHT": "83",
"P_STAR": "5"
},
{
"P_ID": "275",
"P_NAME": "天使报喜",
"P_AUTHOR": "安吉利科",
"P_DYNASTY": "文艺复兴",
"P_TYPE": "壁画 人物 宗教",
"P_INFO": "http",
"P_PICS": "tsbx.jpg",
"P_POSTIL": "",
"P_WIDTH": "321",
"P_HEIGHT": "230",
"P_STAR": "4"
},
{
"P_ID": "276",
"P_NAME": "诞生图",
"P_AUTHOR": "弗兰西斯加",
"P_DYNASTY": "文艺复兴",
"P_TYPE": "木板 油彩 人物 宗教",
"P_INFO": "http",
"P_PICS": "dst.jpg",
"P_POSTIL": "",
"P_WIDTH": "123",
"P_HEIGHT": "124",
"P_STAR": "4"
},
{
"P_ID": "203",
"P_NAME": "春",
"P_AUTHOR": "波提切利",
"P_DYNASTY": "文艺复兴",
"P_TYPE": "木板 蛋彩 人物",
"P_INFO": "http",
"P_PICS": "chun.jpg",
"P_POSTIL": "",
"P_WIDTH": "314",
"P_HEIGHT": "203",
"P_STAR": "5"
},
{
"P_ID": "202",
"P_NAME": "维纳斯的诞生",
"P_AUTHOR": "波提切利",
"P_DYNASTY": "文艺复兴",
"P_TYPE": "布面 蛋彩 人物",
"P_INFO": "http",
"P_PICS": "wnsdds.jpg",
"P_POSTIL": "",
"P_WIDTH": "278.5",
"P_HEIGHT": "172.5",
"P_STAR": "5"
},
{
"P_ID": "262",
"P_NAME": "哀悼基督",
"P_AUTHOR": "波提切利",
"P_DYNASTY": "文艺复兴",
"P_TYPE": "木板 蛋彩 人物 宗教",
"P_INFO": "http",
"P_PICS": "adjd.jpg",
"P_POSTIL": "",
"P_WIDTH": "182",
"P_HEIGHT": "66",
"P_STAR": "4"
},
{
"P_ID": "204",
"P_NAME": "人间乐园",
"P_AUTHOR": "博斯",
"P_DYNASTY": "文艺复兴",
"P_TYPE": "木板 油彩 人物",
"P_INFO": "http",
"P_PICS": "rjly.jpg",
"P_POSTIL": "",
"P_WIDTH": "389",
"P_HEIGHT": "220",
"P_STAR": "4"
},
{
"P_ID": "193",
"P_NAME": "最后的晚餐",
"P_AUTHOR": "达·芬奇",
"P_DYNASTY": "文艺复兴",
"P_TYPE": "壁画 人物 宗教",
"P_INFO": "http",
"P_PICS": "zhdwc.jpg",
"P_POSTIL": "",
"P_WIDTH": "880",
"P_HEIGHT": "460",
"P_STAR": "5"
},
{
"P_ID": "226",
"P_NAME": "抱银鼠的女子",
"P_AUTHOR": "达·芬奇",
"P_DYNASTY": "文艺复兴",
"P_TYPE": "布面 油彩 人物",
"P_INFO": "http",
"P_PICS": "bysdnz.jpg",
"P_POSTIL": "",
"P_WIDTH": "39",
"P_HEIGHT": "54",
"P_STAR": "4"
},
{
"P_ID": "192",
"P_NAME": "蒙娜丽莎",
"P_AUTHOR": "达·芬奇",
"P_DYNASTY": "文艺复兴",
"P_TYPE": "木板 油彩 人物",
"P_INFO": "http",
"P_PICS": "mnls.jpg",
"P_POSTIL": "",
"P_WIDTH": "53",
"P_HEIGHT": "77",
"P_STAR": "5"
},
{
"P_ID": "337",
"P_NAME": "岩间圣母",
"P_AUTHOR": "达·芬奇",
"P_DYNASTY": "文艺复兴",
"P_TYPE": "布面 油彩 人物 宗教",
"P_INFO": "http",
"P_PICS": "yjsm.jpg",
"P_POSTIL": "",
"P_WIDTH": "123",
"P_HEIGHT": "198",
"P_STAR": "4"
},
{
"P_ID": "267",
"P_NAME": "兔",
"P_AUTHOR": "丢勒",
"P_DYNASTY": "文艺复兴",
"P_TYPE": "纸本 水彩 动物",
"P_INFO": "http",
"P_PICS": "tu.jpg",
"P_POSTIL": "",
"P_WIDTH": "23",
"P_HEIGHT": "25",
"P_STAR": "4"
},
{
"P_ID": "263",
"P_NAME": "暴风雨",
"P_AUTHOR": "乔尔乔涅",
"P_DYNASTY": "文艺复兴",
"P_TYPE": "布面 油彩 人物",
"P_INFO": "http",
"P_PICS": "bfy.jpg",
"P_POSTIL": "",
"P_WIDTH": "73",
"P_HEIGHT": "79.5",
"P_STAR": "4"
},
{
"P_ID": "264",
"P_NAME": "乡间音乐会",
"P_AUTHOR": "乔尔乔涅",
"P_DYNASTY": "文艺复兴",
"P_TYPE": "布面 油彩 人物",
"P_INFO": "http",
"P_PICS": "xjyyh.jpg",
"P_POSTIL": "",
"P_WIDTH": "138",
"P_HEIGHT": "110",
"P_STAR": "4"
},
{
"P_ID": "197",
"P_NAME": "圣母圣婴图",
"P_AUTHOR": "拉斐尔",
"P_DYNASTY": "文艺复兴",
"P_TYPE": "布面 油彩 人物 宗教",
"P_INFO": "img",
"P_PICS": "smsyt.jpg",
"P_POSTIL": "",
"P_WIDTH": "80",
"P_HEIGHT": "122",
"P_STAR": "4"
},
{
"P_ID": "196",
"P_NAME": "雅典学派",
"P_AUTHOR": "拉斐尔",
"P_DYNASTY": "文艺复兴",
"P_TYPE": "壁画 人物",
"P_INFO": "http",
"P_PICS": "ydxp.jpg",
"P_POSTIL": "",
"P_WIDTH": "617.2",
"P_HEIGHT": "279.4",
"P_STAR": "5"
},
{
"P_ID": "194",
"P_NAME": "创世纪",
"P_AUTHOR": "米开朗琪罗",
"P_DYNASTY": "文艺复兴",
"P_TYPE": "壁画 人物 宗教",
"P_INFO": "http",
"P_PICS": "csj.jpg",
"P_POSTIL": "",
"P_WIDTH": "",
"P_HEIGHT": "",
"P_STAR": "5"
},
{
"P_ID": "195",
"P_NAME": "最后的审判",
"P_AUTHOR": "米开朗琪罗",
"P_DYNASTY": "文艺复兴",
"P_TYPE": "壁画 人物 宗教",
"P_INFO": "http",
"P_PICS": "zhdsp.jpg",
"P_POSTIL": "",
"P_WIDTH": "1220",
"P_HEIGHT": "1370",
"P_STAR": "4"
},
{
"P_ID": "199",
"P_NAME": "大使",
"P_AUTHOR": "霍尔拜因",
"P_DYNASTY": "文艺复兴",
"P_TYPE": "木板 油彩 人物",
"P_INFO": "http",
"P_PICS": "ds.jpg",
"P_POSTIL": "",
"P_WIDTH": "206",
"P_HEIGHT": "209",
"P_STAR": "4"
},
{
"P_ID": "265",
"P_NAME": "乌比诺的维纳斯",
"P_AUTHOR": "提香",
"P_DYNASTY": "文艺复兴",
"P_TYPE": "布面 油彩 人物",
"P_INFO": "http",
"P_PICS": "wbrdwns.jpg",
"P_POSTIL": "",
"P_WIDTH": "165",
"P_HEIGHT": "119",
"P_STAR": "4"
},
{
"P_ID": "206",
"P_NAME": "雪中猎人",
"P_AUTHOR": "勃鲁盖尔",
"P_DYNASTY": "文艺复兴",
"P_TYPE": "木板 油彩 人物",
"P_INFO": "http",
"P_PICS": "xzlr.jpg",
"P_POSTIL": "",
"P_WIDTH": "162",
"P_HEIGHT": "117",
"P_STAR": "4"
},
{
"P_ID": "205",
"P_NAME": "农民婚礼",
"P_AUTHOR": "勃鲁盖尔",
"P_DYNASTY": "文艺复兴",
"P_TYPE": "木板 油彩 人物",
"P_INFO": "http",
"P_PICS": "nmhl.jpg",
"P_POSTIL": "",
"P_WIDTH": "163",
"P_HEIGHT": "114",
"P_STAR": "4"
},
{
"P_ID": "266",
"P_NAME": "利未家的宴会",
"P_AUTHOR": "韦罗内塞",
"P_DYNASTY": "文艺复兴",
"P_TYPE": "布面 油彩 人物",
"P_INFO": "http",
"P_PICS": "lwjdyh.jpg",
"P_POSTIL": "",
"P_WIDTH": "1280",
"P_HEIGHT": "555",
"P_STAR": "4"
},
{
"P_ID": "268",
"P_NAME": "托莱多风景",
"P_AUTHOR": "格列柯",
"P_DYNASTY": "文艺复兴",
"P_TYPE": "布面 油彩",
"P_INFO": "http",
"P_PICS": "tldfj.jpg",
"P_POSTIL": "",
"P_WIDTH": "109",
"P_HEIGHT": "121",
"P_STAR": "4"
},
{
"P_ID": "200",
"P_NAME": "酒神",
"P_AUTHOR": "卡拉瓦乔",
"P_DYNASTY": "文艺复兴",
"P_TYPE": "布面 油彩 人物",
"P_INFO": "http",
"P_PICS": "js.jpg",
"P_POSTIL": "",
"P_WIDTH": "85",
"P_HEIGHT": "95",
"P_STAR": "4"
},
{
"P_ID": "201",
"P_NAME": "圣马太蒙召",
"P_AUTHOR": "卡拉瓦乔",
"P_DYNASTY": "文艺复兴",
"P_TYPE": "布面 油彩 人物 宗教",
"P_INFO": "http",
"P_PICS": "smtmz.jpg",
"P_POSTIL": "",
"P_WIDTH": "340",
"P_HEIGHT": "322",
"P_STAR": "5"
},
{
"P_ID": "269",
"P_NAME": "圣保罗的皈依",
"P_AUTHOR": "卡拉瓦乔",
"P_DYNASTY": "文艺复兴",
"P_TYPE": "布面 油彩 人物 宗教",
"P_INFO": "http",
"P_PICS": "sbldgy.jpg",
"P_POSTIL": "",
"P_WIDTH": "175",
"P_HEIGHT": "230",
"P_STAR": "4"
},
{
"P_ID": "216",
"P_NAME": "基督下十字架",
"P_AUTHOR": "鲁本斯",
"P_DYNASTY": "17世纪",
"P_TYPE": "布面 油彩 人物 宗教",
"P_INFO": "http",
"P_PICS": "jdxszj.jpg",
"P_POSTIL": "",
"P_WIDTH": "295",
"P_HEIGHT": "425",
"P_STAR": "4"
},
{
"P_ID": "215",
"P_NAME": "抢夺留希波斯的女儿们",
"P_AUTHOR": "鲁本斯",
"P_DYNASTY": "17世纪",
"P_TYPE": "布面 油彩 人物",
"P_INFO": "http",
"P_PICS": "lbxs.jpg",
"P_POSTIL": "",
"P_WIDTH": "209",
"P_HEIGHT": "222",
"P_STAR": "4"
},
{
"P_ID": "213",
"P_NAME": "玛丽·美第奇抵达马赛",
"P_AUTHOR": "鲁本斯",
"P_DYNASTY": "17世纪",
"P_TYPE": "布面 油彩 人物",
"P_INFO": "http",
"P_PICS": "mdqddms.jpg",
"P_POSTIL": "",
"P_WIDTH": "295",
"P_HEIGHT": "394",
"P_STAR": "4"
},
{
"P_ID": "218",
"P_NAME": "杜普教授的解剖课",
"P_AUTHOR": "伦勃朗",
"P_DYNASTY": "17世纪",
"P_TYPE": "布面 油彩 人物",
"P_INFO": "http",
"P_PICS": "dpjsdjpk.jpg",
"P_POSTIL": "",
"P_WIDTH": "216.5",
"P_HEIGHT": "162.5",
"P_STAR": "4"
},
{
"P_ID": "208",
"P_NAME": "夜巡",
"P_AUTHOR": "伦勃朗",
"P_DYNASTY": "17世纪",
"P_TYPE": "布面 油彩 人物",
"P_INFO": "http",
"P_PICS": "yx.jpg",
"P_POSTIL": "",
"P_WIDTH": "435",
"P_HEIGHT": "359",
"P_STAR": "5"
},
{
"P_ID": "270",
"P_NAME": "塞维利亚的卖水人",
"P_AUTHOR": "委拉斯凯兹",
"P_DYNASTY": "17世纪",
"P_TYPE": "布面 油彩 人物",
"P_INFO": "http",
"P_PICS": "swlydmsr.jpg",
"P_POSTIL": "",
"P_WIDTH": "80",
"P_HEIGHT": "105",
"P_STAR": "4"
},
{
"P_ID": "334",
"P_NAME": "教皇英诺森十世肖像",
"P_AUTHOR": "委拉斯凯兹",
"P_DYNASTY": "17世纪",
"P_TYPE": "布面 油彩 人物",
"P_INFO": "http",
"P_PICS": "jhynsss.jpg",
"P_POSTIL": "",
"P_WIDTH": "119",
"P_HEIGHT": "141",
"P_STAR": "4"
},
{
"P_ID": "207",
"P_NAME": "宫娥",
"P_AUTHOR": "委拉斯凯兹",
"P_DYNASTY": "17世纪",
"P_TYPE": "布面 油彩 人物",
"P_INFO": "http",
"P_PICS": "ge.jpg",
"P_POSTIL": "",
"P_WIDTH": "278",
"P_HEIGHT": "318",
"P_STAR": "4"
},
{
"P_ID": "217",
"P_NAME": "公主像",
"P_AUTHOR": "委拉斯凯兹",
"P_DYNASTY": "17世纪",
"P_TYPE": "布面 油彩 人物",
"P_INFO": "http",
"P_PICS": "gzx.jpg",
"P_POSTIL": "",
"P_WIDTH": "88",
"P_HEIGHT": "105",
"P_STAR": "4"
},
{
"P_ID": "271",
"P_NAME": "阿卡迪亚的牧人",
"P_AUTHOR": "普桑",
"P_DYNASTY": "17世纪",
"P_TYPE": "布面 油彩 人物",
"P_INFO": "http",
"P_PICS": "akdydmr.jpg",
"P_POSTIL": "",
"P_WIDTH": "98",
"P_HEIGHT": "74",
"P_STAR": "4"
},
{
"P_ID": "249",
"P_NAME": "倒牛奶的女佣人",
"P_AUTHOR": "弗美尔",
"P_DYNASTY": "17世纪",
"P_TYPE": "布面 油彩 人物",
"P_INFO": "http",
"P_PICS": "dnndnyr.jpg",
"P_POSTIL": "",
"P_WIDTH": "41",
"P_HEIGHT": "45",
"P_STAR": "4"
},
{
"P_ID": "220",
"P_NAME": "手持水罐的女子",
"P_AUTHOR": "弗美尔",
"P_DYNASTY": "17世纪",
"P_TYPE": "布面 油彩 人物",
"P_INFO": "http",
"P_PICS": "scsgdnz.jpg",
"P_POSTIL": "",
"P_WIDTH": "40.5",
"P_HEIGHT": "45.5",
"P_STAR": "4"
},
{
"P_ID": "219",
"P_NAME": "看信的女人",
"P_AUTHOR": "弗美尔",
"P_DYNASTY": "17世纪",
"P_TYPE": "布面 油彩 人物",
"P_INFO": "http",
"P_PICS": "kxdnr.jpg",
"P_POSTIL": "",
"P_WIDTH": "39",
"P_HEIGHT": "46.5",
"P_STAR": "4"
},
{
"P_ID": "227",
"P_NAME": "戴珍珠耳环的少女",
"P_AUTHOR": "维米尔",
"P_DYNASTY": "17世纪",
"P_TYPE": "布面 油彩 人物",
"P_INFO": "http",
"P_PICS": "dzzehdsn.jpg",
"P_POSTIL": "",
"P_WIDTH": "39",
"P_HEIGHT": "44.5",
"P_STAR": "5"
},
{
"P_ID": "272",
"P_NAME": "森林风景",
"P_AUTHOR": "洛兰",
"P_DYNASTY": "17世纪",
"P_TYPE": "纸本 水彩",
"P_INFO": "http",
"P_PICS": "slfj.jpg",
"P_POSTIL": "",
"P_WIDTH": "25.5",
"P_HEIGHT": "39",
"P_STAR": "4"
},
{
"P_ID": "260",
"P_NAME": "小丑",
"P_AUTHOR": "华托",
"P_DYNASTY": "18世纪",
"P_TYPE": "布面 油彩 人物",
"P_INFO": "http",
"P_PICS": "xc.jpg",
"P_POSTIL": "",
"P_WIDTH": "149",
"P_HEIGHT": "184",
"P_STAR": "4"
},
{
"P_ID": "259",
"P_NAME": "水瓮",
"P_AUTHOR": "夏尔丹",
"P_DYNASTY": "18世纪",
"P_TYPE": "木板 油彩 人物",
"P_INFO": "http",
"P_PICS": "sw.jpg",
"P_POSTIL": "",
"P_WIDTH": "45",
"P_HEIGHT": "38",
"P_STAR": "4"
},
{
"P_ID": "225",
"P_NAME": "吹肥皂泡的少年",
"P_AUTHOR": "夏尔丹",
"P_DYNASTY": "18世纪",
"P_TYPE": "布面 油彩 人物",
"P_INFO": "http",
"P_PICS": "cfzpdsm.jpg",
"P_POSTIL": "",
"P_WIDTH": "70",
"P_HEIGHT": "88",
"P_STAR": "5"
},
{
"P_ID": "258",
"P_NAME": "配膳桌",
"P_AUTHOR": "夏尔丹",
"P_DYNASTY": "18世纪",
"P_TYPE": "布面 油彩",
"P_INFO": "http",
"P_PICS": "psz.jpg",
"P_POSTIL": "",
"P_WIDTH": "46",
"P_HEIGHT": "38",
"P_STAR": "4"
},
{
"P_ID": "255",
"P_NAME": "少女与猫",
"P_AUTHOR": "佩宏诺",
"P_DYNASTY": "18世纪",
"P_TYPE": "布面 油彩 人物",
"P_INFO": "http",
"P_PICS": "snym.jpg",
"P_POSTIL": "",
"P_WIDTH": "20",
"P_HEIGHT": "23",
"P_STAR": "4"
},
{
"P_ID": "209",
"P_NAME": "荷拉斯兄弟之誓",
"P_AUTHOR": "大卫",
"P_DYNASTY": "18世纪",
"P_TYPE": "布面 油彩 人物",
"P_INFO": "http",
"P_PICS": "hlsxdzs.jpg",
"P_POSTIL": "",
"P_WIDTH": "427",
"P_HEIGHT": "330",
"P_STAR": "5"
},
{
"P_ID": "210",
"P_NAME": "马拉之死",
"P_AUTHOR": "大卫",
"P_DYNASTY": "18世纪",
"P_TYPE": "布面 油彩 人物",
"P_INFO": "http",
"P_PICS": "mlzs.jpg",
"P_POSTIL": "",
"P_WIDTH": "128.3",
"P_HEIGHT": "165",
"P_STAR": "5"
},
{
"P_ID": "212",
"P_NAME": "拿破仑越过阿尔卑斯山",
"P_AUTHOR": "大卫",
"P_DYNASTY": "18世纪",
"P_TYPE": "布面 油彩 人物",
"P_INFO": "http",
"P_PICS": "nplygarbss.jpg",
"P_POSTIL": "",
"P_WIDTH": "232",
"P_HEIGHT": "271",
"P_STAR": "4"
},
{
"P_ID": "211",
"P_NAME": "拿破仑加冕",
"P_AUTHOR": "大卫",
"P_DYNASTY": "18世纪",
"P_TYPE": "布面 油彩 人物",
"P_INFO": "http",
"P_PICS": "npljm.jpg",
"P_POSTIL": "",
"P_WIDTH": "931",
"P_HEIGHT": "610",
"P_STAR": "4"
},
{
"P_ID": "257",
"P_NAME": "嬉戏者",
"P_AUTHOR": "戈雅",
"P_DYNASTY": "18世纪",
"P_TYPE": "布面 油彩 人物",
"P_INFO": "http",
"P_PICS": "xxz.jpg",
"P_POSTIL": "",
"P_WIDTH": "350",
"P_HEIGHT": "269",
"P_STAR": "4"
},
{
"P_ID": "223",
"P_NAME": "1808年5月3日",
"P_AUTHOR": "戈雅",
"P_DYNASTY": "18世纪",
"P_TYPE": "布面 油彩 人物",
"P_INFO": "http",
"P_PICS": "18080503.jpg",
"P_POSTIL": "",
"P_WIDTH": "406",
"P_HEIGHT": "267",
"P_STAR": "4"
},
{
"P_ID": "253",
"P_NAME": "阿尔卑斯山的雪崩",
"P_AUTHOR": "卢泰尔堡",
"P_DYNASTY": "18世纪",
"P_TYPE": "布面 油彩 山水",
"P_INFO": "http",
"P_PICS": "aebssdxb.jpg",
"P_POSTIL": "",
"P_WIDTH": "160",
"P_HEIGHT": "109.9",
"P_STAR": "4"
},
{
"P_ID": "252",
"P_NAME": "瓦平松的浴女",
"P_AUTHOR": "安格尔",
"P_DYNASTY": "18世纪",
"P_TYPE": "布面 油彩 人物",
"P_INFO": "http",
"P_PICS": "apsdyn.jpg",
"P_POSTIL": "",
"P_WIDTH": "97.5",
"P_HEIGHT": "146",
"P_STAR": "4"
},
{
"P_ID": "222",
"P_NAME": "大宫女",
"P_AUTHOR": "安格尔",
"P_DYNASTY": "18世纪",
"P_TYPE": "布面 油彩 人物",
"P_INFO": "http",
"P_PICS": "dgn.jpg",
"P_POSTIL": "",
"P_WIDTH": "162",
"P_HEIGHT": "91",
"P_STAR": "4"
},
{
"P_ID": "214",
"P_NAME": "梅杜萨之筏",
"P_AUTHOR": "籍里柯",
"P_DYNASTY": "18世纪",
"P_TYPE": "布面 油彩 人物",
"P_INFO": "http",
"P_PICS": "mdszf.jpg",
"P_POSTIL": "",
"P_WIDTH": "716",
"P_HEIGHT": "491",
"P_STAR": "5"
},
{
"P_ID": "333",
"P_NAME": "肯特海滩",
"P_AUTHOR": "泰奥多尔·居丹",
"P_DYNASTY": "19世纪",
"P_TYPE": "布面 油彩",
"P_INFO": "http",
"P_PICS": "ktht.jpg",
"P_POSTIL": "",
"P_WIDTH": "420",
"P_HEIGHT": "264",
"P_STAR": "4"
},
{
"P_ID": "224",
"P_NAME": "自由引导人民",
"P_AUTHOR": "德拉克罗瓦",
"P_DYNASTY": "19世纪",
"P_TYPE": "布面 油彩 人物",
"P_INFO": "http",
"P_PICS": "zyydrm.jpg",
"P_POSTIL": "",
"P_WIDTH": "325",
"P_HEIGHT": "260",
"P_STAR": "5"
},
{
"P_ID": "248",
"P_NAME": "枫丹白露森林",
"P_AUTHOR": "柯罗",
"P_DYNASTY": "19世纪",
"P_TYPE": "布面 油彩 山水",
"P_INFO": "http",
"P_PICS": "fdblsl.jpg",
"P_POSTIL": "",
"P_WIDTH": "242.5",
"P_HEIGHT": "175.5",
"P_STAR": "4"
},
{
"P_ID": "247",
"P_NAME": "珍珠女",
"P_AUTHOR": "柯罗",
"P_DYNASTY": "19世纪",
"P_TYPE": "布面 油彩 人物",
"P_INFO": "http",
"P_PICS": "zzn.jpg",
"P_POSTIL": "",
"P_WIDTH": "50",
"P_HEIGHT": "62",
"P_STAR": "4"
},
{
"P_ID": "234",
"P_NAME": "筛谷的妇女",
"P_AUTHOR": "库尔贝",
"P_DYNASTY": "19世纪",
"P_TYPE": "布面 油彩 人物",
"P_INFO": "http",
"P_PICS": "sgdfn.jpg",
"P_POSTIL": "",
"P_WIDTH": "167",
"P_HEIGHT": "131",
"P_STAR": "4"
},
{
"P_ID": "246",
"P_NAME": "画室",
"P_AUTHOR": "库尔贝",
"P_DYNASTY": "19世纪",
"P_TYPE": "布面 油彩 人物",
"P_INFO": "http",
"P_PICS": "hs.jpg",
"P_POSTIL": "",
"P_WIDTH": "600",
"P_HEIGHT": "360",
"P_STAR": "4"
},
{
"P_ID": "230",
"P_NAME": "播种者",
"P_AUTHOR": "米勒",
"P_DYNASTY": "19世纪",
"P_TYPE": "布面 油彩 人物",
"P_INFO": "http",
"P_PICS": "bzz.jpg",
"P_POSTIL": "",
"P_WIDTH": "82.5",
"P_HEIGHT": "101",
"P_STAR": "4"
},
{
"P_ID": "231",
"P_NAME": "晚钟",
"P_AUTHOR": "米勒",
"P_DYNASTY": "19世纪",
"P_TYPE": "布面 油彩 人物",
"P_INFO": "http",
"P_PICS": "wz.jpg",
"P_POSTIL": "",
"P_WIDTH": "66",
"P_HEIGHT": "55",
"P_STAR": "4"
},
{
"P_ID": "232",
"P_NAME": "拾穗者",
"P_AUTHOR": "米勒",
"P_DYNASTY": "19世纪",
"P_TYPE": "布面 油彩 人物",
"P_INFO": "http",
"P_PICS": "ssz.jpg",
"P_POSTIL": "",
"P_WIDTH": "111",
"P_HEIGHT": "83.5",
"P_STAR": "5"
},
{
"P_ID": "233",
"P_NAME": "三等车厢",
"P_AUTHOR": "杜米埃",
"P_DYNASTY": "19世纪",
"P_TYPE": "布面 油彩 人物",
"P_INFO": "http",
"P_PICS": "sdcx.jpg",
"P_POSTIL": "",
"P_WIDTH": "90.2",
"P_HEIGHT": "65.4",
"P_STAR": "4"
},
{
"P_ID": "251",
"P_NAME": "吹笛少年",
"P_AUTHOR": "马奈",
"P_DYNASTY": "19世纪",
"P_TYPE": "布面 油彩 人物",
"P_INFO": "http",
"P_PICS": "cdsn.jpg",
"P_POSTIL": "",
"P_WIDTH": "98",
"P_HEIGHT": "160",
"P_STAR": "4"
},
{
"P_ID": "235",
"P_NAME": "草地上的午餐",
"P_AUTHOR": "马奈",
"P_DYNASTY": "19世纪",
"P_TYPE": "布面 油彩 人物",
"P_INFO": "http",
"P_PICS": "cdsdwc.jpg",
"P_POSTIL": "",
"P_WIDTH": "265.5",
"P_HEIGHT": "208",
"P_STAR": "4"
},
{
"P_ID": "229",
"P_NAME": "福利·贝热尔的吧台",
"P_AUTHOR": "马奈",
"P_DYNASTY": "19世纪",
"P_TYPE": "布面 油彩 人物",
"P_INFO": "http",
"P_PICS": "bredbt.jpg",
"P_POSTIL": "",
"P_WIDTH": "130.2",
"P_HEIGHT": "95.9",
"P_STAR": "4"
},
{
"P_ID": "228",
"P_NAME": "伏尔加河上的纤夫",
"P_AUTHOR": "列宾",
"P_DYNASTY": "19世纪",
"P_TYPE": "布面 油彩 人物",
"P_INFO": "http",
"P_PICS": "fejhsdqf.jpg",
"P_POSTIL": "",
"P_WIDTH": "281",
"P_HEIGHT": "131.5",
"P_STAR": "4"
},
{
"P_ID": "335",
"P_NAME": "意外归来",
"P_AUTHOR": "列宾",
"P_DYNASTY": "19世纪",
"P_TYPE": "布面 油彩 人物",
"P_INFO": "http",
"P_PICS": "ywgl.jpg",
"P_POSTIL": "",
"P_WIDTH": "167.5",
"P_HEIGHT": "160.5",
"P_STAR": "4"
},
{
"P_ID": "256",
"P_NAME": "第聂伯河上的月夜",
"P_AUTHOR": "库因芝",
"P_DYNASTY": "19世纪",
"P_TYPE": "布面 油彩 山水",
"P_INFO": "http",
"P_PICS": "snbhsdyy.jpg",
"P_POSTIL": "",
"P_WIDTH": "144",
"P_HEIGHT": "105",
"P_STAR": "4"
},
{
"P_ID": "245",
"P_NAME": "煎饼磨坊的舞会",
"P_AUTHOR": "雷诺阿",
"P_DYNASTY": "19世纪",
"P_TYPE": "布面 油彩 人物",
"P_INFO": "http",
"P_PICS": "jbmfdwh.jpg",
"P_POSTIL": "",
"P_WIDTH": "175",
"P_HEIGHT": "131",
"P_STAR": "4"
},
{
"P_ID": "254",
"P_NAME": "雷诺阿画伞",
"P_AUTHOR": "雷诺阿",
"P_DYNASTY": "19世纪",
"P_TYPE": "布面 油彩 人物",
"P_INFO": "http",
"P_PICS": "lnahs.jpg",
"P_POSTIL": "",
"P_WIDTH": "113",
"P_HEIGHT": "179",
"P_STAR": "4"
},
{
"P_ID": "336",
"P_NAME": "布吉瓦的舞会",
"P_AUTHOR": "雷诺阿",
"P_DYNASTY": "19世纪",
"P_TYPE": "布面 油彩 人物",
"P_INFO": "http",
"P_PICS": "bjwdwh.jpg",
"P_POSTIL": "",
"P_WIDTH": "98.1",
"P_HEIGHT": "181.9",
"P_STAR": "4"
},
{
"P_ID": "244",
"P_NAME": "大碗岛星期天的下午",
"P_AUTHOR": "修拉",
"P_DYNASTY": "19世纪",
"P_TYPE": "布面 油彩 人物",
"P_INFO": "http",
"P_PICS": "dwdxqt.jpg",
"P_POSTIL": "",
"P_WIDTH": "308",
"P_HEIGHT": "207",
"P_STAR": "4"
},
{
"P_ID": "236",
"P_NAME": "日出·印象",
"P_AUTHOR": "莫奈",
"P_DYNASTY": "19世纪",
"P_TYPE": "布面 油彩 山水",
"P_INFO": "http",
"P_PICS": "rcyx.jpg",
"P_POSTIL": "",
"P_WIDTH": "63",
"P_HEIGHT": "48",
"P_STAR": "5"
},
{
"P_ID": "250",
"P_NAME": "撑阳伞的女人",
"P_AUTHOR": "莫奈",
"P_DYNASTY": "19世纪",
"P_TYPE": "布面 油彩 人物",
"P_INFO": "http",
"P_PICS": "csdnr.jpg",
"P_POSTIL": "",
"P_WIDTH": "81",
"P_HEIGHT": "100",
"P_STAR": "4"
},
{
"P_ID": "237",
"P_NAME": "睡莲",
"P_AUTHOR": "莫奈",
"P_DYNASTY": "19世纪",
"P_TYPE": "布面 油彩 花鸟",
"P_INFO": "http",
"P_PICS": "sl.jpg",
"P_POSTIL": "",
"P_WIDTH": "73.7",
"P_HEIGHT": "92.7",
"P_STAR": "4"
},
{
"P_ID": "239",
"P_NAME": "向日葵",
"P_AUTHOR": "梵高",
"P_DYNASTY": "19世纪",
"P_TYPE": "布面 油彩 花鸟",
"P_INFO": "http",
"P_PICS": "xrk.jpg",
"P_POSTIL": "",
"P_WIDTH": "72",
"P_HEIGHT": "93",
"P_STAR": "5"
},
{
"P_ID": "240",
"P_NAME": "星夜",
"P_AUTHOR": "梵高",
"P_DYNASTY": "19世纪",
"P_TYPE": "布面 油彩",
"P_INFO": "http",
"P_PICS": "xy.jpg",
"P_POSTIL": "",
"P_WIDTH": "92",
"P_HEIGHT": "73",
"P_STAR": "5"
},
{
"P_ID": "242",
"P_NAME": "呐喊",
"P_AUTHOR": "蒙克",
"P_DYNASTY": "19世纪",
"P_TYPE": "布面 油彩 人物",
"P_INFO": "http",
"P_PICS": "nh.jpg",
"P_POSTIL": "",
"P_WIDTH": "73.5",
"P_HEIGHT": "91",
"P_STAR": "4"
},
{
"P_ID": "241",
"P_NAME": "我们从哪里来",
"P_AUTHOR": "高更",
"P_DYNASTY": "19世纪",
"P_TYPE": "布面 油彩 人物",
"P_INFO": "http",
"P_PICS": "wmcnll.jpg",
"P_POSTIL": "",
"P_WIDTH": "374.6",
"P_HEIGHT": "139.1",
"P_STAR": "4"
},
{
"P_ID": "238",
"P_NAME": "圣维克多山",
"P_AUTHOR": "塞尚",
"P_DYNASTY": "19世纪",
"P_TYPE": "布面 油彩 山水",
"P_INFO": "http",
"P_PICS": "swkds.jpg",
"P_POSTIL": "",
"P_WIDTH": "97.2",
"P_HEIGHT": "52.7",
"P_STAR": "4"
},
{
"P_ID": "243",
"P_NAME": "舞蹈",
"P_AUTHOR": "马蒂斯",
"P_DYNASTY": "19世纪",
"P_TYPE": "布面 油彩 人物",
"P_INFO": "http",
"P_PICS": "wd.jpg",
"P_POSTIL": "",
"P_WIDTH": "391",
"P_HEIGHT": "260",
"P_STAR": "4"
},
{
"P_ID": "287",
"P_NAME": "珊瑚长尾喜鹊图",
"P_AUTHOR": "真加",
"P_DYNASTY": "日本",
"P_TYPE": "纸本 设色 花鸟",
"P_INFO": "img",
"P_PICS": "shcwxqt.jpg",
"P_POSTIL": "",
"P_WIDTH": "35.5",
"P_HEIGHT": "46.3",
"P_STAR": "4"
},
{
"P_ID": "277",
"P_NAME": "神奈川冲浪里",
"P_AUTHOR": "葛饰北斋",
"P_DYNASTY": "日本",
"P_TYPE": "版画",
"P_INFO": "http",
"P_PICS": "snccll.jpg",
"P_POSTIL": "",
"P_WIDTH": "37.9",
"P_HEIGHT": "25.7",
"P_STAR": "5"
}
]
}